# -*- coding: utf-8 -*-
"""Collect every rewritten category into one bank the app can actually load.

    py rewrite/build-preview.py

Writes rewrite/preview-bank.js, which js/rewrite-preview.js pulls in on demand
when the app is opened with ?rewrite. Nothing else loads it: it is roughly a
megabyte and it is a review tool, not a shipped asset.

Why this exists. The rewrite has been verified by ten build checks, a similarity
pass, a cross-category pass and several rounds of LLM fact-checking, and until
now not one of its questions had ever been loaded by the app that will ship
them. Grading, the section menus, the SRS, the review screen and the level
switch have all gone untested against this content. This is the cheapest way to
close that gap and the only way to read the questions the way a student will.

Rank I becomes the Page bank and Rank II the Squire bank. Only rewritten
categories appear, so anything on screen in preview mode is original work; the
sections that have not been written yet are simply absent, and the counts in the
banner say so.
"""

import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "categories"))

import importlib  # noqa: E402

import lib  # noqa: E402

LEVEL_OF = {"Rank I": "intro", "Rank II": "certified"}


def main():
    mods = sorted(f[:-3] for f in os.listdir(os.path.join(HERE, "categories"))
                  if f.endswith(".py") and not f.startswith("_"))

    banks = {"intro": [], "certified": []}
    cats = {"intro": [], "certified": []}

    for name in mods:
        mod = importlib.import_module("categories.%s" % name)
        rank = getattr(mod, "RANK", "Rank I")
        level = LEVEL_OF.get(rank)
        if level is None:
            print("  skip %s: unknown RANK %r" % (name, rank))
            continue

        bank = [dict(e) for e in mod.BANK]
        prefix = getattr(mod, "PREFIX", "i")
        # Exactly what build.py does, so the preview shows the shipped shape:
        # the dealt option order and the real minted ids, not the source order.
        lib.bake_option_order(bank, mod.CAT)

        for e in bank:
            row = {"id": lib.mint(mod.CAT, e["q"], prefix), "cat": mod.CAT, "q": e["q"]}
            if lib.is_mc(e):
                row["opts"] = e["opts"]
                row["a"] = e["a"]
            else:
                row["sa"] = 1
                row["accept"] = e["accept"]
                row["ans"] = e["ans"]
                if e.get("ex"):
                    row["ex"] = 1
            row["exp"] = e["exp"]
            banks[level].append(row)

        cats[level].append({"cat": mod.CAT, "module": name, "n": len(bank)})
        print("  %-30s %-10s %3d" % (mod.CAT, level, len(bank)))

    meta = {
        "intro": {"questions": len(banks["intro"]), "categories": cats["intro"]},
        "certified": {"questions": len(banks["certified"]), "categories": cats["certified"]},
        "total": len(banks["intro"]) + len(banks["certified"]),
    }

    out = io.StringIO()
    out.write("/* ============ rewrite preview bank ============\n")
    out.write("   GENERATED by rewrite/build-preview.py. Do not edit.\n")
    out.write("   Every question here is original work written from a syllabus; none of it\n")
    out.write("   comes from the imported banks. Loaded on demand by js/rewrite-preview.js\n")
    out.write("   when the app is opened with ?rewrite, and by nothing else.\n")
    out.write("   ============ */\n")
    out.write("var REWRITE_PREVIEW={\n")
    out.write(' "meta":%s,\n' % json.dumps(meta, ensure_ascii=False))
    for level in ("intro", "certified"):
        rows = ",\n  ".join(json.dumps(r, ensure_ascii=False) for r in banks[level])
        out.write(' "%s":[\n  %s\n ]%s\n' % (level, rows, "," if level == "intro" else ""))
    out.write("};\n")

    dest = os.path.join(HERE, "preview-bank.js")
    text = out.getvalue()
    io.open(dest, "w", encoding="utf-8", newline="\n").write(text)

    print("\n  Page (Rank I)     %4d questions across %2d categories"
          % (meta["intro"]["questions"], len(cats["intro"])))
    print("  Squire (Rank II)  %4d questions across %2d categories"
          % (meta["certified"]["questions"], len(cats["certified"])))
    print("  total             %4d" % meta["total"])
    print("  wrote %s (%.1f KB)" % (os.path.basename(dest), len(text) / 1024.0))


main()
