# -*- coding: utf-8 -*-
"""Assemble the rewritten study chapters into js/data-primers-intro.js.

    py rewrite/build-primers.py --dry-run
    py rewrite/build-primers.py

Reads rewrite/primers/*.py, checks every chapter, and writes the shipped file in
the original chapter order. The order is taken from ORDER below rather than from
whatever the modules happen to contain, because the chapter list is a course and
a course has a sequence: foundations, then France, then outward.

The file it writes keeps INTRO_CHIP and INTRO_PRIMERS exactly as the engine
expects them. Only the prose inside `body` is new.
"""

import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "primers"))

import importlib  # noqa: E402
import primerlib  # noqa: E402

# group -> module, in course order
ORDER = [
    ("Foundations", "foundations"),
    ("France", "france"),
    ("Italy", "italy"),
    ("Spain", "spain"),
    ("Iberia & Central Europe", "iberia_central"),
    ("North America", "north_america"),
    ("South America & Southern Hemisphere", "southern"),
    ("Across the Cellar", "cellar"),
    ("Beyond Wine", "beyond_wine"),
]

HEADER = """/* ============ Introductory level: 39 study chapters ============
   ORIGINAL WORK. Every chapter was written from a competency list in
   rewrite/primers/, never from the chapter it replaces, and verified against
   that source by rewrite/check-primer-similarity.py.
   GENERATED by rewrite/build-primers.py. Edit the primer module, not this file.
   Each: {g:group, id, t:title, body: HTML}. Rendered by the level engine's
   html-primer branch; ids are structural and must not change.
   ============ */

/* =====================================================================
   STUDY CONTENT
   ===================================================================== */
var INTRO_CHIP = function(c){ return '<span class="chip">'+c+'</span>'; };
"""


def collect():
    chapters, missing = [], []
    for group, modname in ORDER:
        try:
            mod = importlib.import_module(modname)
        except ImportError:
            missing.append((group, modname))
            continue
        for ch in mod.CHAPTERS:
            if ch["g"] != group:
                raise SystemExit("%s declares group %r, expected %r"
                                 % (modname, ch["g"], group))
            chapters.append(ch)
    return chapters, missing


def main(argv):
    dry = "--dry-run" in argv
    chapters, missing = collect()

    seen, bad = set(), []
    for ch in chapters:
        bad += primerlib.problems(ch, seen)
        seen.add(ch["id"])

    print("")
    print("  chapters   %d written" % len(chapters))
    if missing:
        print("  missing    %d group(s) not yet started:" % len(missing))
        for g, m in missing:
            print("               %-36s rewrite/primers/%s.py" % (g, m))
    if bad:
        print("")
        print("  PROBLEMS:")
        for b in bad:
            print("   - %s" % b)
        return 1
    print("  checks     all passed")

    if missing:
        print("")
        print("  not writing: the file ships all 39 or none.")
        return 1

    rows = []
    for ch in chapters:
        rows.append(' {g:"%s", id:"%s", t:"%s", body:`\n%s\n `}'
                    % (ch["g"], ch["id"], ch["t"], ch["body"]))
    text = HEADER + "var INTRO_PRIMERS = [\n" + ",\n".join(rows) + "\n];\n"

    dest = os.path.join(REPO, "js", "data-primers-intro.js")
    print("  output     %s (%.0f KB)" % (os.path.relpath(dest, REPO), len(text) / 1024.0))
    if dry:
        print("")
        print("  DRY RUN, nothing written.")
        return 0
    io.open(dest, "w", encoding="utf-8", newline="\n").write(text)
    print("  written.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
