# -*- coding: utf-8 -*-
"""Reviewed verdicts on paid-bank check flags. See check-paid.py.

Each entry is (bank, check, problem text) that a human read and judged not
worth closing — usually because the close would cost a correct answer. This
is a record of decisions, not a way to silence the checker: anything not
listed here fails the gate.
"""

KNOWN = [
    ('adv', 'accept_list', "accept '0-6' is short, so only an exact match will grade it: What sugar level defines Extra Brut?"),
    ('adv', 'accept_list', "accept '0.6' is short, so only an exact match will grade it: A 5-oz glass sells at $16 from a $48-wholesale 750 ml b"),
    ('adv', 'accept_list', "accept '5.5' is short, so only an exact match will grade it: Moscato d'Asti finishes around what alcohol, and why?"),
    ('adv', 'accept_list', "accept 'ay' is short, so only an exact match will grade it: Name three of the seventeen grand cru villages of Champ"),
    ('adv', 'accept_list', "accept 'cot' is short, so only an exact match will grade it: Which grape's Bordeaux plantings collapsed after the 19"),
    ('adv', 'accept_list', "accept 'dry' is short, so only an exact match will grade it: Alongside édes, Szamorodni's other style is:"),
    ('adv', 'accept_list', "accept 'tdn' is short, so only an exact match will grade it: The compound behind Riesling's aged 'petrol' note:"),
    ('adv', 'accept_list', "accept 'vvf' is short, so only an exact match will grade it: A Champagne labeled 'Blanc de Noirs' from Aÿ made famou"),
    ('adv', 'accept_list', "accept '−7°c' is short, so only an exact match will grade it: An Eiswein harvest legally requires what temperature?"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than $1 75 total 0 65 0 74 0 36 11% pour cost' as correct, so a threshold reads the same in both directions: 'A Negroni pours 1 oz gin ($22/L), 1 oz Campa'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than $19 0 28 $68' as correct, so a threshold reads the same in both directions: 'A bottle costs $19 wholesale; the program ta'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than $48 5 pours $9 60 cost per glass 9 60 16 60% money loser' as correct, so a threshold reads the same in both directions: 'A 5-oz glass sells at $16 from a $48-wholesa'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than 0 6 g l dosage' as correct, so a threshold reads the same in both directions: 'What sugar level defines Extra Brut?'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than 12 months on lees 36 months total from tirage' as correct, so a threshold reads the same in both directions: 'Give the minimum lees-aging for vintage Cham'"),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than 2001 nz screwcap initiative following clare s 2000 lead\' as correct, so a threshold reads the same in both directions: "New Zealand\'s screwcap initiative launched i"'),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than 35 hl ha whites 40' as correct, so a threshold reads the same in both directions: 'Give the maximum base yield (rendement de ba'"),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than 36 months for vdp sekt prestige traditional method mandatory\' as correct, so a threshold reads the same in both directions: "Sekt b.A. with \'Erstes Gewächs\'-style ambiti"'),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than 5 5% fermentation is chilled and filtered to halt keeping sugar and fizz gentle\' as correct, so a threshold reads the same in both directions: "Moscato d\'Asti finishes around what alcohol,"'),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than 51 kaefferkopf ammerschwihr' as correct, so a threshold reads the same in both directions: 'How many Alsace grand cru sites exist, and w'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than 7 c or colder grapes pressed frozen' as correct, so a threshold reads the same in both directions: 'An Eiswein harvest legally requires what tem'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than 70% with merlot and tannat completing' as correct, so a threshold reads the same in both directions: 'Cahors AOP requires what minimum Malbec?'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than 8 750 ml 25 4 oz 3 oz' as correct, so a threshold reads the same in both directions: 'Calculate: a 6-course tasting menu pairs 3-o'"),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than 90% stricter than federal 75%\' as correct, so a threshold reads the same in both directions: "Oregon\'s varietal labeling requires what min"'),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than abbey of saint hilaire 1531' as correct, so a threshold reads the same in both directions: 'Blanquette de Limoux claims sparkling primac'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than aglianico 3 years 1 in wood riserva 4' as correct, so a threshold reads the same in both directions: 'Taurasi DOCG requires which grape at ≥85% an'"),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than ancestor vine 35yr old 70 survivor 100 centenarian below it\' as correct, so a threshold reads the same in both directions: "The Barossa Old Vine Charter\'s top tier, for"'),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than appassimento dried grape dry nebbiolo min 14%\' as correct, so a threshold reads the same in both directions: "Valtellina\'s Sforzato (Sfursat) DOCG applies"'),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than cerasuolo d abruzzo its own doc 2010\' as correct, so a threshold reads the same in both directions: "Montepulciano d\'Abruzzo\'s rosato tradition i"'),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than co planted co harvested co fermented field blend 3 varieties' as correct, so a threshold reads the same in both directions: 'Gemischter Satz, protected as Wiener Gemisch'"),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than conegliano valdobbiadene docg 43 rive plus superiore di cartizze\' as correct, so a threshold reads the same in both directions: "Prosecco\'s DOCG pyramid tops out in which su"'),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than david hohnen of cape mentelle margaret river 1985\' as correct, so a threshold reads the same in both directions: "Cloudy Bay\'s founding company and year:"'),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than do jerez xeres sherry with its sibling do manzanilla sanlucar barrameda since 2022 revision of pliego condiciones unfortified flor aged palomino is legal inside do vino pasto pioneers earlier bottlings had to be sold as vt cadiz' as correct, so a threshold reads the same in both directions: 'Which DO ages Palomino under flor unfortifie'"),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than e g montpeyroux saint saturnin gres montpellier mejanelle pezenas named terroirs still inside aop languedoc terrasses larzac 2014 and pic saint loup 2017 have already graduated to their own aop\' as correct, so a threshold reads the same in both directions: "Name several of AOP Languedoc\'s named terroi"'),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than e g opus one masseto almaviva sena september s hors bordeaux campaign\' as correct, so a threshold reads the same in both directions: "\'La Place de Bordeaux\' now also distributes "'),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than e g radda gaiole panzano of 11\' as correct, so a threshold reads the same in both directions: "Name three of Chianti Classico\'s UGA (Unità "'),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than e g vinsobres 2006 rasteau 2010 dry reds cairanne 2016' as correct, so a threshold reads the same in both directions: 'Which southern Rhône villages were promoted '"),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than eroica since 1999\' as correct, so a threshold reads the same in both directions: "Chateau Ste. Michelle\'s long Riesling collab"'),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than gran selezione estate fruit 30 months aging\' as correct, so a threshold reads the same in both directions: "Chianti Classico\'s top tier since 2014 is:"'),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than incisa della rocchetta family 1968\' as correct, so a threshold reads the same in both directions: "Sassicaia\'s founding family and first commer"'),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than langmeil s freedom vineyard 1843 turkey flat s 1847 block close behind\' as correct, so a threshold reads the same in both directions: "Australia\'s oldest continuously producing Sh"'),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than maison joseph drouhin 1987 veronique drouhin winemaking\' as correct, so a threshold reads the same in both directions: "Which Burgundy house was moved by the 1979 \'"'),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than menzione geografica aggiuntiva delimited cru names 181 in barolo\' as correct, so a threshold reads the same in both directions: "What does \'MGA\' stand for on a modern Barolo"'),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than montelena 1973 chardonnay' as correct, so a threshold reads the same in both directions: 'Which Napa winery won the 1976 Paris tasting'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than ribbon ridge about 3 350 acres 1 350 hectares' as correct, so a threshold reads the same in both directions: 'Which Oregon AVA is the smallest, nested ent'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than ripeness alcohol steinfeder 11 5% federspiel 11 5 12 5% smaragd 12 5%' as correct, so a threshold reads the same in both directions: 'Smaragd, Federspiel and Steinfeder are ranke'"),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than rutherford bench alluvial fans west of hwy 29\' as correct, so a threshold reads the same in both directions: "\'Rutherford dust\' describes the tannin signa"'),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than schlossberg 80 ha also first to be classified in 1975' as correct, so a threshold reads the same in both directions: 'Which Alsace grand cru is the largest, and r'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than schlossberg kaysersberg first grand cru 1975' as correct, so a threshold reads the same in both directions: 'Domaine Weinbach farms beneath which grand c'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than single vintage tawny wood aged 7 years often decades bottled to order' as correct, so a threshold reads the same in both directions: 'Colheita Port is:'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than six years and three months 60 months under voile minimum' as correct, so a threshold reads the same in both directions: 'Vin Jaune must age in cask sans ouillage a m'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than steinberg cistercian 12th century' as correct, so a threshold reads the same in both directions: 'Name the Rheingau monopole of Kloster Eberba'"),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than tdn 1 1 6 trimethyl 1 2 dihydronaphthalene\' as correct, so a threshold reads the same in both directions: "The compound behind Riesling\'s aged \'petrol\'"'),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than traditional method 12 months on lees minimum' as correct, so a threshold reads the same in both directions: 'Cap Classique requires which method and mini'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than two pavie and figeac ausone cheval blanc and angelus had withdrawn' as correct, so a threshold reads the same in both directions: 'How many estates were classified Premier Gra'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than veneto s first docg 1998 dried garganega sweet wine' as correct, so a threshold reads the same in both directions: 'Recioto di Soave earns which historical foot'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than vin pays 2009 eu reform' as correct, so a threshold reads the same in both directions: 'IGP replaced which older French designation?'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than volatile thiols 3mh 3mha' as correct, so a threshold reads the same in both directions: 'Which compound family gives Marlborough Sauv'"),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than vosne romanee 1er cru cros parantoux\' as correct, so a threshold reads the same in both directions: "Henri Jayer\'s most mythologized bottling was"'),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than warren winiarski 1973 s l v cabernet' as correct, so a threshold reads the same in both directions: 'The 1976 Judgment of Paris red winner was ma'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than weinviertel dac 2002 gruner veltliner' as correct, so a threshold reads the same in both directions: 'Which Austrian DAC was the first, and in wha'"),
    ('adv', 'comparative_probe', "grades the INVERSION 'less than westvleteren achel lost status in 2021' as correct, so a threshold reads the same in both directions: 'The five (formerly six) Trappist breweries o'"),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than yakima valley 1983\' as correct, so a threshold reads the same in both directions: "Name Washington\'s first AVA and its year."'),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than yattarna bin 144\' as correct, so a threshold reads the same in both directions: "Penfolds\' white counterpart experiment to Gr"'),
    ('adv', 'comparative_probe', 'grades the INVERSION \'less than zweigelt blaufrankisch st laurent bred by fritz zweigelt in 1922\' as correct, so a threshold reads the same in both directions: "Name Austria\'s most-planted red grape and it"'),
    ('adv', 'compound_answer', 'stem asks for several items but accept \'alavesa\' is one word, so it grades a half-right answer as correct: "Rioja\'s three subzones under the 2017 reform"'),
    ('adv', 'compound_answer', "stem asks for several items but accept 'ambonnay' is one word, so it grades a half-right answer as correct: 'Name three of the seventeen grand cru villag'"),
    ('adv', 'compound_answer', "stem asks for several items but accept 'arbane' is one word, so it grades a half-right answer as correct: 'Name the four permitted Champagne grapes bey'"),
    ('adv', 'compound_answer', "stem asks for several items but accept 'arbanne' is one word, so it grades a half-right answer as correct: 'Name the four permitted Champagne grapes bey'"),
    ('adv', 'compound_answer', "stem asks for several items but accept 'avize' is one word, so it grades a half-right answer as correct: 'Name three of the seventeen grand cru villag'"),
    ('adv', 'compound_answer', "stem asks for several items but accept 'ay' is one word, so it grades a half-right answer as correct: 'Name three of the seventeen grand cru villag'"),
    ('adv', 'compound_answer', 'stem asks for several items but accept \'beaumonts\' is one word, so it grades a half-right answer as correct: "Name Vosne-Romanée\'s three premiers crus mos"'),
    ('adv', 'compound_answer', "stem asks for several items but accept 'bouzy' is one word, so it grades a half-right answer as correct: 'Name three of the seventeen grand cru villag'"),
    ('adv', 'compound_answer', 'stem asks for several items but accept \'brulees\' is one word, so it grades a half-right answer as correct: "Name Vosne-Romanée\'s three premiers crus mos"'),
    ('adv', 'compound_answer', "stem asks for several items but accept 'cairanne' is one word, so it grades a half-right answer as correct: 'Which southern Rhône villages were promoted '"),
    ('adv', 'compound_answer', 'stem asks for several items but accept \'castellina\' is one word, so it grades a half-right answer as correct: "Name three of Chianti Classico\'s UGA (Unità "'),
    ('adv', 'compound_answer', "stem asks for several items but accept 'chouilly' is one word, so it grades a half-right answer as correct: 'Name three of the seventeen grand cru villag'"),
    ('adv', 'compound_answer', "stem asks for several items but accept 'cramant' is one word, so it grades a half-right answer as correct: 'Name three of the seventeen grand cru villag'"),
    ('adv', 'compound_answer', "stem asks for several items but accept 'dewasansan' is one word, so it grades a half-right answer as correct: 'Name two premier sake rice varieties beyond '"),
    ('adv', 'compound_answer', "stem asks for several items but accept 'fromenteau' is one word, so it grades a half-right answer as correct: 'Name the four permitted Champagne grapes bey'"),
    ('adv', 'compound_answer', 'stem asks for several items but accept \'gaiole\' is one word, so it grades a half-right answer as correct: "Name three of Chianti Classico\'s UGA (Unità "'),
    ('adv', 'compound_answer', "stem asks for several items but accept 'gohyakumangoku' is one word, so it grades a half-right answer as correct: 'Name two premier sake rice varieties beyond '"),
    ('adv', 'compound_answer', 'stem asks for several items but accept \'greve\' is one word, so it grades a half-right answer as correct: "Name three of Chianti Classico\'s UGA (Unità "'),
    ('adv', 'compound_answer', 'stem asks for several items but accept \'lamole\' is one word, so it grades a half-right answer as correct: "Name three of Chianti Classico\'s UGA (Unità "'),
    ('adv', 'compound_answer', "stem asks for several items but accept 'louvois' is one word, so it grades a half-right answer as correct: 'Name three of the seventeen grand cru villag'"),
    ('adv', 'compound_answer', "stem asks for several items but accept 'mailly' is one word, so it grades a half-right answer as correct: 'Name three of the seventeen grand cru villag'"),
    ('adv', 'compound_answer', "stem asks for several items but accept 'mesnil' is one word, so it grades a half-right answer as correct: 'Name three of the seventeen grand cru villag'"),
    ('adv', 'compound_answer', 'stem asks for several items but accept \'montefioralle\' is one word, so it grades a half-right answer as correct: "Name three of Chianti Classico\'s UGA (Unità "'),
    ('adv', 'compound_answer', "stem asks for several items but accept 'oger' is one word, so it grades a half-right answer as correct: 'Name three of the seventeen grand cru villag'"),
    ('adv', 'compound_answer', "stem asks for several items but accept 'oiry' is one word, so it grades a half-right answer as correct: 'Name three of the seventeen grand cru villag'"),
    ('adv', 'compound_answer', "stem asks for several items but accept 'omachi' is one word, so it grades a half-right answer as correct: 'Name two premier sake rice varieties beyond '"),
    ('adv', 'compound_answer', 'stem asks for several items but accept \'panzano\' is one word, so it grades a half-right answer as correct: "Name three of Chianti Classico\'s UGA (Unità "'),
    ('adv', 'compound_answer', "stem asks for several items but accept 'puisieulx' is one word, so it grades a half-right answer as correct: 'Name three of the seventeen grand cru villag'"),
    ('adv', 'compound_answer', 'stem asks for several items but accept \'radda\' is one word, so it grades a half-right answer as correct: "Name three of Chianti Classico\'s UGA (Unità "'),
    ('adv', 'compound_answer', "stem asks for several items but accept 'rasteau' is one word, so it grades a half-right answer as correct: 'Which southern Rhône villages were promoted '"),
    ('adv', 'compound_answer', "stem asks for several items but accept 'rosazzo' is one word, so it grades a half-right answer as correct: 'Which Friulian DOCG for a dry white blend di'"),
    ('adv', 'compound_answer', "stem asks for several items but accept 'sillery' is one word, so it grades a half-right answer as correct: 'Name three of the seventeen grand cru villag'"),
    ('adv', 'compound_answer', 'stem asks for several items but accept \'vagliagli\' is one word, so it grades a half-right answer as correct: "Name three of Chianti Classico\'s UGA (Unità "'),
    ('adv', 'compound_answer', "stem asks for several items but accept 'verzenay' is one word, so it grades a half-right answer as correct: 'Name three of the seventeen grand cru villag'"),
    ('adv', 'compound_answer', "stem asks for several items but accept 'verzy' is one word, so it grades a half-right answer as correct: 'Name three of the seventeen grand cru villag'"),
    ('adv', 'compound_answer', "stem asks for several items but accept 'vinsobres' is one word, so it grades a half-right answer as correct: 'Which southern Rhône villages were promoted '"),
    ('adv', 'compound_answer', 'stem asks for several items but accept \'zweigelt\' is one word, so it grades a half-right answer as correct: "Name Austria\'s most-planted red grape and it"'),
    ('adv', 'cross_accept', 'accept \'2001\' on "New Zealand\'s screwcap initiative launch" would also grade the answer to \'The Berlin Tasting of 2004 established w\''),
    ('adv', 'cross_accept', 'accept \'36 months\' on "Sekt b.A. with \'Erstes Gewächs\'-style am" would also grade the answer to \'Give the minimum lees-aging for vintage \''),
    ('adv', 'cross_accept', 'accept \'36 months\' on \'Give the minimum lees-aging for vintage \' would also grade the answer to "Sekt b.A. with \'Erstes Gewächs\'-style am"'),
    ('adv', 'cross_accept', 'accept \'alcohol\' on \'Smaragd, Federspiel and Steinfeder are r\' would also grade the answer to "What do \'original gravity\' and \'final gr"'),
    ('adv', 'cross_accept', "accept 'alcohol' on 'Smaragd, Federspiel and Steinfeder are r' would also grade the answer to 'Best structural logic for raw oysters:'"),
    ('adv', 'cross_accept', "accept 'alcohol' on 'Smaragd, Federspiel and Steinfeder are r' would also grade the answer to 'Capsaicin heat interacts with alcohol by'"),
    ('adv', 'cross_accept', "accept 'alcohol' on 'Smaragd, Federspiel and Steinfeder are r' would also grade the answer to 'Chaptalization is:'"),
    ('adv', 'cross_accept', "accept 'alcohol' on 'Smaragd, Federspiel and Steinfeder are r' would also grade the answer to 'Explain how alcohol contributes to perce'"),
    ('adv', 'cross_accept', "accept 'alcohol' on 'Smaragd, Federspiel and Steinfeder are r' would also grade the answer to 'Junmai Daiginjo requires what maximum se'"),
    ('adv', 'cross_accept', "accept 'alcohol' on 'Smaragd, Federspiel and Steinfeder are r' would also grade the answer to 'Legs/tears on the glass indicate:'"),
    ('adv', 'cross_accept', 'accept \'appassimento\' on "Valtellina\'s Sforzato (Sfursat) DOCG app" would also grade the answer to \'Explain the difference between Recioto a\''),
    ('adv', 'cross_accept', 'accept \'arbois\' on \'Domaine de la Pinte and Overnoy/Houillon\' would also grade the answer to "Name the Jura\'s four geographic AOPs plu"'),
    ('adv', 'cross_accept', 'accept \'atlantic climate\' on "Uruguay\'s Tannat softens relative to Mad" would also grade the answer to "What is \'Vinho Verde\'s\' typical alcohol "'),
    ('adv', 'cross_accept', "accept 'avize' on 'Jacques Selosse, the avatar of grower Ch' would also grade the answer to 'Name three of the seventeen grand cru vi'"),
    ('adv', 'cross_accept', "accept 'avize' on 'Name three of the seventeen grand cru vi' would also grade the answer to 'Jacques Selosse, the avatar of grower Ch'"),
    ('adv', 'cross_accept', 'accept \'bergeron\' on "Savoie\'s Chignin-Bergeron cru is dedicat" would also grade the answer to "What are \'Vin de Savoie Crus\', and rough"'),
    ('adv', 'cross_accept', 'accept \'blaufrankisch\' on \'Egri Bikavér must be built around which \' would also grade the answer to "Name Austria\'s most-planted red grape an"'),
    ('adv', 'cross_accept', "accept 'chaume' on 'The great sweet Chenin trio of Anjou is ' would also grade the answer to 'Which VDN-free Loire sweet appellation r'"),
    ('adv', 'cross_accept', 'accept \'chenin\' on "\'Steen\' historically named which grape i" would also grade the answer to \'Quarts de Chaume gained which unique Loi\''),
    ('adv', 'cross_accept', 'accept \'chianti classico\' on \'Galestro and alberese are the paired soi\' would also grade the answer to "Italy\'s \'Classico\' suffix denotes:"'),
    ('adv', 'cross_accept', "accept 'coteaux du layon' on 'The great sweet Chenin trio of Anjou is ' would also grade the answer to 'Which VDN-free Loire sweet appellation r'"),
    ('adv', 'cross_accept', "accept 'coteaux du layon' on 'Which VDN-free Loire sweet appellation r' would also grade the answer to 'The great sweet Chenin trio of Anjou is '"),
    ('adv', 'cross_accept', 'accept \'cros parantoux\' on "Henri Jayer\'s most mythologized bottling" would also grade the answer to "Name Vosne-Romanée\'s three premiers crus"'),
    ('adv', 'cross_accept', 'accept \'cros parantoux\' on "Name Vosne-Romanée\'s three premiers crus" would also grade the answer to "Henri Jayer\'s most mythologized bottling"'),
    ('adv', 'cross_accept', "accept 'drainage' on 'The Dutch engineering that made the Médo' would also grade the answer to 'Why do slopes beat flats for frost?'"),
    ('adv', 'cross_accept', 'accept \'gewurztraminer\' on "Alto Adige\'s signature native white, pla" would also grade the answer to \'Vendanges Tardives minimum must weights \''),
    ('adv', 'cross_accept', 'accept \'grand cru\' on \'Quarts de Chaume gained which unique Loi\' would also grade the answer to "What was the \'échelle des crus\'?"'),
    ('adv', 'cross_accept', "accept 'grand cru' on 'Quarts de Chaume gained which unique Loi' would also grade the answer to 'Domaine Weinbach farms beneath which gra'"),
    ('adv', 'cross_accept', "accept 'grand cru' on 'Quarts de Chaume gained which unique Loi' would also grade the answer to 'What geological feature makes Rangen uni'"),
    ('adv', 'cross_accept', "accept 'jerez' on 'Which DO ages Palomino under flor unfort' would also grade the answer to 'Name the three towns of the Sherry Trian'"),
    ('adv', 'cross_accept', "accept 'kaefferkopf' on 'Alsace has a trio of grand crus permitte' would also grade the answer to 'How many Alsace grand cru sites exist, a'"),
    ('adv', 'cross_accept', "accept 'kaefferkopf' on 'How many Alsace grand cru sites exist, a' would also grade the answer to 'Alsace has a trio of grand crus permitte'"),
    ('adv', 'cross_accept', "accept 'layon' on 'Which VDN-free Loire sweet appellation r' would also grade the answer to 'The great sweet Chenin trio of Anjou is '"),
    ('adv', 'cross_accept', "accept 'le mesnil-sur-oger' on 'Name three of the seventeen grand cru vi' would also grade the answer to 'Salon, the single-vineyard-era pioneer o'"),
    ('adv', 'cross_accept', 'accept \'malbec\' on "Which grape\'s Bordeaux plantings collaps" would also grade the answer to "Mendoza\'s Uco Valley subzones Gualtallar"'),
    ('adv', 'cross_accept', 'accept \'malbec\' on "Which grape\'s Bordeaux plantings collaps" would also grade the answer to \'Wendouree, the cult of Clare, is famed f\''),
    ('adv', 'cross_accept', "accept 'mesnil' on 'Name three of the seventeen grand cru vi' would also grade the answer to 'Salon, the single-vineyard-era pioneer o'"),
    ('adv', 'cross_accept', "accept 'mesnil' on 'Salon, the single-vineyard-era pioneer o' would also grade the answer to 'Name three of the seventeen grand cru vi'"),
    ('adv', 'cross_accept', 'accept \'muscat blanc a petits grains\' on "Clairette de Die\'s ancestral-method spar" would also grade the answer to \'Muscat du Cap Corse is fortified from wh\''),
    ('adv', 'cross_accept', 'accept \'muscat\' on "Clairette de Die\'s ancestral-method spar" would also grade the answer to "Australia\'s fortified Muscat uses which "'),
    ('adv', 'cross_accept', 'accept \'muscat\' on "Clairette de Die\'s ancestral-method spar" would also grade the answer to "Itata and Bío Bío\'s revival centers on w"'),
    ('adv', 'cross_accept', 'accept \'muscat\' on "Clairette de Die\'s ancestral-method spar" would also grade the answer to "Name Corsica\'s three principal AOPs beyo"'),
    ('adv', 'cross_accept', 'accept \'muscat\' on "Clairette de Die\'s ancestral-method spar" would also grade the answer to \'Muscat du Cap Corse is fortified from wh\''),
    ('adv', 'cross_accept', 'accept \'muscat\' on "Clairette de Die\'s ancestral-method spar" would also grade the answer to \'Vendanges Tardives minimum must weights \''),
    ('adv', 'cross_accept', 'accept \'muscat\' on "Clairette de Die\'s ancestral-method spar" would also grade the answer to \'Which Italian sweet wine comes from the \''),
    ('adv', 'cross_accept', 'accept \'off-dry\' on "\'Feinherb\' on a label indicates:" would also grade the answer to \'Build a cheese-course wine strategy in o\''),
    ('adv', 'cross_accept', 'accept \'off-dry\' on "\'Feinherb\' on a label indicates:" would also grade the answer to \'Capsaicin heat interacts with alcohol by\''),
    ('adv', 'cross_accept', "accept 'oger' on 'Name three of the seventeen grand cru vi' would also grade the answer to 'Salon, the single-vineyard-era pioneer o'"),
    ('adv', 'cross_accept', 'accept \'penfolds\' on "\'La Place de Bordeaux\' now also distribu" would also grade the answer to \'Which Australian wine did Max Schubert c\''),
    ('adv', 'cross_accept', 'accept \'petits grains\' on \'Muscat du Cap Corse is fortified from wh\' would also grade the answer to "Australia\'s fortified Muscat uses which "'),
    ('adv', 'cross_accept', 'accept \'petits grains\' on \'Muscat du Cap Corse is fortified from wh\' would also grade the answer to "Clairette de Die\'s ancestral-method spar"'),
    ('adv', 'cross_accept', "accept 'pinot gris' on 'Name the four permitted Champagne grapes' would also grade the answer to 'Vendanges Tardives minimum must weights '"),
    ('adv', 'cross_accept', "accept 'rangen' on 'Which grand cru, at Thann on volcanic-se' would also grade the answer to 'Name three Alsace grand crus and a produ'"),
    ('adv', 'cross_accept', 'accept \'roussanne\' on "Savoie\'s Chignin-Bergeron cru is dedicat" would also grade the answer to "What is \'vin de paille\' in Hermitage?"'),
    ('adv', 'cross_accept', 'accept \'sand\' on "Toro\'s Tinta de Toro vines survived phyl" would also grade the answer to "Colares\' pre-phylloxera fame comes from "'),
    ('adv', 'cross_accept', "accept 'schlossberg' on 'Domaine Weinbach farms beneath which gra' would also grade the answer to 'Name three Alsace grand crus and a produ'"),
    ('adv', 'cross_accept', "accept 'schlossberg' on 'Domaine Weinbach farms beneath which gra' would also grade the answer to 'Which Alsace grand cru is the largest, a'"),
    ('adv', 'cross_accept', "accept 'schlossberg' on 'Which Alsace grand cru is the largest, a' would also grade the answer to 'Domaine Weinbach farms beneath which gra'"),
    ('adv', 'cross_accept', "accept 'schlossberg' on 'Which Alsace grand cru is the largest, a' would also grade the answer to 'Name three Alsace grand crus and a produ'"),
    ('adv', 'cross_accept', 'accept \'sena\' on "\'La Place de Bordeaux\' now also distribu" would also grade the answer to \'The Berlin Tasting of 2004 established w\''),
    ('adv', 'cross_accept', 'accept \'silex\' on "Pouilly-Fumé\'s flint-smoke reputation ri" would also grade the answer to "Which Sancerre commune\'s terres blanches"'),
    ('adv', 'cross_accept', 'accept \'steiermark\' on "Sauvignon Blanc\'s Austrian stronghold, w" would also grade the answer to "Name Austria\'s four wine-producing state"'),
    ('adv', 'cross_accept', 'accept \'styria\' on "Sauvignon Blanc\'s Austrian stronghold, w" would also grade the answer to "Name Austria\'s four wine-producing state"'),
    ('adv', 'cross_accept', 'accept \'vin de pays\' on "Mas de Daumas Gassac, the \'Lafite of the" would also grade the answer to \'IGP replaced which older French designat\''),
    ('adv', 'cross_accept', 'accept \'vin de pays\' on \'IGP replaced which older French designat\' would also grade the answer to "Mas de Daumas Gassac, the \'Lafite of the"'),
    ('adv', 'negation_probe', 'grades the NEGATION \'not 100% grenache sandy soils no galets\' as correct, so a student can be marked right for saying the opposite: "Château Rayas\' singularity among Châteauneuf"'),
    ('adv', 'negation_probe', 'grades the NEGATION \'not 51% corn new charred oak no additives\' as correct, so a student can be marked right for saying the opposite: "Bourbon\'s legal pillars are:"'),
    ('adv', 'negation_probe', "grades the NEGATION 'not 8 no artificial freezing' as correct, so a student can be marked right for saying the opposite: 'VQA Icewine rules require harvest at what te'"),
    ('adv', 'negation_probe', 'grades the NEGATION \'not aged in warm lofts without estufa\' as correct, so a student can be marked right for saying the opposite: "Madeira\'s \'canteiro\' method means:"'),
    ('adv', 'negation_probe', "grades the NEGATION 'not alcohol and sugar not quality' as correct, so a student can be marked right for saying the opposite: 'Legs/tears on the glass indicate:'"),
    ('adv', 'negation_probe', 'grades the NEGATION \'not brown seeds resolved tannins not just sugar\' as correct, so a student can be marked right for saying the opposite: "\'Phenolic ripeness\' versus sugar ripeness me"'),
    ('adv', 'negation_probe', "grades the NEGATION 'not chateaux estates not vineyards' as correct, so a student can be marked right for saying the opposite: 'Grand Cru in Saint-Émilion attaches to what,'"),
    ('adv', 'negation_probe', 'grades the NEGATION \'not geography not grapes or methods\' as correct, so a student can be marked right for saying the opposite: "Australia\'s GI system differs from the AOC m"'),
    ('adv', 'negation_probe', "grades the NEGATION 'not good but not declared' as correct, so a student can be marked right for saying the opposite: 'Single Quinta Vintage Port appears chiefly i'"),
    ('adv', 'negation_probe', "grades the NEGATION 'not high acid saline no oak low alcohol' as correct, so a student can be marked right for saying the opposite: 'Best structural logic for raw oysters:'"),
    ('adv', 'negation_probe', "grades the NEGATION 'not moisture to infect dryness to concentrate not rot' as correct, so a student can be marked right for saying the opposite: 'Explain why botrytis requires humid mornings'"),
    ('adv', 'negation_probe', "grades the NEGATION 'not natural lactic starter no added lactic acid' as correct, so a student can be marked right for saying the opposite: 'Yamahai and Kimoto methods differ from moder'"),
    ('adv', 'negation_probe', 'grades the NEGATION \'not negociant failure price drop no delivery\' as correct, so a student can be marked right for saying the opposite: "En primeur\'s buyer risks (name two):"'),
    ('adv', 'negation_probe', 'grades the NEGATION \'not neutral young toasty aged no oak\' as correct, so a student can be marked right for saying the opposite: "Hunter Semillon\'s magic trick is:"'),
    ('adv', 'negation_probe', 'grades the NEGATION \'not never arrived ungrafted\' as correct, so a student can be marked right for saying the opposite: "Chile\'s phylloxera status and its viticultur"'),
    ('adv', 'negation_probe', 'grades the NEGATION \'not no added so2 for usda organic wine\' as correct, so a student can be marked right for saying the opposite: "Organic wine in the US versus \'made with org"'),
    ('adv', 'negation_probe', 'grades the NEGATION \'not no charcoal filtration raw cask strength\' as correct, so a student can be marked right for saying the opposite: "\'Muroka nama genshu\' translates to:"'),
    ('adv', 'negation_probe', 'grades the NEGATION \'not no post distillation flavoring\' as correct, so a student can be marked right for saying the opposite: "London Dry gin\'s legal constraint:"'),
    ('adv', 'negation_probe', "grades the NEGATION 'not promo expense at cost not lost revenue' as correct, so a student can be marked right for saying the opposite: 'When costing a comped bottle for a VIP table'"),
    ('adv', 'negation_probe', "grades the NEGATION 'not raisining on vine no botrytis' as correct, so a student can be marked right for saying the opposite: 'Jurançon moelleux concentrates sugar by:'"),
    ('adv', 'negation_probe', 'grades the NEGATION \'not soil not politics\' as correct, so a student can be marked right for saying the opposite: "Hawke\'s Bay\'s Gimblett Gravels district is d"'),
    ('adv', 'negation_probe', "grades the NEGATION 'not sugar ripeness at picking not sweetness' as correct, so a student can be marked right for saying the opposite: 'Give the Oechsle-based logic of the Prädikat'"),
    ('adv', 'negation_probe', "grades the NEGATION 'not sugarcane juice not molasses' as correct, so a student can be marked right for saying the opposite: 'Rhum Agricole differs from most rum by ferme'"),
    ('adv', 'negation_probe', "grades the NEGATION 'not take it back offer alternative without argument' as correct, so a student can be marked right for saying the opposite: 'A guest insists a sound wine is corked. The '"),
    ('adv', 'negation_probe', 'grades the NEGATION \'not topped up barrels no oxidation\' as correct, so a student can be marked right for saying the opposite: "What distinguishes \'ouillé\' Jura whites from"'),
    ('adv', 'negation_probe', "grades the NEGATION 'not treat as own list full service check policy no competing bottle' as correct, so a student can be marked right for saying the opposite: 'BYO/corkage etiquette for the somm includes:'"),
    ('master', 'accept_list', "accept '36k' is short, so only an exact match will grade it: Model a 120-cover restaurant's cellar investment: list "),
    ('master', 'comparative_probe', 'grades the INVERSION \'less than $180 000 5 $36 000 average inventory at cost\' as correct, so a threshold reads the same in both directions: "Model a 120-cover restaurant\'s cellar invest"'),
    ('master', 'comparative_probe', "grades the INVERSION 'less than 1947 vouvray anjou moelleux immortality' as correct, so a threshold reads the same in both directions: 'Which vintage of the 20th century is the Loi'"),
    ('master', 'comparative_probe', "grades the INVERSION 'less than 1977 1985 1994 2000 2011 2016' as correct, so a threshold reads the same in both directions: 'Name three great declared Vintage Port years'"),
    ('master', 'comparative_probe', "grades the INVERSION 'less than 1988 1989 1990 trilogy 2001 2009 2011 2015' as correct, so a threshold reads the same in both directions: 'Name the greatest Sauternes vintages of the '"),
    ('master', 'comparative_probe', 'grades the INVERSION \'less than 1989 and 1990 back to back hot opulent vintages petrus pair among century s greatest\' as correct, so a threshold reads the same in both directions: "Which vintage pair is called \'the twins\' of "'),
    ('master', 'comparative_probe', 'grades the INVERSION \'less than 2013\' as correct, so a threshold reads the same in both directions: "In which vintage did Gaja\'s single-vineyard "'),
    ('master', 'comparative_probe', "grades the INVERSION 'less than corbieres boutenac 30% carignan mandated' as correct, so a threshold reads the same in both directions: 'Which Corbières subzone earned independent A'"),
    ('master', 'comparative_probe', "grades the INVERSION 'less than cremant d alsace and structurally 51 individual grand cru aops since 2011' as correct, so a threshold reads the same in both directions: 'Name the third Alsace wine AOP beside Alsace'"),
    ('master', 'comparative_probe', 'grades the INVERSION \'less than jean michel boursiquot 1994 identified merlot blocks as carmenere\' as correct, so a threshold reads the same in both directions: "The 1990s \'Chilean Merlot\' unmasking: who, w"'),
    ('master', 'comparative_probe', 'grades the INVERSION \'less than jeffrey grosset and clare vignerons collective 2000 bottling switch\' as correct, so a threshold reads the same in both directions: "Who is credited with Australia\'s screwcap Ri"'),
    ('master', 'comparative_probe', "grades the INVERSION 'less than krug grande cuvee blends 120 wines across 10 years all base wines in small oak' as correct, so a threshold reads the same in both directions: 'Which house holds the deepest reserve-wine l'"),
    ('master', 'comparative_probe', "grades the INVERSION 'less than les pucelles puligny montrachet 1er cru adjoining bienvenues batard' as correct, so a threshold reads the same in both directions: 'Name the climat and commune of Domaine Lefla'"),
    ('master', 'comparative_probe', 'grades the INVERSION \'less than massandra crimea tsars fortified and sweet library sotheby s sold its 1775 jerez in 2001\' as correct, so a threshold reads the same in both directions: "Crimea\'s historic sweet-wine cellar of the T"'),
    ('master', 'comparative_probe', 'grades the INVERSION \'less than micro cuvee extraction forward winemaking in garages jean luc thunevin s valandraud 1991 manifesto\' as correct, so a threshold reads the same in both directions: "Describe \'garagiste\' and name the movement\'s"'),
    ('master', 'comparative_probe', 'grades the INVERSION \'less than nielluccio sangiovese malvoisie corse vermentino grenache keeps its own name and sciacarello is none of three dna identifies it as tuscany s mammolo\' as correct, so a threshold reads the same in both directions: "Name Corsica\'s grape synonyms for Sangiovese"'),
    ('master', 'comparative_probe', "grades the INVERSION 'less than pouilly fuisse 22 premiers crus 2020' as correct, so a threshold reads the same in both directions: 'Which Mâconnais village AOP was promoted wit'"),
    ('master', 'comparative_probe', "grades the INVERSION 'less than promoted to grand cru in 1992 monopole of francois lamarche' as correct, so a threshold reads the same in both directions: 'Which grand cru did La Grande Rue become in '"),
    ('master', 'comparative_probe', 'grades the INVERSION \'less than royal decree delimited tokaj as closed production district with vineyard classification predating bordeaux s 1855 by over century\' as correct, so a threshold reads the same in both directions: "Explain Tokaj\'s 1737 royal decree and its wo"'),
    ('master', 'comparative_probe', "grades the INVERSION 'less than schloss johannisberg 1775 delayed messenger spatlesereiter legend' as correct, so a threshold reads the same in both directions: 'Which Rheingau estate produced the first rec'"),
    ('master', 'comparative_probe', "grades the INVERSION 'less than tempranillo c 203 000 ha massed across castilla mancha rioja and ribera del duero ahead of airen c 200 000 ha since mapa s survey with data to 31 july 2021 airen vast dry farmed plateau white of castilla mancha much of it distilled to brandy held title for decades and remains much largest white' as correct, so a threshold reads the same in both directions: 'Which grape dominates Spanish acreage by hec'"),
    ('master', 'comparative_probe', "grades the INVERSION 'less than yes in its serious form single vineyard wild ferment barrel or lees aged bottlings greywacke wild dog point section 94 te koko that trade pungency for texture and age five years honourably' as correct, so a threshold reads the same in both directions: 'Argue whether Marlborough Sauvignon Blanc de'"),
    ('master', 'compound_answer', 'stem asks for several items but accept \'graves\' is one word, so it grades a half-right answer as correct: "Which appellation\'s whites did the 1959 clas"'),
    ('master', 'compound_answer', "stem asks for several items but accept 'rieussec' is one word, so it grades a half-right answer as correct: 'Which châteaux are the eleven Premiers Crus '"),
    ('master', 'cross_accept', 'accept \'1989 1990\' on "Which vintage pair is called \'the twins\'" would also grade the answer to \'Name the greatest Sauternes vintages of \''),
    ('master', 'cross_accept', "accept 'chambertin' on 'Which abbey planted Clos de Bèze and whe' would also grade the answer to 'Name all nine grands crus of Gevrey-Cham'"),
    ('master', 'cross_accept', "accept 'clos de beze' on 'Name all nine grands crus of Gevrey-Cham' would also grade the answer to 'Which abbey planted Clos de Bèze and whe'"),
    ('master', 'cross_accept', 'accept \'zind-humbrecht\' on "Which producer\'s \'Clos Windsbuhl\' and \'C" would also grade the answer to \'Which Alsace producer would you cite for\''),
    ('master', 'negation_probe', 'grades the NEGATION \'not 100 hectares tiny yields no yquem years\' as correct, so a student can be marked right for saying the opposite: "Yquem\'s production discipline in numbers:"'),
    ('master', 'negation_probe', "grades the NEGATION 'not aged champagne junmai sake oxidative jura or sherry no tannin' as correct, so a student can be marked right for saying the opposite: 'Design a pairing for a vegetarian umami-forw'"),
    ('master', 'negation_probe', "grades the NEGATION 'not aged nebbiolo barolo mature aromatics no oak power echo' as correct, so a student can be marked right for saying the opposite: 'Construct the classic pairing logic for whit'"),
    ('master', 'negation_probe', 'grades the NEGATION \'not argon needle through cork sparkling no old crumbly corks risk\' as correct, so a student can be marked right for saying the opposite: "Coravin\'s mechanism and its known limits:"'),
    ('master', 'negation_probe', 'grades the NEGATION \'not bonded warehouse no duty until release\' as correct, so a student can be marked right for saying the opposite: "Explain \'in bond\' storage and its two commer"'),
    ('master', 'negation_probe', 'grades the NEGATION \'not cellar temp hand pump secondary in cask no extraneous co2\' as correct, so a student can be marked right for saying the opposite: "English cask \'real ale\' service specs:"'),
    ('master', 'negation_probe', 'grades the NEGATION \'not champagne pressing final cut not burgundy\' as correct, so a student can be marked right for saying the opposite: "Explain \'rebêche\' — trick question: where do"'),
    ('master', 'negation_probe', "grades the NEGATION 'not chemist beaujolais natural wine theorist no sulfur' as correct, so a student can be marked right for saying the opposite: 'Who was Jules Chauvet and why does he matter'"),
    ('master', 'negation_probe', 'grades the NEGATION \'not concrete no oak parcel wines soil expression\' as correct, so a student can be marked right for saying the opposite: "Zuccardi\'s Piedra Infinita and Catena\'s Adri"'),
    ('master', 'negation_probe', "grades the NEGATION 'not currency reputation lag market access history not quality' as correct, so a student can be marked right for saying the opposite: 'How would you explain the price gap between '"),
    ('master', 'negation_probe', "grades the NEGATION 'not dollars in till not percentage' as correct, so a student can be marked right for saying the opposite: 'Contribution margin versus pour cost — why c'"),
    ('master', 'negation_probe', 'grades the NEGATION \'not farming practice certifications not quality standards\' as correct, so a student can be marked right for saying the opposite: "Explain why \'organic\' and \'biodynamic\' certi"'),
    ('master', 'negation_probe', "grades the NEGATION 'not first i am second i was mouton does not change' as correct, so a student can be marked right for saying the opposite: 'Explain the 1973 Mouton promotion: who signe'"),
    ('master', 'negation_probe', 'grades the NEGATION \'not gg has no pradikat on label\' as correct, so a student can be marked right for saying the opposite: "Explain the VDP\'s stance on Prädikat terms f"'),
    ('master', 'negation_probe', 'grades the NEGATION \'not hexenberg no sorcerer goldert brand hengst\' as correct, so a student can be marked right for saying the opposite: "Which grand cru\'s name means \'sorcerers\' hil"'),
    ('master', 'negation_probe', "grades the NEGATION 'not match cuisine styles not just premium serve in wine glasses train staff' as correct, so a student can be marked right for saying the opposite: 'Explain how to build a sake list for a non-J'"),
    ('master', 'negation_probe', 'grades the NEGATION \'not morey saint denis is not it arbois\' as correct, so a student can be marked right for saying the opposite: "Explain the 1935 \'Appellation d\'Origine Cont"'),
    ('master', 'negation_probe', "grades the NEGATION 'not never override guest offer alternative once' as correct, so a student can be marked right for saying the opposite: 'A guest asks for a wine you consider a poor '"),
    ('master', 'negation_probe', "grades the NEGATION 'not no animal fat lighter proteins high acid whites low tannin reds fining vegan' as correct, so a student can be marked right for saying the opposite: 'Menu wines for a strict-vegan tasting menu: '"),
    ('master', 'negation_probe', 'grades the NEGATION \'not no ava trademarked by chappellet\' as correct, so a student can be marked right for saying the opposite: "Explain Pritchard Hill\'s appellation status."'),
    ('master', 'negation_probe', 'grades the NEGATION \'not no barrique no berlusconi hand drawn manifesto label\' as correct, so a student can be marked right for saying the opposite: "Bartolo Mascarello\'s famous label and its sl"'),
    ('master', 'negation_probe', 'grades the NEGATION \'not no bruising dilution temperature ice shards cloud\' as correct, so a student can be marked right for saying the opposite: "Why does a Martini \'bruise\' claim fail chemi"'),
    ('master', 'negation_probe', 'grades the NEGATION \'not no sugar less protection ages faster needs riper base\' as correct, so a student can be marked right for saying the opposite: "\'Dosage zéro\' aging paradox:"'),
    ('master', 'negation_probe', "grades the NEGATION 'not not one wine per course smaller pours arcs revisit wines alcohol management' as correct, so a student can be marked right for saying the opposite: 'Design a wine pairing for a 12-course tastin'"),
    ('master', 'negation_probe', 'grades the NEGATION \'not only huet wine that is not single vineyard\' as correct, so a student can be marked right for saying the opposite: "What sets Huet\'s \'Cuvée Constance\' apart fro"'),
    ('master', 'negation_probe', 'grades the NEGATION \'not overnoy and no sulfur lineage\' as correct, so a student can be marked right for saying the opposite: "Explain the Jura\'s role in the natural wine "'),
    ('master', 'negation_probe', 'grades the NEGATION \'not overnoy houillon no added sulfur\' as correct, so a student can be marked right for saying the opposite: "Pierre Overnoy\'s Pupillin cellar passed to w"'),
    ('master', 'negation_probe', 'grades the NEGATION \'not poor years no appellation wine made\' as correct, so a student can be marked right for saying the opposite: "Château-Chalon\'s \'declared off\' mechanism:"'),
    ('master', 'negation_probe', 'grades the NEGATION \'not same yeast lower alcohol no fortification acetaldehyde\' as correct, so a student can be marked right for saying the opposite: "Explain \'sous voile\' chemistry versus Sherry"'),
    ('master', 'negation_probe', 'grades the NEGATION \'not savennieres no fiefs vendeens anjou brissac\' as correct, so a student can be marked right for saying the opposite: "The Loire\'s 2011 \'appellation contiguity\' od"'),
    ('master', 'negation_probe', 'grades the NEGATION \'not seneca lake depth thermal mass no freeze\' as correct, so a student can be marked right for saying the opposite: "The Finger Lakes\' \'banana belt\' and its phys"'),
    ('master', 'negation_probe', "grades the NEGATION 'not serve it advise sequencing offer intermediate glass do not lecture' as correct, so a student can be marked right for saying the opposite: 'A guest orders a mature Bordeaux with a heav'"),
    ('master', 'negation_probe', 'grades the NEGATION \'not site not producer no quality guarantee land only\' as correct, so a student can be marked right for saying the opposite: "Explain what \'Grand Cru\' guarantees, and doe"'),
    ('master', 'negation_probe', "grades the NEGATION 'not soil carbon health cover crops no till compost grazing' as correct, so a student can be marked right for saying the opposite: 'Explain regenerative viticulture in one sent'"),
    ('master', 'negation_probe', "grades the NEGATION 'not structured grid calls no shame focus on deduction not guessing' as correct, so a student can be marked right for saying the opposite: 'Explain how you would run a blind tasting fo'"),
    ('master', 'negation_probe', 'grades the NEGATION \'not yeast association numbers aroma profiles no 9 no 1801\' as correct, so a student can be marked right for saying the opposite: "What is \'kobo\' and why do numbered yeast str"'),
]
