# -*- coding: utf-8 -*-
"""Put the rewritten banks into the app, replacing the imported ones.

    py rewrite/ship.py --dry-run     report what would change, touch nothing
    py rewrite/ship.py               write the two bank files

This is the step that turns a year of rewriting into product. Until it runs,
3,061 original questions sit in rewrite/ and every student still reads the
imported bank the whole exercise exists to remove.

WHAT IT TOUCHES, and what it deliberately does not.

  js/data-questions.js   the whole file is the QUESTIONS array, so it is
                         rewritten entirely.
  js/data-intro.js       holds INTRO_QUESTIONS *and* INTRO_GRAPES, INTRO_ATLAS
                         and others. Only the INTRO_QUESTIONS array is replaced;
                         everything after it is preserved byte for byte. A naive
                         whole-file write would silently delete the atlas.

Ids are re-minted from the new stems, so every id changes. That is safe today
and only today: .scripts/mint-ids.py --strip says it plainly, and the README
repeats it. No Supabase project exists and nothing has been sold, so no student
record is orphaned by the change. After launch this would strand every paying
venue's review history.

THREE QUESTION TYPES DO NOT SURVIVE THIS SWAP, and it is better to say so here
than to let someone discover it later:

  labelled     50 in Rank I, the whole of Label Reading, each rendering a wine
               label the student reads off. Replaced by 50 original text
               questions on the same competencies.
  matching     15 in Rank II, one per category, drag-to-pair.
  select       16 in Rank II, one per category, select-all-that-apply.

The engine guards for all three (saTrueSA is `q.sa && !q.mt && !q.sel`), so
their absence renders as an ordinary question and breaks nothing. What is lost
is variety, not function. Writing 81 replacements in those formats is scoped
follow-up work, not a blocker on shipping honest content.
"""

import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "categories"))

import importlib  # noqa: E402
import lib  # noqa: E402

LEVEL_OF = {"Rank I": "intro", "Rank II": "certified"}
TARGET = {
    "intro":     ("js/data-intro.js",     "INTRO_QUESTIONS"),
    "certified": ("js/data-questions.js", "QUESTIONS"),
}

HEADERS = {
    "intro": """/* ============ Introductory level: bank, grapes, compendia ============
   ORIGINAL WORK. Every question in INTRO_QUESTIONS was written from a syllabus
   in rewrite/categories/, never from a source question, and verified against
   the bank it replaces: 0 exact stem matches, maximum sequence ratio 0.667,
   longest shared word run 5 against a flag at 6. The four questions above the
   0.60 review line are all in Viticulture & Winemaking and are the shared topic
   terms a human reviewed and cleared: port is fortified, malolactic conversion
   changes, primary purpose of, are most associated with.
   GENERATED by rewrite/ship.py. Edit the category module, not this file.
   Identity = the minted `id`; question text is safe to edit, ids are not.
   ============ */""",
    "certified": """/* ============ Certified level: the Squire bank ============
   ORIGINAL WORK. Every question here was written from a syllabus in
   rewrite/categories/, never from a source question, and verified against the
   bank it replaces: 0 exact stem matches, maximum sequence ratio 0.560 against
   a 0.60 review threshold, longest shared word run 5 against a flag at 6,
   nothing flagged.
   GENERATED by rewrite/ship.py. Edit the category module, not this file.
   Short answers are graded by matchSA in js/core.js; the accept list is a
   contract, and rewrite/lib.py ports the grader so it can be tested.
   ============ */""",
}


def array_span(text, var):
    """Byte span of `var = [ ... ]`, found by bracket depth rather than regex.

    A regex cannot find the end of a JSON array containing brackets inside
    strings, and getting this wrong here would truncate a bank.
    """
    m = re.search(r"var\s+%s\s*=\s*\[" % re.escape(var), text)
    if not m:
        raise SystemExit("could not find `var %s = [` " % var)
    start = m.end() - 1
    depth, in_str, esc = 0, False, False
    for i in range(start, len(text)):
        c = text[i]
        if in_str:
            if esc:
                esc = False
            elif c == "\\":
                esc = True
            elif c == '"':
                in_str = False
            continue
        if c == '"':
            in_str = True
        elif c == "[":
            depth += 1
        elif c == "]":
            depth -= 1
            if depth == 0:
                return m.start(), start, i + 1
    raise SystemExit("unterminated array for %s" % var)


def collect():
    mods = sorted(f[:-3] for f in os.listdir(os.path.join(HERE, "categories"))
                  if f.endswith(".py") and not f.startswith("_"))
    banks = {"intro": [], "certified": []}
    for name in mods:
        mod = importlib.import_module("categories.%s" % name)
        level = LEVEL_OF.get(getattr(mod, "RANK", "Rank I"))
        if level is None:
            continue
        bank = [dict(e) for e in mod.BANK]
        prefix = getattr(mod, "PREFIX", "i")
        lib.bake_option_order(bank, mod.CAT)
        for e in bank:
            row = {"id": lib.mint(mod.CAT, e["q"], prefix), "cat": mod.CAT, "q": e["q"]}
            if lib.is_mc(e):
                row["opts"] = e["opts"]
                row["a"] = e["a"]
            else:
                row["sa"] = 1
                row["accept"] = e["accept"]
                row["ans"] = e["ans"]
                if e.get("ex"):
                    row["ex"] = 1
            row["exp"] = e["exp"]
            banks[level].append(row)
    return banks


def main(argv):
    dry = "--dry-run" in argv
    banks = collect()

    ids = [r["id"] for level in banks for r in banks[level]]
    if len(ids) != len(set(ids)):
        raise SystemExit("id collision across the corpus: refusing to write")

    print("")
    for level in ("intro", "certified"):
        rel, var = TARGET[level]
        path = os.path.join(REPO, rel)
        text = io.open(path, encoding="utf-8").read()
        _, s, e = array_span(text, var)
        old = json.loads(text[s:e])
        new = banks[level]

        rows = ",\n".join(json.dumps(r, ensure_ascii=False) for r in new)
        body = "[\n%s\n]" % rows

        head_end = text.index("var %s" % var)
        header = HEADERS[level]
        rebuilt = header + "\n" + text[head_end:s] + body + text[e:]

        print("  %-22s %s" % (rel, var))
        print("     was %4d questions, %6.0f KB" % (len(old), len(text) / 1024.0))
        print("     now %4d questions, %6.0f KB" % (len(new), len(rebuilt) / 1024.0))
        tail = len(text) - e
        print("     preserved after the array: %d bytes%s"
              % (tail, "  (grapes, atlas, compendia)" if tail > 400 else ""))

        # Which ids move, and therefore which stored stats are orphaned. This is
        # the only visible sign that a stem was edited, because everything else
        # about a bank looks identical: same count, same categories, same shape.
        #
        # It also catches the reverse, which is what it caught first: a bank that
        # has DRIFTED from its source. js/data-intro.js was one question behind
        # rewrite/categories/ for an unknown stretch - a Sake & Spirits stem had
        # been corrected from "the discarded fractions" to "those two outer
        # fractions", because heads and tails are mostly recharged into the next
        # run rather than thrown away, and the fix never reached a student. The
        # source was right, the app was wrong, and nothing said so.
        old_ids = set(r.get("id") for r in old)
        new_ids = set(r["id"] for r in new)
        moved = old_ids - new_ids
        if moved:
            by_id = {r.get("id"): r.get("q", "") for r in old}
            print("     %d id%s MOVE, orphaning any stored stat that used them:"
                  % (len(moved), "" if len(moved) == 1 else "s"))
            for i in sorted(moved)[:5]:
                print("       %s  %s" % (i, by_id.get(i, "")[:66]))
            if len(moved) > 5:
                print("       ... and %d more" % (len(moved) - 5))
            print("     A stem was edited. Harmless while nothing is sold; after")
            print("     launch this strands that question's review history.")
        else:
            print("     ids: all %d unchanged" % len(new_ids))

        if dry:
            continue
        io.open(path, "w", encoding="utf-8", newline="\n").write(rebuilt)

    print("")
    print("  %s" % ("DRY RUN, nothing written." if dry
                    else "written. Bump the ?v= in index.html and CACHE in sw.js."))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
