"""Rank I rewrite - Alsace (58 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

The category is built around the one thing that makes Alsace peculiar in France:
the label names a grape rather than a place, and everything else follows from
the rain shadow behind the Vosges that lets those grapes ripen this far north.
Stems open with a symptom, a plate of food, a bottle in the hand or a rule that
has been broken, and let the variety, the site or the term be the answer.
"""

from lib import Q

CAT = "Alsace"
SLUG = "r1-alsace"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("The Vosges and the vineyard", 7),
    ("Riesling, Muscat and the dry style", 7),
    ("Gewurztraminer and Pinot Gris", 7),
    ("Sylvaner, the Pinots and Auxerrois", 8),
    ("The Grand Cru system", 8),
    ("Vendanges Tardives and Selection de Grains Nobles", 7),
    ("Cremant, blends and the label", 8),
    ("Soils, history and the table", 6),
]

BANK = [
    # ----------------------------------- the Vosges and the vineyard (7) -----
    Q("The Vosges and the vineyard",
      "Weather arriving from the west drops most of its water on the far side of a mountain wall before it ever reaches the vineyard. Which range does that work?",
      ["The Vosges", "The Jura", "The Ardennes", "The Black Forest"], 0,
      "The Vosges run the length of the region's western edge and force damp Atlantic air to rise, cool and rain itself out on the far flank. The vines sit in the lee, on the sheltered eastern side."),
    Q("The Vosges and the vineyard",
      "Annual rainfall in the sheltered heart of the vineyard, around Colmar, comes closest to which figure?",
      ["Around 500 to 600 millimetres", "Around 900 millimetres",
       "Around 1,300 millimetres", "Around 1,800 millimetres"], 0,
      "That makes Colmar one of the driest towns in France, drier than much of the Mediterranean coast. Low rainfall means slow, unhurried ripening and very little rot in a normal autumn."),
    Q("The Vosges and the vineyard",
      "Warm, dry air sinking down the lee slope of a mountain chain, having shed its moisture on the way up, is known by which name?",
      ["A foehn wind", "A mistral", "A sirocco", "A bise"], 0,
      "Air heats as it descends and compresses, so the lee slope gets wind that is both warmer and drier than the windward side. It is the mechanism behind every rain shadow, here and in the Alps."),
    Q("The Vosges and the vineyard",
      "Growers work the foothill slopes and leave the flat land toward the river to other crops. Which exposure do those slopes mostly present?",
      ["East to south-east", "Due north", "West to north-west",
       "Level ground with no consistent aspect"], 0,
      "An east-facing slope takes the morning sun and warms early, and its tilt drains cold air downhill away from the buds. The flat plain by the Rhine is frost-prone and too fertile for good wine."),
    Q("The Vosges and the vineyard",
      "Mountains along the western edge of the region lose height toward the north. What follows for the vineyards at that end?",
      ["They are wetter and cooler, since the rain shadow is weaker there",
       "They are drier and warmer, since the peaks funnel sun onto them",
       "They are cut off from western weather altogether",
       "They ripen roughly a month earlier"], 0,
      "The highest summits shelter the southern vineyards most effectively. The lower northern hills let more weather through, which is why the north of the region is the cooler and damper half."),
    Q("The Vosges and the vineyard",
      "Two departments split the vineyard between them, one to the north and one to the south. Which pair?",
      ["Bas-Rhin and Haut-Rhin", "Moselle and Meurthe-et-Moselle",
       "Vosges and Territoire de Belfort", "Doubs and Jura"], 0,
      "Bas-Rhin lies north around Strasbourg and Barr, Haut-Rhin south around Colmar. The names follow the river rather than the map: upstream is haut, so the southern half is the high one."),
    Q("The Vosges and the vineyard",
      "Vines are planted from roughly 175 metres up to about 420 metres and no higher. What stops them going further up the hill?",
      ["Forest, cold and a season too short to ripen fruit",
       "A legal ceiling written into the appellation",
       "Soils that turn to heavy clay above the treeline",
       "A complete absence of sunshine on the upper slopes"], 0,
      "Above the vineyard line the Vosges are wooded and cold, and the growing season runs out before the grapes are ripe. The sweet spot is the lower slope, warm enough to ripen and steep enough to drain."),

    # -------------------------- Riesling, Muscat and the dry style (7) -------
    Q("Riesling, Muscat and the dry style",
      "A bone-dry white with piercing acidity, lime and green apple, and a kerosene note creeping in with age, is poured from a tall green flute. Which variety?",
      ["Riesling", "Gewurztraminer", "Pinot Gris", "Muscat"], 0,
      "Alsace ferments Riesling dry far more often than Germany does, so the acidity stands unbuffered by sugar. The petrol note comes from a compound that builds slowly in bottle and is a sign of maturity rather than a fault."),
    Q("Riesling, Muscat and the dry style",
      "Choucroute garnie arrives at the table, salty and rich with pork and sausage over sharp fermented cabbage. Which Alsace wine is the traditional partner?",
      ["A dry Riesling", "A Gewurztraminer Vendanges Tardives",
       "A Pinot Gris Selection de Grains Nobles", "A chilled sweet Muscat"], 0,
      "Acidity is what handles fat and salt, and a dry wine meets the lactic sharpness of the fermented cabbage instead of fighting it. Sweetness alongside that dish reads as cloying within two mouthfuls."),
    Q("Riesling, Muscat and the dry style",
      "A guest asks how an Alsace Riesling will differ from a Mosel Kabinett at a similar price. What is the most reliable answer?",
      ["It will be fermented dry and carry more alcohol",
       "It will be sweeter and lower in alcohol",
       "It will have been raised in new oak barrels",
       "It will be a blend of several white varieties"], 0,
      "The rain shadow ripens fruit more fully, and the house style is dry, so the wine usually lands between 12.5 and 13.5 percent with no sugar left. A Kabinett is picked lighter and often keeps some."),
    Q("Riesling, Muscat and the dry style",
      "Steel tanks and large old oak foudres are the norm in the region's cellars, and new barriques are rare. What is the reasoning?",
      ["New oak would bury the aromatics and the sense of site the wines trade on",
       "Oak of any kind is forbidden by the appellation rules",
       "The wines are bottled too young to spend time in barrel",
       "Barrels cannot be sourced anywhere in the region"], 0,
      "A foudre is old, large and effectively neutral, so it lets a wine breathe without flavouring it. Alsace is built on varietal and vineyard transparency, and vanilla and toast obscure both."),
    Q("Riesling, Muscat and the dry style",
      "Two distinct grapes are bottled under one varietal name here, the older small-berried one and a nineteenth-century crossing that ripens earlier. Which name covers both?",
      ["Muscat", "Riesling", "Sylvaner", "Gewurztraminer"], 0,
      "Muscat Blanc a Petits Grains is the finer and more perfumed of the two; Muscat Ottonel ripens earlier and copes better with cool sites. Most bottles are a blend of the pair."),
    Q("Riesling, Muscat and the dry style",
      "The first asparagus of spring is served with ham and hollandaise, a dish that defeats most wines. Which Alsace bottle is the traditional answer?",
      ["A dry Muscat", "A Riesling Vendanges Tardives",
       "An oak-aged Pinot Noir", "A Gewurztraminer Selection de Grains Nobles"], 0,
      "Muscat smells emphatically of grapes yet finishes dry, and that combination of perfume without sugar sits with asparagus where a hard, acid-driven wine turns metallic."),
    Q("Riesling, Muscat and the dry style",
      "Elsewhere in southern France this aromatic grape is turned into sweet fortified wine, while Alsace ferments it out completely. Which grape?",
      ["Muscat", "Grenache Blanc", "Viognier", "Clairette"], 0,
      "The south stops the fermentation with spirit to make a vin doux naturel. Alsace does the opposite and lets the wine go dry, which is why its version tastes of the fresh grape rather than of syrup."),

    # ----------------------------------- Gewurztraminer and Pinot Gris (7) ---
    Q("Gewurztraminer and Pinot Gris",
      "Lychee, rose petal and ginger fill the glass, the colour is deep gold, the acidity is low and the alcohol high. Which grape?",
      ["Gewurztraminer", "Riesling", "Sylvaner", "Pinot Blanc"], 0,
      "The berry is pink-skinned, which gives both the colour and the phenolic grip. Low acidity is why the wine can taste sweet even when it has been fermented dry."),
    Q("Gewurztraminer and Pinot Gris",
      "The first half of the name Gewurztraminer is a German word. What does it mean?",
      ["Spiced", "Golden", "Noble", "Early-ripening"], 0,
      "Gewurz means spiced, and Traminer points back to Tramin in the Italian Tyrol. The Alsace grape is the aromatic pink-berried mutation of that older, plainer variety."),
    Q("Gewurztraminer and Pinot Gris",
      "A washed-rind cheese from a valley high in the Vosges is pungent enough to flatten almost any wine. Which local bottle is served with it?",
      ["Gewurztraminer", "Sylvaner", "Cremant d'Alsace", "Muscat"], 0,
      "Munster takes its name from the valley on the mountain slope, and Gewurztraminer's weight, perfume and touch of sugar are among the few things that can meet it. Cumin seed is traditionally served alongside."),
    Q("Gewurztraminer and Pinot Gris",
      "Until the 2007 vintage one Alsace variety was sold under a borrowed Hungarian name that the European Union eventually forced off the label. Which variety?",
      ["Pinot Gris", "Sylvaner", "Muscat Ottonel", "Gewurztraminer"], 0,
      "Tokay d'Alsace, later Tokay Pinot Gris, was retired to protect Hungary's Tokaji. The wine has no connection to Furmint or to Hungary, and the name appears to rest on old legend."),
    Q("Gewurztraminer and Pinot Gris",
      "A broad, smoky white with ripe pear and a mushroomy edge, fuller than Riesling and softer in acid, is poured with foie gras. Which variety?",
      ["Pinot Gris", "Muscat", "Sylvaner", "Pinot Blanc"], 0,
      "Pinot Gris carries more body and often a little residual sugar, and that weight is what stands up to a rich terrine. The same profile makes it the regional choice for roast poultry and game birds."),
    Q("Gewurztraminer and Pinot Gris",
      "Berries that ripen a dull pinkish grey rather than black betray a mutation of a familiar red grape. Which is the parent?",
      ["Pinot Noir", "Gamay", "Chardonnay", "Savagnin"], 0,
      "Pinot Noir, Pinot Gris and Pinot Blanc are one vine in three suits of clothes. The grey berry still carries pigment in its skin, which is why the wine is deeper in colour and weightier than most whites."),
    Q("Gewurztraminer and Pinot Gris",
      "Ordering a Pinot Gris and expecting something dry, a guest meets a wine with obvious sweetness. What explains it?",
      ["Sweetness varies widely from producer to producer within the same variety and appellation",
       "Pinot Gris may not legally be fermented dry in this region",
       "The wine had restarted its fermentation in the bottle",
       "Any Alsace wine above 13 percent alcohol retains sugar by law"], 0,
      "House style, not law, decides where a Pinot Gris finishes, and the same appellation covers bone-dry and frankly sweet bottlings. From the 2021 vintage an Alsace white must state its sweetness on the label, as sec, demi-sec, moelleux or doux or on a printed scale, so a current bottle declares itself and only an older one has to be asked about or tasted."),

    # ------------------------------ Sylvaner, the Pinots and Auxerrois (8) ---
    Q("Sylvaner, the Pinots and Auxerrois",
      "A neutral, earthy, generously cropping white was once the workhorse of the region and now survives best in the north around Mittelbergheim. Which grape?",
      ["Sylvaner", "Chasselas", "Auxerrois", "Pinot Blanc"], 0,
      "Sylvaner yields more juice and less perfume than the noble four. On the right site it turns dry and saline rather than dilute, and it is the regional match for onion tart and shellfish."),
    Q("Sylvaner, the Pinots and Auxerrois",
      "One Grand Cru site breaks the four-variety rule to admit Sylvaner, in recognition of a long local tradition. Which site?",
      ["Zotzenberg", "Rangen", "Schlossberg", "Brand"], 0,
      "Zotzenberg at Mittelbergheim had produced serious Sylvaner on its marl and limestone for generations, and the decree was amended to let it say so. It is the only Grand Cru where that name may appear."),
    Q("Sylvaner, the Pinots and Auxerrois",
      "Soft, appley and low in acid, one white makes an undemanding everyday wine and much of the base for the region's sparkling. Which?",
      ["Pinot Blanc", "Riesling", "Sylvaner", "Muscat"], 0,
      "It has neither Riesling's acidity nor Gewurztraminer's perfume, and that neutrality is exactly what a base wine wants. It is also a staple of the carafe list in an Alsace winstub."),
    Q("Sylvaner, the Pinots and Auxerrois",
      "A bottle labelled Pinot Blanc in Alsace may legally contain none of that grape at all. What is likely inside instead?",
      ["Auxerrois", "Chardonnay", "Chasselas", "Sylvaner"], 0,
      "The two are interplanted, blended and sold under the one name. Auxerrois is rounder and lower in acid, so a notably fat, broad Pinot Blanc is usually mostly Auxerrois."),
    Q("Sylvaner, the Pinots and Auxerrois",
      "A white grape of the region shares its name with the black grape that Cahors uses for its wine. Which white grape?",
      ["Auxerrois", "Sylvaner", "Chasselas", "Klevner"], 0,
      "Cahors calls Malbec Auxerrois. The Alsace Auxerrois is a white Pinot relative, born of the same Pinot and Gouais Blanc crossing that gave Chardonnay, and the two share nothing but the word."),
    Q("Sylvaner, the Pinots and Auxerrois",
      "Two label terms differing by a single letter, one ending in -ner and the other in -ener, point to different grapes entirely. Which reading is correct?",
      ["Klevner is Pinot Blanc; Klevener de Heiligenstein is a non-aromatic Traminer",
       "Klevner is Sylvaner; Klevener de Heiligenstein is Pinot Gris",
       "Both are local synonyms for Pinot Blanc",
       "Klevner is Gewurztraminer; Klevener de Heiligenstein is Riesling"], 0,
      "Klevner is simply the Alsatian word for Pinot Blanc. Klevener de Heiligenstein is Savagnin Rose, a plainer cousin of Gewurztraminer grown in a handful of communes in the Bas-Rhin and nowhere else in France."),
    Q("Sylvaner, the Pinots and Auxerrois",
      "The only black grape permitted in the region's still wines gives everything from a pale rose to a barrel-aged red. Which is it?",
      ["Pinot Noir", "Gamay", "Pinot Meunier", "Trollinger"], 0,
      "It was long made pale and served chilled, closer to a rose than a red. Warmer seasons, lower yields and barrel ageing have pushed a generation of growers toward serious reds instead."),
    Q("Sylvaner, the Pinots and Auxerrois",
      "One old variety, as much a table grape as a wine grape, has shrunk to about one percent of the region's plantings and what is left disappears into Edelzwicker. Which?",
      ["Chasselas", "Sylvaner", "Auxerrois", "Muscat Ottonel"], 0,
      "Chasselas is as much a table grape as a wine grape, early and neutral. What is left of it disappears into Edelzwicker, and it is Switzerland rather than Alsace that takes it seriously."),

    # -------------------------------------------- the Grand Cru system (8) ---
    Q("The Grand Cru system",
      "Schlossberg was the first site raised to the region's top tier, a generation after most of France had settled its appellations. In which year?",
      ["1975", "1936", "1962", "1992"], 0,
      "The first decree came in 1975 and named Schlossberg alone. Decrees in 1983 and 1992 took the list to fifty, and Kaefferkopf was added in 2007 to make fifty-one, which leaves this among the youngest classifications in France."),
    Q("The Grand Cru system",
      "Named Grand Cru sites in the region now come to which figure?",
      ["Fifty-one", "Seventeen", "Thirty-three", "Eighty-seven"], 0,
      "Each is separately delimited, with its own boundaries, permitted varieties and maximum crop. The great majority lie in the southern half of the region, in the Haut-Rhin."),
    Q("The Grand Cru system",
      "Four varieties alone may normally be bottled at Grand Cru level. Which set?",
      ["Riesling, Gewurztraminer, Pinot Gris and Muscat",
       "Riesling, Sylvaner, Pinot Blanc and Pinot Noir",
       "Riesling, Gewurztraminer, Pinot Blanc and Chardonnay",
       "Gewurztraminer, Pinot Gris, Auxerrois and Sylvaner"], 0,
      "These are the four noble grapes, and outside a handful of named exceptions the restriction is absolute. Where a single variety is used it is named on the label beside the site, though the sites cleared for a blend name no grape at all. Since the 2022 vintage Pinot Noir may also be bottled as a red at Hengst, Kirchberg de Barr and Vorbourg."),
    Q("The Grand Cru system",
      "Reading an Alsace Grand Cru label beside a Burgundy Grand Cru label, one difference is immediately visible. What is it?",
      ["The Alsace label names a grape variety alongside the vineyard",
       "The Alsace label leaves out the vintage",
       "The Alsace label gives the commune in place of the vineyard",
       "The Alsace label states the yield in hectolitres per hectare"], 0,
      "Varietal labelling is the regional norm and it carries straight into the top tier. Burgundy names the climat and expects you to know the grape from the colour of the wine."),
    Q("The Grand Cru system",
      "Rules at Grand Cru level are tighter than for the regional appellation above all in which respect?",
      ["A lower maximum yield and a higher minimum ripeness at picking",
       "A compulsory period in new oak barrels",
       "A ban on stating the vintage",
       "A requirement to blend at least three varieties"], 0,
      "The decree cuts the permitted crop sharply, raises the minimum must weight and requires the fruit to be picked by hand. Nothing in it says anything about oak."),
    Q("The Grand Cru system",
      "One statement is compulsory on every Grand Cru label that is optional further down the hierarchy. Which?",
      ["The vintage", "The date of bottling",
       "The yield in hectolitres per hectare", "The name of the co-operative"], 0,
      "A Grand Cru must come from a single year and must declare it, alongside the site and the variety. Ordinary Alsace may be blended across vintages and sold without a year."),
    Q("The Grand Cru system",
      "The steepest of the Grands Crus, and the southernmost, rises above Thann on dark volcanic rock. Which is it?",
      ["Rangen", "Kitterle", "Zinnkoepfle", "Kastelberg"], 0,
      "Rangen is the only Grand Cru on volcanic soil, and its slope is severe enough that growers carry washed-out soil back up the hill after storms. The wines are smoky and austere in youth."),
    Q("The Grand Cru system",
      "Two Grands Crus depart from the single-variety rule and permit a blend of grapes in one wine. Which pair?",
      ["Altenberg de Bergheim and Kaefferkopf", "Rangen and Brand",
       "Schlossberg and Hengst", "Rosacker and Geisberg"], 0,
      "Both sites have a long history of co-planted field blends, so their decrees preserve the practice. Everywhere else in the tier the wine must be a single named variety."),

    # --------- Vendanges Tardives and Selection de Grains Nobles (7) ---------
    Q("Vendanges Tardives and Selection de Grains Nobles",
      "Two late-harvest categories were given legal force in 1984, ending a free-for-all in sweet-wine labelling. Which are they?",
      ["Vendanges Tardives and Selection de Grains Nobles",
       "Moelleux and Doux", "Auslese and Beerenauslese",
       "Reserve and Grande Reserve"], 0,
      "The 1984 decree fixed minimum must weights, banned any addition of sugar and required hand picking. Before it, a grower could put almost any word on a rich wine."),
    Q("Vendanges Tardives and Selection de Grains Nobles",
      "A grower has beautifully botrytised Sylvaner and wants to bottle it as Selection de Grains Nobles. What stands in the way?",
      ["Only the four noble varieties may carry either late-harvest term",
       "Sylvaner is incapable of developing noble rot",
       "The wine would have to be sold as Cremant instead",
       "Sylvaner may only be used at Grand Cru level"], 0,
      "Both categories are restricted to Riesling, Gewurztraminer, Pinot Gris and Muscat. Sylvaner does raisin and rot in a warm autumn, but it cannot be labelled either way."),
    Q("Vendanges Tardives and Selection de Grains Nobles",
      "Vendanges Tardives and Selection de Grains Nobles both set minimum must weights, and for two of the four permitted grapes the bar is higher. Which pair faces it?",
      ["Gewurztraminer and Pinot Gris", "Riesling and Muscat",
       "Riesling and Gewurztraminer", "Muscat and Pinot Gris"], 0,
      "Gewurztraminer and Pinot Gris accumulate sugar far more readily, so the law asks more of them before the same words may be used. Riesling and Muscat qualify at a lower level of ripeness."),
    Q("Vendanges Tardives and Selection de Grains Nobles",
      "Pickers go through the rows several times over weeks, taking only shrivelled, fungus-affected berries. Which category demands that?",
      ["Selection de Grains Nobles", "Vendanges Tardives",
       "Cremant d'Alsace", "Edelzwicker"], 0,
      "Selection de Grains Nobles requires noble rot and berry-by-berry selection across successive passes. Vendanges Tardives asks only for late picking, with botrytis permitted rather than required."),
    Q("Vendanges Tardives and Selection de Grains Nobles",
      "A wine labelled Vendanges Tardives goes to a guest who is expecting a dessert wine. What should the server flag first?",
      ["It may be rich but close to dry, since the rules fix ripeness rather than sweetness",
       "It will always be sweeter than a Selection de Grains Nobles",
       "It will be lightly sparkling",
       "It will have been fortified with grape spirit"], 0,
      "The category sets a minimum sugar level in the fruit at picking, not in the finished wine. A producer is free to ferment that sugar out, and some celebrated examples are nearly dry."),
    Q("Vendanges Tardives and Selection de Grains Nobles",
      "Adding sugar to the must is forbidden outright for Vendanges Tardives and Selection de Grains Nobles alike. Why does that ban matter?",
      ["The whole claim of a late-harvest wine is that the concentration happened on the vine",
       "Added sugar would halt the fermentation prematurely",
       "Chaptalisation is illegal everywhere in France",
       "The wines are fermented without cultured yeast"], 0,
      "Chaptalisation is permitted for ordinary Alsace, which is what gives the prohibition teeth here. The sugar has to come from hanging time and noble rot, not from a sack in the cellar."),
    Q("Vendanges Tardives and Selection de Grains Nobles",
      "Vendanges Tardives and Selection de Grains Nobles may not be released for some time after the harvest. For roughly how long?",
      ["About eighteen months", "About six weeks",
       "About six months", "About ten years"], 0,
      "The wines may not be sold until eighteen months have passed, which lets them settle and lets the authorities taste them. Both categories must also pass an official tasting before the term is granted."),

    # ------------------------------ Cremant, blends and the label (8) --------
    Q("Cremant, blends and the label",
      "Second fermentation in the bottle, whole-bunch pressing and nine months on the lees define the region's sparkling appellation, created in 1976. Which is it?",
      ["Cremant d'Alsace", "Mousseux d'Alsace",
       "Cremant de Loire", "Alsace Petillant"], 0,
      "It is made by the same traditional method as Champagne, from hand-picked fruit pressed in whole bunches. Pinot Blanc and Auxerrois form the backbone of most cuvees."),
    Q("Cremant, blends and the label",
      "One grape is authorised in the region for sparkling wine alone and may never appear in a still Alsace bottling. Which?",
      ["Chardonnay", "Auxerrois", "Chasselas", "Muscat Ottonel"], 0,
      "Chardonnay is permitted solely for Cremant d'Alsace, where its acidity and neutrality suit a base wine. As a still varietal it would simply compete with the region's own identity."),
    Q("Cremant, blends and the label",
      "A pink Cremant d'Alsace must be made from one variety and one only. Which?",
      ["Pinot Noir", "Pinot Meunier", "Gamay", "Pinot Gris"], 0,
      "Cremant d'Alsace Rose is entirely Pinot Noir, taken from the skins by pressing or short maceration. Blending finished red wine into white to make the colour is not allowed."),
    Q("Cremant, blends and the label",
      "A blended white sold under an Alsatian word meaning noble mixture may draw on any permitted white grape in any proportion. Which term?",
      ["Edelzwicker", "Gentil", "Klevner", "Reserve Personnelle"], 0,
      "Edel means noble and zwicker means blend, though in practice this is the everyday carafe wine of the region. No minimum proportion of the noble grapes applies, and a vintage is optional."),
    Q("Cremant, blends and the label",
      "A stricter blend term requires at least half the wine to come from the noble varieties, each vinified separately, with a vintage on the label. Which term?",
      ["Gentil", "Edelzwicker", "Klevner", "Cremant d'Alsace"], 0,
      "Gentil sets a floor of fifty percent Riesling, Muscat, Pinot Gris or Gewurztraminer, insists each component would qualify as Alsace in its own right, and sends the finished wine to a tasting panel."),
    Q("Cremant, blends and the label",
      "A tall, slender green bottle is compulsory for the region's still wines, which must also be bottled inside the region. What is that bottle called?",
      ["The flute d'Alsace", "The bocksbeutel", "The clavelin", "The Burgundy bottle"], 0,
      "The flute, sometimes called the vin du Rhin bottle, is written into law along with the requirement to bottle locally. Between them they make an Alsace bottle recognisable across a dining room."),
    Q("Cremant, blends and the label",
      "Naming the grape on the front label is the rule here and the exception in France. What must a varietal Alsace wine contain?",
      ["All of the named variety and nothing else",
       "At least eighty-five percent of the named variety",
       "At least seventy-five percent of the named variety",
       "At least half of the named variety"], 0,
      "There is no blending allowance whatsoever: a wine sold as Riesling is Riesling entire. The apparent exceptions are naming conventions rather than blends, since Muscat covers both permitted Muscats and Pinot Blanc may be Pinot Blanc, Auxerrois or the two together."),
    Q("Cremant, blends and the label",
      "A label reads Reserve, or Cuvee Speciale, and offers nothing further. What weight should that carry?",
      ["None in law, since such terms are unregulated here",
       "It marks a Grand Cru site left unnamed on the label",
       "It guarantees at least two years in barrel",
       "It signals a late-harvest wine"], 0,
      "These are house words with no legal definition in Alsace. The claims that mean something are the appellation, the named site, the variety, the vintage and the two late-harvest terms."),

    # ------------------------------------- soils, history and the table (6) --
    Q("Soils, history and the table",
      "Within a few kilometres a grower may work granite, sandstone, limestone, marl, schist and volcanic rock. What produced that jumble?",
      ["Faulting that dropped the Rhine plain between two blocks of crust",
       "Ash from an extinct chain of volcanoes",
       "Glaciers grinding down a single limestone plateau",
       "River silt laid down over successive floods"], 0,
      "The Rhine valley collapsed along a fault line and the western shoulder was tilted and shattered, exposing rock of wildly different ages side by side. Around a dozen distinct soil types are recognised."),
    Q("Soils, history and the table",
      "Between 1871 and 1918 the region belonged to another country, which pushed its growers toward high volumes of cheap blending wine. Which country?",
      ["Germany", "Switzerland", "Austria", "Belgium"], 0,
      "Annexation after the Franco-Prussian War turned the vineyard into a bulk supplier. Quality returned slowly after 1918, and the region was annexed a second time between 1940 and 1945."),
    Q("Soils, history and the table",
      "Full AOC status arrived here far later than in Bordeaux or Burgundy. In which year?",
      ["1962", "1936", "1945", "1975"], 0,
      "Two annexations and two wars left the region's rules unwritten while the rest of France was being classified in the 1930s. The delay is the reason the Grand Cru tier is younger still."),
    Q("Soils, history and the table",
      "Riquewihr, Kaysersberg and Gewurztraminer all point the same way linguistically. Which heritage?",
      ["Germanic, in the Alemannic dialect called Alsatian",
       "Celtic, surviving in place names alone",
       "Romance, closest to Occitan",
       "Flemish, from the medieval cloth trade"], 0,
      "Alsatian is an Alemannic German dialect, and it supplies most of the village, vineyard and grape names in the region. The wines are French; the vocabulary is not."),
    Q("Soils, history and the table",
      "Biodynamic and organic farming are unusually widespread here by French standards. Which practical factor helps?",
      ["The dry, sheltered climate keeps fungal pressure lower than in damper regions",
       "Organic certification is a legal condition of the appellation",
       "Fungal disease is entirely absent from the region",
       "Subsidies forbid conventional treatments"], 0,
      "Less rain means less mildew and rot, so cutting back sprays is far more practical than on the Atlantic coast. Several of the region's leading estates converted decades ago."),
    Q("Soils, history and the table",
      "A thin base spread with cream, onion and bacon comes out of a wood oven during a cellar visit. What is the dish?",
      ["Tarte flambee, known locally as flammekueche", "Baeckeoffe",
       "Kougelhopf", "Choucroute garnie"], 0,
      "Flammekueche is the Alsatian name and tarte flambee the French one. It is the standard food of a cellar visit, eaten with Sylvaner, Pinot Blanc or a glass of Cremant."),
]
