"""Rank I rewrite - Austria (57 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

The category is built around one idea: Austria is a cool continental country
whose wine all lives on the eastern side of the Alps, where the mountains fall
away and the Pannonian plain blows warm air back at them. That gives the running
order - the land, the rivers and the law first, then the Danube regions west to
east, then the grapes, then Burgenland and the lake that makes sweet wine
inevitable, then Styria and Vienna, and finally the three systems a guest asks
about: Sekt Austria, the Pradikat ladder and the label itself. Stems open with a
rock, a scene at the table, a bottle in the hand or a smell in the glass, and let
the region, grape or term be the answer.

Everything is ASCII: Gruner Veltliner, Blaufrankisch, Niederosterreich,
Pradikat, Qualitatswein, Durnstein, Sudsteiermark.
"""

from lib import Q

CAT = "Austria"
SLUG = "r1-austria"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Climate, land and the Danube", 5),
    ("The wine states and the DAC framework", 7),
    ("The Wachau and its ladder", 7),
    ("Kamptal, Kremstal and the Danube districts", 4),
    ("Weinviertel, Carnuntum and the Thermenregion", 5),
    ("White grapes", 6),
    ("Red grapes and Blaufrankisch country", 6),
    ("Burgenland, botrytis and Rust", 6),
    ("Steiermark and Wien", 4),
    ("Sekt Austria, the Pradikat ladder and the label", 7),
]

BANK = [
    # --------------------------------- climate, land and the Danube (5) ------
    Q("Climate, land and the Danube",
      "Draw a line down the middle of Austria and almost no commercial vineyard falls on the western side of it. What accounts for that?",
      ["The Alps fill the west, and the vines start where the mountains fall away toward the plains of the east",
       "Planting rights are issued only to the eastern federal states",
       "The western half is too wet and too warm for any classic variety",
       "The Danube runs only through the eastern half of the country"], 0,
      "All four wine states sit east or south-east of the Alps, where the land drops and the growing season lengthens. West of that line the ground is high, cold and steep, and the few vines there are a curiosity rather than a trade."),
    Q("Climate, land and the Danube",
      "Terraced vineyards follow a river that enters Lower Austria from the west, passes Krems and Vienna and leaves for Slovakia. Which river, and what does it give the slopes above it?",
      ["The Danube, which moderates temperature and bounces light back up onto the terraces",
       "The Inn, which carries cold Alpine meltwater past the vineyards",
       "The Mur, which drains the southern Styrian hills",
       "The March, which marks the Czech border in the north"], 0,
      "A large body of moving water warms slowly and cools slowly, so the Danube blunts spring frost and holds warmth into the autumn. The Inn and the Mur are Alpine rivers well away from the classic vineyards, and the March forms the eastern border with Slovakia rather than the northern one."),
    Q("Climate, land and the Danube",
      "At roughly forty-seven to forty-eight degrees north, Austrian vineyards share a latitude band with which French wine region?",
      ["Burgundy", "Bordeaux", "The Languedoc", "Champagne"], 0,
      "Chablis sits within half a degree of Vienna and the Cote d'Or a little over a degree further south, which is part of why Austrian growers watch Burgundy so closely. Bordeaux and the Languedoc are considerably further south, and Champagne sits a degree or more north again."),
    Q("Climate, land and the Danube",
      "Wind dropped a deep, pale, fine silt across the Danube valley during the ice ages, and whole hillsides east of the Wachau are buried in it. What is the material?",
      ["Loess", "Slate", "Basalt", "Chalk"], 0,
      "Loess is windblown, calcareous and often many metres deep; it warms quickly and holds water, and it gives a broad, ripe, generous Gruner Veltliner. The lean, taut wines come off weathered primary rock further west, which is a wholly different proposition."),
    Q("Climate, land and the Danube",
      "Mortarless walls of stacked stone hold the soil on the steepest Danube slopes, and growers rebuild them by hand. Beyond stopping the ground from sliding, what do they contribute?",
      ["They soak up the day's heat and give it back to the vines overnight",
       "They channel irrigation water along each terrace",
       "They raise humidity around the fruit and encourage noble rot",
       "They mark the legal boundary of each single vineyard"], 0,
      "Stone is a heat store, so a terrace wall keeps working long after sunset and stretches a ripening day that has nothing to spare at this latitude. Botrytis is the last thing wanted here, since these wines are made dry and clean."),

    # ------------------------ the wine states and the DAC framework (7) ------
    Q("The wine states and the DAC framework",
      "Ask an Austrian grower which federal state he farms in and the answer is nearly always one of four. Which four carry essentially all the country's vineyard?",
      ["Niederosterreich, Burgenland, Steiermark and Wien",
       "Niederosterreich, Oberosterreich, Burgenland and Tirol",
       "Burgenland, Steiermark, Salzburg and Karnten",
       "Wien, Niederosterreich, Vorarlberg and Steiermark"], 0,
      "Lower Austria, Burgenland, Styria and Vienna hold the vineyards; the western and southern states have only token plantings, gathered for labelling purposes under the name Bergland. Vienna is the oddity, a capital with serious commercial vineyard inside its own boundary."),
    Q("The wine states and the DAC framework",
      "Wachau, Kamptal, Kremstal, Weinviertel and Carnuntum are all administered as parts of a single federal state. Which?",
      ["Niederosterreich", "Burgenland", "Steiermark", "Wien"], 0,
      "Lower Austria wraps around Vienna and carries more vineyard than the other three states put together, divided into eight named regions. Burgenland runs south along the Hungarian border and Styria sits in the far south-east."),
    Q("The wine states and the DAC framework",
      "Three letters follow the region name on many Austrian labels and stand for a Latin phrase. What do they abbreviate?",
      ["Districtus Austriae Controllatus", "Denominatio Austriae Classica",
       "Districtus Austriae Classificatus", "Denominazione Austriaca Controllata"], 0,
      "The Latin was chosen so the initials would sit comfortably beside AOC, DOC and DO on an international list. A DAC name may be used only for wine the region has agreed is typical of it, so the letters make a claim about style as well as about place."),
    Q("The wine states and the DAC framework",
      "Before the DAC scheme arrived, a Lower Austrian label led with the grape and treated the region as little more than an address. What did the scheme put in first place instead?",
      ["Typicity of origin, so a regional name is reserved for wines a panel judges characteristic of that place",
       "A ranking of individual sites, so the finest Rieden could be named on a classified label",
       "A yield ceiling set nationally, the same for every region and every variety",
       "A minimum time in cask before release, lengthening at each step up the ladder"], 0,
      "The model is Romance rather than Germanic: the name of the place does the work, not the name of the grape. Each DAC then decides which varieties and styles may carry its name, which is why the permitted grapes differ sharply from one to the next. Site ranking, yields and ageing are all settled region by region and came later; what the scheme changed first was whose name goes on the front of the label."),
    Q("The wine states and the DAC framework",
      "A Kamptal grower ferments a Sauvignon Blanc, a variety his DAC does not permit. What origin may that wine claim on its label?",
      ["Niederosterreich, the federal state, because the DAC name is closed to it",
       "Kamptal, because the fruit was unquestionably grown there",
       "Austria and nothing narrower, because the wine has lost quality status",
       "Kamptal Landwein, a lower tier of the same name"], 0,
      "A wine that falls outside its DAC drops back to the wider federal-state name, and that is precisely what makes the DAC name worth anything. The wine remains Qualitatswein and remains Kamptal fruit in fact; it simply may not say so."),
    Q("The wine states and the DAC framework",
      "Origin can be drawn at three widths inside an Austrian DAC, tightening from the whole district down to one named site. What are those three steps called?",
      ["Gebietswein, Ortswein, Riedenwein", "Gutswein, Ortswein, Grosse Lage",
       "Klassik, Reserve, Grosse Reserve", "Landwein, Qualitatswein, Pradikatswein"], 0,
      "Gebiet is the district, Ort the village and Ried the individual vineyard, and yields and ripeness requirements tighten at each step up. Gutswein, Ortswein and Grosse Lage is Germany's VDP pyramid, and Klassik, Reserve and Grosse Reserve was the Austrian sparkling ladder before its 2022 rebranding. Both look similar to the DAC steps and mean something else entirely."),
    Q("The wine states and the DAC framework",
      "Four broad tiers stack Austrian wine law from the bottom upward. Which sequence is correct?",
      ["Wein, Landwein, Qualitatswein, Pradikatswein",
       "Landwein, Wein, Qualitatswein, Pradikatswein",
       "Wein, Qualitatswein, Landwein, Pradikatswein",
       "Wein, Landwein, Pradikatswein, Qualitatswein"], 0,
      "The upper two tiers must come from a named region and pass a state analysis and a blind tasting before they receive an inspection number. Pradikatswein is then subdivided by must weight, and enrichment is forbidden throughout it."),

    # ------------------------------------ the Wachau and its ladder (7) ------
    Q("The Wachau and its ladder",
      "A blue baroque church tower and the ruined castle where Richard the Lionheart was held look down over terraced vines beside the Danube. Which region?",
      ["Wachau", "Kamptal", "Wagram", "Traisental"], 0,
      "Durnstein sits in the middle of the Wachau, a thirty-kilometre stretch of river between Melk and Krems that UNESCO lists as a cultural landscape. The terraces are cut into weathered gneiss and granulite, and every operation on them is done by hand."),
    Q("The Wachau and its ladder",
      "Two bottles come from one Wachau grower: one off weathered gneiss high on the terraces, one off deep loess near the river. What should a guest expect to taste?",
      ["The primary-rock wine leaner and tauter, the loess wine broader and riper",
       "The primary-rock wine broader and riper, the loess wine leaner and tauter",
       "The loess wine sweet and the primary-rock wine dry",
       "No difference worth naming, since both were made in the same cellar"], 0,
      "Urgestein is the local word for the ancient crystalline rock, and it holds almost no water, so the vine struggles and the wine stays tight and stony. Loess is deep and retentive, and it supplies the flesh that Wachau Gruner Veltliner is loved for."),
    Q("The Wachau and its ladder",
      "The three ripeness words on a Wachau label are no part of Austrian wine law. Who set them, and under what?",
      ["Vinea Wachau, a growers' association, under its own Codex Wachau",
       "The federal wine authority, under the wine law of 1985",
       "The European Union, under the region's protected designation",
       "The Klosterneuburg research institute, under its must-weight scale"], 0,
      "The association formed in 1983 and its rules go well beyond the law: fruit only from the Wachau, no enrichment, no concentration and nothing added for aroma. Membership is voluntary, so a Wachau wine can be superb and carry none of the three words."),
    Q("The Wachau and its ladder",
      "Wachau growers grade ripeness by the alcohol in the finished wine rather than by the sugar in the must. What makes that the sensible measure there?",
      ["The wines are fermented dry, so ripeness ends up as alcohol rather than as residual sugar",
       "Must weight cannot be measured accurately on primary-rock soils",
       "Austrian law forbids must-weight terms anywhere in Lower Austria",
       "The three terms record vineyard altitude rather than ripeness at all"], 0,
      "Germany's ladder works because the sugar survives into the bottle where it can be tasted; a bone-dry wine has spent all of it. Steinfeder, Federspiel and Smaragd therefore read as a scale of weight and power on the palate."),
    Q("The Wachau and its ladder",
      "Lightest of the Wachau's three categories, capped at eleven and a half percent alcohol and named after a feathery grass that seeds itself among the terraces. Which term?",
      ["Steinfeder", "Federspiel", "Smaragd", "Kabinett"], 0,
      "Stipa pennata, the feather grass, colonises the dry stone walls, and the wine named after it is meant to be drunk young and cold. Federspiel and Smaragd sit above it, and Kabinett belongs to the national system rather than to the Wachau."),
    Q("The Wachau and its ladder",
      "The dinner-table weight of Wachau white runs between eleven and a half and twelve and a half percent alcohol. Which of the region's terms marks that band?",
      ["Federspiel", "Steinfeder", "Smaragd", "Ausbruch"], 0,
      "Federspiel takes its name from the lure a falconer swings to call the bird back, a nod to the sport once practised on these cliffs. It is the classic food weight of the region: dry, precise and never heavy."),
    Q("The Wachau and its ladder",
      "An emerald green lizard basking on a terrace wall lent its name to the ripest of the Wachau categories. Which category, and what does it demand?",
      ["Smaragd, which requires at least twelve and a half percent alcohol",
       "Smaragd, which requires botrytis-affected fruit",
       "Steinfeder, which requires at least twelve and a half percent alcohol",
       "Federspiel, which requires hand harvesting above all else"], 0,
      "Smaragd fruit is picked last and off the warmest terraces, and the wines are powerful, dry and capable of decades in bottle. Noble rot is not what any of these categories is chasing, which is why the botrytis version of the answer fails."),

    # ----------------- Kamptal, Kremstal and the Danube districts (4) --------
    Q("Kamptal, Kremstal and the Danube districts",
      "An outcrop of ancient desert sandstone above the village of Zobing carries some of the finest Riesling in the country. Name the site and its region.",
      ["Heiligenstein, in the Kamptal", "Achleiten, in the Wachau",
       "Loibenberg, in the Kremstal", "Spitzerberg, in Carnuntum"], 0,
      "The Heiligenstein is Permian sandstone laid down in a desert some 270 million years ago, shot through with volcanic material, and it is unlike anything around it. Achleiten and Loibenberg are real sites but both sit in the Wachau, and the Spitzerberg is a limestone ridge planted to Blaufrankisch."),
    Q("Kamptal, Kremstal and the Danube districts",
      "Downstream of the Wachau the terraces give way to thick loess around a riverside town, with a baroque abbey looking across from the hill opposite. Which region borrows the town's name?",
      ["Kremstal", "Kamptal", "Wagram", "Weinviertel"], 0,
      "Krems stands where the Wachau ends, and Gottweig Abbey occupies its hill south of the river. The western edge of the region still works primary rock, but loess is what most of it grows on, and loess is what Gruner Veltliner does best."),
    Q("Kamptal, Kremstal and the Danube districts",
      "Limestone and conglomerate underlie a small region on a Danube tributary south of Krems, which is unusual company for Gruner Veltliner. Which region?",
      ["Traisental", "Kamptal", "Wagram", "Carnuntum"], 0,
      "The Traisen flows north into the Danube, and loess covers most of the valley as it does elsewhere along the river. What sets the region apart is what lies under it: a spine of lime-rich conglomerate, Alpine gravel cemented hard, running the length of the western slope and breaking the surface on the best sites. The wines come out firm and stony, with a chalkier edge than the Danube regions on either side of them."),
    Q("Kamptal, Kremstal and the Danube districts",
      "One Lower Austrian region is effectively a single enormous loess terrace north of the Danube, and it is the last stronghold of Roter Veltliner. Which?",
      ["Wagram", "Kamptal", "Thermenregion", "Weinviertel"], 0,
      "The Wagram is a step in the landscape rather than a hill, with loess many metres deep along its face. Roter Veltliner is an old, thick-skinned variety that survives almost nowhere else and gives a broad, nutty, low-acid wine."),

    # --------------- Weinviertel, Carnuntum and the Thermenregion (5) --------
    Q("Weinviertel, Carnuntum and the Thermenregion",
      "Rows of low cellar doors line a lane running out of a village north of Vienna, with no houses attached to any of them. What is the lane called?",
      ["A Kellergasse", "A Buschenschank", "A Ried", "A Weinstrasse"], 0,
      "Press houses and cellars were dug into the loess outside the village, clear of the fire risk and the smell, and they line up into whole streets of them. A Buschenschank is a tavern selling a grower's own wine, a Ried is a single vineyard and a Weinstrasse is a signposted tourist route."),
    Q("Weinviertel, Carnuntum and the Thermenregion",
      "Between the Danube and the Czech border lies the country's most extensive stretch of vineyard, on rolling loess, and its name states plainly what it grows. Which region?",
      ["Weinviertel", "Waldviertel", "Weststeiermark", "Wagram"], 0,
      "Weinviertel means wine quarter; the Waldviertel immediately west of it means forest quarter and grows almost none. This was the region chosen to launch the whole DAC system with the 2002 vintage, on peppery dry Gruner Veltliner."),
    Q("Weinviertel, Carnuntum and the Thermenregion",
      "A Roman legionary town on the Danube east of Vienna gave its name to a modern wine region built on red wine. Which region?",
      ["Carnuntum", "Thermenregion", "Leithaberg", "Weinviertel"], 0,
      "Carnuntum was a garrison and then a provincial capital, and its ruins stand among the vineyards at Petronell. Zweigelt leads the plantings at better than a quarter and Blaufrankisch is the other red the DAC is built on, though Gruner Veltliner is the second most planted variety and close to half the region is white. The limestone ridge of the Spitzerberg is its most admired site."),
    Q("Weinviertel, Carnuntum and the Thermenregion",
      "Spa towns and hot springs south of Vienna gave a wine region its name, and Gumpoldskirchen is its best-known village. Which region?",
      ["Thermenregion", "Carnuntum", "Kremstal", "Rosalia"], 0,
      "Thermen means thermal baths, and Baden bei Wien has been taking the waters since Roman times. The northern half grows Zierfandler and Rotgipfler around Gumpoldskirchen; the southern half turns to Sankt Laurent and Pinot Noir on gravel."),
    Q("Weinviertel, Carnuntum and the Thermenregion",
      "Warm dry air pushes west off the Hungarian plain and reaches the vineyards around the Neusiedler See and east of Vienna. What is that influence called?",
      ["Pannonian", "Atlantic", "Mediterranean", "Foehn"], 0,
      "The Pannonian basin behaves like a small continent: hot summers, cold winters and little rain, which is what lets red grapes ripen this far north. Cold air draining off the wooded hills at night holds the acidity in place, and that daily swing is the making of eastern Austrian wine."),

    # ---------------------------------------------------- white grapes (6) ---
    Q("White grapes",
      "White pepper, green lentil, grapefruit and a faintly bitter almond finish turn up again and again in one Austrian variety. Which?",
      ["Gruner Veltliner", "Welschriesling", "Weissburgunder", "Neuburger"], 0,
      "The pepper comes from rotundone, the same compound behind the spice of cool-climate Syrah, and growers call the note Pfefferl. Gruner covers about a third of Austria's vineyard and ranges from a light spritzy carafe wine to something that will hold twenty years."),
    Q("White grapes",
      "Two Austrian varieties share the Veltliner name, one of them green and one of them red. How are the two related?",
      ["Hardly at all, since they are separate varieties whose names happen to coincide",
       "The red is a colour mutation of the green, as Pinot Gris is of Pinot Noir",
       "The green is a crossing of the red with Riesling",
       "They are one variety, picked early for one name and late for the other"], 0,
      "Gruner Veltliner turned out to be a seedling of Traminer and an obscure vine found at St Georgen in Burgenland. Roter Veltliner is a quite different old variety and is itself a parent of Neuburger and Rotgipfler."),
    Q("White grapes",
      "One high-acid Austrian white borrows Riesling's name without sharing any of its parentage, and appears both as a light Styrian carafe wine and as a great botrytis wine in Burgenland. Which?",
      ["Welschriesling", "Rotgipfler", "Muskateller", "Neuburger"], 0,
      "Welschriesling is grown right across central Europe under other names and has no relationship whatever to the Rhine grape. Its ferocious acidity is exactly what makes it useful when sugars climb, which is why so much Burgenland Beerenauslese is built on it."),
    Q("White grapes",
      "A Styrian wine list offers Morillon beside its Sauvignon Blanc. What is the guest actually being sold?",
      ["Chardonnay", "Pinot Blanc", "Muscat Blanc", "Melon de Bourgogne"], 0,
      "Morillon is the Styrian name for Chardonnay and nothing else, most often made there in a taut unoaked style. Weissburgunder appears on the same lists and is Pinot Blanc under another name, a genuinely different grape from Chardonnay rather than a third synonym for it."),
    Q("White grapes",
      "Two white varieties, one of them also called Spatrot, grow almost nowhere outside the hills south of Vienna and are frequently blended with one another. Which pair?",
      ["Zierfandler and Rotgipfler", "Neuburger and Roter Veltliner",
       "Muskateller and Traminer", "Rotgipfler and Blauburger"], 0,
      "Zierfandler, or Spatrot, brings acidity and Rotgipfler brings weight and a spicy perfume, and Gumpoldskirchen built its name on the combination. Zierfandler has nothing to do with Zinfandel despite the look of the word, and Blauburger is a red grape."),
    Q("White grapes",
      "Set an Austrian Riesling beside a Mosel Riesling of comparable quality. What is the most reliable difference?",
      ["The Austrian will be dry and appreciably higher in alcohol",
       "The Austrian will be noticeably sweeter and lower in alcohol",
       "The Austrian will have been aged in new oak",
       "The Austrian will be softer and lower in acidity"], 0,
      "Austria finishes almost all its Riesling dry, and the Wachau and Kamptal ripen it to twelve or thirteen percent on stony terraces. German Riesling covers the whole sweetness range and on the Mosel is frequently under nine percent."),

    # --------------------------- red grapes and Blaufrankisch country (6) ----
    Q("Red grapes and Blaufrankisch country",
      "A guest wants a light, juicy red with soft tannin, something that will take twenty minutes in the fridge before lunch. Which Austrian variety fits best?",
      ["Zweigelt", "Blaufrankisch", "Cabernet Sauvignon", "Syrah"], 0,
      "Zweigelt was bred at Klosterneuburg in 1922 by crossing Sankt Laurent with Blaufrankisch, and it inherited the softness of one and the colour of the other. It is the most planted red in the country and the everyday red of the Heuriger."),
    Q("Red grapes and Blaufrankisch country",
      "Cross into Germany and the same black grape is called Lemberger; cross into Hungary and it is Kekfrankos. Sour cherry, peppery spice, high acid and real tannic grip. What does Austria call it?",
      ["Blaufrankisch", "Zweigelt", "Sankt Laurent", "Blauer Portugieser"], 0,
      "Blaufrankisch is the serious red of Burgenland and the one that changes most from soil to soil, lean on the iron slate of the far south and broad on Mittelburgenland clay. It is also one of Zweigelt's two parents."),
    Q("Red grapes and Blaufrankisch country",
      "Dark cherry, a silky texture, and a name taken from the saint's day in mid-August when the berries begin to colour. Which Austrian red?",
      ["Sankt Laurent", "Blauburger", "Zweigelt", "Blauer Wildbacher"], 0,
      "Sankt Laurent has long been thought a relative of Pinot Noir and behaves like one: thin skins, early ripening and a habit of setting fruit unevenly. The Thermenregion around Tattendorf and the northern shore of the Neusiedler See are its heartlands."),
    Q("Red grapes and Blaufrankisch country",
      "Deep heavy clay in a strip of Burgenland along the Hungarian border grows so much of one variety that the district is nicknamed after it. Which district?",
      ["Mittelburgenland", "Neusiedlersee", "Leithaberg", "Eisenberg"], 0,
      "Growers call it Blaufrankischland, and Horitschon, Deutschkreutz and Neckenmarkt are its villages. The clay holds water and yields a fuller, darker, riper Blaufrankisch than the thinner soils further south."),
    Q("Red grapes and Blaufrankisch country",
      "Iron in the soil gave one southern Burgenland district its name, and it turns out the leanest, most peppery Blaufrankisch in the country. Which?",
      ["Eisenberg", "Rosalia", "Carnuntum", "Mittelburgenland"], 0,
      "Eisen is iron, and the slate there is stained rusty with it. The wines are lighter in body and higher in acid than Mittelburgenland's, which is the clearest demonstration Austria offers that this grape reads its site."),
    Q("Red grapes and Blaufrankisch country",
      "Limestone and mica schist on a range of hills west of the Neusiedler See carry a DAC covering both whites and a red off the same ground. Which?",
      ["Leithaberg", "Neusiedlersee", "Mittelburgenland", "Eisenberg"], 0,
      "The Leithagebirge separates the lake from the Vienna basin, and its DAC takes Gruner Veltliner, Weissburgunder, Chardonnay and Neuburger for white and Blaufrankisch for red. Rust sits at the southern end of the same shore with a DAC of its own for sweet wine."),

    # ------------------------------- Burgenland, botrytis and Rust (6) -------
    Q("Burgenland, botrytis and Rust",
      "A lake on the Hungarian border spreads across a huge area yet averages barely a metre in depth, ringed by a wide belt of reeds. What does it do for the wines grown around it?",
      ["It lifts autumn humidity and mist, so noble rot arrives almost every year",
       "It cools the vineyards enough to hold the harvest back to December",
       "It supplies the irrigation the sandy eastern shore depends on",
       "It reflects enough light to ripen Cabernet Sauvignon fully"], 0,
      "The Neusiedler See is a steppe lake with no real outflow, and reeds cover about half of it. Warm shallow water and reed beds put moisture into the autumn air, and Botrytis cinerea takes hold in the vineyards on the eastern shore in nearly every vintage."),
    Q("Burgenland, botrytis and Rust",
      "Sandy flats on the eastern side of the lake are dotted with shallow salt ponds and hold the villages of Illmitz and Apetlon. What is that corner called?",
      ["The Seewinkel", "The Leithaberg", "The Rosalia", "The Wagram"], 0,
      "Seewinkel means the corner of the lake, and its water table sits so close to the surface that mist forms readily. It is among the most dependable places in Europe for botrytis-affected sweet wine, which is why the two villages are famous out of all proportion to their size."),
    Q("Burgenland, botrytis and Rust",
      "Morning fog burns off into warm dry afternoons through October beside the lake. Why does a sweet-wine grower need that alternation rather than damp alone?",
      ["The damp lets noble rot take hold, and the dry warmth stops it turning to grey rot while the berries shrivel",
       "The damp swells the berries and the dry afternoons then split them open",
       "The fog freezes the water in the berry and the afternoon thaws the sugar out",
       "The alternation kills the wild yeast, so fermentation can be controlled"], 0,
      "Botrytis needs moisture to infect and dryness to concentrate; unbroken wet turns the same fungus into grey rot, which ruins the crop. Water evaporates through the punctured skin, so sugar, acid and flavour all climb together."),
    Q("Burgenland, botrytis and Rust",
      "Storks nest on the chimneys of a small free city on the western shore of the lake, and its name attaches to a historic sweet wine. Which town?",
      ["Rust", "Illmitz", "Gols", "Eisenstadt"], 0,
      "Rust bought its standing as a free city in 1681, reputedly with a payment partly in wine, and has guarded the Ausbruch name ever since. Illmitz and Gols lie on the far shore and Eisenstadt is the provincial capital inland."),
    Q("Burgenland, botrytis and Rust",
      "Shrivelled botrytis berries are often too dry to yield anything under the press. What did the traditional Ruster method add to get them moving?",
      ["Fresh must or wine from healthy grapes of the same vineyard",
       "Neutral grape spirit, as in a fortified wine",
       "Water heated enough to dissolve the sugar out",
       "Sugar syrup made from concentrated must"], 0,
      "Ausbruch sits between Beerenauslese and Trockenbeerenauslese on the Austrian must-weight ladder, and its name comes from breaking the shrivelled berries out of the bunch. Rust's own designation no longer allows the addition, so the modern wine is pressed from the dried fruit alone."),
    Q("Burgenland, botrytis and Rust",
      "Bunches are laid out on reed mats or straw and left to dry for months before they see a press. Which Austrian Pradikat does that produce?",
      ["Strohwein, also called Schilfwein", "Eiswein", "Ausbruch", "Beerenauslese"], 0,
      "Stroh is straw and Schilf is reed, and the lake shore has no shortage of the latter. The law requires the fruit to rest on straw or reeds until it reaches the necessary must weight, generally three months or more, and the concentration comes from plain evaporation rather than from any fungus."),

    # ------------------------------------------- Steiermark and Wien (4) -----
    Q("Steiermark and Wien",
      "Steep green hills on the Slovenian border grow the Sauvignon Blanc that made Styria's reputation. Which region?",
      ["Sudsteiermark", "Weststeiermark", "Vulkanland Steiermark", "Kremstal"], 0,
      "Southern Styria works slopes so sharp they are farmed more like Alpine meadows than vineyards, and Sauvignon Blanc and Morillon are its calling cards. The Vulkanland to the east sits on extinct volcanoes and leans to Traminer, while Weststeiermark is Schilcher country."),
    Q("Steiermark and Wien",
      "A ferociously tart pink wine pressed from Blauer Wildbacher is the speciality of western Styria. What is it called?",
      ["Schilcher", "Sturm", "Uhudler", "Bergwein"], 0,
      "Schilcher is bracing enough to divide a room and is drunk locally almost to the exclusion of anything else. Sturm is part-fermented must sold in autumn, Uhudler is a curiosity of southern Burgenland made from hybrid vines, and Bergwein means wine off slopes steeper than twenty-six percent."),
    Q("Steiermark and Wien",
      "Several white varieties share one Viennese vineyard, are picked on the same day and go into the vat together. What must be true of the mix for the city's DAC?",
      ["At least three varieties, with the largest no more than half and the third at least a tenth",
       "Exactly three varieties in equal proportion",
       "Any number of varieties, provided each is fermented separately first",
       "At least five varieties, all of them indigenous to Austria"], 0,
      "Wiener Gemischter Satz is a field blend, interplanted and co-fermented, which is a different animal from a cuvee assembled after the fact. Vienna is the only major capital still farming serious commercial vineyard inside its own boundary."),
    Q("Steiermark and Wien",
      "A bunch of pine branches hangs over a doorway on the edge of Vienna and the grower inside is pouring his own wine by the jug. What is the establishment called?",
      ["A Heuriger", "A Kellergasse", "A Vinothek", "A Weingut"], 0,
      "The branch means ausg'steckt, hung out, and signals that this grower is open now; the right to sell one's own wine on the premises rests on an imperial decree of 1784. Heuriger is also the wine itself, meaning this year's, and it keeps the name until Saint Martin's Day the following November."),

    # ------------- Sekt Austria, the Pradikat ladder and the label (7) -------
    Q("Sekt Austria, the Pradikat ladder and the label",
      "Austrian sparkling wine of protected origin climbs three steps, each demanding more of the grower than the last. What are they, from the bottom up?",
      ["Sekt Austria, Sekt Austria Reserve, Sekt Austria Grosse Reserve",
       "Gebietswein, Ortswein, Riedenwein",
       "Steinfeder, Federspiel, Smaragd",
       "Sekt Austria Klassik, Sekt Austria Reserve, Sekt Austria Prestige"], 0,
      "Each step tightens origin, method and time on the lees together, so the pyramid is a single ladder rather than three separate rules; the entry tier was called Klassik until the rebranding to Sekt Austria in 2022 and now carries no qualifier at all. Gebietswein, Ortswein and Riedenwein is the still-wine DAC pyramid, and Steinfeder, Federspiel and Smaragd belongs to the Wachau; neither has anything to do with sparkling wine."),
    Q("Sekt Austria, the Pradikat ladder and the label",
      "Thirty-six months on the lees, a second fermentation in the bottle, and fruit harvested and pressed in one named municipality. Which tier of Sekt Austria is that?",
      ["Sekt Austria Grosse Reserve", "Sekt Austria Reserve", "Sekt Austria", "Riedensekt"], 0,
      "Grosse Reserve tops the pyramid at thirty-six months on the lees and is the only tier that requires the grapes to be harvested and pressed inside a single Gemeinde, with a named Ried permitted on top of that. Reserve sits below it at eighteen months and takes the federal state as its origin, though it too may name a municipality; both must be hand-harvested and bottle-fermented."),
    Q("Sekt Austria, the Pradikat ladder and the label",
      "Entry-level Sekt Austria may be produced in tank rather than in bottle, but it still owes a minimum time on its lees. How long?",
      ["Six months", "Nine months", "Eighteen months", "Thirty-six months"], 0,
      "The base tier draws its fruit from a single federal state and permits any method suited to sparkling wine: six months on the lees if the wine ferments in tank, nine if it ferments in the bottle. The eighteen and thirty-six month figures belong to Reserve and Grosse Reserve, both of which must ferment in the bottle they are sold in."),
    Q("Sekt Austria, the Pradikat ladder and the label",
      "Every bottle of Austrian quality wine wears a narrow red-white-red strip across the capsule. What does it certify?",
      ["That the wine passed a state analysis and blind tasting and carries an inspection number",
       "That the wine was bottled at the estate that grew it",
       "That the wine is dry",
       "That the wine is certified organic"], 0,
      "The banderole carries the national colours and pairs with the Staatliche Prufnummer printed on the label. The controls behind it were rebuilt after the adulteration scandal of 1985 and are now among the strictest anywhere in the wine world."),
    Q("Sekt Austria, the Pradikat ladder and the label",
      "An Austrian label and a German label both read Kabinett, yet the word does not sit on the same rung in the two systems. Where does Austria place it?",
      ["As a category of Qualitatswein, below the Pradikat levels rather than the lowest of them",
       "As the lowest Pradikat, exactly as Germany does",
       "Above Auslese but below Beerenauslese",
       "As a term reserved for sparkling wine"], 0,
      "Austrian Kabinett is unchaptalised Qualitatswein with a ceiling on both alcohol and residual sugar, and the Pradikat ladder starts above it at Spatlese. The ladders differ at the top as well: Austria recognises Ausbruch and Strohwein, which German law does not."),
    Q("Sekt Austria, the Pradikat ladder and the label",
      "Ripeness at harvest is read in Austria on a scale named after a monastery north of Vienna. Which scale?",
      ["Klosterneuburger Mostwaage", "Oechsle", "Baume", "Brix"], 0,
      "One degree KMW is one gram of sugar in a hundred grams of must, so the figure runs at roughly a fifth of the German Oechsle reading for the same juice. Klosterneuburg also houses a school of viticulture founded in 1860, where Zweigelt was bred."),
    Q("Sekt Austria, the Pradikat ladder and the label",
      "One short word must stand in front of a single-vineyard name on an Austrian label, so a site cannot be mistaken for a village. Which word?",
      ["Ried", "Lage", "Ort", "Weingarten"], 0,
      "Ried is Austrian dialect for a delimited parcel of vineyard, and the wine law requires it to precede the name: Ried Heiligenstein, Ried Achleiten. Ort means place and belongs to the village tier, while Lage is not the required prefix; Austrian law has since 2023 provided for Erste Lage and Grosse Lage as classifications that sit on top of a Riedenwein rather than replacing the word Ried."),
]
