"""Rank I rewrite - Australia (57 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

The category is built around the two facts that shape the country. The first is
physical: almost every vine sits in a temperate crescent along the southern and
south-eastern rim, because the interior is desert and the north is tropical, so
coolness has to be found in altitude and sea air rather than in latitude. The
second is legal: Australia registers Geographical Indications, which say where
and never how, so nothing on the label constrains grape, yield or ageing. That
gives the running order - the crescent and its climates first, then the GI
system and what a label may claim, then the states and their leading regions
from South Australia outward, and finally the grapes, styles and closures that
cut across all of them. Stems lead with a glass on the table, a soil, a border
inspection or a scene in the vineyard, and let the region, grape or term be the
answer.

Everything is ASCII: Rhone, Mourvedre, Muscat a Petits Grains, Carinena.
"""

from lib import Q

CAT = "Australia"
SLUG = "r1-australia"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Vineyard geography and climate", 6),
    ("Geographical Indications and labelling", 6),
    ("Barossa and Eden Valley", 7),
    ("Clare, McLaren Vale and the Adelaide Hills", 6),
    ("Coonawarra and the Limestone Coast", 5),
    ("Victoria", 7),
    ("New South Wales", 5),
    ("Western Australia", 5),
    ("Tasmania", 4),
    ("Grapes, styles and closures", 6),
]

BANK = [
    # ------------------------------- vineyard geography and climate (6) ------
    Q("Vineyard geography and climate",
      "Drive north from Adelaide, or inland from any coast, and the vines give out long before the desert begins. What pins Australian viticulture to a crescent along the southern and south-eastern rim of the continent?",
      ["The interior is too hot and dry and the tropical north too wet, so only the temperate southern margin suits the vine",
       "Federal law restricts vineyard planting to land within one hundred kilometres of the coast",
       "The soils of the interior are too fertile to give quality fruit",
       "Phylloxera has made the whole inland unplantable"], 0,
      "Most of the continent is desert or tropical savannah, and a vine needs a warm but not relentless season plus a winter cold enough for dormancy. That combination exists only around the cooler southern rim and on the highlands standing behind it."),
    Q("Vineyard geography and climate",
      "Reading a map of the country's vineyards from north to south, almost every one falls inside a band roughly twelve degrees of latitude wide. Which band?",
      ["About thirty-one to forty-three degrees south",
       "About fifteen to twenty-seven degrees south",
       "About twenty to thirty-two degrees south",
       "About thirty-eight to fifty degrees south"], 0,
      "The Hunter and the Swan sit at the warm northern end and southern Tasmania at the cool southern one. Mirrored into the northern hemisphere that band would run from North Africa to Provence, which is why Australia's cool sites are usually made rather than found."),
    Q("Vineyard geography and climate",
      "Orange sits at a latitude that ought to bake its fruit, yet the Chardonnay comes in with acidity intact and alcohol moderate. What is doing the cooling?",
      ["Height: the vineyards climb the flanks of an extinct volcano, high enough for genuinely cold nights",
       "The Southern Ocean, which lies only a few kilometres away",
       "Persistent cloud drifting down from the tropics",
       "Irrigation drawn from cold mountain rivers"], 0,
      "Every hundred metres of elevation costs roughly half a degree of mean temperature, and nights at height fall further still. Australia uses altitude the way Europe uses latitude, which is how a region well north of Melbourne ends up cooler than one south of it."),
    Q("Vineyard geography and climate",
      "Three hot districts strung along one inland river system depend entirely on irrigation and supply the fruit behind a great deal of everyday Australian wine. Which three?",
      ["Riverland, Murray Darling and Riverina",
       "Barossa Valley, Clare Valley and Eden Valley",
       "Yarra Valley, Mornington Peninsula and Geelong",
       "Margaret River, Great Southern and Pemberton"], 0,
      "The Murray and the Murrumbidgee make farming possible in country otherwise too dry for it. Their fruit is ripe, soft and cheap to grow, and it is the backbone of the multi-region blends sold under the broadest Geographical Indications."),
    Q("Vineyard geography and climate",
      "A grower in Bordeaux would need a dispensation to run water to the vines; across most of Australia a dripline is standard equipment. What explains the difference?",
      ["Rainfall is low and falls mostly outside the growing season, so irrigation is legal and often the only way to farm at all",
       "Australian law obliges growers to irrigate in order to guarantee a yield",
       "Australian soils hold no water whatever the rainfall",
       "European rules ban irrigation everywhere, while Australia has no water regulation at all"], 0,
      "Much of the Australian vineyard receives less growing-season rain than a vine needs, and a dry summer is the norm rather than a crisis. Water there is regulated as a scarce resource rather than treated as a quality question, which inverts the European approach."),
    Q("Vineyard geography and climate",
      "Hundred-year-old Shiraz still stands on its own roots in South Australia, and the state stops travellers at its border to check for vine cuttings, vineyard equipment and even soiled boots. What is being kept out?",
      ["Phylloxera, which has never reached the state",
       "Pierce's disease, which arrived late last century",
       "Downy mildew, which the dry climate otherwise prevents",
       "Fruit fly, which attacks the ripening bunches"], 0,
      "Phylloxera reached Victoria and New South Wales in the nineteenth century but never crossed into South Australia, so its vineyards were never grafted onto American rootstock. That quarantine is the reason some of the oldest producing vines on earth are South Australian."),

    # ------------------------ Geographical Indications and labelling (6) -----
    Q("Geographical Indications and labelling",
      "Barossa Valley appears in large letters on a front label, yet nothing on the bottle commits the producer to a grape, a yield, a ripeness minimum or a day in oak. What does an Australian Geographical Indication actually promise?",
      ["Only that the fruit was grown in the named place",
       "That the wine followed a set of rules on variety and ageing written for that place",
       "That the wine passed an official tasting panel before release",
       "That yields were held below a stated maximum"], 0,
      "A GI is a statement of origin and nothing else, which is the fundamental difference between this system and a French appellation. What is planted, how it is farmed and how it is made are left entirely to the producer, so the name tells you where and never how."),
    Q("Geographical Indications and labelling",
      "High Eden lies inside Eden Valley, which lies inside Barossa, which lies inside South Australia. Reading those four from the smallest outward, what are the tiers called?",
      ["Subregion, region, zone, state",
       "Region, subregion, zone, state",
       "Commune, region, zone, state",
       "Subregion, zone, region, state"], 0,
      "A region must demonstrate measurable homogeneity and a minimum scale of production, and a subregion must be more homogeneous still. A zone has to satisfy neither test, which is why a zone can be enormous and tell a buyer very little."),
    Q("Geographical Indications and labelling",
      "One Australian Geographical Indication reaches across state lines and turns up on inexpensive bottles blended from fruit picked a thousand kilometres apart. Which?",
      ["South Eastern Australia", "Limestone Coast",
       "Central Ranges", "Mount Lofty Ranges"], 0,
      "South Eastern Australia takes in the whole of New South Wales, Victoria and Tasmania along with the grape-growing parts of Queensland and South Australia. It exists to give the cross-state blend a legal name, and it is why one brand can hold its style through a difficult vintage anywhere."),
    Q("Geographical Indications and labelling",
      "A winemaker wants Coonawarra, a single vintage year and Cabernet Sauvignon all printed on the front label. Each of those three claims must hold true of at least how much of the wine?",
      ["Eighty-five percent", "Seventy-five percent",
       "Ninety-five percent", "All of it"], 0,
      "One threshold covers origin, vintage and variety alike, so a Coonawarra Cabernet may legitimately carry fifteen percent of another grape from another place. The claim is verified through the winery's records rather than by tasting the wine."),
    Q("Geographical Indications and labelling",
      "A label reads Semillon Sauvignon Blanc rather than Sauvignon Blanc Semillon, and the wine inside is those same two grapes either way. What does the running order tell a buyer?",
      ["The varieties are listed in descending order of how much of each the blend holds",
       "The first grape named was the first to be fermented",
       "The first grape came from the named region and the second from elsewhere",
       "The order is decorative and carries no meaning at all"], 0,
      "Australia requires a multi-variety label to run from the largest component down, so the name is a recipe read left to right. A wine labelled Shiraz Cabernet holds more Shiraz than Cabernet, and reversing the words on the label would mean reversing the blend."),
    Q("Geographical Indications and labelling",
      "Vintage, variety and origin claims on an Australian label are checked by auditing a winery's own paperwork rather than by judging the wine in the glass. What is that audit scheme called?",
      ["The Label Integrity Program", "The Geographical Indications Committee",
       "The Australian Wine Show Register", "The Winemakers Code of Practice"], 0,
      "The Label Integrity Program follows fruit from the weighbridge to the bottle, so a false claim is caught in the records rather than by a panel. The Geographical Indications Committee is a real body doing a different job: it determines boundaries, it does not police labels."),

    # ------------------------------------- Barossa and Eden Valley (7) -------
    Q("Barossa and Eden Valley",
      "Dense, dark and soft-edged at fifteen percent alcohol, chocolate and ripe plum with a warm sweet finish, grown on a warm valley floor an hour north-east of Adelaide. Which region and grape?",
      ["Barossa Valley Shiraz", "Eden Valley Riesling",
       "Coonawarra Cabernet Sauvignon", "Yarra Valley Pinot Noir"], 0,
      "The Barossa floor is warm, dry and low-lying, so sugar accumulates fast and acidity falls away, giving weight and sweetness of fruit rather than tension. It is the style that made Australian red wine famous abroad and it remains the country's benchmark for the grape."),
    Q("Barossa and Eden Valley",
      "Climb east out of the Barossa floor into hills a few hundred metres higher, and the calling card changes from a broad red to a dry white of lime and chalky grip. Which region have you reached?",
      ["Eden Valley", "Clare Valley", "Adelaide Hills", "McLaren Vale"], 0,
      "Eden Valley shares the Barossa zone with the valley floor but sits higher, cooler and on ancient weathered granite, and Riesling rather than Shiraz is what it is known for. Two neighbouring regions inside one zone produce wines with almost nothing in common."),
    Q("Barossa and Eden Valley",
      "Lutheran families from Silesia and Prussia settled one Australian valley from 1842, and their village names, bakeries and smokehouses are still in place. Which valley did they plant?",
      ["The Barossa Valley", "The Hunter Valley",
       "The Yarra Valley", "The Clare Valley"], 0,
      "German-speaking settlers gave the Barossa its Bethany, its Langmeil and its Krondorf, and they put vines in beside the wheat. Six generations of unbroken farming on the same blocks is why so much of that original planting material is still in the ground."),
    Q("Barossa and Eden Valley",
      "Old Shiraz in the Barossa often stands as a low free-standing shrub, with no wire, no post and no trellis anywhere near it. What is that training form called?",
      ["Bush vine, also known as head training", "Vertical shoot positioning",
       "Scott Henry", "Geneva Double Curtain"], 0,
      "A head-trained bush vine carries its own canopy without any support, and its own leaves shade the fruit from a fierce sun. It suits a dry-grown, low-yielding old block and is far too labour-intensive for anything planted with a machine harvester in mind."),
    Q("Barossa and Eden Valley",
      "Alongside Shiraz, two other heat-tolerant varieties came to the Barossa in the nineteenth century and are now blended with it under a three-letter shorthand. Which two?",
      ["Grenache and Mataro", "Nebbiolo and Barbera",
       "Tempranillo and Graciano", "Carignan and Cinsault"], 0,
      "GSM stands for Grenache, Shiraz and Mataro, the last being the Australian name for Mourvedre. All three tolerate heat and drought, which is why the same trio recurs across the southern Rhone and Spain's Mediterranean coast."),
    Q("Barossa and Eden Valley",
      "Vanilla, coconut and sweet baking spice sit over the fruit of a traditional Barossa Shiraz, and none of it comes from the grape. Where does it come from?",
      ["American oak, whose lactones give exactly those aromas",
       "French oak, which is the standard cooperage for the style",
       "An extended period on lees before bottling",
       "Grape concentrate added shortly before bottling"], 0,
      "American oak is far richer than French in the lactone that reads as coconut and vanilla, and it was cheap and available when the style was formed. French oak gives finer, more savoury spice instead, so the choice between them changes the wine as much as the vineyard does."),
    Q("Barossa and Eden Valley",
      "The Barossa keeps a register that ranks a vineyard purely by its age, with rungs at thirty-five, seventy, one hundred and one hundred and twenty-five years. What is the top rung called?",
      ["Ancestor Vine", "Centenarian Vine", "Survivor Vine", "Heritage Vine"], 0,
      "The Old Vine Charter runs Old Vine, Survivor Vine, Centenarian Vine and Ancestor Vine, the last requiring at least a hundred and twenty-five years of production. It exists because a vineyard that old has no legal protection of any kind and is worth more documented than pulled."),

    # -------------------- Clare, McLaren Vale and the Adelaide Hills (6) -----
    Q("Clare, McLaren Vale and the Adelaide Hills",
      "Bone dry, around twelve percent, lime juice and a hard chalky finish that turns to toast after a decade in bottle: this white is the making of a set of narrow north-south valleys well north of Adelaide. Name the region and the grape.",
      ["Clare Valley Riesling", "Hunter Valley Semillon",
       "Margaret River Chardonnay", "Yarra Valley Chardonnay"], 0,
      "Clare Riesling is fermented dry and bottled without any oak, so nothing stands between the fruit and the acid. With age it turns toasty and takes on a lime-marmalade depth, and the screwcap it has worn since 2000 is largely why that ageing is now dependable."),
    Q("Clare, McLaren Vale and the Adelaide Hills",
      "Clare's summers are hot and it lies well inland, away from any moderating sea, yet its Riesling keeps a ferocious acidity. What preserves it?",
      ["Height, and the cold nights that come with it, which slow the loss of acid after dark",
       "Afternoon sea breezes arriving off the Southern Ocean",
       "Constant cloud cover through the summer months",
       "A limestone subsoil that adds acidity to the juice"], 0,
      "The Clare valleys sit several hundred metres up, and on a clear night at that height the temperature falls sharply. Respiration burns acid through a warm night and stalls through a cold one, so the wide daily swing is what leaves the wine its bite."),
    Q("Clare, McLaren Vale and the Adelaide Hills",
      "Thirty-five kilometres south of Adelaide the vineyards run down toward a gulf, and a sea breeze arrives most summer afternoons to take the heat out of ripening. Which region?",
      ["McLaren Vale", "Barossa Valley", "Coonawarra", "Clare Valley"], 0,
      "McLaren Vale lies between the Mount Lofty Ranges and Gulf St Vincent, and the water is close enough to change the afternoon. The climate reads as Mediterranean, which is why Shiraz, Grenache and a lengthening list of Italian and Spanish varieties all succeed there."),
    Q("Clare, McLaren Vale and the Adelaide Hills",
      "Deep sand at Blewitt Springs, old unirrigated bush vines and a retreat from heavy extraction have made one southern Rhone variety a McLaren Vale speciality, pale and perfumed rather than dense. Which?",
      ["Grenache", "Mourvedre", "Cinsault", "Counoise"], 0,
      "Grenache ripens late and to high sugar, so for decades it was picked overripe and either buried in oak or fortified. Picked earlier off old sandy blocks it gives a translucent, red-fruited wine with fine tannin, and that reversal is among the clearest style changes in modern Australian wine."),
    Q("Clare, McLaren Vale and the Adelaide Hills",
      "Immediately east of Adelaide the land climbs into ranges where Sauvignon Blanc and Chardonnay hold a nervy acidity the plains below cannot manage. Which region?",
      ["Adelaide Hills", "Barossa Valley", "Langhorne Creek", "Riverland"], 0,
      "The Adelaide Hills run along the Mount Lofty Ranges and much of the vineyard sits above four hundred metres. It is one of South Australia's coolest regions and supplies both crisp still whites and base wine for sparkling."),
    Q("Clare, McLaren Vale and the Adelaide Hills",
      "Two named subregions inside the Adelaide Hills appear on labels for cool-climate Chardonnay and Pinot Noir. Which pair?",
      ["Lenswood and Piccadilly Valley", "Watervale and Polish Hill River",
       "High Eden and Moppa", "Blewitt Springs and Seaview"], 0,
      "Lenswood and Piccadilly Valley are the only two subregions the Adelaide Hills has registered, and both sit high and cold enough for a long slow ripening. Watervale and Polish Hill River belong to Clare, and Blewitt Springs and Seaview to McLaren Vale."),

    # ------------------------- Coonawarra and the Limestone Coast (5) --------
    Q("Coonawarra and the Limestone Coast",
      "A narrow cigar-shaped strip of red-brown topsoil lies over soft white limestone with the water table close beneath, and it grows Australia's most celebrated Cabernet. What is that topsoil called?",
      ["Terra rossa", "Kimmeridgian marl", "Galestro", "Crasse de fer"], 0,
      "Terra rossa is a thin iron-rich clay left behind as the limestone below it weathered, and the strip carrying it is only a couple of kilometres wide. Roots pass through it into the limestone, which drains freely yet keeps water within reach, so the vine is neither drowned nor starved."),
    Q("Coonawarra and the Limestone Coast",
      "Cassis, mint and a firm dry structure, from a flat cool strip in the far south-east of South Australia close to the Victorian border. Which variety carries that reputation?",
      ["Cabernet Sauvignon", "Shiraz", "Merlot", "Pinot Noir"], 0,
      "Coonawarra ripens Cabernet slowly enough to shed the green pyrazine edge without surrendering acid or structure, which very few warm countries manage. The eucalypt or mint note is a regional signature rather than a fault."),
    Q("Coonawarra and the Limestone Coast",
      "Coonawarra lies some eighty kilometres from the Southern Ocean and among the more southerly of mainland Australia's vineyard regions, so the season is long and the picking late. What does that slowness give the fruit?",
      ["Time for tannin and flavour to ripen while the acidity is still intact",
       "A higher sugar level than any warmer region can reach",
       "Reliable botrytis in the majority of vintages",
       "Skins thin enough to remove any need for maceration"], 0,
      "Sugar and flavour ripen at different rates, and a long cool season lets the second catch up with the first. Fast-ripened fruit in a hot region gives alcohol before the tannin has softened, and escaping that trade is the whole point of a cool Cabernet site."),
    Q("Coonawarra and the Limestone Coast",
      "Coonawarra, Padthaway and Wrattonbully all sit inside one South Australian zone, named for the rock they have in common. Which zone?",
      ["Limestone Coast", "Fleurieu", "Mount Lofty Ranges", "Lower Murray"], 0,
      "The Limestone Coast also takes in Mount Benson, Robe and Mount Gambier, all standing on the same ancient seabed. Fleurieu covers McLaren Vale and Langhorne Creek, and Mount Lofty Ranges covers the Adelaide Hills and Clare."),
    Q("Coonawarra and the Limestone Coast",
      "Some seventy kilometres north of Coonawarra, on the same limestone, a flatter region was opened up by large companies in the 1960s and became a major source of Chardonnay for national brands. Which region?",
      ["Padthaway", "Wrattonbully", "Mount Benson", "Robe"], 0,
      "Padthaway was developed as a fruit source rather than as a cellar-door destination, and much of its crop has always left the region in a tanker. Wrattonbully, lying between it and Coonawarra, came later and leans red."),

    # ------------------------------------------------------- Victoria (7) ----
    Q("Victoria",
      "An hour's drive east of Melbourne, on hillsides first planted in 1838, growers make Pinot Noir, Chardonnay and traditional-method sparkling. Which region?",
      ["Yarra Valley", "Mornington Peninsula", "Heathcote", "Rutherglen"], 0,
      "The Yarra Valley is Victoria's oldest region and among its coolest, and it spreads across enough altitude and aspect to give quite different wines within one name. Cool-climate Shiraz and Cabernet are made there too, but the Burgundian pair define it."),
    Q("Victoria",
      "A strip of land jutting south from Melbourne has water on three sides, so no vineyard on it stands far from the sea. Which region?",
      ["Mornington Peninsula", "Yarra Valley", "Grampians", "Heathcote"], 0,
      "Port Phillip Bay, Western Port and Bass Strait surround the Mornington Peninsula and hold its temperature inside a narrow band. Pinot Noir, Chardonnay and Pinot Gris account for most of what is planted, in small holdings farmed intensively."),
    Q("Victoria",
      "Central Victorian vineyards sit on a narrow ridge of deep red soil weathered from Cambrian greenstone half a billion years old, and the ridge has become a byword for powerful dark Shiraz. Which region?",
      ["Heathcote", "Grampians", "Rutherglen", "Nagambie Lakes"], 0,
      "The Cambrian ridge runs north to south for some fifty kilometres and its soil holds water well, so the vines ripen steadily rather than under stress. Heathcote Shiraz is dense and dark but keeps a cooler, bluer-fruited edge than a Barossa version."),
    Q("Victoria",
      "A tiny glass arrives at the end of dinner almost black and syrupy, smelling of raisins, rose and orange marmalade, fortified and matured for decades in old wood in hot north-east Victoria. What is it?",
      ["Rutherglen Muscat", "Rutherglen Topaque",
       "Australian Apera", "Sparkling Shiraz"], 0,
      "Rutherglen Muscat comes from Muscat a Petits Grains Rouges left on the vine until it raisins, then fortified and aged through fierce inland summers. Heat and slow evaporation concentrate it further, and the oldest material is blended back into younger wine in a solera-like fashion."),
    Q("Victoria",
      "Rutherglen grades its fortified Muscat on a four-step ladder of rising age and concentration. Which step sits at the top?",
      ["Rare", "Grand", "Classic", "Reserve"], 0,
      "The ladder runs Rutherglen, Classic, Grand and Rare, each demanding a greater average age and a higher concentration than the rung below. It is a scheme run by the producers themselves rather than a legal category, and it is one of the very few age classifications in Australian wine."),
    Q("Victoria",
      "A district in western Victoria built its name on peppery Shiraz and on a sparkling red made from the same grape, and its cellars were tunnelled out of the rock by out-of-work gold miners in the 1860s. Which region?",
      ["Grampians", "Heathcote", "Yarra Valley", "King Valley"], 0,
      "The Grampians, long known as Great Western, sits high enough for a genuinely cool season, so its Shiraz is medium-bodied and spicy rather than broad and sweet. The drives cut into the rock still hold bottles for the region's sparkling reds."),
    Q("Victoria",
      "One white Rhone variety found an unlikely stronghold in central Victoria, where some of the oldest surviving plantings anywhere are still worked. Which variety?",
      ["Marsanne", "Roussanne", "Viognier", "Grenache Blanc"], 0,
      "Marsanne reached the Goulburn Valley in the nineteenth century and stayed, and vines put in during the 1920s are still cropping at Nagambie Lakes. Young it is quiet and lemony; after a decade in bottle it turns to honeysuckle and toast, which is why the good examples repay cellaring."),

    # ------------------------------------------------ New South Wales (5) ----
    Q("New South Wales",
      "A ten-year-old white shows toast, honey and lanolin, has never been near oak, and left the winery at barely eleven percent alcohol. Which region and grape produced it?",
      ["Hunter Valley Semillon", "Clare Valley Riesling",
       "Margaret River Chardonnay", "Adelaide Hills Sauvignon Blanc"], 0,
      "Hunter Semillon is picked early at low sugar and high acid, fermented cool in tank and bottled young, when it tastes of very little. The toast develops entirely in bottle with no oak involved at any stage, and no other region makes anything closely comparable."),
    Q("New South Wales",
      "Rain at harvest, high humidity and cloud through the ripening season would be a catastrophe across most of Australia, and are simply normal in one of its oldest fine wine regions. Which?",
      ["Hunter Valley", "Coonawarra", "Clare Valley", "Great Southern"], 0,
      "The Hunter lies at a subtropical latitude with summer-dominant rainfall arriving off the Pacific, and picking often begins in January. The cloud that comes with the humidity is also a mercy, since it moderates a sun that would otherwise scorch the fruit."),
    Q("New South Wales",
      "Medium-bodied, earthy and leathery rather than dense and sweet, the classic red of the Hunter is made from the same variety as the Barossa's blockbusters. Which variety?",
      ["Shiraz", "Cabernet Sauvignon", "Grenache", "Pinot Noir"], 0,
      "Cloud, humidity and an early harvest leave the Hunter with lower sugar and softer extract than the Barossa draws from the same grape. It was sold through most of the twentieth century as Hunter River Burgundy, which says a good deal about how differently it drinks."),
    Q("New South Wales",
      "One New South Wales region writes a minimum height above sea level into its Geographical Indication, so land below that line may not use the name. Which region?",
      ["Orange", "Mudgee", "Hunter Valley", "Riverina"], 0,
      "Only vineyards at or above six hundred metres may be labelled Orange, and the highest sit well beyond nine hundred on the slopes of an extinct volcano. It is an unusual clause in a system that normally draws a boundary on a map and says nothing about the land inside it."),
    Q("New South Wales",
      "A hot, flat, irrigated district in inland New South Wales is famous for one wine that has nothing to do with volume: a sweet golden botrytis-affected Semillon. Which district?",
      ["Riverina", "Mudgee", "Hilltops", "Cowra"], 0,
      "Fog rising off the irrigation channels around Griffith brings botrytis to fruit that would stay clean in so dry a climate, and the sweet wines that result are among Australia's finest. The same district supplies vast quantities of everyday wine, which is why its reputation lags its best bottles."),

    # --------------------------------------------- Western Australia (5) -----
    Q("Western Australia",
      "A promontory at the far south-western corner of the continent has ocean on three sides and built its reputation on Cabernet Sauvignon grown in gravelly soil. Which region?",
      ["Margaret River", "Great Southern", "Swan District", "Geographe"], 0,
      "Margaret River runs between Cape Naturaliste and Cape Leeuwin, with the Indian Ocean to the west and the Southern Ocean to the south. Its Cabernet is structured and cassis-scented, and it is the wine by which the region is measured."),
    Q("Western Australia",
      "Margaret River's signature white blends two Bordeaux grapes, often with a little oak, and appears on so many lists that it is written as three letters. Which two grapes?",
      ["Sauvignon Blanc and Semillon", "Chardonnay and Viognier",
       "Riesling and Semillon", "Sauvignon Blanc and Chenin Blanc"], 0,
      "The blend pairs Sauvignon Blanc's aromatic lift with Semillon's weight and its willingness to take oak, and neither grape gives the same wine alone. It is a direct import from white Bordeaux, adapted to a far sunnier place."),
    Q("Western Australia",
      "Vintages in Margaret River vary far less than in Bordeaux, and a poor year there is rarely a washout. What makes the season so even?",
      ["Ocean on three sides holds the temperature inside a narrow band from flowering to harvest",
       "Elevation above six hundred metres keeps every night uniformly cold",
       "A rain shadow removes almost all of the winter rainfall",
       "Persistent summer cloud screens the vineyards from the sun"], 0,
      "A large body of water changes temperature slowly, so a maritime climate has small daily and seasonal swings. The rain also falls mainly in winter, well clear of flowering and harvest, which removes the two moments at which a European vintage is usually lost."),
    Q("Western Australia",
      "Western Australia's biggest region by area spreads inland and along the south coast, and divides into five named subregions including Frankland River and Porongurup. Which region?",
      ["Great Southern", "Margaret River", "Peel", "Blackwood Valley"], 0,
      "Great Southern also contains Mount Barker, Albany and Denmark, and the five differ enough that many labels name the subregion rather than the region. Riesling, Shiraz, Cabernet, Pinot Noir and Chardonnay are all made well there, which is unusual inside one name."),
    Q("Western Australia",
      "Of the five Great Southern subregions, one lies furthest inland along a river, runs warmest and driest, and is planted heavily to Shiraz and Cabernet. Which?",
      ["Frankland River", "Albany", "Denmark", "Porongurup"], 0,
      "Distance from the coast makes Frankland River the most continental of the five, with warmer days, colder nights and less rain. Albany and Denmark sit on the water, and their cooler, wetter conditions push them toward Pinot Noir and Chardonnay."),

    # ------------------------------------------------------ Tasmania (4) ----
    Q("Tasmania",
      "An island lying between forty-one and forty-three degrees south grows much of the fruit behind Australia's finest traditional-method sparkling wine. Which state?",
      ["Tasmania", "South Australia", "Victoria", "Western Australia"], 0,
      "Tasmania is cold enough that Chardonnay and Pinot Noir reach flavour ripeness at low sugar and very high acidity, which is precisely what a sparkling base needs. The conditions that make still wine a gamble there make the bubbles dependable."),
    Q("Tasmania",
      "Tamar Valley, Pipers River and Coal River Valley all appear on Tasmanian labels, yet not one of them is a Geographical Indication. What is registered instead?",
      ["The whole island, as a single Geographical Indication",
       "Each of the three, but as zones rather than as regions",
       "Only the northern half of the island",
       "Nothing at all: Tasmania has no Geographical Indication"], 0,
      "Tasmania is one GI covering the entire state, with no official regions or subregions inside it, so those area names are informal usage. Given how differently the north coast and the drier south-east ripen, a single name conceals a great deal of variation."),
    Q("Tasmania",
      "Tasmania's most planted variety gives a still red that is pale to medium in colour, red-fruited and high in acid. Which variety?",
      ["Pinot Noir", "Shiraz", "Cabernet Sauvignon", "Merlot"], 0,
      "Pinot Noir serves two purposes on the island: it is the backbone of the sparkling wine and it makes the most convincing still red. Cabernet is planted only in the warmest pockets and fails to ripen in most years."),
    Q("Tasmania",
      "Almost all Tasmanian vineyards sit along the north coast or down the eastern side, and the west carries none. What rules the west out?",
      ["It takes the full force of the westerlies, and the rainfall that comes with them",
       "It is far too warm and dry for anything but table grapes",
       "It has no soil anywhere deep enough to plant",
       "State law prohibits vineyards there"], 0,
      "The Roaring Forties cross thousands of kilometres of open ocean and strike the west coast first, dumping several times the rain that falls on Hobart. The eastern side lies in the rain shadow of the central highlands, and that is where the vines are."),

    # ------------------------------------- grapes, styles and closures (6) ---
    Q("Grapes, styles and closures",
      "Australia's most widely planted variety carries one name here and a different one in the Rhone valley it came from. What is the Rhone name?",
      ["Syrah", "Mourvedre", "Grenache", "Carignan"], 0,
      "Shiraz and Syrah are one grape, and the two words now signal a difference in expectation rather than in genetics: Shiraz suggests ripeness and sweetness of fruit, Syrah restraint and pepper. Many Australian producers choose between them deliberately to flag which style is in the bottle."),
    Q("Grapes, styles and closures",
      "Mataro appears on Australian labels for a black grape the rest of the world knows by two other names. Which two?",
      ["Mourvedre and Monastrell", "Carignan and Carinena",
       "Cinsault and Hermitage", "Durif and Petite Sirah"], 0,
      "Mourvedre is the French name and Monastrell the Spanish, while Mataro travelled to Australia with early cuttings and stuck. It ripens very late and gives dark, meaty, firmly tannic wine, which is why it usually turns up as the M in a blend rather than on its own."),
    Q("Grapes, styles and closures",
      "A group of Clare Valley producers agreed in 2000 to bottle their Riesling under a closure Australian wineries had tried in the 1970s and abandoned. What were they trying to stop?",
      ["Cork taint, and the random bottle-to-bottle variation that came with it",
       "Sediment forming in the bottle during long ageing",
       "The wine losing colour under shop lighting",
       "Sulphur dioxide escaping through the closure"], 0,
      "A taut dry Riesling exposes a tainted or prematurely oxidised bottle more brutally than almost any other wine, and the Clare growers were losing bottles at random. Australian trials in the 1970s had already put premium Riesling under screwcap and been dropped when buyers balked, so this was a revival rather than a first. It stuck: the screwcap now seals most Australian wine at every price, and the argument has moved on to how much oxygen a liner should admit."),
    Q("Grapes, styles and closures",
      "Blending Shiraz from three separate regions before bottling is treated in Australia as a craft rather than as a compromise. What does the practice buy the winemaker?",
      ["Components with different strengths, which together hold a house style steady from year to year",
       "Exemption from auditing of the label's claims",
       "The right to print any regional name on the label",
       "A legal requirement that applies above a certain alcohol level"], 0,
      "One region brings colour and tannin, another perfume, another acidity, and no single site delivers all of them every season. The trade is that the wine can no longer claim one region and must fall back on a broad Geographical Indication such as South Eastern Australia."),
    Q("Grapes, styles and closures",
      "A fortified wine from north-east Victoria was called Tokay until an agreement with the European Union obliged Australia to surrender the name. What is it called now, and what is it made from?",
      ["Topaque, from Muscadelle", "Apera, from Palomino",
       "Tawny, from Grenache", "Muscat, from Muscat a Petits Grains"], 0,
      "Muscadelle is a Bordeaux grape with no fortified tradition at home, and in Rutherglen it gives cold tea, malt and butterscotch, quite distinct from the raisiny Muscat made alongside it. Apera and Tawny are the replacement names Australia adopted for its sherry and port styles under the same agreement."),
    Q("Grapes, styles and closures",
      "Poured cool with turkey at a midsummer Christmas, a dark foaming full-bodied red just off dry has been an Australian fixture since the nineteenth century. What is it?",
      ["Sparkling Shiraz", "Sparkling Grenache",
       "Sparkling Cabernet Sauvignon", "A sweet red made in the Lambrusco manner"], 0,
      "The style began in Victoria's Great Western and survives almost nowhere else on earth. A full red base takes a second fermentation for pressure, and the dosage leaves just enough sugar to carry the tannin, which is why it is served cool rather than cellar-warm."),
]
