"""Rank I rewrite — Burgundy (63 questions).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

Stem openers are varied deliberately from the start, and narrow factual
questions are approached from an angle chosen at writing time rather than
reframed after a collision — the two rules Bordeaux produced.
"""

from lib import Q

CAT = "Burgundy"
SLUG = "r1-burgundy"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Geography and the Cote", 7),
    ("Grape varieties", 5),
    ("The appellation hierarchy", 8),
    ("Cote de Nuits villages", 8),
    ("Cote de Beaune villages", 8),
    ("Grands Crus", 7),
    ("Chablis", 6),
    ("Cote Chalonnaise and Maconnais", 5),
    ("Beaujolais", 5),
    ("Climate, soil and vineyard", 4),
]

BANK = [
    # ------------------------------------------ geography and the Cote (7) --
    Q("Geography and the Cote",
      "The Cote d'Or divides into which two halves?",
      ["The Cote de Nuits and the Cote de Beaune", "The Cote Chalonnaise and the Maconnais",
       "Chablis and the Cote de Nuits", "The Cote de Beaune and Beaujolais"], 0,
      "Nuits to the north, Beaune to the south. The Cote d'Or is a narrow escarpment barely a few hundred metres wide in places, and it carries almost every famous name."),
    Q("Geography and the Cote",
      "Which half of the Cote d'Or is overwhelmingly planted to red wine?",
      ["The Cote de Nuits", "The Cote de Beaune", "Neither, both are equally split",
       "The Maconnais"], 0,
      "The Cote de Nuits is Pinot Noir country and holds most of the red Grands Crus. The Cote de Beaune makes both, and holds the great whites."),
    Q("Geography and the Cote",
      "Chablis sits well to the north of the Cote d'Or, closer to which other region?",
      ["Champagne", "Beaujolais", "The Rhone", "Alsace"], 0,
      "The isolation is the point: Chablis is nearer Champagne than Beaune, and the cool northerly site is why the wines are as taut as they are."),
    Q("Geography and the Cote",
      "Running south from the Cote d'Or, which region comes next?",
      ["The Cote Chalonnaise", "The Maconnais", "Beaujolais", "Chablis"], 0,
      "The order running south is Cote d'Or, Cote Chalonnaise, Maconnais, then Beaujolais. Prices tend to fall in the same direction."),
    Q("Geography and the Cote",
      "Beaujolais lies at the southern end of Burgundy. Which grape dominates it?",
      ["Gamay", "Pinot Noir", "Chardonnay", "Aligote"], 0,
      "Gamay was expelled from the Cote d'Or in the fourteenth century and found its home on Beaujolais granite, where it makes something entirely its own."),
    Q("Geography and the Cote",
      "Which Burgundian sub-region is the largest source of the region's Chardonnay by volume?",
      ["The Maconnais", "The Cote de Nuits", "Chablis", "The Cote Chalonnaise"], 0,
      "The Maconnais produces far more white than the Cote d'Or, at prices that make Burgundian Chardonnay approachable at all."),
    Q("Geography and the Cote",
      "Burgundy's vineyards run predominantly along which orientation?",
      ["A narrow escarpment facing broadly east", "A wide plateau of even aspect facing west",
       "A chain of north-facing river valleys", "South-facing slopes above a coastal plain"], 0,
      "East-facing mid-slope catches the morning sun and drains well. In a marginal climate that aspect is the difference between ripe and not."),

    # -------------------------------------------------- grape varieties (5) -
    Q("Grape varieties",
      "Red Burgundy from the Cote d'Or is made from which single variety?",
      ["Pinot Noir", "Gamay", "Cabernet Franc", "Cabernet Sauvignon"], 0,
      "Burgundy is a region of monovarietal wines, which is what makes it the reference for expressing site: the grape is held constant and the vineyard varies."),
    Q("Grape varieties",
      "White Burgundy, with rare exceptions, is made from which variety?",
      ["Chardonnay", "Sauvignon Blanc", "Chenin Blanc", "Viognier"], 0,
      "Chardonnay is thought to have originated here, from a crossing of Pinot and Gouais Blanc, and Burgundy remains its benchmark."),
    Q("Grape varieties",
      "Which secondary white grape has its own regional appellation in Burgundy?",
      ["Aligote", "Melon de Bourgogne", "Pinot Blanc", "Sacy"], 0,
      "Bourgogne Aligote is a separate appellation. The grape is sharper and leaner than Chardonnay, and is the traditional base of a kir."),
    Q("Grape varieties",
      "Gamay's expulsion from the Cote d'Or was ordered in the fourteenth century by whom?",
      ["Duke Philip the Bold", "The parliament of Dijon",
       "Napoleon Bonaparte", "The Hospices de Beaune"], 0,
      "The 1395 edict of the Duke of Burgundy called it disloyal and drove it south. Whatever the politics, the result was to reserve the Cote d'Or for Pinot Noir."),
    Q("Grape varieties",
      "Pinot Noir is notoriously difficult to grow. Which characteristic is most responsible?",
      ["Thin skins and tight bunches", "Extremely late ripening",
       "Very high tannin needing years to soften", "Resistance to all rootstock"], 0,
      "Thin skins give the pale colour and fine texture, and also the vulnerability. Tight clusters trap moisture and invite rot in a damp autumn."),

    # ------------------------------------------ the appellation hierarchy (8)
    Q("The appellation hierarchy",
      "Burgundy's appellation pyramid has how many broad tiers?",
      ["Four", "Three", "Five", "Two"], 0,
      "Regional, Village, Premier Cru and Grand Cru. The tiers describe delimited land rather than the producer, which is the opposite of the Bordeaux chateau model."),
    Q("The appellation hierarchy",
      "Of every hundred bottles of Burgundy, roughly how many are Grand Cru?",
      ["About one", "About ten", "About twenty-five", "About fifty"], 0,
      "It is a tiny fraction of a small region, which is much of why the wines cost what they do. Regional appellations account for over half."),
    Q("The appellation hierarchy",
      "On a Grand Cru label from the Cote d'Or, what typically appears as the appellation?",
      ["The vineyard name alone", "The village name alone",
       "The village and vineyard together", "Simply Bourgogne"], 0,
      "Chambertin and Montrachet stand on their own, without a village name. It is the clearest signal of the top tier on the label."),
    Q("The appellation hierarchy",
      "A Premier Cru wine is labelled how?",
      ["Village name, then the vineyard", "Vineyard name alone",
       "Simply Bourgogne Premier Cru", "The producer's name alone"], 0,
      "Gevrey-Chambertin Clos Saint-Jacques, for example. The village comes first, which distinguishes it from a Grand Cru at a glance."),
    Q("The appellation hierarchy",
      "Many Cote d'Or villages appended the name of their finest vineyard in the nineteenth century. Which is an example?",
      ["Gevrey-Chambertin", "Pommard", "Savigny-les-Beaune", "Saint-Aubin"], 0,
      "Gevrey took Chambertin, Chambolle took Musigny, Vosne took Romanee. Savigny's suffix points at the town of Beaune, not at a vineyard, and Pommard and Saint-Aubin appended nothing at all. It flatters the village and confuses the newcomer, permanently."),
    Q("The appellation hierarchy",
      "What does the Burgundian term climat denote?",
      ["A named vineyard parcel", "The weather of a given vintage",
       "A cuvee blended from several parcels", "A cellar shared by the growers of one village"], 0,
      "A named parcel whose boundaries and reputation are centuries old, not merely a plot of land. The climats were recognised by UNESCO in 2015."),
    Q("The appellation hierarchy",
      "Fragmentation of Burgundian vineyard ownership is largely attributable to what?",
      ["The Napoleonic inheritance code", "Phylloxera",
       "The 1855 classification", "Rules obliging growers to sell through a cooperative"], 0,
      "Equal division across generations split parcels into slivers, which is why one Grand Cru can have dozens of owners each making a different wine."),
    Q("The appellation hierarchy",
      "A negociant in Burgundy does what?",
      ["Buys grapes or wine and bottles it under its own name",
       "Owns outright every vineyard whose wine it bottles",
       "Exports finished wine but never bottles any itself",
       "Sets the appellation boundaries for each village"], 0,
      "A negociant may buy grapes, must or finished wine, and bottle it under its own name. Buying fruit lets a house work across many appellations. The distinction from a domaine, which bottles only its own fruit, is worth reading on the label."),

    # ------------------------------------------- Cote de Nuits villages (8) -
    Q("Cote de Nuits villages",
      "Which Cote de Nuits village holds the greatest number of Grands Crus?",
      ["Gevrey-Chambertin", "Chambolle-Musigny", "Vougeot", "Nuits-Saint-Georges"], 0,
      "Nine, headed by Chambertin and Chambertin-Clos de Beze. It is the largest of the Cote de Nuits communes as well."),
    Q("Cote de Nuits villages",
      "Vosne-Romanee is celebrated above all for what?",
      ["A concentration of the most prized Grands Crus", "Its white wines",
       "Producing the largest volume in Burgundy", "Its Gamay"], 0,
      "Romanee-Conti, La Tache, Richebourg and their neighbours sit within a few hundred metres of one another. It is the most expensive ground in wine."),
    Q("Cote de Nuits villages",
      "Despite its reputation, which major Cote de Nuits village has no Grand Cru at all?",
      ["Nuits-Saint-Georges", "Gevrey-Chambertin", "Vosne-Romanee", "Morey-Saint-Denis"], 0,
      "It gave the Cote its name and has a string of fine Premiers Crus, but no Grand Cru was granted."),
    Q("Cote de Nuits villages",
      "Chambolle-Musigny's wines are usually described in which terms?",
      ["Perfumed and delicate", "Massive, tannic and slow to open",
       "Deeply oaked and sweet", "Light and simple"], 0,
      "Thinner, more limestone-rich soils give a lacier texture, and Chambolle is often called the most ethereal of the Cote de Nuits. Its Grands Crus are Musigny and Bonnes-Mares, the latter shared with Morey-Saint-Denis."),
    Q("Cote de Nuits villages",
      "Morey-Saint-Denis sits between which two villages?",
      ["Gevrey-Chambertin and Chambolle-Musigny", "Vosne-Romanee and Nuits-Saint-Georges",
       "Fixin and Marsannay", "Vougeot and Flagey-Echezeaux"], 0,
      "Squeezed between two famous neighbours, and long overlooked for that reason. It holds four Grands Crus wholly its own, plus the Morey slice of Bonnes-Mares."),
    Q("Cote de Nuits villages",
      "Which village is dominated by a single walled Grand Cru of about fifty hectares?",
      ["Vougeot", "Volnay", "Santenay", "Fixin"], 0,
      "Clos de Vougeot is the largest Grand Cru of the Cote de Nuits, walled by the Cistercians, and now divided among some eighty owners."),
    Q("Cote de Nuits villages",
      "Which appellation is unusual in Burgundy for permitting red, white and rose?",
      ["Marsannay", "Pommard", "Meursault", "Chambolle-Musigny"], 0,
      "Marsannay at the northern end of the Cote de Nuits is the only one of the Cote d'Or village appellations covering all three colours."),
    Q("Cote de Nuits villages",
      "Chambertin lies within which village?",
      ["Gevrey-Chambertin", "Chambolle-Musigny", "Morey-Saint-Denis", "Vosne-Romanee"], 0,
      "Chambertin and Chambertin-Clos de Beze are the two senior Grands Crus, with seven others permitted to append the Chambertin name."),

    # ------------------------------------------ Cote de Beaune villages (8) -
    Q("Cote de Beaune villages",
      "Which three neighbouring villages are the heartland of great white Burgundy?",
      ["Meursault, Puligny and Chassagne",
       "Pommard, Volnay and Savigny-les-Beaune", "Fixin, Marsannay and Vougeot",
       "Rully, Givry and Mercurey"], 0,
      "The finest Chardonnay in the world is made along a stretch of a few kilometres. Puligny-Montrachet and Chassagne-Montrachet take their names from the hill they share. Meursault is the broadest in style, Puligny the most precise."),
    Q("Cote de Beaune villages",
      "Meursault differs from its two white neighbours in which respect?",
      ["It has no Grand Cru", "It makes only red wine", "It is not in the Cote de Beaune",
       "It forbids oak"], 0,
      "Its best sites, Perrieres, Genevrieres and Charmes, are Premiers Crus. Many consider Perrieres to merit promotion."),
    Q("Cote de Beaune villages",
      "Volnay is best known for wines of what character?",
      ["Fragrant, silken reds", "Powerful tannic reds", "Rich oaky whites", "Sweet whites"], 0,
      "Volnay is the Chambolle of the Cote de Beaune. Its neighbour Pommard is the sturdier, firmer counterweight."),
    Q("Cote de Beaune villages",
      "Pommard's reds are typically described how, relative to Volnay?",
      ["Firmer and more robust", "Lighter and more perfumed", "Sweeter", "Higher in acidity"], 0,
      "More clay in the soil gives a broader, more tannic wine. The pair are the standard illustration of how quickly Burgundy changes across a boundary."),
    Q("Cote de Beaune villages",
      "Corton is notable as which sort of Grand Cru?",
      ["The Cote de Beaune's only red Grand Cru", "The smallest Grand Cru in Burgundy by area",
       "A white-only Grand Cru", "A Beaujolais cru"], 0,
      "The hill of Corton carries the red Corton and the white Corton-Charlemagne, and it is by far the largest Grand Cru area in Burgundy."),
    Q("Cote de Beaune villages",
      "Which charitable institution holds a famous annual wine auction in Beaune?",
      ["The Hospices de Beaune", "The Confrerie des Chevaliers du Tastevin",
       "The Cistercian abbey of Citeaux", "The Bureau Interprofessionnel"], 0,
      "Founded in 1443 as a hospital for the poor, endowed with vineyards over the centuries. The November auction sets a mood for the vintage."),
    Q("Cote de Beaune villages",
      "Santenay lies at which end of the Cote de Beaune?",
      ["The southern end", "The northern end", "The centre", "It is not in the Cote de Beaune"], 0,
      "The southern extremity, where the Cote d'Or gives way to the Cote Chalonnaise, and traditionally a source of value."),
    Q("Cote de Beaune villages",
      "Which village name appears attached to both a red-producing and a white-producing reputation, split across the Montrachet hill?",
      ["Chassagne-Montrachet", "Meursault", "Volnay", "Aloxe-Corton"], 0,
      "Chassagne was historically a red-wine village and is now better known for white, while retaining a substantial red production."),

    # ---------------------------------------------------- Grands Crus (7) ---
    Q("Grands Crus",
      "Romanee-Conti and La Tache are the monopoles of which domaine?",
      ["Domaine de la Romanee-Conti", "Domaine Leroy", "Domaine Leflaive", "Maison Louis Jadot"], 0,
      "A monopole is a vineyard in a single owner's hands, which is rare in fragmented Burgundy and part of what these two names trade on."),
    Q("Grands Crus",
      "Montrachet is unusual among Grands Crus in that it does what?",
      ["Straddles two communes", "Produces only red wine", "Lies in Chablis",
       "Is owned by one domaine"], 0,
      "It sits across the boundary of Puligny and Chassagne, which is why both villages appended the name."),
    Q("Grands Crus",
      "Corton-Charlemagne produces wine of which colour?",
      ["White", "Red", "Rose", "Both red and white equally"], 0,
      "The white Grand Cru of the Corton hill, traditionally said to have been planted at the emperor's wish so his beard would not be stained."),
    Q("Grands Crus",
      "Which Grand Cru of Chambolle-Musigny produces a small quantity of white wine?",
      ["Musigny", "Bonnes-Mares", "Clos de Vougeot", "Echezeaux"], 0,
      "Musigny Blanc is made in tiny volumes and is the only white permitted from a Cote de Nuits Grand Cru."),
    Q("Grands Crus",
      "Clos de Vougeot's reputation for variable quality is usually attributed to what?",
      ["Its many owners", "Its planting of Gamay alongside Pinot Noir",
       "Its northerly exposure", "A rule against new oak barrels"], 0,
      "Fifty hectares walled as one by monks who blended it all. Divided now among dozens of owners, across ground that slopes unevenly, it can no longer be one wine."),
    Q("Grands Crus",
      "Which order of monks did most to map and wall Burgundy's vineyards in the Middle Ages?",
      ["The Cistercians", "The Benedictines alone", "The Jesuits", "The Franciscans"], 0,
      "Cistercian and Benedictine houses worked the land for centuries and recorded which parcels ripened differently. The climat map is largely their survey."),
    Q("Grands Crus",
      "Echezeaux and Grands-Echezeaux lie within which commune?",
      ["Flagey-Echezeaux", "Gevrey-Chambertin",
       "Chambolle-Musigny", "Nuits-Saint-Georges"], 0,
      "Flagey-Echezeaux's village wine is sold as Vosne-Romanee, which is one of Burgundy's more confusing administrative arrangements."),

    # -------------------------------------------------------- Chablis (6) ---
    Q("Chablis",
      "Which soil type underlies the finest Chablis vineyards?",
      ["Kimmeridgian limestone", "Granite with a thin sandy topsoil",
       "Volcanic basalt", "Deep gravel"], 0,
      "A Jurassic seabed of limestone and marl, full of fossilised oyster shells. The Grands Crus and best Premiers Crus sit on it, and Petit Chablis largely does not."),
    Q("Chablis",
      "How many Grand Cru climats does Chablis have?",
      ["Seven", "One", "Four", "Twelve"], 0,
      "Blanchot, Bougros, Les Clos, Grenouilles, Les Preuses, Valmur and Vaudesir, all on one south-west facing slope above the town."),
    Q("Chablis",
      "Chablis is defined stylistically by which pair of qualities?",
      ["High acidity and little or no new oak", "Heavy oak and low acid",
       "Residual sugar and low alcohol", "High tannin and long maceration"], 0,
      "The cool site gives the acidity; the house style debate is over how much oak, with many producers using none at all."),
    Q("Chablis",
      "Spring frost is a defining hazard in Chablis. Which protection is characteristic there?",
      ["Sprinklers icing the buds", "Overhead netting",
       "Plastic tunnels closed over the rows at night", "Deliberate late pruning only"], 0,
      "Water gives up latent heat as it freezes, holding the bud near zero inside a shell of ice. Smudge pots and wind machines are also used."),
    Q("Chablis",
      "Petit Chablis differs from Chablis chiefly in what respect?",
      ["It comes from Portlandian soils", "It is sweet",
       "It is made from Aligote", "It must be aged in oak before release"], 0,
      "A separate appellation for outlying sites off the Kimmeridgian, on the younger Portlandian rock above it, generally lighter and for earlier drinking."),
    Q("Chablis",
      "Which Chablis Grand Cru climat is often singled out as the most structured and longest-lived?",
      ["Les Clos", "Petit Chablis", "Montee de Tonnerre", "Fourchaume"], 0,
      "Les Clos is the largest and most celebrated of the seven. Montee de Tonnerre and Fourchaume are Premiers Crus, and fine ones."),

    # ------------------------------- Cote Chalonnaise and Maconnais (5) -----
    Q("Cote Chalonnaise and Maconnais",
      "Rully, Givry and Montagny sit in the Cote Chalonnaise. Which neighbour outsizes them all?",
      ["Mercurey", "Rully", "Givry", "Montagny"], 0,
      "Mercurey is predominantly red and the best known of the four village appellations there."),
    Q("Cote Chalonnaise and Maconnais",
      "Montagny is unusual among Cote Chalonnaise appellations because it produces what?",
      ["White wine only", "Red wine only", "Sparkling wine only", "Sweet wine only"], 0,
      "Chardonnay alone. Rully makes both and is also a centre for Cremant de Bourgogne."),
    Q("Cote Chalonnaise and Maconnais",
      "Pouilly-Fuisse is found in which sub-region?",
      ["The Maconnais", "The Cote Chalonnaise", "Chablis", "Beaujolais"], 0,
      "The best-known white appellation of the Maconnais, beneath the rock of Solutre, and the first there to gain Premier Cru status."),
    Q("Cote Chalonnaise and Maconnais",
      "Bouzeron holds a village appellation for which grape?",
      ["Aligote", "Chardonnay", "Pinot Noir", "Gamay"], 0,
      "The only village appellation in Burgundy dedicated to Aligote, and the strongest argument that the grape can be more than a kir base."),
    Q("Cote Chalonnaise and Maconnais",
      "What distinguishes Cremant de Bourgogne from a tank-method sparkling wine?",
      ["Its second fermentation is in the bottle", "It is fermented under pressure in tank",
       "It is carbonated after fermentation", "It is fortified with spirit"], 0,
      "Bottle-fermented from Burgundian grapes, with minimum ageing on lees set by the appellation."),

    # ----------------------------------------------------- Beaujolais (5) ---
    Q("Beaujolais",
      "Fleurie, Morgon and Moulin-a-Vent are three of the Beaujolais crus. How many exist in all?",
      ["Ten", "Five", "Seven", "Fifteen"], 0,
      "Brouilly, Cote de Brouilly, Chenas, Chiroubles, Fleurie, Julienas, Morgon, Moulin-a-Vent, Regnie and Saint-Amour, each labelled by its own name."),
    Q("Beaujolais",
      "Which cru is usually called the sturdiest and longest-lived of Beaujolais?",
      ["Moulin-a-Vent", "Chiroubles", "Saint-Amour", "Regnie"], 0,
      "Manganese-rich granite soils give a firmer wine that can age toward something Pinot-like. Chiroubles sits at the other end, light and floral."),
    Q("Beaujolais",
      "By law the new vintage of Beaujolais Nouveau cannot be sold before one fixed date. Which?",
      ["The third Thursday of November", "Christmas Eve", "The first Monday of October",
       "New Year's Day"], 0,
      "Weeks after harvest, by design. It made the region's name commercially and then overshadowed the crus for a generation."),
    Q("Beaujolais",
      "Which vinification technique is characteristic of Beaujolais?",
      ["Carbonic or semi-carbonic maceration", "Extended barrel ageing",
       "Fortification during fermentation", "Botrytis concentration"], 0,
      "Whole clusters ferment under carbon dioxide before pressing, giving bright colour, low tannin and the banana and kirsch aromatics."),
    Q("Beaujolais",
      "Beaujolais soils differ from the Cote d'Or's most fundamentally in being what?",
      ["Granite and schist rather than limestone", "Chalk rather than clay",
       "Volcanic rather than sedimentary", "Sandy rather than stony"], 0,
      "Granite suits Gamay as limestone suits Pinot Noir. The geological break is much of why the two halves of Burgundy taste unrelated."),

    # -------------------------------------- climate, soil and vineyard (4) --
    Q("Climate, soil and vineyard",
      "Spring frost and rain at harvest are the recurring Burgundian risks. Which climate type do they point to?",
      ["Continental", "Mediterranean",
       "Maritime and mild", "Arid"], 0,
      "Cold winters, warm summers and a short window in which everything must go right. Vintage variation matters more here than almost anywhere in France."),
    Q("Climate, soil and vineyard",
      "On the Cote d'Or, the finest vineyards are generally found where on the slope?",
      ["Mid-slope", "At the very top", "On the flat land at the base", "In the valley floor"], 0,
      "Mid-slope drains well, escapes the frost that settles at the bottom and keeps the thin topsoil the top of the hill loses."),
    Q("Climate, soil and vineyard",
      "Which pair of rock types underlies most of the Cote d'Or?",
      ["Limestone and marl", "Granite and schist", "Basalt and tuff", "Sandstone and flint"], 0,
      "The proportions shift from parcel to parcel, and those shifts are much of what the climat system is recording."),
    Q("Climate, soil and vineyard",
      "Hail has become a recurring concern in Burgundy. What is its principal danger beyond the current crop?",
      ["Wounded wood invites disease", "It sweetens the fruit",
       "It delays budbreak the following spring", "It improves drainage"], 0,
      "A storm can strip a vineyard in minutes, and wounded wood carries the consequences forward into later seasons. Several recent vintages were shaped by it."),
]
