"""Rank I rewrite - Beer (56 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing.

The running order follows the beer itself: grain and water first, then the
maltings, the brewhouse, the fermenting room, out into the style families a list
actually carries, and finally the cellar, the glass and the plate. A server who
works through it in order meets each fact at the moment it becomes useful.

Cider is left almost entirely alone and the process chemistry is kept shallow,
because a Rank II Beer & Cider category has to sit above this one.

Every stem opener is distinct, the constructions in lib.BANNED_TEMPLATES are
avoided by design rather than by later reframing, and where the answer is a style
name or a term the stem leads with a symptom, a scene at the bar or a line on a
spec sheet so the subject arrives as the answer rather than the first clause.
"""

from lib import Q

CAT = "Beer"
SLUG = "r1-beer"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("The four raw materials", 5),
    ("Malting and kilning", 5),
    ("Mash tun, kettle and hops", 6),
    ("Yeast, fermentation and conditioning", 5),
    ("Lagers of Bohemia and Germany", 7),
    ("Wheat beers, German and Belgian", 4),
    ("Abbey, Trappist, saison and lambic", 6),
    ("Pale ale, IPA, porter and stout", 6),
    ("Numbers on the spec sheet", 4),
    ("Draught, glassware and temperature", 5),
    ("Beer at the table", 3),
]

BANK = [
    # ------------------------------------------- the four raw materials (5) --
    Q("The four raw materials",
      "Brewers at Burton-on-Trent drew on a well water heavy in calcium sulphate, and the pale ales made there gained a notably dry, sharpened bitterness. What is the practice of dosing water elsewhere to imitate that called?",
      ["Burtonisation", "Krausening", "Decoction", "Fining"], 0,
      "Sulphate accentuates hop bitterness and dryness, while carbonate-rich water suits dark roasted grain instead, which is part of why Dublin became a stout town and Burton a pale ale one. Modern brewers build whatever profile they want by adding salts to stripped water."),
    Q("The four raw materials",
      "Alongside a useful load of enzymes, one grain carries a tough outer husk that settles into a natural filter bed when the sweet liquid is drawn off. Which grain is the brewer's default?",
      ["Barley", "Wheat", "Rye", "Maize"], 0,
      "Wheat and rye are huskless and turn a mash gluey and slow to run, so they are used as part of a grist rather than alone. Barley's husk and its high enzyme content are why it, and not any other cereal, became the base of beer."),
    Q("The four raw materials",
      "Long before refrigeration, beers sent on lengthy sea voyages were loaded with extra quantities of one ingredient whose resins hold spoilage bacteria back. Which ingredient?",
      ["Hops", "Malt", "Yeast", "Brewing salts"], 0,
      "Hop alpha acids are mildly antibacterial as well as bitter, so hopping doubled as preservation in an age with no other option. That is the practical root of the heavily hopped export styles, of which India Pale Ale is the famous survivor."),
    Q("The four raw materials",
      "Fermentable sugar disappears from the wort and alcohol, carbon dioxide and a crowd of aroma compounds appear in its place. Which of the four raw materials did that work?",
      ["Yeast", "Hops", "Malt", "Brewing liquor"], 0,
      "Malt supplies the sugar and hops the bitterness, but only yeast converts the one into the other. Strain choice also sets much of the finished flavour, which is why an identical wort can end up as two beers that taste nothing alike."),
    Q("The four raw materials",
      "Bavaria's purity law of 1516 listed only three permitted ingredients, and the omission was ignorance rather than intent. Which ingredient is missing from that list?",
      ["Yeast", "Hops", "Barley", "Water"], 0,
      "Yeast had not been identified, and brewers pitched the dregs of a previous batch without knowing what was in them. Later restatements of the Reinheitsgebot added it once Pasteur and Hansen had explained what was actually doing the work."),

    # ---------------------------------------------- malting and kilning (5) --
    Q("Malting and kilning",
      "Grain is steeped in water, allowed to sprout, then dried to halt the sprouting before the growing shoot eats the starch. What is that whole sequence called?",
      ["Malting", "Mashing", "Lautering", "Conditioning"], 0,
      "The maltster does this work, usually in a business separate from the brewery. Arresting germination at the right moment is the skill: too early and the enzymes are weak, too late and the seed has spent the starch the brewer came for."),
    Q("Malting and kilning",
      "Persuading barley to sprout is laborious and costs the maltster some of the starch outright. What does germination create that makes it worth doing?",
      ["Enzymes able to cut starch into fermentable sugar",
       "Alcohol, in small quantities",
       "The bitterness that balances sweetness",
       "Carbon dioxide for natural carbonation"], 0,
      "Amylase enzymes develop as the seed prepares to feed its own shoot, and the brewer hijacks them in the mash tun. Raw unmalted grain holds plenty of starch but has no means of releasing it."),
    Q("Malting and kilning",
      "Two malts are made from the same barley: one is dried gently and stays pale straw, the other is taken to fierce heat and comes out almost black. Which step accounts for the difference?",
      ["How the malt is kilned",
       "The length of the steep",
       "The barley variety chosen",
       "The moisture content of the grain at harvest"], 0,
      "Kilning temperature and duration drive browning reactions, so colour and flavour climb together from bready through toffee to coffee. Hard roasting also destroys the enzymes, which is why dark malts appear in small proportions beside a pale base."),
    Q("Malting and kilning",
      "A grist is built from one malt supplying almost all the fermentable extract, with small additions of darker malts for colour and flavour. What is the bulk component called?",
      ["Base malt", "Speciality malt", "Crystal malt", "Roasted barley"], 0,
      "Pale ale malt and pilsner malt are the usual bases, and they carry the enzyme load that has to convert the whole mash. Speciality malts are seasoning, and a few percent will change the colour of the finished beer completely."),
    Q("Malting and kilning",
      "The dry coffee and bitter-chocolate bite of an Irish stout, and its near-black colour, come from one part of the grist. Which?",
      ["Roasted unmalted barley",
       "A large proportion of crystal malt",
       "A high dose of Munich malt",
       "A charge of flaked maize"], 0,
      "Roasted barley is taken so far in the kiln that it contributes astringency and roast rather than sugar, while crystal and Munich malts give caramel and bread rather than coffee and flaked maize gives almost no flavour at all. Chocolate and black malts do comparable work in porter, and it is that roast character that separates the family from brown ales."),

    # ------------------------------------- mash tun, kettle and hops (6) --
    Q("Mash tun, kettle and hops",
      "Milled malt meets hot water in the first vessel of the brewhouse and rests there while the enzymes work. What is the sweet liquid run off afterwards called?",
      ["Wort", "Must", "Trub", "Krausen"], 0,
      "Must is the grape equivalent and belongs to winemaking. Trub is the protein and hop sludge that drops out after the boil, and krausen is the foam head that sits on an actively fermenting beer."),
    Q("Mash tun, kettle and hops",
      "Once the sweet liquid has been drawn off, the spent grain bed still holds recoverable sugar, so hot water is trickled through it. What is that rinse called?",
      ["Sparging", "Racking", "Fining", "Krausening"], 0,
      "Sparge water is kept hot enough for the liquid to run freely but not so hot that it strips harsh tannin out of the husks. Rinse too far and the last runnings turn thin and astringent."),
    Q("Mash tun, kettle and hops",
      "A rolling boil sterilises the wort, drives off raw grain volatiles and coagulates protein out of solution. Which further job depends on that same heat?",
      ["Isomerising the hop acids",
       "Converting starch into fermentable sugar",
       "Generating the carbon dioxide that carbonates the beer",
       "Building the alcohol"], 0,
      "Alpha acids are barely soluble until heat rearranges them, so a long boil is what actually extracts bitterness. Starch conversion has already finished in the mash, and the alcohol arrives later with the yeast."),
    Q("Mash tun, kettle and hops",
      "Hops go into a ninety-minute boil at two moments, a charge at the start and another in the final few minutes. What does the late charge give that the early one cannot?",
      ["Aroma and hop flavour",
       "Bitterness, because alpha acids need only brief contact",
       "Colour",
       "Head retention"], 0,
      "The volatile oils that carry hop aroma survive a few minutes of heat but boil away over an hour, so bitterness and aroma need separate additions. It is why a beer can be intensely fragrant and only moderately bitter, or bracingly bitter and almost silent on the nose."),
    Q("Mash tun, kettle and hops",
      "An IPA smells overwhelmingly of grapefruit, mango and pine yet drinks no more bitter than its recipe would suggest. Which cold addition, made well after the kettle, produced that nose?",
      ["Dry hopping", "First wort hopping", "Decoction mashing", "Krausening"], 0,
      "With no heat there is no isomerisation, so the oils are extracted while the bitterness is not. This is the technique behind the whole modern aromatic IPA family, and the aroma it gives fades with age faster than bitterness does."),
    Q("Mash tun, kettle and hops",
      "Rice and maize turn up in the grist of a great many pale lagers around the world. What are they contributing?",
      ["Fermentable sugar with very little flavour",
       "The enzymes that convert the starch",
       "Bitterness to balance the malt",
       "The husk that forms the filter bed"], 0,
      "Adjuncts ferment out almost completely and leave next to no flavour behind, lightening body and colour and lowering cost as they go. A beer brewed to the Reinheitsgebot cannot use them, so the difference between the two is stylistic and not only legal."),

    # ---------------------------- yeast, fermentation and conditioning (5) --
    Q("Yeast, fermentation and conditioning",
      "One tank is held at twenty degrees Celsius and another at ten, each pitched with a different species of yeast. Which pair of words names the two families that result?",
      ["Ale and lager", "Cask and keg", "Sour and wild", "Draught and bottled"], 0,
      "Warm fermentation throws fruity esters and finishes in days; cold fermentation is slow and leaves a cleaner beer in which malt and hops speak plainly. Almost everything else that divides the two families follows from that one choice."),
    Q("Yeast, fermentation and conditioning",
      "Fruity notes of banana, pear drop and apple appear in a warm-fermented beer that never had fruit anywhere near it. Which compounds are responsible?",
      ["Esters", "Alpha acids", "Tannins", "Sulphides"], 0,
      "Esters are yeast by-products and they climb as fermentation temperature climbs, which is precisely why lager brewers keep their tanks cold. A Bavarian wheat beer is the extreme case, where one ester is deliberately encouraged rather than suppressed."),
    Q("Yeast, fermentation and conditioning",
      "A lager tastes of butterscotch and coats the mouth slickly, and the brewer admits the tank was chilled down early. Which compound was never cleaned up?",
      ["Diacetyl", "Acetaldehyde", "Ethyl acetate", "Isoamyl acetate"], 0,
      "Yeast makes diacetyl during fermentation and reabsorbs it afterwards if left warm long enough, a step brewers call the diacetyl rest. Acetaldehyde is the green apple fault and comes from the same impatience."),
    Q("Yeast, fermentation and conditioning",
      "A fine sediment sits in the bottom of the bottle, and the beer carbonated itself in the package rather than in a tank. Which practice produced that?",
      ["Bottle conditioning",
       "Forced carbonation from a gas cylinder",
       "Pasteurisation after filling",
       "Sterile filtration before filling"], 0,
      "Live yeast and a small sugar addition ferment inside the sealed bottle, so the beer keeps developing and rewards a careful pour. Most Trappist beers and a great many Belgian ales arrive this way."),
    Q("Yeast, fermentation and conditioning",
      "A British cellar holds an unfiltered, unpasteurised beer still working on its own yeast, drawn upstairs by a hand pump with no gas behind it. What is that beer called?",
      ["Cask ale", "Keg lager", "Nitro stout", "Lambic"], 0,
      "Cask ale is served at cellar temperature with gentle natural carbonation, and once broached it has only a few days of useful life. Keg beer is filtered, sealed and pushed by gas, which is why it survives far longer on tap."),

    # ------------------------------------ lagers of bohemia and germany (7) --
    Q("Lagers of Bohemia and Germany",
      "Weeks or months of near-freezing storage after the main fermentation drop out haze and round off the harshness of a young beer. What is that period called?",
      ["Lagering", "Sparging", "Mashing", "Fining"], 0,
      "Lagern is simply German for to store, and the whole family of beers took its name from the practice. The long cold rest is also when residual diacetyl and sulphur compounds are scrubbed away."),
    Q("Lagers of Bohemia and Germany",
      "Copies of one 1842 original are sold all over the world under shortenings of its town's name. Which beer are all of them reaching back to?",
      ["The pale golden lager of Plzen",
       "The dark lager of Munich",
       "The amber lager of Vienna",
       "The strong lager of Einbeck"], 0,
      "Soft Bohemian water, pale malt and Saaz hops gave a clear golden beer at the moment glassware became cheap enough for drinkers to see it. Nearly every industrial lager brewed since is a descendant of it."),
    Q("Lagers of Bohemia and Germany",
      "Munich answered Bohemia with a pale lager of its own, rounder, softer in bitterness and leaning on bready malt. What is it called?",
      ["Helles", "Dunkel", "Marzen", "Bock"], 0,
      "Helles simply means pale, and the contrast with a Czech pilsner is malt-led balance against hop-led snap. Dunkel is the older dark Munich style that helles went on to displace at home, since what Spaten was answering in 1894 was the success of Bohemian pilsner."),
    Q("Lagers of Bohemia and Germany",
      "An amber, toasty lager worked out by Anton Dreher in the 1840s took firmer root in Mexico than it ever did at home. Which style?",
      ["Vienna lager", "Schwarzbier", "Kolsch", "Gose"], 0,
      "Vienna malt gives the colour and a light toast without any roast bitterness behind it. Austrian brewers largely abandoned the style, while Austrian emigrants to Mexico kept it alive and it became a fixture there."),
    Q("Lagers of Bohemia and Germany",
      "Bavarian brewing was forbidden over the hot months, so a stronger batch was laid down in one particular month and stored to last until autumn. Which style still carries that month in its name?",
      ["Marzen", "Dunkel", "Kellerbier", "Rauchbier"], 0,
      "Marzen means March, and whatever survived the summer was drunk off at the autumn festival, which is how it became the Oktoberfest beer. Modern festival beers are often paler and lighter than the classic amber version."),
    Q("Lagers of Bohemia and Germany",
      "Monks in Munich brewed a strong dark lager to carry them through a fasting Lent, and its descendants almost all bear names ending in -ator. Which style is that?",
      ["Doppelbock", "Maibock", "Schwarzbier", "Altbier"], 0,
      "Liquid bread was the idea: heavy in malt, sweetish and generally seven to nine percent. Bock is the strong lager family and doppelbock its stronger branch, the suffix following the original Salvator."),
    Q("Lagers of Bohemia and Germany",
      "A jet-black German lager reaches the table and the guest braces for something heavy and sweet, but it is dry, clean and light in body. Which style is in the glass?",
      ["Schwarzbier", "Doppelbock", "Imperial stout", "Dubbel"], 0,
      "Colour and body are not the same property: a small quantity of dark malt colours a beer completely without adding weight to it. That is one of the most useful facts a server has when a guest announces they dislike dark beer."),

    # ---------------------------------- wheat beers, german and belgian (4) --
    Q("Wheat beers, German and Belgian",
      "Banana and clove dominate the nose of a cloudy Bavarian wheat beer, and neither comes from the grain or the hops. What produced them?",
      ["The yeast strain", "The wheat itself", "The kilning of the malt", "A long cold conditioning"], 0,
      "The weizen strain makes isoamyl acetate for the banana and a phenol called 4-vinyl guaiacol for the clove, and a warm ferment encourages both. Change the yeast and the style vanishes whatever the grist looks like."),
    Q("Wheat beers, German and Belgian",
      "Two versions of one Bavarian wheat beer sit on the list, one labelled hefe and the other kristall. What separates them?",
      ["One is filtered, the other is not",
       "One is markedly stronger than the other",
       "One uses wheat and the other barley",
       "One is aged in oak"], 0,
      "Hefe is German for yeast, so a hefeweizen keeps its sediment and is poured cloudy, often after rolling the bottle to rouse it. Kristall is the same beer filtered bright, and filtering strips much of the soft texture along with the haze."),
    Q("Wheat beers, German and Belgian",
      "Coriander seed and dried orange peel are traditional seasonings in one Belgian wheat beer, brewed with a good proportion of unmalted wheat. Which style?",
      ["Witbier", "Hefeweizen", "Saison", "Dunkelweizen"], 0,
      "Unmalted wheat gives the milky haze and a soft, faintly tart palate, and the spicing survives from the centuries before hops took over. The Bavarian wheat beers use no spice at all and take their character from yeast instead."),
    Q("Wheat beers, German and Belgian",
      "German rules set a floor on how much of the grist must be wheat malt before a beer may be sold as Weissbier. Where does that floor sit?",
      ["At least half", "At least a fifth", "At least four fifths", "No minimum is specified"], 0,
      "Most weissbiers in practice run between fifty and seventy percent wheat, with barley malt making up the balance for its enzymes and its husk. Wheat alone would leave the brewer with a mash that has no filter bed at all."),

    # --------------------------------- abbey, trappist, saison and lambic (6) --
    Q("Abbey, Trappist, saison and lambic",
      "The hexagonal Authentic Trappist Product logo may be used only where a set of conditions is satisfied. Which of these is one of them?",
      ["The beer is brewed in the monastery",
       "The beer is bottle conditioned",
       "The abbey stands in Belgium",
       "The beer exceeds six percent alcohol"], 0,
      "Brewing on the premises under the monks' supervision, with the proceeds supporting the community and charitable work, are the tests that matter. Trappist breweries exist well outside Belgium, in the Netherlands, Italy and England among others, and the roster shifts as communities open, close or lose the label."),
    Q("Abbey, Trappist, saison and lambic",
      "A commercial brewery licenses a monastery's name and brews the beer at its own plant some distance away. What may the result be called?",
      ["An abbey beer", "A Trappist beer", "A saison", "A lambic"], 0,
      "Abbey is a style designation and a commercial arrangement rather than a guarantee of monastic production. The Trappist logo exists precisely to draw that line, and it is the distinction most often muddled at the table."),
    Q("Abbey, Trappist, saison and lambic",
      "Strong, pale gold, around eight or nine percent, dry and peppery in spite of the strength, and traditionally Belgian. Which name does that beer usually carry?",
      ["Tripel", "Dubbel", "Witbier", "Gueuze"], 0,
      "Pale malt with a dose of candi sugar gives strength without heaviness, and a hot vigorous ferment dries the beer right out. A dubbel is the darker, raisiny sibling sitting a step lower in strength."),
    Q("Abbey, Trappist, saison and lambic",
      "Farms in Wallonia brewed in the cool months for their seasonal harvest workers to drink through the following summer. Which style descends from that habit?",
      ["Saison", "Lambic", "Witbier", "Dubbel"], 0,
      "The modern style is dry, highly attenuated, peppery and refreshing rather than powerful, which is what a field worker actually needed. Farmhouse origins also mean there was never one recipe, so the family is unusually broad."),
    Q("Abbey, Trappist, saison and lambic",
      "Hot wort is run into a wide shallow open pan under the roof and left overnight so that whatever is in the air can inoculate it. Which family of beers begins that way?",
      ["Lambic", "Kolsch", "Marzen", "Porter"], 0,
      "The vessel is a coolship, and the resident microflora of the Senne valley outside Brussels does the work of a pitched yeast. Fermentation then continues in old oak barrels for anything from one to three years."),
    Q("Abbey, Trappist, saison and lambic",
      "A blender marries young and old barrels, bottles the result, and the sugar still left in the young beer restarts fermentation inside the glass. Which Belgian beer is made this way?",
      ["Gueuze", "Kriek", "Faro", "Tripel"], 0,
      "The blend gives a dry, sharply acidic, vigorously carbonated beer often compared to sparkling wine, and it is corked and caged like one. Kriek is lambic refermented on cherries, and faro is lambic sweetened with sugar."),

    # ------------------------------------ pale ale, ipa, porter and stout (6) --
    Q("Pale ale, IPA, porter and stout",
      "Grapefruit, pine and resin, rather than earthy herbal notes, mark the hops of which pale ale tradition?",
      ["American, built on Cascade and its relatives",
       "English, built on Fuggles and Goldings",
       "German, built on Hallertau",
       "Czech, built on Saaz"], 0,
      "Cascade was the variety that started it, and the citrus and resin signature became the calling card of American craft brewing. The English and continental varieties carry less oil and read herbal, floral and earthy instead."),
    Q("Pale ale, IPA, porter and stout",
      "Extra hops and a higher gravity were built into a pale ale so that it would survive months at sea on the way to a distant garrison. Which style came out of that trade?",
      ["India Pale Ale", "Porter", "Barleywine", "Mild"], 0,
      "Both alcohol and hop resins resist spoilage, so the recipe was insurance as much as flavour. The modern version has kept the hops enthusiastically and quietly dropped the reason for them."),
    Q("Pale ale, IPA, porter and stout",
      "The word stout began in beer language as an adjective for a strong beer of any colour, and in eighteenth-century London it fixed itself permanently to one dark style. Which style was that?",
      ["Porter", "Mild", "Bitter", "Barleywine"], 0,
      "A brewery would list porter and stout porter side by side, and the adjective eventually walked off on its own. That history is why the two styles shade into one another rather than dividing along any clean line."),
    Q("Pale ale, IPA, porter and stout",
      "A dry Irish stout arrives with a dense, tight, creamy head and a soft mouthfeel that reads almost still. Which dispense gas gives it that?",
      ["Nitrogen and carbon dioxide", "Pure carbon dioxide", "Compressed air", "Argon"], 0,
      "Nitrogen is far less soluble than carbon dioxide, so it comes out of solution as very small persistent bubbles and the beer tastes less prickly. The same beer poured on straight carbon dioxide is sharper and noticeably thinner in texture."),
    Q("Pale ale, IPA, porter and stout",
      "Black as ink, close to ten percent, and shipped originally from London across the Baltic to the Russian court. Which beer is that?",
      ["Imperial stout", "Oatmeal stout", "Milk stout", "Dry Irish stout"], 0,
      "The strength served as a preservative on a long cold sea route and as a flourish for a wealthy customer. It also cellars for years, which puts it on the short list of age-worthy beers alongside barleywine, old ale and gueuze."),
    Q("Pale ale, IPA, porter and stout",
      "Milk sugar goes into one dark ale for the very reason that brewer's yeast cannot ferment it. What does the beer gain?",
      ["Sweetness and body, and the name milk stout",
       "Extra bitterness, and the name dry stout",
       "Higher alcohol, and the name imperial stout",
       "A firmer head, and the name porter"], 0,
      "Lactose passes straight through fermentation, so it survives as residual sweetness and a fuller texture. It is also why the style is unsuitable for anyone avoiding dairy, which is worth knowing before it reaches the table."),

    # ---------------------------------------- numbers on the spec sheet (4) --
    Q("Numbers on the spec sheet",
      "One beer on the sheet is marked 12 and another 70 on the same scale, and the second will taste far more bracing. What is being measured?",
      ["Bitterness", "Alcohol by volume", "Colour", "Original gravity"], 0,
      "International Bitterness Units count isomerised hop acids dissolved in the finished beer. A mass-market lager sits in the high single figures, a pilsner in the thirties or forties, and a modern double IPA can run past eighty."),
    Q("Numbers on the spec sheet",
      "The density of the liquid is read before the yeast goes in and again once fermentation has finished, and the gap tells the brewer how much sugar was consumed. What is the first reading called?",
      ["Original gravity", "Final gravity", "Alpha acid content", "Bitterness units"], 0,
      "Water is the reference point at 1.000, so a wort at 1.050 carries a substantial load of dissolved sugar. The difference between the two readings converts directly into alcohol, and the proportion consumed is the attenuation."),
    Q("Numbers on the spec sheet",
      "A guest wants two or three glasses across a long evening without losing the thread of the conversation. Which figure on your list should guide the recommendation?",
      ["Alcohol by volume", "Bitterness units", "Original gravity", "The colour rating"], 0,
      "Beer covers an enormous range, from a three percent mild to a fourteen percent barleywine, so strength is the number that governs the pace of an evening. A serving size that is sensible for one of those is reckless for the other."),
    Q("Numbers on the spec sheet",
      "One beer measures sixty-five bitterness units and tastes balanced, while another measures forty and tastes searing. What explains the reversal?",
      ["Residual sweetness and body mask perceived bitterness",
       "The scale runs backwards, so the lower figure means the more bitter beer",
       "The figure counts hop aroma rather than bitter compounds",
       "The figure is taken on the wort rather than on the finished beer"], 0,
      "Perceived bitterness is a ratio against malt sweetness, so the figure alone does not predict how a beer tastes and brewers talk about balance rather than raw units. A big sweet double IPA carries bitterness that would be punishing in a thin, dry beer."),

    # ------------------------------- draught, glassware and temperature (5) --
    Q("Draught, glassware and temperature",
      "Neglected draught lines grow a film of yeast, bacteria and beer stone that turns everything poured through them cloudy and sour. How often should a working system be cleaned?",
      ["Every one to two weeks", "Once a quarter", "Once a year", "Only when a guest complains"], 0,
      "A fortnight is the usual industry benchmark, and busy lines carrying unfiltered or heavily hopped beer need attention sooner. No amount of care in the cellar rescues beer that has been dragged through a dirty line."),
    Q("Draught, glassware and temperature",
      "A long run from a cold room to a bar tower at the far end of the building needs more push than carbon dioxide alone can supply without over-carbonating the beer. What is blended in?",
      ["Nitrogen", "Oxygen", "Compressed air", "Helium"], 0,
      "Nitrogen dissolves poorly, so it supplies pressure without inflating the carbonation of the beer behind it. Air would oxidise the beer and introduce bacteria, which is why it was abandoned as a dispense gas."),
    Q("Draught, glassware and temperature",
      "A tulip, a tall weizen glass and a broad goblet all sit behind the same bar. What is the glass mainly doing for the beer?",
      ["Shaping the head and steering the aroma to the nose",
       "Changing the carbonation level of the beer",
       "Altering the bitterness of the beer",
       "Slowing oxidation over the course of an hour"], 0,
      "A collar of foam holds volatile aroma above the liquid, and the width of the rim decides how much of it reaches the drinker. Shape also governs how fast the beer warms in the hand, which matters for the stronger styles."),
    Q("Draught, glassware and temperature",
      "Poured straight from the fridge at three degrees, a Belgian tripel and an imperial stout both taste of almost nothing. What does serving them warmer restore?",
      ["Aroma and complexity, which cold suppresses",
       "Carbonation, which cold destroys",
       "Bitterness, which cold creates",
       "Head retention, which cold prevents"], 0,
      "Volatile compounds need warmth to leave the liquid, so a very cold strong beer is mute. Crisp lagers are served cold for the opposite reason, since coldness is much of their appeal and there is less aroma to lose."),
    Q("Draught, glassware and temperature",
      "The glass is held at forty-five degrees for most of the pour and straightened at the end. What is the pourer actually controlling?",
      ["The depth of the head",
       "The temperature of the beer",
       "The bitterness of the beer",
       "The rate at which the keg empties"], 0,
      "Beer knocked straight into an upright glass releases its gas as foam and leaves the liquid beneath flat. A head of the right depth is part of the style, so pouring to avoid foam altogether is as much a mistake as drowning the glass in it."),

    # -------------------------------------------------- beer at the table (3) --
    Q("Beer at the table",
      "Charred, grilled and heavily roasted flavours on the plate find a direct echo in one class of beer rather than a contrast. Which?",
      ["Porter and stout", "Wheat beer", "Pilsner", "Witbier"], 0,
      "The crust on the meat and the roast in the malt come from the same browning reactions, so the flavours run in parallel rather than against each other. The same resemblance carries the pairing on to chocolate and coffee puddings."),
    Q("Beer at the table",
      "Briny raw shellfish is served in Dublin and Galway beside a dark beer that is low in alcohol, dry and roasty. Which beer is it?",
      ["Dry Irish stout", "Doppelbock", "Tripel", "Hefeweizen"], 0,
      "Roast bitterness plays against the salt while the creamy texture flatters the shellfish, and the modest strength keeps the beer from swamping it. It is among the oldest surviving beer pairings in the trade."),
    Q("Beer at the table",
      "A hop-forward beer poured beside a sweet dessert turns harsh and metallic in the glass. What has happened?",
      ["Sugar in the dish has sharpened perceived bitterness",
       "The dessert has stripped the carbonation out of the beer",
       "The sugar has raised the actual alcohol content of the beer",
       "The cold of the dessert has muted the malt"], 0,
      "Sweetness in the food pushes up the perceived bitterness and acidity of whatever is drunk alongside it, exactly as it does with a dry wine. A pudding wants a beer at least as sweet as itself, which is why a doppelbock or a fruit lambic answers better."),
]
