"""Rank I rewrite — Bordeaux (63 questions).

Second category, run to test the pilot's amendment: vary stem construction
deliberately from the start rather than reframing collisions afterwards. Every
stem here opens differently by design, and lib.template_variety enforces it.

Written from the syllabus below. The imported bank was not read while writing.
"""

from lib import Q

CAT = "Bordeaux"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"
SLUG = "r1-bordeaux"

SYLLABUS = [
    ("Geography and the rivers", 6),
    ("Grape varieties", 7),
    ("The 1855 Classification", 7),
    ("Left Bank appellations", 8),
    ("Right Bank appellations", 7),
    ("The Saint-Emilion classification", 4),
    ("Sweet wines", 6),
    ("Dry whites", 5),
    ("Winemaking and the trade", 6),
    ("Soil and terroir", 4),
    ("Labels and hierarchy", 3),
]

BANK = [
    # ------------------------------------------- geography and rivers (6) ---
    Q("Geography and the rivers",
      "The Garonne and the Dordogne converge to form which estuary?",
      ["The Gironde", "The Charente", "The Adour", "The Sevre"], 0,
      "The two rivers meet north of the city to form the Gironde estuary. Left Bank and Right Bank are defined by which side of that water a vineyard sits on."),
    Q("Geography and the rivers",
      "A merchant offers you a Left Bank red. Which grape most likely leads its blend?",
      ["Cabernet Sauvignon", "Merlot", "Cabernet Franc", "Petit Verdot"], 0,
      "Left Bank gravel suits Cabernet Sauvignon, which usually dominates there. The Right Bank's cooler clay and limestone favour Merlot instead."),
    Q("Geography and the rivers",
      "Entre-Deux-Mers sits between which two rivers?",
      ["The Garonne and the Dordogne", "The Garonne and the Gironde",
       "The Dordogne and the Isle", "The Ciron and the Garonne"], 0,
      "The name means between two seas, though the two waters are tidal rivers. The appellation itself is used for dry white wine only."),
    Q("Geography and the rivers",
      "Of these appellations, which one lies on the Right Bank?",
      ["Pomerol", "Margaux", "Saint-Julien", "Pessac-Leognan"], 0,
      "Pomerol and Saint-Emilion are Right Bank. Margaux, Saint-Julien and Pessac-Leognan all sit on the Left Bank."),
    Q("Geography and the rivers",
      "Why does proximity to the Gironde estuary benefit Medoc vineyards?",
      ["Water moderates temperature and reduces frost risk", "It raises the acidity of the fruit",
       "It supplies irrigation water", "It prevents fungal disease"], 0,
      "A large body of water warms and cools slowly, damping extremes and lowering frost risk. The best Medoc vineyards sit close to the water for that reason."),
    Q("Geography and the rivers",
      "Bordeaux is moderated by the Atlantic and sheltered by the Landes forest. Which climate type is this?",
      ["Maritime", "Continental", "Mediterranean", "Alpine"], 0,
      "Ocean proximity keeps the swing between seasons narrow. It also brings rain, which is why vintage variation matters so much here."),

    # ------------------------------------------------ grape varieties (7) ---
    Q("Grape varieties",
      "In most Right Bank blends, which variety dominates?",
      ["Merlot", "Cabernet Sauvignon", "Petit Verdot", "Malbec"], 0,
      "Merlot ripens earlier and suits the cooler clay soils of Pomerol and Saint-Emilion, giving the plusher, rounder style of the Right Bank."),
    Q("Grape varieties",
      "A blending component ripens late and brings blackcurrant, cedar and firm tannin. Which is it?",
      ["Cabernet Sauvignon", "Merlot", "Muscadelle", "Semillon"], 0,
      "Cabernet Sauvignon's thick skins give colour and tannin, and its late ripening is why it needs the Left Bank's warm, well-drained gravel."),
    Q("Grape varieties",
      "One of these is not a permitted red Bordeaux variety. Which?",
      ["Syrah", "Petit Verdot", "Carmenere", "Malbec"], 0,
      "The classic red set is Cabernet Sauvignon, Merlot, Cabernet Franc, Petit Verdot, Malbec and Carmenere. Syrah belongs to the Rhone and is not permitted."),
    Q("Grape varieties",
      "White Bordeaux is built mainly on which pair of grapes?",
      ["Sauvignon Blanc and Semillon", "Chardonnay and Viognier",
       "Chenin Blanc and Colombard", "Riesling and Muscadelle"], 0,
      "Sauvignon Blanc brings aroma and acidity, Semillon weight and texture. The proportions swing between crisp Entre-Deux-Mers and richer Pessac-Leognan."),
    Q("Grape varieties",
      "Petit Verdot rarely exceeds a few percent of a blend. What explains that?",
      ["It ripens very late and is intensely coloured and tannic", "It is prone to noble rot",
       "It is banned above five percent", "It loses colour in barrel"], 0,
      "Petit Verdot ripens later even than Cabernet Sauvignon and can fail in cool years. Used sparingly it adds colour, structure and a violet note."),
    Q("Grape varieties",
      "Chateau Cheval Blanc is known for an unusually high proportion of which grape?",
      ["Cabernet Franc", "Petit Verdot", "Malbec", "Semillon"], 0,
      "Cheval Blanc's Saint-Emilion vineyard carries far more Cabernet Franc than its neighbours, which is much of what makes its style distinctive."),
    Q("Grape varieties",
      "Sauternes producers prize one grape for its thin skin and affinity for noble rot. Which?",
      ["Semillon", "Sauvignon Blanc", "Muscadelle", "Colombard"], 0,
      "Semillon's thin skin lets Botrytis take hold readily, and its waxy texture carries the sweetness. Sauvignon Blanc is blended in for acidity and lift."),

    # ------------------------------------------ the 1855 classification (7) -
    Q("The 1855 Classification",
      "In 1855 brokers were asked to rank Bordeaux's wines for a world exposition held in which city?",
      ["Paris", "London", "Vienna", "Brussels"], 0,
      "Napoleon III wanted a ranking ready for the Universal Exposition in Paris. The brokers produced the list, and it has barely changed since."),
    Q("The 1855 Classification",
      "How many tiers does the 1855 classification of reds contain?",
      ["Five", "Three", "Four", "Seven"], 0,
      "First through Fifth Growths, or premiers through cinquiemes crus. Sauternes was classified at the same time on a separate scale."),
    Q("The 1855 Classification",
      "On what basis were the 1855 growths ranked?",
      ["The prices the wines had been commanding", "A blind tasting by the brokers",
       "Vineyard soil surveys", "The age of each estate"], 0,
      "The brokers ranked by long-standing market price, which they took as the settled verdict on quality. No tasting was involved."),
    Q("The 1855 Classification",
      "Only one 1855 red First Growth lies outside the Medoc. Which?",
      ["Haut-Brion", "Latour", "Margaux", "Lafite Rothschild"], 0,
      "Haut-Brion sits in Graves, now Pessac-Leognan, and its reputation was too great to leave out of a Medoc-focused list."),
    Q("The 1855 Classification",
      "Baron Philippe de Rothschild campaigned for half a century over his estate's rank. Which chateau was it?",
      ["Mouton Rothschild", "Palmer", "Lynch-Bages", "Pontet-Canet"], 0,
      "Mouton's elevation in 1973 is the only substantive change ever made to the red classification, and it took decades of pressure to win."),
    Q("The 1855 Classification",
      "At its creation, the 1855 list named how many First Growths?",
      ["Four", "Three", "Five", "Six"], 0,
      "Lafite, Latour, Margaux and Haut-Brion. Mouton's 1973 promotion took the number to five, where it stands."),
    Q("The 1855 Classification",
      "Chateau d'Yquem holds a rank unique in the 1855 classification. What is it?",
      ["Premier Cru Superieur", "Grand Cru Exceptionnel",
       "Premier Grand Cru Classe A", "Cru Hors Classe"], 0,
      "Yquem alone was placed above the First Growths of Sauternes, in a tier created for it and never given to another estate."),

    # ------------------------------------------- left bank appellations (8) -
    Q("Left Bank appellations",
      "Lafite Rothschild and Latour both lie in which commune?",
      ["Pauillac", "Margaux", "Saint-Estephe", "Saint-Julien"], 0,
      "Pauillac holds three of the five First Growths, more than any other commune, and its wines are the Medoc benchmark for structure and cassis."),
    Q("Left Bank appellations",
      "Margaux and Haut-Brion are two of the five First Growths. Where are the other three?",
      ["All in Pauillac", "All in Saint-Julien", "All in Saint-Estephe",
       "Split between Saint-Julien and Margaux"], 0,
      "Lafite Rothschild, Latour and Mouton Rothschild are all Pauillac, which is why that commune is treated as the Medoc benchmark."),
    Q("Left Bank appellations",
      "Travelling north through the Medoc, which of the four great communes comes last?",
      ["Saint-Estephe", "Margaux", "Saint-Julien", "Pauillac"], 0,
      "Running north the order is Margaux, Saint-Julien, Pauillac, Saint-Estephe. The northernmost has more clay and a firmer, sterner reputation."),
    Q("Left Bank appellations",
      "Pessac-Leognan was carved out of which larger appellation?",
      ["Graves", "Haut-Medoc", "Entre-Deux-Mers", "Medoc"], 0,
      "Created in 1987 for the northern, finest part of Graves, it holds Haut-Brion and the best dry whites of Bordeaux."),
    Q("Left Bank appellations",
      "Immediately south of Pauillac lies which commune?",
      ["Saint-Julien", "Saint-Estephe", "Margaux", "Listrac"], 0,
      "Saint-Julien sits between Pauillac and Margaux, and is often described as balancing Pauillac's power with Margaux's finesse."),
    Q("Left Bank appellations",
      "Margaux is most often praised for which stylistic quality?",
      ["Perfume and finesse", "Massive tannin", "High residual sugar", "Overt oak"], 0,
      "Margaux's lighter, more gravelly soils give the most aromatic and silken of the great Medoc communes, though it is also the largest and most varied."),
    Q("Left Bank appellations",
      "Gravel dominates the Left Bank. Why does that suit Cabernet Sauvignon?",
      ["It drains freely and stores warmth, helping a late variety ripen",
       "It holds water for the whole season", "It raises acidity in the fruit",
       "It prevents phylloxera"], 0,
      "Deep gravel banks shed water and radiate stored heat, which is what lets a late-ripening variety finish in a maritime climate."),
    Q("Left Bank appellations",
      "The four classified communes of the Medoc all sit within which broader appellation?",
      ["Haut-Medoc", "Medoc", "Graves", "Cotes de Bordeaux"], 0,
      "Haut-Medoc covers the southern, finer half of the peninsula. The plain Medoc appellation covers the northern part beyond it."),

    # ------------------------------------------ right bank appellations (7) -
    Q("Right Bank appellations",
      "Chateau Petrus is found in which appellation?",
      ["Pomerol", "Saint-Emilion", "Fronsac", "Margaux"], 0,
      "Petrus sits on Pomerol's clay plateau and is made almost entirely from Merlot. Pomerol is tiny and has no classification at all."),
    Q("Right Bank appellations",
      "Among major Bordeaux appellations, Pomerol is unusual in lacking what?",
      ["Any official classification", "Any red wine production",
       "Permission to use Merlot", "An appellation of its own"], 0,
      "Pomerol has never been classified. Reputation and price do the ranking instead, which has not held its best estates back."),
    Q("Right Bank appellations",
      "Pomerol, Fronsac and Lalande-de-Pomerol are all small. Which Right Bank neighbour dwarfs them?",
      ["Saint-Emilion", "Pomerol", "Fronsac", "Lalande-de-Pomerol"], 0,
      "Saint-Emilion dwarfs its neighbours in area and number of estates, which is part of why it needs a classification and Pomerol does not."),
    Q("Right Bank appellations",
      "Montagne-Saint-Emilion is an example of what?",
      ["A Saint-Emilion satellite appellation", "A First Growth",
       "A sweet wine appellation", "A negociant house"], 0,
      "The satellites, including Montagne, Lussac, Puisseguin and Saint-Georges, may append the Saint-Emilion name to their own."),
    Q("Right Bank appellations",
      "Fronsac lies close to which river?",
      ["The Dordogne", "The Garonne", "The Ciron", "The Adour"], 0,
      "Fronsac and Canon-Fronsac sit just west of Saint-Emilion above the Dordogne, and are long regarded as offering Right Bank character at lower prices."),
    Q("Right Bank appellations",
      "Cotes de Bourg and Blaye face the Medoc from which side?",
      ["The Right Bank", "The Left Bank", "Downstream of the estuary mouth", "Inland of Entre-Deux-Mers"], 0,
      "Both look across the Gironde at the Medoc from the Right Bank, and both are Merlot-led."),
    Q("Right Bank appellations",
      "Pomerol's plateau is known for a distinctive soil feature. What is it?",
      ["Iron-rich clay, the crasse de fer", "Pure chalk", "Volcanic ash", "Wind-blown sand"], 0,
      "A band of iron-bearing clay underlies the best of the plateau, and is commonly credited with the density and the mineral, truffled note of the wines."),

    # ------------------------------- the saint-emilion classification (4) ---
    Q("The Saint-Emilion classification",
      "How often is the Saint-Emilion classification revised?",
      ["Roughly every ten years", "Once a century", "Every vintage", "It has never been revised"], 0,
      "Periodic revision is the point of it: estates can be promoted or demoted, which makes it the living counterpart to the fixed 1855 list."),
    Q("The Saint-Emilion classification",
      "What is the top tier of the Saint-Emilion classification?",
      ["Premier Grand Cru Classe A", "Grand Cru Classe", "Premier Cru Superieur", "Cru Bourgeois Exceptionnel"], 0,
      "Below it sit Premier Grand Cru Classe B and then Grand Cru Classe. Note that plain Saint-Emilion Grand Cru is an appellation, not a rank."),
    Q("The Saint-Emilion classification",
      "The Saint-Emilion classification differs from the 1855 in one fundamental way. Which?",
      ["It is revisable, so estates can rise and fall", "It ranks only white wines",
       "It was created by Napoleon III", "It has a single tier"], 0,
      "The 1855 list has changed once in more than a century and a half. Saint-Emilion rebuilds its ranking periodically, with all the argument that invites."),
    Q("The Saint-Emilion classification",
      "Which two chateaux were the original Premier Grand Cru Classe A?",
      ["Ausone and Cheval Blanc", "Petrus and Le Pin",
       "Figeac and Pavie", "Angelus and Canon"], 0,
      "Ausone and Cheval Blanc held the top rank alone for decades before the category was widened, and the membership has moved since."),

    # ----------------------------------------------------- sweet wines (6) --
    Q("Sweet wines",
      "Sauternes owes its sweetness chiefly to what?",
      ["Noble rot concentrating the grapes", "Fortification during fermentation",
       "Added grape concentrate", "Freezing the fruit on the vine"], 0,
      "Botrytis cinerea pierces the skin and the berry dehydrates, concentrating sugar and acid and adding its own honeyed character."),
    Q("Sweet wines",
      "The cold Ciron meets the warmer Garonne each autumn. Why does that matter?",
      ["It generates the morning mists that encourage noble rot", "It cools the fermentation cellars",
       "It irrigates the vineyards", "It prevents hail"], 0,
      "Mist forms overnight and burns off in afternoon sun. That damp-then-dry alternation is exactly what noble rot needs and grey rot does not get."),
    Q("Sweet wines",
      "One commune inside the Sauternes area may use its own appellation. Which?",
      ["Barsac", "Bommes", "Fargues", "Preignac"], 0,
      "Barsac wines may be labelled either Barsac or Sauternes. Barsac sits on more limestone and is often a shade lighter in style."),
    Q("Sweet wines",
      "Yields in Sauternes are famously low. What drives that?",
      ["Botrytised berries shrivel, and picking is selective and repeated",
       "The appellation forbids irrigation", "Vines are planted very sparsely",
       "Only one press cycle is permitted"], 0,
      "A shrivelled berry yields little juice, and pickers take only what is ready. Yquem's output per vine is proverbially close to a single glass."),
    Q("Sweet wines",
      "Across the Garonne from Sauternes lies which sweet white appellation?",
      ["Loupiac", "Pomerol", "Listrac", "Fronsac"], 0,
      "Loupiac, Cadillac and Sainte-Croix-du-Mont face Sauternes from the opposite bank and make botrytis-affected sweet whites at gentler prices."),
    Q("Sweet wines",
      "Pickers in Sauternes pass through the vineyard repeatedly through the harvest. What is that practice called?",
      ["Tries successives", "Saignee", "Remuage", "Assemblage"], 0,
      "Successive passes take only the berries that have reached the right state of botrytis. It is slow, weather-dependent and the main reason for the cost."),

    # ------------------------------------------------------ dry whites (5) --
    Q("Dry whites",
      "Age-worthy dry white Bordeaux is most associated with which appellation?",
      ["Pessac-Leognan", "Entre-Deux-Mers", "Sauternes", "Pomerol"], 0,
      "Barrel-fermented Sauvignon and Semillon from Pessac-Leognan are the region's serious whites, and the best age for decades."),
    Q("Dry whites",
      "The Entre-Deux-Mers appellation may be used for which style?",
      ["Dry white only", "Red only", "Sweet white only", "Any style"], 0,
      "The appellation covers dry white wine. Red wine grown in the same area is sold as Bordeaux or Bordeaux Superieur instead."),
    Q("Dry whites",
      "Semillon is blended with Sauvignon Blanc for what reason?",
      ["It adds weight and texture where Sauvignon gives aroma and acidity",
       "It raises the alcohol", "It deepens the colour", "It prevents oxidation"], 0,
      "The pairing is complementary: Semillon's broad, waxy palate fills out Sauvignon's sharper aromatic drive, and it also ages well."),
    Q("Dry whites",
      "Barrel fermentation contributes what to a white Pessac-Leognan?",
      ["Texture and a toasty, spicy overlay", "Higher acidity",
       "Residual sugar", "Deeper colour from the skins"], 0,
      "Fermenting and ageing in barrel builds body and integrates oak more gently than ageing alone, and lees work adds further texture."),
    Q("Dry whites",
      "A third grape adds a floral, grapey lift in small amounts to white Bordeaux. Which?",
      ["Muscadelle", "Viognier", "Chenin Blanc", "Riesling"], 0,
      "Muscadelle is used in small proportions for perfume. It is unrelated to the Muscat family despite the resemblance in name."),

    # ------------------------------------- winemaking and the trade (6) ----
    Q("Winemaking and the trade",
      "What structural feature defines a red Bordeaux?",
      ["It is a blend of several permitted varieties", "It is always a single variety",
       "It is fortified after fermentation", "It is aged only in stainless steel"], 0,
      "Blending is the region's central idea: varieties ripen differently and hedge each other across vintages, and the assemblage is decided each year."),
    Q("Winemaking and the trade",
      "Buying a wine as futures, before it is bottled, is known as what?",
      ["En primeur", "Sur lie", "Negoce direct", "Recolte"], 0,
      "Wine is offered in the spring after harvest while still in barrel, and delivered a couple of years later. It funds the chateau and sets the vintage's price."),
    Q("Winemaking and the trade",
      "Most Bordeaux chateaux sell their wine through whom?",
      ["Negociants, introduced by courtiers", "Directly to the public only",
       "Government auction", "Cooperative bottling only"], 0,
      "The chateau sells to negociant merchants, brokered by courtiers, who distribute onward. Few great estates sell direct."),
    Q("Winemaking and the trade",
      "A chateau's junior label, made from younger vines and declassified lots, is called what?",
      ["A second wine", "A cru bourgeois", "A vin de garage", "A recolte"], 0,
      "Second wines let a chateau keep the grand vin strict while still selling the rest, and they carry the house style at a lower price."),
    Q("Winemaking and the trade",
      "Red Bordeaux is traditionally matured in barrels of what size?",
      ["225 litres", "500 litres", "60 litres", "1,000 litres"], 0,
      "The 225 litre barrique is the Bordeaux standard, and its surface-to-volume ratio is much of why the region's oak influence is what it is."),
    Q("Winemaking and the trade",
      "The network of negociants and courtiers that trades Bordeaux is called what?",
      ["The Place de Bordeaux", "The Cercle Rive Droite", "The Union des Grands Crus", "The Bourse du Vin"], 0,
      "The Place is the trading system itself, and it now distributes wines from well beyond Bordeaux."),

    # ------------------------------------------------ soil and terroir (4) --
    Q("Soil and terroir",
      "Left Bank and Right Bank soils differ broadly in what way?",
      ["Gravel on the Left, clay and limestone on the Right", "Chalk on the Left, sand on the Right",
       "Volcanic on the Left, granite on the Right", "They are essentially identical"], 0,
      "That difference is why the grape emphasis flips across the estuary: gravel for late Cabernet Sauvignon, cooler clay for earlier Merlot."),
    Q("Soil and terroir",
      "Saint-Emilion's limestone plateau particularly suits which variety?",
      ["Merlot", "Petit Verdot", "Sauvignon Blanc", "Malbec"], 0,
      "Limestone holds moisture in reserve and keeps acidity, which suits Merlot. Cabernet Franc does well there too."),
    Q("Soil and terroir",
      "In Bordeaux, what does the word chateau denote?",
      ["A wine estate, whether or not a grand building exists", "A castle open to visitors",
       "A classified growth only", "A cooperative cellar"], 0,
      "Chateau names an estate and its vineyard holdings. Many carry no building of the kind the word suggests."),
    Q("Soil and terroir",
      "Well-drained gravel warms readily. Which ripening problem does that help solve?",
      ["Finishing a late-ripening variety in a cool, damp climate", "Excessive sugar accumulation",
       "Loss of colour in the skins", "Premature budbreak"], 0,
      "Warmth at the root and free drainage push a late variety over the line. In wet years drainage matters as much as the heat."),

    # --------------------------------------------- labels and hierarchy (3) -
    Q("Labels and hierarchy",
      "Where does Cru Bourgeois sit relative to the 1855 growths?",
      ["Below and outside them", "Above the First Growths",
       "Between Second and Third Growths", "It is another name for Fifth Growths"], 0,
      "Cru Bourgeois is a separate Medoc ranking for estates the 1855 list did not include, and it has been reorganised several times."),
    Q("Labels and hierarchy",
      "Bordeaux Superieur differs from basic Bordeaux AOC in what respect?",
      ["Lower yields, higher minimum alcohol and longer ageing", "It must be white",
       "It must come from the Medoc", "It must be a single variety"], 0,
      "Superieur is a stricter version of the regional appellation rather than a different place, so the fruit may come from anywhere in the region."),
    Q("Labels and hierarchy",
      "A label reading simply Bordeaux AOC tells you what about sourcing?",
      ["The fruit may come from anywhere in the wider region", "The fruit is from the Medoc",
       "The wine is classified", "The wine is sweet"], 0,
      "It is the regional catch-all, and the majority of Bordeaux by volume is sold under it. Nothing about a commune or a rank is implied."),
]
