"""Rank I rewrite - Champagne (60 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

A parallel category covers other sparkling and fortified wines, so nothing here
strays outside the appellation: the five districts, the three grapes, the method
end to end, dosage, the village crus, the producer codes, the three quality
tiers, the ageing floors and service at the table.
"""

from lib import Q

CAT = "Champagne"
SLUG = "r1-champagne"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Geography and the five districts", 8),
    ("The three principal grapes", 6),
    ("The traditional method", 10),
    ("Dosage and sweetness levels", 6),
    ("The cru village system", 6),
    ("Houses, growers and cooperatives", 6),
    ("Non-vintage, vintage and prestige cuvee", 6),
    ("Ageing requirements", 5),
    ("Service and storage", 7),
]

BANK = [
    # ------------------------------ geography and the five districts (8) -----
    Q("Geography and the five districts",
      "Five named districts make up the Champagne vineyard. Which of them is planted overwhelmingly to Chardonnay?",
      ["The Cote des Blancs", "The Montagne de Reims", "The Vallee de la Marne",
       "The Cote des Bar"], 0,
      "The name states the case: a run of east-facing chalk slopes south of Epernay that supplies the backbone of most Blanc de Blancs. The Cote de Sezanne continues the same seam further south."),
    Q("Geography and the five districts",
      "Frost-prone valley floors reward a variety that buds late and ripens early. Which district is that variety's stronghold?",
      ["The Vallee de la Marne", "The Cote des Blancs", "The Montagne de Reims",
       "The Cote de Sezanne"], 0,
      "Meunier dominates the Marne valley for exactly that reason. Later budbreak carries it past the worst of the frosts that settle on low ground, and early ripening finishes the job in a short season."),
    Q("Geography and the five districts",
      "Ranged around a wooded plateau south of Reims, which district is dominated by Pinot Noir?",
      ["The Montagne de Reims", "The Cote des Blancs", "The Cote de Sezanne",
       "The Vallee de la Marne"], 0,
      "The mountain is a low forested plateau and its vineyards ring the slopes on almost every aspect. Grand Cru villages such as Verzenay, Ambonnay and Bouzy sit on it."),
    Q("Geography and the five districts",
      "Growers in the Aube department work land closer to Chablis than to Epernay. What is their district called?",
      ["The Cote des Bar", "The Cote des Blancs", "The Montagne de Reims",
       "The Cote de Sezanne"], 0,
      "It lies roughly a hundred kilometres south of the Marne heartland, on Kimmeridgian marl rather than pure chalk, and it is planted mostly to Pinot Noir."),
    Q("Geography and the five districts",
      "Deep, porous white rock stores winter rainfall, drains freely and throws light back into the canopy. Which subsoil is described?",
      ["Chalk", "Granite", "Volcanic tuff", "Alluvial gravel"], 0,
      "Belemnite and Micraster chalk underlie the best slopes. It works as a reservoir in a dry summer and a drain in a wet one, so the vine neither drowns nor bakes."),
    Q("Geography and the five districts",
      "Beneath Reims, quarries cut by the Gallo-Romans now hold millions of bottles at a steady cool temperature. What are these cellars called?",
      ["Crayeres", "Pupitres", "Celliers", "Gyropalettes"], 0,
      "The Romans quarried building chalk and left pits shaped like inverted pyramids. They hold around ten degrees year round, which is close to ideal for long ageing on the lees."),
    Q("Geography and the five districts",
      "At roughly forty-nine degrees north, the region sits near the northern limit of ripening. What does that give the base wines?",
      ["High acidity and low potential alcohol", "High alcohol and low acidity",
       "Substantial tannin", "Deep colour and high phenolic extract"], 0,
      "Marginal ripening is the basis of the whole style. Fruit picked at modest sugar and searing acidity makes a thin still wine and an ideal sparkling base."),
    Q("Geography and the five districts",
      "Which two towns serve as the region's commercial capitals, one holding the coronation cathedral and the other the Avenue de Champagne?",
      ["Reims and Epernay", "Troyes and Sezanne", "Chalons and Bar-sur-Aube",
       "Ay and Cramant"], 0,
      "Reims has the cathedral and the largest chalk cellars; Epernay's grand avenue runs directly above kilometres of tunnelled galleries."),

    # ----------------------------------- the three principal grapes (6) ------
    Q("The three principal grapes",
      "A label reading Blanc de Blancs tells a guest what about the contents?",
      ["It was made only from white grapes",
       "It was made entirely from black grapes", "It was bottled with no dosage at all",
       "It spent no time ageing on its lees"], 0,
      "White from whites. Chardonnay dominates the category so completely that the terms are used interchangeably, although the rare white varieties are also permitted."),
    Q("The three principal grapes",
      "Only Pinot Noir and Meunier went into a particular cuvee. Which term belongs on the label?",
      ["Blanc de Noirs", "Blanc de Blancs", "Coteaux Champenois", "Cuvee de Prestige"], 0,
      "A white wine pressed from black grapes. Whole-bunch pressing keeps the juice pale, and the results are usually broader and more overtly fruity than a Blanc de Blancs."),
    Q("The three principal grapes",
      "Late budding offers a measure of insurance against spring frost on low-lying sites. Which of the three main varieties provides it?",
      ["Meunier", "Chardonnay", "Pinot Noir", "Pinot Gris"], 0,
      "Meunier buds later and ripens earlier than Pinot Noir, so it both dodges the frost and finishes ahead of the autumn rain. It gives a blend forward fruit and early drinkability."),
    Q("The three principal grapes",
      "A house wants acidity, finesse and the capacity to age for decades. Which variety does it build that cuvee around?",
      ["Chardonnay", "Meunier", "Pinot Gris", "Petit Meslier"], 0,
      "Chardonnay supplies the citrus and chalk line that carries a wine through very long lees ageing. Blanc de Blancs from the Cote des Blancs are often the slowest of all to open."),
    Q("The three principal grapes",
      "Beyond the famous three, several near-extinct varieties remain legal in the appellation. Which is one of them?",
      ["Petit Meslier", "Aligote", "Gamay", "Sylvaner"], 0,
      "Arbane, Petit Meslier, Pinot Blanc and Pinot Gris survive in tiny plantings. A handful of growers now bottle them, often as a single cuvee drawing on all seven permitted varieties."),
    Q("The three principal grapes",
      "Rose here may legally be produced by a route forbidden in most French appellations. What is it?",
      ["Blending in still red wine",
       "Adding red grape skins to the dosage", "Colouring the wine with elderberry",
       "Fermenting the wine on oak chips"], 0,
      "Rose d'assemblage is the common method: the still red goes into the white base before the second fermentation, which gives precise control of colour from year to year. The alternative, rose de saignee, takes its colour from a short maceration on skins instead."),

    # -------------------------------------- the traditional method (10) ------
    Q("The traditional method",
      "Harvesting is done by hand across the whole appellation. Which requirement of the pressing stage explains the rule?",
      ["Whole, unbroken bunches must reach the press", "The fruit must be crushed in the vineyard",
       "Machines cannot climb the slopes", "Sorting is forbidden in the cellar"], 0,
      "A machine breaks the berries, and broken black grapes bleed colour into the juice. Whole bunches also form their own filter bed, so the press runs gently and the juice comes off clean."),
    Q("The traditional method",
      "From a marc of 4,000 kilograms of grapes, what is the greatest volume of juice that may be taken?",
      ["2,550 litres", "4,000 litres", "1,000 litres", "3,600 litres"], 0,
      "The ceiling works out at about 102 litres per 160 kilograms and is deliberately low. Pressing harder extracts phenolics and colour that a delicate base wine cannot carry."),
    Q("The traditional method",
      "The first 2,050 litres to run from that press carry which name?",
      ["The cuvee", "The taille", "The rebeche", "The vin clair"], 0,
      "The cuvee fraction is the cleanest and most acidic juice and goes into the best wines. The 500 litres of taille that follow are richer, coarser and quicker to age."),
    Q("The traditional method",
      "Some producers block malolactic conversion in their base wines. What are they preserving?",
      ["Sharp malic acidity in the base wine", "Residual sugar",
       "Colour extracted from the black skins", "Carbon dioxide from the first fermentation"], 0,
      "Malolactic softens malic acid into lactic and adds a creamy note. Blocking it keeps the wine taut, leaner and longer-lived, at the cost of needing more time or a touch more dosage to come into balance."),
    Q("The traditional method",
      "Blending takes place long before the wine ever sparkles. What does assemblage draw together?",
      ["Different villages, varieties and often several vintages",
       "Wines from a single vineyard in one village only",
       "Wines bought in from other French sparkling regions",
       "Already finished sparkling wines taken after disgorgement"], 0,
      "A large house may taste through hundreds of separate lots in the new year. The blend rather than the vineyard is the traditional unit of quality here, which inverts the Burgundian model."),
    Q("The traditional method",
      "Bottling for the second fermentation includes an addition of sugar and yeast. What is that mixture called?",
      ["The liqueur de tirage", "The liqueur d'expedition", "The rebeche", "The taille"], 0,
      "Still wine, cane sugar and a yeast culture, plus a clarifying agent to help the deposit slide later. The bottle is then sealed under a crown cap and laid down."),
    Q("The traditional method",
      "Trapped carbon dioxide from the second fermentation builds to roughly what pressure?",
      ["About six atmospheres", "About one atmosphere", "About twenty atmospheres",
       "About half an atmosphere"], 0,
      "Five to six bar, comparable to a lorry tyre. Roughly four grams of sugar per litre yields one further atmosphere, and the same fermentation adds a little over one percent alcohol."),
    Q("The traditional method",
      "Brioche, toast and biscuit notes develop while the wine rests on its spent yeast. Which process produces them?",
      ["Autolysis", "Maceration", "Malolactic conversion", "Oxidation through the cork"], 0,
      "The dead yeast cells break down and release amino acids, mannoproteins and other compounds into the wine. The longer the contact, the deeper the register and the finer the bead."),
    Q("The traditional method",
      "Bottles are turned and progressively tilted over a period of weeks. What does remuage accomplish?",
      ["It works the sediment down into the neck", "It dissolves the sediment back into the wine",
       "It raises the pressure in the bottle", "It removes the dosage"], 0,
      "Hand riddling on a pupitre takes a skilled worker several weeks; a gyropalette handles around five hundred bottles at once in a few days. The bottle ends up inverted, sur pointe."),
    Q("The traditional method",
      "Necks are dipped into a freezing bath before the crown cap comes off. What does that achieve?",
      ["It freezes the sediment into a plug", "It sterilises the wine",
       "It drives the carbon dioxide out", "It sweetens the wine"], 0,
      "The pressure in the bottle expels the frozen plug the moment the cap comes off. Degorgement a la glace loses only a mouthful of wine and can be done at speed on a line. The older method a la volee, disgorging unfrozen, is now the minority but stays in real use for magnums and larger formats and among some growers."),

    # ---------------------------------- dosage and sweetness levels (6) ------
    Q("Dosage and sweetness levels",
      "After disgorgement the bottle is topped up with wine and usually a little sugar. What is that addition called?",
      ["The liqueur d'expedition", "The liqueur de tirage", "The remuage", "The rebeche"], 0,
      "Dosage sets the final sweetness and fills the space the ice plug left behind. It is measured in grams of sugar per litre, and the legal categories follow directly from it."),
    Q("Dosage and sweetness levels",
      "A guest assumes Extra Dry is the driest style on the list. Where does it actually sit?",
      ["Sweeter than Brut, at 12 to 17 grams per litre", "Drier than Brut Nature",
       "At exactly the same sweetness as Brut", "At the sweetest end of the scale"], 0,
      "The category names are historical and actively misleading. Sec is sweeter still and Demi-Sec sweeter again, so reading the words as English reverses the truth."),
    Q("Dosage and sweetness levels",
      "How much residual sugar may a wine labelled Brut carry?",
      ["Fewer than 12 grams per litre", "Fewer than 3 grams per litre",
       "Between 17 and 32 grams per litre", "Between 32 and 50 grams per litre"], 0,
      "Brut is by far the largest category and most houses sit somewhere near the middle of the band. The sugar is there to balance ferocious acidity rather than to read as sweetness."),
    Q("Dosage and sweetness levels",
      "No sugar whatever is added at dosage. Which term appears on the label?",
      ["Brut Nature", "Extra Brut", "Sec", "Doux"], 0,
      "Brut Nature, Pas Dose and Dosage Zero all say the same thing, and the wine may still hold up to 3 grams per litre left from fermentation. Nothing conceals a thin base wine."),
    Q("Dosage and sweetness levels",
      "A guest asks you to walk the dosage scale upward in sweetness. Which sequence do you give them?",
      ["Brut Nature, Extra Brut, Brut, Extra Dry, Sec, Demi-Sec, Doux",
       "Brut, Brut Nature, Extra Brut, Sec, Extra Dry, Demi-Sec, Doux",
       "Extra Brut, Brut Nature, Extra Dry, Brut, Sec, Doux, Demi-Sec",
       "Doux, Demi-Sec, Sec, Extra Dry, Brut, Extra Brut, Brut Nature"], 0,
      "Seven categories, of which only the two extremes are intuitive. Extra Dry sitting between Brut and Sec is the step that catches almost everyone."),
    Q("Dosage and sweetness levels",
      "A dessert course calls for something distinctly sweet from the region. Which category fits?",
      ["Demi-Sec, at 32 to 50 grams per litre", "Sec, at 17 to 32 grams per litre",
       "Extra Dry, at 12 to 17 grams per litre", "Brut, under 12 grams per litre"], 0,
      "Demi-Sec is the practical dessert style, since Doux above 50 grams is now very rarely made. A Brut against a sweet dish is left tasting sour and hollow."),

    # --------------------------------------- the cru village system (6) ------
    Q("The cru village system",
      "Unlike the Burgundian arrangement, the cru ranking here attaches to what unit?",
      ["The whole village and all its vineyards", "One named vineyard parcel inside a village",
       "The estate holdings of an individual producer", "The vintage in which the fruit was grown"], 0,
      "Every hectare inside a Grand Cru commune carries the rank, prime slope and flat land alike. It rewards the address rather than the plot, which is why single-vineyard bottlings are a recent development."),
    Q("The cru village system",
      "How many villages hold Grand Cru status in Champagne?",
      ["Seventeen", "Five", "Thirty-three", "Sixty"], 0,
      "Seventeen communes sit at the top, with a broader band of Premiers Crus beneath them. Most Grand Cru land lies in the Montagne de Reims and on the Cote des Blancs."),
    Q("The cru village system",
      "The old echelle des crus rated each village on a percentage scale. What figure marked a Grand Cru?",
      ["One hundred percent", "Ninety percent", "Eighty percent", "Fifty percent"], 0,
      "The scale originally fixed the price a grower was paid per kilogram of fruit. It was dropped as a pricing mechanism in the 2000s, but the rankings it produced remain in everyday use."),
    Q("The cru village system",
      "Villages rated between ninety and ninety-nine on that scale earned which designation?",
      ["Premier Cru", "Grand Cru", "Coteaux Champenois", "Cru Classe"], 0,
      "Anything below ninety carried no cru designation at all. A Premier Cru name on a label is a genuine if broad indication of the quality of the raw material."),
    Q("The cru village system",
      "Avize, Cramant and Le Mesnil-sur-Oger are Grand Cru villages celebrated for which grape?",
      ["Chardonnay", "Pinot Noir", "Meunier", "Pinot Blanc"], 0,
      "All three sit on the Cote des Blancs, where the chalk lies closest to the surface. Le Mesnil is known for wines so austere in youth that they can need a decade to unwind."),
    Q("The cru village system",
      "Ay and Bouzy carry Grand Cru rank on the strength of which variety?",
      ["Pinot Noir", "Chardonnay", "Meunier", "Arbane"], 0,
      "Both are warm, well-exposed sites for black grapes. Bouzy is also known for a still red bottled under the Coteaux Champenois appellation."),

    # ---------------------------- houses, growers and cooperatives (6) -------
    Q("Houses, growers and cooperatives",
      "Two initials in the small print identify who actually made the wine. A bottle marked NM comes from whom?",
      ["A merchant house that buys in grapes",
       "A grower using only fruit from vines it farms", "A cooperative that sells its members' wine",
       "A retailer commissioning its own brand"], 0,
      "Negociant Manipulant covers almost every famous name: the house buys in fruit and bottles the wine under its own name. The houses own only a fraction of the vineyard they need, so long-term grower contracts are the real foundation of the business."),
    Q("Houses, growers and cooperatives",
      "Which code marks a grower who makes and bottles wine from vines they farm themselves?",
      ["RM", "NM", "CM", "MA"], 0,
      "Recoltant Manipulant is the grower-producer, the source of what the trade calls grower Champagne. The scale is small and the wine usually speaks of one village rather than of a house style."),
    Q("Houses, growers and cooperatives",
      "A cooperative vinifies its members' fruit and sells the result under a single brand. Which code applies?",
      ["CM", "RC", "SR", "ND"], 0,
      "Cooperative de Manipulation. RC is the related case, where an individual grower takes finished wine back from the cooperative and sells it under a personal label."),
    Q("Houses, growers and cooperatives",
      "A supermarket commissions Champagne and puts its own brand on the bottle. Which two letters appear?",
      ["MA", "NM", "RM", "SR"], 0,
      "Marque d'Acheteur, a buyer's own brand. The code says nothing at all about quality, only that the name on the front is not the name of the producer."),
    Q("Houses, growers and cooperatives",
      "Where should you look to find that producer code?",
      ["In the small print on the label",
       "On the front label beside the vintage", "Stamped into the base of the bottle",
       "Printed on the foil capsule"], 0,
      "It is required by law and very easy to miss. The number next to it identifies the individual house, grower or cooperative in the official register."),
    Q("Houses, growers and cooperatives",
      "Most of the region's planted area belongs to whom?",
      ["Thousands of small growers", "The largest houses between them",
       "The cooperatives, which own it outright", "The French state"], 0,
      "The average holding is measured in a few hectares and sometimes in fractions of one. That imbalance is why supply contracts and cooperative membership shape the entire trade."),

    # ------------------- non-vintage, vintage and prestige cuvee (6) ---------
    Q("Non-vintage, vintage and prestige cuvee",
      "The majority of Champagne carries no year on the label. What is that blend meant to achieve?",
      ["A consistent house style",
       "The highest possible price", "A wine from a single vineyard",
       "The shortest possible time before sale"], 0,
      "The climate is marginal enough that any single harvest can disappoint. Blending across years, villages and varieties is how a house repeats one recognisable style from one year to the next, and how it makes a difficult vintage taste like a fine one."),
    Q("Non-vintage, vintage and prestige cuvee",
      "Older wines held back in tank or cask are worked into each new blend. What are they called?",
      ["Reserve wines", "Vins clairs", "Taille", "Liqueur de tirage"], 0,
      "Some houses keep a perpetual reserve, topped up at every harvest and drawn from continuously, so a trace of many past vintages runs through every bottle they sell."),
    Q("Non-vintage, vintage and prestige cuvee",
      "When a house declares a vintage, what must be true of the wine?",
      ["All of it comes from that single harvest",
       "At least eighty-five percent comes from that harvest",
       "It contains no reserve wine older than five years", "It receives no dosage"], 0,
      "Declaration is a judgement rather than an entitlement. A house declares only when it believes the year merits it, and in a poor run it may skip several years together."),
    Q("Non-vintage, vintage and prestige cuvee",
      "Created for a Russian tsar and still sold in clear glass, Cristal belongs to which house?",
      ["Louis Roederer", "Taittinger", "Bollinger", "Pol Roger"], 0,
      "The clear bottle was reputedly made so that nothing could be concealed inside it. A prestige cuvee is a house's flagship, drawn from its best crus and given the longest ageing."),
    Q("Non-vintage, vintage and prestige cuvee",
      "Comtes de Champagne, a Blanc de Blancs, is the prestige cuvee of which house?",
      ["Taittinger", "Krug", "Veuve Clicquot", "Perrier-Jouet"], 0,
      "It is named for the counts who ruled the region in the Middle Ages, and it is drawn from Grand Cru Chardonnay on the Cote des Blancs."),
    Q("Non-vintage, vintage and prestige cuvee",
      "Not every prestige cuvee carries a year. Which is the best-known example that does not?",
      ["Krug Grande Cuvee", "Dom Perignon", "Cristal", "Comtes de Champagne"], 0,
      "Grande Cuvee is a multi-vintage blend of well over a hundred separate wines and is the house's signature bottling, though its single-vineyard cuvees sit above it. A vintage date is not what defines the tier."),

    # ------------------------------------------ ageing requirements (5) ------
    Q("Ageing requirements",
      "Before release, a non-vintage wine must rest on its lees in bottle for a minimum period. How long?",
      ["Twelve months", "Three months", "Thirty-six months", "Six years"], 0,
      "Fifteen months must pass in total between tirage and sale, of which at least twelve are on the lees. Serious houses treat those figures as a floor and routinely double them."),
    Q("Ageing requirements",
      "A vintage wine faces a longer legal minimum. What is it?",
      ["Thirty-six months", "Twelve months", "Fifteen months", "Ten years"], 0,
      "Three years is the floor, and many houses hold vintage wines far longer before disgorging. That extra time builds the toasted, nutty register the category is bought for."),
    Q("Ageing requirements",
      "Bollinger's R.D. stands for recemment degorge. What does the label promise?",
      ["Long lees ageing, then recent disgorgement", "No dosage of any kind at disgorgement",
       "A single vineyard as the source of the fruit", "Fermentation in stainless steel rather than in oak"], 0,
      "Recently disgorged. The wine keeps the protection of lees contact for years longer, then reaches the table with the vigour of a young disgorgement and the depth of an old wine."),
    Q("Ageing requirements",
      "Many producers now print the disgorgement date on the back label. What does it let a buyer judge?",
      ["How long the wine has been off its lees", "The year of harvest",
       "The dosage the wine received in grams per litre", "The vineyard of origin"], 0,
      "A wine changes faster once the lees are gone and oxygen begins to reach it past the cork. Two bottles of one cuvee disgorged years apart can taste markedly different."),
    Q("Ageing requirements",
      "What does an unusually long stay on the lees do to the bubble itself?",
      ["It makes the mousse finer and more persistent", "It removes the bubbles altogether",
       "It raises the pressure sharply", "It makes the bubbles noticeably coarser"], 0,
      "Mannoproteins released by the dying yeast lower surface tension and hold carbon dioxide more tightly. The result is a creamy bead rather than a coarse froth."),

    # ------------------------------------------ service and storage (7) ------
    Q("Service and storage",
      "At what temperature is a young non-vintage best poured?",
      ["Eight to ten degrees Celsius", "Two to four degrees Celsius",
       "Sixteen to eighteen degrees Celsius", "Twelve to fourteen degrees Celsius"], 0,
      "Cold enough to keep the mousse lively, warm enough for the aroma to show at all. Serving near freezing mutes the fruit and hardens the acidity."),
    Q("Service and storage",
      "A mature prestige cuvee is often served a few degrees warmer than a young Brut. Why?",
      ["Its complex aromatics need the warmth to open", "It contains far more sugar",
       "Warmth raises the pressure in the bottle", "Cold would strip out the dosage"], 0,
      "Ten to twelve degrees suits an old vintage wine. Treat it much as you would a fine white Burgundy rather than as an aperitif fizz."),
    Q("Service and storage",
      "Opening a bottle safely begins with a thumb held over the cork. How far is the wire cage then loosened?",
      ["Six half-turns of the wire loop", "Two half-turns", "Twelve half-turns",
       "It is lifted off entirely before anything else"], 0,
      "Six half-turns frees the cage on every muselet made. The thumb stays put throughout, because a cork under six atmospheres travels faster than anyone can react."),
    Q("Service and storage",
      "With the cage loosened, which part should be turned?",
      ["The bottle, while the cork is held still", "The cork, while the bottle is held still",
       "Both, in opposite directions", "Neither, the cork is levered upward"], 0,
      "Turning the base gives control and eases the cork out with a sigh rather than a report. Holding the bottle at about forty-five degrees reduces the chance of it foaming over."),
    Q("Service and storage",
      "Which glass shape best serves a fine Champagne at table?",
      ["A tulip that swells at the bowl and narrows at the rim",
       "A wide, shallow coupe with a broad open rim",
       "A narrow, straight-sided flute with no bowl at all",
       "A small fortified-wine glass, filled to the brim"], 0,
      "The bowl gives the aroma room to gather and the narrowed rim delivers it. A coupe spills both the aroma and the bubbles away, whatever its history at parties."),
    Q("Service and storage",
      "A bottle needs chilling quickly during service. Which is fastest?",
      ["A bucket of half ice and half water", "A bucket of ice alone",
       "The freezer compartment for twenty minutes", "The main refrigerator at four degrees"], 0,
      "Water carries heat away from the entire surface of the bottle where ice alone touches it only at points. A handful of salt lowers the bath temperature further still."),
    Q("Service and storage",
      "A freshly polished glass kills the bead within seconds of pouring. What is the usual cause?",
      ["Detergent residue left in the bowl", "The glass being too cold",
       "The glass being too large", "Static from the polishing cloth"], 0,
      "Surfactants collapse foam on contact. Rinse with hot water and polish over steam with a clean, unscented linen cloth, never with a soapy one."),
]
