"""Rank I rewrite - Dessert & Sweet Wines (58 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

The category is organised by MECHANISM rather than by country, because that is
what a floor team actually needs: sugar gets concentrated in the berry by rot,
by frost or by drying, or else it is left in the wine by stopping the yeast.
Port, Sherry, Madeira and Marsala belong to the Sparkling/Fortified/Sweet
category and are deliberately left alone here, so fortification appears only as
the fourth route to sweetness - mutage and the vins doux naturels - and the
weight of the bank sits on botrytis, freezing and appassimento.

Stems lead with a smell, a symptom in the vineyard or a scene at the table and
let the wine, the grape or the process be the answer.
"""

from lib import Q

CAT = "Dessert & Sweet Wines"
SLUG = "r1-dessert-sweet"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Routes to sweetness and the numbers", 6),
    ("Noble rot: conditions and effects", 7),
    ("Sauternes and Barsac", 8),
    ("Tokaji", 6),
    ("Germany and Austria", 7),
    ("Eiswein and Icewine", 6),
    ("Dried-grape wines of Italy", 6),
    ("Drying beyond Italy", 6),
    ("Fortification by arrest", 6),
]

BANK = [
    # --------------------------- routes to sweetness and the numbers (6) -----
    Q("Routes to sweetness and the numbers",
      "Every classic route to a naturally sweet wine works on one of two variables. Which pair?",
      ["Concentrating the sugar in the grape, or halting fermentation before the yeast has used it up",
       "Adding sugar to the must, or adding sugar to the finished wine",
       "Lowering the acidity, or raising the alcohol",
       "Extending skin contact, or extending lees ageing"], 0,
      "Noble rot, frost and drying all take water out of the berry, so what remains is more concentrated. Fortification takes the other path entirely, killing the yeast with spirit while grape sugar is still in the vat."),
    Q("Routes to sweetness and the numbers",
      "Each German Pradikat level carries a minimum juice sugar, read on a scale named after a nineteenth-century Pforzheim goldsmith. Which scale?",
      ["Oechsle", "Brix", "Baume", "Klosterneuburger Mostwaage"], 0,
      "Oechsle measures the density of the must, so a reading of 150 means a litre of juice weighs 150 grams more than a litre of water. Brix, Baume and the Austrian KMW scale record the same ripeness on different arithmetic."),
    Q("Routes to sweetness and the numbers",
      "A technical sheet for a dessert wine gives 120 grams per litre alongside the alcohol and the total acidity. Which measurement is that?",
      ["Residual sugar", "Volatile acidity", "Malic acid", "Glycerol"], 0,
      "Residual sugar is what the yeast never converted, and dessert styles run from roughly 45 grams per litre to several hundred. The other three are reported in the same units but at a small fraction of that figure."),
    Q("Routes to sweetness and the numbers",
      "Two dessert wines carry an identical 150 grams of residual sugar, yet one tastes fresh and the other cloying. Which component most often accounts for the difference?",
      ["Acidity", "Tannin", "Alcohol", "Colour"], 0,
      "Sugar with nothing to cut it turns syrupy in the mouth and tiring after half a glass. It is why the great sweet wines come from cool sites and high-acid grapes such as Riesling, Chenin Blanc and Furmint."),
    Q("Routes to sweetness and the numbers",
      "Chateau d'Yquem is often said to make about a glass of wine from each vine. What lies behind a figure that low?",
      ["Shrivelled berries hold very little juice, and pickers reject most of the crop over repeated passes",
       "The appellation forbids more than one bunch to be left on each vine",
       "Most of the volume is lost to evaporation during long barrel ageing",
       "The greater part of the crop is sold off to negociants"], 0,
      "A berry that has given up half its water yields half as much juice, and fruit that has not rotted cleanly is left on the vine or declassified. The tiny yield is a consequence of the method rather than a rule imposed on it."),
    Q("Routes to sweetness and the numbers",
      "German producers may sweeten a finished dry wine by blending back unfermented juice held aside from the same harvest. What is that reserve called?",
      ["Sussreserve", "Dosage", "Liqueur de tirage", "Mistelle"], 0,
      "Sussreserve is grape juice rather than sugar, so sweetness and wine come from the same fruit. It is legal at every German quality level, Pradikat wines included, so long as the juice is unchaptalised and of at least equal quality from the same region, though the finest sweet wines still get their sugar from a fermentation that stopped of its own accord."),

    # ----------------------------- noble rot: conditions and effects (7) -----
    Q("Noble rot: conditions and effects",
      "A grey fungus punctures the skin of a ripe white grape and, given the right weather, transforms it. What is its Latin name?",
      ["Botrytis cinerea", "Plasmopara viticola", "Erysiphe necator", "Guignardia bidwellii"], 0,
      "One organism causes both noble rot and the grey rot that ruins a crop, and only the weather decides which. The others are downy mildew, powdery mildew and black rot, none of which ever does a grower a favour."),
    Q("Noble rot: conditions and effects",
      "Misty, damp mornings give way to dry breezy afternoons right through the autumn. Why does that alternation matter to a sweet-wine grower?",
      ["Humidity lets noble rot take hold, and the dry afternoons stop it turning destructive",
       "Humidity raises the sugar while the dry afternoons raise the acidity",
       "The daily temperature swing is what sets the colour of the fruit",
       "Damp air prevents the fungus from establishing at all"], 0,
      "Unbroken damp turns the same fungus into grey rot, which splits berries, taints flavour and can take a crop in days. The dry afternoon checks its spread and lets the punctured fruit dehydrate instead."),
    Q("Noble rot: conditions and effects",
      "Rain that never lets up through the harvest turns the sweet-wine grower's ally into a disaster. What is that ruinous form called?",
      ["Grey rot", "Sour rot", "Esca", "Downy mildew"], 0,
      "Grey rot is the same species behaving badly, spreading through sound fruit and leaving mouldy, tainted juice. Sour rot is a separate affair involving bacteria, wild yeasts and fruit flies."),
    Q("Noble rot: conditions and effects",
      "Fungal threads pierce the skin and the berry shrivels over the following days. What is actually happening inside it?",
      ["Water escapes through the perforated skin, concentrating the sugar and acid left behind",
       "The fungus manufactures sugar and feeds it into the berry",
       "The berry draws water up from the stem and swells",
       "Alcohol begins to form inside the intact grape"], 0,
      "No sugar is added from outside the berry. The fungus opens thousands of tiny holes, the berry loses water to the air, and everything dissolved in that water is left behind in a much smaller volume, minus the share of sugar and acid the fungus takes for itself."),
    Q("Noble rot: conditions and effects",
      "Botrytised wines feel unusually viscous in the mouth at only moderate alcohol. Which compound generated by the fungus helps explain that?",
      ["Glycerol", "Tannin", "Malic acid", "Sulphur dioxide"], 0,
      "The fungus produces glycerol as it works through the grape's sugar, and it survives fermentation into the bottle. Texture in these wines comes from sugar, glycerol and extract together rather than from alcohol."),
    Q("Noble rot: conditions and effects",
      "Honey, beeswax, dried apricot, marmalade and a faint mushroomy note run through a deep golden wine. Which process produced that set of aromas?",
      ["Noble rot", "Freezing on the vine", "Fortification with grape spirit", "Ageing under a veil of yeast"], 0,
      "Those markers belong to the fungus rather than to the grape, which is why a botrytised Semillon and a botrytised Furmint smell more like each other than either does like its own dry version."),
    Q("Noble rot: conditions and effects",
      "Juice pressed from nobly rotten fruit browns alarmingly fast and shrugs off the usual dose of sulphur. Which enzyme carried by the fungus is responsible?",
      ["Laccase", "Pectinase", "Invertase", "Amylase"], 0,
      "Laccase is an oxidase the fungus brings with it, and unlike the grape's own oxidase it is barely troubled by sulphur dioxide. Cellars handling botrytised must work quickly and keep air away from it."),

    # ------------------------------------------- Sauternes and Barsac (8) ----
    Q("Sauternes and Barsac",
      "Cold water from a small tributary meets the warmer Garonne and lays mist over the vineyards on autumn mornings. Which river does that work?",
      ["The Ciron", "The Dordogne", "The Lot", "The Isle"], 0,
      "The Ciron runs through cool forest before joining the Garonne at Barsac, and the temperature gap between the two rivers is what makes the fog. No fog, no Sauternes."),
    Q("Sauternes and Barsac",
      "Thin skins and a marked susceptibility to noble rot make one variety the backbone of a Sauternes blend. Which grape?",
      ["Semillon", "Sauvignon Blanc", "Muscadelle", "Colombard"], 0,
      "Semillon rots more readily and more evenly than its partners and carries the waxy, lanolin texture the style depends on. Sauvignon Blanc supplies acidity and lift, and a little Muscadelle is sometimes added for perfume."),
    Q("Sauternes and Barsac",
      "One of the five communes entitled to the Sauternes name may instead bottle under an appellation of its own. Which commune?",
      ["Barsac", "Bommes", "Fargues", "Preignac"], 0,
      "Barsac growers may label as Barsac or as Sauternes, and many use both. Its ground is flatter and more limestone-rich than the gravel further south, and the wines are often a shade lighter and more mineral."),
    Q("Sauternes and Barsac",
      "Sweet white wines were ranked alongside the reds in the Bordeaux classification of 1855. Which estate was placed in a category of its own above all the others?",
      ["Chateau d'Yquem", "Chateau Climens", "Chateau Suduiraut", "Chateau Rieussec"], 0,
      "Yquem was made Premier Cru Superieur, a rank held by no other property in the 1855 lists. The three named beside it are classified growths of Sauternes and Barsac, one tier below."),
    Q("Sauternes and Barsac",
      "Pickers may be sent through the same rows six or more times in a single autumn on a Sauternes estate. What forces that?",
      ["Noble rot arrives berry by berry rather than taking a whole vineyard at once",
       "The appellation caps the quantity that may be picked in a day",
       "Each pass is restricted to one of the three permitted varieties",
       "The fruit must be picked before dawn while it is still cold"], 0,
      "A single bunch can hold shrivelled, healthy and unripe berries at the same moment. Picking it all at once blends concentrate with water, so the crew takes only what is ready and comes back for the rest."),
    Q("Sauternes and Barsac",
      "Just north of Barsac, set within the Graves, lies a smaller appellation making a lighter sweet white. Which one?",
      ["Cerons", "Loupiac", "Sainte-Croix-du-Mont", "Cadillac"], 0,
      "Cerons is the left-bank neighbour, and its growers may also declassify into Graves. Loupiac, Sainte-Croix-du-Mont and Cadillac are the sweet appellations facing them from the opposite bank of the Garonne."),
    Q("Sauternes and Barsac",
      "A classic Sauternes finishes near fourteen per cent alcohol with well over a hundred grams of sugar still in it. Why does the fermentation stop there?",
      ["The accumulating alcohol overwhelms the yeast before the sugar has run out",
       "Grape spirit is added to kill the yeast",
       "The appellation requires the wine to be pasteurised",
       "Sugar is stirred back into the wine after fermentation"], 0,
      "A must this concentrated holds far more sugar than any yeast can convert, so the ferment stalls of its own accord, sometimes after months. Producers may then chill, sulphur or filter the wine to be sure it stays stopped."),
    Q("Sauternes and Barsac",
      "Noble rot fails to arrive at all in a cold wet autumn. What does a Sauternes estate typically do with that crop?",
      ["Bottle it as a dry white under a broader Bordeaux appellation",
       "Fortify it with grape spirit and sell it as a vin doux naturel",
       "Release it as Sauternes at a reduced price",
       "Freeze the fruit and make an ice wine from it"], 0,
      "Several leading estates keep a long-standing dry label for exactly this. Chateau d'Yquem declared no vintage at all in 1972, 1974 and 1992, which tells you how seriously the decision is taken."),

    # ------------------------------------------------------------ Tokaji (6) -
    Q("Tokaji",
      "Two rivers converge at the foot of the Zemplen hills and fog the slopes above them almost every autumn. Which pair?",
      ["The Bodrog and the Tisza", "The Danube and the Drava",
       "The Vah and the Hron", "The Mures and the Somes"], 0,
      "The Bodrog meets the Tisza at Tokaj itself. Damp air rising off the confluence into warm, sheltered volcanic slopes gives one of the most dependable noble rot climates in Europe."),
    Q("Tokaji",
      "High acidity, thin skins and a readiness to rot nobly make one variety the mainstay of the Tokaj vineyard. Which?",
      ["Furmint", "Harslevelu", "Sarga Muskotaly", "Kabar"], 0,
      "Furmint holds most of the plantings and gives the acid spine that lets these wines carry enormous sugar without collapsing. Harslevelu adds perfume and body, and small amounts of the others are also permitted."),
    Q("Tokaji",
      "Shrivelled, nobly rotten berries are picked out one at a time and worked into a paste rather than pressed as whole fruit. What are those berries called?",
      ["Aszu", "Szamorodni", "Forditas", "Maslas"], 0,
      "Aszu berries are collected in small hods and kneaded into a dough, which is then steeped in base wine or must. Forditas and maslas are the lesser wines made afterwards from the spent paste and its lees."),
    Q("Tokaji",
      "A number once printed on every Tokaji Aszu label recorded how many hods of that paste went into a barrel of base wine. What was the unit called?",
      ["Puttonyos", "Gonci", "Hordo", "Kadar"], 0,
      "A puttony is the hod itself, holding roughly twenty-five kilos, and the gonci is the 136-litre barrel it was tipped into. More hods meant more sugar, so the count worked as a sweetness scale."),
    Q("Tokaji",
      "Juice weeps out of a vat of shrivelled berries under nothing but their own weight, so sweet that it barely ferments at all. What is it called?",
      ["Eszencia", "Aszu", "Szamorodni", "Forditas"], 0,
      "Eszencia must carry at least 450 grams of sugar per litre to use the name, and most run well past 500, taking years to reach two or three per cent alcohol. It is spooned rather than poured, and is usually blended into Aszu rather than bottled on its own."),
    Q("Tokaji",
      "Whole bunches are picked without separating out the rotten berries, so the sweetness of the wine depends entirely on what the year delivered. Which Tokaji style is that?",
      ["Szamorodni", "Aszu", "Eszencia", "Maslas"], 0,
      "The name is Polish for as it was born. A rot-rich year gives a sweet edes szamorodni; a poor one gives a dry szaraz version, traditionally aged under a film of yeast in a partly filled barrel."),

    # ---------------------------------------------- Germany and Austria (7) --
    Q("Germany and Austria",
      "Ranked by the sugar in the juice at picking, in what order do the German Pradikat levels run?",
      ["Kabinett, Spatlese, Auslese, Beerenauslese, Trockenbeerenauslese",
       "Spatlese, Kabinett, Auslese, Trockenbeerenauslese, Beerenauslese",
       "Kabinett, Auslese, Spatlese, Beerenauslese, Trockenbeerenauslese",
       "Auslese, Kabinett, Spatlese, Trockenbeerenauslese, Beerenauslese"], 0,
      "Every step up is a higher minimum must weight in the juice, and from Auslese upward the law also asks for selection in the vineyard, berry by berry at Beerenauslese and Trockenbeerenauslese. Eiswein sits alongside Beerenauslese on must weight, though it reaches that figure by freezing rather than by rot."),
    Q("Germany and Austria",
      "A German label reads Trockenbeerenauslese. What does that word actually describe?",
      ["Dried-out berries selected individually from the bunch",
       "A dry-tasting wine made from selected bunches",
       "Berries dried on straw mats after picking",
       "Grapes harvested during a spell of dry weather"], 0,
      "Trocken here refers to the raisined state of the berry, not to the taste of the wine, which is among the sweetest made anywhere. Pickers work with tweezers, and a great vineyard may give a few hundred bottles."),
    Q("Germany and Austria",
      "A guest orders a Spatlese Trocken and is startled to be poured something bone dry. What does the Pradikat on that label actually record?",
      ["The sugar in the juice at harvest, not the sugar in the finished wine",
       "The residual sugar of the bottled wine",
       "The rank of the vineyard the fruit came from",
       "The minimum age of the vines"], 0,
      "Must weight and residual sugar are two different measurements. A ripe Spatlese picking can be fermented all the way out, giving a dry wine of real body from fruit that could equally have been left sweet."),
    Q("Germany and Austria",
      "Botrytis never appears in a warm dry German autumn, yet a Beerenauslese is still declared. How?",
      ["The berries raisined on the vine and reached the required must weight with no fungus at all",
       "Sussreserve was blended in to lift the sugar",
       "The fruit was frozen in the winery before pressing",
       "The must was concentrated by boiling"], 0,
      "The Pradikat is a sugar threshold, and shrivelling in dry heat is another way to cross it. Wines made this way taste pure and grapey where a botrytised version would be honeyed and savoury."),
    Q("Germany and Austria",
      "A large, very shallow steppe lake on the Hungarian border fogs the vineyards around it in most autumns. Which Austrian lake?",
      ["The Neusiedlersee", "The Attersee", "The Bodensee", "The Wolfgangsee"], 0,
      "Water barely a metre or two deep evaporates readily and blankets the flat land around Rust and Illmitz in mist. Botrytis is close to an annual event there, which is unusual anywhere in the world."),
    Q("Germany and Austria",
      "Between Beerenauslese and Trockenbeerenauslese, Austria's ladder holds a rung that Germany's does not. What is it called?",
      ["Ausbruch", "Strohwein", "Smaragd", "Eiswein"], 0,
      "Ausbruch is the speciality of Rust on the Neusiedlersee, traditionally made by pouring fresh must or wine over botrytised berries to draw their sugar out. Smaragd is a Wachau ripeness term rather than a legal Pradikat."),
    Q("Germany and Austria",
      "Reed mats or straw hold the bunches for at least three months of drying under an Austrian Pradikat of its own. Which one?",
      ["Strohwein", "Ausbruch", "Eiswein", "Bergwein"], 0,
      "Strohwein and its synonym Schilfwein cover the same practice, reed being the local alternative to straw around the Neusiedlersee. Bergwein is not a ripeness level at all but a designation for fruit off steep slopes."),

    # ---------------------------------------------- Eiswein and Icewine (6) --
    Q("Eiswein and Icewine",
      "Frozen grapes go into the press solid and only a trickle of syrup runs out. What is left behind in the press?",
      ["Ice crystals of water, holding back most of the berry's volume",
       "Crystals of frozen sugar, which are discarded",
       "Frozen alcohol, which would otherwise dilute the wine",
       "Frozen acid, leaving a softer juice"], 0,
      "Water freezes at a higher temperature than a sugar solution, so the pure water in the berry turns to ice while the sugary syrup stays liquid. Pressing hard against that ice is the whole trick."),
    Q("Eiswein and Icewine",
      "Eiswein grapes in Germany must go into the press still frozen. Which temperature is the accepted threshold for picking?",
      ["Minus seven degrees Celsius", "Minus two degrees Celsius",
       "Minus fifteen degrees Celsius", "Zero degrees Celsius"], 0,
      "German law asks only that the fruit be frozen at harvest and at pressing; minus seven is the working threshold, cold enough to hold back most of the water as ice and lift the must to Beerenauslese weight. Canada writes its own figure into the VQA rules, one degree lower still at minus eight."),
    Q("Eiswein and Icewine",
      "Freshly picked healthy grapes are put in a freezer overnight and pressed the next morning. Why can the result not be sold as Eiswein?",
      ["The freeze has to happen naturally, with the fruit still hanging on the vine",
       "The temperature reached was too low for the style",
       "Eiswein must show botrytis character",
       "Eiswein may only be made from Riesling"], 0,
      "Artificial freezing is called cryoextraction and is legal in some regions as a way of rescuing a rain-diluted harvest, but it forfeits the name. The risk that the freeze never comes is the point of the wine."),
    Q("Eiswein and Icewine",
      "Grapes hang unpicked into December while the grower waits for a hard frost. What can go wrong in the meantime?",
      ["Birds, wind and rot can take the crop before the temperature ever falls far enough",
       "The berries pass their sugar back into the vine",
       "The acidity falls away to nothing",
       "The vine itself is usually killed"], 0,
      "Nets go over the rows and the wait can run past New Year. A mild winter means no harvest at all, which is why the wines cost what they do and why some years simply produce none."),
    Q("Eiswein and Icewine",
      "Set beside a botrytised wine of the same sweetness, an ice wine tastes strikingly different. What marks it out?",
      ["Pure primary fruit and searing acidity, with none of the honeyed or savoury notes of rot",
       "Much lower acidity and a heavier texture",
       "Noticeable tannin from extended skin contact",
       "A distinctly oxidative, nutty character"], 0,
      "Nothing has grown on the fruit, so the wine tastes of the grape it came from: green apple, pear and citrus from Riesling, tropical fruit from Vidal. Concentration without transformation is the whole idea."),
    Q("Eiswein and Icewine",
      "A thick-skinned French-American hybrid holds onto its bunches through a Canadian winter better than any vinifera. Which variety?",
      ["Vidal", "Seyval Blanc", "Baco Noir", "Marechal Foch"], 0,
      "Vidal's tough skin resists splitting and its bunches stay attached long after Riesling would have dropped its fruit. It gives the mango and pineapple style most Canadian icewine drinkers know."),

    # -------------------------------------- dried-grape wines of Italy (6) ---
    Q("Dried-grape wines of Italy",
      "Bunches are laid out in an airy loft for three or four months after harvest and lose a third of their weight. What is that Italian practice called?",
      ["Appassimento", "Governo", "Ripasso", "Saignee"], 0,
      "The dried fruit is pressed in the depths of winter, giving a must so concentrated that fermentation is slow and stubborn. Governo and ripasso both add something back to a finished wine, and saignee bleeds juice off red skins."),
    Q("Dried-grape wines of Italy",
      "A sweet red from the hills north of Verona comes from grapes dried until midwinter, with the fermentation halted while sugar remains. Which wine?",
      ["Recioto della Valpolicella", "Amarone della Valpolicella",
       "Valpolicella Ripasso", "Bardolino Superiore"], 0,
      "Recioto is the older of the two great dried-grape wines of the zone, and Amarone began as a barrel of it that was allowed to ferment right out. Amaro means bitter, which is how the dry version struck those who first tasted it."),
    Q("Dried-grape wines of Italy",
      "Dried Garganega makes a sweet golden white in the hills east of Verona. Which wine is it?",
      ["Recioto di Soave", "Torcolato", "Soave Superiore", "Sciacchetra"], 0,
      "Same grape and same hills as dry Soave, with the bunches dried right through the winter first. Torcolato is Breganze's dried-grape sweet white from Vespaiola, and Sciacchetra comes from the Cinque Terre."),
    Q("Dried-grape wines of Italy",
      "Bunches hang from rafters through the winter, and the wine then spends years in small sealed barrels left deliberately part-empty. Which Tuscan speciality?",
      ["Vin Santo", "Passito di Pantelleria", "Sciacchetra", "Sagrantino Passito"], 0,
      "The barrels, called caratelli, are sealed and stored in a loft, so the wine swings through summer heat and winter cold for three years or more. That cycling gives the nutty, caramel, dried-fig character."),
    Q("Dried-grape wines of Italy",
      "Each caratello for Vin Santo is charged with a residue held back from the previous batch. What is that starter called?",
      ["The madre", "The solera", "The flor", "The governo"], 0,
      "The madre is a sludge of yeast and lees carried from barrel to barrel across generations, and it is what gets a fermentation moving in a must too sweet for ordinary yeast. Every cellar's madre is its own."),
    Q("Dried-grape wines of Italy",
      "On a windy volcanic island between Sicily and Tunisia, Zibibbo grapes are dried in the sun for a deep amber sweet wine. Which grape is Zibibbo?",
      ["Muscat of Alexandria", "Muscat Blanc a Petits Grains", "Malvasia Bianca", "Grillo"], 0,
      "Pantelleria trains its vines in hollows scooped out of the ground to shelter them from the wind, and the fruit is dried on open racks. Muscat of Alexandria is the coarser of the two great Muscats, but on this island it is magnificent."),

    # --------------------------------------------- drying beyond Italy (6) ---
    Q("Drying beyond Italy",
      "In the Jura and the northern Rhone, bunches are dried on mats or hung in ventilated lofts before a very slow winter pressing. What is the wine called?",
      ["Vin de paille", "Vin jaune", "Macvin du Jura", "Cremant du Jura"], 0,
      "Paille is straw, and the mats gave the style its name even where the fruit now hangs in crates. Vin jaune is dry and aged under a film of yeast, and macvin is grape juice fortified before it ever ferments."),
    Q("Drying beyond Italy",
      "Sun-dried Xynisteri and Mavro from a group of hill villages make a wine Cyprus has been exporting since the crusades. Which wine?",
      ["Commandaria", "Retsina", "Mavrodaphne", "Samos Muscat"], 0,
      "The name comes from the Grande Commanderie, the Knights Hospitaller estate that organised the trade. The grapes are laid out in the sun after picking and the wine is then aged oxidatively."),
    Q("Drying beyond Italy",
      "Assyrtiko is left in the sun for a fortnight after picking to make a sweet, tarry, deep amber wine. Which Greek island?",
      ["Santorini", "Crete", "Samos", "Lemnos"], 0,
      "Vinsanto from Santorini is a separate thing from Tuscan Vin Santo, and the shared name has several competing explanations. Assyrtiko keeps ferocious acidity even at three hundred grams of sugar."),
    Q("Drying beyond Italy",
      "Berries left hanging on the vine simply shrivel in dry autumn air, with no fungus involved at all. What is that called in French?",
      ["Passerillage", "Pourriture noble", "Mutage", "Debourbage"], 0,
      "Passerillage concentrates sugar exactly as noble rot does, but the flavours stay purer and more apricot-like without the honeyed, savoury layer the fungus adds. Pourriture noble is the French name for noble rot itself."),
    Q("Drying beyond Italy",
      "A Cape wine made from Muscat raisined on the vine was among the most prized bottles in Europe two centuries ago. Which wine?",
      ["Constantia", "Madeira Malmsey", "Tokaji Aszu", "Marsala"], 0,
      "Muscat Blanc a Petits Grains grown below the mountains behind Cape Town, unfortified, and revived in the 1980s after a century out of production. Jane Austen, Dickens and Napoleon's household all have a place in its story."),
    Q("Drying beyond Italy",
      "Grapes are laid out on mats in the Andalusian sun until they are close to raisins, then pressed for an almost black, treacly wine. Which variety?",
      ["Pedro Ximenez", "Palomino", "Zalema", "Airen"], 0,
      "The sun-drying is called the soleo, and it lifts the must to sugar levels no yeast could ever work through. The wine is fortified early and can pour like oil at over four hundred grams of sugar per litre."),

    # ----------------------------------------- fortification by arrest (6) ---
    Q("Fortification by arrest",
      "Neutral grape spirit goes in partway through fermentation, killing the yeast and leaving the grape's own sugar in the wine. What is that family of French wines called?",
      ["Vin doux naturel", "Vin de liqueur", "Vin gris", "Vin de paille"], 0,
      "Naturel refers to the sugar, which was never added, rather than to the spirit. Vin de liqueur is the other fortified family, where the spirit goes in before fermentation has begun at all."),
    Q("Fortification by arrest",
      "The addition of spirit to stop a fermentation has a name of its own in French cellars. What is it?",
      ["Mutage", "Remuage", "Soutirage", "Collage"], 0,
      "Mutage is the act, and the wine is then said to be muted. Remuage is riddling, soutirage is racking and collage is fining, all quite separate operations."),
    Q("Fortification by arrest",
      "A honeyed, orange-blossom-scented fortified sweet white comes from a village beneath the Dentelles de Montmirail. Which appellation?",
      ["Muscat de Beaumes-de-Venise", "Rasteau", "Banyuls", "Maury"], 0,
      "Muscat Blanc a Petits Grains grown in the southern Rhone and muted at around fifteen per cent alcohol. Rasteau, Banyuls and Maury are the Grenache-based vins doux naturels, and are mostly red."),
    Q("Fortification by arrest",
      "Some Roussillon fortified wines are deliberately left in glass demijohns out of doors, through summer heat and winter cold. What does that develop?",
      ["A rancio character of walnut, coffee and dried fig",
       "A veil of yeast giving almond and fresh dough notes",
       "A pronounced petrol note",
       "A bright, primary red-fruit character"], 0,
      "Heat and oxygen together take the wine somewhere no cool reductive cellar could. Rancio is prized rather than avoided here, and the same word describes the character of very old Australian fortifieds."),
    Q("Fortification by arrest",
      "In a hot corner of north-east Victoria, Muscat raisins on the vine, is muted with spirit, then ages for decades in old barrels under tin roofs. Which region?",
      ["Rutherglen", "Coonawarra", "Barossa Valley", "Hunter Valley"], 0,
      "Summer heat in the sheds drives both concentration and oxidation, and a blending system on solera lines keeps very old material in every bottle. The grape is the red-berried form of Muscat Blanc a Petits Grains, known locally as Brown Muscat."),
    Q("Fortification by arrest",
      "Four tiers of rising age and richness are used for Rutherglen Muscat. Which sits at the top?",
      ["Rare", "Grand", "Classic", "Reserve"], 0,
      "Rutherglen Muscat, then Classic, then Grand, then Rare, each a step up in concentration. The ladder is set and policed by the local producers rather than by wine law, with each tier carrying its own band of average age, from three to five years at the base to twenty years or more for Rare."),
]
