"""Rank I rewrite - Food & Pairing (54 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing.

The running order is built around one idea: a beginner does not need a theory of
taste, they need to decide what to pour at a table tonight. So the order follows
the plate rather than the textbook. Weight comes first because it settles more
bad pairings than anything else, then the four things a dish can throw at a wine
in the order a kitchen actually throws them - fat, salt and smoke, sugar,
protein - then heat and green bitterness, then the marriages that have outlived
every fashion, the handful of foods that defeat wine, and finally the shape of a
meal from the first glass to the last.

The Rank II Food & Pairing category owns the chemistry: why tannin binds with
protein, what cynarin does to a sweet receptor, which interaction explains a
classic. This one stops at the rule and the recommendation. Where Rank II asks
what is happening, this asks what to pour, and several dishes appear here whose
mechanism is deliberately left to the category above.

Regional categories already own their own tables - Muscadet with oysters,
choucroute in Alsace, Crottin in Sancerre - so those pairings are named here only
as distractors, never as tasks.

Every stem opener is distinct, the constructions in lib.BANNED_TEMPLATES are
avoided by design, and where the answer is a dish rather than a wine the stem
leads with the glass instead, so the subject always arrives as the answer.
"""

from lib import Q

CAT = "Food & Pairing"
SLUG = "r1-food-pairing"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Weight, intensity and the two strategies", 6),
    ("Fat, richness and the fryer", 5),
    ("Salt, smoke and cured food", 4),
    ("Sugar on the plate", 5),
    ("Protein, tannin and the red meat reflex", 5),
    ("Heat, spice and pepper", 5),
    ("Green things and the bitter edge", 5),
    ("Classics that have survived", 8),
    ("The standard traps", 7),
    ("From aperitif to the last course", 4),
]

BANK = [
    # ------------------------ weight, intensity and the two strategies (6) --
    Q("Weight, intensity and the two strategies",
      "Poached prawns with lemon open the meal and a slow-braised beef shin follows it. Which pair of pours matches each course for weight?",
      ["A light unoaked white with the prawns, a full-bodied red with the beef",
       "A full-bodied oaked red with the prawns, a light unoaked white with the beef",
       "The same sweet fortified wine with both courses",
       "The same young tannic red with both courses"], 0,
      "Weight is the crudest measure of a dish and the one worth settling before anything is argued about flavour: the prawns vanish under anything heavy and the braise makes a delicate white taste of water. Get the volume right and a mediocre flavour match still drinks well, while getting it wrong cannot be rescued by cleverness later."),
    Q("Weight, intensity and the two strategies",
      "A fifteen percent oaked red is poured beside a plate of steamed sole. What is the guest most likely to notice?",
      ["The fish tastes of almost nothing",
       "The wine tastes thin and sour, its fruit stripped out",
       "Both taste much as they did on their own",
       "The fish tastes markedly saltier than before"], 0,
      "An overpowering wine does not improve a delicate dish, it erases it, and the guest usually blames the kitchen rather than the pour. Thin and sour is what happens in the opposite mismatch, when a light white is sent out against a braise."),
    Q("Weight, intensity and the two strategies",
      "Raw fish dressed with lime, ginger and coriander is feather-light on the plate and very loud in flavour. What does that combination ask of the wine?",
      ["Pronounced aroma and flavour carried at a light body",
       "A heavy, high-alcohol wine to match the volume",
       "Firm tannin and a long spell in new oak",
       "Enough sweetness to coat the palate"], 0,
      "Weight and intensity are separate axes, and a dish can be extreme on one while modest on the other. An aromatic white at twelve percent carries plenty of flavour without the mass that would flatten raw fish, which is exactly the combination this plate is asking for."),
    Q("Weight, intensity and the two strategies",
      "A cod fillet arrives blanketed in a butter and cream sauce. Which white is the sounder call?",
      ["A white with body and a ripe, rounded texture",
       "A thin, neutral white at eleven percent, served very cold",
       "A sweet late-harvest white",
       "An intensely aromatic off-dry white"], 0,
      "Cream and butter add weight the fish alone does not have, so a wine that suited the plain poached version now tastes watery beside it. Sweetness is the wrong axis entirely here, and a loudly aromatic wine argues with the sauce instead of supporting it."),
    Q("Weight, intensity and the two strategies",
      "A server has thirty seconds to judge how heavy an unfamiliar wine will feel in the mouth. Which figure on the label is the most useful clue?",
      ["The stated alcohol",
       "The harvest year",
       "The volume of the bottle",
       "The number of varieties in the blend"], 0,
      "Alcohol adds viscosity and warmth of its own, and it also stands in for ripeness, so a wine at fourteen and a half will almost always feel fuller than one at eleven. Sugar and oak add weight too, which makes it a guide rather than a rule, but it is the fastest guide a label offers."),
    Q("Weight, intensity and the two strategies",
      "Echoing a quality the dish already carries and supplying one it lacks are the two oldest strategies in pairing. A very sweet wine is set beside a salty blue cheese: which strategy is that, and why?",
      ["It supplies what the plate lacks, since nothing in the cheese is sweet",
       "It echoes the plate, since the cheese is as sweet as the wine",
       "It echoes the plate, since the wine is as salty as the cheese",
       "It supplies what the plate lacks, since the wine is the drier of the two"], 0,
      "Echoing means the same quality turns up on both sides of the table, so the glass repeats something the cook has already put on the plate. The other strategy works the opposite way round, with the wine bringing a quality the dish has none of at all, which is why sugar registers so loudly against salt. Naming which of the two a pairing rests on is the quickest way to explain it to a guest."),

    # ------------------------------------- fat, richness and the fryer (5) --
    Q("Fat, richness and the fryer",
      "A basket of whitebait comes out of the fryer, hot and glistening with oil. Which pour keeps the palate fresh to the last one?",
      ["A bone-dry sparkling wine",
       "A warm, high-alcohol red",
       "A sweet fortified wine",
       "A soft, heavily oaked white with very little acidity"], 0,
      "Anything straight out of the fryer wants the glass cold, dry and lively. The heavy red piles weight on weight, the sweet wine turns the whole plate cloying, and the soft oaked white brings nothing to reset the palate with, so the same answer covers tempura, fried chicken and fish and chips."),
    Q("Fat, richness and the fryer",
      "Duck rillettes and a coarse pork terrine are set out with cornichons and mustard. Which red is the easier partner?",
      ["A light, high-acid red served slightly cool",
       "A heavily oaked red at fifteen percent",
       "An old and delicate red at the peak of its life",
       "A sweet red made from grapes dried on straw mats"], 0,
      "Fat and salt want freshness set against them rather than more weight, and a light chill sharpens a simple red further. The old bottle is the real trap on a list like this: a coarse terrine with mustard beside it tramples a wine whose whole appeal is subtlety."),
    Q("Fat, richness and the fryer",
      "A smooth chicken liver parfait is spread thickly on toast, unctuous and faintly metallic. Which glass is the traditional foil?",
      ["A gently sweet white",
       "A young, firmly tannic red",
       "A neutral dry white with low acidity",
       "A high-alcohol dry rose"], 0,
      "Sweetness meets the richness instead of fighting it, while the acid underneath stops the pairing turning heavy after two mouthfuls. Tannin against liver tends to read metallic, and the neutral white simply disappears under the fat."),
    Q("Fat, richness and the fryer",
      "Roast pork with crackling arrives with a spoonful of apple sauce on the side. Which pour handles the fat and the sweet sauce at once?",
      ["An off-dry white",
       "A tannic red",
       "A very sweet dessert wine",
       "A soft, low-acid white with no sugar"], 0,
      "The apple sauce is the complication rather than the pork: a bone-dry wine tastes stripped beside it, so a little sugar in the glass keeps the wine's own fruit intact while the acidity deals with the crackling. A dessert wine overshoots so far that the meat stops registering at all."),
    Q("Fat, richness and the fryer",
      "Fried chicken is ordered at the bar and the guest wants red rather than white. Which suggestion does the least damage?",
      ["A juicy, low-tannin red served cool",
       "A young red with firm, drying tannin",
       "A heavily oaked red at fifteen percent",
       "A sweet red dessert wine"], 0,
      "A stated preference is worth working with rather than around, and a red can be made to fit here by choosing one that behaves like a white: cool, fruity and light on grip. Tannin and oak are what turn fried food harsh in the mouth, so the recommendation is really about avoiding those two."),

    # -------------------------------------- salt, smoke and cured food (4) --
    Q("Salt, smoke and cured food",
      "Hot-smoked salmon, oily and heavy with smoke, opens the meal. Which white is the safer choice?",
      ["An unoaked white with firm acidity",
       "A richly oaked, buttery white",
       "A sweet botrytised white",
       "A warm, high-alcohol white at fifteen percent"], 0,
      "Two lots of smoke do not cancel each other, they accumulate, so a barrel-heavy wine beside smoked fish tastes acrid within a couple of mouthfuls. Keeping the wine clean and sharp leaves the smoke where the cook put it, and gives the oil in the fish something to be cut by."),
    Q("Salt, smoke and cured food",
      "Ribs come out of the smoker lacquered in a sweet, sticky sauce. Which red suits them?",
      ["A ripe, fruit-forward red with soft tannin",
       "A lean, austere red with searing acidity",
       "A pale, delicate red at twelve percent",
       "A tannic red from a cool climate, aged in new oak"], 0,
      "A sauce with sugar in it needs a wine whose fruit reads sweet, or the wine turns hard and sour beside it. Lean and austere is exactly the wrong direction here, and firm tannin against smoke and char comes across as bitter rather than as structure."),
    Q("Salt, smoke and cured food",
      "Of the snacks a bar can put in front of a guest holding a glass of wine, which is the most obliging?",
      ["Salted almonds",
       "Pickled onions in vinegar",
       "Chocolate truffles",
       "A wedge of ripe pineapple"], 0,
      "Salt is the friendliest thing you can set beside a glass: it makes fruit read more clearly and takes the edge off whatever bitterness the wine carries. The other three each fight the glass in their own way, which is why a bowl of nuts or olives is the standing default in every wine bar in the world."),
    Q("Salt, smoke and cured food",
      "Green olives and a glass of red are ordered together and the wine turns unpleasantly metallic. What is the usual fix?",
      ["Pour a dry white instead",
       "Serve the same red much warmer",
       "Decant the red for an hour to soften it",
       "Add a little ice to the red"], 0,
      "Brine and tannin are a poor combination, and no amount of handling the same bottle repairs it, because the problem is the match rather than the condition of the wine. Olives sit far more happily with something dry, sharp and unoaked, which is why they belong beside a fino or a manzanilla as naturally as they do beside a cold glass of white."),

    # ---------------------------------------------- sugar on the plate (5) --
    Q("Sugar on the plate",
      "The kitchen sends out a slice of tarte Tatin, caramelised and very sweet. Which of these bottles will taste sour beside it?",
      ["A brut sparkling wine",
       "A late-harvest Muscat",
       "A botrytised sweet white",
       "A tawny Port"], 0,
      "Sweetness is judged against whatever came immediately before it, so a dry wine tasted after a caramelised pudding loses its fruit and shows only acid and alcohol. The other three all carry enough sugar of their own to hold their ground, which is the whole reason dessert wines exist."),
    Q("Sugar on the plate",
      "One first course on tonight's menu will strip the fruit out of a bone-dry white and leave it tasting sharp and hollow. Which is it?",
      ["Ripe melon wrapped in prosciutto",
       "Grilled sardines with lemon",
       "Steak tartare with capers",
       "A dozen oysters on ice"], 0,
      "Very ripe melon is sweet enough to out-sweeten a dry wine, and the ham beside it does not change that. The other three are salty, savoury or saline, and every one of those flatters a dry white rather than fighting it."),
    Q("Sugar on the plate",
      "Sweet-and-sour pork, glazed teriyaki chicken and a mango salad all set the wine list the same problem. What is it?",
      ["Sugar in a savoury dish",
       "An unusually high level of salt",
       "Bitterness from charring",
       "Raw vinegar"], 0,
      "Sweetness on a savoury plate is easy to miss when reading a menu, and it changes the recommendation completely, because a dry wine beside it loses its fruit exactly as it would beside a pudding. A wine with a trace of sugar of its own, or a red with very ripe fruit, keeps its shape."),
    Q("Sugar on the plate",
      "Ice cream is on the dessert list and the sommelier hesitates before pouring anything with it. What is the difficulty?",
      ["The cold numbs the palate to the wine",
       "Its acidity outruns any sweet wine",
       "It contains no sugar to speak of",
       "Its fat binds with tannin"], 0,
      "A very cold spoonful shuts the palate down for a moment, so whatever follows registers faintly and an expensive glass is wasted. Pouring alongside rather than after, and choosing something intensely flavoured, are the two usual ways around it."),
    Q("Sugar on the plate",
      "Strawberries and cream close a long summer lunch. Which pour is the safest?",
      ["A gently sweet sparkling wine",
       "A sweet, nutty fortified white at eighteen percent",
       "A dry tannic red",
       "An oaked dry white"], 0,
      "Fruit at the end of a meal reads sweet, so the glass has to bring at least as much sugar or it turns tart in the mouth. Sugar on its own is not the whole answer, though, because the wine also has to stay light and fresh: a warming, nutty style buries fruit this delicate whatever its sweetness. Demi-sec sparkling wine and Moscato d'Asti both do the job at very different prices."),

    # ------------------------- protein, tannin and the red meat reflex (5) --
    Q("Protein, tannin and the red meat reflex",
      "A young, firmly tannic red is showing hard and drying on its own before dinner. Which plate would flatter it most?",
      ["A rare rib of beef",
       "A bowl of miso soup",
       "A goat cheese salad",
       "A lemon sorbet"], 0,
      "Protein and fat take the edge off astringency, which is why a red that seems punishing on its own settles down beside red meat. The other three give the tannin nothing to work against, so it stays exactly as hard as it was and the wine gets the blame."),
    Q("Protein, tannin and the red meat reflex",
      "A vegetarian guest asks for a red as substantial as the one their neighbour is drinking with steak. Which dish on the menu would carry it?",
      ["A rich bean and lentil stew",
       "A green salad dressed sharply with lemon and shallot",
       "Steamed asparagus with hollandaise",
       "A chilled tomato soup"], 0,
      "Weight, texture and a little fat are what a big red needs, and none of the three requires meat to supply them; pulses cooked long and slow in oil give all three. The other dishes are green, acidic or cold, and beside any of them the same wine reads as pure tannin."),
    Q("Protein, tannin and the red meat reflex",
      "Rare steak is ordered and the guest asks for white wine rather than red. Which white gives the dish the best chance?",
      ["A full-bodied white with oak and some grip",
       "A light, neutral white at eleven percent",
       "A sweet botrytised white",
       "An off-dry aromatic white"], 0,
      "White wine carries far too little tannin to meet the protein the way a red does, so the match has to be made on weight and texture instead, and a barrel-aged white has both, with a little grip of its own from the oak. Anything light or sweet is simply flattened by the meat, and the guest concludes that white with steak cannot be done."),
    Q("Protein, tannin and the red meat reflex",
      "The same bird goes out four ways on tonight's menu. Which preparation calls for the fullest wine?",
      ["Roasted with the skin crisped and a pan gravy",
       "Steamed with ginger and spring onion, served plain",
       "Served cold and sliced into a salad",
       "Poached in a light stock"], 0,
      "Browning, crisp skin and a pan gravy add a weight and a savoury depth that gentle cooking never produces, so the same ingredient can end up needing a light white or a substantial red. That is why the protein named on the menu is such an unreliable guide on its own."),
    Q("Protein, tannin and the red meat reflex",
      "Beef carpaccio arrives sliced thin under lemon, oil and rocket rather than grilled. What happens to the wine choice?",
      ["Much lighter and fresher",
       "Heavier, since raw meat needs more tannin",
       "Sweeter, to balance the bitterness of the rocket",
       "Unchanged, since the meat is the same"], 0,
      "Raw, sliced thin and dressed with citrus and peppery leaves, the dish has far more in common with a first-course salad than with a grilled steak. Tannin has almost nothing to bind to, and the acid in the dressing is now the loudest thing on the plate."),

    # ------------------------------------------- heat, spice and pepper (5) --
    Q("Heat, spice and pepper",
      "A fiery Sichuan dish reaches the table and four bottles are already open. Which one will make the burn worse?",
      ["A tannic red at fifteen percent",
       "An off-dry white at eight percent",
       "A dry sparkling wine served very cold",
       "A lightly sweet rose at eleven percent"], 0,
      "Alcohol and tannin both sharpen the sensation of heat, so the strongest and grippiest bottle on the table is the one to keep well away from the chilli. Cold, low in alcohol and faintly sweet is the direction that helps, and all three of the others sit somewhere along it."),
    Q("Heat, spice and pepper",
      "Ground black pepper crusts a steak thickly. Unlike chilli heat, what does this kind of spice allow?",
      ["A dry red with savoury, peppery aromatics of its own",
       "A very sweet wine, as with chilli",
       "A wine as low in alcohol as possible",
       "No wine at all, since pepper defeats every style"], 0,
      "The compound behind chilli sets off a genuine heat response that alcohol makes worse; the one behind black pepper is far milder and reads as an aroma as much as a burn. Peppery reds echo it happily, which is why a coarse-ground pepper crust is one of the easiest things on any menu to pour against."),
    Q("Heat, spice and pepper",
      "Coconut milk softens a hot curry, and the dish is now rich as well as fiery. What does the coconut change about the recommendation?",
      ["The wine now needs weight as well as sweetness",
       "The dish no longer needs any sweetness in the glass",
       "The dish is now best served with a dry oaked red",
       "The wine can be as tannic as you like"], 0,
      "Fat coats the palate and takes some of the sting out of chilli, but it also adds body, so a wispy low-alcohol white that would have suited a thin broth is now too slight for the bowl. Something with a little sugar and a little more substance holds both ends of the dish."),
    Q("Heat, spice and pepper",
      "The ice bucket comes out before the bottle has even been chosen, because the main course is fiercely hot. What is the chill doing for the guest?",
      ["Cooling the palate against the burn",
       "Lowering the wine's alcohol by a degree or so",
       "Removing the tannin from the wine",
       "Adding sweetness to the wine"], 0,
      "Temperature is the one lever a server still controls at the moment of service, and a well-chilled glass is a genuine relief beside chilli. Nothing in the bucket alters what is in the bottle, only how it is perceived, which is enough to rescue a difficult course."),
    Q("Heat, spice and pepper",
      "Wasabi, mustard and horseradish all sting, and yet they behave quite differently from chilli at the table. What is the practical difference?",
      ["Their heat fades in seconds rather than building",
       "They cannot be tasted alongside wine at all, at any strength",
       "They are far hotter than any chilli",
       "They make a wine taste sweeter"], 0,
      "The volatile compounds behind mustard heat clear quickly and travel up the nose rather than settling on the tongue, so they disrupt a wine far less than capsaicin does. A dish seasoned with them can take a drier and stronger wine than a chilli dish of the same apparent intensity."),

    # --------------------------------- green things and the bitter edge (5) --
    Q("Green things and the bitter edge",
      "Grilled radicchio and bitter chicory leaves are the side dish. Which glass is least likely to turn harsh?",
      ["A soft red with very little tannin",
       "A young red with drying, mouth-puckering tannin",
       "A heavily oaked white",
       "A dry red fortified wine"], 0,
      "Bitterness in the glass adds to bitterness on the plate instead of cancelling it, so tannin and heavy oak both make bitter leaves worse. A soft fruity red or a fresh unoaked white leaves the vegetable to speak for itself, which is what the cook intended."),
    Q("Green things and the bitter edge",
      "Peas, broad beans and a fistful of fresh herbs dominate a spring plate. Which white shares that green character rather than fighting it?",
      ["A herbaceous, unoaked Sauvignon Blanc",
       "A rich Chardonnay matured in new oak barrels",
       "An oxidative, nutty dry white",
       "A sweet Muscat"], 0,
      "This is one of the few places where an obviously green, grassy wine is an advantage rather than a liability, because the same character is already on the plate. A big oaked white buries the vegetables and a sweet one turns the whole dish into something else."),
    Q("Green things and the bitter edge",
      "A deep, savoury mushroom and Parmesan risotto is going out. Which red is the safer recommendation?",
      ["A mature, gentle red",
       "A young red at the height of its grip",
       "A tannic red aged in new oak",
       "A sweet fortified red"], 0,
      "Savoury depth of this kind makes firm tannin read harder and drier than it really is, so age and gentleness matter far more than power. A red past its youth has already shed most of the grip that would clash, which is one of the few genuine arguments for opening an older bottle with a vegetarian dish."),
    Q("Green things and the bitter edge",
      "Aubergine, courgette and peppers are stewed down in olive oil and served warm. Which is the natural pour?",
      ["A dry rose or a light red served cool",
       "A powerful red at fifteen percent, aged in oak",
       "A sweet late-harvest wine",
       "A heavily oaked white"], 0,
      "Olive oil and long, slow cooking give these vegetables a weight no salad has, and nothing like the depth a meat dish brings. The plate therefore sits in the gap between white-wine and red-wine territory rather than squarely in either. Rose and a lightly chilled red both live in that gap, which is much of why they suit a Mediterranean table."),
    Q("Green things and the bitter edge",
      "Before a single bottle is opened, which of these vegetable dishes is already the friendliest to wine?",
      ["Roasted root vegetables",
       "Raw asparagus spears with a lemon dressing",
       "A bowl of raw fennel and celery",
       "A raw onion and tomato salad"], 0,
      "Heat, browning and concentrated sugar move a vegetable towards the wine; raw, green and pungent moves it away. The distinction is worth more to a beginner than any list of grape varieties, because it explains why the same vegetable can be easy company one night and impossible the next."),

    # ------------------------------------- classics that have survived (8) --
    Q("Classics that have survived",
      "Six oysters, shucked and set on ice with nothing but a wedge of lemon. Which of these bottles is the classic pour?",
      ["Chablis",
       "Meursault",
       "A ripe New World Chardonnay",
       "An oaked white Rioja"], 0,
      "All four are made from grapes that can give a broad, rich wine, and the one that works is the one usually left alone in steel: little or no oak, no sweetness, high acid, and a saline edge that reads as an extension of the oyster. The grand cru bottles do see some barrel, but the everyday Chablis that goes with oysters does not, and oak with shellfish is one of the reliably bad combinations in the whole subject."),
    Q("Classics that have survived",
      "A whole side of salmon is grilled over coals and the table asks for red. Which grape is the standard answer?",
      ["Pinot Noir",
       "Cabernet Sauvignon",
       "Nebbiolo",
       "Tannat"], 0,
      "A red with low tannin and bright acidity behaves much like a white against fish, and salmon has enough oil and flesh to carry it. The big, structured reds are the ones usually blamed for the tinny taste fish is famous for causing, which is reason enough to keep them back for the meat course."),
    Q("Classics that have survived",
      "A stew has spent the afternoon cooking with the best part of a bottle of red wine in it. Which pour is the safest?",
      ["A wine of the same style as the one in the pot",
       "A sweet white, for contrast with the savoury stew",
       "A dry sparkling wine, to lift the richness",
       "A very old and delicate red, for its complexity"], 0,
      "Cooking with a wine and drinking it alongside is the oldest shortcut in pairing, and it works because the flavours in the pot are already the flavours in the glass. It is also the reason regional cooking and regional wine agree so often, since neither was developed with the other absent."),
    Q("Classics that have survived",
      "A plain roast chicken is famously the most accommodating dish on any menu. What makes it so?",
      ["It is moderate in weight, fat and flavour",
       "It has almost no flavour of its own to speak of",
       "It carries a great deal of salt in the skin",
       "It is unusually high in acid"], 0,
      "Nothing about it is extreme, so it sits comfortably beside a white or a red and rarely embarrasses either. It is the dish to reach for when a table cannot agree, and the reason so many producers name it when asked what to drink with their own wine."),
    Q("Classics that have survived",
      "Roast leg of lamb, studded with garlic and rosemary, is carved at the table. Which of these bottles is the enduring answer?",
      ["A red Bordeaux",
       "An oaked white Rioja",
       "A Mosel Kabinett",
       "A dry Marsala"], 0,
      "The fat and protein in the lamb soften Cabernet and Merlot tannin, and the cedary, herbal edge of a claret runs alongside the rosemary rather than across it. The pairing is old enough that Cabernet-based reds appear beside lamb on menus in countries that grow neither."),
    Q("Classics that have survived",
      "The old rule pairs white with fish and red with meat. Which dish shows it up most clearly?",
      ["Grilled tuna, seared rare",
       "Poached turbot in a light stock",
       "Raw scallops dressed with lime",
       "Steamed sea bass with lemon"], 0,
      "Tuna is dense, meaty and best served pink, and a light red handles it better than most whites do. The other three are exactly the dishes the old rule was written for, and it serves them perfectly well, which is why it survives as a starting point rather than as a law."),
    Q("Classics that have survived",
      "The same regional wine keeps turning up beside the same regional dish, century after century. What is the soundest explanation?",
      ["The two grew up together",
       "The dish is always cooked with that wine",
       "The wine is cheaper in its own region than anywhere else",
       "Regional law requires the combination"], 0,
      "Cooks and growers in the same place spent centuries correcting one another, and what survived is a pairing that works rather than a rule anyone sat down and wrote. It is why what grows together goes together is a better first guess than any chart, and why a regional menu is the easiest place to start."),
    Q("Classics that have survived",
      "A holiday table carries a mild roast bird surrounded by sweet, salty and sharp accompaniments. Which pour is the most forgiving?",
      ["A fruity, low-tannin red or a full rose",
       "The most tannic red on the list",
       "A bone-dry, austere white",
       "A very sweet dessert wine"], 0,
      "The bird is mild but the table is crowded, so the wine has to be forgiving rather than impressive, and low tannin with generous fruit collides with the fewest things on the plate. Cranberry sauce on its own is enough to strip a dry tannic red of everything it had."),

    # ------------------------------------------- the standard traps (7) --
    Q("The standard traps",
      "Nothing about the bottle has changed, yet the sip taken after the starter tastes oddly and distinctly sweet. Which vegetable did the guest just eat?",
      ["Globe artichoke",
       "Roasted red pepper",
       "Cucumber",
       "Fennel"], 0,
      "The effect is strong enough that this vegetable has a reputation as unpairable, and it is why a kitchen cooking for a wine dinner tends to keep it off the menu altogether. Plenty of lemon and olive oil, or roasting it hard, softens the problem without removing it."),
    Q("The standard traps",
      "Which starter coats the palate so thoroughly that everything poured after it is muffled?",
      ["A soft-boiled egg with buttered soldiers",
       "A tomato and basil salad dressed with oil",
       "Grilled prawns with garlic, chilli and parsley",
       "A clear beef consomme"], 0,
      "A rich yolk leaves a film that blunts whatever follows, which is why egg dishes have an awkward reputation with wine and why brunch menus reach for something sharp and sparkling. Acidity and bubbles are the counter, and both of them work by clearing rather than by matching."),
    Q("The standard traps",
      "A first-course salad is being dressed for a menu built around wine. Which change gives the wine the best chance?",
      ["Use less vinegar, and more oil and lemon",
       "Use a stronger vinegar so it stands out",
       "Add sugar to the dressing",
       "Chill the salad harder"], 0,
      "Sharp vinegar flattens whatever is drunk after it, and no bottle on the list repairs a dressing that aggressive, so the fix belongs in the kitchen rather than the cellar. Citrus is gentler and oil buffers the acid, which is the cheapest adjustment available to anyone."),
    Q("The standard traps",
      "A very dark, bitter chocolate torte closes the meal. Which pour is the least suitable?",
      ["A dry, tannic red",
       "A sweet red made from dried grapes",
       "A rich, raisiny sweet Sherry",
       "A sweet red fortified wine"], 0,
      "Two failures arrive at once: the bitterness of the chocolate and the bitterness of the tannin pile up, and there is no sugar in a dry wine to meet the sugar in the pudding. Everything else here is sweet enough and soft enough to stand beside it."),
    Q("The standard traps",
      "A double espresso is drunk before the dessert wine is poured. What has that done to the wine?",
      ["Left a bitterness behind that flattens it",
       "Cleared the palate for the wine that follows",
       "Made the wine seem more tannic",
       "Nothing at all"], 0,
      "Strong coffee is bitter, hot and lingering, and all three get in the way of whatever is tasted next. The order is the fix rather than the wine: pour the sweet glass first and let the coffee close the meal."),
    Q("The standard traps",
      "A tinny, almost metallic taste comes up the moment a tannic red meets the fish course. Which fish was on the plate?",
      ["Grilled mackerel",
       "Poached turbot",
       "Grilled sole",
       "Steamed cod"], 0,
      "The oil in a fish of this kind reacting with the wine is the usual explanation, and the taste is unmistakable once it has been met. Lean white fish does not produce it at all, which shows the fault belongs to the oil rather than to fish in general."),
    Q("The standard traps",
      "Fresh pineapple and lime finish the meal, and the sweet wine beside them tastes thick and flat. What is the difficulty?",
      ["The fruit is sharper than the wine",
       "The fruit is far sweeter than the wine is",
       "The fruit is being served too warm to taste",
       "The fruit carries a tannin of its own"], 0,
      "A sweet wine needs acidity of its own to stand beside sharp fruit, or it reads heavy and dull the moment the two meet. It is the same reason the great dessert wines are prized for their acid quite as much as for their sugar."),

    # ----------------------------- from aperitif to the last course (4) --
    Q("From aperitif to the last course",
      "Guests arrive and want a glass before the menus have even been opened. Which style makes the best aperitif?",
      ["Dry, light and high in acid",
       "Sweet, rich and full-bodied",
       "Tannic and high in alcohol",
       "Heavily oaked and warming"], 0,
      "A first glass is there to sharpen the appetite rather than satisfy it, so anything sweet or heavy dulls the palate before the food has arrived. Dry sparkling wine, dry Sherry and a crisp unoaked white are all built for exactly this job."),
    Q("From aperitif to the last course",
      "Cheese comes before the pudding in France and after it in Britain. What does the French order make easier?",
      ["The red from the main course can carry on",
       "The cheese course still needs its own red either way",
       "No wine is served with cheese in either order",
       "The sweet wine has to be opened first"], 0,
      "Putting the cheese first lets one bottle serve two courses and keeps the sweet wine for the sweet course, where relative sweetness decides everything. It is a practical arrangement as much as a national habit, and it is worth knowing which order a kitchen follows before writing the pairings."),
    Q("From aperitif to the last course",
      "Thin, hot consomme opens the meal. What is the standard advice about wine with soup?",
      ["Pour little or nothing",
       "Pour the biggest red of the meal",
       "Pour the same wine as the main course",
       "Pour the sweetest wine of the meal"], 0,
      "Two liquids at once give the palate no contrast of texture, and a hot bowl blunts aroma besides. The traditional exception is a fortified wine such as a dry Sherry or a Sercial Madeira, which has the concentration to be noticed at all."),
    Q("From aperitif to the last course",
      "A sorbet lands between the fish course and the meat course. What is it doing, in wine terms?",
      ["Clearing the palate between two very different wines",
       "Replacing the need for a wine with the meat course",
       "Signalling the end of the white wines",
       "Adding sweetness to the next wine"], 0,
      "The point is that the wine following it is met fresh rather than through the last of the fish, which matters most when the two pours have nothing in common. Its own cold and sugar are the reason nothing worth tasting is poured alongside it."),
]
