"""Rank I rewrite - Grapes & Labels (50 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing.

One idea runs through the whole category: a grape and the name printed on the
bottle are two different things. The running order follows that thought. First
why a single vine collects a dozen names and how anybody now decides that two
names are one plant, then the red aliases and the white ones, then the names
that mislead because they merely look alike, then the two labelling traditions
set against each other - the label that names the grape and the label that names
the place - then how a mixture of grapes is declared, then the words buried
inside a variety's own name, and last three moments where a guest is waiting.

BOUNDARIES. Wine Law owns the varietal and vintage percentage minimums as legal
rules and no question here states one. Label Reading owns the producer, bottling
and mandatory-statement wording. The vine in the vineyard and the wine in the
glass belong to Viticulture & Winemaking and to Tasting & Service.

Several classic synonym sets are already the TASK of a committed category and
are deliberately absent rather than rewritten with different words: Mataro,
Mourvedre and Monastrell (Australia and Spain), Cannonau (Italy), Steen and
Pineau de la Loire (South Africa and Loire), the Carmenere and Merlot
identification (South America), Tinta Roriz and Cencibel (Portugal and Spain),
Blaufrankisch and Lemberger (Austria), Spatburgunder and Gutedel (Germany),
Fume Blanc and Petite Sirah (United States), Viura and Macabeo (Spain), Morillon
(Austria), Melon de Bourgogne (Loire), Brunello and Prugnolo Gentile (Rank II
Italy). Naming any of them here alongside its defining clue would have handed
over another question's answer, and no check catches that.

Every stem opener is distinct, the constructions in lib.BANNED_TEMPLATES are
avoided by design, and where the answer is a variety the stem opens with a
bottle, a list or a guest so the grape arrives as the answer rather than as the
first clause.
"""

from lib import Q

CAT = "Grapes & Labels"
SLUG = "r1-grapes-labels"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("One vine, many names", 6),
    ("Reds under other names", 7),
    ("Whites under other names", 6),
    ("Names that mislead", 6),
    ("Labelling by grape", 6),
    ("Labelling by place", 6),
    ("Blends, and what a label may claim", 6),
    ("The words inside a grape's name", 4),
    ("Answering for the grape at the table", 3),
]

BANK = [
    # ---------------------------------------------- one vine, many names (6) --
    Q("One vine, many names",
      "Reference books on vine varieties give a single plant one main entry and then list a dozen further names beneath it, every one of them in daily use somewhere. What is each of those further names called?",
      ["A synonym", "A clone", "A crossing", "A rootstock"], 0,
      "A synonym is the identical plant under another name, so two wines can share a vine and share nothing else whatever. A clone is a selection made within one variety and a crossing is a new variety bred from two parents, so neither word will do instead. The most travelled vines have collected names by the dozen, and the registers that hold them run to hundreds of pages."),
    Q("One vine, many names",
      "Cuttings travelled with growers, soldiers and monks for centuries before anybody kept a register of what was planted where. What is the lasting consequence for today's labels?",
      ["One variety turns up under a different name in nearly every country that took it up",
       "Most European varieties died out and a handful of survivors replaced them",
       "Each district ended up with a genuinely different variety of its own",
       "Grape names were standardised early, because the export trade insisted on it"], 0,
      "A vine arriving somewhere new was named in the local language, or after the place it had come from, or after whoever carried the cuttings, and nothing obliged anyone to ask what it had been called before. Naming was local and the plant was not, which is the entire reason synonym lists exist. It also means the number of distinct varieties in the world is far smaller than the number of names for them."),
    Q("One vine, many names",
      "Two districts a thousand miles apart argue over whether their grape is one variety or two, and the wines taste nothing alike. What settles it?",
      ["Comparing the DNA profiles of the two plants",
       "Tasting the two wines side by side",
       "Comparing the colour of the berries at harvest",
       "Taking whichever of the two names was recorded first"], 0,
      "A profile is read from the vine rather than from the wine, so climate, yield and cellar work cannot disturb it. That matters because those three move flavour far more than identity does, and no argument of this kind has ever been settled by tasting. The older evidence was the shape of the leaves and the growing tips, skilled work that was frequently wrong."),
    Q("One vine, many names",
      "A grower knows his vine by three names and may print only one of them on the bottles he is sending abroad. What decides which?",
      ["Each country publishes the variety names its own labels are allowed to carry",
       "The name used in the variety's country of origin always takes precedence",
       "The importer chooses whichever of the names sells best in that market",
       "The oldest recorded name has to be used wherever the wine is sold"], 0,
      "Each country keeps its own list of the variety names its labels may carry, and a name missing from that list cannot go on a bottle sold there. The same wine can therefore be sold under one name at home and a different one across a border. A producer who exports widely reprints labels market by market for exactly this reason."),
    Q("One vine, many names",
      "A variety name printed for generations was struck off the permitted list because it repeated the name of a protected wine region elsewhere. Which principle forced the change?",
      ["A variety name may not trade on a protected place name belonging to somebody else",
       "A variety name has to be in the language of the country that grows it",
       "A variety name may not run to more than a single word",
       "A variety name has to match the one used where the variety originated"], 0,
      "Protection of a place name reaches evocation as well as outright use, so a variety name that reads like a region can be withdrawn even where nobody was deceived. Growers are normally given a transition period to sell through old labels, which leaves cellars holding bottles under a name the shelf no longer shows. Changes of this kind have gone through more than once in the last twenty-five years."),
    Q("One vine, many names",
      "One word opens the names of a long list of Italian, Iberian and Greek wines, white and red, sweet and dry, and most of the vines behind them turn out not to be related to each other. Which word?",
      ["Malvasia", "Vermentino", "Garganega", "Verdicchio"], 0,
      "It is a group of varieties rather than a variety, and Malvasia Bianca, Malvasia di Candia, Malvasia Istriana and Malvasia di Lipari are separate vines with separate parentages, while Puglia's Malvasia Nera turns out to be a natural cross of Negroamaro with another Malvasia. The word appears to travel back to a Greek port that shipped sweet wine to Venice, and it attached itself to whatever was in the barrel. A label carrying it therefore promises far less than it looks as though it should."),

    # ------------------------------------------- reds under other names (7) ---
    Q("Reds under other names",
      "One estate bottles a single vineyard twice, printing Syrah on one label and Shiraz on the other, and the vines, the clone and the soil are identical. What is that pair of words doing?",
      ["Signalling the style the buyer should expect, since both name one variety",
       "Marking two different clones of the one variety",
       "Separating an estate-grown wine from one made with bought-in fruit",
       "Separating an oaked bottling from an unoaked one"], 0,
      "Usage rather than law has attached an expectation to each word, the French form suggesting pepper, freshness and restraint and the Australian form suggesting riper, sweeter, fuller fruit. Nothing binds a producer to either reading, so the choice is a convention the label trusts the buyer to understand. Growers working cool sites outside France very often choose the French form for precisely that reason."),
    Q("Reds under other names",
      "A list is to carry one variety twice, from two countries, without printing the same grape name in both places. Which pairing does that?",
      ["A Puglian Primitivo and a Californian Zinfandel",
       "A Rioja Tempranillo and a Tuscan Sangiovese",
       "A Beaujolais Gamay and a Loire Gamay",
       "A Sicilian Nero d'Avola and a Puglian Negroamaro"], 0,
      "The two names belong to one variety, registered separately in each country long before anybody compared the plants, so a list can show it twice without repeating a word. Gamay is Gamay in both of the places named, and the remaining pairs are genuinely different vines. It makes a useful flight, since a guest meets one grape in two climates and tastes what the place did to it."),
    Q("Reds under other names",
      "Handed a Spanish red labelled Garnacha and a southern French red labelled Grenache, a guest asks whether the two are related. What is the correct answer?",
      ["Yes, one and the same variety, spelled the Spanish way on one label and the French way on the other",
       "No, two closely related varieties whose names resemble one another because both descend from a common Pyrenean parent",
       "No, the French vine is a crossing bred from the Spanish one",
       "Yes, but only where the French wine states its grape on the label"], 0,
      "The vine is Spanish in origin, crossed the Pyrenees centuries ago and picked up a French spelling on the way. It is among the most widely planted black grapes anywhere and turns out everything from pale dry pink to sweet fortified red, so a shared identity guarantees nothing at all about style. Its modern reputation rests on old low-yielding bush vines rather than on the volume it was long grown for."),
    Q("Reds under other names",
      "The corner of a Cahors label carries the word Cot, and the guest holding the bottle recognises nothing on it. Which grape does that word name?",
      ["Malbec", "Merlot", "Tannat", "Fer Servadou"], 0,
      "Cot is the older French name and Cahors has used it since long before the wider world learned the other one, so both turn up on labels there. Touraine growers in the Loire use it as well. The wine most drinkers associate with the better-known name is made a hemisphere away, which is why one word travelled and the other stayed at home."),
    Q("Reds under other names",
      "Labels from one Alpine Italian province print two names for the same pale red grape, one Italian and one German, often on a single bottle. What explains the doubling?",
      ["The province is officially bilingual, so its grapes and its wines are named twice",
       "The two names mark two different clones grown there",
       "One name is used for the still wine and the other for the sparkling",
       "One name belongs to the co-operatives and the other to private estates"], 0,
      "Alto Adige and Sudtirol are one place in the two official languages, and villages, denominations and varieties all carry an Italian name and a German one. The grape in question makes a pale, light, low-tannin red drunk young and mostly drunk locally. Reading such a label means recognising a translation rather than hunting for a second wine."),
    Q("Reds under other names",
      "A Priorat back label prints Samso, a Rioja one prints Mazuelo and a Languedoc one prints Carignan. What links the three words?",
      ["All three name a single black variety, in three of the languages that grow it",
       "All three name varieties bred from one common parent",
       "All three are permitted blending partners within one appellation",
       "All three name a style of wine rather than a grape"], 0,
      "The vine is high in acid, high in tannin and enormously productive, which is why it was planted by the hectare for bulk wine and then pulled out again. Where old bush vines survive and crop very little it is taken seriously once more. A Spanish denomination shares one of the names, both of them taken from the same Aragonese town, and is planted more to other varieties than to that grape, which catches people out."),
    Q("Reds under other names",
      "Growers in Chinon call the grape Breton, and growers on Bordeaux's Right Bank call the same vine Bouchet. Which variety are both of them talking about?",
      ["Cabernet Franc", "Cabernet Sauvignon", "Malbec", "Merlot"], 0,
      "Breton has nothing to do with Brittany and is thought to record the name of the man said to have spread the vine through the Loire, while Bouchet is the old Libournais word and survives inside several estate names there. One variety, two districts, and wines that resemble each other very little. It is a clean reminder that a synonym tells you about naming and never about style."),

    # ----------------------------------------- whites under other names (6) ---
    Q("Whites under other names",
      "Two neutral, high-acid whites reach the same buyer, one labelled Ugni Blanc in France and one labelled Trebbiano Toscano in Italy. What is the relationship between them?",
      ["A single vine, called Ugni Blanc where France grows it and Trebbiano where Italy does",
       "Two different varieties belonging to one family",
       "A French crossing bred from the Italian variety and Colombard",
       "One variety, though only the Italian name may lawfully be printed in Europe"], 0,
      "It is among the most widely planted white grapes in the world and gives a wine so neutral that it is usually blended away or used as a base rather than bottled under its own name. Italy attaches a regional word to it, so Trebbiano Toscano, Trebbiano Romagnolo and Trebbiano d'Abruzzo look like one family and are in fact several distinct vines. That makes the Italian name considerably less precise than the French one."),
    Q("Whites under other names",
      "Sent back for looking faintly coppery rather than water-white, a glass of Pinot Grigio comes to you at the pass. What is the correct explanation?",
      ["The skins hold a pink-grey pigment, and juice left in contact with them takes up colour",
       "The wine has oxidised in the bottle",
       "A little red wine has been blended in, which is the usual way of producing a copper tint in a white",
       "The wine has been matured in new oak"], 0,
      "Pressing quickly gives the pale wine most drinkers expect and leaving the juice on the skins gives a coppery one, so the colour is a decision rather than an accident. Italian producers call the deliberate version ramato, meaning coppered, and it is a long-standing style in the north-east. The same variety under its French name is more often made in a fuller, weightier manner again."),
    Q("Whites under other names",
      "A Ligurian white labelled Pigato, a Piedmontese one labelled Favorita and a Provencal one labelled Rolle all prove to share one identity. Which better-known name covers the three of them?",
      ["Vermentino", "Verdicchio", "Cortese", "Arneis"], 0,
      "Local selections differ a little in the vineyard, which is why each district defends its own word, but the vine behind them is single. It grows right around the north-western Mediterranean and on the islands, and the widely known name is what most export labels now carry. Provence in particular keeps its own word on the bottle, while Sardinia and Tuscany print the international one, so which name a buyer meets depends on where the wine was made."),
    Q("Whites under other names",
      "An Italian list offers Riesling Renano and Riesling Italico, and a guest asks for the true Rhine grape. Which of the two should be poured?",
      ["Riesling Renano", "Riesling Italico",
       "Either, since the two phrases mean the same thing",
       "Neither, since both name crossings bred from Riesling"], 0,
      "Renano means of the Rhine and marks the genuine article. The other name belongs to an unrelated high-acid white that carries a different name in nearly every country between Austria and the Black Sea, and nothing but that second word separates the two on an Italian label. Borrowing a famous variety's name for an unrelated grape was ordinary practice, and although modern rules stop new ones being coined the old names stand, which is why Riesling Italico is still a name an Italian label may carry."),
    Q("Whites under other names",
      "A northern Italian label prints Pinot Bianco and a German one prints Weissburgunder, and a guest assumes two different grapes. Which single variety is in both bottles?",
      ["Pinot Blanc", "Pinot Gris", "Chardonnay", "Chenin Blanc"], 0,
      "Both names translate the French one word for word, the Italian directly and the German by way of the family name it uses for the whole Pinot group. The wine is a quiet, appley, medium-bodied white that suffers from being compared with Chardonnay, which it faintly resembles and is regularly mistaken for. Recognising the translation is most of what reading such a label requires."),
    Q("Whites under other names",
      "A Sicilian white labelled Grecanico and a Veneto white from the hills around Soave turn out to be one vine. Which name does the Veneto print?",
      ["Garganega", "Verdicchio", "Grillo", "Trebbiano"], 0,
      "The match was established only recently, ending a long assumption that a Sicilian grape whose name suggests Greece could have nothing to do with a Venetian one. The vine ripens late, keeps its acidity and gives a wine of almonds and white flowers in both places, though the climates could hardly be less alike. Names that gesture at an origin are among the least reliable evidence in the whole subject."),

    # ------------------------------------------------ names that mislead (6) --
    Q("Names that mislead",
      "Three whites reach one table from Spain, the Portuguese Atlantic islands and the Marche, and their grape names differ by only a handful of letters. What is the relationship between the three vines?",
      ["There is none; the resemblance is in the names alone",
       "All three are colour mutations of one variety",
       "All three are crossings from a single parent",
       "All three are regional names for one variety"], 0,
      "Verdejo, Verdelho and Verdicchio all take their names from the green tinge of a ripening berry, and words built on that root have attached themselves to unrelated vines right around the Mediterranean. A shared word root looks like evidence and is not. Cases of this kind stood open for centuries, since a name carries no record of where the cuttings actually came from."),
    Q("Names that mislead",
      "A story often told at the table has one famous black grape carried to France from a Persian city whose name it echoes. Where did the vine actually come from?",
      ["It is a natural crossing of two obscure varieties from south-eastern France",
       "It reached France from Persia exactly as the story has it, carried west by returning crusaders",
       "It is a colour mutation of Grenache",
       "It was bred deliberately in a nineteenth-century nursery"], 0,
      "The parents are Dureza from the Ardeche and Mondeuse Blanche from Savoie, both local, both obscure, which puts the grape's origin squarely in France. Romantic origin stories cling to grape names because a name that sounds like a distant place invites one. The lesson generalises: a name is evidence of what people once believed and not of where a vine came from."),
    Q("Names that mislead",
      "Bottles sold for decades in California as Napa Gamay were made from a southern French variety called Valdiguie, and the authorities eventually withdrew the old name. What was the objection?",
      ["A variety name may not be printed on a wine made from a different variety",
       "The name was one producer's registered trademark, so no other winery could lawfully print it",
       "The name duplicated a French appellation, and no imported name may appear on an American label",
       "The variety had been dropped from the list of vines California permits growers to plant"], 0,
      "Once the identification was made the label was describing a grape that was not in the bottle, and long usage rescues nothing. Producers were given time to sell through their stock and then had to print the correct name. Several other borrowed names left American labels in the same period, for the same reason."),
    Q("Names that mislead",
      "Two Bordeaux varieties share the word Sauvignon and a guest supposes that one must be a red version of the other. What is the actual link?",
      ["Cabernet Sauvignon is a natural crossing of Cabernet Franc with Sauvignon Blanc, so the shared word records a parent",
       "There is no link at all, the shared word being one of many that attached themselves to unrelated vines around Bordeaux over the centuries",
       "Cabernet Sauvignon is a colour mutation of Sauvignon Blanc",
       "Sauvignon Blanc is a white mutation of Cabernet Sauvignon"], 0,
      "The crossing happened by chance in a Bordeaux vineyard, most probably in the seventeenth century, and the parents were identified only in the 1990s. Both are still widely grown, which is unusual and is what made the case straightforward to prove once the tools existed. A shared word in two grape names occasionally does mean something, and this is one of the rare occasions."),
    Q("Names that mislead",
      "Across one list appear Muscadet, Muscadelle and Muscat, and a guest takes the three for variations on a single grape. Which reading is correct?",
      ["One is an appellation, one is a Bordeaux variety unrelated to the family, and only the third names that family",
       "All three name members of the Muscat family",
       "All three are French names for one variety",
       "Two of the three name grapes of the Muscat family, and the third names the Loire village they were first grown in"], 0,
      "The first is an appellation in the western Loire and no modern label prints it as a grape name; the second is a minor white of Bordeaux whose name is the only thing it shares with the aromatic family; the third covers a whole group of related aromatic vines. Three labels, three quite different kinds of word. Nothing but the first five letters connects them."),
    Q("Names that mislead",
      "A section of an English wine list is headed Claret, and a guest goes looking for a grape of that name. What is the word actually doing?",
      ["Naming red Bordeaux in English trade usage, rather than any grape or appellation",
       "Standing as an old English name for Cabernet Sauvignon, the grape the region's reds are built on",
       "Marking a Bordeaux wine above a set alcoholic strength",
       "Marking any wine built from two or more varieties"], 0,
      "It descends from clairet, the pale red the region shipped to England in the Middle Ages, and survived in English as a general word for the region's reds. It binds nobody to anything, which is why it also turns up as a fanciful name on bottles from other countries. A guest who asks for it wants red Bordeaux, or something built to resemble it."),

    # -------------------------------------------------- labelling by grape (6) --
    Q("Labelling by grape",
      "A guest reads the word varietal on your list and takes it for a mark of quality. What does the word denote?",
      ["A wine named after, and made principally from, one grape variety",
       "A wine of better quality than a blend, since a single grape has nothing to hide behind",
       "A wine from a single vineyard, small enough that one variety fills the whole of it",
       "A wine made without any oak"], 0,
      "The word describes how a wine is labelled and nothing else, so a varietal wine can be superb or dismal and can still draw on many parcels and many sites. The opposite of a varietal wine is not a poor wine but a wine sold under a place name or a brand. A good many of the most expensive bottles in the world are not varietal wines at all."),
    Q("Labelling by grape",
      "Twenty countries stand side by side on one supermarket shelf, and most of the bottles can be compared at a glance because they print the same handful of words. Which labelling convention allows that?",
      ["Varietal labelling, which puts the grape variety on the front",
       "Vintage dating, which puts the year of the harvest on the front label",
       "Estate bottling statements, which say who grew the fruit and who bottled it",
       "Protected designations of origin, which tie a name to one delimited place"], 0,
      "A shopper who has learned six grape names can navigate a shelf drawn from a dozen countries, which is why the practice spread out of California through the New World and into the cheaper European tiers. A place-labelled bottle asks far more of its reader and repays it with far more information."),
    Q("Labelling by grape",
      "A grape name fills the front of a bottle and no region appears anywhere on it. What has that grape name said about where the wine grew?",
      ["Nothing at all, since a variety name carries no origin with it",
       "That the fruit came from the variety's home region",
       "That the wine was made outside Europe",
       "That the fruit was drawn from more than one country"], 0,
      "Varieties are planted on every wine-growing continent, so a name on its own places a wine nowhere. Rules elsewhere on the label still require an origin statement of some sort, and on the cheapest wines that can be as wide as a whole trading bloc. Variety and origin are two separate claims, made separately and checked separately."),
    Q("Labelling by grape",
      "A back label heads its list of grapes with a single French word that a guest mistakes for a quality term. Which word introduces the varieties?",
      ["Cepage", "Cuvee", "Cru", "Millesime"], 0,
      "Cepage is simply the French for grape variety, and a German label uses Rebsorte and an Italian one vitigno in the same place. Cru points at a vineyard or a ranking and millesime at the year, so the three words answer three quite different questions. Recognising which of them a line is answering is most of the work of reading an unfamiliar label."),
    Q("Labelling by grape",
      "An appellation permits one grape and one grape only, and the producer prints that grape's name on the front anyway. What is it doing there?",
      ["Answering buyers who shop by variety, since the rules already settle what is in the bottle",
       "Satisfying a rule that the variety must always be stated once an appellation permits only one grape",
       "Signalling that the wine comes from a single vineyard",
       "Warning that a second variety is present as well"], 0,
      "Naming the variety is an optional particular almost everywhere, so a producer adds it where the export market expects it and leaves it off where the appellation sells itself. It costs nothing and answers the first question a buyer trained on New World labels will ask. Optional does not mean unchecked, since a statement a producer chooses to make is still one the rules will hold him to."),
    Q("Labelling by grape",
      "A dozen countries with little else in common plant the same short list of grapes, in good part because those names are recognised on an export shelf. What are those grapes collectively called?",
      ["International varieties", "Indigenous varieties", "Crossings",
       "Clonal selections"], 0,
      "Cabernet Sauvignon, Merlot, Chardonnay, Sauvignon Blanc and Syrah travel further than any others, and a grower planting them buys instant recognition at the price of saying anything local. The reaction against that is the revival of indigenous varieties, whose names sell nothing on their own and have to be explained bottle by bottle. Both strategies are visible on any modern list."),

    # ------------------------------------------------- labelling by place (6) --
    Q("Labelling by place",
      "No grape is named anywhere on a European red, and its producer has broken no rule at all. Why is the variety missing?",
      ["The appellation already settles which grapes may be used, so naming them adds nothing",
       "European producers are forbidden to name varieties",
       "The blend changes from year to year, so it cannot be stated",
       "The variety appears only on bottles intended for export"], 0,
      "Where the rulebook fixes the grapes, the place name carries that information for anybody who knows the rules, and centuries of labels were written for people who did. The information is assumed rather than hidden. Supplying it for a guest who has not got it is a good part of what a sommelier is for."),
    Q("Labelling by place",
      "A by-the-glass list is arranged by grape, and one European bottle on it names no grape anywhere. Where should it be filed?",
      ["Under the variety its appellation requires, since that is what is in the bottle",
       "Under its appellation, since no variety is stated",
       "It cannot honestly be listed by variety at all",
       "Under whichever variety the guest is most likely to expect"], 0,
      "The wine is made from that grape whether or not the label says so, and a list exists to help a guest choose rather than to reproduce a label word for word. Printing the appellation and the variety together is the usual solution and teaches the guest something on the way. What the heading claims has to be checked against the rulebook behind the name rather than against the label alone."),
    Q("Labelling by place",
      "Told that a place name implies a grape, a guest concludes that any European label can be decoded that way. Where does the reasoning fail?",
      ["Where an appellation permits several varieties, so the name fixes a style rather than a grape",
       "Where the appellation covers a very small area",
       "Where the wine is white rather than red",
       "Where the producer also owns vineyards elsewhere, since fruit may then be trucked in from another appellation"], 0,
      "Plenty of appellations run to a dozen permitted grapes or more, and two wines from one such name can be built quite differently and both comply. In those places the label tells you the rulebook was followed and only the producer's own literature tells you the blend. The single-variety appellation is the easy case rather than the general one."),
    Q("Labelling by place",
      "One appellation makes a red and a white, and the two wines are not made from the same grape. What does a buyer need in order to read either label?",
      ["The variety the rules assign to each colour within that one name",
       "The vintage, since the grapes alternate from year to year",
       "The alcoholic strength of each of the two wines",
       "The name of the company that bottled them"], 0,
      "A single denomination frequently covers several colours, each with its own permitted varieties, its own ceiling on yield and sometimes its own ageing rules. The place is one word and the rulebook behind it runs to many pages. That is the practical reason a place-labelled bottle demands more of its reader than a varietal one does."),
    Q("Labelling by place",
      "Vineyards in a European village were planted to whatever local practice required, and every buyer for miles knew what that was. What did that leave worth printing on the bottle?",
      ["The place, because it was the only part that varied",
       "The grape, because buyers wanted it confirmed",
       "The strength, because it varied most from year to year",
       "The producer's trade, because few buyers could read"], 0,
      "Where custom, and later law, settled the variety for everyone in the village, naming it would have been like printing the language a book is written in. What differed from bottle to bottle was whose land the wine came from and how good that land was. The convention has long outlived the conditions that produced it, which is why half the world now needs it explained."),
    Q("Labelling by place",
      "A New World label prints a region on one line and a variety on the line beneath it. What is each of those two lines doing?",
      ["The region carries the origin claim and the variety names the plant, and each is checked separately",
       "The region is decoration and only the variety is regulated, since origin claims are audited nowhere outside Europe",
       "The variety is decoration and only the region is regulated",
       "Together the two form a single protected name"], 0,
      "Both statements are audited, against different rules, and neither one depends on the other for its truth. The arrangement is what gives such labels their reputation for plain speaking, since the two questions a buyer asks are answered in two lines. A European bottle answers the first and leaves the second to the reader."),

    # ------------------------------ blends, and what a label may claim (6) -----
    Q("Blends, and what a label may claim",
      "Percentages for each grape run along the foot of a back label whose front names no grape at all. What obliges the producer to print them?",
      ["Nothing; a breakdown of a blend is voluntary",
       "European law requires it for any wine that is a blend",
       "It is required whenever no single grape reaches half of the wine",
       "It is required for wines sold above a set price"], 0,
      "Producers print a breakdown because it interests the kind of buyer who reads back labels, not because anyone made them do it. The proportions can shift from vintage to vintage while the front label stays exactly as it was, which is one reason many producers would rather not commit to figures at all. What is compulsory on a label sits elsewhere, and the make-up of a blend is not part of it."),
    Q("Blends, and what a label may claim",
      "A European label naming two grapes rather than one makes a promise that a single name does not. What is it?",
      ["That the wine is made entirely from the two varieties named",
       "That the two were fermented together rather than blended afterwards",
       "That the two came from separate vineyards",
       "That the wine was aged in oak before bottling"], 0,
      "Naming one variety leaves a margin behind it that need not be declared anywhere; naming two closes that margin, because the pair have to account for the whole wine. A producer with a small third component therefore either leaves it out of the blend or leaves the second name off the label. A wine that cannot make the promise simply names one grape, or none."),
    Q("Blends, and what a label may claim",
      "Six varieties go into a blend and not one of them dominates it, so the front of the bottle carries an invented name instead. What lies behind that choice?",
      ["No one grape carries enough of the wine to be named alone, and six names sell nothing",
       "Blends of more than three varieties may not be sold under any name",
       "An invented name is required whenever the fruit comes from several vineyards",
       "A producer must invent a name once the wine is exported"], 0,
      "A label may name one grape by itself only where that grape carries the wine, and a genuinely equal blend has no such grape. Naming every variety in the blend is the lawful alternative, and six names across a front label sell nothing, so the producer builds a name of his own and then spends years teaching buyers what stands behind it. Several of the most admired wines in the world are sold exactly that way, so an invented name is no evidence of a modest bottle."),
    Q("Blends, and what a label may claim",
      "A Californian back label calls the wine a Bordeaux blend, and not a drop of French wine is in it. What is that phrase claiming?",
      ["The set of grape varieties used, and nothing whatever about where the fruit grew",
       "That the winemaker trained in Bordeaux",
       "That the wine may lawfully use the region's name",
       "That part of the fruit was bought in from Bordeaux, which is what naming the region reports"], 0,
      "Phrases of this kind borrow a region's name as shorthand for a recipe and carry no legal weight anywhere. They are useful to a buyer all the same, since they say in two words what a list of varieties takes a line to say. In Europe such wording runs straight into the protection given to the region's name, which is why it is far commoner on labels written for other markets."),
    Q("Blends, and what a label may claim",
      "An estate sells its single varieties cheaply and reserves a blend for its most expensive bottling. What does that arrangement say about blending?",
      ["That blending is a tool for building a better wine rather than a sign of a lesser one",
       "That blends are cheaper to produce than single varieties",
       "That the estate's varietal wines failed to qualify for their appellation",
       "That a blend is required at the top of any range"], 0,
      "Varieties ripen at different moments and cover each other's weaknesses from one year to the next, so a blend can be both more consistent and more complete than any of its parts. The idea that blending hides something comes from the cheapest end of the trade, where it often does. Most of the classic wines of Europe are blends and most of them never say so on the label."),
    Q("Blends, and what a label may claim",
      "A pink wine names a black grape on its front label and a guest calls it an error. What should you tell them?",
      ["The label is right, since a rose is made from black grapes given only brief contact with their skins",
       "The label should name the white grape that the wine was blended with",
       "The label names the grape the vineyard is planted to rather than the one in the wine",
       "The colour came from the barrel, so no grape name applies"], 0,
      "Colour sits in the skins and not in the juice, so the same black grape gives a red wine, a pink one or a white one depending on how long the two are left together. A varietal rose is therefore named after a black grape as a matter of course. It is among the most common questions asked at a table in summer and among the easiest to answer well."),

    # ----------------------------------- the words inside a grape's name (4) ---
    Q("The words inside a grape's name",
      "Four labels from four countries open a grape's name with Tinta, Tinto, Nero and Blau. What do those four words announce?",
      ["That the grape is black-skinned", "That the wine will be dry",
       "That the wine was matured in wood",
       "That the grape is a mutation of a white variety"], 0,
      "Colour words are among the most dependable things in grape naming: the Iberian pair, the Italian word and the German one all mark a dark-skinned vine. It is the quickest way into an unfamiliar name on a label in a language you cannot read. Nothing in the word promises a style, and vines of this kind turn out everything from the palest pink to the blackest red in the country."),
    Q("The words inside a grape's name",
      "A southern French white is labelled Grenache Blanc and a red beside it is labelled Grenache. What does that extra word mark?",
      ["A white-berried mutation of the same vine, bottled as a variety in its own right",
       "A white wine pressed quickly from the black grape, before the skins can give up any colour",
       "A younger selection of the same variety",
       "A blend of the black grape with a white one"], 0,
      "Vines throw colour mutations often enough that several familiar varieties exist in more than one colour, each with a settled name and a settled character of its own. This one is fuller and lower in acid than its black counterpart and is a mainstay of the white blends of the Mediterranean south. A pale wine pressed from a black grape is a different thing entirely and has its own vocabulary."),
    Q("The words inside a grape's name",
      "Two related whites grown side by side in the Pyrenean foothills are separated on their labels by the words Petit and Gros, and a guest reads that pair as a ranking. What do the two words record?",
      ["The size of the berry, which is why one of them concentrates far more than the other",
       "The age of the vines the fruit came from",
       "The order in which the two are picked",
       "The relative standing of the two wines, the smaller word marking the lesser of the two bottlings"], 0,
      "Small berries carry more skin against less juice, so the smaller-berried of the pair gives the more concentrated wine and has the greater reputation, in dry wines and sweet ones alike. Size and quality line up here by an accident of botany rather than because the words mean anything of the sort. The same pair of words elsewhere separates two entirely unrelated varieties, so it is never a rank."),
    Q("The words inside a grape's name",
      "A Sicilian red is labelled Nero d'Avola and a guest takes Avola for the appellation. What is that word doing in the name?",
      ["It belongs to the variety's name, recording a town the grape became associated with",
       "It names the appellation the wine comes from, which is why the grape name and the place run together",
       "It names the estate that grew the fruit",
       "It marks a superior selection of the variety"], 0,
      "Grape names built out of a place are common, and the place inside them is a piece of history rather than an origin claim, since the vine can be planted anywhere that suits it. The appellation, where there is one, is stated separately and in its own form of words. Reading the two as one line is among the easiest mistakes to make on an Italian label."),

    # ------------------------------ answering for the grape at the table (3) --
    Q("Answering for the grape at the table",
      "Two bottles of Chardonnay from opposite ends of the world taste nothing alike, and a guest asks whether one of them has been mislabelled. What is the answer?",
      ["Neither has; a variety name commits a producer to the grape and to nothing else",
       "The riper of the two is very probably a blend",
       "One of them must have been made from a different variety",
       "The difference means that one of the two wines is faulty"], 0,
      "Climate, yield, picking date, vessel and the winemaker's intention move a wine much further than identity does, which is how one grape arrives lean and stony in one glass and broad and buttery in the next. A variety name opens a conversation rather than describing a taste. Saying what that grape usually does in that particular place is the useful half of the answer."),
    Q("Answering for the grape at the table",
      "A guest asks for the grape they drank on holiday in Spain and nothing on your list carries that name. What is the first thing to check?",
      ["Whether the list already holds the same variety under another country's name for it",
       "Whether something similar can be poured without mentioning the substitution",
       "Whether a case can be ordered in for that evening",
       "Whether the guest has remembered the name correctly"], 0,
      "A great many varieties sit on a list twice under two names, and a sommelier who knows the synonyms says yes where a colleague says no. It is the most practical everyday use of synonym knowledge there is. Naming the alternative openly also leaves the guest with something they will use again."),
    Q("Answering for the grape at the table",
      "A guest who has enjoyed a bottle wants the grape written down so they can buy it at home, and the vine travels under a different name where they live. Which name goes on the card?",
      ["The name printed where the guest shops, since that is the form their own shelf will carry",
       "The name on the bottle in front of them, since a variety may only be sold under the name its producer chose",
       "The name used where the vine originated, since every other country's register is built from that form",
       "The name vine scientists use in their catalogues, since that is the one form recognised everywhere"], 0,
      "The same vine reaches shelves under one name in one market and another name somewhere else, so the useful name is whichever one the guest's own shop prints. Vine scientists do settle on a reference name for their catalogues, and it carries no authority over a label and will never appear above a shop shelf. A recommendation the guest cannot act on when they get home has not really been given."),
]
