"""Rank I rewrite - Germany (59 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

The category is built around the one problem that shapes everything German:
ripening a late grape at fifty degrees north. That gives the running order -
latitude, river and slope first, then the regions in the order a student meets
them, then the grapes, then the two systems that confuse guests most, the
Pradikat ladder and the label. Stems lead with a symptom, a rock, a scene at
the table or a bottle in the hand, and let the region, grape or term be the
answer.

Everything is ASCII: Rhone, Cotes, Wurttemberg, Gewurztraminer, Spatlese.
"""

from lib import Q

CAT = "Germany"
SLUG = "r1-germany"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Latitude, rivers and slope", 6),
    ("The thirteen Anbaugebiete", 5),
    ("Mosel, Saar and Ruwer", 8),
    ("Rheingau and Nahe", 6),
    ("Rheinhessen and the Pfalz", 6),
    ("Baden, Franken and the south", 6),
    ("Grape varieties", 7),
    ("The Pradikat ladder", 8),
    ("Labels, sweetness and the VDP", 7),
]

BANK = [
    # -------------------------------------- latitude, rivers and slope (6) ---
    Q("Latitude, rivers and slope",
      "Most of Germany's vineyard sits between roughly forty-seven and fifty-two degrees north, among the coolest latitudes carrying classic wine regions. What does that position do to the sunlight?",
      ["It keeps the sun low, so ground tilted toward it gathers more energy",
       "It lifts the sun overhead at midday, so level ground gathers the most energy",
       "It lengthens the ripening season by roughly two months in an average year",
       "It removes the risk of spring frost"], 0,
      "At a low sun angle the same beam of light is smeared across a wide patch of flat ground. Tilting the ground toward the sun concentrates it again, which is why Germany's best sites are also its steepest."),
    Q("Latitude, rivers and slope",
      "Growers on the Rhine and the Mosel plant as close to the water as the slope allows, and abandon the ground once it climbs away from the bank. What are the rivers giving them?",
      ["Reflected light, stored warmth that blunts frost, and a longer autumn",
       "Irrigation water permitted under German wine law",
       "Cool air that holds budbreak back until the frost risk has passed",
       "Humidity high enough to prevent fungal disease"], 0,
      "A large body of water warms and cools slowly, so the river carries heat into the autumn and takes the edge off the coldest nights. Its surface also throws light back up onto the slope above it."),
    Q("Latitude, rivers and slope",
      "Dark Devonian rock along the Mosel absorbs heat through the day and gives it back after sunset. What is it?",
      ["Slate", "Granite", "Muschelkalk limestone", "Loess"], 0,
      "Slate is dark enough to warm quickly and splits into plates that drain hard and hold no water. On a cold October night the stone is still radiating the afternoon back at the fruit."),
    Q("Latitude, rivers and slope",
      "The Mosel doubles back on itself again and again on its way to the Rhine. Why does that serpentine course matter so much to a grower?",
      ["Every bend gives a different aspect, and only some ripen Riesling",
       "The bends slow the current and raise humidity enough to guarantee noble rot",
       "The loops shorten the distance the fruit must travel to the cellar",
       "Each bend forms a separate appellation under German law"], 0,
      "A single meander presents every point of the compass within a couple of kilometres. The famous sites are the ones caught on the steep southern flank of a bend, and the ground facing them is often left unplanted."),
    Q("Latitude, rivers and slope",
      "Vines on the steepest Mosel ground are each trained up a single tall stake rather than along a wire trellis. What forces that?",
      ["The slope is too steep to work along a contour",
       "A stake carries more fruit per vine than a wire",
       "German law requires stake training for Pradikatswein",
       "Stakes shelter the vine from wind coming off the river"], 0,
      "Einzelpfahl training lets a worker move vertically, which is the only practical direction on ground of forty or fifty degrees. Every operation is done by hand, and that cost is built into the price of the bottle."),
    Q("Latitude, rivers and slope",
      "Nothing on the steepest slate slopes can be worked by tractor or machine harvester. What follows from that for the wine?",
      ["Labour costs many times more, setting a price floor",
       "Yields run far higher than on flat land",
       "The wine must legally be sold as Landwein or Tafelwein",
       "Fermentation has to be carried out in the vineyard itself"], 0,
      "Hand pruning, hand picking and carrying eroded soil back up the hill in baskets all have to be paid for, which sets a floor under what the wine must sell for. Where the market will not carry that cost the vineyards are simply abandoned, and many fine sites have been."),

    # -------------------------------------- the thirteen Anbaugebiete (5) ----
    Q("The thirteen Anbaugebiete",
      "A German quality wine must name on its label whichever of the thirteen official growing regions it came from. What are those regions called?",
      ["Anbaugebiete", "Bereiche", "Grosslagen", "Landweingebiete"], 0,
      "The Anbaugebiet is the top administrative unit; a Bereich is a district inside one, and a Grosslage a collective site inside that. Qualitatswein and Pradikatswein must both carry the Anbaugebiet name."),
    Q("The thirteen Anbaugebiete",
      "Which German region is unusual in planting more red than white, with Trollinger and Lemberger at the centre of it?",
      ["Wurttemberg", "Baden", "Franken", "Rheingau"], 0,
      "Wurttemberg drinks most of what it makes, and Trollinger, the grape the Alto Adige calls Schiava, is its everyday red. Lemberger, which Austria knows as Blaufrankisch, is the serious one."),
    Q("The thirteen Anbaugebiete",
      "One German region lies far to the south, facing Alsace across the Rhine, and is the warmest of the thirteen. Which?",
      ["Baden", "Wurttemberg", "Franken", "Pfalz"], 0,
      "Baden is long and narrow, running from the Bodensee up to Heidelberg. Its warmth is why the Pinot family rather than Riesling dominates there, in the shape of Spatburgunder, Grauburgunder and Weissburgunder."),
    Q("The thirteen Anbaugebiete",
      "A tiny northerly region on a left-bank tributary of the Rhine gives itself over almost entirely to red wine, which is remarkable that far north. Which one?",
      ["Ahr", "Mittelrhein", "Hessische Bergstrasse", "Saale-Unstrut"], 0,
      "The Ahr valley is narrow, steep and floored with slate, and it traps enough heat to ripen Spatburgunder at fifty degrees north. Fruhburgunder, an early-ripening mutation of the same grape, is its other speciality."),
    Q("The thirteen Anbaugebiete",
      "Two German regions sit far to the east on the Saale and the Elbe, and spent forty years cut off from the western wine trade. Which pair?",
      ["Saale-Unstrut and Sachsen", "Franken and Wurttemberg",
       "Mittelrhein and Ahr", "Baden and Hessische Bergstrasse"], 0,
      "Both are among the smallest and most northerly of the thirteen, and both lay inside East Germany until 1990. They work steep terraces and bottle almost everything dry."),

    # ------------------------------------------ Mosel, Saar and Ruwer (8) ----
    Q("Mosel, Saar and Ruwer",
      "Riesling from Mosel slate often reaches the table at seven or eight percent alcohol. What keeps a wine that light from tasting thin?",
      ["Residual sugar balanced by acidity",
       "A long spell in oak before bottling",
       "Fortification with neutral spirit",
       "Malolactic conversion softening the acid"], 0,
      "The cool site leaves the acidity intact and the fermentation is stopped with sugar still in the wine. Sweetness and acid balance one another, so the wine reads as delicate rather than watery."),
    Q("Mosel, Saar and Ruwer",
      "Two tributaries joining the Mosel near Trier were once named alongside it in the region's full title. Which?",
      ["The Saar and the Ruwer", "The Nahe and the Ahr",
       "The Main and the Neckar", "The Lahn and the Sieg"], 0,
      "The Saar is cooler and steelier than the main valley and the Ruwer smaller and lighter still. The whole region was called Mosel-Saar-Ruwer before the name was shortened to Mosel."),
    Q("Mosel, Saar and Ruwer",
      "The Mosel's best-known individual site clings to the slate directly above one town and carries a physician's name from a legend about a cured archbishop. Which vineyard?",
      ["Bernkasteler Doctor", "Wehlener Sonnenuhr",
       "Erdener Treppchen", "Piesporter Goldtropfchen"], 0,
      "The story has an Archbishop of Trier recovering from a fever after drinking it, and the site is a narrow strip of steep slate right behind the town. It is a byword for expensive vineyard land in Germany."),
    Q("Mosel, Saar and Ruwer",
      "Slate is not all one colour along the Mosel. Which village is known for weathered red slate and volcanic sandstone giving unusually spicy, exotic Riesling?",
      ["Urzig", "Graach", "Wehlen", "Trittenheim"], 0,
      "The Wurzgarten, the spice garden, sits on red rock rather than the blue-grey slate of Wehlen and Graach upstream. Its wines are broader and more perfumed, and they smell of the name."),
    Q("Mosel, Saar and Ruwer",
      "The upper stretch of the river toward Luxembourg sits on limestone rather than slate and grows an ancient, ferociously tart white grape. Which?",
      ["Elbling", "Silvaner", "Muller-Thurgau", "Gutedel"], 0,
      "Elbling is one of the oldest varieties still worked in Germany and gives a thin, high-acid wine that mostly ends up as Sekt. The Obermosel's Muschelkalk is a completely different geology from the Devonian slate downstream."),
    Q("Mosel, Saar and Ruwer",
      "A grower on one Mosel tributary loses whole vintages to unripeness in poor years yet makes the most piercing wine of the valley in good ones. Which tributary, and why?",
      ["The Saar, because it is colder and ripeness is not assured",
       "The Ruwer, because its soils are pure sand and hold no water",
       "The Saar, because it is planted mainly to red varieties",
       "The Ruwer, because it lies south of the main valley and ripens too fast"], 0,
      "The Saar is a side valley open to cold air, so the margin between ripe and unripe is thinner there than anywhere on the Mosel. When the year does deliver, the acidity gives wines of extraordinary tension and life."),
    Q("Mosel, Saar and Ruwer",
      "A vineyard on a Mosel bend near Bremm is routinely called the steepest in Europe. Roughly what gradient does it reach?",
      ["About sixty-five degrees", "About twenty degrees",
       "About thirty-five degrees", "About eighty-five degrees"], 0,
      "The Calmont is worked on ropes and a via ferrata runs through it for walkers. Anything approaching that angle can only be tended by hand, one vine at a time."),
    Q("Mosel, Saar and Ruwer",
      "A guest asks for the lightest serious white on the list to drink with a lightly spiced dish. Which German bottling answers that best?",
      ["A Mosel Riesling Kabinett", "A Baden Spatburgunder",
       "A Franken Silvaner trocken", "A Pfalz Grosses Gewachs"], 0,
      "Kabinett from the Mosel is usually the lowest in alcohol of anything worth cellaring, and its trace of sugar handles chilli and ginger that a dry wine would fight. The other three are all dry and considerably fuller."),

    # ----------------------------------------------- Rheingau and Nahe (6) ---
    Q("Rheingau and Nahe",
      "For some thirty kilometres west of Wiesbaden the Rhine abandons its northward course and runs east to west. What does that hand the growers on its north bank?",
      ["A full southern exposure across a long stretch of slope",
       "Shelter from the sun through the hottest part of the day",
       "A northerly exposure that preserves acidity",
       "Protection from the river's humidity"], 0,
      "The river turns west at Wiesbaden, runs to Rudesheim and turns north again at Bingen. The whole north bank therefore looks south across the water, and that sentence is most of what the Rheingau is."),
    Q("Rheingau and Nahe",
      "A courier carrying harvest permission from the Prince-Abbot of Fulda arrived late in 1775, and the shrivelled, rotten grapes were picked and pressed anyway. Which estate tells that story?",
      ["Schloss Johannisberg", "Kloster Eberbach",
       "Schloss Vollrads", "Schloss Reinhartshausen"], 0,
      "The wine turned out to be a revelation and Spatlese entered the language. The tale has been polished over two centuries, but the estate's records do show a late-picked wine from that harvest."),
    Q("Rheingau and Nahe",
      "Riesling covers most of the Rheingau, but one village at its western end has grown red wine on slate for centuries. Which grape?",
      ["Spatburgunder", "Dornfelder", "Trollinger", "Lemberger"], 0,
      "Assmannshausen sits where the Rhine turns north into its gorge and the soils change from quartzite and loess to slate. Its Spatburgunder is pale, savoury and quite unlike the riper Baden style."),
    Q("Rheingau and Nahe",
      "The English word hock, used for a century to mean Rhine wine of any kind, is a worn-down version of which Rheingau town's name?",
      ["Hochheim", "Hattenheim", "Hallgarten", "Geisenheim"], 0,
      "Hochheim sits apart from the rest of the Rheingau, on the river Main east of Wiesbaden. Queen Victoria's fondness for its wine did the rest, and the shortened name spread to cover everything German and white."),
    Q("Rheingau and Nahe",
      "Volcanic porphyry, slate, quartzite, sandstone and loam all surface within a few kilometres of one river valley south-west of Bingen. Which region?",
      ["Nahe", "Rheingau", "Mittelrhein", "Hessische Bergstrasse"], 0,
      "The Nahe cuts through an unusually broken piece of geology, which is why no two of its villages taste alike. Its Rieslings are conventionally placed between the Mosel's delicacy and the Rheingau's weight."),
    Q("Rheingau and Nahe",
      "One Nahe vineyard was terraced early in the twentieth century on the spoil of a worked-out copper mine and is now among the region's most celebrated. Which?",
      ["Schlossbockelheimer Kupfergrube", "Niederhauser Hermannshohle",
       "Dorsheimer Goldloch", "Traiser Bastei"], 0,
      "Kupfergrube simply means copper mine, and the terraces were cut into volcanic rock left behind by the workings. The wines have a smoky, mineral cast that has nothing to do with the vine."),

    # --------------------------------------- Rheinhessen and the Pfalz (6) ---
    Q("Rheinhessen and the Pfalz",
      "A steep, crumbling cliff of iron-stained red slate and sandstone drops straight to the Rhine at Nierstein and Nackenheim. What is that slope called?",
      ["The Roter Hang", "The Haardt", "The Kaiserstuhl", "The Wonnegau"], 0,
      "Rotliegend is the formation and Roter Hang, the red slope, is the name growers use. It carries Rheinhessen's finest Riesling sites, and almost all the rest of the region is far gentler ground."),
    Q("Rheinhessen and the Pfalz",
      "Westhofen and Dalsheim sit inland from the Rhine in southern Rheinhessen, in a district that became the centre of the region's dry-wine revival. Which district?",
      ["The Wonnegau", "The Roter Hang", "The Mittelhaardt", "The Ortenau"], 0,
      "Wonnegau means something close to the district of delight. Its limestone and clay gave a generation of younger growers the raw material for serious dry Riesling after decades of anonymous blending."),
    Q("Rheinhessen and the Pfalz",
      "Fig and almond trees grow among the vines along one German region's wine road, which is not what fifty degrees north would suggest. What makes that possible?",
      ["Hills to the west shelter the vineyards and cast a rain shadow over them",
       "The Rhine is at its widest here and stores enough heat to warm the air",
       "The soils are volcanic and radiate warmth through the night",
       "The vineyards sit high enough to stand above the frost line"], 0,
      "The Haardt is the northern continuation of the Vosges and wrings the rain out of the westerlies before they arrive. The Pfalz is one of the driest and warmest corners of Germany as a result."),
    Q("Rheinhessen and the Pfalz",
      "Growers in one Mittelhaardt village have carted crushed black volcanic rock onto their vineyards for generations. Which village, and to what end?",
      ["Forst, because the dark stone absorbs heat and warms sandy soil",
       "Deidesheim, because the stone raises the acidity of the soil",
       "Wachenheim, because the stone smothers weeds between the rows",
       "Ruppertsberg, because the stone opens up drainage in heavy clay"], 0,
      "Basalt was quarried from an outcrop above the village and spread across the vineyards below. Kirchenstuck, Jesuitengarten and Pechstein are the sites that made the practice famous."),
    Q("Rheinhessen and the Pfalz",
      "Two Bereiche divide the Pfalz along its length, one around Bad Durkheim and Forst and one running south toward the French border. What is the northern of the two generally called?",
      ["The Mittelhaardt", "The Sudliche Weinstrasse",
       "The Bergstrasse", "The Markgraflerland"], 0,
      "The Mittelhaardt holds the classic Riesling villages of Forst, Deidesheim, Ruppertsberg and Wachenheim. The Sudliche Weinstrasse to the south is warmer again, and leans toward the Pinot family and Dornfelder."),
    Q("Rheinhessen and the Pfalz",
      "A generation of growers took over family estates west of the Rhine from the 1990s and pulled a region famous for cheap semi-sweet blends round to dry, single-site Riesling. Which region?",
      ["Rheinhessen", "Mosel", "Franken", "Wurttemberg"], 0,
      "Rheinhessen carries more vineyard than any other German region, and for decades most of it went into Liebfraumilch. Lower yields, later picking and village and vineyard names on the label reversed that."),

    # ------------------------------------ Baden, Franken and the south (6) ---
    Q("Baden, Franken and the south",
      "An extinct volcano rising out of the Rhine plain, capped with terraced loess, records some of the highest temperatures in German viticulture. What is it called?",
      ["The Kaiserstuhl", "The Ortenau", "The Markgraflerland", "The Bodensee"], 0,
      "Volcanic rock underlies deep wind-blown loess on the Kaiserstuhl, and the combination holds heat remarkably well. Spatburgunder and Grauburgunder are what it is planted to."),
    Q("Baden, Franken and the south",
      "In the far south of Baden, near Basel, growers work a soft, neutral old variety that Switzerland calls Chasselas. What is its German name?",
      ["Gutedel", "Rulander", "Klingelberger", "Elbling"], 0,
      "Gutedel gives a low-acid wine drunk young and almost entirely locally, and the Markgraflerland is effectively its only German home. Klingelberger is the Ortenau's name for Riesling, and Rulander is Pinot Gris in a richer style."),
    Q("Baden, Franken and the south",
      "A squat, flattened flagon quite unlike any other German bottle marks the wine of one region. Which?",
      ["Franken", "Mosel", "Rheingau", "Wurttemberg"], 0,
      "The Bocksbeutel is protected for Franken and for two pockets of Baden, the Taubertal in the north and the Neuweier vineyards near Baden-Baden. It will not lie down in a rack and is instantly recognisable across a room, which is rather the point."),
    Q("Baden, Franken and the south",
      "Which grape is Franken's signature, bottled dry and showing an earthy, herbal, almost savoury cast?",
      ["Silvaner", "Riesling", "Muller-Thurgau", "Bacchus"], 0,
      "Silvaner ripens earlier than Riesling, which matters badly in Franken's short continental season, and it takes its character from limestone and gypsum marl. Franken finishes it dry almost without exception."),
    Q("Baden, Franken and the south",
      "Shell limestone laid down in a shallow tropical sea underlies the best vineyards around Wurzburg. What is that rock called?",
      ["Muschelkalk", "Buntsandstein", "Keuper", "Rotliegend"], 0,
      "Muschelkalk gives the taut, stony Silvaner of the Stein and its neighbours above the town. Keuper, a gypsum-rich marl, takes over further east around Iphofen and gives a broader, softer wine."),
    Q("Baden, Franken and the south",
      "Twelve of the thirteen Anbaugebiete sit in EU wine zone A and one sits in the warmer zone B. What does that difference change for the grower?",
      ["A lower ceiling on enrichment of the must in zone B",
       "A higher permitted yield per hectare in zone B",
       "Permission to irrigate an established vineyard in zone B",
       "A longer minimum ageing period before release in zone B"], 0,
      "Zone A allows enrichment of up to 3.0% vol and zone B only 2.0%, so the warmer zone may add less sugar before fermentation. Baden is the region concerned, and its warmth is exactly why the allowance is smaller."),

    # ------------------------------------------------- grape varieties (7) ---
    Q("Grape varieties",
      "A German white arrives with searing acidity, lime and green apple, a whiff of kerosene once it has age, and it mirrors its vineyard more faithfully than almost any grape. Which variety?",
      ["Riesling", "Silvaner", "Muller-Thurgau", "Weissburgunder"], 0,
      "Riesling ripens very late, which is why it needs the best slopes Germany has, and it holds acidity even when fully ripe. The petrol note comes from a compound that builds in bottle and is a marker of the grape rather than a fault."),
    Q("Grape varieties",
      "A crossing made at Geisenheim in 1882 ripens early, yields heavily and carries low acidity, and it once covered more German vineyard than any other variety. Which?",
      ["Muller-Thurgau", "Kerner", "Scheurebe", "Bacchus"], 0,
      "Hermann Muller crossed Riesling with what DNA analysis eventually identified as the table grape Madeleine Royale, not the Silvaner assumed for a century. It was meant to give Riesling character on lesser sites and delivered volume instead; bottled dry it is often labelled Rivaner."),
    Q("Grape varieties",
      "Grauburgunder and Rulander appear on German labels for one and the same grape. What separates the two names in practice?",
      ["Grauburgunder signals a dry style and Rulander a richer, sweeter one",
       "Grauburgunder is grown in the north and Rulander in the south",
       "Rulander is a modern crossing and Grauburgunder is not",
       "Rulander is always made sparkling"], 0,
      "Both are Pinot Gris. The split is convention rather than law, but a bottle marked Rulander is usually the fuller, sweeter interpretation and Grauburgunder the crisp dry one."),
    Q("Grape varieties",
      "Which German name should you look for on a label to find Pinot Noir?",
      ["Spatburgunder", "Grauburgunder", "Weissburgunder", "Trollinger"], 0,
      "Spat means late and the Burgunder suffix marks the Pinot family, so Grauburgunder is Pinot Gris and Weissburgunder Pinot Blanc. Spatburgunder is the most widely planted red variety in Germany."),
    Q("Grape varieties",
      "A German crossing bred in Wurttemberg in the 1950s was designed above all to put colour into pale red blends, and became a variety in its own right. Which?",
      ["Dornfelder", "Regent", "Portugieser", "Lemberger"], 0,
      "Dornfelder gives a dark, soft, plummy wine with little tannin, made both as an everyday red and, from lower yields, in a more ambitious barrel-aged style. It stands second only to Spatburgunder among Germany's red plantings."),
    Q("Grape varieties",
      "A dry German white shows quiet pear and green herbs, moderate acidity and a stony finish, and is the traditional partner for white asparagus. Which variety?",
      ["Silvaner", "Riesling", "Scheurebe", "Kerner"], 0,
      "Silvaner's softer acidity and mild aromatics leave the vegetable alone instead of fighting it, and Spargelzeit in May is when Germany drinks most of it. Riesling's acidity and Scheurebe's grapefruit both trample the dish."),
    Q("Grape varieties",
      "Which German crossing gives a pungent white smelling of grapefruit and blackcurrant, and is bottled sweet as readily as dry?",
      ["Scheurebe", "Kerner", "Bacchus", "Huxelrebe"], 0,
      "Scheurebe was bred in Rheinhessen from Riesling and a partner only identified much later, and its aromatics survive right up into Beerenauslese. Overcropped or underripe it smells frankly of cat, which is why it is planted less than it once was."),

    # --------------------------------------------- the Pradikat ladder (8) ---
    Q("The Pradikat ladder",
      "Two bottles of German Riesling both say Spatlese on the label; one is bone dry and one is sweet. What is that word actually recording?",
      ["The sugar in the grapes at harvest",
       "The sugar left in the finished wine",
       "The calendar date on which the fruit was picked",
       "The length of ageing before the wine was released"], 0,
      "Pradikat is a must weight, measured before fermentation begins. What becomes of that sugar afterwards is the winemaker's decision, so a Spatlese trocken and a sweet Spatlese start from the same place and end up somewhere different."),
    Q("The Pradikat ladder",
      "Put the rungs in order: which sequence runs from the lowest must weight upward?",
      ["Kabinett, Spatlese, Auslese, Beerenauslese, Trockenbeerenauslese",
       "Spatlese, Kabinett, Auslese, Trockenbeerenauslese, Beerenauslese",
       "Kabinett, Auslese, Spatlese, Beerenauslese, Trockenbeerenauslese",
       "Auslese, Spatlese, Kabinett, Beerenauslese, Trockenbeerenauslese"], 0,
      "Each rung demands more sugar in the fruit than the one below it, and the minimum figures differ by region and by grape. Eiswein sits alongside Beerenauslese in must weight, with Trockenbeerenauslese at the top."),
    Q("The Pradikat ladder",
      "German must weight is read on a nineteenth-century scale that measures the density of the juice against water. What is that scale called?",
      ["Oechsle", "Baume", "Brix", "KMW"], 0,
      "One degree Oechsle is the number of grams by which a litre of must outweighs a litre of water. Baume is the French scale, Brix the American and KMW the Austrian, and all four are reading the same thing."),
    Q("The Pradikat ladder",
      "Adding sugar to the must before fermentation is allowed for German Qualitatswein but forbidden outright at one level. Which?",
      ["Pradikatswein", "Landwein", "Deutscher Wein", "Deutscher Sekt"], 0,
      "The entire point of the ladder is that the sugar came out of the vineyard, so enrichment would make the claim meaningless. Lower down the pyramid, where no ripeness claim is being made, it is permitted."),
    Q("The Pradikat ladder",
      "Frozen fruit is picked before dawn on a January morning and pressed while still solid. What is being separated from what?",
      ["Water held as ice crystals, from concentrated sugary juice",
       "Sugar from acid, with the acid left behind in the ice",
       "Skins from pulp, which the cold makes easier to part",
       "Yeast from the must, which the cold kills off"], 0,
      "The ice stays behind in the press and only the concentrated liquid runs out. German rules set a minimum of minus seven degrees Celsius at picking, and the wine keeps ferocious acidity alongside its sugar."),
    Q("The Pradikat ladder",
      "Eiswein and Beerenauslese reach comparable must weights, yet one condition sets Eiswein apart. Which?",
      ["Its grapes must be healthy and free of noble rot, and frozen on the vine",
       "Its grapes must be picked before the general harvest starts",
       "It must be fermented out to complete dryness",
       "It must spend three years in cask before release"], 0,
      "Botrytis is what concentrates a Beerenauslese; freezing is what concentrates an Eiswein, and rot would muddy the clean piercing fruit that is the whole appeal of the style. The gamble is that a hard enough frost may never arrive."),
    Q("The Pradikat ladder",
      "Pickers go through the vineyard taking only the ripest bunches, some of them touched by noble rot. Which Pradikat does that describe?",
      ["Auslese", "Kabinett", "Spatlese", "Trockenbeerenauslese"], 0,
      "Auslese means selected, and at this rung the selection is made bunch by bunch. Beerenauslese goes further and picks individual berries, and Trockenbeerenauslese takes only the shrivelled ones."),
    Q("The Pradikat ladder",
      "German wine law stacks four broad quality tiers. Which sequence runs from the bottom upward?",
      ["Deutscher Wein, Landwein, Qualitatswein, Pradikatswein",
       "Landwein, Deutscher Wein, Pradikatswein, Qualitatswein",
       "Qualitatswein, Landwein, Pradikatswein, Deutscher Wein",
       "Deutscher Wein, Qualitatswein, Landwein, Pradikatswein"], 0,
      "The two lower tiers are table and country wine. The two upper ones must name an Anbaugebiet and pass an official tasting and analysis, and Pradikatswein is then split by must weight into the six familiar rungs."),

    # ------------------------------- labels, sweetness and the VDP (7) -------
    Q("Labels, sweetness and the VDP",
      "A German Riesling labelled trocken may legally carry up to nine grams of residual sugar rather than the usual four. What has to be true for that to be allowed?",
      ["The total acidity must be no more than two grams below the residual sugar",
       "The wine must come from a classified single vineyard",
       "The alcohol must exceed thirteen percent",
       "The wine must be at least three years old"], 0,
      "The allowance exists because acidity masks sugar on the palate. Nine grams in a taut, high-acid Riesling still tastes dry, where the same sugar in a soft low-acid wine would not."),
    Q("Labels, sweetness and the VDP",
      "Many German estates now put a word on their off-dry bottles that carries no legal meaning whatever, in preference to halbtrocken. Which word?",
      ["Feinherb", "Lieblich", "Suss", "Edelsuss"], 0,
      "Halbtrocken is capped at twelve grams of residual sugar, or eighteen where the sugar sits no more than ten grams above the total acidity, and it sounds like a compromise, so growers reached for something warmer. Feinherb is undefined and therefore covers a wider range, while lieblich and suss are the legal terms for genuinely sweet wine."),
    Q("Labels, sweetness and the VDP",
      "Two Mosel labels read Piesporter Goldtropfchen and Piesporter Michelsberg, and the two look identical in form. What separates them?",
      ["Goldtropfchen is one vineyard, Michelsberg many",
       "Goldtropfchen is a collective name and Michelsberg a single vineyard",
       "One names a village and the other names a district",
       "One denotes a dry wine and the other a sweet one"], 0,
      "An Einzellage is one delimited site; a Grosslage can spread across thousands of hectares and many villages, and nothing in the pre-reform wording tells them apart. The 2021 law now requires a Grosslage name to be prefixed Region, phased in toward the 2026 vintage, but older bottles on shelves and lists still carry the ambiguous form."),
    Q("Labels, sweetness and the VDP",
      "Thousands of small German vineyard names were abolished and merged by one piece of legislation, which also invented the collective site. Which law?",
      ["The German Wine Law of 1971", "The German Wine Law of 1930",
       "The EU wine market reform of 2008", "The VDP statutes of 1910"], 0,
      "The 1971 law cut some thirty thousand site names down to around two and a half thousand Einzellagen and imposed a minimum size on them. It also created the Grosslage, which let a bulk blend borrow a famous village's name."),
    Q("Labels, sweetness and the VDP",
      "A semi-sweet German white sold under brand names for a generation takes its name from a church in Worms. Which wine?",
      ["Liebfraumilch", "Piesporter Michelsberg",
       "Zeller Schwarze Katz", "Kroever Nacktarsch"], 0,
      "The Liebfrauenkirche gave its name to a Qualitatswein blend carrying at least eighteen grams of residual sugar and drawn from Rheinhessen, the Pfalz, the Nahe or the Rheingau. Its collapse in reputation dragged German wine down with it for thirty years."),
    Q("Labels, sweetness and the VDP",
      "A dry wine from a member estate's top classified site carries the letters GG embossed in the glass, and an eagle bearing a grape cluster on the capsule. What is that marking?",
      ["Grosses Gewachs, the mark of a growers' association",
       "A legal German quality tier ranking above Pradikatswein",
       "A guarantee that the fruit was affected by noble rot",
       "A promise of at least ten years of bottle age before release"], 0,
      "The VDP is an association of growers and its rulebook is stricter than the law, capping yields, requiring hand harvest and holding the wine back for a later release. The 2021 wine law has since written Grosses Gewachs into German law as well, with the qualifying rules set region by region, but the embossed bottle and the eagle capsule remain the VDP's own. Grosses Gewachs is always dry; a sweet wine off the same site is labelled with its Pradikat instead."),
    Q("Labels, sweetness and the VDP",
      "The VDP grades its members' wines on a four-step pyramid modelled on Burgundy. What sits at the top of it?",
      ["VDP.Grosse Lage", "VDP.Erste Lage", "VDP.Ortswein", "VDP.Gutswein"], 0,
      "Gutswein is the estate wine and Ortswein the village wine, with the two site tiers above them. Grosse Lage answers to a Grand Cru, and it is where Grosses Gewachs comes from."),
]
