"""Rank I rewrite - History & Figures (50 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing.

The running order is a single line drawn through time, because that is the one
thing this category can give a student that no regional chapter can: an amphora
on a wrecked ship, then the abbeys that kept the record, then the trade treaties
that decided what England drank, the strong English bottle, the chemists, the
first men to draw a boundary on a map, the three American plagues and the
American cure, the revolts and prohibitions of the twentieth century, and
finally the institutions and the tasting that reordered the modern market. A
student who works through it in order ends up able to place any fact in a
century, which is the whole competency.

Every regional category owns its own history in passing, so this one takes the
view they cannot: the person and the event rather than the estate or the
appellation. Where a region already asks how its own ranking works, this asks who
wanted it and what problem it was answering. Producers & Icons owns houses, so
where a house and a person are entangled the question is keyed on the person.

Every stem opener is distinct, no construction in lib.BANNED_TEMPLATES appears,
and the stem leads with a scene, a date, an object or a symptom so that the name
being tested arrives as the answer rather than as the first clause. Option length
was varied deliberately from the start: some keys are the longest option in their
question and some the shortest.
"""

from lib import Q

CAT = "History & Figures"
SLUG = "r1-history-figures"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("The ancient world", 5),
    ("Monasteries and the medieval vineyard", 5),
    ("Trade, treaties and travellers", 6),
    ("The bottle, the cork and the sparkle", 5),
    ("Science enters the cellar", 5),
    ("Drawing boundaries, ranking vineyards", 5),
    ("The vine plagues and the American cure", 6),
    ("War, prohibition and the growers' revolt", 5),
    ("Institutions of the modern trade", 4),
    ("The Judgment of Paris and after", 4),
]

BANK = [
    # -------------------------------------------------- the ancient world (5) --
    Q("The ancient world",
      "Divers working a Roman wreck bring up hundreds of tall clay jars with pointed bases, sealed at the neck with pitch and stamped with a maker's mark. What are these wine containers called?",
      ["Amphorae", "Demijohns", "Puncheons", "Wineskins"], 0,
      "The pointed base let a jar be stood upright in sand or stacked in a ship's hold, and the pitch lining sealed clay that would otherwise have leaked. The stamps on the handles and rims are how the ancient wine trade is traced today, since a jar found in Britain can be matched to the kiln that made it."),
    Q("The ancient world",
      "Seafaring merchants out of the Levantine coast carried vine cuttings west to Carthage, Sicily and the coast of Iberia long before Rome had a fleet of its own. Which people were they?",
      ["The Phoenicians", "The Etruscans", "The Vandals", "The Normans"], 0,
      "Their trading posts around the western Mediterranean give the first evidence of vines in several countries that now build whole economies on wine. Greek colonists followed and planted the south of Italy so thoroughly that it was known to the ancient world as the land of vines."),
    Q("The ancient world",
      "Roman traders working north of the Alps found the tribes there using a container of bent staves and hoops, lighter than clay and far harder to break on a cart. Who is credited with the wooden barrel?",
      ["The Celtic peoples of Gaul", "Greek colonists in southern Italy",
       "The Egyptians of the Nile delta", "The Norse"], 0,
      "Wood could be rolled by one man, repaired, and refilled for years, and it survived roads that would have destroyed a cargo of jars. Rome adopted it for bulk movement across the western provinces, and the trade has used a hooped wooden vessel ever since."),
    Q("The ancient world",
      "An emperor ordered provincial vineyards cut back in AD 92, wanting grain planted in their place and provincial wine kept away from Rome's own market. Which emperor?",
      ["Domitian", "Augustus", "Constantine", "Nero"], 0,
      "The edict is usually read as protection for Italian growers dressed up as a grain policy, and it was widely ignored outside Italy. Probus is credited with lifting the restriction nearly two centuries later, after which planting in Gaul, Spain and the Rhineland expanded without hindrance."),
    Q("The ancient world",
      "At the drinking parties of one ancient civilisation the wine was mixed with water in a communal bowl before it went round, and taking it neat was thought the habit of barbarians. Which civilisation?",
      ["The Greeks", "The Egyptians", "The Persians", "The Etruscans"], 0,
      "The bowl was a krater and the proportions were argued over as a question of manners, with something like one part wine to three of water counted as civilised. Rome inherited the custom, which is why ancient descriptions of drinking bear so little relation to how a glass is poured now."),

    # ------------------------------ monasteries and the medieval vineyard (5) --
    Q("Monasteries and the medieval vineyard",
      "Vine growing survived the collapse of the western empire and pushed further north than Rome had ever taken it, carried by the religious houses. Which requirement kept it going?",
      ["Wine was needed for the celebration of the Mass",
       "Church law obliged every abbey to be self-sufficient in all crops",
       "Wine was the only lawful form in which a tithe could be paid",
       "Monks were forbidden by their rule to drink water"], 0,
      "A church without wine could not say Mass, so every religious house had reason to secure a supply it controlled rather than buying one. That is why vineyards appear in medieval England, in Poland and along the Baltic, at latitudes where the economics alone would never have justified them."),
    Q("Monasteries and the medieval vineyard",
      "A sixth-century monastic rule granted each monk a daily measure of wine rather than forbidding it, and the houses that adopted it became vineyard owners across Europe. Whose rule was it?",
      ["Benedict of Nursia", "Bernard of Clairvaux", "Augustine of Hippo",
       "Francis of Assisi"], 0,
      "The rule concedes that wine is no drink for monks and then allows a daily ration anyway, on the grounds that the times will not bear the stricter line. That concession shaped a thousand years of European agriculture, and Bernard of Clairvaux belongs to the reforming order that grew out of it five centuries later."),
    Q("Monasteries and the medieval vineyard",
      "Records of which parcels ripened first and which gave the best wine accumulated in monastic hands over centuries and almost nowhere else. Which feature of those houses accounts for it?",
      ["They were literate corporate bodies that outlived any individual owner",
       "They alone were permitted to own vineyards",
       "They held the only presses",
       "Their wine was exempt from tax"], 0,
      "A monastery does not divide its land among heirs and does not forget what the previous generation learned, so observations could be written down and compared harvest after harvest. Secular holdings changed hands, were split and were fought over, and whatever they had learned went with them."),
    Q("Monasteries and the medieval vineyard",
      "England had working vineyards attached to its abbeys until a sixteenth-century king broke with Rome and closed them, and commercial planting there did not resume in earnest for four centuries. Which event was that?",
      ["The Dissolution of the Monasteries", "The Norman Conquest of 1066",
       "The enclosure of the common fields", "The English Civil War"], 0,
      "Henry VIII's break with Rome removed both the institutions and the guaranteed market for their wine at a stroke. A cooling climate over the following centuries finished the job, and English vineyards returned as a serious business only in the later twentieth century."),
    Q("Monasteries and the medieval vineyard",
      "Vineyards belonging to the French church were seized in the 1790s and auctioned to whoever could pay, which is how a great deal of the country's finest land first reached private hands. Which upheaval put it on the market?",
      ["The French Revolution", "The Hundred Years War", "The Franco-Prussian War",
       "The reign of Louis XIV"], 0,
      "The confiscated estates were sold as biens nationaux, national property, and the buyers ranged from Paris merchants to the growers who had worked the ground for the monks. Several celebrated vineyards passed out of church ownership within a few years of one another, and none has returned."),

    # ----------------------------------- trade, treaties and travellers (6) --
    Q("Trade, treaties and travellers",
      "A marriage in 1152 carried the duchy of Aquitaine to the future king of England, and for three hundred years afterwards Bordeaux shipped most of its wine to London. Whose marriage was it?",
      ["Eleanor of Aquitaine to Henry Plantagenet",
       "Catherine de Medici to Henry II of France",
       "Anne of Brittany to Charles VIII",
       "Mary of Guise to James V of Scotland"], 0,
      "Gascony became English territory and its wine entered England at preferential duty, which built the region's export trade centuries before anyone thought of ranking its estates. The political connection ended with the English defeat at Castillon in 1453; the London market for the wine never did."),
    Q("Trade, treaties and travellers",
      "English woollens were let into Portugal in 1703, and Portuguese wine came into England at a third less duty than French wine paid. Which treaty struck that bargain?",
      ["The Methuen Treaty", "The Treaty of Utrecht", "The Treaty of Tordesillas",
       "The Treaty of Rome"], 0,
      "It was signed while England was at war with France, so the gap in duty was as much politics as commerce, and the preference shaped British drinking for well over a century, until the duties on French and Portuguese wine were equalised in 1831 and the treaty lapsed a few years later. Generations of British drinkers grew up on Portuguese wine because it was the cheap option rather than the fashionable one."),
    Q("Trade, treaties and travellers",
      "Engineers from the Low Countries were hired in the seventeenth century to cut drainage channels through the marshes north of Bordeaux, uncovering the gravel banks that now carry its best vineyards. Which people did that work?",
      ["The Dutch", "The Flemish weavers of Bruges", "The Genoese",
       "The Hanseatic merchants of Lubeck"], 0,
      "They had drained their own country and sold the technique across northern Europe, and the channels they cut still drain the peninsula today. Before that work the region's reputation rested on the gravel south of the city, which had never needed draining."),
    Q("Trade, treaties and travellers",
      "A London diarist recorded in 1663 that he had drunk a French wine with a particular good taste of its own, and named the property rather than the region it came from. Whose diary was it?",
      ["Samuel Pepys", "John Evelyn", "Daniel Defoe", "James Boswell"], 0,
      "The wine came from Haut-Brion, and the entry marks the moment a single Bordeaux property began to be sold on its own name at a premium over its neighbours. Selling an estate rather than a district is the commercial idea everything later in fine wine is built on."),
    Q("Trade, treaties and travellers",
      "War with France in the 1690s shut French wine out of England behind punitive duty, and London merchants went looking up the Douro for something to sell instead. Which trade grew out of that search?",
      ["The port trade", "The sherry trade", "The claret trade", "The madeira trade"], 0,
      "Douro wine was rough and did not travel well, which is precisely why British firms established themselves on the river to solve the problem rather than simply buying from a broker. It is the reason so many of the great shipping names there are English or Scottish to this day."),
    Q("Trade, treaties and travellers",
      "An American minister to France spent the spring of 1787 touring vineyards from Burgundy to Bordeaux, took meticulous notes on owners and prices, and afterwards ordered his wine direct from the properties. Who was he?",
      ["Thomas Jefferson", "Benjamin Franklin", "John Adams", "Alexander Hamilton"], 0,
      "He wanted to know which slope made which wine and recorded what he found as a surveyor would. Buying direct from a property instead of through a merchant was unusual then, and it is the reason bottles claiming to bear his initials have caused so much argument among collectors since."),

    # ----------------------------- the bottle, the cork and the sparkle (5) --
    Q("The bottle, the cork and the sparkle",
      "Popular history credits a Benedictine cellarer at Hautvillers with inventing sparkling Champagne. What did he actually spend his career doing?",
      ["Blending across many parcels, and pressing black grapes for clear white wine",
       "Discovering the second fermentation and learning to provoke it",
       "Devising the wire cage that holds a cork down",
       "Inventing the riddling rack"], 0,
      "Bubbles were a fault in his day and his cellars worked hard to prevent them, since a bottle that refermented was as likely to burst as to please anyone. His lasting achievements were assemblage, building a wine from fruit grown on many different sites, and pressing dark-skinned grapes fast enough to keep the juice white."),
    Q("The bottle, the cork and the sparkle",
      "Coal-fired furnaces in seventeenth-century England turned out glass darker, thicker and far stronger than the wood-fired French kind, which is what first made a wine under pressure worth keeping. Which Englishman is credited with the design?",
      ["Sir Kenelm Digby", "Christopher Merret", "Robert Boyle", "Michael Faraday"], 0,
      "England had banned wood in glass furnaces to preserve timber for the navy, so its glassmakers had already moved to coal and were reaching higher temperatures than anyone else. A bottle of the softer continental glass burst readily under pressure, and cellars were still losing serious fractions of a vintage to breakage well into the nineteenth century."),
    Q("The bottle, the cork and the sparkle",
      "A paper read to the Royal Society in 1662 described putting sugar into finished wine so that it would come out brisk and sparkling, decades before the practice is recorded in France. Who presented it?",
      ["Christopher Merret", "Dom Pierre Perignon", "Sir Kenelm Digby",
       "Antoine Lavoisier"], 0,
      "Merret was a physician and an early fellow of the society, and his note is the first written description of provoking a second fermentation on purpose. It is why the English claim on the technique is taken seriously by historians, whatever the marketing of the region that perfected it may suggest."),
    Q("The bottle, the cork and the sparkle",
      "Bottles were blown squat and onion-shaped until the eighteenth century, when glassmakers began drawing them out into straight-sided cylinders. What did the new shape make possible?",
      ["Storing them on their sides to age",
       "Filling and corking them by machine at speed",
       "Withstanding far higher internal pressure",
       "Cheaper glass"], 0,
      "A cylinder stacks, and a cork kept wet by the wine does not shrink and let air past. The idea of a vintage worth keeping for years, and of a cellar as something with a value, follows directly from a change in the shape of the glass."),
    Q("The bottle, the cork and the sparkle",
      "A young widow took over her husband's Champagne house in 1805, ran it for more than half a century, and got a shipment through to Russia in 1814 ahead of every competitor. Who was she?",
      ["Barbe-Nicole Clicquot Ponsardin", "Louise Pommery", "Lily Bollinger",
       "Camille Olry-Roederer"], 0,
      "She inherited a small merchant business in her twenties and turned it into an export house at a moment when war had closed most of Europe to trade. Champagne has produced a striking number of such figures, which is why the French word for widow appears on more than one label in the region."),

    # ---------------------------------------- science enters the cellar (5) --
    Q("Science enters the cellar",
      "Adding sugar to must before fermentation, so that a thin year finishes stronger, carries the name of the French chemist and government minister who publicised it around 1801. Who?",
      ["Jean-Antoine Chaptal", "Joseph Louis Gay-Lussac", "Antoine Lavoisier",
       "Louis Pasteur"], 0,
      "Chaptal was Napoleon's minister of the interior and wrote a treatise on winemaking that put the practice in front of every grower in France. He did not invent it, and his real contribution was as much the spread of careful cellar method as the sugar he is remembered for."),
    Q("Science enters the cellar",
      "Fermentation was taken to be a spontaneous chemical decay until a French chemist showed in the 1860s that living micro-organisms do the work. Who showed it?",
      ["Louis Pasteur", "Justus von Liebig", "Antoine Lavoisier", "Emile Peynaud"], 0,
      "He had been asked to find out why so much French wine was spoiling, and found that particular organisms produced particular faults, which is the beginning of microbiology as much as of modern winemaking. Gentle heating to kill those organisms was worked out for wine long before it was applied to milk."),
    Q("Science enters the cellar",
      "An equation published in 1810 set out the proportions in which sugar becomes alcohol and carbon dioxide, and every calculation of potential alcohol still rests on it. Whose equation?",
      ["Joseph Louis Gay-Lussac's", "Antoine Laurent de Lavoisier's",
       "Louis Pasteur's", "Jean-Antoine Chaptal's"], 0,
      "Roughly speaking a given weight of sugar yields about half its weight in alcohol, which is what lets a must weight be read off as a probable percentage before fermentation begins. Lavoisier had already shown that nothing is lost in the process; this put numbers to it."),
    Q("Science enters the cellar",
      "A physician was commissioned by the French government in the 1860s to survey the vineyards of the entire country, and the cane-pruning system he recommended now carries his name worldwide. Who was he?",
      ["Jules Guyot", "Alexis Millardet", "Jules-Emile Planchon", "Pierre Viala"], 0,
      "His reports set down what every region grew and how it was pruned at a moment when nobody had written it all in one place. Training a vine to one or two canes off a low trunk was his prescription for a regular crop, and it became the default across France and far beyond it."),
    Q("Science enters the cellar",
      "From the 1950s onward a Bordeaux oenologist pressed estates to pick on ripeness rather than the calendar, discard rotten fruit and control the malolactic, and the region's difficult vintages stopped being undrinkable. Who was he?",
      ["Emile Peynaud", "Louis Pasteur", "Jules Guyot", "Alexis Lichine"], 0,
      "He consulted for dozens of properties and taught two generations at the university in his city, and his insistence on sound fruit and clean cellars is now so ordinary that it is hard to see as an argument. It was one: growers had simply accepted that a wet year produced bad wine."),

    # ------------------------------ drawing boundaries, ranking vineyards (5) --
    Q("Drawing boundaries, ranking vineyards",
      "An edict of 1716 fixed the boundaries of four Tuscan wine zones and set up a body to police the use of their names in trade. Which ruler issued it?",
      ["Cosimo III de' Medici", "The Marquis of Pombal", "Napoleon III of France",
       "Charles VI, Holy Roman Emperor"], 0,
      "Chianti, Carmignano, Pomino and Val d'Arno di Sopra were the four, and the edict is usually cited as the earliest attempt anywhere to protect wine names by drawing a line on a map. Naming the ground and then controlling who may use the word is the whole idea appellation law was later built on."),
    Q("Drawing boundaries, ranking vineyards",
      "Eighteenth-century governments in Tuscany, Hungary and Portugal all drew boundaries around wine regions within a few decades of one another, and for the same commercial reason. What was it?",
      ["Wine from elsewhere was sold under a famous name",
       "Growers had planted far more vines than the market could absorb",
       "Duty on wine was being evaded at the ports",
       "The church claimed a tithe on every harvest"], 0,
      "A name that sells is a name worth counterfeiting, and by the eighteenth century the famous ones were being stuck on anything that would pour. Every later system, from the French appellations to the European register, answers the same problem with the same two moves: draw the boundary, then control the word."),
    Q("Drawing boundaries, ranking vineyards",
      "A Tuscan baron who had served briefly as prime minister of the newly united Italy set down a recipe for his region's red wine in 1872, and growers followed it for a century afterwards. Who was he?",
      ["Bettino Ricasoli", "Camillo Benso di Cavour", "Giuseppe Garibaldi",
       "Vittorio Emanuele II"], 0,
      "He experimented at his own estate for decades before publishing, and his prescription of one dominant black grape supported by another is the ancestor of the rules that govern the zone now. Cavour was pushing comparable work in Piedmont in the same decades, hiring a cellar master who turned Barolo from a sweetish wine into a dry one."),
    Q("Drawing boundaries, ranking vineyards",
      "Champagne growers rioted in 1911, burning cellars in Ay and emptying vats into the street while troops were rushed in by rail. What had provoked them?",
      ["Merchants were buying grapes from outside the region",
       "A new duty was imposed on every bottle shipped",
       "An order required every vine to be grafted onto American stock",
       "Growers were forbidden to sell to anyone but the cooperative"], 0,
      "The vineyard had been cut back by disease while sales were rising, so wine from far outside the district was being blended in and sold under the region's name. A boundary had been drawn in law in 1908 and fought over from the day it appeared, the Aube demanding entry and the Marne resisting, and the riots bought only a compromise second zone; the question was not settled until 1927."),
    Q("Drawing boundaries, ranking vineyards",
      "Growers around one southern Rhone village wrote their own production rules in 1923 and went to court to enforce them, and the lawyer and grower who led them is usually called the father of the French appellation system. Who was he?",
      ["Baron Le Roy de Boiseaumarie", "Joseph Capus", "Jean-Antoine Chaptal",
       "Louis Pasteur"], 0,
      "His charter did what no earlier boundary had managed: it settled not only where the wine could come from but which varieties were allowed, how ripe the fruit had to be and what would be thrown out. Courts upheld it, and a decade later the same architecture was applied to the whole country."),

    # ----------------------------- the vine plagues and the american cure (6) --
    Q("The vine plagues and the American cure",
      "The first of the American afflictions reached Europe in the 1840s, greying the leaves and splitting the berries, and growers learned to beat it by dusting the vines with sulphur. Which disease was it?",
      ["Oidium", "Downy mildew, or peronospora", "Black rot", "Botrytis bunch rot"], 0,
      "Powdery mildew is the English name for the same fungus, and it grows on the surface of the plant, which is exactly why a surface dusting defeats it. Sulphur remains the standard treatment and is permitted in organic viticulture, so the nineteenth-century answer is still the one in use."),
    Q("The vine plagues and the American cure",
      "Dying vines across the Midi in the 1860s baffled everyone until a botanist from Montpellier dug beside a failing plant rather than under it and found a yellow aphid on the roots. Who was he?",
      ["Jules-Emile Planchon", "Alexis Millardet", "Charles Valentine Riley",
       "Pierre Viala"], 0,
      "Digging at the edge of the damage was the trick, since the insects abandon a vine once it is finished and leave nothing to find. He named the louse and then crossed to the United States to see how American vines lived with it, and what he learned there is the basis of the answer still used."),
    Q("The vine plagues and the American cure",
      "France decorated a Texan nurseryman in 1888 for the vine material he shipped across the Atlantic and for his advice on matching it to different soils. Who was he?",
      ["Thomas Volney Munson", "Charles Valentine Riley", "Ephraim Wales Bull",
       "Agoston Haraszthy"], 0,
      "The award was the Chevalier du Merite Agricole, and he earned it by knowing the wild American species better than anyone alive. That mattered because a vine that shrugs off the louse can still turn yellow and die in chalky ground, so matching the species to the soil, rather than merely finding something resistant, is what made the cure work in practice."),
    Q("The vine plagues and the American cure",
      "Production fell so far during the crisis that cellars were topped up with raisins, sugar and water, and in 1889 the French state answered with a statute. What did that law do?",
      ["It defined wine as the product of fermented fresh grapes alone",
       "It banned the import of American vine material",
       "It fixed a minimum price for a hectolitre",
       "It created the appellation system"], 0,
      "Watering, sugaring and fermenting imported raisins had all become normal, because the shortage had made them extremely profitable. Fixing what the word wine means is the necessary first move before any origin rule can mean anything, and France took it under the pressure of fraud rather than out of principle."),
    Q("The vine plagues and the American cure",
      "Vines along a Medoc roadside had been daubed with a conspicuous paste to stop passers-by helping themselves, and in 1882 a botanist noticed that those vines alone had escaped the new mildew. Who followed the observation up?",
      ["Alexis Millardet", "Jules-Emile Planchon", "Louis Pasteur", "Jules Guyot"], 0,
      "The mixture had been made up out of whatever was in the farm shed, and it proved to be the first effective fungicide against downy mildew. It still carries the name of the region where it was noticed, and vineyards across Europe turned blue-green every summer for the century that followed."),
    Q("The vine plagues and the American cure",
      "Live plants could not survive a long sea voyage until a sealed glazed case was devised in the 1830s, and within a few decades three American vine diseases had crossed to Europe. What was that case called?",
      ["The Wardian case", "The glasshouse cloche", "The vasculum", "The cold frame"], 0,
      "It is a closed box of glass in which a plant recycles its own moisture, and it transformed the movement of plants around the empires of the nineteenth century. Faster steamships did the rest: a pest that starved on a six-week crossing arrived alive on a two-week one."),

    # -------------------------- war, prohibition and the growers' revolt (5) --
    Q("War, prohibition and the growers' revolt",
      "Hundreds of thousands of growers marched through the towns of the French Midi in the summer of 1907, and a regiment sent to keep order mutinied and joined them. What had brought them out?",
      ["Fraudulent wine had collapsed the price of their own",
       "A new land tax on every planted hectare in the south",
       "An order requiring every vine to be grafted",
       "The closure of their main export route"], 0,
      "Sugared and watered wine, together with cheap imports from across the Mediterranean, had flooded the market just as the vineyard recovered from the louse. The state answered with laws against fraud and with the first obligation on growers to declare their harvest, which is the ancestor of every modern production record."),
    Q("War, prohibition and the growers' revolt",
      "A single-issue pressure group worked seat by seat through American state legislatures, backing any candidate who would vote dry and punishing any who would not. Which group did most to write national prohibition into the constitution?",
      ["The Anti-Saloon League", "The Woman's Christian Temperance Union",
       "The American Temperance Society", "The Prohibition Party"], 0,
      "Endorsing dry candidates of either party, and never running its own, made it the model for modern single-issue lobbying. The Woman's Christian Temperance Union had been building the moral case since 1874, close to half a century by the time the ban passed, but the legislative machinery belonged to the league."),
    Q("War, prohibition and the growers' revolt",
      "The constitutional ban needed a statute to say what counted as an intoxicating drink, and the statute drew the line at half of one percent alcohol. What is that statute called?",
      ["The Volstead Act", "The Harrison Act", "The Webb-Kenyon Act", "The Mann Act"], 0,
      "Half a percent catches ordinary beer and cider comfortably, which is why so much of the trade closed rather than trying to reformulate around it. The same figure survives in American law as the threshold below which a drink may be sold as non-alcoholic."),
    Q("War, prohibition and the growers' revolt",
      "Repeal came in 1933, and it had to be done the way the ban had been imposed, by amending the constitution a second time. Which amendment repealed it?",
      ["The Twenty-first", "The Eighteenth", "The Nineteenth", "The Twenty-second"], 0,
      "The Eighteenth had imposed prohibition, and the Twenty-first is the only amendment ever passed purely to undo another one. It handed control of alcohol back to the individual states, which is why drinks law in the United States still changes sharply at a state line."),
    Q("War, prohibition and the growers' revolt",
      "A tiny French crop, cut back by a hard spring frost and then ripened through a hot dry summer, was picked in the year the war in Europe ended. Which vintage is still spoken of as one of the century's greatest?",
      ["1945", "1918", "1929", "1963"], 0,
      "Frost in May reduced the crop to a fraction of a normal year, and what survived was small-berried, thick-skinned and concentrated. Bottles from that harvest were still showing well half a century later, which is how a year becomes a byword rather than merely a good vintage."),

    # ------------------------------------ institutions of the modern trade (4) --
    Q("Institutions of the modern trade",
      "An intergovernmental body founded in Paris in 1924 gathers the world's vineyard and harvest statistics and writes the technical standards that national wine laws borrow from. Which body?",
      ["The OIV", "The World Trade Organisation",
       "The Food and Agriculture Organisation of the United Nations",
       "The European Commission"], 0,
      "Its name in full is the International Organisation of Vine and Wine, and it grew out of the same fraud crisis that forced countries to agree what words like wine and vineyard actually meant. Its analytical methods and category definitions are written into the law of many countries that are not even members."),
    Q("Institutions of the modern trade",
      "Burgundian growers sold their wine in cask to merchants until the 1930s, when a French wine writer and an American importer began persuading them to do something else. What was it?",
      ["Bottle their own wine at the property",
       "Sell only through the local cooperative",
       "Blend across several villages before selling",
       "Sell their grapes rather than their wine"], 0,
      "The pair were hunting for wine that tasted of one particular place, and concluded that the only way to keep it that way was to have it bottled where it was made. Growers became names in their own right as a result, and the modern market in single-grower Burgundy dates from that decade."),
    Q("Institutions of the modern trade",
      "A London examining body set up by the wine trade in 1955 awards a qualification whose holders may put two letters after their names. Which body is it?",
      ["The Institute of Masters of Wine", "The Court of Master Sommeliers",
       "The Wine and Spirit Education Trust", "The Worshipful Company of Vintners"], 0,
      "Its examination covers theory, blind tasting and a research paper, and it was opened beyond the British trade in the 1980s. It is an examining institute rather than a trade association, which is much of why the qualification travels as well as it does."),
    Q("Institutions of the modern trade",
      "An examining body formally established in London in 1977 tests candidates on restaurant service and salesmanship as well as on blind tasting and theory. Which is it?",
      ["The Court of Master Sommeliers", "The Institute of Masters of Wine",
       "The Guild of Sommeliers", "The Chaine des Rotisseurs"], 0,
      "Its examination is built around what actually happens at the table, under the clock, in front of a guest. That focus is what separates it from the trade and production qualifications, and it is why its title is the one used on a restaurant floor."),

    # ------------------------------------- the judgment of paris and after (4) --
    Q("The Judgment of Paris and after",
      "A blind tasting held in Paris in 1976, judged entirely by French palates, put Californian wines top in both the red and the white flight. What is that event now called?",
      ["The Judgment of Paris", "The Great Claret Trial", "The Paris Exposition",
       "The Vinexpo Verdict"], 0,
      "The name is a joke on the Greek myth in which Paris is made to award a golden apple to one of three goddesses. It stuck because a journalist happened to be in the room and reported the result abroad, and because no French panel had ever ranked New World wine above its own."),
    Q("The Judgment of Paris and after",
      "Two flights were poured at the 1976 Paris tasting, one red and one white, and each set Californian bottles against French ones made from the same principal grape. Which pair of grapes was used?",
      ["Cabernet Sauvignon and Chardonnay", "Pinot Noir and Riesling",
       "Merlot and Sauvignon Blanc", "Syrah and Chenin Blanc"], 0,
      "The reds went up against classed-growth Bordeaux and the whites against white Burgundy, so both flights were chosen where California was working with the same varieties as the benchmark. That choice is why the outcome was read as a like-for-like comparison rather than a curiosity."),
    Q("The Judgment of Paris and after",
      "The reds from the 1976 Paris line-up were opened again thirty years later, on the widely held assumption that the Californian bottles would long since have collapsed. What happened?",
      ["The Californians again finished ahead", "The Bordeaux took the top five places",
       "Almost every bottle was undrinkable", "The judges declared the result a tie"], 0,
      "They had aged perfectly well, and a Californian red again topped the ranking. The original result had been dismissed on the grounds that the French wines were built to last and the Californians were not, and the re-tasting removed that objection."),
    Q("The Judgment of Paris and after",
      "An American lawyer began publishing an independent newsletter on wine in 1978, scoring bottles out of a hundred and refusing all advertising, and buying habits worldwide followed his numbers for a generation. Who was he?",
      ["Robert Parker", "Michael Broadbent", "Hugh Johnson", "Alexis Lichine"], 0,
      "Taking no advertising was the whole point, because it meant readers could believe that nobody in the trade had paid for the verdict. A single number is easy to print on a shelf label and easy to trade on, which is why the scale spread far beyond the publication that introduced it."),
]
