"""Rank I rewrite - Italy (61 questions).

Written from the syllabus below. The imported bank was not read while writing.

Stem construction follows the three rules the earlier categories produced: every
opener is distinct, the subject noun is kept out of the opening clause wherever
the question is a define-or-explain, and the recorded collision templates are
avoided from the outset rather than reframed afterwards.
"""

from lib import Q

CAT = "Italy"
SLUG = "r1-italy"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Geography and climate", 5),
    ("Wine law and label language", 6),
    ("Piedmont", 8),
    ("Northwest and Alpine Italy", 4),
    ("Veneto", 7),
    ("Friuli and Trentino-Alto Adige", 4),
    ("Tuscany", 9),
    ("Central Italy", 5),
    ("Southern Italy", 5),
    ("Sicily and Sardinia", 4),
    ("Sparkling, sweet and fortified", 4),
]

BANK = [
    # ---------------------------------------------- geography and climate (5) -
    Q("Geography and climate",
      "Italy's peninsula is divided lengthwise by which mountain range?",
      ["The Apennines", "The Dolomites", "The Pyrenees", "The Massif Central"], 0,
      "The Apennines run the length of the country from Liguria down to Calabria, while the Alps close off the north. Their altitude is what keeps nights cool even in the far south."),
    Q("Geography and climate",
      "Wine is produced commercially in every Italian administrative region. How many such regions does the country have?",
      ["Twenty", "Twelve", "Fifteen", "Twenty-eight"], 0,
      "All twenty regions grow grapes for sale, from Alpine Valle d'Aosta to Sicily. Very few wine countries can say the same, and it is part of why the native grape count is so high."),
    Q("Geography and climate",
      "Italy's two main wine-producing islands lie off the west and the south. Which are they?",
      ["Sicily and Sardinia", "Elba and Capri", "Ischia and Pantelleria",
       "Corsica and Malta"], 0,
      "Sicily sits off the toe of the peninsula and Sardinia west of the mainland. Both have long, hot seasons tempered by sea breezes and by planting at altitude."),
    Q("Geography and climate",
      "Bardolino and Lugana are grown beside which large lake?",
      ["Lake Garda", "Lake Como", "Lake Maggiore", "Lake Trasimeno"], 0,
      "Garda's mass of water warms and cools slowly, damping temperature extremes on its shores. The lighter reds and whites grown around it depend on that moderation."),
    Q("Geography and climate",
      "Growers across southern Italy plant high on the Apennine slopes. What does the elevation chiefly buy them?",
      ["Cooler nights that preserve acidity and aroma", "Deeper limestone soils",
       "Higher yields per hectare", "Freedom from hail damage"], 0,
      "A wide day-to-night swing slows sugar accumulation relative to flavour development. In a hot climate that is the main tool for keeping freshness in the glass."),

    # --------------------------------------- wine law and label language (6) --
    Q("Wine law and label language",
      "A label reads DOCG. What does that final letter add over a DOC wine?",
      ["A guarantee backed by chemical analysis and a tasting panel",
       "A guarantee that the fruit was farmed organically",
       "A guarantee of single-vineyard origin",
       "A guarantee of at least ten years of ageing"], 0,
      "DOC wines face laboratory and tasting examination too, so Garantita is a matter of degree: the panel tastes lot by lot at bottling and every bottle carries a numbered state seal, the contrassegno. The production rules behind a DOCG, yields and ageing among them, are stricter as well."),
    Q("Wine law and label language",
      "Under EU classification, DOC and DOCG wines are grouped together as what?",
      ["DOP", "IGP", "Vino da Tavola", "Vino Varietale"], 0,
      "DOP covers every protected designation of origin, and IGT wines fall into the broader IGP band. The older Italian initials still appear on most labels."),
    Q("Wine law and label language",
      "Which term on an Italian label marks the historic heart of a denomination?",
      ["Classico", "Riserva", "Superiore", "Vendemmia"], 0,
      "Classico zones are the original delimited areas, later ringed by expansions of the same name. Chianti Classico and Soave Classico are the familiar examples."),
    Q("Wine law and label language",
      "A producer holds a wine well past the standard minimum to earn one extra word on the label. Which word?",
      ["Riserva", "Classico", "Frizzante", "Amabile"], 0,
      "National law sets the floor at two years of ageing for reds and one year for whites, and an individual denomination's rules may demand longer still. Riserva frequently carries a higher minimum alcohol as well."),
    Q("Wine law and label language",
      "A denomination allows one extra word for wines meeting a higher minimum alcohol. Which word is it?",
      ["Superiore", "Classico", "Selezione", "Integrale"], 0,
      "Superiore usually pairs the alcohol requirement with lower permitted yields. It says nothing about oak, vineyard site or a tasting assessment."),
    Q("Wine law and label language",
      "Tuscan reds blending Sangiovese with Cabernet Sauvignon fell outside the DOC rules entirely. Which category was created in 1992 to house them?",
      ["IGT", "DOCG", "DOC", "Vino da Tavola"], 0,
      "Before 1992 those wines were sold as plain table wine despite their price. IGT gave them a legitimate geographic designation, and many Super Tuscans still choose Toscana IGT."),

    # -------------------------------------------------------- Piedmont (8) ---
    Q("Piedmont",
      "Barolo and Barbaresco are both built on which single grape?",
      ["Nebbiolo", "Barbera", "Dolcetto", "Corvina"], 0,
      "Both denominations require one hundred percent Nebbiolo, so what separates them is site, soil and ageing rather than variety. The grape gives pale colour with fierce tannin and acidity."),
    Q("Piedmont",
      "Which grape supplies Piedmont's high-acid, low-tannin everyday red around Asti and Alba?",
      ["Barbera", "Nebbiolo", "Dolcetto", "Grignolino"], 0,
      "Barbera is the region's most planted red. It ripens with striking acidity and very little tannin, which is why it drinks young and sits so well against food."),
    Q("Piedmont",
      "A deeply coloured, low-acid Piedmontese red ripens weeks ahead of Nebbiolo. Which grape is it?",
      ["Dolcetto", "Barbera", "Freisa", "Cortese"], 0,
      "Dolcetto's early ripening lets growers use the cooler sites where Nebbiolo would never finish. The name means little sweet one and refers to the fruit, not the wine, which is dry."),
    Q("Piedmont",
      "Which white grape stands behind the wines of Gavi?",
      ["Cortese", "Arneis", "Garganega", "Vermentino"], 0,
      "Gavi lies in the southeast of Piedmont near the Ligurian border. Cortese gives a dry, lean, citrus-driven wine that traditionally went to the seafood restaurants of the coast."),
    Q("Piedmont",
      "Roero's white DOCG rests on a grape that was close to extinction in the 1970s. Name it.",
      ["Arneis", "Cortese", "Favorita", "Erbaluce"], 0,
      "Arneis was revived in the Roero hills across the Tanaro from the Langhe. It is rounder and less acidic than Cortese, with a pear and almond character."),
    Q("Piedmont",
      "Two Nebbiolo denominations in the far north of Piedmont call the grape Spanna. Which pair?",
      ["Gattinara and Ghemme", "Gavi and Ovada", "Asti and Alba",
       "Barolo and Barbaresco"], 0,
      "Alto Piemonte sits well north of the Langhe on volcanic and glacial soils. Its Nebbiolo is lighter framed and often blended with small amounts of local varieties."),
    Q("Piedmont",
      "Between Barolo and Barbaresco, which carries the longer minimum ageing before release?",
      ["Barolo", "Barbaresco", "Both require exactly the same",
       "Neither carries an ageing minimum"], 0,
      "Barolo needs longer in total and longer in wood than Barbaresco, and both extend further again for Riserva. Barbaresco's fruit ripens slightly earlier, which suits the shorter requirement."),
    Q("Piedmont",
      "A gently sparkling, sweet, low-alcohol Piedmontese wine is pressed from Moscato Bianco. Which is it?",
      ["Moscato d'Asti", "Gavi", "Brachetto d'Acqui", "Freisa d'Asti"], 0,
      "Fermentation is stopped early, leaving sugar, grape aroma and around five and a half percent alcohol. The wine is frizzante rather than fully sparkling."),

    # ---------------------------------------- northwest and Alpine Italy (4) --
    Q("Northwest and Alpine Italy",
      "Lombardy's traditional-method sparkling DOCG takes its name from a zone near Brescia. Which is it?",
      ["Franciacorta", "Oltrepo Pavese", "Lugana", "Valtellina"], 0,
      "Franciacorta uses Chardonnay, Pinot Nero and Pinot Bianco with the second fermentation in bottle. It is the Italian benchmark for that style and is priced accordingly."),
    Q("Northwest and Alpine Italy",
      "Steep terraces above the Adda valley in Lombardy grow Nebbiolo under a local name. What is it called there?",
      ["Chiavennasca", "Spanna", "Picotendro", "Pignolo"], 0,
      "Valtellina's terraces are among the steepest worked vineyards in Italy, all of it hand labour. Sforzato is the zone's dried-grape version of the same grape."),
    Q("Northwest and Alpine Italy",
      "Of the twenty regions, which produces the least wine, hemmed in by Alpine valleys?",
      ["Valle d'Aosta", "Liguria", "Molise", "Umbria"], 0,
      "Valle d'Aosta's vineyards climb high Alpine slopes and its total output is tiny, so bottles rarely leave the region. Molise, Liguria and Basilicata are the other very small producers, and their order shifts from vintage to vintage."),
    Q("Northwest and Alpine Italy",
      "Cinque Terre and Rossese di Dolceacqua belong to which coastal region?",
      ["Liguria", "Tuscany", "Lazio", "Marche"], 0,
      "Liguria is a narrow crescent of terraced coast squeezed between mountains and sea. Vermentino and Pigato carry the whites, and volumes are small enough that little is exported."),

    # ----------------------------------------------------------- Veneto (7) --
    Q("Veneto",
      "The white wines of Soave are built principally on which variety?",
      ["Garganega", "Trebbiano di Soave", "Verdicchio", "Cortese"], 0,
      "Garganega ripens late and gives a lightly nutty, lemon-toned wine. Trebbiano di Soave or Chardonnay may fill a minority share of the blend."),
    Q("Veneto",
      "Corvina, Rondinella and Molinara form the traditional blend behind which red?",
      ["Valpolicella", "Chianti Classico", "Lambrusco di Sorbara", "Rosso Conero"], 0,
      "Corvina leads and supplies the sour-cherry lift the style is known for. The same grapes handled in a lighter way make Bardolino on the shore of Lake Garda."),
    Q("Veneto",
      "Grapes are laid on racks to shrivel for months, then fermented right out to around fifteen percent alcohol. Which wine results?",
      ["Amarone della Valpolicella", "Recioto della Valpolicella",
       "Valpolicella Ripasso", "Bardolino Chiaretto"], 0,
      "Appassimento concentrates sugar, acid and flavour before fermentation even begins. Taking that sugar all the way to dryness is exactly what separates Amarone from sweet Recioto."),
    Q("Veneto",
      "A basic Valpolicella is refermented on the drained skins left over from Amarone. What is the result called?",
      ["Ripasso", "Recioto", "Chiaretto", "Passito"], 0,
      "Re-passing the young wine over that pomace adds alcohol, colour and texture. It was conceived as a way of making a fuller wine without the cost of full appassimento."),
    Q("Veneto",
      "Which variety must dominate a bottle of Prosecco?",
      ["Glera", "Garganega", "Trebbiano", "Moscato Bianco"], 0,
      "The grape was formally renamed Glera in 2009 so that Prosecco could be protected as a place name rather than a variety name that anyone might plant."),
    Q("Veneto",
      "A second fermentation gives Prosecco its bubbles. Where does that fermentation take place?",
      ["In a sealed pressure tank", "In each individual bottle",
       "In a cask under a film of yeast", "Nowhere, the gas is injected"], 0,
      "The tank or Charmat method finishes quickly and keeps the pear and white-flower aromatics intact. Long ageing on lees in bottle would replace them with bready character."),
    Q("Veneto",
      "The senior Prosecco denomination covers hills between two towns north of Treviso. Which pair names it?",
      ["Conegliano and Valdobbiadene", "Bassano and Asolo", "Verona and Soave",
       "Vicenza and Padua"], 0,
      "Conegliano Valdobbiadene Prosecco Superiore is DOCG, and the steepest slope within it, Cartizze, is the most prized site of all."),

    # ----------------------------------- Friuli and Trentino-Alto Adige (4) --
    Q("Friuli and Trentino-Alto Adige",
      "Which Italian region built its modern reputation on precise varietal whites from Collio and the Colli Orientali?",
      ["Friuli-Venezia Giulia", "Veneto", "Marche", "Umbria"], 0,
      "Friuli sits in the far northeast against the Slovenian border. Cool nights and a run of both native and international whites define what it does best."),
    Q("Friuli and Trentino-Alto Adige",
      "Tocai Friulano had to be renamed after a dispute with Hungary. What appears on labels now?",
      ["Friulano", "Ribolla Gialla", "Verduzzo", "Malvasia Istriana"], 0,
      "The EU reserved Tokaj for Hungary, so the region's signature white dropped the first half of its name. DNA profiling showed the variety is Sauvignonasse, also called Sauvignon Vert, and it has no relation to Furmint or to Tokaji."),
    Q("Friuli and Trentino-Alto Adige",
      "German is an official language in the northernmost Italian wine zone. Which zone is that?",
      ["Alto Adige", "Trentino", "Valle d'Aosta", "Friuli"], 0,
      "Alto Adige, or Sudtirol, was Austrian territory until 1919 and labels often appear in both languages. Schiava and Lagrein are its historic reds."),
    Q("Friuli and Trentino-Alto Adige",
      "Teroldego Rotaliano is grown on a flat gravelly fan in which region?",
      ["Trentino", "Alto Adige", "Veneto", "Lombardy"], 0,
      "The Campo Rotaliano lies north of Trento where two rivers meet. Teroldego is its deeply coloured native red and is grown almost nowhere else."),

    # ---------------------------------------------------------- Tuscany (9) --
    Q("Tuscany",
      "Which grape accounts for the red wines of Chianti, Montalcino and Montepulciano alike?",
      ["Sangiovese", "Nebbiolo", "Montepulciano", "Canaiolo"], 0,
      "Sangiovese is Italy's most planted variety. Its local clones and names, Brunello and Prugnolo Gentile, are much of what marks those three zones apart."),
    Q("Tuscany",
      "A black rooster on the neck seal identifies a bottle from which zone?",
      ["Chianti Classico", "Brunello di Montalcino", "Bolgheri", "Carmignano"], 0,
      "The Gallo Nero is the consortium mark for the hills between Florence and Siena. Chianti Classico has been its own DOCG since 1996, entirely separate from the Chianti DOCG that surrounds it, and only Classico bottles carry the seal."),
    Q("Tuscany",
      "A Brunello cannot be released until the fifth year after harvest. How much of that time must it spend in wood?",
      ["Two years", "Six months", "Four years", "Ten months"], 0,
      "Two years in oak is the minimum, with further time in bottle before release and a full extra year for Riserva. Rosso di Montalcino is the younger wine from the same zone."),
    Q("Tuscany",
      "Prugnolo Gentile is the local name for Sangiovese in the wine of which hill town?",
      ["Montepulciano", "Montalcino", "San Gimignano", "Greve"], 0,
      "Vino Nobile di Montepulciano must be at least seventy percent Sangiovese under that local name. The town has nothing to do with the Montepulciano grape of Abruzzo."),
    Q("Tuscany",
      "A guest cannot see the difference between Montepulciano d'Abruzzo and Vino Nobile di Montepulciano. What should you tell them?",
      ["One names a grape grown in Abruzzo, the other a Tuscan town growing Sangiovese",
       "They are the same wine sold under two names",
       "One is white and the other red",
       "One is sparkling and the other still"], 0,
      "Montepulciano the variety is planted heavily down the Adriatic side of the country. Montepulciano the town is in southern Tuscany, and its wine is Sangiovese."),
    Q("Tuscany",
      "Cabernet Sauvignon planted near the Tuscan coast made the reputation of which denomination?",
      ["Bolgheri", "Carmignano", "Morellino di Scansano", "Montecucco"], 0,
      "Bolgheri sits on the Maremma coast south of Livorno, and the zone launched the Super Tuscan movement. Sassicaia went further in 2013, becoming Bolgheri Sassicaia DOC, Italy's first denomination held by a single estate."),
    Q("Tuscany",
      "Tuscany's only white DOCG grows around a town of medieval towers. Which wine is it?",
      ["Vernaccia di San Gimignano", "Orvieto Classico", "Vermentino di Bolgheri",
       "Bianco di Pitigliano"], 0,
      "Vernaccia di San Gimignano was the first wine in Italy to be granted DOC status, in 1966. It remains the region's only white at DOCG level."),
    Q("Tuscany",
      "Sangiovese grown in the warm coastal Maremma carries which denomination name?",
      ["Morellino di Scansano", "Rosso di Montalcino", "Carmignano", "Chianti Rufina"], 0,
      "Morellino is simply the local name for Sangiovese in that corner of Tuscany. The heat gives a fuller, softer wine than the same grape makes in the hills inland."),
    Q("Tuscany",
      "Dried grapes, small sealed casks and years in a warm loft produce which Tuscan speciality?",
      ["Vin Santo", "Amarone", "Marsala", "Passito di Pantelleria"], 0,
      "Trebbiano and Malvasia are dried, pressed and sealed into caratelli, often with a madre starter from a previous batch. The casks are left through the swings of the seasons."),

    # ---------------------------------------------------- central Italy (5) --
    Q("Central Italy",
      "Which region grows Verdicchio in the hills behind Ancona?",
      ["Marche", "Umbria", "Abruzzo", "Lazio"], 0,
      "Marche faces the Adriatic on the eastern side of the peninsula. Verdicchio dei Castelli di Jesi and the higher, cooler Verdicchio di Matelica are its two zones for the grape."),
    Q("Central Italy",
      "One of Italy's most tannic red grapes is grown around Montefalco. Which is it?",
      ["Sagrantino", "Sangiovese", "Aglianico", "Nero d'Avola"], 0,
      "Sagrantino carries exceptional tannin even by Italian standards and needs long ageing to soften. Montefalco also makes a sweet passito version from the same fruit."),
    Q("Central Italy",
      "Which city has Frascati grown in the volcanic hills immediately outside it?",
      ["Rome", "Naples", "Florence", "Bologna"], 0,
      "The Castelli Romani hills southeast of Rome are old volcanic country. Frascati is their Malvasia and Trebbiano based white, historically drunk young in the city."),
    Q("Central Italy",
      "Frizzante red wine served cool alongside rich Emilian cooking comes from which grape?",
      ["Lambrusco", "Barbera", "Schiava", "Bonarda"], 0,
      "Lambrusco is a family of related varieties around Modena and Reggio Emilia. The bubbles and acidity are there to cut through the fat of the local food."),
    Q("Central Italy",
      "A pale cherry-coloured rose from Abruzzo carries which denomination name?",
      ["Cerasuolo d'Abruzzo", "Chiaretto di Bardolino", "Rosato del Salento",
       "Lacryma Christi"], 0,
      "Cerasuolo means cherry-coloured. It is made from Montepulciano with only brief skin contact and holds a denomination of its own, separate from the red."),

    # --------------------------------------------------- southern Italy (5) --
    Q("Southern Italy",
      "Which red variety, grown on volcanic soils in Campania, gives the wine Taurasi?",
      ["Aglianico", "Primitivo", "Negroamaro", "Gaglioppo"], 0,
      "Aglianico ripens very late and carries firm tannin with high acidity, so it rewards ageing. Taurasi was the first DOCG granted anywhere in southern Italy."),
    Q("Southern Italy",
      "Fiano and Greco di Tufo are white denominations of which region?",
      ["Campania", "Puglia", "Basilicata", "Calabria"], 0,
      "The hills inland of Naples around Avellino are high and cool. That altitude is why these whites keep structure and can age, unusually for the south."),
    Q("Southern Italy",
      "Vineyards on the slopes of an extinct volcano called Vulture grow Aglianico in which region?",
      ["Basilicata", "Campania", "Calabria", "Molise"], 0,
      "Basilicata is mountainous and largely landlocked, and Aglianico del Vulture is effectively its one famous wine. The soils are volcanic ash and lava at real altitude."),
    Q("Southern Italy",
      "DNA work matched a widely planted Californian grape to a Puglian variety. Which Italian name does it carry?",
      ["Primitivo", "Negroamaro", "Nero d'Avola", "Aglianico"], 0,
      "Primitivo and Zinfandel proved to be the same variety, traced back to Croatian Tribidrag. Puglia's heat pushes it towards ripe, jammy, high-alcohol styles."),
    Q("Southern Italy",
      "Salice Salentino and Negroamaro belong to the heel of Italy. Which region is that?",
      ["Puglia", "Calabria", "Campania", "Sicily"], 0,
      "The Salento peninsula is flat, hot and very dry. Negroamaro and Primitivo dominate its reds, which tend to be soft and warm rather than structured."),

    # ------------------------------------------------ Sicily and Sardinia (4) -
    Q("Sicily and Sardinia",
      "Which volcano's slopes grow Nerello Mascalese and Carricante?",
      ["Mount Etna", "Mount Vesuvius", "Mount Vulture", "Stromboli"], 0,
      "Etna's terraces climb to altitudes no other Sicilian zone reaches, on black volcanic soil. The reds come out pale and taut, closer to Nebbiolo than to the island's usual style."),
    Q("Sicily and Sardinia",
      "Sicily's only DOCG blends Nero d'Avola with a lighter, perfumed red. Which is the partner grape?",
      ["Frappato", "Nerello Cappuccio", "Grillo", "Perricone"], 0,
      "Frappato brings red fruit and lift to Nero d'Avola's depth and colour. The wine is Cerasuolo di Vittoria, from the southeast corner of the island."),
    Q("Sicily and Sardinia",
      "Grenache travelled to Sardinia and is grown there under which name?",
      ["Cannonau", "Carignano", "Monica", "Bovale"], 0,
      "Cannonau is the island's signature red, typically warm, herbal and generous in alcohol. Carignano del Sulcis, from old bush vines in the southwest, is the other red to know."),
    Q("Sicily and Sardinia",
      "Which Sardinian white denomination holds the island's only DOCG rank?",
      ["Vermentino di Gallura", "Vernaccia di Oristano", "Nuragus di Cagliari",
       "Vermentino di Sardegna"], 0,
      "Gallura, in the granite hills of the northeast, gives the most concentrated Vermentino on the island. Vermentino di Sardegna covers the rest of Sardinia at DOC level."),

    # ------------------------------------- sparkling, sweet and fortified (4) -
    Q("Sparkling, sweet and fortified",
      "A fortified wine from western Sicily is graded Fine, Superiore and Vergine. Which is it?",
      ["Marsala", "Vin Santo", "Passito di Pantelleria", "Sciacchetra"], 0,
      "Marsala was built up by English merchants in the late eighteenth century as a rival to Madeira and Sherry. Its grades turn on ageing, and its colours are oro, ambra and rubino."),
    Q("Sparkling, sweet and fortified",
      "Which Italian term describes a lightly sparkling wine, held at lower pressure than a fully sparkling one?",
      ["Frizzante", "Spumante", "Metodo Classico", "Amabile"], 0,
      "Frizzante wines carry roughly one to two and a half atmospheres against three or more for spumante. Lambrusco and Moscato d'Asti are the everyday examples."),
    Q("Sparkling, sweet and fortified",
      "Zibibbo dried in the sun on a small island south of Sicily makes which sweet wine?",
      ["Passito di Pantelleria", "Recioto di Soave", "Sciacchetra", "Vin Santo"], 0,
      "Zibibbo is the local name for Muscat of Alexandria. Pantelleria's relentless wind and heat concentrate the fruit on the vine and on drying racks before pressing."),
    Q("Sparkling, sweet and fortified",
      "Sweet wines made in Valpolicella and Soave from dried grapes share which name?",
      ["Recioto", "Ripasso", "Amarone", "Chiaretto"], 0,
      "Recioto keeps residual sugar because fermentation is halted before the sugar runs out. Amarone is the same dried fruit taken all the way to dryness instead."),
]
