"""Rank I rewrite - Loire (59 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

The category is organised as a journey up the river, because that is how the
geology, the climate and the grapes actually change: Atlantic and Melon de
Bourgogne at the mouth, schist and Chenin through Anjou, tuffeau and Cabernet
Franc in Touraine, Kimmeridgian marl and Sauvignon Blanc in the Centre. Stems
lead with a symptom, a soil or a scene at the table and let the appellation or
the grape be the answer.
"""

from lib import Q

CAT = "Loire"
SLUG = "r1-loire"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("The river and its regions", 5),
    ("Pays Nantais and Muscadet", 8),
    ("Anjou and dry Chenin", 6),
    ("Saumur and sparkling Loire", 6),
    ("Sweet Chenin on the Layon", 6),
    ("Vouvray, Montlouis and Touraine whites", 7),
    ("Cabernet Franc in Touraine", 7),
    ("Sancerre, Pouilly-Fume and the Centre", 9),
    ("Soils, climate and other grapes", 5),
]

BANK = [
    # ------------------------------------- the river and its regions (5) -----
    Q("The river and its regions",
      "Travelling inland from the Atlantic, in what order do the four broad Loire wine regions appear?",
      ["Pays Nantais, then Anjou-Saumur, then Touraine, then the Centre",
       "Anjou-Saumur, then Pays Nantais, then Touraine, then the Centre",
       "The Centre, then Touraine, then Anjou-Saumur, then Pays Nantais",
       "Touraine, then the Centre, then Anjou-Saumur, then Pays Nantais"], 0,
      "The river meets the Atlantic at Saint-Nazaire, some fifty kilometres below Nantes, so the Pays Nantais is the seaward end and the Centre lies furthest upstream, roughly four hundred kilometres inland. Every soil, grape and climate change follows that line."),
    Q("The river and its regions",
      "Vineyards near Nantes ripen in mild damp air off the ocean, while those around Sancerre face hard winters and a real frost risk. What is that eastward shift?",
      ["Maritime influence giving way to a continental climate",
       "Continental influence giving way to a maritime climate",
       "Mediterranean influence giving way to an alpine climate",
       "A uniform maritime climate along the whole valley"], 0,
      "The Atlantic reaches only so far inland. Losing its moderating effect means colder winters, warmer summers and sharper vintage variation at the eastern end of the valley."),
    Q("The river and its regions",
      "Two entirely different bedrocks meet in the middle of the valley: ancient schist and granite to the west, soft chalky limestone to the east. What are those geological domains called?",
      ["The Massif Armoricain and the Paris Basin",
       "The Massif Central and the Rhone graben",
       "The Jura arc and the Aquitaine Basin",
       "The Vosges massif and the Rhine rift"], 0,
      "The join runs near Saumur. West of it the rock is hard, acidic and hundreds of millions of years old; east of it lies the sedimentary limestone that also underlies Paris."),
    Q("The river and its regions",
      "One Loire appellation group takes its name from a river of the basin spelled without the final e, north of Tours. Which appellation belongs to it?",
      ["Jasnieres", "Quincy", "Bonnezeaux", "Cheverny"], 0,
      "The Loir is a separate river from the Loire, and Jasnieres is its best-known appellation: a thin strip of south-facing tuffeau making severe, long-lived dry Chenin."),
    Q("The river and its regions",
      "Wine grown along the valley but outside any district or village appellation is sold under which regional name?",
      ["IGP Val de Loire", "AOC Val de Loire", "Vin de France", "IGP Pays d'Oc"], 0,
      "The regional IGP covers the whole basin and is where varietal labelling and experimental plantings live. Vin de France carries no geographical claim at all, and Pays d'Oc belongs to the Languedoc."),

    # ------------------------------------- Pays Nantais and Muscadet (8) -----
    Q("Pays Nantais and Muscadet",
      "A hard winter in 1709 killed most of the vineyard around Nantes, and growers replanted with a Burgundian white chosen for its hardiness. Which variety?",
      ["Melon de Bourgogne", "Aligote", "Chardonnay", "Chenin Blanc"], 0,
      "Melon survives cold better than what it replaced and ripens early enough for a damp Atlantic autumn. It has been the sole grape of Muscadet ever since, and is scarcely grown in Burgundy today."),
    Q("Pays Nantais and Muscadet",
      "Chardonnay's parents also produced the grape behind Muscadet. Which crossing is it?",
      ["Pinot and Gouais Blanc", "Chenin Blanc and Sauvignon Blanc",
       "Traminer and Sauvignon Blanc", "Pinot and Cabernet Franc"], 0,
      "The same humble Gouais Blanc crossed with Pinot gave Chardonnay, Aligote, Gamay and Melon among many others. Shared parentage says nothing about shared flavour, as these two demonstrate."),
    Q("Pays Nantais and Muscadet",
      "Winter is spent in tank without racking, and the wine goes into bottle straight off its fine sediment. Which label term records that?",
      ["Sur lie", "Vieilles vignes", "Elevage en fut de chene", "Vendange tardive"], 0,
      "The term is regulated rather than decorative: the wine must remain on its fine lees through the winter and be bottled directly off them in the year following the harvest."),
    Q("Pays Nantais and Muscadet",
      "A young Muscadet reaches the table with a faint prickle on the tongue and a bready, creamy edge. What accounts for both at once?",
      ["Bottling straight off the fine lees, which keeps a trace of dissolved carbon dioxide and adds yeasty texture",
       "A second fermentation carried out in the bottle",
       "Malolactic conversion completed in new oak barrels",
       "A small dosage of sugar syrup added before bottling"], 0,
      "Nothing is added and nothing ferments twice. Carbon dioxide left over from the original fermentation stays dissolved because the wine is never racked, and the spent yeast contributes the texture."),
    Q("Pays Nantais and Muscadet",
      "Two small rivers south-east of Nantes lend their names to the most important of the Muscadet appellations. Which is it?",
      ["Muscadet Sevre et Maine", "Muscadet Coteaux de la Loire",
       "Muscadet Cotes de Grandlieu", "Muscadet Coteaux d'Ancenis"], 0,
      "The Sevre Nantaise and the Maine drain the heart of the vineyard. Coteaux de la Loire and Cotes de Grandlieu are the other two named zones, and Coteaux d'Ancenis is a separate appellation entirely."),
    Q("Pays Nantais and Muscadet",
      "A bottle of Clisson has rested on its lees far longer than a standard Muscadet, yet the words sur lie appear nowhere on the label. Why are they absent?",
      ["The cru communal rules demand lees ageing well beyond what the sur lie definition permits",
       "The wine was racked off its lees immediately after fermentation",
       "Sur lie may only be used on the generic Muscadet appellation",
       "The wine was raised in barrel rather than in tank"], 0,
      "Sur lie is tied to an early bottling. The village crus keep their wine on lees for years instead, so they gain concentration and texture but forfeit the term that made the region's name."),
    Q("Pays Nantais and Muscadet",
      "A plate of raw oysters arrives and the sommelier reaches for the Atlantic end of the valley. Which qualities make that match work?",
      ["Low alcohol, high acidity and a dry, saline, unoaked finish",
       "Noticeable residual sugar over a creamy, oak-aged texture",
       "Firm tannin supported by high alcohol",
       "Botrytis character carried on low acidity"], 0,
      "Acidity does the work a squeeze of lemon would, and the absence of oak or sweetness leaves the shellfish untouched. It is the closest thing the wine list has to a default pairing."),
    Q("Pays Nantais and Muscadet",
      "A second white appellation around Nantes works with Folle Blanche and is leaner and sharper still than its famous neighbour. What is it called?",
      ["Gros Plant du Pays Nantais", "Coteaux d'Ancenis",
       "Fiefs Vendeens", "Cotes de Grandlieu"], 0,
      "Folle Blanche is so high in acid that it was long grown mainly for distillation into brandy. As a table wine it is austere, cheap and very good with the same shellfish."),

    # ---------------------------------------- Anjou and dry Chenin (6) -------
    Q("Anjou and dry Chenin",
      "Steep dark schist slopes on the north bank downstream of Angers give France's most austere and long-lived dry Chenin. Which appellation?",
      ["Savennieres", "Vouvray", "Montlouis-sur-Loire", "Jasnieres"], 0,
      "Poor rock, low yields and full southern exposure make a wine that can be almost forbidding in youth. Ten years usually turns the austerity into honey, quince and wet wool."),
    Q("Anjou and dry Chenin",
      "One Savennieres vineyard was granted an appellation in its own name and sits as a single walled amphitheatre of vines above the river. Which is it?",
      ["Coulee de Serrant", "Le Clos du Papillon", "Les Monts Damnes", "Clos Rougeard"], 0,
      "Coulee de Serrant and Roche aux Moines are the two named crus carved out of Savennieres. Clos du Papillon is a celebrated lieu-dit but not an appellation of its own."),
    Q("Anjou and dry Chenin",
      "Growers around Angers speak of Anjou noir and Anjou blanc. What does that pair of names distinguish?",
      ["Dark schist of the old massif to the west against pale tuffeau limestone to the east",
       "Red wine production to the west against white wine production to the east",
       "Old vines against young plantings",
       "Sweet wine against dry wine"], 0,
      "The colours are the rocks, not the wine. Black schist gives the brooding dry Chenin and sweet Layon wines; the white limestone further east gives the softer, chalkier style around Saumur."),
    Q("Anjou and dry Chenin",
      "Rose de Loire, Rose d'Anjou and Cabernet d'Anjou all cover pink wine from the same corner of the valley. Which of the three must be finished dry?",
      ["Rose de Loire", "Rose d'Anjou", "Cabernet d'Anjou",
       "All three must be finished dry"], 0,
      "Rose de Loire is the dry one by law. Rose d'Anjou is off-dry and built on Grolleau, while Cabernet d'Anjou is medium sweet and made only from the two Cabernets."),
    Q("Anjou and dry Chenin",
      "Which variety dominates the reds of Anjou-Villages and gives them their leafy, raspberry-scented profile?",
      ["Cabernet Franc", "Gamay", "Pinot Noir", "Grolleau"], 0,
      "Anjou-Villages is the stricter red appellation sitting above plain Anjou Rouge, with lower yields and later release. Cabernet Franc carries it, as it carries almost every serious Loire red."),
    Q("Anjou and dry Chenin",
      "Loire growers have long used a local name for Chenin Blanc that misleads visitors into thinking of Burgundy. What is it?",
      ["Pineau de la Loire", "Melon de Bourgogne", "Blanc Fume", "Breton"], 0,
      "Pineau de la Loire has nothing to do with Pinot. Chenin's real home is here, and outside the valley only South Africa, where it was long called Steen, grows it in quantity."),

    # ----------------------------------- Saumur and sparkling Loire (6) ------
    Q("Saumur and sparkling Loire",
      "Soft white limestone quarried for the chateaux of the valley left miles of galleries beneath the town of Saumur. What is that rock called?",
      ["Tuffeau", "Silex", "Gabbro", "Kimmeridgian marl"], 0,
      "Tuffeau is a porous, sandy chalk laid down in a warm Cretaceous sea. It cuts easily when freshly quarried and hardens in the air, which is why so much of the region is built and cellared in it."),
    Q("Saumur and sparkling Loire",
      "A cool, humid cellar cut into rock and holding a steady temperature all year suits one wine style above all. Which became the speciality of Saumur?",
      ["Traditional-method sparkling wine", "Botrytised sweet white wine",
       "Long-aged oxidative red wine", "Fortified sweet wine"], 0,
      "Bottle-fermented wine needs cool, stable storage in bulk for months or years, and the quarries provided exactly that for nothing. The trade grew up around the cellars rather than the vineyards."),
    Q("Saumur and sparkling Loire",
      "A red grown on the limestone plateau immediately east of Saumur is the most sought-after Cabernet Franc of Anjou-Saumur. Which appellation?",
      ["Saumur-Champigny", "Saumur Rouge", "Anjou-Villages", "Bourgueil"], 0,
      "The shallow soil over tuffeau warms quickly and drains hard, ripening Cabernet Franc more fully than the surrounding zone. The wines are supple and perfumed, and the best of them age well."),
    Q("Saumur and sparkling Loire",
      "One Loire sparkling appellation may draw grapes from Anjou, Saumur and Touraine alike, and requires hand harvesting and whole-bunch pressing. Which is it?",
      ["Cremant de Loire", "Saumur Mousseux", "Vouvray Mousseux", "Touraine Mousseux"], 0,
      "Cremant de Loire is the valley-wide appellation with the tighter rulebook: compulsory hand picking into crates, whole-bunch pressing and a press yield capped at 100 litres of must per 150 kilos of fruit. Those are its genuine extra demands rather than the lees minimum, which Vouvray Mousseux matches."),
    Q("Saumur and sparkling Loire",
      "Piercing acidity and orchard-fruit character make one variety the natural base for Loire sparkling wine. Which grape?",
      ["Chenin Blanc", "Chardonnay", "Melon de Bourgogne", "Sauvignon Blanc"], 0,
      "Chenin holds acidity at ripeness better than almost any white grape, which is what a base wine needs. Chardonnay, Cabernet Franc and Pinot Noir play supporting roles in the blends."),
    Q("Saumur and sparkling Loire",
      "Pressing intact bunches rather than crushed fruit is compulsory for Cremant. What does the rule protect?",
      ["Clean, pale juice with little phenolic extraction or colour from black grapes",
       "A higher sugar concentration in the must",
       "A faster and warmer first fermentation",
       "Deeper colour drawn from the skins"], 0,
      "Whole bunches form their own drainage bed, so the press works gently and the juice runs clear. Broken black berries would bleed colour and hard phenolics into a wine meant to be delicate."),

    # ------------------------------------ sweet Chenin on the Layon (6) ------
    Q("Sweet Chenin on the Layon",
      "Morning mists rise off a small tributary south of Angers and burn away by midday, autumn after autumn. Which wine style does that pattern make possible?",
      ["Botrytised sweet Chenin Blanc", "Bone-dry sparkling wine",
       "Deeply tannic red wine", "Fortified sweet wine"], 0,
      "Damp nights let noble rot establish and dry afternoons stop it turning grey and destructive. The Layon valley is one of the few places in France where that rhythm is reliable."),
    Q("Sweet Chenin on the Layon",
      "Grand Cru rank appears on exactly one Loire label. Which appellation carries it?",
      ["Quarts de Chaume", "Bonnezeaux", "Coteaux du Layon", "Savennieres"], 0,
      "A tiny south-facing amphitheatre of schist above the Layon, sheltered from the north and reliably misted at dawn. Yields are the lowest of any Loire appellation."),
    Q("Sweet Chenin on the Layon",
      "Within the commune of Thouarce, a run of steep schist slopes carries its own sweet-wine appellation inside the wider Layon zone. Which?",
      ["Bonnezeaux", "Quarts de Chaume", "Coteaux de l'Aubance", "Savennieres"], 0,
      "Three south-facing slopes above the river, worked for botrytised and raisined Chenin. It is the largest of the Layon's separately named sweet appellations and among the longest-lived."),
    Q("Sweet Chenin on the Layon",
      "A smaller tributary runs south of Angers between the Loire and the Layon, and its schist slopes make sweet Chenin in a lighter, earlier-drinking register than the celebrated valley to the south-west. Which appellation sits there?",
      ["Coteaux de l'Aubance", "Coteaux du Layon", "Bonnezeaux", "Jasnieres"], 0,
      "The Aubance runs a few kilometres north-east of the Layon over the same dark rock, but its slopes are gentler and noble rot arrives less reliably. The wines are usually made in a lighter style and drunk within a decade, and the appellation stays far less known than its bigger neighbour."),
    Q("Sweet Chenin on the Layon",
      "Noble rot does not form in every autumn, yet sweet wine is still made. Which vineyard route concentrates the sugar instead?",
      ["Passerillage, with the berries raisining on the vine",
       "Fortification of the must with grape spirit",
       "Chaptalisation of the must before fermentation",
       "Freezing the picked fruit in the winery to draw off water"], 0,
      "Left hanging into a dry autumn, the berry loses water through its skin and the sugar concentrates without any fungus. The result is purer and more apricot-like, with less of the honeyed botrytis note."),
    Q("Sweet Chenin on the Layon",
      "A fifty-year-old Quarts de Chaume still tastes fresh rather than cloying. Which quality of the grape explains that?",
      ["Its very high natural acidity", "Its high tannin",
       "Its high alcohol", "The new oak it was raised in"], 0,
      "Sugar without acid tastes flabby within a decade. Chenin holds enough acidity to carry two hundred grams of residual sugar and still finish clean, which is why these wines outlive most Sauternes drinkers expect them to."),

    # --------------------- Vouvray, Montlouis and Touraine whites (7) --------
    Q("Vouvray, Montlouis and Touraine whites",
      "On the right bank east of Tours, a single appellation makes dry, off-dry, sweet and sparkling wine from one grape. Which is it?",
      ["Vouvray", "Montlouis-sur-Loire", "Jasnieres", "Cheverny"], 0,
      "Chenin's acidity lets a grower choose the style after seeing what the year delivers. The tuffeau slope above the river is honeycombed with cellars cut into the rock."),
    Q("Vouvray, Montlouis and Touraine whites",
      "Hemmed between the Loire and the Cher on the left bank, which appellation won independence from its more famous neighbour in 1938?",
      ["Montlouis-sur-Loire", "Vouvray", "Touraine-Amboise", "Cour-Cheverny"], 0,
      "Sandier soils over the tuffeau give a slightly quicker, more open style. The same range of dry through sweet and sparkling is made, and the wines are almost always the better value of the pair."),
    Q("Vouvray, Montlouis and Touraine whites",
      "A guest wants a Vouvray with clear sweetness on the palate but stops well short of a dessert wine. Which label term sends you to the right bottle?",
      ["Demi-sec", "Sec", "Moelleux", "Doux"], 0,
      "Sec is dry and moelleux is frankly sweet, with doux sweeter again. Demi-sec sits between them, carrying enough sugar to read as off-dry while staying a wine for the table rather than the dessert course."),
    Q("Vouvray, Montlouis and Touraine whites",
      "A cold, wet summer leaves the fruit at modest ripeness with searing acidity. What will a Vouvray producer make from it?",
      ["Dry still wine and sparkling wine", "A botrytised moelleux",
       "A doux from raisined fruit", "An oak-aged red"], 0,
      "High acid and low sugar is exactly the profile a base wine wants, so poor years go to the sparkling cuvee. Sweet wine is only attempted when the autumn delivers rot or raisining."),
    Q("Vouvray, Montlouis and Touraine whites",
      "A sommelier is asked for Loire bubbles that carry a single village name rather than the valley-wide Cremant. Which appellation can supply them?",
      ["Vouvray Mousseux", "Sancerre Mousseux",
       "Muscadet Mousseux", "Chinon Mousseux"], 0,
      "Sparkling wine is written into the rules of Vouvray and Montlouis, as it is at Saumur and in Anjou, so the village name carries the fizz on its own label. Sancerre, Muscadet and Chinon have no sparkling category at all, and they fall outside the Cremant de Loire zone as well, so a grower there who wants bubbles has to leave appellation wine altogether."),
    Q("Vouvray, Montlouis and Touraine whites",
      "A single obscure white grape survives in one small appellation near Blois and almost nowhere else on earth. Which variety?",
      ["Romorantin", "Orbois", "Folle Blanche", "Pineau d'Aunis"], 0,
      "Cour-Cheverny exists solely to protect it. The wine is lean, waxy and slow to open, and neighbouring Cheverny uses Sauvignon Blanc instead."),
    Q("Vouvray, Montlouis and Touraine whites",
      "Two levels of fizz are permitted in Vouvray and Montlouis, and the gentler one carries markedly lower pressure. Which term marks it?",
      ["Petillant", "Mousseux", "Cremant", "Tranquille"], 0,
      "Petillant is softly frothing rather than fully sparkling, and is the older local style. Tranquille simply means still, so it marks the absence of any bubble at all."),

    # ------------------------------------- Cabernet Franc in Touraine (7) ----
    Q("Cabernet Franc in Touraine",
      "Local growers call it Breton, a name with no connection to Brittany at all. Which variety?",
      ["Cabernet Franc", "Gamay", "Cot", "Pineau d'Aunis"], 0,
      "The origin of the name is disputed: it appears in Rabelais in 1534, well before the abbot Breton usually credited with it, and one account ties it instead to vines arriving through a Breton port. It buds and ripens early, which is what lets it work this far north."),
    Q("Cabernet Franc in Touraine",
      "Vines along the Vienne, just above its confluence with the Loire, feed which red appellation?",
      ["Chinon", "Bourgueil", "Saint-Nicolas-de-Bourgueil", "Saumur-Champigny"], 0,
      "The town sits under a vast medieval fortress on the Vienne. Bourgueil and Saint-Nicolas lie on the opposite bank of the Loire a short distance downstream."),
    Q("Cabernet Franc in Touraine",
      "Among Chinon, Bourgueil and Saint-Nicolas-de-Bourgueil, only one may also bottle a white wine. Which, and from what grape?",
      ["Chinon, from Chenin Blanc", "Bourgueil, from Chenin Blanc",
       "Saint-Nicolas-de-Bourgueil, from Sauvignon Blanc",
       "All three, from Chenin Blanc"], 0,
      "Chinon Blanc is a small but genuine part of the appellation, and there is a Chinon rose as well. The two Bourgueil appellations are restricted to red and rose only."),
    Q("Cabernet Franc in Touraine",
      "Two soil types split the reds of Chinon: light sand and gravel terraces beside the river, and limestone slopes above them. What does that difference produce?",
      ["Early-drinking, fruity wine from the terraces and firmer, ageworthy wine from the slopes",
       "Firm, ageworthy wine from the terraces and light, fruity wine from the slopes",
       "Sweet wine from the terraces and dry wine from the slopes",
       "White wine from the terraces and red wine from the slopes"], 0,
      "Free-draining sand gives a supple wine for drinking within a few years. The tuffeau slopes hold more water and give structure, and those are the bottlings worth cellaring."),
    Q("Cabernet Franc in Touraine",
      "Sandier soils on the western edge of the Bourgueil zone give lighter, earlier-drinking Cabernet Franc under a name of its own. Which?",
      ["Saint-Nicolas-de-Bourgueil", "Chinon", "Touraine-Amboise", "Anjou-Villages"], 0,
      "It is a separate appellation covering a single commune, generally more perfumed and quicker to open than Bourgueil itself. In practice the styles overlap heavily from producer to producer."),
    Q("Cabernet Franc in Touraine",
      "A light-bodied red arrives with raspberry, violet, pencil shavings and a green-pepper edge, on fine tannin and high acidity. Which grape and origin?",
      ["Cabernet Franc from Touraine", "Gamay from Beaujolais",
       "Pinot Noir from Sancerre", "Merlot from Pomerol"], 0,
      "The herbaceous note comes from pyrazines that ripeness reduces but never quite erases this far north. It is a signature rather than a fault, and it is why these wines take a light chill so well."),
    Q("Cabernet Franc in Touraine",
      "A dark, plummy Touraine red is labelled with the old French name for the variety Argentina calls Malbec. What is that name?",
      ["Cot", "Grolleau", "Pineau d'Aunis", "Breton"], 0,
      "Cot is the old French name for the variety Cahors calls Auxerrois and Argentina calls Malbec. In Touraine it makes a deeper, more brambly red than Cabernet Franc, often blended with it."),

    # ------------------------- Sancerre, Pouilly-Fume and the Centre (9) -----
    Q("Sancerre, Pouilly-Fume and the Centre",
      "Chalky marl full of fossil oyster shells underlies the western slopes above Chavignol, the same seam that surfaces a hundred kilometres away in Chablis. What is it?",
      ["Kimmeridgian marl, known locally as terres blanches", "Silex",
       "Caillottes", "Tuffeau"], 0,
      "Heavy, water-retaining clay-limestone that ripens slowly and gives the broadest, most structured wines of the appellation. Caillottes, the stonier Portlandian limestone, gives quicker and more aromatic wine."),
    Q("Sancerre, Pouilly-Fume and the Centre",
      "Growers on the eastern edge of the Centre, nearest the river, work stony ground of flint, and their wines are traditionally described as smoky. What is that soil called?",
      ["Silex", "Caillottes", "Terres blanches", "Gabbro"], 0,
      "Silex is flint, concentrated around Saint-Andelain and giving Pouilly-Fume its most celebrated wines, though Kimmeridgian marl covers more of the appellation. Whether the gunflint aroma really comes from the rock is disputed, but the wines from it are undeniably taut."),
    Q("Sancerre, Pouilly-Fume and the Centre",
      "Red and rose Sancerre exist alongside the white. Which single variety fills them?",
      ["Pinot Noir", "Gamay", "Cabernet Franc", "Grolleau"], 0,
      "Burgundy is close, and Pinot Noir was widely planted here before phylloxera. The reds are pale and red-fruited, and warmer recent vintages have made them considerably more serious."),
    Q("Sancerre, Pouilly-Fume and the Centre",
      "One appellation in the village of Pouilly is reserved for Chasselas rather than Sauvignon Blanc. What is it called?",
      ["Pouilly-sur-Loire", "Pouilly-Fume", "Pouilly-Fuisse", "Pouilly-Loche"], 0,
      "Two appellations share one village and the difference is the grape. Chasselas is a neutral table grape and the wine is a curiosity, made in dwindling quantities."),
    Q("Sancerre, Pouilly-Fume and the Centre",
      "Which older name for Sauvignon Blanc still appears on labels from Pouilly?",
      ["Blanc Fume", "Pineau de la Loire", "Breton", "Melon B"], 0,
      "Blanc Fume de Pouilly is the full traditional form, and the fume in the appellation name comes from it. California's Fume Blanc borrowed the word outright in the 1960s."),
    Q("Sancerre, Pouilly-Fume and the Centre",
      "Barely twenty kilometres west of Sancerre, a smaller appellation grows Sauvignon Blanc and Pinot Noir on the same Kimmeridgian marl. Which?",
      ["Menetou-Salon", "Quincy", "Coteaux du Giennois", "Chateaumeillant"], 0,
      "Same soils, same grapes and the same styles in white, red and rose, with a fraction of the recognition. It is the standard recommendation when a guest wants Sancerre and balks at the price."),
    Q("Sancerre, Pouilly-Fume and the Centre",
      "On sand and gravel terraces above the river Cher, one appellation of the Centre bottles white wine and nothing else. Which?",
      ["Quincy", "Reuilly", "Menetou-Salon", "Coteaux du Giennois"], 0,
      "White only, from Sauvignon Blanc, and one of the earliest appellations granted in France. The sandy soils warm early, so the wines tend to be riper and rounder than Sancerre."),
    Q("Sancerre, Pouilly-Fume and the Centre",
      "Which appellation of the Centre is best known for a pale, delicate rose made from Pinot Gris?",
      ["Reuilly", "Quincy", "Sancerre", "Menetou-Salon"], 0,
      "Pinot Gris for rose is unusual anywhere in France and is Reuilly's signature. The same appellation also makes Sauvignon Blanc whites and Pinot Noir reds."),
    Q("Sancerre, Pouilly-Fume and the Centre",
      "A fresh goat cheese from a hamlet in the Sancerre hills is the textbook partner for the local white. Which cheese?",
      ["Crottin de Chavignol", "Sainte-Maure de Touraine",
       "Selles-sur-Cher", "Valencay"], 0,
      "The cheese and the wine come from the same slopes, and acidity is what makes the pairing work: it cuts the chalky richness of the curd rather than fighting it. The other three are Loire goat cheeses from further west."),

    # -------------------------------- soils, climate and other grapes (5) ----
    Q("Soils, climate and other grapes",
      "Steep slopes directly above the water are favoured throughout the middle Loire. What does the river do for those vineyards?",
      ["It moderates temperature and reflects light onto the slope, easing ripening in a marginal climate",
       "It supplies irrigation water permitted under the appellation rules",
       "It raises humidity enough to prevent fungal disease altogether",
       "It cools the site enough to delay the harvest by a month"], 0,
      "A large body of water warms slowly and cools slowly, softening both frost and heat spikes. The same humidity that helps in autumn also brings the rot that growers spend the summer fighting."),
    Q("Soils, climate and other grapes",
      "A mild March brings budbreak early, and a clear still night in April drops the temperature below zero. Which hazard is being described?",
      ["Spring frost", "Coulure", "Hail", "Downy mildew"], 0,
      "Green shoots have no defence once they are out, and a single night can remove most of a crop. Frost is the defining risk of the whole valley and the reason for candles, wind machines and sprinklers."),
    Q("Soils, climate and other grapes",
      "A pale red from the Loir valley carries an unmistakable scent of white pepper on a very light frame. Which variety?",
      ["Pineau d'Aunis", "Grolleau", "Cot", "Gamay"], 0,
      "Almost extinct a generation ago and now sought after for exactly the peppery lift that once counted against it. It appears in Coteaux du Loir, Coteaux du Vendomois and parts of Touraine."),
    Q("Soils, climate and other grapes",
      "Which variety is the traditional backbone of Anjou's pale, off-dry pink wine?",
      ["Grolleau", "Pineau d'Aunis", "Gamay", "Cabernet Franc"], 0,
      "Grolleau is high-yielding, low in alcohol and pale in colour, which suits a large-volume rose. Cabernet d'Anjou is the separate appellation that uses the Cabernets instead."),
    Q("Soils, climate and other grapes",
      "One variety in this valley can be bottled bone dry, off-dry, richly sweet, softly frothing or fully sparkling. Which?",
      ["Chenin Blanc", "Sauvignon Blanc", "Melon de Bourgogne", "Cabernet Franc"], 0,
      "No other white grape covers that range convincingly, and the reason is acidity: enough of it to keep a sweet wine fresh and to make a sparkling base, in the same fruit from the same slope."),
]
