"""Rank I rewrite - Label Reading (50 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing.

The running order is the one a person's eye actually takes with a strange bottle
in hand. First the statements the law forced onto the glass, because they are the
only ones that have to be true. Then who filled the bottle and where, then which
of the several names on the front is the brand and which is the place, then the
year, then the numbers, then the warnings and the little printed marks nobody
reads, then the capsule and the neck, and finally three situations where a guest
is waiting for an answer.

The legal frameworks themselves belong to Wine Law, grape synonyms to Grapes and
Labels, and a single country's classification ladder to that country. What is
left, and what this category is, is decoding: given this bottle, what does that
line on it actually commit anyone to.

Every stem opener is distinct, the constructions in lib.BANNED_TEMPLATES are
avoided by design, and where the answer is a term or a phrase the stem leads with
the thing seen on the glass so the name arrives as the answer.
"""

from lib import Q

CAT = "Label Reading"
SLUG = "r1-label-reading"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("What the law makes them print", 6),
    ("Who bottled it, and where", 6),
    ("Brand, place and producer", 5),
    ("Vintage and non-vintage", 5),
    ("Strength, sweetness and volume", 5),
    ("Sulfites, allergens and warnings", 5),
    ("Seals, logos and marks", 5),
    ("Front label, back label, small print", 5),
    ("Capsule, neck and closure", 5),
    ("The bottle in the hand", 3),
]

BANK = [
    # ------------------------------- what the law makes them print (6) -------
    Q("What the law makes them print",
      "Four items appear on a bottle of European wine: the name of the bottler, the alcoholic strength, the volume and the harvest year. Which one of them is the producer free to leave off?",
      ["The harvest year", "The name of the bottler", "The alcoholic strength",
       "The volume"], 0,
      "A year is an optional particular, which is why a wine may quite legally be sold carrying none at all. The other three are obligatory on every bottle, and a wine that omits any of them cannot be put on shelf."),
    Q("What the law makes them print",
      "A number followed by a percentage sign and the letters vol sits near the foot of a European label. What is being stated?",
      ["The actual alcoholic strength of the wine, as a percentage of its volume",
       "The proportion of the named grape in the blend, measured before fermentation",
       "The residual sugar, in grams per litre",
       "The proportion of the bottle that has been filled"], 0,
      "The figure is measured on the finished wine, which makes it one of very few numbers on a label describing what is actually in the glass rather than where it came from. Read beside the origin it is also the quickest guide to weight and warmth, which is why a practised buyer looks at it before reading a word of the back label."),
    Q("What the law makes them print",
      "Beside 75 cl on a European label stands a small lower-case letter e. What does that mark certify?",
      ["That the fill is controlled as an average across the run rather than measured bottle by bottle",
       "That the wine is certified organic and may be sold as such anywhere in the European single market",
       "That the glass is made from recycled material",
       "That the wine travelled under a duty suspension"], 0,
      "The estimated sign belongs to European weights and measures rules: a bottling line is judged on the average contents of a batch, within permitted tolerances, instead of on every individual bottle. It is a metrology mark and says nothing whatever about the wine."),
    Q("What the law makes them print",
      "A short code such as L3021 is printed on the back label or etched into the glass and appears nowhere else on the bottle. What is it for?",
      ["Identifying one bottling run, so a single batch can be traced or withdrawn",
       "Recording how many bottles the estate declared to its appellation authority that year",
       "Naming the vineyard parcel the fruit came from",
       "Certifying that the wine passed an official tasting"], 0,
      "Lot marking is a traceability requirement rather than a quality claim, and it is the first thing an authority asks for when a batch has to be recalled. European rules require the letter L in front of the code unless the code is already plainly distinguishable from everything else on the label, and what follows the letter is the bottler's own system."),
    Q("What the law makes them print",
      "Wine shipped into the United States must identify a business inside the country that a buyer or an inspector can pursue. Which statement carries that?",
      ["Imported by, followed by a company name and address",
       "Product of, followed by the country where the wine was made",
       "Contains sulfites",
       "Estate bottled"], 0,
      "The importer stands behind the bottle in the market where it is sold, which is why a town in New Jersey or Illinois appears on wines whose producer is world famous. It is commercially useful too: the importer is often the fastest route to the rest of a producer's range."),
    Q("What the law makes them print",
      "Scanning a square black and white code on a recent European bottle opens the full ingredient list and nutrition table. Which particular must still be printed on the bottle itself?",
      ["The energy value", "The carbohydrate content", "The full list of ingredients",
       "The names of any fining agents used"], 0,
      "European rules that reached wine in December 2023 allow the ingredient list and most of the nutrition declaration to live behind an electronic label, but the energy value has to stay on the physical bottle. Allergen information stays printed as well, which is why the sulfite line never migrates to the code."),

    # ----------------------------------- who bottled it, and where (6) -------
    Q("Who bottled it, and where",
      "The words mis en bouteille au chateau run in small type along the bottom of a Medoc label. What has the producer committed to?",
      ["The wine was bottled at the property that grew and made it",
       "The wine was bottled by hand rather than on a line",
       "The wine spent a period in oak before bottling",
       "The wine was bottled within a year of the harvest"], 0,
      "This is the French estate-bottling formula, and it ties a single business to the whole chain: it grew the fruit, made the wine and filled the bottle at the address given. It says nothing about how the wine was handled in between or how long it was kept, so it is a statement of responsibility rather than of style or quality."),
    Q("Who bottled it, and where",
      "Two German bottles stand side by side, one reading Erzeugerabfullung and the other Gutsabfullung. Which is the tighter claim, and why?",
      ["Gutsabfullung, which requires an estate working its own vines and a wine-qualified person in charge",
       "Erzeugerabfullung, which requires the bottling to be done inside the village whose name is on the label",
       "Erzeugerabfullung, which restricts the wine to a single vineyard",
       "Neither; the two words carry identical legal force"], 0,
      "Erzeugerabfullung means producer bottling and is broad enough to cover a co-operative filling bottles from a member's fruit. Gutsabfullung is the narrow estate term, so it is the one telling a buyer that the same business farmed the vines and filled the bottle."),
    Q("Who bottled it, and where",
      "Along the foot of an Italian label runs the phrase imbottigliato all'origine. What is being claimed?",
      ["The wine was bottled in the zone where it was made, not tankered away and filled elsewhere",
       "The wine was bottled straight from the cask, with neither filtration nor fining before filling",
       "Every grape came from vineyards the bottler owns",
       "The wine was bottled in the year of the harvest"], 0,
      "Bulk wine can be moved anywhere before it is packaged, and this phrase is the Italian answer to that: the filling was done at the producer's own premises, at a co-operative's, or by a firm inside the denominated zone, and the words are reserved for DOP and IGP wines. They say nothing about who owned the vines, which is the separate claim integralmente prodotto, while a producer wanting to state only who filled the bottle uses imbottigliato da followed by a name."),
    Q("Who bottled it, and where",
      "An Italian producer's name is preceded by Azienda Agricola on one bottle and by Azienda Vinicola on another. What separates the two descriptions?",
      ["The agricola works its own vineyards, while the vinicola may buy grapes or wine in",
       "The agricola is a co-operative and the vinicola a private company",
       "The agricola may bottle only wine of the highest denomination",
       "The agricola is simply the older of the two company forms"], 0,
      "Agricola describes a farming business, so the fruit comes off land the company works. Vinicola describes a winemaking business with no farming requirement behind it at all, which means the grapes may have been bought from anyone. Either word tells a buyer more than any adjective on the front of the bottle."),
    Q("Who bottled it, and where",
      "A guest points at the words Cellared and bottled by on an American back label and asks whether the winery named there made the wine. What has that winery not done?",
      ["Carried out the fermentation", "Aged the wine", "Blended the wine",
       "Filtered the wine"], 0,
      "The phrase covers wine bought in already made and then held, blended or matured before bottling. American rules keep a separate and stricter form of words for a winery that did the fermenting itself at the address printed, so cellared is what is left when that work was done elsewhere. The winemaking that shaped the wine was somebody else's."),
    Q("Who bottled it, and where",
      "One bottle names a domaine and another a merchant house, and both carry the same appellation and vintage. Which question does the domaine name answer that the merchant name leaves open?",
      ["Who farmed the vines", "Which year the fruit was picked",
       "How long the wine was aged", "How many bottles were made"], 0,
      "A domaine bottles wine from land it works, so the name on the glass is also the name of the farmer. A merchant's trading name guarantees a house style and an address, and says nothing about who pruned, who picked or who decided the harvest date."),

    # ------------------------------------ brand, place and producer (5) ------
    Q("Brand, place and producer",
      "No turret, no manor and no gatehouse stand anywhere on the property, and yet the label reads Chateau. Is that legitimate?",
      ["Yes; on a wine label the word marks a defined holding whose wine is made on site, not a building",
       "No; the word may be used only where a building of listed historic standing survives on the property",
       "Yes, but only for wines from Bordeaux",
       "No; the word is reserved for estates ranked in the 1855 classification"], 0,
      "European rules treat the term as tied to a vineyard holding: the fruit has to come from that holding and the wine has to be made there. A modest farmhouse therefore qualifies while a grand house buying its grapes in does not, so the word describes production and not architecture."),
    Q("Brand, place and producer",
      "The largest words on a supermarket bottle are a coined two-word phrase that appears in no atlas and in no statute. What is that phrase?",
      ["A brand name owned by the producer or the retailer", "An appellation of origin",
       "A protected traditional term recognised across the European Union",
       "The name of a vineyard"], 0,
      "Type size is a marketing decision rather than a hierarchy, so the biggest words on a label are very often the element with the least legal content behind them. The origin claim may sit at half the size beneath, and it is the one that actually binds anybody to anything."),
    Q("Brand, place and producer",
      "Two place names compete for attention on an unfamiliar label. Which clue most reliably marks the one that is the appellation?",
      ["A legal designation printed with it, such as Denominacion de Origen or Appellation Controlee",
       "The name set in the larger type of the two",
       "The name that is also repeated on the capsule",
       "The name printed closest to the vintage, since the year and the origin are required to sit together"], 0,
      "Size and position are design choices that change from bottle to bottle, and a capsule or a neck band is no better a guide, but an appellation is usually printed with the formula that gives it force. The habit is not universal: Champagne needs no Appellation Controlee line because the word itself is the appellation, German labels carry Qualitatswein or a Pradikat instead, and an American AVA stands on its own. The other place name is usually the estate, a vineyard, or a brand borrowing local colour."),
    Q("Brand, place and producer",
      "The bottler's address on a French label names a town in a department far from the appellation printed above it. What does that address actually tell you?",
      ["Where the bottling was carried out, which need not be where the fruit grew",
       "That the appellation claim has been made in error and the bottle should not have been sold",
       "That the wine was declassified before bottling",
       "That the wine was made from bought-in grapes"], 0,
      "The bottler statement identifies a business and its premises for traceability, while origin is carried entirely by the appellation. The two lines can point at different places with nothing at all wrong, which is why an address is a poor guide to where a wine comes from."),
    Q("Brand, place and producer",
      "A producer line reads Cave Cooperative on one bottle and Cantina Sociale on another. What kind of business is named in each case?",
      ["A jointly owned winery vinifying fruit delivered by many member growers",
       "A merchant buying finished wine and blending it under its own name",
       "A family estate trading under a formal company name",
       "A public body that approves wine before release"], 0,
      "The members own the winery between them and bring their grapes to it, so a single name can stand for hundreds of separate holdings. Co-operatives make a very large share of the wine in many regions, and their range runs from bulk through to serious single-site bottlings."),

    # ---------------------------------------- vintage and non-vintage (5) ----
    Q("Vintage and non-vintage",
      "Millesime on a French label, Jahrgang on a German one and Annata on an Italian one all introduce the same piece of information. What is it?",
      ["The year the grapes were harvested", "The year the wine was bottled",
       "The number of bottles produced", "The average age of the vines"], 0,
      "A vintage is fixed at the harvest, so a wine picked in one year and released four years later still carries the picking year. Cosecha does the same work in Spanish, and none of these words says anything about when the bottle was actually filled."),
    Q("Vintage and non-vintage",
      "A long official number runs along the bottom of a German label and its final two digits read 21, while the front of the bottle says 2019. What do those last digits record?",
      ["The year the wine was submitted for official testing and approval",
       "The year the grapes were harvested",
       "The batch number within the estate's own records",
       "The alcoholic strength rounded to a whole number"], 0,
      "Germany's official test number is granted once a wine has passed analysis and a tasting panel, and it ends with the year that happened. A wine submitted after the turn of the year therefore carries a number that looks like a later vintage, which catches out anyone reading the small print in place of the front label."),
    Q("Vintage and non-vintage",
      "No year appears anywhere on a bottle of inexpensive branded red. What does the absence tell a buyer about the contents?",
      ["The wine is not claimed as the produce of a single harvest and may draw on more than one",
       "The wine was bottled before the year of the harvest could be established and confirmed by the authorities",
       "The wine is too young to be given a year",
       "The wine has been declassified from a higher category"], 0,
      "A year is a claim, and European rules allow it only where the fruit came overwhelmingly from the harvest named, with individual appellations free to demand the whole of it, so a wine drawing broadly on more than one picking cannot make that claim. Blending across years is a legitimate technique rather than a fault, and for such a wine the brand and the producer are what a buyer has to go on instead of a date."),
    Q("Vintage and non-vintage",
      "Shelves carry two vintages of one wine and the labels are otherwise identical. What does the year on each reliably tell a buyer?",
      ["How old the wine is", "Whether the harvest was a good one",
       "Whether the wine will improve with keeping", "How long the wine spent in barrel"], 0,
      "A vintage is a date and not a verdict. Whether a given year went well in a given place is knowledge the reader brings to the label, and readiness depends as much on the producer and the style as it does on the weather."),
    Q("Vintage and non-vintage",
      "Solera 1888 is printed across a sherry label, and the wine inside was bottled last year. What does that date record?",
      ["The year the solera was laid down, rather than a harvest",
       "The year the house was founded",
       "The year the youngest wine in the blend was picked",
       "The year the bottle was filled"], 0,
      "A fractionally blended wine has no single harvest to declare, so the date points at the establishment of the system instead. It is a claim about lineage and continuity, and a reader who takes it for a vintage will be out by more than a century."),

    # ------------------------------- strength, sweetness and volume (5) ------
    Q("Strength, sweetness and volume",
      "One bottle states 750 ml and another 75 cl, and both are ordinary full-size bottles. What is the difference between them?",
      ["None; the two figures are the same volume written in different units",
       "The centilitre bottle holds slightly less",
       "One figure is taken before corking and the other after",
       "The centilitre figure includes the volume of the punt"], 0,
      "Seven hundred and fifty millilitres and seventy-five centilitres are identical. European labels have conventionally used centilitres and American ones millilitres, so a shelf of imports shows both notations for exactly the same bottle."),
    Q("Strength, sweetness and volume",
      "The net contents line on a bottle reads 1.5 L, and the wine inside is the same as in the standard bottle beside it. What is that format called?",
      ["A magnum", "A jeroboam", "A double magnum", "A half bottle"], 0,
      "A magnum holds two standard bottles and is the first step up the ladder of large formats. More wine behind the same width of neck is the physical argument for magnums ageing more slowly, which is one of the few format claims with something behind it."),
    Q("Strength, sweetness and volume",
      "An unfamiliar white states eight percent alcohol and says nothing about sweetness anywhere on the bottle. What does the low figure most often signal?",
      ["Fermentation was stopped with grape sugar still in the wine",
       "The wine was diluted with water before bottling",
       "The wine has shed alcohol over a long ageing",
       "The wine has been through a second, malolactic fermentation"], 0,
      "Sugar that never ferments never becomes alcohol, so a wine well under ten percent has usually kept some of it. The reading is not infallible, but where a label is silent on sweetness the strength is the most useful number on the bottle."),
    Q("Strength, sweetness and volume",
      "Sweetness is stated on every sparkling wine sold in Europe and on only some still wines. What accounts for the difference?",
      ["Sugar content is an obligatory particular for sparkling wine and an optional one for still wine",
       "Sweetness in still wine cannot be measured reliably",
       "Sparkling wine is always sweetened after fermentation and still wine never is",
       "The requirement applies only to sparkling wines that took their bubbles from a fermentation in the bottle"], 0,
      "A sparkling wine can be moved a long way across the sweetness scale after its fermentation has finished, so a buyer is told where it landed. A still wine may declare sweetness and very often does not, which is why the alcohol figure and the origin do so much of the work at the table."),
    Q("Strength, sweetness and volume",
      "American labels may print the words Table Wine where a figure would otherwise go. What is that phrase declaring?",
      ["That the wine sits inside an alcohol class of roughly seven to fourteen percent",
       "That the wine is the lowest quality grade recognised in the United States",
       "That the wine carries no appellation of origin",
       "That the wine is meant to be drunk within a year"], 0,
      "It is a class designation about strength, and a producer using it need not print the exact percentage anywhere. European readers hear a quality tier in the words, which is the wrong end of the stick entirely."),

    # ----------------------------- sulfites, allergens and warnings (5) ------
    Q("Sulfites, allergens and warnings",
      "Almost every bottle sold in Europe and America carries the words contains sulfites. What triggers the requirement?",
      ["Sulphur dioxide present at ten milligrams per litre or more",
       "Any deliberate addition of sulphur dioxide at any stage",
       "Sulphur dioxide present at a hundred milligrams per litre or more",
       "The use of sulphur to sterilise the barrels"], 0,
      "Ten milligrams per litre is a very low bar, and fermentation on its own can produce that much, which is why the line appears on almost everything including wines made without any addition. It is an allergen warning aimed at a small number of sensitive people, not a comment on how the wine was made."),
    Q("Sulfites, allergens and warnings",
      "Egg white and milk casein are used to fine wine, and a label sometimes has to say so. When does that declaration become necessary?",
      ["When detectable residues remain in the finished wine",
       "Whenever either agent is used at any point",
       "Only when the wine is sold outside its country of origin",
       "Only for wines above a set alcoholic strength"], 0,
      "Both are allergens and both normally go to the bottom with the sediment they gather, so the requirement bites only where traces survive into the bottle. That is why two wines fined the same way can carry different labels, and it is the line a guest avoiding dairy or egg actually needs read out to them."),
    Q("Sulfites, allergens and warnings",
      "A paragraph headed in capitals warns of two specific hazards and appears on every bottle sold in the United States. Which two does it name?",
      ["Drinking while pregnant, and impaired ability to drive or operate machinery",
       "Drinking while pregnant, and the risk of sulphite allergy",
       "Impaired ability to drive, and the risk of addiction",
       "The risk of sulphite allergy, and the risk of liver disease"], 0,
      "The Government Warning has run in fixed wording since the late 1980s: birth defects from drinking during pregnancy, and impairment of driving and machinery, with a general note on health problems. Because the text cannot be varied it looks identical on a two dollar bottle and a two thousand dollar one."),
    Q("Sulfites, allergens and warnings",
      "A small pictogram of a pregnant woman inside a crossed circle appears on French bottles. What is its status?",
      ["It is required by French law on wine sold in France",
       "It is a voluntary mark adopted by some producers",
       "It is required only on wines above thirteen percent",
       "It is an importer's addition for export markets"], 0,
      "France made the mark compulsory in 2007, as either the pictogram or a printed sentence, and most producers chose the picture because it takes up less room. Comparable requirements have since spread through other European countries, so the symbol now appears well beyond France."),
    Q("Sulfites, allergens and warnings",
      "No added sulfites is printed on a back label. What does that claim rule out?",
      ["Deliberate addition, but not the sulphur dioxide fermentation itself produces",
       "Any sulphur dioxide whatever in the finished wine, whatever its source and however little of it",
       "The burning of sulphur candles in the cellar only",
       "Nothing at all; the phrase carries no meaning"], 0,
      "Yeast throws off small quantities of sulphur dioxide as a by-product, so a wine with nothing added can still test positive and may still have to carry the allergen line. The claim describes the winemaker's choices rather than the analysis."),

    # --------------------------------------- seals, logos and marks (5) ------
    Q("Seals, logos and marks",
      "A green rectangle carrying a leaf outlined in white stars is printed on a European back label. What does it certify?",
      ["That the fruit was farmed organically and the wine made within permitted cellar limits",
       "That the wine contains no added sulphur dioxide",
       "That no machinery was used in the vineyard",
       "That the producer belongs to a growers' association recognised by the European Commission"], 0,
      "The organic logo covers both halves of the job, since European rules were extended from the vineyard into the cellar in 2012 with limits on what may be added and a lower ceiling on sulphur. It is a method mark rather than a quality mark, and an organic wine can be as good or as poor as any other."),
    Q("Seals, logos and marks",
      "Demeter appears in small type beneath a producer's name. What does that word mark?",
      ["Certification by a private biodynamic body whose rules go beyond the organic ones",
       "A vineyard ranking granted by the appellation authority after an inspection of the site",
       "A guarantee that the wine is unfined and unfiltered",
       "The name of the co-operative that vinified the wine"], 0,
      "Biodynamic certification is private rather than statutory, and it asks for the organic baseline plus a set of preparations and a working calendar. Since no wine law recognises the standard, the mark rests entirely on its certifier's own auditing."),
    Q("Seals, logos and marks",
      "A circular symbol of two interlocking arrows sits in the small print of a European back label. What has the producer paid for?",
      ["Membership of a packaging recovery scheme, which is not a claim that the packaging is recyclable",
       "An independent audit confirming the glass is recycled",
       "A guarantee that the empty bottle can be returned to the producer against a deposit paid at the till",
       "A reduction in duty for using lighter glass"], 0,
      "The Green Dot is a licence mark: the company has contributed to the cost of collecting and sorting packaging waste in the countries where it sells. Shoppers read it as a recycling claim about the bottle in their hand, which it has never been."),
    Q("Seals, logos and marks",
      "A gold medal sticker from an international competition is stuck to the shoulder of a bottle. What does it apply to?",
      ["That wine from that harvest, judged on one day by one panel",
       "Every vintage the producer has made of that wine",
       "The producer's whole range in the year of the award",
       "The appellation, which any member may then advertise"], 0,
      "A medal goes to a specific wine from a specific year, so a sticker carried across to the next release means nothing at all. Competitions also differ enormously in entry cost and in how freely they hand medals out, which is worth knowing before treating one as evidence."),
    Q("Seals, logos and marks",
      "A numbered adhesive seal holding a random scatter of bubbles is applied to the neck of an expensive bottle. What is it there to do?",
      ["Authenticate that individual bottle, since the pattern cannot be reproduced",
       "Record the duty paid on the bottle",
       "Show the bottle has been kept at a controlled temperature since it left the cellar",
       "Certify the vineyard's farming practices"], 0,
      "Anti-counterfeiting marks have become common at the top of the market, where a fake costs the forger very little and the buyer a great deal. The pattern forms during manufacture rather than being printed, so each seal is unique and can be checked against a register."),

    # ------------------------- front label, back label, small print (5) ------
    Q("Front label, back label, small print",
      "Nothing on the front of a European bottle states the alcohol, the volume or the bottler, and all three appear together on the back. Has a rule been broken?",
      ["No; those particulars must be readable together without turning the bottle, which the back satisfies",
       "Yes; the alcoholic strength must always appear on the front label",
       "Yes; the name and address of the bottler have to be printed apart from the other obligatory particulars",
       "No, but only because the wine is sold in its country of origin"], 0,
      "European rules ask for the obligatory particulars in a single field of vision, indelible and distinguishable from the artwork around them, and say nothing about which face of the bottle that is. Designers push them to the back as a matter of course, which is why the back label is usually where the real reading is."),
    Q("Front label, back label, small print",
      "Three sentences about a family farming since 1743 and a wine made with passion fill a back label. What weight do they carry?",
      ["None under wine law; the copy is advertising, answerable to general trading rules",
       "They are verified by the appellation authority before printing",
       "They must be true or the wine loses its appellation",
       "They are checked by the importer for the market where the wine is sold"], 0,
      "Only the obligatory particulars and any regulated term are controlled by wine law, and the prose around them is advertising, answering to the general rules against misleading a buyer instead. That is not the same as unchecked: an invented family history is actionable as a false trade description wherever the wine is sold, but the remedy sits outside the wine code. The small print is where the bottler, the origin and the strength are obliged to be accurate."),
    Q("Front label, back label, small print",
      "An American bottle carries a small printed strip pasted over part of the producer's own back label. Who applied it, and why?",
      ["The importer, so the bottle carries the statements the American market requires",
       "The producer, to correct a printing error discovered after the labels were applied",
       "The retailer, to show the price and the country of origin",
       "The customs service, to show duty has been paid"], 0,
      "Obligatory statements follow the country of sale rather than the producer, so one wine sold in two markets needs two sets of them. A pasted strip is the cheapest way to add whatever a European label lacks without reprinting the original."),
    Q("Front label, back label, small print",
      "The first digits of a bottle's bar code correspond to a country. Which country is it?",
      ["The one where the company that owns the number is registered, not necessarily where the wine was made",
       "The one where the grapes were grown",
       "The one where the wine was bottled",
       "The one into which the wine was imported, since the number is issued by the customs service of that country"], 0,
      "A bar code prefix identifies the numbering organisation that issued the number to a company, so a wine made in one country by a business registered in another carries the registering country's prefix. Origin is stated in words elsewhere on the label, and the code is no shortcut to it."),
    Q("Front label, back label, small print",
      "Wine of the European Union appears where a country of origin would normally sit. What does that line tell a buyer?",
      ["The wine was blended from wine grown in more than one member state",
       "The wine comes from a member state that forbids its own name on labels",
       "The wine carries a designation covering the whole union",
       "The wine was bottled inside the union from grapes grown outside it"], 0,
      "Once wine or fruit has crossed a border and been blended, no single country can be claimed, so the union as a whole becomes the provenance. It is the broadest origin statement available, which is why such wines lean so heavily on a brand name instead."),

    # ------------------------------------ capsule, neck and closure (5) ------
    Q("Capsule, neck and closure",
      "A metal capsule on a French bottle carries an image of Marianne and a departmental number in place of the producer's own design. What is it?",
      ["A duty-paid capsule that also serves as the wine's movement document",
       "A seal applied by the appellation authority after tasting",
       "A mark showing the wine was bottled by a co-operative",
       "A guarantee the bottle has not been opened and refilled"], 0,
      "The capsule-conge is bought from the French revenue and shows the duty settled, which lets the bottle travel without separate accompanying paperwork. Colour separates the fiscal families, wine from vin doux naturel from spirits, though it no longer separates an appellation wine from an IGP, since a single lie-de-vin capsule has been allowed to stand for either since 2011. The number identifies the department where the bottler is registered."),
    Q("Capsule, neck and closure",
      "A numbered paper strip crosses the neck of an Italian bottle and tears when the capsule is cut. What does it show?",
      ["A state-issued seal, individually numbered, for a wine in the denominated system",
       "That the wine has been aged the minimum period for its category",
       "That the bottle was filled at the estate rather than by a merchant",
       "That the producer belongs to a growers' consortium"], 0,
      "The strip comes from the state printer and is issued in a controlled quantity to each producer, so the number of bottles claimed for a denomination can be checked against the seals handed out. It is a policing device and carries no verdict on how good the wine is."),
    Q("Capsule, neck and closure",
      "The vintage is printed on a narrow band around the neck and nowhere on the main label. What does that arrangement buy the producer?",
      ["One main label can be printed in bulk for every year, with only the small band changing",
       "The year can be altered after the wine has been released, since the band is not the label",
       "The wine escapes the rules governing vintage statements",
       "The bottle can be sold in markets that forbid a vintage"], 0,
      "Main labels are printed in long runs and neck bands in short ones, so splitting the year off is simply cheaper. It also means the year can go missing: soak a neck band off in an ice bucket and the bottle no longer says what it is."),
    Q("Capsule, neck and closure",
      "Drawing the cork from an old bottle reveals an estate name and a year branded along its side. What does that add to what the label says?",
      ["Corroboration that the bottle came from the named estate and the vintage claimed",
       "Proof that the wine has never been recorked or topped up since it left the cellar where it was filled",
       "A guarantee that the wine inside is sound",
       "Evidence that the bottle was filled by hand"], 0,
      "A branded cork is a second and independent statement of the same facts, and a mismatch between cork and label is among the oldest warnings of an invented bottle. It settles nothing about the condition of the wine, which only the glass can tell you."),
    Q("Capsule, neck and closure",
      "Raised letters and numbers are moulded into the base and lower body of the glass, where no label reaches. What do they identify?",
      ["The glassworks, the mould and often the year the bottle itself was made",
       "The vintage of the wine inside",
       "The number of bottles the producer filled during that particular bottling run",
       "The alcoholic strength of the wine"], 0,
      "Bottle makers mark their moulds so a faulty batch can be traced back to the plant that made it, much as a lot code traces a fill. The marks belong to the glass rather than to the wine, and glass dated later than the vintage is a well-known sign of a fake."),

    # ---------------------------------------- the bottle in the hand (3) -----
    Q("The bottle in the hand",
      "A guest wants to buy tonight's wine again at home and asks you to write it down. Which three elements must you copy?",
      ["Producer, appellation and vintage", "Brand name, colour and price",
       "Importer, alcohol and volume", "Bar code and bottle size"], 0,
      "Those three narrow a wine to one product from one year, which is what any merchant needs in order to search for it. Artwork and fanciful names are redesigned and reused constantly, and a guest who remembers only the picture on the front is very hard to help."),
    Q("The bottle in the hand",
      "The label is mould-stained and cockled and has lifted at one corner, while the fill sits high in the neck. What does the paper's condition suggest?",
      ["Long storage somewhere cool and damp, which is not in itself a problem for the wine",
       "That the bottle stood upright in a warm room",
       "That wine has leaked past the cork at some point and dried across the glass and the paper",
       "That the bottle has been refilled and relabelled"], 0,
      "Damp cellars ruin paper and look after corks, so a battered label above a good fill is usually reassuring rather than alarming. It is the level of the wine in the neck rather than the state of the printing that is worth watching."),
    Q("The bottle in the hand",
      "A regular guest insists a bottle is not the wine they had last month because the label looks entirely different, though every regulated statement on the glass is unchanged. What has happened?",
      ["The producer has redesigned the label, which changes nothing about the wine",
       "The wine has been rebottled by another company",
       "The bottle comes from a different market and holds a different blend",
       "The wine has been relabelled after a reclassification"], 0,
      "Artwork is changed for commercial reasons and carries no legal information whatever, which makes it the least reliable way to recognise a wine. Read the regulated statements instead, since those are the lines a producer cannot restyle at will, and the guest can be reassured on the spot."),
]
