"""Rank I rewrite - New Zealand (55 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

The category is built around one idea: New Zealand grows wine further from the
equator than almost anywhere else, in a narrow pair of islands sitting in a
large cold ocean, so nothing here behaves the way its latitude predicts. Cool
sea air, strong ultraviolet light and nights that fall away hold acidity and
aroma in place while the fruit ripens, and the single region that escapes the
sea escapes it completely. That gives the running order: light, ocean and
mountains first, then the map and the short history that produced it, then the
regions in the order a student meets them from Marlborough southward and back
up the North Island, then the grapes that are not Sauvignon Blanc, and finally
the two things the industry decided collectively rather than winery by winery,
its closure and its sustainability audit. Stems lead with a rock, a wind, a
harvester working at night, a scene at the table or a bottle in the hand, and
let the region, grape or compound be the answer.

Everything is ASCII: Rhone, Medoc, Gewurztraminer, Muller-Thurgau.
"""

from lib import Q

CAT = "New Zealand"
SLUG = "r1-new-zealand"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Latitude, light and maritime climate", 5),
    ("The wine map, its history and its rules", 4),
    ("Marlborough", 7),
    ("Sauvignon Blanc, the style and its making", 6),
    ("Nelson, Canterbury and Waipara", 5),
    ("Central Otago", 6),
    ("Hawke's Bay", 6),
    ("Wairarapa and Martinborough", 4),
    ("Gisborne, Auckland and the north", 4),
    ("Grapes beyond Sauvignon Blanc", 4),
    ("Closures and sustainability", 4),
]

BANK = [
    # -------------------------- latitude, light and maritime climate (5) -----
    Q("Latitude, light and maritime climate",
      "Clean southern air and a thin ozone layer put New Zealand vineyards under stronger ultraviolet light than European sites the same distance from the equator. What does that intensity do in the vineyard?",
      ["It pushes the skins to build colour, tannin and aroma compounds, while the cool air keeps sugar from running away with them",
       "It drives sugar up so fast that most fruit has to be picked before its flavour arrives",
       "It sterilises the vineyard, so fungal disease is effectively unknown there",
       "It bleaches the skins, which is why black varieties are barely planted"], 0,
      "Ultraviolet light is a stress, and a vine answers it by thickening skins and laying down phenolics and flavour precursors in them. Because the surrounding ocean keeps daytime heat modest at the same time, that build-up happens without the runaway ripeness a sunny warm climate would bring, which is much of why the aromatic whites shout so loudly."),
    Q("Latitude, light and maritime climate",
      "A single mountain chain runs almost the whole length of the South Island, and every vineyard on that island lies to the east of it. Which chain?",
      ["The Southern Alps", "The Richmond Range",
       "The Tararua Ranges", "The Kaikoura Ranges"], 0,
      "The Alps stand across the prevailing westerlies and wring them dry, so the west coast is one of the wettest inhabited places on earth while Marlborough and Central Otago are among the driest corners of the country. The Richmond Range is a local barrier between Nelson and Marlborough, and the Tararuas belong to the North Island."),
    Q("Latitude, light and maritime climate",
      "Blenheim lies about as far from the equator as Rome, yet its Sauvignon Blanc arrives with an acidity no Roman grower could hope for. What accounts for the mismatch?",
      ["Cold ocean surrounds the entire country, so sea temperature rather than latitude sets the growing season",
       "The vineyards sit above a thousand metres, and the coolness is altitude rather than anything else",
       "Harvest dates are fixed by law early enough to protect acidity",
       "The vines are grown under shade cloth to slow the ripening down"], 0,
      "Rome sits at roughly forty-two degrees north and Blenheim at roughly forty-one degrees south, and they have almost nothing else in common. A narrow island chain in a large cool ocean has mild summers, cool nights and a small seasonal swing, so latitude on its own predicts nothing about a maritime climate."),
    Q("Latitude, light and maritime climate",
      "Ringed by mountains and lying further from the sea than any other New Zealand wine district, one region gets hot dry summers, hard frosts and a daily temperature swing no coastal site can match. Which region?",
      ["Central Otago", "Marlborough", "Hawke's Bay", "Nelson"], 0,
      "Central Otago is the country's only semi-continental wine climate, and everything about it follows from being inland and enclosed: low rainfall, fierce summer days, cold nights and a real winter. Every other New Zealand region is maritime, with the sea holding its temperature inside a narrow band."),
    Q("Latitude, light and maritime climate",
      "Spray programmes, leaf plucking and open canopies take up more of a New Zealand grower's season than irrigation ever does. Which pressure sets that agenda?",
      ["Humidity and rain arriving during the growing season, which make fungal disease the standing threat",
       "Sustained drought, which makes water the limiting factor almost everywhere",
       "Spring hail, which strips the shoots in the majority of vintages",
       "Salt-laden wind, which burns the leaves off the vine"], 0,
      "A maritime climate delivers rain in summer as well as winter, and warm damp air in a dense canopy is what botrytis and the mildews want. Opening the fruiting zone so it dries after rain is therefore the central vineyard task, and only Central Otago farms in conditions dry enough to change that calculation."),

    # -------------------- the wine map, its history and its rules (4) --------
    Q("The wine map, its history and its rules",
      "Wellington and Blenheim face each other across the water dividing New Zealand's two main islands. What is that stretch of water called?",
      ["Cook Strait", "Bass Strait", "Foveaux Strait", "Tasman Bay"], 0,
      "Cook Strait separates the North Island from the South Island and is crossed constantly by the ferries carrying fruit, wine and tanks between them. Bass Strait divides Australia from Tasmania, Foveaux Strait cuts off Stewart Island in the far south, and Tasman Bay is the water Nelson curls around."),
    Q("The wine map, its history and its rules",
      "Driving the length of the country from the northernmost vineyards to the southernmost, in what order do these four regions arrive?",
      ["Northland, Gisborne, Marlborough, Central Otago",
       "Gisborne, Northland, Central Otago, Marlborough",
       "Northland, Marlborough, Gisborne, Central Otago",
       "Gisborne, Marlborough, Northland, Central Otago"], 0,
      "Northland occupies the far north of the North Island, Gisborne sits on its east coast, Marlborough begins the South Island across Cook Strait, and Central Otago lies deep inland in the south. Nothing commercial is planted south of Central Otago, which makes it the end of the drive."),
    Q("The wine map, its history and its rules",
      "A grape glut in the mid-1980s had the government paying growers to pull vines out, and roughly a quarter of the national vineyard came out of the ground. Which variety lost the most?",
      ["Muller-Thurgau", "Sauvignon Blanc", "Pinot Noir", "Chardonnay"], 0,
      "Muller-Thurgau was a German crossing planted for volume, and it was the country's most planted variety well into the early 1990s, making cheap off-dry white sold in flagons and casks. The vine pull cleared the ground that Sauvignon Blanc and Chardonnay then took, and New Zealand's identity abroad changed completely within a decade."),
    Q("The wine map, its history and its rules",
      "A producer wants Nelson printed on the front of a wine blended from seventy percent Nelson fruit and thirty percent Marlborough. Why is that label not allowed?",
      ["A stated place must account for at least eighty-five percent of the wine, and seventy falls short",
       "Blending fruit across regional boundaries is prohibited outright in New Zealand",
       "Nelson holds no registered name, so it may never appear on a label at all",
       "Marlborough fruit may only ever be sold under the Marlborough name"], 0,
      "One threshold governs place, grape and vintage alike, so this blend may be labelled New Zealand but not Nelson. The registered name settles where the fruit grew and nothing more: it sets no rule on which grape is planted, how heavily it crops or how long the wine spends in oak."),

    # ----------------------------------------------------- Marlborough (7) ---
    Q("Marlborough",
      "Broad, flat and floored with rounded stones dropped by a braided river on its way to the sea, this is where Marlborough's first modern vines went in. Which valley?",
      ["The Wairau Valley", "The Awatere Valley",
       "The Waihopai Valley", "The Moutere Valley"], 0,
      "The Wairau runs west to east and empties into Cloudy Bay, and its free-draining stony terraces are the classic ground for Marlborough Sauvignon Blanc. The Waihopai is a tributary valley opening into it from the south, and Moutere belongs to Nelson on the other side of the ranges."),
    Q("Marlborough",
      "Higher, drier, windier and wide open to the ocean, this Marlborough valley picks a fortnight after its neighbour and gives Sauvignon Blanc of tomato leaf, green herb and a saline snap. Which valley?",
      ["The Awatere Valley", "The Wairau Valley",
       "The Waihopai Valley", "The Moutere Hills"], 0,
      "The Awatere lies south over the Wither Hills, climbs a hundred or two metres above the Wairau floor in its upper reaches and sits closer to the cold open Pacific. Cooler and more exposed means later ripening, sharper acidity and far more of the green pyrazine character that the warmer Wairau floor loses."),
    Q("Marlborough",
      "Clay-rich side valleys such as Omaka, Fairhall and Brancott run into the Wairau from the south, and growers plant them to something other than Sauvignon Blanc. Which grape?",
      ["Pinot Noir", "Riesling", "Gewurztraminer", "Cabernet Sauvignon"], 0,
      "Clay holds water where the shingle of the valley floor lets it straight through, and that steadier supply suits Pinot Noir. More Pinot Noir is planted in Marlborough than in any other New Zealand region, split between still red off these southern slopes and base wine for sparkling."),
    Q("Marlborough",
      "Marlborough had been out of the wine business for four decades when a large wine company gambled on land the district had run sheep on, and Sauvignon Blanc went into that ground within a couple of seasons. In which decade?",
      ["The 1970s", "The 1930s", "The 1950s", "The 1990s"], 0,
      "The first modern planting went in during 1973, Sauvignon Blanc followed in 1975 and the first Marlborough Sauvignon Blanc came off the 1979 vintage. Within twenty years that wine had become the way the rest of the world recognised New Zealand, which is a faster rise than any other region in the country has managed. Marlborough had grown wine long before, at David Herd's Auntsfield from 1873, but that business closed in the 1930s and the land went back to grazing."),
    Q("Marlborough",
      "Under a thin skin of topsoil the Wairau plain runs metres deep in old river shingle, and growers in a rainy maritime climate treat that as a gift. What does the shingle do for them?",
      ["It drains hard and holds very little, so a vine that would otherwise run to leaf is held in check",
       "It supplies potassium the vine could not obtain from any other soil",
       "It stores winter rain and releases it back through a dry summer",
       "It shields the roots from phylloxera, so grafting is unnecessary"], 0,
      "Growing-season rain plus a deep fertile soil equals vigour, and a vine still growing at veraison shades its own fruit and gives thin green wine. Shingle limits both water and nutrition, so growth stops at the right moment without the grower having to force it."),
    Q("Marlborough",
      "Growers set aside Marlborough's coolest, latest-ripening blocks for a use that wants the fruit off the vine earlier than a still wine would take it. What makes those sites an asset rather than a liability?",
      ["They hold high acidity at low sugar, which is what a base wine for bottle fermentation needs",
       "They ripen fast enough to reach the high alcohol a base wine has to start from",
       "They attract the botrytis a base wine depends on for texture",
       "They give the deep colour a blanc de noirs is graded on"], 0,
      "A sparkling base wants flavour at low sugar and very high acidity, which is exactly what a cool Marlborough site hands over without any coaxing. Most of the fruit behind New Zealand's serious bottle-fermented sparkling wine is grown there, whoever puts their name on the label."),
    Q("Marlborough",
      "Assembling a wine labelled simply Marlborough, a winemaker blends parcels off the valley floor with parcels grown south over the hills. What does each side bring?",
      ["Ripe tropical weight from the Wairau, herbal cut and acidity from the Awatere",
       "Oak character from the Wairau and stainless steel character from the Awatere",
       "Sweetness from the Awatere and alcohol from the Wairau",
       "Colour from the Wairau and tannin from the Awatere"], 0,
      "The regional name covers both valleys, so the blend is legal, and it is how most large-volume Marlborough Sauvignon is actually built. The two ripen a fortnight apart and taste like different wines, which is precisely what makes combining them worth the trouble."),

    # ------------------ Sauvignon Blanc, the style and its making (6) --------
    Q("Sauvignon Blanc, the style and its making",
      "Green capsicum, cut grass and blackcurrant leaf in a Sauvignon Blanc come from a family of compounds that sunlight and warmth break down. What are they?",
      ["Methoxypyrazines", "Volatile thiols", "Terpenes", "Esters"], 0,
      "Pyrazines are present in the berry from early on and fall away as the fruit is exposed to sun and heat, so a cool shaded site keeps them and a hot exposed one does not. The Awatere retains far more of them than the warmer Wairau floor, which is most of why the two valleys smell so different."),
    Q("Sauvignon Blanc, the style and its making",
      "Passionfruit, grapefruit and a boxwood note are absent from the juice and appear only once the ferment is running, because yeast cuts them free from odourless precursors. Which compounds are these?",
      ["Volatile thiols", "Methoxypyrazines", "Anthocyanins", "Higher alcohols"], 0,
      "Thiols travel into the juice bound and inert, and how many are released depends on the yeast strain and on the handling of the fruit. Machine picking and a little time on skins raise the precursor load, which is one reason the Marlborough style holds together so consistently at enormous volume."),
    Q("Sauvignon Blanc, the style and its making",
      "A winery chasing the classic Marlborough profile wants the aromatics unmasked and the acidity untouched. Which set of cellar decisions belongs to that aim?",
      ["Cool fermentation in stainless steel, malolactic conversion blocked, no oak, early bottling",
       "Warm fermentation in new oak, full malolactic conversion, two years in barrel",
       "A month of fermentation on the skins, then ageing in buried clay",
       "Fermentation halted with grape spirit, then bottling under cork"], 0,
      "Malolactic conversion would trade the wine's sharp malic acid for softer lactic acid and lay a dairy note over the fruit, and oak would simply cover the thiols the whole style rests on. Every choice in the recipe exists to get the vineyard's aromatics into bottle unaltered."),
    Q("Sauvignon Blanc, the style and its making",
      "Harvesters work Marlborough's Sauvignon Blanc rows through the small hours with their headlights on. Beyond the machine's own convenience, what does picking in the dark protect?",
      ["Cold fruit oxidises slowly, so the aroma precursors survive the wait for the press",
       "Cold fruit ferments faster once crushed, which shortens the vintage",
       "Night picking raises the sugar reading recorded at the weighbridge",
       "Darkness stops pyrazines forming in the berry overnight"], 0,
      "Warm juice browns and loses volatile compounds within hours, and a crop this size cannot all reach a press immediately. Fruit arriving at ten or twelve degrees rather than twenty-five buys the winery hours it would otherwise not have, and Marlborough now picks this way at a scale matched almost nowhere else."),
    Q("Sauvignon Blanc, the style and its making",
      "Sancerre and Marlborough ferment the same variety, yet the New Zealand wine smells several times louder. Which difference in the growing season does most of that work?",
      ["Long bright days over cold nights, which build ripe thiol character while holding on to acid and green aroma alike",
       "Far heavier crops, which dilute the wine and exaggerate its aromatics",
       "A different grape entirely, sold under a borrowed name",
       "A long spell in new oak before the wine is released"], 0,
      "Sancerre ripens through a moderate continental summer and arrives flinty and restrained. Marlborough ripens under intense light with nights that drop away sharply, so it reaches tropical thiol ripeness without shedding either its pyrazine edge or its acidity, and the two wines have made one grape mean two quite different things."),
    Q("Sauvignon Blanc, the style and its making",
      "Some producers ferment Marlborough Sauvignon Blanc with wild yeast in old barrels and leave it on its lees for a year. What are they trying to gain?",
      ["Texture, savoury complexity and the ability to age, in place of an immediate aromatic burst",
       "A higher alcohol level than the standard style can reach",
       "Residual sugar, since a barrel ferment always stops early",
       "The legal right to use the regional name on the label"], 0,
      "The mainstream style is bottled young, drunk young, and fading after two or three years. Lees ageing and old wood build a broader, more mineral wine that behaves more like white Bordeaux, and the price of it is the passionfruit rush that made the region's name in the first place."),

    # -------------------------- Nelson, Canterbury and Waipara (5) -----------
    Q("Nelson, Canterbury and Waipara",
      "Cross the Richmond Range westward out of Marlborough and you drop into a smaller, wetter region curled around a sheltered bay. Which region?",
      ["Nelson", "Waipara", "Wairarapa", "Gisborne"], 0,
      "Nelson sits on Tasman Bay and trades sunshine records with Marlborough, but it takes considerably more rain, so disease pressure and picking decisions matter more there. It is a region of many small producers making aromatic whites, Chardonnay and Pinot Noir rather than one of large volume."),
    Q("Nelson, Canterbury and Waipara",
      "Nelson splits between a flat plain of river gravels and a set of heavier clay hills that ripen later and give denser wine. What are the hills called?",
      ["The Moutere Hills", "The Waimea Plains",
       "The Wither Hills", "The Teviotdale Hills"], 0,
      "Moutere is old weathered clay-gravel and it holds water where the Waimea shingle drains it straight away, so the two halves of one small region ripen quite differently. The Wither Hills divide the Wairau from the Awatere in Marlborough, and the Teviotdale Hills shelter Waipara."),
    Q("Nelson, Canterbury and Waipara",
      "North of Christchurch a valley lies behind a low range that blocks the cold easterly off the sea, so it ripens warmer than the plains around it. Which valley?",
      ["Waipara", "Moutere", "Gibbston", "Te Muna"], 0,
      "The Teviotdale Hills take the sea breeze out of the afternoon, and Waipara runs noticeably warmer than Christchurch at the same latitude. It lies inside the North Canterbury region, which is the name most labels now carry."),
    Q("Nelson, Canterbury and Waipara",
      "Limestone under parts of the Waipara Valley and a long dry autumn have made two grapes the district's calling card. Which pair?",
      ["Riesling and Pinot Noir", "Sauvignon Blanc and Merlot",
       "Chardonnay and Syrah", "Pinot Gris and Cabernet Franc"], 0,
      "Waipara Riesling runs from bone dry to frankly sweet and holds a lime-and-honey line that rewards a decade in bottle. Its Pinot Noir is savoury and firm rather than plush, and both grapes depend on the long ripening period the shelter behind the hills makes possible."),
    Q("Nelson, Canterbury and Waipara",
      "Out on the flat shingle plains around Christchurch the wind comes straight off the Pacific and the season is short and cool. What does that ground favour?",
      ["Lean high-acid whites and light-bodied Pinot Noir",
       "Full-bodied Cabernet Sauvignon", "Fortified wine matured in old wood",
       "Late-harvest botrytised sweet wine"], 0,
      "The Canterbury Plains are gravel washed off the Alps, cold, exposed and quick to give up their heat, so a thick-skinned late-ripening variety will never finish there. The region's more serious wines come from Waipara to the north, where the shelter and the extra warmth change what is possible."),

    # --------------------------------------------------- Central Otago (6) ---
    Q("Central Otago",
      "Vines in Central Otago push their roots into loess lying over a grey metamorphic rock that splits into glinting plates. Which rock?",
      ["Schist", "Basalt", "Limestone", "Granite"], 0,
      "Otago schist formed under heat and pressure from old sea-floor sediment, and it fractures along its layers, so roots follow the cracks down to moisture. The loess above it is a fine wind-blown silt, and that pairing of a shallow fertile blanket over fractured rock is what growers there mean when they talk about their soils."),
    Q("Central Otago",
      "The coolest and highest of Central Otago's subdistricts sits in a river gorge, picks last of all and makes the most delicate Pinot Noir in the region. Which one?",
      ["Gibbston", "Bannockburn", "Bendigo", "Alexandra"], 0,
      "Gibbston is squeezed into the Kawarau gorge above the Cromwell basin and sits at around 320 to 420 metres, roughly a hundred metres above Bannockburn, so in a cold year the fruit barely arrives. When it does, the wine is perfumed and fine-boned rather than powerful, which is a style the rest of the region cannot easily copy."),
    Q("Central Otago",
      "North-facing slopes above Lake Dunstan catch more sun than anywhere else in Central Otago and give the region's richest, darkest Pinot Noir. Which subregion?",
      ["Bendigo", "Gibbston", "Wanaka", "Alexandra"], 0,
      "South of the equator the north-facing slope is the sunny one, and Bendigo's terraces above the lake are the warmest ground in Central Otago. Gibbston is the coldest of the subdistricts and Wanaka sits apart to the north-west, beside its own lake rather than in the Cromwell basin."),
    Q("Central Otago",
      "Helicopters hover over Central Otago vineyards before dawn in spring, and wind machines turn all night beside them. Which hazard are the growers fighting?",
      ["Frost", "Hail", "Botrytis", "Sunburn"], 0,
      "On a clear still night cold air pools on the valley floor while warmer air sits above it, and a machine or a helicopter simply mixes the two. An inland basin ringed by mountains delivers exactly those nights, and frost is the standing price Central Otago pays for its dry sunny days."),
    Q("Central Otago",
      "A summer day in the Cromwell basin can pass thirty degrees while the night that follows falls towards five. What does that swing give the region's Pinot Noir?",
      ["Deep colour and ripe tannin built by day, with acidity preserved through the cold nights",
       "Very high alcohol and a soft low-acid texture",
       "Green herbaceous flavours that never quite ripen out",
       "A pale colour with almost no tannin at all"], 0,
      "Ripening is driven by daytime warmth while acid is burned away through warm nights, so a wide daily range lets the two be pulled apart. It is the same mechanism that makes high-altitude vineyards work in hot countries, produced here by distance from the sea instead of by height."),
    Q("Central Otago",
      "Gold miners planted the first Central Otago vines in the 1860s, after which the district went most of a century without commercial wine. When did the modern revival take hold?",
      ["The 1980s", "The 1920s", "The 1950s", "The 2000s"], 0,
      "Experimental blocks went in through the 1970s and the first commercial releases followed in the 1980s, once it was clear that Pinot Noir could ripen somewhere this extreme. Growth since has been rapid, and Pinot Noir now accounts for the great bulk of everything planted there."),

    # ------------------------------------------------------ Hawke's Bay (6) --
    Q("Hawke's Bay",
      "French missionaries needing altar wine founded New Zealand's oldest surviving winery in 1851. In which region does it still stand?",
      ["Hawke's Bay", "Northland", "Auckland", "Marlborough"], 0,
      "The Marist brothers settled on the east coast of the North Island and have made wine there ever since, which makes Hawke's Bay the oldest wine region of consequence in the country. It is also the second most planted, behind Marlborough and well ahead of everywhere else."),
    Q("Hawke's Bay",
      "A flood in 1867 shifted a Hawke's Bay river off its course and left a bed of bare grey stones that farmers wrote off as worthless. What stands on that ground now?",
      ["The Gimblett Gravels", "The Bridge Pa Triangle",
       "The Martinborough Terrace", "Te Awanga"], 0,
      "The Ngaruroro River abandoned the bed, and the shingle was quarried for road metal long before anyone thought to plant it. It is now the most closely watched red wine ground in New Zealand, given over to Bordeaux varieties and Syrah, with the Bridge Pa Triangle its near neighbour on deeper soils."),
    Q("Hawke's Bay",
      "No government committee drew the boundary of the Gimblett Gravels, and no parish or council line marks it out. What fixes it instead?",
      ["The extent of a single soil type, so the district stops where the gravels stop",
       "A ten-kilometre radius drawn from the centre of Hastings",
       "The land held by the growers who founded the association, wherever it lies",
       "A minimum height above sea level written into the rules"], 0,
      "The boundary was traced from the soil survey, and the name itself is protected as a trademark held by the growers' association. A wine may carry it only if the overwhelming majority of its fruit was grown inside that soil line, which is an unusually strict rule for a New World appellation."),
    Q("Hawke's Bay",
      "Bare stones across a vineyard floor soak up the day's heat and hand it back after sundown. Which grape does that most obviously rescue in Hawke's Bay?",
      ["Cabernet Sauvignon", "Pinot Noir", "Riesling", "Sauvignon Blanc"], 0,
      "Cabernet ripens late and fails almost everywhere else in New Zealand, arriving green, hard and hollow. The stored warmth of the gravels supplies just enough extra heat at the end of the season to carry it home, which is why most of the country's serious Cabernet blends come from this stretch of ground, with Waiheke Island the only real rival."),
    Q("Hawke's Bay",
      "Black pepper, violets and a medium body rather than jam and sweetness: Hawke's Bay has built an international reputation on one Rhone red. Which?",
      ["Syrah", "Grenache", "Mourvedre", "Carignan"], 0,
      "Picked in a cool maritime autumn the grape keeps its peppery, floral register and lands nearer the northern Rhone than South Australia. New Zealand producers almost always print Syrah rather than Shiraz, and the choice of word is a deliberate statement about what is in the bottle."),
    Q("Hawke's Bay",
      "Ordering the classic Hawke's Bay red, a guest is handed a blend rather than a single varietal wine. Which grapes are in the bottle?",
      ["Merlot, Cabernet Sauvignon, Cabernet Franc and Malbec",
       "Syrah, Grenache and Mourvedre", "Pinot Noir and Pinot Meunier",
       "Tempranillo, Graciano and Garnacha"], 0,
      "Merlot leads most of these blends because it ripens more dependably than Cabernet Sauvignon in a maritime autumn, with Cabernet Franc and Malbec adding perfume and colour. The model is the Right Bank of Bordeaux rather than the Medoc, even on the warmest gravels."),

    # --------------------------------- Wairarapa and Martinborough (4) -------
    Q("Wairarapa and Martinborough",
      "A soil and climate survey in the late 1970s singled out a gravel terrace at the southern end of the North Island as the country's most promising Pinot Noir ground, and vines went in within two years. Which district?",
      ["Martinborough", "Gisborne", "Waipara", "Bendigo"], 0,
      "The survey weighed rainfall, temperature and soils against Burgundy and pointed at this one terrace, which makes it a rare case of a wine region founded on a report rather than on habit. A handful of small wineries were established there around 1980 and the reputation followed inside a decade."),
    Q("Wairarapa and Martinborough",
      "Wind funnels through a gap in the ranges and hammers Martinborough's vines through flowering every spring. What does that battering do to the wine?",
      ["It cuts the crop and thickens the skins, giving small quantities of concentrated, firmly structured wine",
       "It strips acidity out of the fruit, giving soft early-drinking wine",
       "It spreads botrytis through the canopy, so most fruit is picked sweet",
       "It delays ripening so far that the fruit has to be picked green"], 0,
      "Wind at flowering knocks off potential berries before they ever set, and continued exposure leaves the vine with smaller fruit and thicker skins. That is why Martinborough makes so little wine, and why what it does make is denser than the size of the district would suggest."),
    Q("Wairarapa and Martinborough",
      "Martinborough, Gladstone and Masterton all sit inside one registered region at the bottom of the North Island. What is that region called?",
      ["Wairarapa", "North Canterbury", "Nelson", "Waiheke"], 0,
      "Wairarapa is the official name and Martinborough the sub-district that made it famous, an hour or so over the hill from Wellington. It is among the smallest producing regions in the country by volume and among the most highly regarded by reputation."),
    Q("Wairarapa and Martinborough",
      "Shielded from the prevailing westerlies by the Tararua Ranges, Martinborough stays markedly drier through autumn than Wellington an hour away. Why does that dryness matter so much to its Pinot Noir?",
      ["Fruit can be left hanging to ripen fully without dilution or rot setting in",
       "It removes any need to prune the vine or manage its canopy",
       "It concentrates sugar so far that chaptalisation becomes compulsory",
       "It guarantees the botrytis the district's sweet wines depend on"], 0,
      "Pinot Noir has thin skins and tight bunches and rots readily in a wet autumn, so how long a region dares leave fruit on the vine decides how ripe its tannin gets. For this grape a dry autumn is worth more than a warm summer."),

    # -------------------------- Gisborne, Auckland and the north (4) ---------
    Q("Gisborne, Auckland and the north",
      "Fertile alluvial flats on the east coast of the North Island, warm and humid with autumn rain a real risk, and a long-standing claim to be the country's Chardonnay capital. Which region?",
      ["Gisborne", "Hawke's Bay", "Nelson", "Wairarapa"], 0,
      "Gisborne is warm enough to ripen easily and fertile enough to crop heavily, which pushed it toward volume for most of its history. Its Chardonnay is broad and tropical rather than tight and mineral, and Gewurztraminer and Pinot Gris do well on the same flats."),
    Q("Gisborne, Auckland and the north",
      "An island in the harbour off New Zealand's largest city runs warmer and drier than the mainland beside it, and its growers plant Bordeaux reds and Syrah rather than Pinot Noir. Which island?",
      ["Waiheke Island", "Stewart Island", "Great Barrier Island", "Kapiti Island"], 0,
      "Waiheke sits in the Hauraki Gulf a short ferry ride from Auckland, in a partial rain shadow with sea on every side holding off both frost and extreme heat. Land there is scarce and expensive, so the wines are made in small quantities and priced accordingly."),
    Q("Gisborne, Auckland and the north",
      "Croatian families who came to dig kauri gum in the nineteenth century planted vines west of Auckland, and their surnames are still on labels there. Which white grape is that district best known for now?",
      ["Chardonnay", "Riesling", "Sauvignon Blanc", "Gewurztraminer"], 0,
      "The Dalmatian settlers stayed on, and their descendants founded several of the country's oldest wine companies, most of which still keep their head offices around Auckland. Kumeu, north-west of the city, has become New Zealand's benchmark address for tightly built barrel-fermented Chardonnay grown on heavy clay."),
    Q("Gisborne, Auckland and the north",
      "The first grapevines planted in New Zealand went into the ground in the far north in 1819. Who put them there?",
      ["The missionary Samuel Marsden", "The British Resident James Busby",
       "A French Marist brother", "A Dalmatian gum digger"], 0,
      "Marsden planted at Kerikeri in the Bay of Islands and left no record of any wine being made from the fruit. Busby, who arrived later and planted at Waitangi, is credited with the first recorded New Zealand wine, which a visiting French navigator tasted and praised around 1840."),

    # ---------------------------------- grapes beyond Sauvignon Blanc (4) ----
    Q("Grapes beyond Sauvignon Blanc",
      "One black grape covers more New Zealand ground than every other red variety put together, and it succeeds on river gravel, hillside clay and glacial schist alike. Which?",
      ["Pinot Noir", "Merlot", "Syrah", "Cabernet Sauvignon"], 0,
      "Pinot Noir wants a long cool ripening season and a dry autumn, and most of the country offers exactly that. A great deal of the crop never appears as a red at all, because it also underpins the traditional-method sparkling wines."),
    Q("Grapes beyond Sauvignon Blanc",
      "Pear, spice and a broad soft texture, often with a trace of sugar left in, describe a white that went from almost nothing to one of the country's most planted. Which variety?",
      ["Pinot Gris", "Chenin Blanc", "Viognier", "Semillon"], 0,
      "Pinot Gris arrived late and spread quickly, offering drinkers a rounder alternative to the Sauvignon Blanc that surrounds them. Styles run from bone dry in the Alsace manner to noticeably sweet, so the producer rather than the variety decides what turns up in the glass."),
    Q("Grapes beyond Sauvignon Blanc",
      "From tightly wound barrel-fermented bottlings in the north to Gisborne's broad tropical ones, this grape is taken seriously in almost every New Zealand region. Which?",
      ["Chardonnay", "Riesling", "Sauvignon Blanc", "Pinot Gris"], 0,
      "Chardonnay takes its character from the site and the cellar rather than from itself, which is why it turns up everywhere and tastes different each time. New Zealand's examples are built on high natural acidity, so they carry oak and lees work without turning heavy."),
    Q("Grapes beyond Sauvignon Blanc",
      "Outside the warmest gravels of Hawke's Bay and Waiheke, Cabernet Sauvignon struggles to finish ripening in New Zealand. Which Bordeaux grape carries most of the country's red blends instead?",
      ["Merlot", "Malbec", "Petit Verdot", "Carmenere"], 0,
      "Merlot ripens earlier and far more dependably in a maritime autumn, and it gives flesh where Cabernet gives structure. Cabernet Franc and Malbec appear in the same blends in smaller proportions, and Petit Verdot ripens even later than Cabernet Sauvignon, so it is planted barely at all."),

    # ------------------------------------ closures and sustainability (4) ----
    Q("Closures and sustainability",
      "A three-year-old New Zealand Sauvignon Blanc still smells of passionfruit and cut grass. Which property of the closure it wears is doing that work?",
      ["It admits very little oxygen, and does so at the same rate in every bottle",
       "It admits more oxygen than cork, which keeps the wine lively",
       "It releases sulphur dioxide slowly into the headspace",
       "It allows a slow secondary fermentation to carry on in bottle"], 0,
      "Thiols and pyrazines are fragile and oxidise readily, so an aromatic white loses its entire point if the seal leaks. Consistency matters as much as the low ingress: a case sealed with cork varies bottle to bottle, and a case under screwcap does not."),
    Q("Closures and sustainability",
      "An expensive New Zealand red built to spend twenty years in a cellar is very likely to be sealed the same way as a supermarket Sauvignon Blanc. What does that reveal about the country's approach to closures?",
      ["The screwcap is used right across the range rather than treated as a budget option",
       "Cork is reserved by law for wines above a set price",
       "Screwcaps are permitted on white wine only",
       "Screwcaps were adopted because cork cannot be obtained in the southern hemisphere"], 0,
      "New Zealand producers moved together at the start of the 2000s rather than one winery at a time, and the change reached the top of the range as fast as the bottom. The argument since has not been whether to use a screwcap but how much oxygen the liner should let through for a wine meant to age."),
    Q("Closures and sustainability",
      "An independently audited national scheme scores New Zealand growers on soil, water, agrichemicals, energy, waste and the people they employ, and almost the whole producing vineyard area takes part. What is it called?",
      ["Sustainable Winegrowing New Zealand", "Entwine",
       "Integrated Production of Wine", "The Wine Standards Board"], 0,
      "The programme began in the mid-1990s and grew into a condition of joining the industry's own export marketing, which is why participation is close to universal rather than a minority badge. Entwine was the Australian scheme until it was folded into Sustainable Winegrowing Australia in 2019, and Integrated Production of Wine is the South African one."),
    Q("Closures and sustainability",
      "A bottle certified organic in New Zealand has met a different standard from the national sustainability programme most of the country's vineyards belong to. Where do the two part company?",
      ["Organic certification bans synthetic agrichemicals outright, while the sustainability scheme measures and limits their use inside a wider scorecard",
       "Organic certification governs the winery only, and the sustainability scheme the vineyard only",
       "The organic standard applies to exports and the sustainability scheme to the home market",
       "They are the same scheme operating under two different names"], 0,
      "A sustainability audit takes in energy, water, waste and employment as well as spraying, so it covers ground the organic standard never touches. What it does not do is prohibit a synthetic spray outright, and that single difference is why a producer might pursue both certifications at once."),
]
