"""Rank I rewrite - Portugal (58 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

The category is organised the way the country actually changes: Atlantic and
granite in the Minho, schist and heat up the Douro, mountain-ringed granite in
the Dao, cold clay in Bairrada, hot plains in the Alentejo, sand and estuary
around Lisbon, then the islands. Port is deliberately light because the
Sparkling, Fortified and Sweet category carries it. Stems lead with a soil, a
symptom, a training system or a scene at the table and let the region, the
grape or the term be the answer.
"""

from lib import Q

CAT = "Portugal"
SLUG = "r1-portugal"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("The Portuguese wine map", 4),
    ("Vinho Verde", 8),
    ("The Douro", 9),
    ("Dao and Bairrada", 8),
    ("Alentejo and the south", 6),
    ("Setubal, Bucelas and Colares", 6),
    ("Madeira and the Azores", 8),
    ("Native grapes", 5),
    ("Cork and the label", 4),
]

BANK = [
    # -------------------------------------- the Portuguese wine map (4) ------
    Q("The Portuguese wine map",
      "Rainfall falls and heat rises steadily as you travel from the Minho down to the Alentejo. Which climatic shift does that describe?",
      ["Atlantic maritime in the north-west giving way to Mediterranean conditions in the south",
       "Mediterranean conditions in the north giving way to maritime conditions in the south",
       "One uniform Mediterranean climate across the whole mainland",
       "Alpine conditions in the north giving way to desert in the south"], 0,
      "The north-west takes the weather off the ocean full in the face and can receive well over a metre of rain a year, while the southern plains bake through a long dry summer. Almost every difference in Portuguese wine style follows that line."),
    Q("The Portuguese wine map",
      "A Portuguese label carries no DOC and no village, yet still claims a broad origin such as Alentejano or Lisboa. Which tier is that?",
      ["Vinho Regional", "Denominacao de Origem Controlada",
       "Indicacao de Proveniencia Regulamentada", "Vinho"], 0,
      "Vinho Regional is Portugal's equivalent of a French IGP: wider boundaries, a longer list of permitted grapes and the freedom to name a variety on the label. Plain Vinho makes no geographical claim at all."),
    Q("The Portuguese wine map",
      "Some Portuguese demarcated areas spent years in a probationary rank abbreviated IPR before promotion. Where did that rank sit?",
      ["Between Vinho Regional and DOC, for candidate appellations",
       "Above DOC, as a superior classification for the finest estates",
       "Below plain Vinho, for wine that had failed inspection",
       "Alongside DOC, covering fortified wine only"], 0,
      "Indicacao de Proveniencia Regulamentada marked an area whose rules were already fixed but whose track record was not yet long enough for DOC. Most were eventually promoted or folded into a regional name, and the tier has all but vanished under EU labelling."),
    Q("The Portuguese wine map",
      "Mountain ranges standing between the coast and the interior are decisive for Portuguese wine. What do they chiefly do?",
      ["Block Atlantic rain and cloud, leaving hot dry conditions inland",
       "Funnel Atlantic rain inland, keeping the interior wet",
       "Cool the coastal strip by shading it from the afternoon sun",
       "Trap cold air on the plateau, bringing frost through the summer"], 0,
      "The Marao and Montemuro shield the Douro, and the Caramulo and Serra da Estrela ring the Dao. In both cases a maritime climate becomes a hot, dry, continental one within a few dozen kilometres."),

    # ------------------------------------------------------ Vinho Verde (8) --
    Q("Vinho Verde",
      "Guests often assume the green in Vinho Verde refers to the colour in the glass. What does the word actually indicate?",
      ["That the wine is made to be drunk young, soon after the harvest",
       "That the fruit is picked unripe and the wine is high in malic acid",
       "That the region's wines must by law be sold in green glass",
       "That the wine takes a green tinge from long storage in stainless steel"], 0,
      "Verde here means youthful rather than coloured, and the wines were traditionally sold within months of the vintage. The region also makes red and rose under the same name, which no colour reading can explain."),
    Q("Vinho Verde",
      "Bounded by the Minho river along the Spanish border and by the Douro to the south, which region occupies that corner of Portugal?",
      ["Vinho Verde", "Tras-os-Montes", "Dao", "Bairrada"], 0,
      "The Minho province is the wettest and greenest corner of the country, granite underfoot and Atlantic weather overhead. That rainfall drives both the training systems and the light, sharp style."),
    Q("Vinho Verde",
      "Traditional Minho smallholdings trained vines high overhead on pergolas and even up living trees. Which two problems did that solve at once?",
      ["Other crops could grow underneath and the canopy stayed clear of damp ground",
       "Sugar levels rose sharply and the wine finished higher in alcohol",
       "Spring frost was avoided and summer irrigation became unnecessary",
       "Yields fell sharply, and the smaller crop that remained ripened to a higher sugar"], 0,
      "Holdings were tiny and had to feed a family, so cabbages and maize grew beneath the fruit. Lifting the canopy also kept it out of the still, humid air at ground level, where rot thrives in a region this wet."),
    Q("Vinho Verde",
      "A young Vinho Verde arrives at the table with a faint prickle of gas. Where did that traditionally come from?",
      ["Malolactic conversion finishing after the wine was already in bottle",
       "A second alcoholic fermentation deliberately induced in bottle",
       "Extended lees contact in tank through the winter",
       "Carbon dioxide left over from a fortification step"], 0,
      "The old wines went into bottle unstable and finished their malolactic there, which threw a light spritz and often a haze. Modern producers ferment out, filter, and inject a measured dose of carbon dioxide at bottling instead."),
    Q("Vinho Verde",
      "Along the Minho river in the far north lies a warmer, drier pocket that is the traditional home of Alvarinho. Which sub-region?",
      ["Moncao e Melgaco", "Lima", "Basto", "Paiva"], 0,
      "Moncao e Melgaco sits in a rain shadow behind the Serra da Peneda, which lets Alvarinho reach a ripeness it cannot find elsewhere in the region. The same grape is Albarino across the river in Rias Baixas."),
    Q("Vinho Verde",
      "A Vinho Verde smelling emphatically of bay laurel, orange blossom and lime takes its name from that scent. Which variety?",
      ["Loureiro", "Avesso", "Trajadura", "Azal"], 0,
      "Loureiro is named for the laurel and is the most aromatic of the region's workhorse whites, at its best around the Lima valley. Trajadura lends body and low acid to a blend, while Avesso needs the warmer inland sites of Baiao."),
    Q("Vinho Verde",
      "In the Minho a black grape gives an inky, sharply acidic red that locals drink from white ceramic bowls. Which variety?",
      ["Vinhao", "Baga", "Castelao", "Ramisco"], 0,
      "Vinhao has coloured pulp as well as coloured skin, so the wine stains the bowl it is poured into. It is bracing and low in alcohol, made for grilled sardines and cured pork rather than for export."),
    Q("Vinho Verde",
      "One white grape appears in Minho blends under the local name Pederna, while Bucelas builds its entire reputation on it. Which grape?",
      ["Arinto", "Alvarinho", "Encruzado", "Fernao Pires"], 0,
      "Arinto holds its acidity even in real heat, which is why it travels the length of the country and turns up in Alentejo blends as well. Pederna is simply its Minho name."),

    # ------------------------------------------------------- the Douro (9) ---
    Q("The Douro",
      "Boundary stones planted in the years after 1756, under the Marquis of Pombal, still stand among the vines above the river. What did they establish?",
      ["One of the first demarcated wine regions",
       "The first cooperative winery in Europe",
       "A tax boundary with no connection to wine",
       "The land border between Portugal and Spain"], 0,
      "Pombal's chartered company of 1756 fixed the limits of the region, graded the vineyards and controlled prices, largely to stop the adulteration of wine sold to the British trade. That combination of a fixed boundary and enforced rules puts it among the earliest regulated wine regions anywhere. The marcos pombalinos, cut and set out over the years that followed, are still in the ground."),
    Q("The Douro",
      "Vines on the steepest Douro slopes survive summers with almost no rain by rooting metres down through fractured rock. Which rock?",
      ["Schist", "Granite", "Chalk", "Basalt"], 0,
      "Schist splits into near-vertical plates, so roots follow the fissures down to moisture the surface lost months earlier. Granite appears at the region's margins but does not fracture the same way, and roots cannot exploit it as deeply."),
    Q("The Douro",
      "Moving upstream from Mesao Frio toward the Spanish border, in what order do the three Douro sub-regions appear?",
      ["Baixo Corgo, then Cima Corgo, then Douro Superior",
       "Douro Superior, then Cima Corgo, then Baixo Corgo",
       "Cima Corgo, then Baixo Corgo, then Douro Superior",
       "Baixo Corgo, then Douro Superior, then Cima Corgo"], 0,
      "The Corgo is a tributary joining at Regua, and the two names mean below and above it. Rainfall drops and heat climbs steadily eastward, so the Douro Superior is the hottest and the least densely planted of the three."),
    Q("The Douro",
      "Narrow ledges walled in dry schist, holding one or two rows of vines apiece, climb the oldest Douro slopes. What are they called?",
      ["Socalcos", "Patamares", "Vinha ao alto", "Espaldeira"], 0,
      "Socalcos were built by hand over centuries and cannot take a tractor, so everything on them is still done by people and mules. Patamares, the bulldozed earth-banked terraces of the 1970s onward, replaced them wherever mechanisation mattered more than history."),
    Q("The Douro",
      "On slopes gentle enough to allow it, Douro growers now plant rows running straight up and down the hill instead of across it. What does that buy?",
      ["A tractor can work the rows",
       "The fruit ripens a full month earlier",
       "Erosion is eliminated altogether",
       "Irrigation becomes unnecessary"], 0,
      "Vinha ao alto removes the terrace entirely, so a tractor can climb the rows instead of crawling along ledges, and it fits more vines on the same ground. It only works below roughly a thirty percent gradient, and it needs careful cover cropping, because water running downhill takes soil with it."),
    Q("The Douro",
      "Every Douro vineyard is scored on altitude, gradient, soil, yield and grape mix, and the letter grade it earns controls one thing specifically. What?",
      ["How much of its must may be fortified into Port each year",
       "The price its bottles may be sold for",
       "Whether the estate is allowed to bottle unfortified wine",
       "The number of vines permitted per hectare"], 0,
      "The cadastro grades run from A to F, and the annual beneficio allocates fortification rights accordingly. Whatever is not turned into Port stays available for unfortified Douro wine."),
    Q("The Douro",
      "Unfortified red from the Douro was long dismissed as a by-product until a wine first made in 1952 changed the argument. Which wine?",
      ["Barca Velha", "Pera Manca", "Mouchao", "Palacio da Brejoeira"], 0,
      "Fernando Nicolau de Almeida modelled it on Bordeaux, hauling ice up from the coast to cool the ferment. It is declared only in years judged worthy, and it opened the road to the Douro DOC granted three decades later."),
    Q("The Douro",
      "Ripening late and cropping more generously than Touriga Nacional, which Douro variety supplies perfume and supple fruit to a blend?",
      ["Touriga Franca", "Tinta Barroca", "Tinto Cao", "Sousao"], 0,
      "Budding and ripening late protects Touriga Franca from spring frost and suits the hottest sites in the valley. It gives floral lift and softer tannin where Touriga Nacional gives density and structure."),
    Q("The Douro",
      "White wine from the Douro has turned serious in the last generation, grown high up or on slopes facing away from the sun. Which grapes carry it?",
      ["Viosinho, Rabigato, Gouveio and Codega do Larinho",
       "Alvarinho, Loureiro, Trajadura and Avesso",
       "Sercial, Verdelho, Boal and Malvasia",
       "Antao Vaz, Roupeiro, Perrum and Diagalves"], 0,
      "Rabigato brings the acidity, Viosinho the body and Gouveio the citrus, the last being the grape Madeira calls Verdelho. Altitude does most of the work, since the best white parcels sit six hundred metres up or on north-facing schist where the fruit never bakes."),

    # ------------------------------------------------- Dao and Bairrada (8) --
    Q("Dao and Bairrada",
      "Ringed by the Serra do Caramulo, the Serra da Nave and the Serra da Estrela, one region grows vines in clearings among pine forest, most of them four to five hundred metres up and some as high as eight hundred. Which?",
      ["Dao", "Bairrada", "Tras-os-Montes", "Beira Interior"], 0,
      "The mountains take the edge off the Atlantic from the west and the Spanish meseta from the east, giving a long, temperate growing season. Granite sand underfoot and pine on every horizon are the region's signature."),
    Q("Dao and Bairrada",
      "Underneath the Dao's vineyards lies a poor, free-draining, acidic sand weathered from one bedrock. Which?",
      ["Granite", "Limestone", "Schist", "Volcanic basalt"], 0,
      "Granitic sand gives low vigour and small crops, and it is much of why Dao reds feel firmer and more mineral than the riper, softer reds of the southern plains. Schist appears only in patches at the edges."),
    Q("Dao and Bairrada",
      "For decades Dao growers were obliged by law to sell their fruit to the local cooperative, and private houses could buy only finished wine. What did that produce?",
      ["Dull, uniform wine and a damaged reputation",
       "Exceptionally consistent quality across every producer",
       "A ban on estate bottling that remains in force today",
       "A rapid rise in single-vineyard bottlings"], 0,
      "Everyone's fruit went into the same vats and the wine was then held far too long in old wood, which is why the reds of that era taste dried out and tannic rather than thin. The monopoly held from the Salazar era until the late 1980s, when Portugal's entry into the European Community swept it away, and estate bottling followed."),
    Q("Dao and Bairrada",
      "One Portuguese white grape carries enough structure and acidity to be barrel-fermented and cellared for a decade, and it belongs to the Dao. Which?",
      ["Encruzado", "Fernao Pires", "Roupeiro", "Trajadura"], 0,
      "Encruzado is unusually restrained in aroma for a Portuguese white, which is exactly why it takes oak and time without being smothered. Comparisons with white Burgundy are made often and are not absurd."),
    Q("Dao and Bairrada",
      "A soft, early-drinking red grape of the Dao is known across the Spanish border as Mencia. What do the Portuguese call it?",
      ["Jaen", "Alfrocheiro", "Baga", "Trincadeira"], 0,
      "Jaen ripens early and gives colour and juicy red fruit but little structure. It is almost always blended with Touriga Nacional and Alfrocheiro rather than bottled on its own."),
    Q("Dao and Bairrada",
      "Between the Dao and the ocean sits a region that takes its name from the heavy clay under its vines. Which?",
      ["Bairrada", "Lisboa", "Tejo", "Beira Interior"], 0,
      "Barro is Portuguese for clay, and the cold clay-limestone here holds water, ripens the fruit late and gives wines of formidable acidity. The Atlantic is close enough to make rot the grower's constant worry."),
    Q("Dao and Bairrada",
      "Late to ripen in a damp maritime autumn, and fierce with acid and tannin when it finally does, one grape dominates the reds of the clay belt near Coimbra. Which?",
      ["Baga", "Castelao", "Ramisco", "Alfrocheiro"], 0,
      "Baga hangs on the vine into a wet October and was long fermented with all its stems, which is how it earned its reputation for being undrinkable young. Destemming and gentler handling have turned it into one of Portugal's most ageworthy reds."),
    Q("Dao and Bairrada",
      "Roast suckling pig is the dish every restaurant around Mealhada is judged on, and the local wine trade grew a speciality to match it. Which style?",
      ["Traditional-method sparkling wine", "Fortified sweet white wine",
       "Oxidatively aged white wine", "Carbonic-maceration red"], 0,
      "Bairrada has made bottle-fermented espumante since the late nineteenth century, and a bright, high-acid sparkling wine cuts the fat of leitao better than anything still. Baga itself is often the base, pressed pale."),

    # ------------------------------------------- Alentejo and the south (6) --
    Q("Alentejo and the south",
      "Vines in the south share their ground with a wooded savannah of evergreen oaks grazed by black pigs, a farmed landscape called the montado. Which tree is it built on?",
      ["Cork oak", "Olive", "Eucalyptus", "Umbrella pine"], 0,
      "Quercus suber and its holm-oak cousin shade the pasture, the acorns feed the pigs and the bark is stripped for stoppers. Wine, pork and cork all come off the same hectare."),
    Q("Alentejo and the south",
      "Granite at seven hundred metres, in the coolest corner of a famously hot region, marks which Alentejo sub-region?",
      ["Portalegre", "Vidigueira", "Reguengos", "Granja-Amareleja"], 0,
      "Portalegre sits in the Serra de Sao Mamede against the Spanish border, high enough for fresher acidity and a later picking date than the plains allow. Granja-Amareleja, by contrast, is among the hottest ground in Portugal."),
    Q("Alentejo and the south",
      "In a handful of Alentejo cellars the wine still ferments and rests in tall clay vessels sealed with olive oil, opened by tradition on Saint Martin's Day. What is the vessel called?",
      ["Talha", "Tinaja", "Qvevri", "Lagar"], 0,
      "The technique is Roman and survived around Vidigueira, and the rules now recognise it in its own right. Tinaja is the Spanish equivalent and qvevri the Georgian one, while a lagar is the shallow stone trough used for treading grapes."),
    Q("Alentejo and the south",
      "A red-fleshed French crossing found its most convincing home on the Alentejo plains, where it gives colour, structure and dark fruit. Which variety?",
      ["Alicante Bouschet", "Trincadeira", "Moreto", "Tinta Caiada"], 0,
      "Almost every red grape has clear juice, but this one stains from the pulp as well as the skin, which made it valuable to blenders everywhere. In the Alentejo it long outgrew that role and is now bottled on its own by the region's best estates."),
    Q("Alentejo and the south",
      "Drought-tolerant and reliably even in ripening, one white grape anchors Alentejo blends and is usually paired with Arinto to keep the wine fresh. Which?",
      ["Antao Vaz", "Roupeiro", "Perrum", "Fernao Pires"], 0,
      "Antao Vaz brings weight and ripe tropical fruit but not much acid, so Arinto is blended in to carry it. Roupeiro, also called Siria, is the region's other traditional white and fades quickly in bottle."),
    Q("Alentejo and the south",
      "A grower in Reguengos and a grower in the Douro turn out to be working the same variety under two names. Which pair?",
      ["Aragonez and Tinta Roriz", "Trincadeira and Baga",
       "Castelao and Alicante Bouschet", "Alfrocheiro and Jaen"], 0,
      "The grape is Tempranillo, called Tinta Roriz in the north and Aragonez in the south. Renaming grapes region by region is the single hardest part of learning Portugal."),

    # --------------------------------- Setubal, Bucelas and Colares (6) ------
    Q("Setubal, Bucelas and Colares",
      "Deep Atlantic sand west of Sintra kept phylloxera out, so the vines there are still growing on their own roots. Which appellation?",
      ["Colares", "Bucelas", "Carcavelos", "Palmela"], 0,
      "The louse cannot travel through pure sand, which leaves these among the very few ungrafted vineyards left in Europe. Growers dig trenches down through the dune to the clay beneath before they plant."),
    Q("Setubal, Bucelas and Colares",
      "Sprawling low across the sand behind screens of woven cane, the vines of Colares are being defended against what?",
      ["Salt-laden Atlantic wind", "Spring frost rolling off the hills",
       "Summer hail", "Excessive sunlight on the fruit"], 0,
      "The vineyards sit almost on the beach, and unbroken ocean wind would shred the shoots and burn the leaves with salt. Keeping the canopy low and screened is the only way the fruit survives to October."),
    Q("Setubal, Bucelas and Colares",
      "Ferociously tannic and needing a decade before it is civil, the red of the Sintra sand vineyards comes from which variety?",
      ["Ramisco", "Castelao", "Baga", "Vinhao"], 0,
      "Ramisco on ungrafted sand yields almost nothing and makes a wine that is severe in youth and remarkable at twenty years. Malvasia de Colares is the white counterpart in the same appellation."),
    Q("Setubal, Bucelas and Colares",
      "British officers billeted near Lisbon during the Peninsular War took home a crisp white they called Lisbon Hock. Which small DOC made it?",
      ["Bucelas", "Colares", "Setubal", "Carcavelos"], 0,
      "Bucelas lies in the Trancao valley just north of the city and makes white wine only, built on Arinto. The English taste for it faded, and the appellation is now down to a handful of producers."),
    Q("Setubal, Bucelas and Colares",
      "After fortification, the winemaker returns the muscat skins to the fortified wine and leaves them there for months. What does that achieve?",
      ["A far more intense grape and orange-peel aroma",
       "A dry finish, because the added spirit ferments out the sugar",
       "A pale colour, because the skins reabsorb pigment",
       "A gentle sparkle, because the skins restart fermentation"], 0,
      "Alcohol is a better solvent for aromatic compounds than must is, so the maceration pulls terpenes out of the skins that fermentation alone would leave behind. It is the signature step of Moscatel de Setubal."),
    Q("Setubal, Bucelas and Colares",
      "Warm sandy soils on the peninsula south of Lisbon suit a black grape that locals label Periquita. What is its proper name?",
      ["Castelao", "Trincadeira", "Aragonez", "Alfrocheiro"], 0,
      "Castelao is the mainstay of Palmela and of southern Portugal generally, giving a firm raspberry-and-tobacco red that softens over a few years. Periquita is a local name that a nineteenth-century brand made famous, which is why it still clings to the grape."),

    # ----------------------------------------- Madeira and the Azores (8) ----
    Q("Madeira and the Azores",
      "Casks shipped as ballast to the Indies and back came home tasting better than when they left, and an island trade rebuilt itself around that discovery. Which wine?",
      ["Madeira", "Port", "Sherry", "Marsala"], 0,
      "Heat and motion in the hold cooked and aerated the wine, and the returned casks, vinho da roda, fetched a premium. Once the effect was understood, producers reproduced it on land rather than pay for the voyage."),
    Q("Madeira and the Azores",
      "Madeira is either heated artificially over a matter of months or left to ripen in cask in a hot loft over many years. What is the slow, unforced route called?",
      ["Canteiro", "Estufa", "Solera", "Vinho da roda"], 0,
      "Canteiro is the name of the wooden rack the cask rests on, up under the roof where the sun does the work. Artificial heat comes either from a warmed tank, held at forty-five to fifty degrees for at least three months, or from an armazem de calor, a cask store warmed more gently for six months or more, and both serve the commercial blends."),
    Q("Madeira and the Azores",
      "Someone opening a meal wants the leanest, most bracing thing on the Madeira list. Which of these varieties goes in the glass?",
      ["Sercial", "Bual", "Malvasia", "Terrantez"], 0,
      "The classic ladder runs Sercial, Verdelho, Bual, then Malvasia, and Malvasia is the one sold as Malmsey. Terrantez is a rare noble variety that sits outside that four. Sercial is planted highest and coolest on the island and finishes almost dry, which is why it works before the food rather than after it."),
    Q("Madeira and the Azores",
      "Sweetness in a fortified wine is settled at a single moment during the ferment. When is a Malmsey fortified relative to a Sercial?",
      ["Earlier, while a great deal of sugar is still unfermented",
       "Later, once the yeast has worked through almost all the sugar",
       "At exactly the same point, with sugar added afterwards",
       "Only after the wine has already been heated"], 0,
      "Spirit kills the yeast, so whatever sugar remains at that moment stays in the wine for good. Fortifying early leaves a sweet wine and fortifying late a dry one, which is the whole mechanism behind the four styles."),
    Q("Madeira and the Azores",
      "A single-year Madeira labelled Frasqueira has spent how long in cask before it may be bottled?",
      ["At least twenty years", "At least three years",
       "At least eight years", "At least fifty years"], 0,
      "Frasqueira, or vintage Madeira, is the top of the hierarchy and comes from one variety and one harvest. Colheita is the shorter single-vintage category, released after five years."),
    Q("Madeira and the Azores",
      "Blends labelled simply Reserve or Rainwater are generally built on one workhorse variety rather than on the classic whites. Which grape?",
      ["Tinta Negra", "Bastardo", "Verdelho", "Malvasia"], 0,
      "Tinta Negra is hardy, adaptable and can be vinified at any sweetness level, which makes it the backbone of the commercial range. Sercial, Verdelho, Bual and Malvasia are reserved for the more expensive bottlings."),
    Q("Madeira and the Azores",
      "Vines on Pico grow inside thousands of small enclosures walled in black volcanic stone, a landscape on the UNESCO list. What are the enclosures called?",
      ["Currais", "Poios", "Socalcos", "Patamares"], 0,
      "Each curral is a few square metres of lava cleared to bare rock and walled to break the Atlantic wind and hold the day's heat into the night. The wines that come off them are unmistakably saline."),
    Q("Madeira and the Azores",
      "Two Azorean DOCs, Pico and Biscoitos, built their historic export reputation on a single white variety also grown on Madeira. Which?",
      ["Verdelho", "Fernao Pires", "Loureiro", "Antao Vaz"], 0,
      "Verdelho crossed from Madeira to the islands and gave a strong, partly oxidative white that travelled well by sea. Both islands still make a fortified licoroso from it, but the modern revival has been driven by crisp, saline dry whites."),

    # ---------------------------------------------------- native grapes (5) --
    Q("Native grapes",
      "Tiny berries, thick skins, a stingy crop and a scent of violets and bergamot describe Portugal's most admired black grape. Which?",
      ["Touriga Nacional", "Touriga Franca", "Trincadeira", "Alfrocheiro"], 0,
      "Low yields nearly saw it abandoned before selection work in the Dao and the Douro rescued it. Colour, tannin and perfume all arrive in unusual concentration, which is why a little of it goes a long way in a blend."),
    Q("Native grapes",
      "An early-ripening, low-acid white with a loud floral and citrus perfume answers to Maria Gomes in Bairrada. What is it called elsewhere?",
      ["Fernao Pires", "Bical", "Arinto", "Roupeiro"], 0,
      "One grape with two names in neighbouring regions, which is entirely normal in Portugal. Its aromatics arrive early and fade fast, so it is picked promptly and drunk young."),
    Q("Native grapes",
      "Asked for the Portuguese white grape that Spain calls Albarino, a sommelier should say what?",
      ["Alvarinho", "Arinto", "Avesso", "Azal"], 0,
      "One grape, one river, two countries: Rias Baixas grows it in Galicia and Moncao e Melgaco grows it across the Minho. In both places it gives fuller, more stone-fruited wine than the varieties around it."),
    Q("Native grapes",
      "Old vineyards in the Douro and in Portalegre were planted with dozens of varieties intermingled and are still picked all together. What is that arrangement called?",
      ["A field blend", "A massal selection", "A clonal trial", "A polyculture terrace"], 0,
      "Nobody recorded what was planted where, so the blending happens in the vineyard rather than the cellar. Vinha velha on a Portuguese label usually points to exactly this, and the spread of ripening dates is part of why the wines balance."),
    Q("Native grapes",
      "Spicy, herbal and badly prone to rot in a wet autumn, one Alentejo black grape is known in the north as Tinta Amarela. What is its southern name?",
      ["Trincadeira", "Moreto", "Castelao", "Alfrocheiro"], 0,
      "Trincadeira lends lift and spice to blends dominated by Aragonez and Alicante Bouschet, but thin skins and tight bunches make it a liability in a damp year. Dry Alentejo heat is precisely what it needs."),

    # ------------------------------------------------ cork and the label (4) -
    Q("Cork and the label",
      "Bark is stripped from a cork oak in summer and the tree is then left alone for a fixed period before the next harvest. How long?",
      ["Nine years", "Three years", "Fifteen years", "Twenty-five years"], 0,
      "Portuguese law sets the minimum at nine years, and the tree regrows its bark without being felled or otherwise damaged. A cork oak is usually not stripped at all until it is about twenty-five years old."),
    Q("Cork and the label",
      "The first two strippings of a cork oak never become wine stoppers. Why not?",
      ["The bark is too coarse and irregular for a stopper",
       "The bark is toxic to wine at that age",
       "The tree is legally protected until its third stripping",
       "The first two harvests are reserved for the state"], 0,
      "Virgin and secondary cork go to flooring, insulation and shoe soles. Only from the third harvest, more than forty years into the tree's life, does the bark have the uniform cell structure a stopper needs."),
    Q("Cork and the label",
      "Drawing a stopper at the table, a sommelier finds a body of glued cork granules finished with a disc of solid cork at each end. What sort of closure is that?",
      ["A technical cork, an agglomerated body capped with natural cork discs",
       "A colmated cork, one solid piece whose surface pits have been filled with cork dust",
       "A natural cork, punched in one piece from a single strip of bark",
       "A synthetic stopper extruded from food-grade polymer"], 0,
      "The granules are the offcuts left after whole corks are punched from the bark, and the discs put natural cork where the wine actually touches. Stoppers built this way cost a fraction of a one-piece cork and are meant for wine drunk within a few years, since the glue line is not built for decades. A colmated cork is a different economy again: one solid piece whose lenticels have been packed with cork dust to smooth it."),
    Q("Cork and the label",
      "A red labelled Garrafeira has met an ageing requirement that plain Reserva does not. What is it?",
      ["At least thirty months in total, twelve of them in bottle",
       "At least twelve months in new oak barrels",
       "At least five years in the producer's own cellar",
       "At least twenty-four months in cask, with no bottle minimum"], 0,
      "Reserva asks only for a stated vintage and alcohol half a degree above the regional minimum. Garrafeira adds the time, and the compulsory spell in glass is what gives those wines their settled, secondary character."),
]
