"""Rank I rewrite - Rhone (59 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

The valley is really two regions sharing a river, so the syllabus is built that
way: the granite crus of the north one at a time, then the galets and the long
variety list of the south, with the mistral, the soils and the regional tiers
treated as the connective tissue between them.

Everything outside the CAT constant is deliberately unaccented ASCII. CAT itself
must byte-match the string the shipped app hardcodes in its region lists.
"""

from lib import Q

CAT = "Rhône"
SLUG = "r1-rhone"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Northern Rhone geography and climate", 5),
    ("Cote-Rotie and Condrieu", 8),
    ("Hermitage and Crozes-Hermitage", 7),
    ("Saint-Joseph, Cornas and Saint-Peray", 7),
    ("Northern grapes and winemaking", 6),
    ("Chateauneuf-du-Pape", 10),
    ("Southern crus and sweet wines", 8),
    ("Cotes du Rhone and the regional tiers", 4),
    ("Soils, mistral and vineyard practice", 4),
]

BANK = [
    # -------------------------- northern geography and climate (5) -----------
    Q("Northern Rhone geography and climate",
      "Between Valence and Montelimar the vines all but vanish for some fifty kilometres. What does that empty stretch separate?",
      ["The Northern Rhone from the Southern Rhone", "The Rhone valley from Provence",
       "Beaujolais from the Rhone valley", "The Diois from the Ardeche"], 0,
      "The gap is why the two halves feel like different countries. North of it the climate is continental and the vineyards are steep; south of it the land opens out and the climate turns Mediterranean."),
    Q("Northern Rhone geography and climate",
      "Harsh winters, a real risk of spring frost and a short season in which everything must ripen. Which climate type does the northern half of the valley have?",
      ["Continental", "Mediterranean", "Maritime", "Semi-arid"], 0,
      "Vintage variation matters far more in the north than in the south. A cool year gives lean, peppery Syrah and a warm one gives something much riper, from the same rows of vines."),
    Q("Northern Rhone geography and climate",
      "Slopes so steep that no tractor can work them force growers to tie each vine to its own wooden pole. What is that pole called?",
      ["An echalas", "A galet", "A gobelet", "A palissage"], 0,
      "The stakes are often lashed into tripods so the vine can resist the wind on an exposed terrace. Everything on those slopes, including the harvest, is carried by hand."),
    Q("Northern Rhone geography and climate",
      "Almost every cru of the northern valley sits on the right bank of the river. Which two look back at them from the left?",
      ["Hermitage and Crozes-Hermitage", "Cornas and Saint-Peray",
       "Condrieu and Chateau-Grillet", "Cote-Rotie and Saint-Joseph"], 0,
      "The hill of Hermitage and the flatter land around it are the exception, which is part of why Hermitage catches so much sun: the river swings west there and the hill ends up facing due south."),
    Q("Northern Rhone geography and climate",
      "Red wine in every northern appellation that makes one must be built on a single black grape. Which one?",
      ["Syrah", "Grenache", "Mourvedre", "Carignan"], 0,
      "One grape across the five northern appellations that make red is what makes the north such a clear lesson in site. Condrieu, Chateau-Grillet and Saint-Peray are white only. Grenache and Mourvedre belong to the south and are not permitted in any northern cru."),

    # ------------------------------------- Cote-Rotie and Condrieu (8) -------
    Q("Cote-Rotie and Condrieu",
      "A terraced amphitheatre above the town of Ampuis takes its name from the way the sun bakes it. Which appellation?",
      ["Cote-Rotie", "Cornas", "Condrieu", "Crozes-Hermitage"], 0,
      "The roasted slope, and the northernmost of the valley's crus. Its terraces are held up by dry stone walls that need constant rebuilding after heavy rain."),
    Q("Cote-Rotie and Condrieu",
      "Whole clusters of a white grape may legally go into the fermenter alongside the Syrah in that northernmost cru. Which white grape?",
      ["Viognier", "Marsanne", "Roussanne", "Clairette"], 0,
      "The two are often interplanted, so the practice began as a matter of convenience rather than theory. Picked together they also ripen together, which is why the tradition survived."),
    Q("Cote-Rotie and Condrieu",
      "Cote-Rotie growers co-ferment only a little Viognier in practice, though the rules permit a good deal more. What is the legal ceiling?",
      ["Twenty percent", "Five percent", "Fifty percent", "Two percent"], 0,
      "Most growers use nothing like the maximum, and many use none at all. A few percent is enough to change the aroma without turning the wine pale."),
    Q("Cote-Rotie and Condrieu",
      "Local legend divides the hill above Ampuis between a landowner's two daughters, one fair and one dark. What are the two sectors called?",
      ["The Cote Blonde and the Cote Brune", "Les Bessards and Les Greffieux",
       "La Chapelle and Le Meal", "The Cote des Blancs and the Cote des Noirs"], 0,
      "The story is charming and the geology is real: the two flanks genuinely differ in rock and in soil colour, and the wines differ with them."),
    Q("Cote-Rotie and Condrieu",
      "Iron-rich schist and clay on one flank, paler granitic gneiss on the other. Which flank gives the sturdier, slower-maturing wine?",
      ["The Cote Brune", "The Cote Blonde", "The plateau above the terraces",
       "The alluvial flat beside the river"], 0,
      "Brune builds tannin and needs time; Blonde is the more perfumed and open of the two. Many bottlings blend both, precisely to get the perfume and the frame together."),
    Q("Cote-Rotie and Condrieu",
      "Apricot, honeysuckle and a broad oily texture with notably low acidity, from granite terraces just south of Ampuis. Which appellation is in the glass?",
      ["Condrieu", "Saint-Peray", "Crozes-Hermitage blanc", "Hermitage blanc"], 0,
      "Low acidity is the signature and the problem: the wine is glorious at two or three years and rarely rewards keeping. Picking date decides everything, since the aromatics arrive very late and the acid falls away fast."),
    Q("Cote-Rotie and Condrieu",
      "An estate of barely more than three hectares holds an entire appellation to itself, enclosed within the boundaries of Condrieu. Which appellation?",
      ["Chateau-Grillet", "Coulee de Serrant", "Chateau-Chalon", "Cornas"], 0,
      "One of the smallest appellations in France, a single south-facing granite amphitheatre planted to Viognier. A whole appellation in one owner's hands is very nearly unique in the country."),
    Q("Cote-Rotie and Condrieu",
      "Fermenting the white grapes together with the black, rather than blending two finished wines, achieves what?",
      ["The colour is stabilised and the aroma lifted", "The alcohol rises sharply",
       "Malolactic conversion is prevented", "The tannins are stripped away"], 0,
      "Compounds from the white grape bind to the red pigments and hold them in solution, so the wine ends up more stable in colour rather than paler. The aromatic lift is the part you can smell."),

    # -------------------------- Hermitage and Crozes-Hermitage (7) -----------
    Q("Hermitage and Crozes-Hermitage",
      "A single granite hill rising behind the town of Tain gives Syrah its most age-worthy expression in France. Which appellation crowns it?",
      ["Hermitage", "Cornas", "Cote-Rotie", "Crozes-Hermitage"], 0,
      "The hill is small enough to walk across in an hour and has been famous for centuries. Its reds were once shipped north and west to strengthen thinner wines, including claret, which tells you how concentrated they were."),
    Q("Hermitage and Crozes-Hermitage",
      "Long-lived whites from that hill, capable of decades in bottle, are built on which pair of varieties?",
      ["Marsanne and Roussanne", "Viognier and Clairette", "Chardonnay and Aligote",
       "Bourboulenc and Picpoul"], 0,
      "They close up for years in the middle of their life and then reopen, nutty and honeyed. A guest who opens one at five years old will usually think it dull."),
    Q("Hermitage and Crozes-Hermitage",
      "Growers on the hill above Tain keep one parcel at its western end, a spine of hard granite under almost no topsoil, for their firmest and slowest-maturing red. Which parcel is that?",
      ["Les Bessards", "Les Greffieux", "Le Meal", "Les Rocoules"], 0,
      "Bare granite means small crops and tannin that arrives hard and fine, so wine from there needs the longest in bottle. Les Greffieux sits lower on clay and gravel and gives perfume and suppleness instead, while Les Rocoules is the parcel growers reserve for white."),
    Q("Hermitage and Crozes-Hermitage",
      "A label may add Les Bessards, Le Meal or L'Hermite beneath the appellation name. What are those?",
      ["Named parcels on the hill", "Villages within Crozes-Hermitage",
       "Classified growths of Cornas", "Merchant houses based in Tain"], 0,
      "The hill is a patchwork of granite, loess and stony terraces, and the parcels taste different enough to name. Most estates still blend across several of them for their principal wine."),
    Q("Hermitage and Crozes-Hermitage",
      "Eleven communes wrapping around that hill carry far more vines than the hill itself. Which appellation covers them?",
      ["Crozes-Hermitage", "Saint-Joseph", "Hermitage", "Cornas"], 0,
      "It is the workhorse of the north and the usual first taste of northern Syrah, since the volume keeps the price within reach. Its southern sector is flat glacial gravel, while the northern communes are granite slopes much like Hermitage itself."),
    Q("Hermitage and Crozes-Hermitage",
      "Two bottles of that same appellation can taste unrelated, the first lean and firm, the second soft and forward. What best explains it?",
      ["It takes in both steep granite slopes and a flat stony plain",
       "It permits both Syrah and Mourvedre for red",
       "One is a village wine and the other a cru",
       "One is white and the other red"], 0,
      "The northern sector around Gervans and Larnage is hillside granite; the southern sector is flat alluvial ground. Knowing which half a wine comes from tells you more than the vintage does."),
    Q("Hermitage and Crozes-Hermitage",
      "Blending a little Marsanne or Roussanne into the red is legal on the hill of Tain. Up to what proportion?",
      ["Fifteen percent", "Twenty percent", "Five percent",
       "None, white grapes are forbidden"], 0,
      "Very few producers use it now, though the tradition is old and was once thought to soften the tannin. The allowance is a permission rather than an instruction."),

    # ----------------------- Saint-Joseph, Cornas and Saint-Peray (7) --------
    Q("Saint-Joseph, Cornas and Saint-Peray",
      "A ribbon of vineyard runs some fifty kilometres along the right bank, from Chavanay in the north to Guilherand in the south. Which appellation?",
      ["Saint-Joseph", "Crozes-Hermitage", "Cornas", "Condrieu"], 0,
      "Stretching an appellation that far means the quality is uneven, since the granite heart of it around Tournon and Mauves sits alongside far flatter land. Producer matters more here than in any other northern cru."),
    Q("Saint-Joseph, Cornas and Saint-Peray",
      "Steep granite terraces in a sheltered amphitheatre ripen Syrah earlier than anywhere else in the north, and no white grape may enter the wine at all. Which appellation?",
      ["Cornas", "Saint-Joseph", "Hermitage", "Crozes-Hermitage"], 0,
      "The name is said to come from a Celtic term for burnt earth. Hills behind the village block the north wind, so it ripens ahead of its neighbours and gives the darkest, most tannic of the northern reds."),
    Q("Saint-Joseph, Cornas and Saint-Peray",
      "Still whites and a sparkling wine, both from Marsanne and Roussanne, with no red permitted whatever. Which appellation faces Valence across the river?",
      ["Saint-Peray", "Condrieu", "Saint-Joseph", "Cornas"], 0,
      "The southernmost appellation of the north and the least seen abroad. Its sparkling wine was fashionable in the nineteenth century and has been quietly recovering ground since."),
    Q("Saint-Joseph, Cornas and Saint-Peray",
      "Of the two whites permitted at Hermitage and Saint-Joseph, one is planted far more widely because it yields reliably and resists disease better. Which?",
      ["Marsanne", "Roussanne", "Viognier", "Clairette"], 0,
      "It gives the weight and the waxy texture; its partner gives perfume and acidity but is a nuisance in the vineyard. Most blends lean heavily on the easier grape."),
    Q("Saint-Joseph, Cornas and Saint-Peray",
      "Reds from that long right-bank ribbon may take a small share of white grapes, less than Hermitage allows. What is the limit?",
      ["Ten percent", "Fifteen percent", "Twenty-five percent", "None is allowed"], 0,
      "The rule mirrors Hermitage at a lower level, and as there it is used sparingly. Cornas alone among the northern reds permits nothing at all."),
    Q("Saint-Joseph, Cornas and Saint-Peray",
      "Bubbles in the sparkling wine of Saint-Peray come from a second fermentation carried out where?",
      ["In the bottle, by the traditional method", "In a sealed tank under pressure",
       "By injecting carbon dioxide before bottling", "In a single fermentation halted by cold"], 0,
      "Bottle-fermented and riddled like Champagne, from Marsanne and Roussanne rather than Chardonnay. The result is broader and less taut than a northern sparkling wine from a cooler region."),
    Q("Saint-Joseph, Cornas and Saint-Peray",
      "Victor Hugo put the wine of one Rhone village into Les Miserables, and Saint-Joseph later grew out of its slopes. Which village?",
      ["Mauves", "Tournon", "Serves", "Chavanay"], 0,
      "The wine of Mauves was famous long before the appellation was created in 1956. The granite core of Saint-Joseph still lies around that village and its neighbour Tournon."),

    # ------------------------------- northern grapes and winemaking (6) ------
    Q("Northern grapes and winemaking",
      "Fermenting Syrah with a proportion of its stems left in the vat is common practice in the north. What does whole-bunch inclusion usually contribute?",
      ["Aromatic lift and a firmer tannic frame", "Extra sweetness from sugar in the stems",
       "A deeper, more saturated colour", "Immunity from malolactic conversion"], 0,
      "Green stems can add a bitter, stalky note, so the decision turns on how ripe the wood is. Stems also absorb some colour, so the wine often ends up a shade lighter rather than darker."),
    Q("Northern grapes and winemaking",
      "Peppery aroma in cool-vintage Syrah has been traced to one aroma compound. Which?",
      ["Rotundone", "Methoxypyrazine", "Diacetyl", "Sotolon"], 0,
      "It also occurs in black pepper itself, which is why the descriptor is so exact. Warm sites and hot years suppress it, so the pepper fades as you move south down the valley."),
    Q("Northern grapes and winemaking",
      "Weight, almond and a waxy texture come from one of the two northern whites; perfume, pear and firmer acidity from the other, which is fickle in the vineyard. Which is the fickle one?",
      ["Roussanne", "Marsanne", "Viognier", "Bourboulenc"], 0,
      "It ripens late, rots easily and oxidises quickly, so growers plant it for what it brings to a blend rather than for an easy life. Its name refers to the russet colour of the ripe skin."),
    Q("Northern grapes and winemaking",
      "The black grape behind every northern Rhone red is called something else in Australia. Which name?",
      ["Shiraz", "Durif", "Mataro", "Malbec"], 0,
      "The same grape, and the name is now a rough style signal: the French spelling tends to promise pepper and restraint, the Australian one ripeness and sweet fruit."),
    Q("Northern grapes and winemaking",
      "Traditional northern cellars matured Syrah in large old casks rather than in new barriques. What is such a cask called?",
      ["A foudre", "A barrique", "A pupitre", "An amphora"], 0,
      "Big and old means slow, gentle oxygen exchange and almost no oak flavour. Many estates that experimented with new barrels have drifted back toward larger wood."),
    Q("Northern grapes and winemaking",
      "Plantings of one northern white had fallen to a few hectares by the late 1960s before a worldwide revival. Which grape?",
      ["Viognier", "Marsanne", "Roussanne", "Counoise"], 0,
      "It came within a generation of disappearing, then became fashionable and was planted from California to Australia. Condrieu remains the reference point for what it can do."),

    # -------------------------------------------- Chateauneuf-du-Pape (10) ---
    Q("Chateauneuf-du-Pape",
      "Large rounded quartzite stones cover the plateau of La Crau, holding the day's heat well into the night. What are they called?",
      ["Galets roules", "Terra rossa", "Crayeres", "Kimmeridgian marl"], 0,
      "They were rolled smooth by the river and the glaciers long ago. They are famous but not universal: the same appellation also has deep sand and sandstone, which give much lighter, more perfumed wines."),
    Q("Chateauneuf-du-Pape",
      "A single southern appellation permits thirteen named grapes, eighteen once the colour variants are counted apart. Which appellation?",
      ["Chateauneuf-du-Pape", "Gigondas", "Vacqueyras", "Lirac"], 0,
      "Grenache, Clairette and Picpoul each exist in more than one colour, which is where the higher figure comes from. Almost nobody plants all of them, and many fine wines use three or four."),
    Q("Chateauneuf-du-Pape",
      "Warmth, high alcohol, sweet red fruit and a pale rim in a wine from the papal village point to its dominant grape. Which?",
      ["Grenache", "Syrah", "Mourvedre", "Counoise"], 0,
      "It ripens to high sugar and gives little colour, so a young example can look deceptively light for its weight. Old bush vines of it are the backbone of the appellation."),
    Q("Chateauneuf-du-Pape",
      "One of the classic southern trio needs real heat to ripen and repays it with tannin, colour and a gamey, meaty note. Which grape?",
      ["Mourvedre", "Cinsault", "Counoise", "Terret Noir"], 0,
      "It buds and ripens late, so it only works in the warmest sites. It also brings the ageing capacity that Grenache lacks, which is why so many blends carry a little of it."),
    Q("Chateauneuf-du-Pape",
      "A guest asks for a rose from the papal village. What do you tell them?",
      ["The appellation covers red and white only", "Rose there may be made only from Cinsault",
       "Rose there comes only from the plateau of La Crau",
       "Rose there is made but may not be exported"], 0,
      "Point them across the river to Tavel or Lirac instead. A grower in the village who makes rose must sell it under a broader appellation."),
    Q("Chateauneuf-du-Pape",
      "Uniquely strict harvest rules there require picking by hand and what else?",
      ["A compulsory sorting that rejects part of the crop",
       "Complete destemming of every bunch",
       "A single harvest date fixed for the whole appellation",
       "Chaptalisation of any must below the minimum"], 0,
      "The discarded fruit cannot be made into appellation wine at all. Combined with very low permitted yields, it is one of the more demanding sets of rules in France."),
    Q("Chateauneuf-du-Pape",
      "The minimum alcohol demanded there is the highest of any French appellation. What is it?",
      ["12.5 percent", "10.5 percent", "11.5 percent", "14 percent"], 0,
      "In practice most wines land far above it, and fifteen percent is unremarkable. The floor was set to keep out thin wine from over-cropped vines rather than to encourage power."),
    Q("Chateauneuf-du-Pape",
      "Why does the village carry a papal name at all?",
      ["The fourteenth-century popes at Avignon kept a castle there",
       "A pope was born in the village",
       "The vineyards belonged to Rome until the Revolution",
       "A pope blessed the first vintage of the appellation"], 0,
      "The popes moved the papacy to Avignon and built a summer residence a few miles north. The ruined keep still stands above the vines and appears on countless labels."),
    Q("Chateauneuf-du-Pape",
      "Some bottles from the village are moulded with crossed keys beneath a tiara. What does that emblem tell a buyer?",
      ["The producer belongs to the local growers' association",
       "The wine contains all thirteen permitted varieties",
       "The wine comes from a single vineyard",
       "The wine was aged at least three years before release"], 0,
      "The embossed bottle was adopted in the 1930s as a mark of origin against fraud. It says nothing about the style or the quality of what is inside."),
    Q("Chateauneuf-du-Pape",
      "Whites are a small part of the village's output. Which description fits them?",
      ["Full-bodied and broad, with modest acidity", "Light and sharply acidic",
       "Sweet and fortified", "Aged oxidatively under a film of yeast"], 0,
      "Grenache Blanc, Clairette, Roussanne and Bourboulenc give weight rather than tension. They are usually drunk young, though the best go quiet for several years and then return."),

    # ----------------------------- southern crus and sweet wines (8) ---------
    Q("Southern crus and sweet wines",
      "Vineyards climbing to the foot of the jagged limestone teeth of the Dentelles de Montmirail give a Grenache red firmer and fresher than the plain below. Which cru?",
      ["Gigondas", "Tavel", "Rasteau", "Vinsobres"], 0,
      "Altitude and limestone give cooler nights and better acidity than the valley floor. It is the standard recommendation for a guest who finds Chateauneuf too heavy."),
    Q("Southern crus and sweet wines",
      "Which cru sits immediately south of Gigondas on flatter, stonier ground and makes all three colours?",
      ["Vacqueyras", "Lirac", "Rasteau", "Cairanne"], 0,
      "The two are constantly compared, and the flatter site shows: warmer, rounder and quicker to drink, usually at a friendlier price."),
    Q("Southern crus and sweet wines",
      "A dry rose deep enough in colour to be mistaken for a light red, and the only wine its right-bank appellation may produce. Which appellation?",
      ["Tavel", "Lirac", "Bandol", "Cotes de Provence"], 0,
      "Colour comes from a longer maceration than a pale Provencal rose gets, and the wine has the structure to take a real main course. It is one of the few roses worth a year or two in bottle."),
    Q("Southern crus and sweet wines",
      "Just north of that rose-only appellation, which right-bank neighbour makes red, white and rose alike?",
      ["Lirac", "Chusclan", "Vinsobres", "Rasteau"], 0,
      "It shares the same stony terraces and long enjoyed a lesser reputation, largely because Tavel took the attention. Its reds are the argument for looking at the right bank at all."),
    Q("Southern crus and sweet wines",
      "One southern cru is known both for dry red wine and for a fortified sweet wine made from the same grape. Which?",
      ["Rasteau", "Gigondas", "Vinsobres", "Cairanne"], 0,
      "The sweet version comes in pale and dark styles depending on how it is aged, and an oxidative example develops the nutty rancio character. Both are Grenache."),
    Q("Southern crus and sweet wines",
      "A sweet golden wine of grapey, orange-blossom aroma comes from a village beneath the Dentelles de Montmirail. Which appellation?",
      ["Muscat de Beaumes-de-Venise", "Rasteau", "Clairette de Die",
       "Muscat de Rivesaltes"], 0,
      "Made from Muscat Blanc a Petits Grains, the aromatic Muscat rather than the coarser ones. The same village also has its own appellation for dry red wine."),
    Q("Southern crus and sweet wines",
      "Roussillon may blend a second, coarser Muscat into its fortified sweet wines, while the Rhone version admits a single Muscat and no other. Which variety?",
      ["Muscat Blanc a Petits Grains", "Muscat of Alexandria", "Muscat Ottonel",
       "Muscat Hamburg"], 0,
      "The small-berried white Muscat is the perfumed one, orange blossom and crushed grape, and it is all the Rhone appellation will take, its red-berried form counting as the same variety. Rivesaltes and its neighbours lean on Muscat of Alexandria as well, which is fatter and less floral. Muscat Ottonel is a nineteenth-century crossing grown in Alsace and central Europe, and Muscat Hamburg is a table grape."),
    Q("Southern crus and sweet wines",
      "Which variety is prized in southern rose for perfume and freshness rather than for power?",
      ["Cinsault", "Mourvedre", "Carignan", "Syrah"], 0,
      "It gives pale colour, floral aroma and low tannin, so it dilutes weight in the best sense. In red blends it is the grape that keeps a hot vintage drinkable."),

    # ------------------------ Cotes du Rhone and the regional tiers (4) ------
    Q("Cotes du Rhone and the regional tiers",
      "Bottles from the valley climb through a hierarchy of appellations. Which sequence runs from the broadest tier to the narrowest?",
      ["Cotes du Rhone, then Villages, then Villages with a named commune, then the crus",
       "Cotes du Rhone, then the crus, then Villages, then Villages with a named commune",
       "The crus, then Cotes du Rhone, then Villages, then Villages with a named commune",
       "Villages, then Cotes du Rhone, then the crus, then Villages with a named commune"], 0,
      "Each step up tightens yields and narrows the ground. A cru drops the Cotes du Rhone name entirely and stands on its own, which is the clearest signal on the label."),
    Q("Cotes du Rhone and the regional tiers",
      "Adding a commune name such as Sablet or Seguret after Cotes du Rhone Villages signals what?",
      ["A smaller delimited area with stricter rules than plain Villages",
       "The wine comes from a single estate",
       "The commune has been promoted to cru status",
       "The wine may be sold only within France"], 0,
      "The named communes are the waiting room for promotion, and several current crus passed through it. They are reliably the best value in the valley."),
    Q("Cotes du Rhone and the regional tiers",
      "May a grower in the northern half of the valley label a wine Cotes du Rhone?",
      ["Yes, the regional appellation covers the whole valley",
       "No, it applies to the southern half only",
       "Only if the wine is white",
       "Only in years when no cru wine is declared"], 0,
      "The regional appellation runs from Vienne to Avignon, though the overwhelming majority of the wine is southern. A northern grower with young vines or declassified fruit uses it regularly."),
    Q("Cotes du Rhone and the regional tiers",
      "Which trio of grapes forms the backbone of most red Cotes du Rhone?",
      ["Grenache, Syrah and Mourvedre", "Grenache, Cinsault and Carignan",
       "Syrah, Marsanne and Roussanne", "Cabernet Sauvignon, Merlot and Grenache"], 0,
      "Grenache brings the sweet fruit and alcohol, Syrah the colour and pepper, Mourvedre the tannin and savour. The abbreviation has followed the blend around the world."),

    # -------------------- soils, mistral and vineyard practice (4) -----------
    Q("Soils, mistral and vineyard practice",
      "A cold, dry wind funnels down the valley from the north, sometimes for days on end. What is it called?",
      ["The mistral", "The tramontane", "The sirocco", "The foehn"], 0,
      "It accelerates as the valley narrows and can blow at over a hundred kilometres an hour. Locals blame it for a great deal more than viticulture."),
    Q("Soils, mistral and vineyard practice",
      "Growers put up with that wind for one clear benefit. What is it?",
      ["It dries the vines and holds fungal disease in check",
       "It ripens the grapes by warming the vineyard",
       "It raises humidity around the bunches",
       "It carries mineral dust onto the leaves"], 0,
      "A dry canopy is why organic farming is so much easier here than in a damp maritime region. The cost is broken shoots and vines under stress in a hard spring."),
    Q("Soils, mistral and vineyard practice",
      "Low bush-trained vines carrying neither wire nor stake are the classic southern answer to that wind. What is that training called?",
      ["Gobelet", "Guyot", "Cordon de Royat", "Echalas"], 0,
      "The short trunk keeps the vine stable and its own canopy shades the fruit from fierce sun. Newer plantings are often trellised instead, so that machines can work the rows."),
    Q("Soils, mistral and vineyard practice",
      "Thin, free-draining rock on the steep northern slopes against deep beds of stone on the southern plain. Which pairing names the two?",
      ["Granite in the north and galets roules in the south",
       "Chalk in the north and clay in the south",
       "Volcanic basalt in the north and limestone in the south",
       "Sand in the north and slate in the south"], 0,
      "Granite gives the taut, mineral frame of northern Syrah; the stones of the south store heat and push Grenache toward ripeness and alcohol. The contrast explains most of the difference in the glass."),
]
