"""Rank I rewrite - Sake & Spirits (64 questions).

Written from the syllabus below. The imported bank was not read while writing.

Every stem opener is distinct, and the constructions in lib.BANNED_TEMPLATES are
avoided by design rather than by later reframing. Where the answer is a term,
the term is kept out of the opening clause so the stem leads with the symptom or
the scenario instead of the subject noun.
"""

from lib import Q

CAT = "Sake & Spirits"
SLUG = "r1-sake-spirits"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Sake rice and water", 5),
    ("Polishing and koji", 6),
    ("Sake brewing", 5),
    ("Special designation sake", 7),
    ("Sake styles and terms", 5),
    ("Serving sake", 5),
    ("Distillation basics", 5),
    ("Brandy", 6),
    ("Whisky", 7),
    ("Agave spirits", 4),
    ("Rum, gin and vodka", 5),
    ("Liqueurs and bitters", 4),
]

BANK = [
    # ---------------------------------------------- sake rice and water (5) --
    Q("Sake rice and water",
      "A beverage is made by converting rice starch into sugar and fermenting it, with no still involved at any point. Which drink is that?",
      ["Sake", "Shochu", "Awamori", "Baijiu"], 0,
      "Sake is brewed, closer in method to beer than to wine, and never distilled. The other three are spirits, which is why they arrive at far higher strengths."),
    Q("Sake rice and water",
      "Grains chosen for brewing carry a chalky opaque centre that table rice lacks. What is that core called?",
      ["Shinpaku", "Koji", "Moromi", "Kasu"], 0,
      "The shinpaku is loose starch that the mould can penetrate easily. Brewing varieties also grow larger grains with less protein and fat in the outer layers."),
    Q("Sake rice and water",
      "Which named rice variety is the most sought after by brewers, grown chiefly in Hyogo prefecture?",
      ["Yamada Nishiki", "Koshihikari", "Gohyakumangoku", "Omachi"], 0,
      "Yamada Nishiki is treated as the benchmark and commands a premium at competition level. Gohyakumangoku belongs to Niigata and Omachi to Okayama; Koshihikari is an eating rice."),
    Q("Sake rice and water",
      "Roughly four fifths of what ends up in the bottle is a single ingredient. Which one?",
      ["Water", "Rice", "Koji", "Distilled alcohol"], 0,
      "Because water dominates the volume, its mineral profile shapes the finished style, and breweries have historically been sited on a particular spring or well."),
    Q("Sake rice and water",
      "Brewing water rich in minerals such as potassium and magnesium pushes the ferment which way?",
      ["Faster and more vigorous, giving a firmer, drier sake",
       "Slower and cooler, giving a sweeter, rounder sake",
       "It has no measurable effect on fermentation",
       "It stops fermentation before the yeast finishes"], 0,
      "Nada in Hyogo built its name on hard water known as miyamizu. Kyoto's Fushimi district sits on soft water and is known for a gentler, softer style."),

    # ----------------------------------------------- polishing and koji (6) --
    Q("Polishing and koji",
      "A label states a seimaibuai of 50 percent. What does that figure tell you?",
      ["Half of each grain has been milled away",
       "Half the finished sake is water",
       "Half the rice used was ordinary table rice",
       "The sake rested for half a year before release"], 0,
      "The ratio names what remains, not what was removed, which is the commonest misreading. The lower the number, the more of the grain has gone to dust."),
    Q("Polishing and koji",
      "The outer layers of each grain are milled off before brewing mainly to get rid of what?",
      ["Protein and fat, which throw coarse off-flavours",
       "Starch, which the yeast cannot ferment",
       "Water held inside the husk",
       "Colour compounds that would tint the sake"], 0,
      "Protein, fat and minerals concentrate near the surface and produce heavy, savoury notes. Milling is slow work and can take two or three days for a competition sake."),
    Q("Polishing and koji",
      "Which organism is cultivated on steamed rice to break the starch down into fermentable sugar?",
      ["Aspergillus oryzae, the koji mould", "Saccharomyces cerevisiae, brewer's yeast",
       "Lactobacillus, a bacterium", "Botrytis cinerea, a vineyard fungus"], 0,
      "Aspergillus oryzae releases enzymes that cleave starch into glucose. Yeast then eats that glucose, so the two organisms have entirely separate jobs."),
    Q("Polishing and koji",
      "Saccharification and alcoholic fermentation run at the same time in the same tank. What is that arrangement called?",
      ["Multiple parallel fermentation", "Malolactic conversion",
       "Carbonic maceration", "Solera fermentation"], 0,
      "Sugar is released only as fast as the yeast consumes it, so the mash never becomes syrupy. It is why sake reaches close to 20 percent alcohol without fortification."),
    Q("Polishing and koji",
      "Where is the mould propagated during the two days or so that it takes to make koji?",
      ["In the koji muro, a warm and humid dedicated room",
       "In the pressing shed alongside the finished mash",
       "In an open outdoor yard", "Inside the main fermentation tank"], 0,
      "The muro is held warm and damp and the rice is turned by hand through the night. It is the stage brewers describe as the one that decides the sake."),
    Q("Polishing and koji",
      "Barley malt supplies its own enzymes to a beer mash. What does that job in a sake mash?",
      ["Koji", "Yeast", "Water", "Distilled alcohol"], 0,
      "Malting germinates the barley and wakes its enzymes. Rice has no equivalent trick, so the enzymes have to be supplied from outside by the mould."),

    # ------------------------------------------------------ sake brewing (5) --
    Q("Sake brewing",
      "After the rice has been washed and soaked, how is it prepared for the mould and the mash?",
      ["It is steamed rather than boiled", "It is boiled in water until soft",
       "It is roasted dry over a flame", "It is milled for a second time"], 0,
      "Steaming firms the outside of the grain while softening the inside, which is exactly what the mould needs. Boiled rice turns to paste and is useless for brewing."),
    Q("Sake brewing",
      "Which stage supplies the dense, healthy yeast population that goes on to drive the main mash?",
      ["The shubo, also called the moto", "The moromi",
       "The joso, or pressing", "The hi-ire, or pasteurisation"], 0,
      "The starter concentrates yeast in a small, acidic volume before it is scaled up. Building it takes anywhere from two weeks to a month depending on the method."),
    Q("Sake brewing",
      "A brewery adds lactic acid directly to the starter to keep spoilage organisms out while the yeast builds. Which method is that?",
      ["Sokujo", "Kimoto", "Yamahai", "Shizuku"], 0,
      "Sokujo is the modern default and takes about two weeks. Kimoto and yamahai instead wait for ambient lactic bacteria to acidify the starter, which takes far longer."),
    Q("Sake brewing",
      "Why is the main mash built up in three staged additions spread across four days?",
      ["To keep the yeast dense enough to stay dominant as the volume grows",
       "To lower the final alcohol content",
       "To satisfy a labelling requirement",
       "To make the mash easier to press"], 0,
      "Adding all the rice and water at once would dilute the yeast and let spoilage organisms take hold. A rest day between the first and second additions lets the yeast catch up."),
    Q("Sake brewing",
      "Once fermentation finishes the mash is pressed. What is the solid residue left behind?",
      ["Sake kasu, the pressed lees", "Koji", "Moto", "Shinpaku"], 0,
      "Kasu is a valued ingredient in its own right, used for pickling vegetables and fish and for the winter soup kasujiru. Nothing about it is waste."),

    # ------------------------------------------ special designation sake (7) --
    Q("Special designation sake",
      "A bottle carries no grade beyond the brewery name and accounts for the bulk of what Japan drinks. What is that category?",
      ["Futsu-shu, ordinary sake", "Junmai", "Ginjo", "Daiginjo"], 0,
      "Ordinary sake sits outside the eight special designations and faces looser rules on milling and additions. Premium grades are the minority of national output."),
    Q("Special designation sake",
      "Which word on a label guarantees that nothing but rice, water, koji and yeast went in?",
      ["Junmai", "Honjozo", "Ginjo", "Genshu"], 0,
      "Junmai means pure rice. It says nothing by itself about how far the rice was milled, so junmai can be anything from workmanlike to superb."),
    Q("Special designation sake",
      "A small, measured quantity of distilled alcohol has been stirred into the mash before pressing. Which designation covers that?",
      ["Honjozo", "Junmai", "Genshu", "Nigori"], 0,
      "The addition is capped at 10 percent of the weight of the polished rice. It lifts aroma out of the mash and lightens the body rather than stretching the volume."),
    Q("Special designation sake",
      "No more than what proportion of each grain may remain for a sake to be labelled ginjo?",
      ["60 percent", "70 percent", "50 percent", "80 percent"], 0,
      "Ginjo also demands careful, cool, slow brewing on top of the milling figure. Honjozo needs 70 percent or less, and daiginjo 50 percent or less."),
    Q("Special designation sake",
      "Two bottles show milling figures of 50 percent and 60 percent. What is the highest grade each figure unlocks?",
      ["Daiginjo and ginjo respectively", "Ginjo and daiginjo respectively",
       "Honjozo and junmai respectively", "Futsu-shu and honjozo respectively"], 0,
      "Fifty percent or less opens the door to daiginjo, sixty percent or less to ginjo. Add junmai to either name and the sake also has no added alcohol."),
    Q("Special designation sake",
      "The prefix tokubetsu sits in front of junmai or honjozo on a label. What is the brewery claiming?",
      ["Extra milling or another special method, which must be declared",
       "That the sake was never pasteurised",
       "That the sake is sparkling",
       "That the sake was aged for ten years"], 0,
      "Tokubetsu means special, and the brewery has to say what the special element is. Usually it is milling to 60 percent or the use of a single prized rice."),
    Q("Special designation sake",
      "Slow fermentation at deliberately low temperatures, chasing a fruity and floral perfume, is the signature of which approach?",
      ["Ginjo-zukuri", "Kimoto-zukuri", "Yamahai-zukuri", "Sokujo-zukuri"], 0,
      "Cool, long fermentation preserves the esters that give melon, pear and banana notes, known collectively as ginjo-ka. The other three names describe starter methods instead."),

    # ------------------------------------------- sake styles and terms (5) --
    Q("Sake styles and terms",
      "A cloudy white sake still carrying suspended rice solids has been through which treatment?",
      ["A coarse filtration, so it is sold as nigori",
       "No charcoal filtration, so it is sold as muroka",
       "No dilution, so it is sold as genshu",
       "Cedar cask ageing, so it is sold as taruzake"], 0,
      "Nigori is pressed through a wide mesh that lets rice solids through, so the bottle is usually rolled gently before pouring. Muroka is a different claim altogether: charcoal filtration was skipped, which keeps colour and texture but leaves nothing in suspension."),
    Q("Sake styles and terms",
      "Bottles marked nama have to be kept refrigerated from brewery to glass. What has been left out?",
      ["Pasteurisation", "Filtration", "Pressing", "Milling"], 0,
      "Most sake is pasteurised twice, once before storage and once at bottling. Skipping it leaves live enzymes and a fresher, livelier flavour that spoils if it warms up."),
    Q("Sake styles and terms",
      "Which term tells you that no water was added to bring the strength down before bottling?",
      ["Genshu", "Nigori", "Koshu", "Namazake"], 0,
      "Genshu usually lands between 17 and 20 percent instead of the customary 15 or 16. It suits ice or a splash of water at the table."),
    Q("Sake styles and terms",
      "A guest asks for the Japanese spirit distilled from barley, sweet potato or rice. What should you point them toward?",
      ["Shochu", "Sake", "Mirin", "Amazake"], 0,
      "Shochu goes through a still and typically arrives at around 25 percent, so it is not sake at all. Mirin is a sweet cooking wine and amazake is barely alcoholic."),
    Q("Sake styles and terms",
      "Deliberately matured sake that has darkened to amber and turned nutty and savoury goes by which name?",
      ["Koshu", "Shiboritate", "Arabashiri", "Nigori"], 0,
      "Koshu is a small niche because the overwhelming majority of sake is meant to be drunk young, ideally within a year of leaving the brewery."),

    # ------------------------------------------------------ serving sake (5) --
    Q("Serving sake",
      "Which vessel would you set on the table to pour from rather than to drink from?",
      ["A tokkuri", "An ochoko", "A masu", "A sakazuki"], 0,
      "The tokkuri is the narrow-necked flask. The ochoko is the small cup, the masu the square cedar box, and the sakazuki the flat ceremonial dish."),
    Q("Serving sake",
      "A delicate daiginjo is going to the table. How should it reach the guest?",
      ["Chilled, so the aromatics survive",
       "Heated to around 50 degrees Celsius",
       "Warmed gently in a flask of hot water",
       "Poured over a full glass of ice"], 0,
      "Heat drives off the fine esters that the brewer worked at low temperature to build. Sturdier junmai and honjozo take warming far better."),
    Q("Serving sake",
      "Warming sake to roughly 50 degrees Celsius before service is described by which word?",
      ["Atsukan", "Reishu", "Hiya", "Genshu"], 0,
      "Atsukan is the hot end of the scale and nurukan a gentler 40 or so. Reishu means chilled and hiya means served at ambient temperature without heating."),
    Q("Serving sake",
      "Most sake reaches the guest at what alcoholic strength?",
      ["About 15 to 16 percent", "About 5 to 6 percent",
       "About 25 percent", "About 40 percent"], 0,
      "The mash itself ferments to nearly 20 percent and is then cut with water before bottling. Undiluted genshu skips that step and stays higher."),
    Q("Serving sake",
      "An opened bottle is going back into the refrigerator. What should the guest be told about it?",
      ["It oxidises quickly and is best finished within a few days",
       "It will keep improving for several months",
       "It can sit out at room temperature indefinitely",
       "It should be frozen to preserve it"], 0,
      "Sake has no tannin and little acidity to defend it once air gets in. Treat an open bottle the way you would treat an open white wine, or more carefully still."),

    # ----------------------------------------------- distillation basics (5) --
    Q("Distillation basics",
      "Separating alcohol from water inside a still relies on which difference between the two?",
      ["Their boiling points", "Their colours",
       "Their sugar contents", "Their acidities"], 0,
      "Ethanol boils near 78 degrees Celsius and water at 100, so the vapour coming off is richer in alcohol. Distillation concentrates alcohol; it never creates any."),
    Q("Distillation basics",
      "A still is charged, run off, emptied and then charged again for the next run. Which type behaves that way?",
      ["A pot still", "A column still", "An alambic armagnacais", "A worm tub"], 0,
      "Batch working leaves more congeners in the spirit, which is why pot stills suit flavour-driven categories. A column still and the small alambic armagnacais both run without pause, and a worm tub is a condenser rather than a still at all."),
    Q("Distillation basics",
      "The distiller sets aside the first and last portions of a run and keeps only the middle. What are those two outer fractions called?",
      ["Heads and tails", "Hearts and cuts",
       "Lees and pomace", "Wash and low wines"], 0,
      "Heads carry volatile, solvent-like compounds and tails carry heavy, oily ones, so only the middle cut, the hearts, goes forward from this run. They are not waste: most distillers hold them back and put them into the next charge, which is why a still house wastes very little."),
    Q("Distillation basics",
      "A cask quietly loses a few percent of its contents to the air every year in the warehouse. What is that loss called?",
      ["The angels' share", "The devil's cut",
       "The heart of the run", "The feints"], 0,
      "Liquid evaporates through the staves, and in a humid warehouse the strength falls while a dry one loses more water. The devil's cut is the spirit soaked into the wood itself."),
    Q("Distillation basics",
      "A bottle sold in the United States reads 80 proof. What strength is in the glass?",
      ["40 percent alcohol by volume", "80 percent alcohol by volume",
       "20 percent alcohol by volume", "60 percent alcohol by volume"], 0,
      "American proof is simply twice the alcohol by volume. Eighty proof is the legal floor for most spirit categories sold there."),

    # ------------------------------------------------------------ brandy (6) --
    Q("Brandy",
      "Which white grape supplies the overwhelming majority of the base wine for Cognac?",
      ["Ugni Blanc", "Chardonnay", "Sauvignon Blanc", "Chenin Blanc"], 0,
      "The base wine is thin, sharp and low in alcohol, which is unappealing to drink and ideal to distil. Folle Blanche and Colombard are also permitted but planted far less."),
    Q("Brandy",
      "Two of the six Cognac crus carry the word Champagne in their names. Which of them ranks highest?",
      ["Grande Champagne", "Petite Champagne", "Borderies", "Fins Bois"], 0,
      "Both sit on chalky soils that give long-lived, floral spirit. A bottle labelled Fine Champagne blends the two, with at least half from Grande Champagne."),
    Q("Brandy",
      "How many times must Cognac go through the still, and in what apparatus?",
      ["Twice, in a Charentais pot still", "Once, in a column still",
       "Three times, in a pot still", "Continuously, in a Coffey still"], 0,
      "The second pass, the bonne chauffe, is where the cuts are made. Armagnac by contrast traditionally takes a single pass through a column of its own design."),
    Q("Brandy",
      "A label reads VSOP. What is the minimum age of the youngest spirit in that blend?",
      ["Four years", "Two years", "Six years", "Ten years"], 0,
      "VS requires two years and VSOP four. Age statements on blended spirits always describe the youngest component, never the average."),
    Q("Brandy",
      "Gascony distils its brandy traditionally in a single pass through a small continuous column of local design. Which spirit is that?",
      ["Armagnac", "Cognac", "Calvados", "Marc de Bourgogne"], 0,
      "The alambic armagnacais delivers a lower-strength, more aromatic and more rustic spirit. Bas-Armagnac is the most admired subregion, and single-vintage bottlings are a local tradition."),
    Q("Brandy",
      "Normandy fills its stills with something that is not a grape at all. What comes out?",
      ["Apple brandy, sold as Calvados", "Cherry brandy, sold as kirsch",
       "Pear brandy, sold as poire williams", "Pomace brandy, sold as marc"], 0,
      "Cider is distilled, with pears permitted alongside apples. Pays d'Auge is the appellation that insists on double distillation in pot stills."),

    # ------------------------------------------------------------ whisky (7) --
    Q("Whisky",
      "Which requirement must every Scotch satisfy before it can legally be sold?",
      ["At least three years in oak casks in Scotland",
       "At least ten years in oak casks",
       "Ageing in new charred oak only",
       "Distillation three times"], 0,
      "Three years in oak in Scotland and a minimum of 40 percent alcohol are the baseline. Any age on the label refers to the youngest whisky in the bottle."),
    Q("Whisky",
      "A bottle says single malt. What exactly does the word single promise?",
      ["That every drop came from one distillery",
       "That it came from one cask",
       "That it went through the still only once",
       "That only one grain besides barley was used"], 0,
      "Single means one distillery, not one barrel; the contents are usually a blend of many casks. A one-barrel bottling is labelled single cask separately."),
    Q("Whisky",
      "Smoke, tar and medicinal iodine in a malt whisky are picked up at which point in production?",
      ["When the malted barley is dried over a peat fire",
       "During fermentation in the washback",
       "From the cask during maturation",
       "From sea water added before bottling"], 0,
      "Burning peat coats the damp malt in phenolic compounds that survive all the way to the glass. Islay is the classic home of the style, though peating is a choice, not a place."),
    Q("Whisky",
      "Which grain has to make up at least 51 percent of the mash bill for a whiskey to be called bourbon?",
      ["Corn", "Rye", "Malted barley", "Wheat"], 0,
      "The balance is usually rye or wheat plus a little malted barley for enzymes. Wheated bourbons read softer and rounder; high-rye ones read spicier."),
    Q("Whisky",
      "Casks used to mature bourbon can be filled only once. What kind are they?",
      ["New charred oak", "Used sherry butts",
       "Refilled bourbon barrels", "Untoasted chestnut casks"], 0,
      "That one-fill rule floods the world with cheap ex-bourbon barrels, which is why Scotch, Irish whiskey, rum and tequila so often mature in them."),
    Q("Whisky",
      "Before it goes into the barrel, a Tennessee whiskey is filtered through a deep bed of sugar maple charcoal. What is that step called?",
      ["The Lincoln County Process", "The sour mash process",
       "Chill filtration", "The solera system"], 0,
      "The charcoal strips harsher compounds from the new spirit and is what separates Tennessee whiskey from bourbon. Sour mash, by contrast, means recycling spent stillage into the next mash."),
    Q("Whisky",
      "Triple distillation and a generally unpeated character are most associated with which country's whiskey?",
      ["Ireland", "Scotland", "Canada", "Japan"], 0,
      "Irish whiskey also has a category of its own in single pot still, made from a mash of both malted and unmalted barley, which gives a distinctive creamy, spicy weight."),

    # ----------------------------------------------------- agave spirits (4) --
    Q("Agave spirits",
      "Which single agave species is permitted for tequila?",
      ["Blue Weber agave", "Espadin", "Tobala", "Any of roughly thirty species"], 0,
      "Tequila is restricted to one plant, grown chiefly in Jalisco. Mezcal may draw on many species, of which espadin is by far the most planted."),
    Q("Agave spirits",
      "The harvested heart of the plant is trimmed of its spiked leaves before cooking. What is that heart called?",
      ["The pina", "The quiote", "The mosto", "The bagazo"], 0,
      "It is named for its resemblance to a pineapple and can weigh well over forty kilograms. The plant takes several years in the ground before it is ready to cut."),
    Q("Agave spirits",
      "A tequila has spent five months in oak. Which category does that put it in?",
      ["Reposado", "Blanco", "Anejo", "Extra anejo"], 0,
      "Blanco is essentially unaged, reposado runs from two to twelve months, anejo from one to three years and extra anejo beyond three."),
    Q("Agave spirits",
      "Where does the smoke in most mezcal come from?",
      ["Roasting the agave in wood-fired earthen pits",
       "Peat burned under the mash", "Heavily charred oak barrels",
       "Smoke added after distillation"], 0,
      "The pit roast is the defining step and puts smoke into the sugar before fermentation even begins. Tequila steams its agave in ovens or autoclaves, which is why it is not smoky."),

    # ------------------------------------------------ rum, gin and vodka (5) --
    Q("Rum, gin and vodka",
      "Every rum in the world begins with which raw material?",
      ["Sugarcane, either as molasses or as fresh juice",
       "Malted barley", "Corn", "Agave"], 0,
      "Most of the Caribbean ferments molasses, the residue of sugar refining. Rhum agricole, the Martinique style, ferments fresh-pressed cane juice instead and tastes grassier for it."),
    Q("Rum, gin and vodka",
      "Brazil's national spirit is pressed and fermented from cane on the day it is cut. What is it called?",
      ["Cachaca", "Pisco", "Grappa", "Rhum agricole"], 0,
      "Cachaca is legally its own category in Brazil rather than a rum, and it is the base of the caipirinha. Unaged versions are clear; aged ones rest in native woods."),
    Q("Rum, gin and vodka",
      "Which botanical has to lead for a spirit to be sold as gin at all?",
      ["Juniper", "Coriander", "Angelica", "Orris root"], 0,
      "Juniper must be the predominant flavour by law. Coriander, angelica and orris are common supporting players but none of them can carry the category."),
    Q("Rum, gin and vodka",
      "No flavouring or colouring may be introduced once the spirit has left the still. Which style carries that restriction?",
      ["London Dry gin", "Old Tom gin", "Genever", "Sloe gin"], 0,
      "London Dry is a method rather than a place, so it can be made anywhere. Old Tom is sweetened, genever is built on malt wine, and sloe gin is a flavoured liqueur."),
    Q("Rum, gin and vodka",
      "Rectifying a spirit to a very high strength and stripping out what character remains produces which category?",
      ["Vodka", "Gin", "Aquavit", "Absinthe"], 0,
      "The base can be grain, potato, grape or molasses, since the aim of the process is to remove its fingerprint. The other three are all deliberately flavoured after or during distillation."),

    # -------------------------------------------- liqueurs and bitters (4) --
    Q("Liqueurs and bitters",
      "A bitter red Italian aperitivo, taken with soda or in a Negroni, is most likely which of these?",
      ["Campari", "Fernet-Branca", "Cynar", "Averna"], 0,
      "A Negroni is equal parts gin, Campari and sweet vermouth. Fernet is a bracing digestive, Cynar is built on artichoke, and Averna is sweeter and darker."),
    Q("Liqueurs and bitters",
      "Which category covers the bitter Italian herbal digestives poured after a meal?",
      ["Amaro", "Amaretto", "Sambuca", "Limoncello"], 0,
      "Amaro simply means bitter, and the family runs from gentle to punishing. Amaretto is sweet and almond-scented, sambuca is anise-led, and limoncello is a lemon liqueur."),
    Q("Liqueurs and bitters",
      "Green and yellow versions of one French herbal liqueur have been produced by Carthusian monks for centuries. Which is it?",
      ["Chartreuse", "Benedictine", "Drambuie", "Galliano"], 0,
      "The green is the stronger and more assertive of the pair, the yellow softer and honeyed. The recipe draws on a long list of botanicals and has never been published."),
    Q("Liqueurs and bitters",
      "Aniseed-scented spirits turn milky white the moment water is added. What is that effect called?",
      ["The louche", "The bloom", "The angels' share", "The cut"], 0,
      "Anethole dissolves in alcohol but not in water, so it drops out of solution as an emulsion. Pastis, ouzo, raki and absinthe all do it."),
]
