"""Rank I rewrite - South Africa (56 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

The category is built on one idea: the Cape is a narrow winelands wedged between
two oceans and standing on some of the oldest rock under vine anywhere, and
almost everything a student needs to know follows from that. So the running
order starts with the physical Cape - the cold Benguela water, the south-easter
that rides in on it, the folded mountains and the ancient granite, shale and
sandstone - then takes the Wine of Origin scheme, which says where and only
where, then walks the districts outward from Stellenbosch to the west coast, the
peninsula, the south coast and the hot interior, and closes on the grapes: the
cross made at Stellenbosch in 1925, the white the Cape called Steen, and the
sparkling wine named for a method rather than a place. Stems lead with a wind,
a rock, a fog bank, a bottle in the hand or a label at the cellar door, and let
the place, grape or term be the answer.

The Rank II South Africa category sits above this one, so ward boundaries in
detail, clonal history and producer specifics are left to it.

Everything is ASCII: Hemel-en-Aarde, Cotes, Rhone, Muscat de Frontignan.
"""

from lib import Q

CAT = "South Africa"
SLUG = "r1-south-africa"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Cape geography and climate", 5),
    ("History and the industry's institutions", 4),
    ("The Wine of Origin scheme", 7),
    ("Soils and the old rocks", 4),
    ("Stellenbosch, Paarl and Franschhoek", 7),
    ("Swartland, Darling and the Coastal Region", 5),
    ("Constantia and the Cape Peninsula", 4),
    ("The Cape South Coast", 6),
    ("Breede River and the Klein Karoo", 5),
    ("Pinotage and the Cape reds", 4),
    ("Chenin Blanc, the whites and Cap Classique", 5),
]

BANK = [
    # ------------------------------------- Cape geography and climate (5) ----
    Q("Cape geography and climate",
      "Two ocean currents pass the southern tip of Africa, one cold and running north up the Atlantic seaboard, one warm and running south down the Indian Ocean side. Which of them does the cooling for the winelands?",
      ["The Benguela, which carries cold water north along the west coast",
       "The Agulhas, which brings warm Indian Ocean water down the east coast",
       "The Mozambique Channel drift, which runs down the far east coast",
       "The Canary current, which runs down the north-west African coast"], 0,
      "Water off the west coast is far colder than the latitude suggests, and the sea air and morning fog that come off it drop temperatures wherever a vineyard sits within reach. The Agulhas is real and it is warm, which is why the country's cool sites face the Atlantic rather than the Indian Ocean."),
    Q("Cape geography and climate",
      "Rain arrives in the Cape winelands mostly between May and August, and hardly falls at all while the fruit is ripening. Which climate type does that pattern name?",
      ["Mediterranean", "Continental", "Tropical savannah", "Cool maritime"], 0,
      "Winter-dominant rainfall with a hot dry summer is the Mediterranean signature, and it makes water rather than sunshine the limiting factor. Inland districts irrigate as a matter of course, while dry farming survives only where the soil can hold the winter rain deep enough to last."),
    Q("Cape geography and climate",
      "A hard wind blows out of the south-east for days at a time through the Cape summer, dries the canopy and knocks back rot. What do locals call it?",
      ["The Cape Doctor", "The Berg wind", "The Levanter", "The Sirocco"], 0,
      "The nickname is a compliment: by scouring humidity out of the vineyard it holds back botrytis and powdery mildew, and it drops temperatures at the same time. The bill is paid at flowering, when a strong blow shakes off crop and thickens skins on what remains. A berg wind is the opposite thing, hot and dry off the interior."),
    Q("Cape geography and climate",
      "A buyer plans a trip taking in every major Cape wine district, and never has to cross a provincial boundary to do it. Which province is he driving around in?",
      ["Western Cape", "Northern Cape", "Eastern Cape", "KwaZulu-Natal"], 0,
      "The Northern Cape does grow vines along the Orange River, and there are token plantings elsewhere, but the Western Cape holds the overwhelming bulk of the industry. Everything outside it is either too hot, too dry or, on the eastern side of the country, too wet in summer."),
    Q("Cape geography and climate",
      "Long ridges of folded rock run through the winelands and divide them into separate valleys, giving growers altitude and aspect that a plain could not. What are those ranges called?",
      ["The Cape Fold Mountains", "The Drakensberg escarpment",
       "The Magaliesberg", "The Soutpansberg"], 0,
      "The Cape Fold Belt was thrown up about two hundred and fifty million years ago, when the southern edge of Gondwana was crumpled against the ocean plate grinding under it, and the Simonsberg, Helderberg, Hottentots Holland and Groot Drakenstein all belong to it. The ranges matter more than latitude here: they block or funnel the sea air, and they carry the vineyards that need height to stay cool."),

    # -------------------------- History and the industry's institutions (4) --
    Q("History and the industry's institutions",
      "Vines were planted at a Dutch supply post below Table Mountain within a few years of its founding, and the first Cape wine was pressed in 1659. What had the post been established to do?",
      ["Victual ships on the sea route to the East Indies",
       "Serve as a penal colony for the Dutch Republic",
       "Work the alluvial gold of the Cape Flats",
       "House a mission school for the interior"], 0,
      "Jan van Riebeeck's refreshment station stood halfway between Europe and the East Indies, and it existed to put fresh food and drink aboard passing fleets. Wine was thought to help against scurvy on the long haul east. That is why viticulture reached the Cape early and by a commercial rather than a monastic route."),
    Q("History and the industry's institutions",
      "French Protestant refugees were granted farms in a mountain-ringed valley east of Cape Town from 1688, and the valley still carries a name meaning French corner. Which valley?",
      ["Franschhoek", "Tulbagh", "Jonkershoek", "Hemel-en-Aarde"], 0,
      "The Huguenots brought vine-growing experience the Dutch settlers lacked, and their surnames are still on estates there three centuries later. The valley is closed on three sides, which keeps the floor warm and still while the slopes above it stay cooler."),
    Q("History and the industry's institutions",
      "One Cape governor founded a town on the Eerste River in 1679 and planted a farm of his own on the slopes behind Cape Town six years later. Who was he?",
      ["Simon van der Stel", "Jan van Riebeeck",
       "Abraham Perold", "Paul Kruger"], 0,
      "Stellenbosch is named for him, and so is Simonsberg. The farm he took for himself behind Table Mountain, Constantia, became the source of the sweet wine that made the Cape famous in Europe, so one governor stands behind both the country's leading red district and its most famous sweet wine."),
    Q("History and the industry's institutions",
      "Formed in 1918 and given statutory power a few years later, a growers' co-operative fixed minimum prices and handed out production quotas until the system was dismantled in the 1990s. Which body was that?",
      ["The KWV", "The Wine and Spirit Board",
       "VinPro", "The Cape Winemakers Guild"], 0,
      "It was formed to cope with a grape surplus, and for seventy years it rewarded volume over quality: a quota was worth more than a good site, and high-cropping varieties were planted where they had no business being. Deregulation, and the end of the export boycott, are why so much of the modern Cape vineyard has been replanted."),

    # ------------------------------------- The Wine of Origin scheme (7) -----
    Q("The Wine of Origin scheme",
      "A label names a single pocket of ground inside a district rather than the district itself, telling the buyer the fruit came off that one patch. Which Wine of Origin tier is that tighter name?",
      ["A ward", "A subregion", "An estate", "A single vineyard"], 0,
      "The scheme nests geographical unit, region, district and ward, with the ward as the tightest tier and the one defined on soil, climate and ecology rather than on administrative convenience. A ward is where a Cape label gets closest to naming a piece of ground."),
    Q("The Wine of Origin scheme",
      "Vintage and variety claims on a Cape label each need eighty-five percent of the wine behind them. The origin claim is stricter than that. What does it demand?",
      ["Every grape must come from the named area",
       "Ninety percent of the grapes from the named area",
       "Ninety-five percent of the grapes from the named area",
       "The same eighty-five percent as the other two claims"], 0,
      "Origin is absolute in this system, which is worth knowing because the other two claims are not. A wine labelled Stellenbosch Cabernet Sauvignon 2019 was grown entirely in Stellenbosch, but may legitimately hold fifteen percent of another grape and fifteen percent of another year."),
    Q("The Wine of Origin scheme",
      "A visitor buys a bottle at a cellar door and the label reads Wine of Origin Estate. What has that phrase committed the producer to?",
      ["The grapes were grown and the wine made on the registered unit",
       "The property has been in one family for at least three generations",
       "The whole property lies inside a single ward",
       "The wine was bottled on site but the fruit may have been bought in"], 0,
      "An estate is registered as a production unit, so the claim is about farming and vinification happening in the same place. It says nothing whatever about quality, and a great many of the Cape's best wines are made from bought-in fruit and cannot use the term at all."),
    Q("The Wine of Origin scheme",
      "Registering a block as a single vineyard in South Africa carries a restriction no other origin tier imposes. What is capped?",
      ["The size of the block, at six hectares",
       "The yield, at fifty hectolitres per hectare",
       "The finished alcohol, at fourteen percent",
       "The planting density, at ten thousand per hectare"], 0,
      "The block must also be planted to one variety, so the designation means a genuinely single parcel rather than a marketing name. Six hectares is small enough that the wine really can be the expression of one site, which is the whole point of registering it."),
    Q("The Wine of Origin scheme",
      "One Wine of Origin region exists solely for fortified wine and overlays Paarl, Tulbagh and Wellington. Which region?",
      ["Boberg", "Klein Karoo", "Breede River Valley", "Olifants River"], 0,
      "Boberg is the oddity in the scheme: a region that sits on top of districts already covered by the Coastal Region, and that may be used only for fortified styles. The Klein Karoo makes a great deal of fortified wine but is an ordinary region covering every style."),
    Q("The Wine of Origin scheme",
      "Certification of a Cape wine's origin, vintage and variety claims is handled by a statutory body rather than by the producers themselves. Which body?",
      ["The Wine and Spirit Board", "The KWV",
       "SAWIS", "The Cape Winemakers Guild"], 0,
      "The board runs the scheme and issues the seal, which is why a Cape origin claim is auditable rather than merely asserted. SAWIS is a real organisation doing a different job, gathering the industry's statistics, and the Cape Winemakers Guild is a voluntary association of winemakers."),
    Q("The Wine of Origin scheme",
      "Since 2010 the sticker sealing a certified Cape bottle has carried a second guarantee alongside origin, vintage and variety, traceable through the number printed on it. What else does it certify?",
      ["That vineyard and cellar were run sustainably",
       "That no sulphur dioxide was added at any stage",
       "That the vineyard was never irrigated",
       "That residual sugar stays below a stated level"], 0,
      "The Integrated Production of Wine scheme audits farming and cellar practice against the industry's sustainability standards, and folding it into the same seal made participation close to universal. The number can be entered on a public site to trace the bottle back, which is unusual transparency for a national scheme."),

    # ------------------------------------------ Soils and the old rocks (4) --
    Q("Soils and the old rocks",
      "Weathered granite lies beneath the mountain foot slopes of Stellenbosch, Paarl and the Paardeberg, and growers farming without irrigation prize it. What does it give them?",
      ["A clay-rich soil that holds winter rain through a dry summer",
       "Drainage so free that daily irrigation becomes unavoidable",
       "A strongly alkaline soil that has to be corrected before planting",
       "Enough fertility to push yields well past what quality allows"], 0,
      "Granite breaks down to a deep reddish soil with real clay content, and that clay is a reservoir deep enough for the vine to draw on through months without rain and still finish the season. It is a large part of why unirrigated bush vines are possible on these slopes in a climate where the growing season is essentially dry."),
    Q("Soils and the old rocks",
      "The pale, quartz-rich rock that forms the cliffs above Cape Town also underlies vineyard soils across the winelands, and it is acidic and desperately poor in nutrients. What is it called?",
      ["Table Mountain Sandstone", "Malmesbury shale",
       "Bokkeveld shale", "Cape granite"], 0,
      "It weathers to a bleached, sandy, low-vigour soil that usually needs lime before it will grow anything, and it drains hard. Wines off it tend to be lean and taut rather than broad, which is exactly why growers chasing a finer style go looking for it."),
    Q("Soils and the old rocks",
      "Swartland growers talk constantly about the shale beneath their bush vines, a rock laid down long before anything with a shell existed. Which shale?",
      ["Malmesbury shale", "Bokkeveld shale",
       "Kimmeridgian marl", "Dwyka tillite"], 0,
      "Malmesbury shale is Precambrian, and it splits into plates roots can follow down through. It alternates with granite intrusions such as the Paardeberg across the district, and growers there will name which of the two a wine came off as readily as a Burgundian names a slope."),
    Q("Soils and the old rocks",
      "Rock beneath the Cape vineyards runs to hundreds of millions of years old, and in places far older than that, which is ancient even by the standards of the wine world. What has that age done to the soils above it?",
      ["It has stripped them of their nutrients",
       "It has made them unusually rich in organic matter",
       "It has made them uniformly alkaline",
       "It has left them too shallow for roots to pass a metre"], 0,
      "Soils formed on young volcanic or glacial material are still releasing minerals; soils weathered for this long have had theirs leached away. Low natural vigour suits quality, but it also means the Cape grower is managing an impoverished soil rather than restraining a fertile one."),

    # -------------------------- Stellenbosch, Paarl and Franschhoek (7) ------
    Q("Stellenbosch, Paarl and Franschhoek",
      "Granite foot slopes below the mountains, Cabernet-led reds, the country's main viticulture faculty and its oldest wine route all belong to a single district. Which one?",
      ["Stellenbosch", "Paarl", "Robertson", "Swartland"], 0,
      "The district runs from sandy flats near the water up to slopes well above three hundred metres, so one name covers a wide range of sites and styles. The wine route opened in 1971 and was the first in the country, which is much of why the town became the industry's centre of gravity."),
    Q("Stellenbosch, Paarl and Franschhoek",
      "Stellenbosch reaches south toward a large bay, and the afternoon wind coming off it is why the district ripens later than its inland neighbours. Which bay?",
      ["False Bay", "Walker Bay", "Table Bay", "Saldanha Bay"], 0,
      "The south-easter crosses that water before it reaches the vineyards, and the blocks closest to it pick latest. Table Bay lies on the other side of the peninsula at Cape Town, Saldanha is well up the west coast, and Walker Bay is a hundred kilometres east at Hermanus."),
    Q("Stellenbosch, Paarl and Franschhoek",
      "A bare granite dome above one Cape town gleams after rain, and both the town and its district take their name from it. Which district?",
      ["Paarl", "Tulbagh", "Darling", "Wellington"], 0,
      "Paarl means pearl in Dutch, and the outcrop is among the largest granite domes anywhere. The district is warmer and further from the sea than Stellenbosch, which pushes it toward Rhone varieties, Chenin Blanc and the fortified styles that gave Boberg its reason to exist."),
    Q("Stellenbosch, Paarl and Franschhoek",
      "Summer temperatures climb several degrees on the short drive inland from Stellenbosch to Paarl. What accounts for the jump?",
      ["Paarl lies further from the cold sea air",
       "Paarl lies considerably closer to the equator",
       "Paarl stands several hundred metres higher",
       "Paarl receives no winter rainfall to cool its soils"], 0,
      "Distance from the ocean is the strongest single variable in the Cape, and it changes faster than latitude ever could over twenty kilometres. The two districts share a border and a mountain, and still make quite different wine from the same grapes."),
    Q("Stellenbosch, Paarl and Franschhoek",
      "A white grape that once covered the great majority of Cape vineyards now survives chiefly in a handful of old blocks around Franschhoek. Which grape?",
      ["Semillon", "Chenin Blanc", "Palomino", "Colombard"], 0,
      "Cape growers called it groendruif, the green grape, for the colour of its leaves, and in the nineteenth century it was very nearly the whole white vineyard. It collapsed to a fraction of the plantings during the twentieth, and the surviving old vines are treated as heritage material."),
    Q("Stellenbosch, Paarl and Franschhoek",
      "Vine nurseries cluster in one district at the foot of Bain's Kloof, and most of the country's grafted planting material starts life there. Which district?",
      ["Wellington", "Tulbagh", "Elgin", "Robertson"], 0,
      "Almost every new Cape vineyard is planted with vines raised in that one valley, which makes its nurseries quietly influential over what the country grows. The district also makes ripe reds and Chenin Blanc in its own right, in a climate close to Paarl's."),
    Q("Stellenbosch, Paarl and Franschhoek",
      "One mountain lends its name to a ward in Stellenbosch and to a second ward in Paarl, on opposite flanks of the same slope. Which mountain?",
      ["Simonsberg", "Helderberg", "Kasteelberg", "Paardeberg"], 0,
      "Simonsberg-Stellenbosch and Simonsberg-Paarl share a mountain and a reputation for serious red wine, and the district boundary rather than the geology decides which name a grower may use. It is a neat demonstration that a ward is drawn on the land and a district on the map."),

    # ------------------ Swartland, Darling and the Coastal Region (5) --------
    Q("Swartland, Darling and the Coastal Region",
      "Wheat fields, rolling hills and unirrigated bush vines lie an hour north of Cape Town, in a district named for the dark colour its native scrub takes on. Which district?",
      ["Swartland", "Darling", "Tulbagh", "Wellington"], 0,
      "Swartland means black land, after the renosterbos that darkens the hills. It was farmed for grain and bulk wine for most of its history, and dry farming is the norm rather than a boast there, since outside the Berg River corridor on its eastern edge there is next to no water to irrigate with."),
    Q("Swartland, Darling and the Coastal Region",
      "Old dryland bush vines turned a bulk-farming district into the Cape's most closely watched source of fine wine over the last two decades. Which two varieties lead it?",
      ["Chenin Blanc for the whites and Syrah for the reds",
       "Sauvignon Blanc for the whites and Pinot Noir for the reds",
       "Chardonnay for the whites and Cabernet Sauvignon for the reds",
       "Colombard for the whites and Pinotage for the reds"], 0,
      "Chenin was already in the ground as old unirrigated bush vines, planted for bulk wine and brandy and then rediscovered, while the Syrah is largely modern planting, put on shale and granite from the 1990s by growers who had seen what the district could do. The reds are usually blended in the southern Rhone manner with Grenache, Mourvedre and Cinsaut, and the whites are picked earlier and handled far more gently than the district's history would suggest."),
    Q("Swartland, Darling and the Coastal Region",
      "Stellenbosch, Swartland and Darling are neighbouring districts gathered under a single regional name. Which region?",
      ["Coastal Region", "Cape South Coast", "Breede River Valley", "Klein Karoo"], 0,
      "Paarl, Wellington, Tulbagh and Cape Town belong to it as well, so a blend drawn across any of them still has a legal place name to print. The name is inherited rather than descriptive, and several districts genuinely on the coast are not in it."),
    Q("Swartland, Darling and the Coastal Region",
      "Cold Atlantic air reaches a small west coast district whose Groenekloof ward built a name for pungent, high-acid Sauvignon Blanc. Which district?",
      ["Darling", "Swartland", "Robertson", "Tulbagh"], 0,
      "The sea is close and the water is cold, so the mornings are foggy and the afternoons breezy even in midsummer. It sits immediately west of the Swartland and makes a completely different sort of wine because of that one difference."),
    Q("Swartland, Darling and the Coastal Region",
      "Follow the coast road north beyond the Swartland and vineyards continue up a river valley long known for volume, and now also for old Grenache high on the mountain slopes above it. Which region?",
      ["Olifants River", "Breede River Valley", "Cape South Coast", "Klein Karoo"], 0,
      "The valley floor is hot and irrigated and was built around co-operatives, but the Citrusdal Mountain district climbs several hundred metres above it, and the Piekenierskloof ward up there holds very old bush-vine Grenache. Altitude changed the region's reputation without changing its address."),

    # ----------------------------- Constantia and the Cape Peninsula (4) -----
    Q("Constantia and the Cape Peninsula",
      "Vines went into the slopes behind Cape Town in the 1680s on a governor's own farm, and the ward there is the oldest named wine origin in the country. Which ward?",
      ["Constantia", "Durbanville", "Hout Bay", "Philadelphia"], 0,
      "The original farm was later broken up, which is why several neighbouring estates carry versions of the name. The slopes are decomposed granite, face the incoming south-easter, and catch well over a metre of rain a year, which is a great deal by Cape standards."),
    Q("Constantia and the Cape Peninsula",
      "No spirit is added and no noble rot is involved, yet the Cape's most historic sweet wine reaches enormous sugar levels from fruit shrivelled on the vine. Which variety supplies it?",
      ["Muscat de Frontignan", "Muscat of Alexandria", "Chenin Blanc", "Semillon"], 0,
      "Muscat de Frontignan is the Cape name for the small-berried white Muscat, the grape the Cape also fortifies as Muscadel, and Muscat of Alexandria, which the Cape calls Hanepoot, is the coarser cousin grown for the table and for sweet fortified jerepigo. Production lapsed after phylloxera and the wine was revived in the 1980s, and its unusual distinction is that it concentrates by drying on the vine rather than by fungus or fortification."),
    Q("Constantia and the Cape Peninsula",
      "Morning fog off the cold Atlantic settles over hills at the edge of Cape Town's northern suburbs, where deep red clay grows sharply defined Sauvignon Blanc. Which ward?",
      ["Durbanville", "Constantia", "Groenekloof", "Devon Valley"], 0,
      "The hills are low but they sit directly in the path of sea air, and the clay holds enough water for dry farming. It is a reminder that in the Cape a cool site is made by the ocean or by height, never by going further south."),
    Q("Constantia and the Cape Peninsula",
      "The ward that gave the Cape its famous sweet wine is better known today for a dry white grown on cool granite slopes. Which grape?",
      ["Sauvignon Blanc", "Chardonnay", "Riesling", "Pinot Gris"], 0,
      "It is often bottled with a proportion of Semillon, in the Bordeaux manner rather than the Loire one, which gives it weight to carry the acidity. The sweet wine is still made, but it is a specialty of a couple of estates while the dry white is the ward's everyday business."),

    # --------------------------------------------- The Cape South Coast (6) --
    Q("The Cape South Coast",
      "A valley running inland from a whale-watching town on the south coast has become the country's reference point for Pinot Noir. What is that valley called?",
      ["Hemel-en-Aarde", "Bot River", "Jonkershoek", "Piekenierskloof"], 0,
      "The name means heaven and earth, and three separate wards climb it as the land rises away from the sea. All three sit inside the Walker Bay district, and the higher and further inland they go the later they pick."),
    Q("The Cape South Coast",
      "Vineyards around Hermanus ripen slowly because of the cold water in the bay below them. Which district covers them?",
      ["Walker Bay", "Cape Agulhas", "Elgin", "Overberg"], 0,
      "Cold water a few kilometres away holds the growing season long and the acidity high, which is why Pinot Noir and Chardonnay work there and Cabernet Sauvignon does not. Overberg and Cape Agulhas are genuine neighbouring districts in the same region."),
    Q("The Cape South Coast",
      "Clay-rich soils weathered from a rock quite unlike the Swartland's shale give the Hemel-en-Aarde its ability to hold water through a dry summer. Which rock?",
      ["Bokkeveld shale", "Malmesbury shale",
       "Table Mountain Sandstone", "Cape granite"], 0,
      "Bokkeveld shale weathers to heavy clay, and clay is what lets an unirrigated vine on a warm slope reach harvest in balance. It is much younger than the Malmesbury shale of the Swartland and behaves very differently in the vineyard."),
    Q("The Cape South Coast",
      "Apple and pear orchards covered a high plateau east of Cape Town long before any vines arrived, and the district is now among the coolest in the country. Which district?",
      ["Elgin", "Robertson", "Tulbagh", "Wellington"], 0,
      "The plateau sits a few hundred metres up, ringed by mountains and open to sea air through a gap, and the rainfall is high. Sauvignon Blanc, Chardonnay, Pinot Noir and Riesling all ripen late there, and the orchards are still the dominant crop."),
    Q("The Cape South Coast",
      "The southernmost vineyards on the African continent stand on a windswept plain near an old mission village, and their Sauvignon Blanc is severe, saline and low-yielding. Which ward?",
      ["Elim", "Elgin", "Bot River", "Groenekloof"], 0,
      "The ward lies in the Cape Agulhas district with the sea on three sides and almost nothing to break the wind. Crops are tiny because of it, and the wines are correspondingly concentrated and taut."),
    Q("The Cape South Coast",
      "Elgin and Walker Bay both lie within sight of the sea, yet neither of them belongs to the Coastal Region. Which region holds them?",
      ["Cape South Coast", "Breede River Valley", "Klein Karoo", "Boberg"], 0,
      "Coastal Region is a name inherited from an older scheme rather than a description of where the districts are, and it covers Stellenbosch, Paarl, Swartland and their neighbours further north. Cape Agulhas, Overberg and Plettenberg Bay sit alongside Elgin and Walker Bay in the southern region."),

    # ---------------------------- Breede River and the Klein Karoo (5) -------
    Q("Breede River and the Klein Karoo",
      "Lime-rich soils are scarce in the Cape and ordinary in one inland district, which used them to breed racehorses long before it used them for Chardonnay. Which district?",
      ["Robertson", "Worcester", "Tulbagh", "Paarl"], 0,
      "Limestone in the ground meant strong bone in the stock, and the same soils now underpin the district's Chardonnay and a great deal of its sparkling wine. Days are hot, but a south-easterly funnels up the valley most afternoons and takes the edge off."),
    Q("Breede River and the Klein Karoo",
      "Mountains wring the rain out of the westerly weather before it reaches one inland valley, so the vineyards there are irrigated from the river running through them. Which region?",
      ["Breede River Valley", "Olifants River", "Coastal Region", "Cape South Coast"], 0,
      "Worcester, Breedekloof and Robertson are its districts, and between them they grow an enormous share of the national crop. Much of it goes to distillation or to everyday blends, but the cooler margins and the older Chenin blocks have changed how the region is read."),
    Q("Breede River and the Klein Karoo",
      "Semi-desert country beyond the mountain passes grows Touriga Nacional and Tinta Barocca for the Cape's finest fortified reds. Which town sits at the centre of that trade?",
      ["Calitzdorp", "Oudtshoorn", "Montagu", "Barrydale"], 0,
      "The Klein Karoo is hot, dry and stony, which is close enough to the Douro that the Portuguese varieties behave as they should. The same district makes a great deal of fortified Muscadel, red and white, in a sweeter and simpler register."),
    Q("Breede River and the Klein Karoo",
      "A Cape fortified red left in cask until it turns amber and tastes of nuts and dried fruit is sold under which name?",
      ["Cape Tawny", "Cape Ruby", "Cape Vintage", "Cape Vintage Reserve"], 0,
      "The Cape prefix replaced a borrowed Portuguese term under an agreement with the European Union, and the family of names maps onto the styles it names. Cape Ruby is young and fruity, and Cape Vintage comes from a single year and does its ageing in the bottle rather than in wood."),
    Q("Breede River and the Klein Karoo",
      "A Cape grape name translates as cock's foot, after the splayed shape of the bunch. Which name is it?",
      ["Hanepoot", "Steen", "Groendruif", "Muscadel"], 0,
      "Hanepoot is Muscat of Alexandria, grown for the table, for raisins and for sweet fortified jerepigo. Muscadel is the Cape name for the other Muscat, the small-berried Muscat de Frontignan, fortified as both a red and a white around Robertson and the Klein Karoo."),

    # -------------------------------------- Pinotage and the Cape reds (4) ---
    Q("Pinotage and the Cape reds",
      "A cross made at Stellenbosch University in 1925 married a difficult Burgundian red to a hardy southern French workhorse. Which two grapes?",
      ["Pinot Noir and Cinsaut", "Pinot Noir and Grenache",
       "Pinot Noir and Carignan", "Cabernet Sauvignon and Cinsaut"], 0,
      "Abraham Perold was after Pinot's flavour with a constitution that could survive the Cape, and the name fuses Pinot with Hermitage, which is what the Cape then called Cinsaut. Nothing was bottled commercially from it until 1961, more than thirty years after the seedlings were planted."),
    Q("Pinotage and the Cape reds",
      "Two very different reds reach the shelf under the same Cape variety: one bright, red-fruited and savoury, the other dark and smelling strongly of mocha and chocolate. What produces the second?",
      ["Heavily charred oak, used deliberately in the cellar for effect",
       "A much cooler site giving a longer growing season",
       "Fermentation on the skins of a second red variety",
       "Arresting the fermentation with spirit while sugar remains"], 0,
      "The mocha style is a cellar decision rather than a vineyard one, built with strongly toasted barrels, staves or chips and often a little sweetness left in. It sells enormously well and it divides opinion, because it tastes more of the treatment than of the grape."),
    Q("Pinotage and the Cape reds",
      "A South African red blend earns an informal name of its own when it carries a meaningful share of one home-grown variety. Which variety?",
      ["Pinotage", "Cinsaut", "Cabernet Sauvignon", "Syrah"], 0,
      "There is no legal definition and producers argue about the proportion, but the presence of the Cape's own crossing is the point of the term. That is precisely what separates it from the other Cape blend, which is built on the red Bordeaux varieties and contains none of it."),
    Q("Pinotage and the Cape reds",
      "Cabernet Sauvignon, Merlot, Cabernet Franc and Petit Verdot grown at the Cape and bottled together are sold under a borrowed name. Which?",
      ["Cape Bordeaux blend", "Cape Blend", "Cape Vintage", "Cape Tawny"], 0,
      "Stellenbosch makes more of it than anywhere else, usually Cabernet-led and firmly structured. Keeping the two Cape blend terms apart is a standard trap: one names the red Bordeaux varieties, the other requires the local crossing."),

    # ----------------- Chenin Blanc, the whites and Cap Classique (5) --------
    Q("Chenin Blanc, the whites and Cap Classique",
      "Cape growers called their most widely planted white Steen for generations before anyone connected it to a French variety. Which grape is it?",
      ["Chenin Blanc", "Semillon", "Colombard", "Palomino"], 0,
      "The identification was made in the 1960s, by which point the grape had been planted for decades on the strength of its yield, its acidity and its usefulness for distillation. It is now the source of the Cape's most distinctive whites, bottled everywhere from fresh and unwooded to barrel-fermented and long-lived."),
    Q("Chenin Blanc, the whites and Cap Classique",
      "Bush vines planted in the 1960s crop a fraction of what a young trellised block does, and growers pay a premium for their fruit anyway. What do the old vines give?",
      ["Small, even crops of concentrated fruit",
       "Riper fruit at lower acidity and higher alcohol",
       "Natural resistance to phylloxera",
       "Larger berries with thinner skins"], 0,
      "An old vine has a deep root system and has stopped putting energy into growing, so it sets a modest crop and ripens it evenly without much intervention. The Old Vine Project certifies blocks of thirty-five years and older with a seal stating the year they were planted, which gives an old vineyard a documented value it never used to have."),
    Q("Chenin Blanc, the whites and Cap Classique",
      "A neutral, high-acid white planted across the hot irrigated interior is grown mostly to be distilled rather than drunk as wine. Which variety?",
      ["Colombard", "Chenin Blanc", "Sauvignon Blanc", "Hanepoot"], 0,
      "Acidity that survives real heat is exactly what a brandy base needs, and neutrality is a virtue when the still is going to supply the character. South African potstill brandy is a serious category, and the Breede River districts grow most of the wine that goes into it."),
    Q("Chenin Blanc, the whites and Cap Classique",
      "Cap Classique may be made anywhere in South Africa, from grapes Champagne would never permit. What does the term guarantee instead?",
      ["That the second fermentation happened in the bottle sold",
       "That the wine spent three years in a cellar before release",
       "That only Chardonnay and Pinot Noir went into it",
       "That the fruit came from a single registered ward"], 0,
      "The term names a method and says nothing about place or variety, which is the reverse of how Champagne is defined. A Cape sparkler made in a pressurised tank is a perfectly legal wine and simply may not use the name."),
    Q("Chenin Blanc, the whites and Cap Classique",
      "Chardonnay and Pinot Noir lead most Cap Classique, and one further grape turns up in it far more often at the Cape than it ever would in Champagne. Which?",
      ["Chenin Blanc", "Semillon", "Colombard", "Pinotage"], 0,
      "It holds high acidity at picking ripeness, which is the first thing a sparkling base needs, and there is a great deal of it in the ground. It appears at both ends of the market, in inexpensive bottles made largely from it and in serious ones where it is blended with the Champagne pair."),
]
