"""Rank I rewrite - South America (60 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

Scope is the continent's three established producers plus Brazil in brief:
Argentina from Salta down to Patagonia with Mendoza at the centre, Chile from
Elqui to Bio-Bio, Uruguay's Tannat, and the two Brazilian extremes. The
cross-cutting themes the assignment asks for - the Andes and altitude, the rain
shadow and irrigation, phylloxera status and label law - are carried through
every block rather than parked in one.

Stem openers are varied deliberately from the start, and each narrow factual
question is approached from an angle chosen at writing time rather than
reframed after a collision.
"""

from lib import Q

CAT = "South America"
SLUG = "r1-south-america"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Mendoza and its sub-regions", 9),
    ("Argentina beyond Mendoza", 7),
    ("Argentine grape varieties", 7),
    ("Chile: land and climate", 7),
    ("Chile's Central Valley", 8),
    ("Chile's coastal and southern valleys", 6),
    ("Chilean grape varieties", 7),
    ("Uruguay and Brazil", 5),
    ("Vineyard practice and label law", 4),
]

BANK = [
    # ---------------------------------- Mendoza and its sub-regions (9) ------
    Q("Mendoza and its sub-regions",
      "Westerly air off the Pacific dumps its moisture climbing the Andes and arrives on the far side wrung dry. What does that leave Mendoza?",
      ["A desert where no vineyard survives without irrigation",
       "A cool maritime climate with reliable summer rain",
       "A humid subtropical climate under constant rot pressure",
       "A monsoon pattern of heavy midsummer downpours"], 0,
      "Rainfall across most of the Mendoza vineyard runs to around two hundred millimetres a year. Sun and drought are the givens; water is the one thing that has to be engineered."),
    Q("Mendoza and its sub-regions",
      "Snowmelt reaches the vines along open channels that the Huarpe people began and the Spanish extended. What are those channels called?",
      ["Acequias", "Quebradas", "Parrales", "Bodegas"], 0,
      "The acequia network still governs who draws water and on which day. Rights to it are worth as much in Mendoza as the land they feed."),
    Q("Mendoza and its sub-regions",
      "Argentina's first delimited appellation was created in 1989 on the terraces above the Mendoza river and built around Malbec. Which zone earned it?",
      ["Lujan de Cuyo", "Tupungato", "Cafayate", "Rivadavia"], 0,
      "Lujan de Cuyo took the country's first DOC and San Rafael later became the second. Almost everything else on an Argentine label is registered as a geographical indication instead."),
    Q("Mendoza and its sub-regions",
      "Vineyards on stony alluvial fans between roughly nine hundred and fifteen hundred metres make up Mendoza's coolest and most fashionable sub-region. Which is it?",
      ["The Uco Valley", "Maipu", "Rivadavia", "San Rafael"], 0,
      "Tupungato, Tunuyan and San Carlos are its three departments. Height buys cold nights, so the wines hold an acidity that the warmer land nearer the city cannot."),
    Q("Mendoza and its sub-regions",
      "Chalky, limestone-rich pockets and tense, high-acid Malbec have made one district of Tupungato the most sought-after address in the Uco Valley. Which?",
      ["Gualtallary", "Agrelo", "Perdriel", "Vistalba"], 0,
      "Gualtallary sits high on the Andean side, where free-draining stones lie over calcareous material that is scarce elsewhere in Mendoza. The other three are Lujan de Cuyo districts, lower and warmer."),
    Q("Mendoza and its sub-regions",
      "Warm, low-lying land closest to Mendoza city holds many of the province's oldest Malbec and Bonarda vines. Which historic department is it?",
      ["Maipu", "Tupungato", "San Carlos", "Tunuyan"], 0,
      "Maipu was planted long before anyone thought of farming the high country, and its old vines give a rounder, softer style. The other three are Uco Valley departments."),
    Q("Mendoza and its sub-regions",
      "South of the main Mendoza belt, on the Diamante and Atuel rivers, sits the province's second controlled appellation. Which is it?",
      ["San Rafael", "Agrelo", "Cafayate", "Chilecito"], 0,
      "San Rafael lies lower, warmer and further from the Andes than the Uco Valley. It has a long history in volume production alongside its bottled wine."),
    Q("Mendoza and its sub-regions",
      "Whole estates in Mendoza are roofed over with netting stretched above the rows. Which threat does that answer?",
      ["Hail", "Phylloxera", "Downy mildew", "Spring frost"], 0,
      "A summer hailstorm can strip a vineyard in minutes and it recurs often enough that many growers treat netting as a cost of doing business rather than an option."),
    Q("Mendoza and its sub-regions",
      "A hot, dry wind falls off the Andes in late winter and spring, parching flowers and wrecking fruit set. What do Argentines call it?",
      ["The Zonda", "The Pampero", "The Mistral", "The Levante"], 0,
      "The Zonda is a foehn wind, warmed and dried by its own descent. The Pampero is its opposite number, a cold southwesterly sweeping up off the plains."),

    # ------------------------------------- Argentina beyond Mendoza (7) ------
    Q("Argentina beyond Mendoza",
      "Vines at seventeen hundred metres and higher, in a dry valley of red rock in the far north, belong to which province?",
      ["Salta", "Rio Negro", "Neuquen", "San Juan"], 0,
      "Salta farms some of the highest vineyards worked anywhere, with one estate above three thousand metres. Torrontes and a dense, savoury Malbec are its calling cards."),
    Q("Argentina beyond Mendoza",
      "Dry, sunny and roughly seventeen hundred metres up, Cafayate lies at the heart of which valley system?",
      ["The Calchaqui Valleys", "The Famatina Valley", "The Uco Valley",
       "The Alto Valle del Rio Negro"], 0,
      "The Calchaqui Valleys thread through Salta, Catamarca and Tucuman. Cafayate is their commercial centre and the source of most Argentine Torrontes with a reputation."),
    Q("Argentina beyond Mendoza",
      "Fruit grown above two thousand metres reaches the winery with unusually thick, dark skins. Which condition of altitude explains it?",
      ["Intense ultraviolet radiation, which the vine answers by thickening skins",
       "Higher average temperatures through the ripening period",
       "Much heavier rainfall on the upper slopes",
       "A far shorter interval between budbreak and harvest"], 0,
      "Thinner air filters less ultraviolet light, so the berry builds phenolics and colour as protection. The wide day-to-night swing at the same height is what keeps acidity in place."),
    Q("Argentina beyond Mendoza",
      "The Famatina Valley and a long cooperative tradition are the marks of which Argentine province?",
      ["La Rioja", "San Juan", "Catamarca", "Mendoza"], 0,
      "La Rioja lends its name to Torrontes Riojano, the best of the three Torrontes. An unusually large share of its crop passes through one very big cooperative."),
    Q("Argentina beyond Mendoza",
      "Hot, low country in the Tulum Valley supplies Syrah along with much of the base wine for Argentine vermouth and brandy. Which province is it?",
      ["San Juan", "Rio Negro", "Salta", "La Pampa"], 0,
      "San Juan lies immediately north of Mendoza and is both hotter and lower. Its more serious Syrah comes from the higher Pedernal and Calingasta valleys rather than the Tulum floor."),
    Q("Argentina beyond Mendoza",
      "Constant wind, very low humidity and a long cool season along an irrigated river valley describe Argentina's southern vineyards. Which region?",
      ["Rio Negro in Patagonia", "Cafayate in Salta", "Tulum in San Juan",
       "Chilecito in La Rioja"], 0,
      "The Alto Valle del Rio Negro was planted with fruit orchards before anyone planted vines. Wind thickens skins and holds disease down, and the latitude gives slow, even ripening."),
    Q("Argentina beyond Mendoza",
      "Desert scrub irrigated from a dammed river around San Patricio del Chanar carries Patagonia's newest large plantings. Which province?",
      ["Neuquen", "Chubut", "Cordoba", "Entre Rios"], 0,
      "Neuquen was built from bare ground in the late 1990s, unlike Rio Negro next door, where some vines are a century old. Malbec and Pinot Noir lead there."),

    # ------------------------------------ Argentine grape varieties (7) ------
    Q("Argentine grape varieties",
      "Cuttings brought from France in 1853 by an agronomist hired to modernise Mendoza's farming gave the country its emblem. Which red variety was it?",
      ["Malbec", "Tannat", "Bonarda", "Carmenere"], 0,
      "Michel Aime Pouget was engaged to run a new agricultural school and arrived with French vine material. Malbec reached Argentina before phylloxera had reshaped its French homeland."),
    Q("Argentine grape varieties",
      "Set beside Cahors, the Malbec grown in Mendoza differs as a plant in which way?",
      ["Smaller berries in tighter bunches", "Much larger berries in looser bunches",
       "Considerably later budbreak", "Markedly higher natural acidity"], 0,
      "A century and a half of selection in a dry, sunny place produced a distinct plant. More skin per unit of juice is part of why Argentine Malbec is plusher and darker than the French original."),
    Q("Argentine grape varieties",
      "DNA analysis showed Argentina's most aromatic white to be a natural cross of Criolla Chica with which other variety?",
      ["Muscat of Alexandria", "Riesling", "Chenin Blanc", "Pedro Ximenez"], 0,
      "Criolla Chica is the missionaries' vine, called Pais in Chile and Mission in California. The Muscat parent accounts for the flowery, grapey perfume of Torrontes."),
    Q("Argentine grape varieties",
      "A guest expects sweetness from a heady, rose-scented Argentine white and meets a dry, faintly bitter finish instead. Which variety was poured?",
      ["Torrontes", "Viognier", "Gewurztraminer", "Moscatel"], 0,
      "Perfume and sugar are separate things, and this is the standing proof. The grip on the finish is characteristic and makes the wine a better match for spiced food than its nose suggests."),
    Q("Argentine grape varieties",
      "A red planted second only to Malbec in Argentina carries an Italian name, yet DNA matched it to Savoie's Douce Noire. Which is it?",
      ["Bonarda", "Barbera", "Sangiovese", "Nebbiolo"], 0,
      "The same vine is called Charbono in California. Argentine Bonarda ripens late and gives juicy dark fruit with soft tannin, and it is only now being taken seriously."),
    Q("Argentine grape varieties",
      "Pink-skinned varieties still cover a wide stretch of Argentine vineyard and supply inexpensive wine for the home market. Which pair are they?",
      ["Criolla Grande and Cereza", "Bonarda and Barbera", "Torrontes and Viognier",
       "Malbec and Syrah"], 0,
      "Both descend from the vines the Spanish brought and both crop heavily. Their acreage has fallen steadily as growers replant to Malbec for export."),
    Q("Argentine grape varieties",
      "Century-old plantings of a Bordeaux white survive on the Rio Negro valley floor, a legacy of the settlers who first irrigated it. Which variety?",
      ["Semillon", "Sauvignon Blanc", "Muscadelle", "Colombard"], 0,
      "Patagonian Semillon is lean and long lived, nothing like the broad versions the grape gives in warmer places. Old Merlot and Pinot Noir survive alongside it."),

    # --------------------------------------- Chile: land and climate (7) -----
    Q("Chile: land and climate",
      "Between the coastal range and the Andes runs a long structural depression that lends its name to the heart of Chilean viticulture. What is that name?",
      ["The Central Valley", "The Aconcagua Valley", "The Secano Interior",
       "The Southern Regions"], 0,
      "In Chilean law the Valle Central covers Maipo, Rapel, Curico and Maule. Casablanca and Aconcagua sit outside it, in the Aconcagua region further north."),
    Q("Chile: land and climate",
      "A cold ocean current running north along the shore drags fog inland each morning and keeps Chilean coastal vineyards far cooler than their latitude suggests. Which current?",
      ["The Humboldt Current", "The Benguela Current", "The Gulf Stream",
       "The Canary Current"], 0,
      "It carries Antarctic water up the western seaboard and is the single largest cooling influence on Chilean wine. Without it these latitudes would be far too warm for Sauvignon Blanc or Pinot Noir."),
    Q("Chile: land and climate",
      "Dense sea fog that rolls into the far northern valleys at dawn carries a local name. Which?",
      ["The camanchaca", "The Sudestada", "The Puelche", "The Pampero"], 0,
      "In Limari and Elqui the camanchaca is what makes viticulture possible so near the Atacama. It burns off by mid-morning and leaves a fiercely sunny afternoon behind it."),
    Q("Chile: land and climate",
      "Rainfall across Chile's wine country changes steadily along the length of the country. In which direction does it increase?",
      ["From north to south", "From south to north",
       "It changes very little from one end to the other",
       "It peaks in the middle and falls away at both ends"], 0,
      "The north shades into the Atacama desert and the far south is genuinely wet. That gradient is why irrigation is compulsory in Limari and optional or unnecessary in Itata."),
    Q("Chile: land and climate",
      "Chilean labels may add Costa, Entre Cordilleras or Andes beside the valley name. What do those three words tell a buyer?",
      ["Where the vineyard sits between the ocean and the mountains",
       "How long the wine spent in oak", "The age of the vines",
       "The sweetness of the finished wine"], 0,
      "Introduced in 2011, they cut across the north-south valley names, which had lumped cool coastal fruit in with warm inland fruit. Costa is the maritime side, Andes the mountain side, Entre Cordilleras the ground between."),
    Q("Chile: land and climate",
      "Almost every Chilean vine grows on its own roots rather than on grafted rootstock. Which fact allows it?",
      ["Phylloxera has never established itself in the country",
       "Chilean law forbids the import of rootstock",
       "Chilean vines are hybrids the louse cannot feed on",
       "Drip irrigation drowns the louse in the root zone"], 0,
      "Desert to the north, ocean to the west, the Andes to the east and cold to the south have kept the pest out. Ungrafted vines are the ordinary case here and a rarity almost everywhere else."),
    Q("Chile: land and climate",
      "Vineyards in Chile's northern and central valleys cannot carry a crop on growing-season rainfall alone. What waters them?",
      ["River water fed by Andean snowmelt", "Desalinated seawater piped from the coast",
       "Summer monsoon rain", "Artesian springs in the coastal range"], 0,
      "A Mediterranean climate puts its rain in winter, so the vine is driest exactly when it is growing. Meltwater arrives in the rivers as the season warms, which is convenient timing."),

    # ---------------------------------------- Chile's Central Valley (8) -----
    Q("Chile's Central Valley",
      "Gravel terraces on the upper reaches of a river immediately south of Santiago produce Chile's most celebrated Cabernet Sauvignon. Which valley?",
      ["Maipo", "Casablanca", "Limari", "Bio-Bio"], 0,
      "Maipo Cabernet is often marked by a minty, eucalyptus lift over blackcurrant fruit. The valley runs from the Andes nearly to the sea, and the Andean end is the serious part."),
    Q("Chile's Central Valley",
      "The flagship Cabernets of Alto Maipo come overwhelmingly from one commune on stony ground beside the river. Which?",
      ["Puente Alto", "Peumo", "Marchigue", "Lontue"], 0,
      "Puente Alto and neighbouring Pirque sit high on the Maipo's alluvial gravels, close enough to the Andes to catch cold night air draining off the mountains."),
    Q("Chile's Central Valley",
      "Wine blended from Cachapoal and Colchagua may be sold under which single umbrella denomination?",
      ["Rapel", "Curico", "Maule", "Aconcagua"], 0,
      "Rapel is the parent name for both. Cachapoal lies to the north and Colchagua to the south, separated by a low range of hills."),
    Q("Chile's Central Valley",
      "Warm, clay-rich ground in Cachapoal has become the reference address for Chile's signature red. Which sector is it?",
      ["Peumo", "Pirque", "Requinoa", "Isla de Maipo"], 0,
      "Peumo gives Carmenere the heat and the long season the variety demands. Picked too soon it turns hard and green, so the site has to buy the grower time."),
    Q("Chile's Central Valley",
      "A horseshoe of granitic hillside in Colchagua, curled around a river bend and planted to Syrah, Carmenere and Cabernet, is known as what?",
      ["Apalta", "Los Lingues", "Lolol", "Chimbarongo"], 0,
      "Apalta's slopes give poorer, better-drained soil than the valley floor and a natural amphitheatre of exposures. It is the single most quoted name in Colchagua."),
    Q("Chile's Central Valley",
      "A Catalan producer arrived in 1979 with stainless steel and temperature control, and the date is often taken as the start of the modern Chilean industry. Where did he settle?",
      ["Curico", "Maipo", "Casablanca", "Elqui"], 0,
      "Miguel Torres set up in Curico and Chilean whites in particular were transformed inside a decade. Curico's Lontue and Teno sub-valleys remain a large source of everyday wine."),
    Q("Chile's Central Valley",
      "Dry-farmed bush vines planted after the earthquake of 1939 underpin a growers' association in Maule. Which variety do they champion?",
      ["Carignan", "Pais", "Cinsault", "Malbec"], 0,
      "Carignan was brought in to add colour and acid to Pais after the quake wrecked the region's cellars. VIGNO now bottles it from old unirrigated vines and has made Maule a serious name again."),
    Q("Chile's Central Valley",
      "Running from north to south, which order correctly places the four sub-regions of Chile's Central Valley?",
      ["Maipo, Rapel, Curico, Maule", "Maule, Curico, Rapel, Maipo",
       "Rapel, Maipo, Maule, Curico", "Curico, Maule, Maipo, Rapel"], 0,
      "Santiago sits at the northern end beside Maipo, and Maule marks the southern boundary of the Central Valley proper. Everything below it belongs to the Southern Regions."),

    # -------------------------- Chile's coastal and southern valleys (6) -----
    Q("Chile's coastal and southern valleys",
      "Morning fog, cold nights and a real risk of spring frost make one valley between Santiago and the sea Chile's white wine pioneer. Which?",
      ["Casablanca", "Colchagua", "Curico", "Cachapoal"], 0,
      "Planted from the early 1980s on ground nobody had thought suitable for vines, Casablanca proved Chile could make cool-climate Sauvignon Blanc and Chardonnay. Frost is the price of the cold air that pools there."),
    Q("Chile's coastal and southern valleys",
      "Planting the Leyda Valley became viable only once water was piped several kilometres from a neighbouring river. Which obstacle did that remove?",
      ["There was too little rainfall to establish vines without irrigation",
       "The soils were too saline until they had been flushed",
       "Frost could not be fought without sprinkler water",
       "The slopes were too steep to work without terracing"], 0,
      "San Antonio and its Leyda sub-valley lie a few kilometres from the Pacific, which supplies the cold and the wind but not the water. The pipeline opened one of Chile's best sites for Sauvignon Blanc and Pinot Noir."),
    Q("Chile's coastal and southern valleys",
      "Calcareous soils, near-desert rainfall and ocean fog have made one far northern valley Chile's source of taut Chardonnay and cool-climate Syrah. Which?",
      ["Limari", "Maule", "Colchagua", "Itata"], 0,
      "Limestone is scarce in Chilean vineyards and Limari has it. The valley opens straight to the sea, so the camanchaca reaches a long way inland."),
    Q("Chile's coastal and southern valleys",
      "Chile's northernmost vineyards share their valleys with the stills that make the national spirit. Which spirit is that?",
      ["Pisco", "Cachaca", "Singani", "Grappa"], 0,
      "Elqui is pisco country, distilled largely from Muscat varieties, and its wine vineyards climb high above the valley floor. Cachaca is Brazilian and Singani Bolivian."),
    Q("Chile's coastal and southern valleys",
      "A warm east-west valley named for the highest peak in the Americas built its reputation on Cabernet and Syrah grown at Panquehue. Which valley?",
      ["Aconcagua", "Rapel", "Maule", "San Antonio"], 0,
      "The Aconcagua valley runs inland from the coast north of Santiago and is one of Chile's warmest quality zones. Its cool coastal sector, Aconcagua Costa, is a far more recent development."),
    Q("Chile's coastal and southern valleys",
      "Ungrafted bush vines of Pais, some of them centuries old, alongside old dry-farmed Cinsault, are concentrated in which southern zone?",
      ["Itata", "Maipo", "Aconcagua", "Casablanca"], 0,
      "Itata holds Chile's oldest vineyards, farmed on the dry hills of the secano interior. Bio-Bio and Malleco further south are cool and wet enough for Riesling, Chardonnay and Pinot Noir."),

    # -------------------------------------- Chilean grape varieties (7) -----
    Q("Chilean grape varieties",
      "Much of what Chile exported as Merlot before 1994 turned out to be a different Bordeaux variety. Which one?",
      ["Carmenere", "Malbec", "Cabernet Franc", "Petit Verdot"], 0,
      "Carmenere had been interplanted with Merlot for a century and nobody had pulled the two apart. Chile now grows more of it than anywhere else and treats it as a national signature."),
    Q("Chilean grape varieties",
      "Which discipline, working from the shape of leaves and shoots in the vineyard, first showed that Chile's Merlot was not all Merlot?",
      ["Ampelography", "Oenology", "Pedology", "Phenology"], 0,
      "The French ampelographer Jean-Michel Boursiquot made the call in 1994 and DNA work confirmed it. Pedology is the study of soils and phenology the timing of the vine's growth stages."),
    Q("Chilean grape varieties",
      "Picked on the same day as the Merlot beside it, Carmenere shows a hard green capsicum note. What is the cause?",
      ["Pyrazines that fall away only after several more weeks of ripening",
       "Too much new oak", "Malolactic conversion", "Residual sugar left in the wine"], 0,
      "Carmenere ripens very late, often into May in Chile, and the whole art of it is holding your nerve. Underripe fruit gives the green streak the variety was once notorious for."),
    Q("Chilean grape varieties",
      "Spanish missionaries carried a black variety through the Americas in the sixteenth century, and in Chile it still fills jugs of country wine. What is it called there?",
      ["Pais", "Carignan", "Cinsault", "Bonarda"], 0,
      "The same vine is Mission in California, Criolla Chica in Argentina and Listan Prieto in Spain. Old dry-farmed Pais is now bottled seriously, often by carbonic maceration."),
    Q("Chilean grape varieties",
      "Export markets in the 1980s and 1990s wanted a name they already knew, and one variety duly overtook Pais as Chile's most planted vine. Which?",
      ["Cabernet Sauvignon", "Merlot", "Chardonnay", "Syrah"], 0,
      "Cabernet Sauvignon is the backbone of the Chilean trade, from everyday bottlings up to the icons of Alto Maipo. Pais retreated to the old dry-farmed hills of the south."),
    Q("Chilean grape varieties",
      "Older Chilean plantings sold as Sauvignon Blanc were found to include a duller, far less aromatic variety. Which?",
      ["Sauvignonasse", "Semillon", "Verdejo", "Chenin Blanc"], 0,
      "Sauvignonasse is Friulano, and it gives a broad, mild wine with none of the pungency. Replanting with true Sauvignon Blanc is much of why Chilean whites improved so sharply."),
    Q("Chilean grape varieties",
      "Peppery, tightly wound reds from Chile's cool coastal and far northern sites have made the case for which variety?",
      ["Syrah", "Carmenere", "Pais", "Merlot"], 0,
      "Syrah from Limari, Elqui and Aconcagua Costa tastes closer to the northern Rhone than to Australia. Carmenere would never finish ripening in any of those places."),

    # ------------------------------------------- Uruguay and Brazil (5) -----
    Q("Uruguay and Brazil",
      "A Basque immigrant planted a south-west French red near Salto in the 1870s, and Uruguayans called the vine by his name for a century afterwards. Which variety?",
      ["Tannat", "Malbec", "Carmenere", "Bonarda"], 0,
      "Pascual Harriague gave his name to the vine, and Tannat is now Uruguay's flagship. It arrives riper and rounder here than in Madiran, its French home."),
    Q("Uruguay and Brazil",
      "Most Uruguayan vineyards sit in one department just north of the capital, on clay and limestone near the Rio de la Plata. Which?",
      ["Canelones", "Maldonado", "Rivera", "Colonia"], 0,
      "Canelones surrounds Montevideo and holds the bulk of the country's planting. Maldonado on the Atlantic coast and Rivera on the Brazilian border are the ambitious newer areas."),
    Q("Uruguay and Brazil",
      "Humid air off the Atlantic and the Rio de la Plata sets Uruguay's central viticultural problem. What is it?",
      ["Fungal disease and rot pressure through the growing season",
       "Drought severe enough to require irrigation everywhere",
       "Winter cold that kills vines outright",
       "Too little heat to ripen any red variety"], 0,
      "Canopy management and disciplined spraying matter more here than anywhere else on the continent. Tannat's thick skins are part of why it copes, though its compact bunches still demand careful canopy work and spray penetration."),
    Q("Uruguay and Brazil",
      "Italian immigrant families settled a humid, hilly zone in Rio Grande do Sul, and its growers have found their strongest suit in one style. Which?",
      ["Sparkling wine", "Fortified wine", "Late-harvest sweet wine",
       "Oak-aged Cabernet Sauvignon"], 0,
      "Serra Gaucha takes rain right through the growing season, which suits a lean sparkling base far better than it suits ripe red wine. Vale dos Vinhedos within it was the first Brazilian area granted a geographical indication."),
    Q("Uruguay and Brazil",
      "Vines planted near the ninth parallel south never go properly dormant, so growers there can take more than one crop a year. Which Brazilian region?",
      ["Vale do Sao Francisco", "Serra Gaucha", "Campanha", "Santa Catarina"], 0,
      "Irrigation from the Sao Francisco river lets the grower decide when to prune and therefore when to pick. It is one of very few places on earth where a vineyard runs on a tropical rather than a seasonal calendar."),

    # ------------------------------- Vineyard practice and label law (4) -----
    Q("Vineyard practice and label law",
      "A Chilean label naming a variety, a vintage and a valley must draw at least what proportion of the wine from each?",
      ["Seventy-five percent", "Fifty-one percent", "Sixty percent", "One hundred percent"], 0,
      "Seventy-five percent is the domestic minimum, while wine bound for the European Union has to meet a stricter eighty-five. Most producers work comfortably above either figure."),
    Q("Vineyard practice and label law",
      "Overhead canopies of wire on high posts, with the fruit hanging in shade beneath, are the traditional Argentine training system. What is it called?",
      ["Parral", "Guyot", "Gobelet", "Lyre"], 0,
      "Parral suits table grapes and high-yielding Criolla, and it shelters fruit from a fierce sun. Quality plantings have largely moved to vertical trellising for better exposure and airflow."),
    Q("Vineyard practice and label law",
      "Argentina has phylloxera in its soils, yet most of its vines are still ungrafted. Which explanation is the accepted one?",
      ["Sandy soils and flood irrigation keep the insect's damage in check",
       "The Andes stop the insect from crossing into the country",
       "Argentine vines are American hybrids the insect cannot feed on",
       "Winter cold kills the insect off every year"], 0,
      "Phylloxera struggles in sand and fares badly under periodic flooding, and both are ordinary conditions in Mendoza. Chile's position is different again, since the pest never arrived there at all."),
    Q("Vineyard practice and label law",
      "Flood channels fed the rows for generations, but newer high-altitude plantings in the Uco Valley mostly use what instead?",
      ["Drip irrigation", "Overhead sprinklers", "No irrigation at all",
       "Furrow flooding twice each season"], 0,
      "Drip gives precise control over how much water each vine receives and when, which is the main lever on vigour in a desert. It also works on stony slopes where a flood channel could never be run level."),
]
