"""Rank I rewrite - Spain (59 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

Sherry appears here as part of Spain rather than as a fortified-wine topic, so
the angles are chosen to complement the parallel sparkling and fortified
category rather than to repeat it: the dryness of Oloroso, Palo Cortado, the
headspace a butt is left, which row the saca comes from, the age statements and
what an opened Fino does on the bar.

Every stem leads with a symptom, a scenario or an observation and lets the
subject fall out as the answer, and no two share their opening three words.
"""

from lib import Q

CAT = "Spain"
SLUG = "r1-spain"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("The appellation hierarchy", 6),
    ("Grape varieties", 7),
    ("Rioja", 8),
    ("The ageing ladder", 6),
    ("Ribera del Duero and Toro", 5),
    ("Catalunya and Priorat", 5),
    ("Cava", 5),
    ("Galicia and the Atlantic north", 5),
    ("Rueda, Navarra, Bierzo and La Mancha", 5),
    ("Jerez and the Sherry styles", 7),
]

BANK = [
    # ------------------------------------------ the appellation hierarchy (6) -
    Q("The appellation hierarchy",
      "Two Spanish regions alone hold the country's top appellation tier. Rioja is one; which is the other?",
      ["Priorat", "Ribera del Duero", "Rueda", "Jerez"], 0,
      "Rioja was raised to Denominacion de Origen Calificada in 1991 and Priorat followed, printing the Catalan form DOQ on its labels. The tier demands a long record as an ordinary DO before it can even be applied for."),
    Q("The appellation hierarchy",
      "A single estate can carry its own denomination in Spain, ranked above the DO that surrounds it. What is that category called?",
      ["Vino de Pago", "Vino de la Tierra", "Vino de Calidad con Indicacion Geografica",
       "Vino de Mesa"], 0,
      "A Vino de Pago recognises one property with a distinct terroir, and the estate must grow and vinify its own fruit. Dominio de Valdepusa in Toledo was the first to be granted it."),
    Q("The appellation hierarchy",
      "A region must normally spend years at an intermediate quality level before it may apply for full DO status. Which level is that?",
      ["Vino de Calidad con Indicacion Geografica", "Vino de la Tierra", "Vino de Pago",
       "Vino de Mesa"], 0,
      "Five years as a Vino de Calidad before applying for DO, then ten years as a DO before applying for the tier above. The ladder is deliberately slow, so a name has to be earned across decades."),
    Q("The appellation hierarchy",
      "Which term on a Spanish label matches what the rest of Europe calls a protected geographical indication?",
      ["Vino de la Tierra", "Denominacion de Origen", "Vino de Pago", "Vino de Mesa"], 0,
      "Vino de la Tierra covers a wide zone with looser rules on grapes and yields. It is often where an ambitious estate goes when it wants to plant something the local DO forbids."),
    Q("The appellation hierarchy",
      "A small numbered seal on the back of a Spanish bottle states its ageing class and vouches for its origin. Who issues it?",
      ["The denomination's Consejo Regulador", "The bodega that made the wine",
       "The exporter handling the shipment", "The regional government's tax office"], 0,
      "Every denomination has a Consejo Regulador that writes its rules, inspects its members and numbers each back label. That is why a Spanish ageing term is a checkable claim rather than a marketing word."),
    Q("The appellation hierarchy",
      "Ordering the Spanish quality ladder from the loosest rules to the strictest, which sequence is right?",
      ["Vino, Vino de la Tierra, DO, DOCa", "Vino de la Tierra, Vino, DOCa, DO",
       "DO, DOCa, Vino, Vino de la Tierra", "Vino, DOCa, Vino de la Tierra, DO"], 0,
      "Each step tightens the permitted grapes, the maximum yields, the ageing minimums and the boundary itself. Vino de Pago sits outside the sequence, since it applies to one estate rather than to a region."),

    # ------------------------------------------------------ grape varieties (7)
    Q("Grape varieties",
      "An early-ripening black grape with thick skins and modest acidity became the most widely planted red variety in Spain. Which one?",
      ["Tempranillo", "Garnacha", "Monastrell", "Graciano"], 0,
      "The name comes from temprano, meaning early. Ripening weeks ahead of Garnacha is what lets it succeed at altitude in Ribera del Duero, where autumn arrives without warning."),
    Q("Grape varieties",
      "Tinta del Pais, Cencibel and Ull de Llebre all name one variety. Which?",
      ["Tempranillo", "Garnacha", "Mencia", "Monastrell"], 0,
      "The vine travelled around Spain long before anyone catalogued it, so nearly every region gave it a local name. Tinta de Toro belongs on the same list, as does Portugal's Tinta Roriz."),
    Q("Grape varieties",
      "Old bush vines on Priorat slate and the dry pink wines of Navarra both rest on which variety?",
      ["Garnacha", "Tempranillo", "Graciano", "Bobal"], 0,
      "Garnacha oxidises easily and can look pale, yet from low-yielding old vines it gives real depth and perfume. Spain, most probably Aragon, is where it came from."),
    Q("Grape varieties",
      "A very late-ripening variety that needs real heat to finish gives Jumilla and Yecla their dark, tannic reds. Which is it, and what is it called in France?",
      ["Monastrell, called Mourvedre in France", "Mazuelo, called Carignan in France",
       "Garnacha Tintorera, called Alicante Bouschet in France",
       "Graciano, called Morrastel in France"], 0,
      "Monastrell buds late and ripens very late, so it belongs in the hot southeast. It gives high tannin and dark fruit, and turns meaty and gamey with age."),
    Q("Grape varieties",
      "Thick skins and searing acidity let one white variety thrive on a rainy Atlantic coast where rot is the constant threat. Which is it?",
      ["Albarino", "Verdejo", "Viura", "Godello"], 0,
      "Albarino carries the damp of Rias Baixas because its berries are small and its skins tough. Across the Mino in Portugal the same vine is called Alvarinho."),
    Q("Grape varieties",
      "A white grape that browns easily in the press house is picked at night under inert gas and finishes with a bitter almond twist. Which one?",
      ["Verdejo", "Albarino", "Palomino", "Macabeo"], 0,
      "Verdejo oxidises readily, so the modern Rueda style depends on night harvesting and protective handling. That faintly bitter, fennel-like finish is its signature."),
    Q("Grape varieties",
      "Bodegas in Jerez want a base wine that contributes almost nothing of its own before ageing begins. Which grape gives them that?",
      ["Palomino", "Pedro Ximenez", "Moscatel", "Airen"], 0,
      "Palomino is low in acid, low in aroma and generous in yield. A dry Sherry takes its character from flor, oxygen and wood rather than from fruit, so neutrality is an asset here."),

    # ---------------------------------------------------------------- rioja (8)
    Q("Rioja",
      "Three zones divide the Rioja denomination. Which of them lies in the Basque province of Alava?",
      ["Rioja Alavesa", "Rioja Alta", "Rioja Oriental", "Rioja Media"], 0,
      "Alavesa is the smallest of the three, on chalky clay under the Sierra de Cantabria. Its villages are also the traditional home of the whole-bunch carbonic style drunk within the year."),
    Q("Rioja",
      "Garnacha ripens most reliably in the warmest, lowest and driest part of Rioja. Which zone is that?",
      ["Rioja Oriental", "Rioja Alta", "Rioja Alavesa",
       "The Najerilla valley"], 0,
      "The eastern end lies lower and hotter, with a Mediterranean edge to the climate, and it grows most of the region's Garnacha. It was called Rioja Baja until 2018, an old name that described altitude and not quality."),
    Q("Rioja",
      "A limestone ridge along Rioja's northern edge blocks the worst of the Atlantic weather. What is it called?",
      ["The Sierra de Cantabria", "The Picos de Europa", "The Sierra de Gredos",
       "The Montes de Toledo"], 0,
      "Without that wall the region would be as wet as the Basque coast an hour away. The shelter is what lets Rioja ripen at all at five hundred metres and more."),
    Q("Rioja",
      "Merchants fleeing a ruined Bordeaux in the nineteenth century brought barrel ageing south to Rioja. What had driven them out?",
      ["The phylloxera epidemic", "A collapse in the price of claret",
       "The Napoleonic wars", "A French ban on wine exports"], 0,
      "The louse ruined the French vineyard from the 1860s and reached Rioja only in 1899, some three decades later, and in that gap Rioja learned to age in 225-litre barricas. The habit long outlasted the crisis."),
    Q("Rioja",
      "A traditional Rioja Gran Reserva smells of coconut, vanilla and dill. Which cellar practice accounts for that?",
      ["Long ageing in barrels of American oak", "A month of maceration on the skins",
       "Ageing under a film of flor", "Blending in a share of Moscatel"], 0,
      "American oak is far higher in the lactone that reads as coconut and dill, and Rioja's classic houses have used it for well over a century. French oak gives a tighter, more toasted register."),
    Q("Rioja",
      "A blender wants floral lift and firm acidity to rescue a soft, broad Tempranillo. Which Rioja variety is reached for?",
      ["Graciano", "Garnacha", "Viura", "Monastrell"], 0,
      "Graciano yields little and is awkward to grow, which is why it nearly disappeared, but a few percent transforms a blend with violet aromatics and bite."),
    Q("Rioja",
      "One variety supplies both the backbone of white Rioja and a third of the classic Cava blend. Which is it?",
      ["Viura, known in Catalonia as Macabeo", "Malvasia, known in Catalonia as Parellada",
       "Garnacha Blanca, known in Catalonia as Xarel-lo",
       "Verdejo, known in Catalonia as Subirat Parent"], 0,
      "Viura and Macabeo are one grape under two names. It is neutral and high in acid, which suits both a barrel-aged white Rioja and a bottle of sparkling wine."),
    Q("Rioja",
      "A cluster of nineteenth-century bodegas still stands around one railway station in Rioja Alta. Which town?",
      ["Haro", "Logrono", "Laguardia", "Calahorra"], 0,
      "The Barrio de la Estacion grew up around the rail link that carried wine to France, and several of Rioja's oldest houses sit within a few hundred metres of each other."),

    # ----------------------------------------------------- the ageing ladder (6)
    Q("The ageing ladder",
      "Which of these is the minimum time a red Rioja Crianza must spend in cask?",
      ["Twelve months", "Six months", "Twenty-four months", "Three months"], 0,
      "Twelve months in oak within twenty-four months of total ageing. Spain's national floor for Crianza is only six months in wood, so a Rioja Crianza is a stricter wine than the word promises elsewhere."),
    Q("The ageing ladder",
      "Five years of ageing, at least two in cask and three more in bottle, earn a red Rioja which designation?",
      ["Gran Reserva", "Reserva", "Crianza", "Joven"], 0,
      "Most houses declare it only in vintages they believe will repay the wait. The long spell in bottle is why a Gran Reserva often reaches the table already mature."),
    Q("The ageing ladder",
      "What limits the size of the casks that may count toward Spain's ageing terms?",
      ["A ceiling of 330 litres", "A ceiling of 600 litres", "They must hold exactly 225 litres",
       "Nothing, only the species of wood is fixed"], 0,
      "A large cask gives far less oxygen and extract per litre of wine, so ageing in one would not deliver what the term promises. The 225-litre barrica remains the working standard."),
    Q("The ageing ladder",
      "A sommelier says Spain's ageing terms are unusual in European wine law. What makes them so?",
      ["Cask and bottle minimums are set nationally in law",
       "A tasting panel awards each wine a quality score",
       "They may be used only in Rioja and Ribera del Duero",
       "They name the grape varieties the wine may contain"], 0,
      "Elsewhere the term is defined appellation by appellation, if at all. Spain fixes one set of cask and bottle minimums nationally, which many denominations then tighten and the Consejo checks, so the words compare across bodegas."),
    Q("The ageing ladder",
      "Ordering Rioja's red ageing classes by the total time each demands, which sequence is correct?",
      ["Joven, Crianza, Reserva, Gran Reserva", "Crianza, Joven, Reserva, Gran Reserva",
       "Joven, Reserva, Crianza, Gran Reserva", "Crianza, Reserva, Gran Reserva, Joven"], 0,
      "Nothing required, then two years, then three, then five. The ladder measures elapsed time and nothing else, so a superb young wine from a great site still sits at the bottom of it."),
    Q("The ageing ladder",
      "Beyond its time in cask, a red Rioja Reserva must also rest in bottle before release. What is that minimum?",
      ["Six months", "Two years", "One month", "There is no bottle requirement"], 0,
      "Three years in total, of which at least twelve months in cask and at least six in bottle. The bottle rule is what stops a wine going straight from barrel to shelf."),

    # --------------------------------------------- ribera del duero and toro (5)
    Q("Ribera del Duero and Toro",
      "Frost can strike in late May and again in September on the high plateau around Aranda de Duero. Which denomination farms it?",
      ["Ribera del Duero", "Toro", "Cigales", "Rueda"], 0,
      "Vineyards run from roughly 750 to 900 metres, so nights stay cold and the season is short. That gap between day heat and night cold is what holds colour and acidity in Tinto Fino."),
    Q("Ribera del Duero and Toro",
      "Downstream from Ribera del Duero the valley turns hotter and drier and the reds grow heavier. Which denomination sits there?",
      ["Toro", "Cigales", "Rueda", "Bierzo"], 0,
      "Toro lies in Zamora province, where Tempranillo is called Tinta de Toro and gives dense, high-alcohol wine. Sandy soils there let some ungrafted old vines survive phylloxera."),
    Q("Ribera del Duero and Toro",
      "One Castilian estate was making a Bordeaux-influenced red for over a century before any denomination existed around it. Which estate?",
      ["Vega Sicilia", "Marques de Riscal", "Lopez de Heredia", "Bodegas Torres"], 0,
      "Founded in the 1860s and famous for Unico, it blends Tinto Fino with Cabernet Sauvignon and other Bordeaux varieties. Ribera del Duero itself was granted DO status only in 1982."),
    Q("Ribera del Duero and Toro",
      "The river behind these Castilian denominations changes its name at the Portuguese border. What does it become?",
      ["The Douro", "The Tejo", "The Minho", "The Mondego"], 0,
      "Duero and Douro are one river. It runs west past Ribera del Duero, Rueda and Toro before cutting the schist gorges where Port is grown."),
    Q("Ribera del Duero and Toro",
      "A Ribera del Duero red is usually darker and firmer in tannin than a Rioja of the same age. Which factor explains most of that?",
      ["The altitude, and the wide swing from day heat to night cold",
       "A large share of Garnacha in the blend",
       "A longer minimum cask ageing set by the denomination",
       "A prohibition on American oak"], 0,
      "Cold nights near 800 metres slow the loss of acid and thicken the skins, so the fruit arrives with more colour and tannin. Rioja's lower, more Atlantic sites give a lighter frame."),

    # ------------------------------------------------- catalunya and priorat (5)
    Q("Catalunya and Priorat",
      "Vines dig through crumbling black slate on terraces around a ruined Carthusian priory. Which denomination is this?",
      ["Priorat", "Montsant", "Penedes", "Terra Alta"], 0,
      "The soil is called llicorella and the priory is Scala Dei, which gave the region its name. Yields are tiny and the wines come out dense, high in alcohol and stony."),
    Q("Catalunya and Priorat",
      "Old, low-yielding bush vines of two traditional varieties carried the Priorat revival of the 1980s. Which pair?",
      ["Garnacha and Carinena", "Tempranillo and Graciano", "Monastrell and Bobal",
       "Mencia and Godello"], 0,
      "Both were already planted on the old terraces, Carinena also going by Samso in Catalonia. Cabernet Sauvignon and Syrah were brought in by the incoming producers rather than inherited."),
    Q("Catalunya and Priorat",
      "Which denomination forms a horseshoe around Priorat and is often sold as its affordable neighbour?",
      ["Montsant", "Terra Alta", "Conca de Barbera", "Costers del Segre"], 0,
      "Montsant was carved out of the old Tarragona denomination and shares varieties and much of the climate, though only part of it sits on the same slate."),
    Q("Catalunya and Priorat",
      "Trepat is grown almost nowhere else and goes into pink wine. Which Catalan denomination is its home?",
      ["Conca de Barbera", "Emporda", "Alella", "Pla de Bages"], 0,
      "Conca de Barbera is Trepat's stronghold. The variety is permitted for rosado Cava but not for white, and it gives pale colour, low tannin and bright red-fruit aromatics."),
    Q("Catalunya and Priorat",
      "Which Catalan denomination climbs from the Mediterranean shore to eight hundred metres inland, so that one estate can grow Xarel-lo low down and Parellada high up?",
      ["Penedes", "Emporda", "Priorat", "Costers del Segre"], 0,
      "Penedes divides into a coastal, a central and a high zone. That spread of altitude is much of why Sant Sadurni d'Anoia grew into the heart of the sparkling trade, and it makes serious still wine besides."),

    # ----------------------------------------------------------------- cava (5)
    Q("Cava",
      "A Spanish denomination may cover authorised parcels in Catalonia, Rioja, Navarra, Aragon and Extremadura at once. Which one?",
      ["Cava", "Rueda", "Ribera del Duero", "Jerez"], 0,
      "Cava was drawn around a method and a register of approved plots rather than one boundary, which is why it stretches across the country. The great majority of it still comes from Penedes."),
    Q("Cava",
      "Which three varieties make up the traditional white Cava blend?",
      ["Macabeo, Xarel-lo and Parellada", "Verdejo, Albarino and Godello",
       "Chardonnay, Pinot Noir and Trepat", "Garnacha Blanca, Moscatel and Malvasia"], 0,
      "Macabeo brings fruit and is the same grape as Rioja's Viura, Xarel-lo brings body and structure, and Parellada brings acidity from higher, cooler sites. Chardonnay and Pinot Noir are permitted additions."),
    Q("Cava",
      "How long must a Cava labelled Gran Reserva rest on its lees?",
      ["Thirty months", "Nine months", "Twelve months", "Sixty months"], 0,
      "Thirty months at minimum, against a floor of nine for the basic category. Lees contact is what builds the toast and bread-dough character that separates a serious Cava from a cheap one."),
    Q("Cava",
      "The first Spanish sparkling wine of the traditional method was bottled in 1872 by a member of which house?",
      ["Codorniu", "Freixenet", "Bodegas Torres", "Juve y Camps"], 0,
      "Josep Raventos came back from Champagne and bottled the first, using local varieties rather than imported ones. Freixenet, also of Sant Sadurni, became the trade's other giant."),
    Q("Cava",
      "For most of its first century this wine was sold under a borrowed French word. What forced the change to the name Cava?",
      ["European rules reserving Champagne to its own region",
       "A Spanish tax on foreign trade names", "A shortage of the traditional grapes",
       "A change in the method of production"], 0,
      "The trade dropped champana and took cava, the word for the underground cellar where the bottles rest. Nothing about the wine itself changed with the name."),

    # ---------------------------------------- galicia and the atlantic north (5)
    Q("Galicia and the Atlantic north",
      "Granite posts hold vines on overhead frames well clear of the ground in Rias Baixas. Which problem is that solving?",
      ["Fungal disease in a very wet climate", "Frost settling on the lower slopes",
       "Excessive summer heat on the fruit", "Wind coming off the Atlantic"], 0,
      "The parral lifts the canopy clear of the damp air near the ground, so that air moves through it and the fruit dries after rain, on a coast that can take well over a metre of it a year. It also let a smallholder grow vegetables underneath."),
    Q("Galicia and the Atlantic north",
      "Which Rias Baixas subzone is the coolest, the nearest to the sea and the historic heart of Albarino?",
      ["Val do Salnes", "O Rosal", "Condado do Tea", "Soutomaior"], 0,
      "Salnes sits around Cambados on the Ria de Arousa and gives the most bracing, saline wines. Condado do Tea lies inland up the Mino and is the warmest of the subzones."),
    Q("Galicia and the Atlantic north",
      "Rescued from near-extinction in the 1970s, one white variety now defines Valdeorras. Which is it?",
      ["Godello", "Albarino", "Treixadura", "Loureira"], 0,
      "Godello is broader and stonier than Albarino and takes well to lees ageing and a little oak. Valdeorras lies inland on slate at the eastern edge of Galicia."),
    Q("Galicia and the Atlantic north",
      "Terraces cut into gorges above the Sil and the Mino are worked by hand and sometimes reached by boat. Which denomination?",
      ["Ribeira Sacra", "Ribeiro", "Rias Baixas", "Monterrei"], 0,
      "The slopes reach gradients no machine can work, which is why the region is a byword for heroic viticulture. Mencia is its principal red grape."),
    Q("Galicia and the Atlantic north",
      "On the Basque coast a sharp, low-alcohol white with a faint prickle is drunk young as an aperitif. What is it called?",
      ["Txakoli", "Ribeiro", "Vinho Verde", "Cava"], 0,
      "Txakoli comes from three small Basque denominations and is built mainly on Hondarrabi Zuri. It is bottled with a trace of carbon dioxide and drunk within the year."),

    # -------------------------------- rueda, navarra, bierzo and la mancha (5) -
    Q("Rueda, Navarra, Bierzo and La Mancha",
      "A Rioja house went looking for a white grape in the 1970s and replanted an old Castilian variety. Which denomination grew out of that?",
      ["Rueda", "Cigales", "Toro", "Arlanza"], 0,
      "Marques de Riscal wanted a white to sit beside its Rioja reds and settled on Verdejo. Rueda was recognised in 1980, the first denomination in Castilla y Leon."),
    Q("Rueda, Navarra, Bierzo and La Mancha",
      "Before Verdejo was replanted, Rueda's reputation rested on a very different wine. What was it?",
      ["An oxidatively aged white called dorado", "A sweet botrytised white", "A dark, tannic red",
       "A traditional-method sparkling wine"], 0,
      "Dorado was aged in glass demijohns and part-filled barrels under a film of yeast, closer to a light Sherry than to any modern white. A little of it is still made."),
    Q("Rueda, Navarra, Bierzo and La Mancha",
      "Dry Garnacha rosado made the name of a denomination that shares part of its ground with Rioja. Which one?",
      ["Navarra", "Campo de Borja", "Somontano", "Cigales"], 0,
      "Part of Rioja Oriental lies inside Navarra, and the two have shared grapes and history for centuries. Navarra also plants more Cabernet, Merlot and Chardonnay than most Spanish denominations."),
    Q("Rueda, Navarra, Bierzo and La Mancha",
      "Steep slate slopes in a sheltered basin in the province of Leon give fragrant, lightly built reds. Which denomination?",
      ["Bierzo", "Ribeira Sacra", "Valdeorras", "Toro"], 0,
      "El Bierzo sits in a bowl between the Galician mountains and the Castilian plateau, taking Atlantic rain with continental heat. Old ungrafted Mencia on slate is its calling card."),
    Q("Rueda, Navarra, Bierzo and La Mancha",
      "Spain's most widely planted white variety covers the hot central plateau and goes in quantity to the brandy stills. Which grape?",
      ["Airen", "Viura", "Palomino", "Verdejo"], 0,
      "Airen survives drought on poor soil, planted wide apart as low bushes across La Mancha. Its wine is neutral, which is what a still wants, and the Tempranillo beside it goes by Cencibel."),

    # ------------------------------------------- jerez and the sherry styles (7)
    Q("Jerez and the Sherry styles",
      "A guest assumes an Oloroso must be sweet because it is dark. What do you tell them?",
      ["It is dry, unless it has been sweetened for a cream blend",
       "It is always sweet, being made from raisined grapes", "It is off-dry by law",
       "Its sweetness comes from the flor"], 0,
      "Every dry Sherry, all of them from Palomino, ferments out. The colour and the walnut smell come from years of oxygen, and sweetness in a dark Sherry has been blended in afterwards. The naturally sweet Pedro Ximenez and Moscatel are the exceptions, pressed from sun-dried grapes and fortified before the sugar is gone."),
    Q("Jerez and the Sherry styles",
      "A butt marked for Fino loses its flor without ever being refortified, and finishes with the nose of an Amontillado over the body of an Oloroso. Which style is it?",
      ["Palo Cortado", "Amontillado", "Oloroso", "Cream"], 0,
      "An Amontillado is refortified on purpose to kill its flor, while a Palo Cortado arrives there by accident. It carries the aromatic delicacy of the one over the body of an Oloroso, and it is the rarest of the dry styles."),
    Q("Jerez and the Sherry styles",
      "A cellar hand fills a Sherry butt right up to the bung and is told to draw some back out. What has he got wrong?",
      ["The wine needs a headspace of air above it",
       "The wine expands as it warms and would burst the cask",
       "It leaves no room for the sweetening wine added later",
       "Full butts cannot be stacked safely in the bodega"], 0,
      "A 600-litre bota is filled to around 500 litres. The air above the wine is what keeps a film of flor alive on a Fino, and what feeds the slow oxidation of an Oloroso."),
    Q("Jerez and the Sherry styles",
      "In a Sherry bodega, which row of butts is drawn from when wine is bottled?",
      ["The solera, the row nearest the floor", "The first criadera, immediately above it",
       "The youngest criadera at the top", "Whichever row the cellar master judges ready"], 0,
      "Solera comes from suelo, the floor. What is drawn off is replaced from the first criadera, which is replaced from the second, and so on upward, so no bottle is ever the produce of one year."),
    Q("Jerez and the Sherry styles",
      "The letters VORS on a Sherry label promise an average age of what?",
      ["Thirty years", "Twelve years", "Twenty years", "Fifty years"], 0,
      "VOS marks an average of twenty years and VORS thirty, both verified before the label may be used. They appear on the dry oxidative styles and on Pedro Ximenez, never on a Fino."),
    Q("Jerez and the Sherry styles",
      "A bottle of Fino has stood open behind the bar for a fortnight. What has become of it?",
      ["Its delicacy has oxidised away",
       "It has opened up and improved with air", "It has turned noticeably sweeter",
       "Nothing, since fortification makes it stable"], 0,
      "Biologically aged Sherry is a light wine of about fifteen percent that has been shielded from oxygen its whole life. Treat an open bottle as you would an open white, replace it after a few days, and serve it cold in a proper glass."),
    Q("Jerez and the Sherry styles",
      "Montilla-Moriles in Cordoba province supplies much of the raw material for one famous Andalucian sweet wine. Which grape ripens there for it?",
      ["Pedro Ximenez", "Palomino", "Moscatel", "Airen"], 0,
      "Montilla is hot enough to ripen Pedro Ximenez to enormous sugar, and the grapes are then sun-dried on mats before pressing. That raisined must is what sweetens a Cream Sherry."),
]
