"""Rank I rewrite - Sparkling/Fortified/Sweet (61 questions).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

Champagne is deliberately held to the minimum needed for contrast, since it has
its own Rank I category. The budget goes to the other sparkling regions, to the
four fortified families, and to the three routes to concentration in a sweet
wine: noble rot, freezing and drying.

Stems are built to lead with a symptom, a label or a scenario rather than with
the subject noun, so that define-the-term constructions never open a question.
"""

from lib import Q

CAT = "Sparkling/Fortified/Sweet"
SLUG = "r1-sparkling-fortified-sweet"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Sparkling method and vocabulary", 10),
    ("Sparkling regions of the world", 9),
    ("Port", 9),
    ("Sherry", 9),
    ("Madeira and Marsala", 6),
    ("Vins doux naturels", 4),
    ("Botrytis and late harvest", 7),
    ("Ice wine and dried-grape wines", 7),
]

BANK = [
    # ------------------------------- sparkling method and vocabulary (10) ---
    Q("Sparkling method and vocabulary",
      "Fine, persistent bead and a bready character in the glass point to a second fermentation carried out where?",
      ["In the same bottle the wine is sold in", "In a sealed pressure tank",
       "In an open wooden vat", "In a cask under a veil of yeast"], 0,
      "That is the traditional method, and the wine then rests on its spent yeast inside that bottle for a year or more. The pressure and the toasty flavour both come from there."),
    Q("Sparkling method and vocabulary",
      "Prosecco keeps its primary pear and white-flower aromatics because its second fermentation happens where?",
      ["In a sealed pressurised tank", "In each bottle, over years on the lees",
       "In an open vat", "In a small oak barrel"], 0,
      "The tank method takes weeks rather than years, so the grape's own aroma survives intact. Long lees contact would replace it with bread and biscuit."),
    Q("Sparkling method and vocabulary",
      "After the second fermentation the spent yeast has to be worked down into the neck of the bottle. What is that operation called?",
      ["Riddling, or remuage", "Tirage", "Assemblage", "Dosage"], 0,
      "Bottles are tilted and turned a fraction at a time, by hand on a pupitre or by machine in a gyropalette, until the sediment sits against the closure."),
    Q("Sparkling method and vocabulary",
      "The neck of a bottle is dipped in freezing brine and a plug of ice is then blown out. Which step is that?",
      ["Disgorgement", "Tirage", "Riddling", "Malolactic fermentation"], 0,
      "Freezing traps the sediment in a pellet that the wine's own pressure expels the moment the cap comes off. The small loss of volume is what the dosage replaces."),
    Q("Sparkling method and vocabulary",
      "Topping a bottle back up after disgorgement, with wine and a measured amount of sugar, goes by which name?",
      ["The dosage, or liqueur d'expedition", "The liqueur de tirage", "The taille",
       "Chaptalisation"], 0,
      "The dosage sets the final sweetness and rounds off the acidity. The liqueur de tirage is the other end of the process, the sugar and yeast that began the second fermentation."),
    Q("Sparkling method and vocabulary",
      "Ranked from driest upward, which run of sparkling sweetness terms is correct?",
      ["Brut Nature, Extra Brut, Brut, Extra Dry, Sec, Demi-Sec",
       "Extra Brut, Brut Nature, Brut, Sec, Extra Dry, Demi-Sec",
       "Brut, Brut Nature, Extra Brut, Extra Dry, Demi-Sec, Sec",
       "Extra Dry, Extra Brut, Brut, Brut Nature, Sec, Demi-Sec"], 0,
      "Extra Dry is the trap on a wine list: it sits sweeter than Brut, not drier. Doux, above Demi-Sec, is rare today."),
    Q("Sparkling method and vocabulary",
      "Brioche, toast and biscuit aromas in a bottle-fermented sparkling wine arise from what?",
      ["Autolysis, the breakdown of dead yeast cells on the lees", "New oak barrels",
       "Malolactic fermentation", "The sugar added at dosage"], 0,
      "Once the yeast has finished it dies and slowly ruptures, releasing compounds into the wine around it. The longer a bottle rests on those lees, the more pronounced the character."),
    Q("Sparkling method and vocabulary",
      "A single fermentation is halted by cold and left to finish inside a sealed bottle, leaving the wine cloudy and lightly fizzy. Which technique is that?",
      ["The ancestral method", "The traditional method", "The tank method", "Carbonation"], 0,
      "No fresh yeast or sugar is added for a second fermentation, so the bubbles come from the first one finishing in glass. It is the basis of pet-nat and of Bugey-Cerdon."),
    Q("Sparkling method and vocabulary",
      "A label reading Blanc de Noirs tells the guest what?",
      ["The wine is white but made from black grapes",
       "The wine is white and made only from white grapes",
       "Red and white wine were blended together", "The wine spent time on its skins"], 0,
      "Gentle pressing draws the juice off before it picks up colour from the skins. Blanc de Blancs is the mirror image, white grapes alone."),
    Q("Sparkling method and vocabulary",
      "An Italian label may say frizzante rather than spumante. What does that distinction record?",
      ["The pressure in the bottle", "The sweetness of the wine", "The grape variety used",
       "The region of origin"], 0,
      "Frizzante is lightly sparkling, roughly one to two and a half atmospheres, while spumante is fully sparkling above three. Moscato d'Asti is frizzante and Asti is spumante."),

    # -------------------------------- sparkling regions of the world (9) ----
    Q("Sparkling regions of the world",
      "A traditional-method sparkler built on Macabeo, Xarel-lo and Parellada carries which name?",
      ["Cava", "Txakoli", "Rueda", "Sekt"], 0,
      "Cava is defined by its method rather than by a single place, though the great majority comes from Penedes in Catalonia. Chardonnay and Pinot Noir are permitted alongside the three traditional grapes."),
    Q("Sparkling regions of the world",
      "Which variety must dominate a Prosecco?",
      ["Glera", "Garganega", "Cortese", "Trebbiano"], 0,
      "The grape was renamed Glera in 2009 so that Prosecco itself could be protected as a place name. Conegliano Valdobbiadene is the historic hillside heart of the zone."),
    Q("Sparkling regions of the world",
      "Lombardy's benchmark bottle-fermented sparkler, built largely on Chardonnay and Pinot Noir, is sold as what?",
      ["Franciacorta", "Lambrusco", "Gavi", "Soave"], 0,
      "Franciacorta uses the traditional method with long lees ageing. Its Saten style is an all-white blend bottled at lower pressure for a softer, creamier mousse."),
    Q("Sparkling regions of the world",
      "At around five and a half percent alcohol and only gently fizzy, Moscato d'Asti gets its sweetness how?",
      ["A single fermentation is stopped early, leaving sugar behind",
       "Sugar is added just before bottling", "The grapes are dried before pressing",
       "Spirit is added to halt the fermentation"], 0,
      "Chilling and filtering arrest the ferment in tank, so the wine keeps grape sugar, low alcohol and a pressure well short of a full spumante."),
    Q("Sparkling regions of the world",
      "A German sparkling wine made entirely from the grower's own fruit is labelled how?",
      ["Winzersekt", "Landwein", "Federweisser", "Perlwein"], 0,
      "Winzersekt is estate-grown grower fizz and must be bottle-fermented by the traditional method, with at least nine months on the lees. Much inexpensive Sekt is instead tank made from base wine bought in from elsewhere in Europe."),
    Q("Sparkling regions of the world",
      "Outside Champagne, which word on a French label guarantees the wine was made by the traditional method?",
      ["Cremant", "Mousseux", "Perlant", "Petillant"], 0,
      "Cremant d'Alsace, de Bourgogne, de Loire and the rest share rules on hand harvesting, whole-bunch pressing and a minimum time on the lees."),
    Q("Sparkling regions of the world",
      "Which country turned a sparkling red made from Shiraz into a national specialty?",
      ["Australia", "Argentina", "South Africa", "New Zealand"], 0,
      "Usually off dry, soft in tannin and served lightly chilled. It is a fixture of an Australian Christmas table, where the holiday falls in high summer."),
    Q("Sparkling regions of the world",
      "South African bottle-fermented sparkling wine is sold under which designation?",
      ["Cap Classique", "Espumante", "Sekt", "Perlwein"], 0,
      "The first South African bottle-fermented sparkler was made in 1971, but the Cap Classique name dates from 1992, adopted once the Champagne terms were closed off. Chardonnay and Pinot Noir lead the blends, with Chenin Blanc still widely used."),
    Q("Sparkling regions of the world",
      "Served cool alongside the cured pork and Parmigiano of Emilia, which frothy red is the local staple?",
      ["Lambrusco", "Bardolino", "Freisa", "Brachetto"], 0,
      "Lambrusco is a family of related varieties grown around Modena and Reggio. The good bottles are dry and tank made, and their acidity and light tannin cut straight through fat."),

    # ------------------------------------------------------------- port (9) -
    Q("Port",
      "Grape spirit goes into Port partway through fermentation. What does that achieve?",
      ["It kills the yeast and leaves unfermented sugar in the wine",
       "It removes sugar and raises the acidity", "It starts a second fermentation",
       "It strips colour out of the must"], 0,
      "Fermentation is stopped at around six or seven percent alcohol and the spirit takes the wine close to twenty. The sweetness is grape sugar the yeast never reached."),
    Q("Port",
      "Port's vineyards climb the terraced schist of which river valley?",
      ["The Douro", "The Tejo", "The Minho", "The Mondego"], 0,
      "A hot, dry valley sheltered from Atlantic weather by the Serra do Marao. The wine takes its name from Oporto at the river mouth, though the shippers built their ageing lodges across the water in Vila Nova de Gaia."),
    Q("Port",
      "Of the Douro's red varieties, which is generally rated the finest for Port?",
      ["Touriga Nacional", "Baga", "Castelao", "Trincadeira"], 0,
      "Touriga Franca, Tinta Roriz, Tinta Barroca and Tinto Cao complete the classic five. Blending is the norm, and old vineyards are often planted as a field mixture."),
    Q("Port",
      "Bottled after about two years in wood and then left to mature for decades in glass, this style is declared only in exceptional years. Which is it?",
      ["Vintage Port", "Tawny Port", "Colheita", "White Port"], 0,
      "A declaration is the shipper's own judgement and comes perhaps three times a decade. The wine goes into bottle unfiltered, throws a heavy crust, and must be decanted."),
    Q("Port",
      "A pale amber rim and flavours of walnut and dried fig in a Port point to what?",
      ["Long ageing in cask before bottling", "Long ageing in bottle after two years in wood",
       "Fermentation under a veil of yeast", "A short maceration and very early bottling"], 0,
      "Air reaching the wine through the wood browns it and builds nutty, dried-fruit flavour. The permitted age indications are ten, twenty, thirty, forty, fifty and eighty years, and each states the style a tasting panel judges the blend to show rather than a verified average."),
    Q("Port",
      "A wood-aged Port from one named harvest, kept in cask for at least seven years, is sold as what?",
      ["Colheita", "Crusted Port", "Vintage Port", "Ruby Reserve"], 0,
      "A Colheita carries a year like a vintage Port but has done its ageing in cask, so it needs no decanting. The label gives the bottling date as well as the harvest."),
    Q("Port",
      "Four to six years in cask, then bottled ready to drink: which Port designation is that?",
      ["Late Bottled Vintage", "Crusted Port", "Colheita", "Single quinta vintage"], 0,
      "LBV comes from a single year but does its formative ageing in wood rather than glass. Most is filtered and pours clear; unfiltered bottlings still throw a deposit."),
    Q("Port",
      "In a year a shipper declines to declare, it may still bottle a vintage wine drawn from one property. What is that called?",
      ["A single quinta vintage Port", "A colheita", "A crusted Port", "A ruby reserve"], 0,
      "The fruit comes from one estate, usually in a season judged short of a full declaration, though a few properties bottle one in declared years as well. These mature earlier and cost a fraction of a declared vintage."),
    Q("Port",
      "Chilled over ice with tonic and a twist of lemon is the everyday Portuguese serve for which Port?",
      ["White Port", "Vintage Port", "Crusted Port", "Forty year old tawny"], 0,
      "Made from white Douro grapes in styles running dry to sweet. Treated this way it is an aperitif rather than a dessert wine, which is how most Portuguese drink it."),

    # ----------------------------------------------------------- sherry (9) -
    Q("Sherry",
      "Jerez de la Frontera anchors the Sherry triangle. Which two towns complete it?",
      ["El Puerto de Santa Maria and Sanlucar de Barrameda", "Cadiz and Seville",
       "Montilla and Malaga", "Cordoba and Huelva"], 0,
      "All three sit in Andalucia within reach of the Atlantic, and the historic bodegas are concentrated in them. Sanlucar's damper sea air is why its wines differ from those of Jerez."),
    Q("Sherry",
      "A brilliant white soil that crusts over and holds winter rain through a rainless summer underpins the best Sherry vineyards. What is it called?",
      ["Albariza", "Terra rossa", "Galestro", "Crasse de fer"], 0,
      "Albariza is chalky and limestone-rich, and it sets hard after rain so that moisture is sealed beneath for the vine to draw on. Macharnudo and Balbaina are celebrated albariza pagos."),
    Q("Sherry",
      "Nearly every dry Sherry is built on which grape?",
      ["Palomino", "Pedro Ximenez", "Airen", "Verdejo"], 0,
      "Palomino is neutral and low in acid, which suits a wine whose character is built in the bodega rather than the vineyard. Pedro Ximenez and Moscatel are kept for sweet wines."),
    Q("Sherry",
      "A film of living yeast forms across the surface of a part-filled butt. What is it, and what does it do?",
      ["Flor, which shields the wine from air", "Flor, which speeds up oxidation",
       "Mother, which turns the wine to vinegar", "Lees, which sweeten the wine"], 0,
      "Biological ageing keeps a Fino pale and gives it a dough-like, bruised-apple tang. The yeast feeds on alcohol and glycerol and leaves acetaldehyde behind."),
    Q("Sherry",
      "Why must a wine destined to become Oloroso be fortified higher than one headed for Fino?",
      ["Flor cannot survive at the higher strength, so the wine ages in contact with air",
       "Higher alcohol makes the flor grow faster",
       "The extra spirit is what makes the wine sweet",
       "No wine may enter a solera below seventeen percent"], 0,
      "Fino is fortified to about fifteen percent, which the yeast tolerates. Oloroso goes to seventeen or above, which kills any flor, and the wine darkens and turns nutty from oxygen instead."),
    Q("Sherry",
      "A wine that started life under flor, lost it, and finished its ageing exposed to air is sold as what?",
      ["Amontillado", "Fino", "Pedro Ximenez", "Cream"], 0,
      "Two lives in one glass: a Fino's saline tang beneath an oxidative, hazelnut depth. Palo Cortado is the rarer wine that arrives at the same duality by accident."),
    Q("Sherry",
      "Which dry Sherry style may only be aged in Sanlucar de Barrameda?",
      ["Manzanilla", "Fino", "Oloroso", "Amontillado"], 0,
      "The cool, humid Atlantic air there keeps the flor thick through the year, so the wine stays lighter and more saline than a Fino aged inland at Jerez."),
    Q("Sherry",
      "Wine drawn from the oldest row of casks is replaced from the row above, and so on up the stack. What is that arrangement called?",
      ["The solera", "The estufagem", "The appassimento", "The cuve close"], 0,
      "Fractional blending evens out vintage differences and refreshes older wine with younger. The feeding rows are the criaderas, and no cask is ever drained completely."),
    Q("Sherry",
      "Grapes laid out in the sun to raisin before pressing yield which near-black, syrupy Sherry?",
      ["Pedro Ximenez", "Fino", "Palo Cortado", "Manzanilla"], 0,
      "Sun-drying pushes the sugar far past what yeast can ferment, so the wine stays thick and dark. It behaves more like a sauce than a drink and is often poured over ice cream."),

    # ---------------------------------------------- madeira and marsala (6) -
    Q("Madeira and Marsala",
      "Heat is applied deliberately during the ageing of Madeira. What does it give the wine?",
      ["A cooked, tangy character and near indestructible stability",
       "A fresh, floral aroma", "A pale colour and softer acidity", "A light spritz"], 0,
      "The style descends from barrels that improved while crossing the tropics as ballast. Because the wine has already been oxidised and heated, an opened bottle keeps for months."),
    Q("Madeira and Marsala",
      "Between the two ways of warming Madeira, which is reserved for the finest wines?",
      ["Canteiro, years of gentle warmth in cask under the roof",
       "Estufa, tanks held near fifty degrees for months",
       "Chilling the wine below freezing", "Burying the casks in sand"], 0,
      "Canteiro relies on the natural heat of the lodge and takes years. The estufa tanks do a cruder version of the same job in months, and serve everyday bottlings."),
    Q("Madeira and Marsala",
      "Sercial, Verdelho, Bual and Malmsey appear on Madeira labels. What do those names record?",
      ["The grape, and with it the sweetness, running driest to sweetest in that order",
       "The number of years spent in cask", "The lodge that aged the wine",
       "The altitude of the vineyard"], 0,
      "Malmsey is Malvasia and the richest of the four; Sercial is bracingly dry. A wine named for one of them has to be made overwhelmingly from that variety."),
    Q("Madeira and Marsala",
      "Which grape accounts for most of Madeira's plantings, though it long went unmentioned on labels?",
      ["Tinta Negra", "Sercial", "Terrantez", "Palomino"], 0,
      "Tinta Negra is a red grape adaptable enough to be made at every sweetness level. The noble white varieties together account for a small minority of the island's vines."),
    Q("Madeira and Marsala",
      "Marsala takes its name from a town on which island?",
      ["Sicily", "Sardinia", "Corsica", "Crete"], 0,
      "The wine was developed on Sicily's western coast for the British trade in the late eighteenth century. Grillo, Catarratto and Inzolia are the main white grapes behind it."),
    Q("Madeira and Marsala",
      "Oro, Ambra and Rubino on a Marsala label record what?",
      ["The colour of the wine", "The residual sugar", "The length of ageing",
       "The vineyard of origin"], 0,
      "Gold, amber and ruby. Sweetness is declared separately as secco, semisecco or dolce on the Fine and Superiore tiers, while Vergine takes no sweetening and is dry by definition; ageing runs Fine, Superiore, Superiore Riserva, then Vergine."),

    # ------------------------------------------------ vins doux naturels (4)-
    Q("Vins doux naturels",
      "Spirit goes in partway through fermentation and nothing sweet is ever added. Which French category does that describe?",
      ["Vin doux naturel", "Vin de liqueur", "Vin de paille", "Vin jaune"], 0,
      "The sweetness is grape sugar the yeast never reached, exactly as in Port. Most sit between fifteen and eighteen percent alcohol. A vin de liqueur differs in that the spirit goes into unfermented must."),
    Q("Vins doux naturels",
      "Which southern Rhone village is as well known for a sweet fortified Muscat as for its red wine?",
      ["Beaumes-de-Venise", "Gigondas", "Vacqueyras", "Cairanne"], 0,
      "Muscat de Beaumes-de-Venise is made from Muscat Blanc a Petits Grains, grapey and scented with orange blossom, and it is traditionally poured with melon or a fruit tart."),
    Q("Vins doux naturels",
      "Banyuls and Maury build their sweet fortified reds on which variety?",
      ["Grenache", "Syrah", "Mourvedre", "Cinsault"], 0,
      "Aged in a deliberately oxidative style, they take on coffee, walnut and dried fig. Banyuls is one of the few wines that can stand up to dark chocolate."),
    Q("Vins doux naturels",
      "Casks left deliberately part full, in the sun or in a warm loft, develop which prized character?",
      ["Rancio", "Flor", "Petillance", "Botrytis"], 0,
      "Rancio is a controlled oxidative note of walnut, coffee and old wood. The same word describes the equivalent character in very old Sherry and in Armagnac."),

    # ---------------------------------------- botrytis and late harvest (7) -
    Q("Botrytis and late harvest",
      "One fungus can either destroy a crop or make a great sweet wine. What decides which?",
      ["Whether dry weather follows the damp that let it take hold",
       "Whether the grapes are red or white", "Whether the vineyard is irrigated",
       "Whether the vines are young or old"], 0,
      "Damp mornings let Botrytis cinerea establish itself, but if the wet keeps up it turns to grey rot and the fruit is lost. Dry, breezy afternoons are what turn infection into concentration."),
    Q("Botrytis and late harvest",
      "How does Botrytis cinerea concentrate the juice inside a berry?",
      ["It pierces the skin so water evaporates away",
       "It converts the grape's acid into sugar",
       "It ferments part of the sugar while still on the vine",
       "It thickens the skin and traps water inside"], 0,
      "The fungus perforates the skin with its filaments and the berry shrivels, concentrating sugar, acid and flavour together. It also contributes honey, ginger and dried apricot of its own."),
    Q("Botrytis and late harvest",
      "Which meeting of rivers supplies the autumn mists that make Sauternes possible?",
      ["The cold Ciron running into the warmer Garonne",
       "The Dordogne running into the Gironde", "The Vienne running into the Loire",
       "The Saone running into the Rhone"], 0,
      "The Ciron leaves a shaded forest cold and chills the surface of the Garonne, so fog forms at night and burns off by midday. That daily rhythm is the reason the appellation exists where it does."),
    Q("Botrytis and late harvest",
      "Pickers go through a Sauternes vineyard several times in one harvest. Why?",
      ["Botrytis spreads unevenly, so only the shrivelled berries are taken each pass",
       "Each pass gathers a different grape variety",
       "The grapes have to be sorted by colour on the vine",
       "The pickers are paid by the day rather than the crate"], 0,
      "Those passes are the tries, and there can be half a dozen across several weeks. Yields fall to a fraction of a dry white's, which is most of why the wine costs what it does."),
    Q("Botrytis and late harvest",
      "Which German Pradikat level calls for individually selected, shrivelled botrytised berries?",
      ["Trockenbeerenauslese", "Kabinett", "Spatlese", "Auslese"], 0,
      "Beerenauslese sits just below it and Eiswein alongside. All of them depend on the season, so they are made only in favourable years and in tiny quantities."),
    Q("Botrytis and late harvest",
      "A Hungarian label gives a number of puttonyos. What does that number record?",
      ["The sweetness of a Tokaji Aszu", "The years the wine spent in cask",
       "The altitude of the vineyard", "The number of grape varieties blended"], 0,
      "It began as a count of hods of botrytised aszu berries kneaded into a base wine, and now stands for a minimum residual sugar. Five and six puttonyos are the usual bottlings."),
    Q("Botrytis and late harvest",
      "Coteaux du Layon, Bonnezeaux and Quarts de Chaume concentrate which grape?",
      ["Chenin Blanc", "Sauvignon Blanc", "Semillon", "Melon de Bourgogne"], 0,
      "Chenin's searching acidity carries great sweetness without turning cloying, and the Layon valley draws noble rot in the best years. Vouvray makes sweet wine from the same grape further upstream."),

    # ----------------------------------- ice wine and dried-grape wines (7) -
    Q("Ice wine and dried-grape wines",
      "Fruit has to be picked and pressed while still frozen solid for which style?",
      ["Ice wine", "Vin Santo", "Amarone", "Sauternes"], 0,
      "Water in the berry stays behind as ice in the press, so only concentrated sugar and acid run off. Germany's Eiswein and Canada's icewine are the same idea under two names."),
    Q("Ice wine and dried-grape wines",
      "Which hardy hybrid does most of the work in Canadian icewine?",
      ["Vidal", "Chardonnay", "Gewurztraminer", "Zinfandel"], 0,
      "Vidal has thick skins that survive months hanging into winter without splitting. Riesling and Cabernet Franc are also used, in far smaller quantities."),
    Q("Ice wine and dried-grape wines",
      "Bunches are laid on racks in an airy loft for months, losing water and gaining concentration. Which Italian practice is that?",
      ["Appassimento", "Governo", "Ripasso", "Estufagem"], 0,
      "Valpolicella dries Corvina and its partners this way over the winter. Fermented out the result is Amarone; stopped while still sweet it is Recioto."),
    Q("Ice wine and dried-grape wines",
      "Amarone and Recioto della Valpolicella begin from the same dried grapes. What separates them?",
      ["Amarone is fermented dry while Recioto keeps its sweetness",
       "Recioto is fortified and Amarone is not",
       "Amarone is dried and Recioto is not", "Recioto is white and Amarone is red"], 0,
      "Amarone means bitter, which is how the dry version got its name. Recioto is the older of the two and was the region's original sweet speciality."),
    Q("Ice wine and dried-grape wines",
      "Dried on mats, fermented in small sealed barrels under the roof and poured with cantucci: which Tuscan wine?",
      ["Vin Santo", "Brunello di Montalcino", "Vernaccia di San Gimignano",
       "Vino Nobile di Montepulciano"], 0,
      "Trebbiano and Malvasia dry for months, then spend years in caratelli sealed with a madre left from an earlier batch. The results run from unctuous to nearly dry."),
    Q("Ice wine and dried-grape wines",
      "The island of Pantelleria dries which grape for its celebrated passito?",
      ["Zibibbo, the local name for Muscat of Alexandria", "Nero d'Avola", "Grillo",
       "Carricante"], 0,
      "The wine is all dried apricot, fig and orange peel. The vines are trained low in hollows scooped out of the ground to shelter them from the wind."),
    Q("Ice wine and dried-grape wines",
      "Bunches dried on straw beds in the Jura give which wine?",
      ["Vin de paille", "Vin jaune", "Macvin du Jura", "Cremant du Jura"], 0,
      "The fruit dries for weeks before a slow fermentation and years in cask. Austria's Strohwein and the straw wines of the northern Rhone rest on the same principle."),
]
