"""Rank I rewrite — Tasting & Service (66 questions).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

Openers varied from the start, and the constructions in lib.BANNED_TEMPLATES
avoided by construction rather than by later reframing.
"""

from lib import Q

CAT = "Tasting & Service"
SLUG = "r1-tasting-service"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("The deductive grid", 7),
    ("Sight", 6),
    ("Nose", 7),
    ("Palate", 8),
    ("Assessing structure", 6),
    ("Faults", 6),
    ("Service temperature", 6),
    ("Glassware and decanting", 6),
    ("Opening and pouring", 7),
    ("Order of service and the list", 7),
]

BANK = [
    # ------------------------------------------------- the deductive grid (7)
    Q("The deductive grid",
      "A systematic tasting method proceeds in which order?",
      ["Sight, nose, palate, conclusion", "Nose, sight, conclusion, palate",
       "Palate, sight, nose, conclusion", "Conclusion, sight, nose, palate"], 0,
      "The order matters because each stage constrains the next. Reaching a conclusion first and then hunting for evidence is the commonest way to taste badly."),
    Q("The deductive grid",
      "What is the purpose of tasting to a fixed grid rather than freely?",
      ["It forces every component to be assessed, including inconvenient ones",
       "It makes tasting faster", "It guarantees the correct answer",
       "It removes the need for experience"], 0,
      "A grid stops you skipping what does not fit the theory you have already formed. It is a discipline against your own guessing."),
    Q("The deductive grid",
      "In a blind tasting conclusion, which elements are typically called?",
      ["Grape, origin and vintage range", "Producer and vineyard only",
       "Price and importer", "The winemaker's name"], 0,
      "Grape, place and approximate age, argued from the evidence gathered. Naming the producer is a party trick rather than the exercise."),
    Q("The deductive grid",
      "Why should a taster describe rather than judge in the early stages?",
      ["Description gathers evidence; judgement closes it off prematurely",
       "Judgement is forbidden by law", "Description is faster",
       "Judging requires a certified palate"], 0,
      "Saying good or bad ends the enquiry. Saying pale ruby with a garnet rim leaves you somewhere to go."),
    Q("The deductive grid",
      "Palate fatigue during a long tasting is best managed how?",
      ["Spitting, plain water, and breaks between flights", "Drinking more slowly",
       "Eating strongly flavoured food", "Tasting only reds"], 0,
      "Alcohol accumulates and the palate dulls. Spitting is professional practice, not modesty, and water between flights resets more than bread does."),
    Q("The deductive grid",
      "Ambient conditions can distort a tasting. Which is most disruptive?",
      ["Strong ambient smells such as perfume or cooking", "A quiet room",
       "Natural daylight", "A white tablecloth"], 0,
      "The nose does most of the work, so competing aromas ruin an assessment. Daylight and a white surface are aids rather than distractions."),
    Q("The deductive grid",
      "Why is a white background used when assessing a wine's appearance?",
      ["It lets colour and clarity be judged without distortion", "It keeps the wine cooler",
       "It is a legal requirement", "It reduces glare on the glass"], 0,
      "Colour read against a patterned or coloured surface is unreliable. A tilted glass over white paper is the standard arrangement."),

    # -------------------------------------------------------------- sight (6)
    Q("Sight",
      "The edge of a red has paled and browned while the core stays deep. What does that suggest?",
      ["Advancing age", "High alcohol", "Residual sugar", "The use of oak"], 0,
      "A young red runs to the edge with its core colour; an older one pales and browns at the rim. It is one of the more reliable visual clues."),
    Q("Sight",
      "As a red wine ages, its colour generally moves in which direction?",
      ["From purple toward ruby, garnet and tawny", "From tawny toward purple",
       "It does not change", "From garnet toward green"], 0,
      "Anthocyanins polymerise and drop out over time. Whites move the opposite way, deepening from pale straw toward gold and amber."),
    Q("Sight",
      "The tears or legs running down a glass indicate what?",
      ["Alcohol and glycerol content", "Wine quality", "Age", "Sweetness alone"], 0,
      "They are a surface-tension effect, useful as a rough alcohol signal and worthless as a quality one, despite the folklore."),
    Q("Sight",
      "You pour a wine that is visibly cloudy in the glass. What should that prompt?",
      ["An unfiltered wine, or a fault such as microbial spoilage",
       "High tannin", "Correct serving temperature", "Extended oak ageing"], 0,
      "Deliberately unfiltered wines can be cloudy by intent, so haze prompts a question rather than a verdict. Confirm on the nose and palate."),
    Q("Sight",
      "Small crystals in the bottom of a bottle or on the cork are usually what?",
      ["Harmless tartrate crystals", "Broken glass", "Mould", "Sugar"], 0,
      "Tartrates precipitate when a wine is chilled and are tasteless. They alarm guests, so a quiet explanation is part of the job."),
    Q("Sight",
      "A deep, opaque colour in a young red most reliably suggests what?",
      ["Thick-skinned grapes, warm climate or extended maceration",
       "Great age", "High acidity", "Low alcohol"], 0,
      "Colour reflects extraction and grape variety more than quality. A pale wine may be a great Pinot Noir and a black one an ordinary Syrah."),

    # --------------------------------------------------------------- nose (7)
    Q("Nose",
      "A young unoaked white smells of lemon, green apple and elderflower. Those aromas are classed as what?",
      ["Primary, from the grape", "Secondary, from fermentation",
       "Tertiary, from bottle age", "Quaternary, from bottling"], 0,
      "Primary from the fruit, secondary from winemaking including fermentation and oak, tertiary from age. Sorting them is most of the deductive work."),
    Q("Nose",
      "Which aromas are classed as tertiary?",
      ["Those developed through ageing, such as leather, mushroom and dried fruit",
       "Fresh citrus and green apple", "Vanilla from new oak", "Banana from carbonic maceration"], 0,
      "Tertiary character is what bottle and barrel time build. Its presence is the strongest evidence for calling an older vintage range."),
    Q("Nose",
      "Vanilla, coconut and sweet spice on the nose most often point to what?",
      ["New oak", "Botrytis", "Malolactic conversion alone", "High acidity"], 0,
      "Oak lactones and vanillin come from the barrel. American oak tends to the coconut and dill end, French toward finer spice."),
    Q("Nose",
      "A buttery aroma in a white wine is most commonly attributed to what?",
      ["Malolactic conversion producing diacetyl", "New oak alone",
       "Residual sugar", "Cold fermentation"], 0,
      "Diacetyl is the by-product. Whether it is welcome is a style question, and many producers block malolactic to preserve tautness."),
    Q("Nose",
      "Why should a taster smell the wine before swirling as well as after?",
      ["The most volatile compounds and some faults show before agitation",
       "Swirling destroys the wine", "It is purely traditional",
       "It warms the wine"], 0,
      "The still nose catches the lightest, most fleeting compounds. Swirling then releases the heavier ones by increasing the surface area."),
    Q("Nose",
      "Aroma intensity is assessed independently of quality because what?",
      ["A restrained wine may be fine and a loud one ordinary",
       "Intensity cannot be measured", "Quality is decided only on the palate",
       "Intensity always indicates age"], 0,
      "Keeping the two apart is the discipline. Many great wines are quiet, particularly when young or served too cold."),
    Q("Nose",
      "Fruit described as fresh rather than cooked or dried suggests what about origin?",
      ["A cooler climate or a younger wine", "A warmer climate",
       "Extended barrel ageing", "High residual sugar"], 0,
      "Fruit condition is one of the better climate clues: crisp and tart at the cool end, baked and jammy at the warm end."),

    # ------------------------------------------------------------ palate (8)
    Q("Palate",
      "Which structural components are assessed on the palate?",
      ["Sweetness, acidity, tannin, alcohol and body", "Colour and clarity",
       "Aroma intensity alone", "Only tannin and colour"], 0,
      "Each is judged separately before any conclusion about balance. Running them together is how a high-alcohol wine gets called sweet."),
    Q("Palate",
      "Length, in tasting terms, refers to what?",
      ["How long the flavour persists after swallowing or spitting",
       "How long the wine spent in barrel", "How long the bottle has aged",
       "The size of the pour"], 0,
      "Persistence is one of the more dependable quality markers, and it is measured in seconds after the wine has gone."),
    Q("Palate",
      "A wine described as balanced means what?",
      ["No single component dominates the others", "It has no tannin",
       "It is exactly half sweet and half dry", "It is inexpensive"], 0,
      "Balance is a relationship rather than a level: high acid can be balanced by high sugar, and high tannin by fruit and body."),
    Q("Palate",
      "Body, in tasting terms, describes what?",
      ["The weight and texture of the wine in the mouth", "The colour depth",
       "The alcohol level alone", "The tannin level alone"], 0,
      "Alcohol, glycerol, sugar and extract all contribute. Whole-mouth impression rather than a single measurable component."),
    Q("Palate",
      "Perceived sweetness in a dry wine can be created by which component?",
      ["High alcohol or ripe fruit character", "High acidity", "Firm tannin",
       "Low temperature"], 0,
      "Alcohol reads faintly sweet and very ripe fruit reads sweeter still. A technically dry wine is regularly described as sweet for this reason."),
    Q("Palate",
      "Retronasal perception refers to what?",
      ["Aromas reaching the olfactory receptors from the back of the mouth",
       "Smelling the empty glass", "Smelling before swirling",
       "The sensation of tannin"], 0,
      "Much of what is called flavour is smell arriving from behind. It is why a blocked nose flattens food and wine alike."),
    Q("Palate",
      "Why do tasters draw air across the wine in the mouth?",
      ["It volatilises aromatic compounds for retronasal perception",
       "It cools the wine", "It removes tannin", "It reduces alcohol"], 0,
      "Air lifts the aromatics off the liquid and up behind the palate. Unattractive to watch and genuinely informative."),
    Q("Palate",
      "A wine that seems hollow in the middle is usually said to lack what?",
      ["Mid-palate fruit or concentration", "Acidity", "Alcohol", "Colour"], 0,
      "Attack and finish present, nothing between. It is a common shape in over-cropped or heavily manipulated wine."),

    # ------------------------------------------------ assessing structure (6)
    Q("Assessing structure",
      "Acidity is judged physically by which sensation?",
      ["Salivation at the sides of the tongue", "A drying grip on the gums",
       "Warmth in the throat", "Weight on the tongue"], 0,
      "The mouth waters in response to acid. Counting how long salivation continues is a practical way to rank two wines."),
    Q("Assessing structure",
      "Which wine component registers as touch rather than as a taste?",
      ["Tannin", "Acidity", "Sweetness", "Bitterness"], 0,
      "Astringency is touch rather than taste: tannin binding the lubricating proteins in saliva. It is why it builds across several sips."),
    Q("Assessing structure",
      "Alcohol is assessed by which sensation?",
      ["Warmth at the back of the mouth and throat", "Salivation",
       "A drying grip", "A metallic tang"], 0,
      "The burn is the clue, and it is easily confused with body. Very high alcohol also reads slightly sweet."),
    Q("Assessing structure",
      "Why is tannin best assessed after several sips rather than one?",
      ["It accumulates, so a single sip understates it", "It disappears with repetition",
       "The first sip is always inaccurate", "It changes the wine's temperature"], 0,
      "Astringency builds as saliva proteins are stripped. A wine that seemed supple can turn firm by the third mouthful."),
    Q("Assessing structure",
      "Confusing tannin with acidity is a common error. What distinguishes them?",
      ["Tannin dries the mouth; acid makes it water", "Tannin is sweet; acid is bitter",
       "Tannin is felt only in whites", "There is no reliable difference"], 0,
      "Opposite physical responses. Both can make a wine seem firm, which is where the confusion comes from."),
    Q("Assessing structure",
      "Serving temperature affects perceived structure in which way?",
      ["Cold accentuates acid and tannin; warmth accentuates alcohol and body",
       "Temperature has no effect on structure", "Cold accentuates alcohol",
       "Warmth accentuates acidity"], 0,
      "Much of what is blamed on a wine is really a service fault. The useful range is narrower than most people assume."),

    # ------------------------------------------------------------ faults (6)
    Q("Faults",
      "A wine smelling of wet cardboard, damp cellar and muted fruit is showing what?",
      ["Cork taint from TCA", "Volatile acidity", "Reduction", "Heat damage"], 0,
      "TCA strips fruit before it announces itself, so a merely dull wine may be lightly corked. It can come from cellar materials as well as cork."),
    Q("Faults",
      "Nail varnish and vinegar on the nose indicate which fault?",
      ["Volatile acidity", "Cork taint", "Reduction", "Tartrate instability"], 0,
      "Acetic acid with ethyl acetate. Trace levels add lift and are sometimes deliberate; past a threshold the wine is spoiled."),
    Q("Faults",
      "Struck match, rubber or drains on opening, often blowing off with air, suggests what?",
      ["Reduction", "Oxidation", "Cork taint", "Brettanomyces"], 0,
      "Sulphur compounds from a low-oxygen environment. Decanting or swirling frequently clears it, which distinguishes it from a permanent fault."),
    Q("Faults",
      "A white wine that is deep gold, flat and smelling of bruised apple is likely what?",
      ["Oxidised", "Reduced", "Corked", "Too cold"], 0,
      "Acetaldehyde and colour deepening. Deliberate in Sherry and Vin Jaune, a fault in an unfortified table wine."),
    Q("Faults",
      "Barnyard, sticking plaster and leather notes are usually attributed to what?",
      ["Brettanomyces", "Malolactic conversion", "New oak", "Botrytis"], 0,
      "A spoilage yeast. Opinion divides on trace levels, and at higher levels it flattens fruit and homogenises a range."),
    Q("Faults",
      "A pushed-up cork and a maderised, stewed character point to what?",
      ["Heat damage in storage or transit", "Cork taint", "Reduction",
       "Excessive filtration"], 0,
      "Wine expands when it gets hot and forces the cork. It is a shipping and storage failure rather than a winemaking one."),

    # ----------------------------------------------- service temperature (6)
    Q("Service temperature",
      "Sparkling wine is generally served within which range?",
      ["6 to 10 C", "12 to 14 C", "16 to 18 C", "2 to 4 C"], 0,
      "Cold holds the mousse and keeps the pressure manageable on opening. Fine vintage Champagne benefits from the warmer end."),
    Q("Service temperature",
      "Full-bodied red wine is best served around which temperature?",
      ["15 to 18 C", "20 to 22 C", "8 to 10 C", "4 to 6 C"], 0,
      "Room temperature is a phrase from unheated houses. Above about 18 C alcohol dominates and the wine loses definition."),
    Q("Service temperature",
      "Beaujolais and other light reds are often served how?",
      ["Lightly chilled, around 12 to 14 C", "At 20 C", "As cold as sparkling wine",
       "Warmed slightly above room temperature"], 0,
      "Low tannin and bright fruit take a chill well. Over-warm Gamay turns flabby."),
    Q("Service temperature",
      "Serving a white wine too cold has which effect?",
      ["It mutes aroma and flavour", "It increases perceived sweetness",
       "It softens acidity", "It has no effect"], 0,
      "Aromatics need warmth to volatilise. An expensive white poured from an ice bucket is often tasted at its worst."),
    Q("Service temperature",
      "Which fortified wine is conventionally served chilled?",
      ["Fino Sherry", "Vintage Port", "Tawny Port at cellar temperature",
       "Bual Madeira"], 0,
      "Fino and Manzanilla are served cold and drunk fresh, closer to a white wine than to the other fortifieds."),
    Q("Service temperature",
      "Why is an ice bucket filled with both ice and water rather than ice alone?",
      ["Water conducts heat away far faster than air between ice cubes",
       "It looks more attractive", "It stops the label peeling",
       "It prevents the wine freezing"], 0,
      "Ice alone touches only part of the bottle. Half water and half ice chills in a fraction of the time."),

    # ------------------------------------------- glassware and decanting (6)
    Q("Glassware and decanting",
      "Why is a wine glass tapered inward at the rim?",
      ["It concentrates aromas toward the nose", "It prevents spills",
       "It strengthens the glass", "It makes the pour look larger"], 0,
      "A bowl that narrows gathers the volatiles. It is also why a glass is filled to its widest point and no higher."),
    Q("Glassware and decanting",
      "A wine glass should be filled to roughly what level?",
      ["The widest part of the bowl at most", "The brim", "Three-quarters full",
       "One-tenth full"], 0,
      "Leaving air above the wine is what makes swirling possible. A full glass cannot be assessed."),
    Q("Glassware and decanting",
      "A forty-year-old red has thrown a heavy deposit. What is the decant chiefly achieving?",
      ["To separate the wine from its sediment", "To warm it quickly",
       "To add oxygen aggressively", "To remove tannin"], 0,
      "Old wine throws a deposit and is often fragile, so the decant is careful and served promptly. Aeration is the secondary consideration."),
    Q("Glassware and decanting",
      "A young Barolo is closed and grippy on opening. Why might you decant it?",
      ["To aerate it and soften the tannin", "To remove sediment",
       "To chill it", "To reduce its alcohol"], 0,
      "The opposite purpose from an old wine, and it may be poured vigorously and left to open for an hour or more."),
    Q("Glassware and decanting",
      "Why is a candle or light used beneath the neck when decanting?",
      ["To see sediment approaching the neck and stop pouring",
       "To warm the wine", "For ceremony alone", "To check the cork"], 0,
      "Any steady light works. The point is the moment the deposit reaches the shoulder, when pouring stops."),
    Q("Glassware and decanting",
      "Washing glassware with strongly scented detergent risks what?",
      ["Leaving residue that taints the wine's aroma", "Cracking the glass",
       "Dulling the colour", "Raising the serving temperature"], 0,
      "Glasses are best rinsed in very hot water and polished with a lint-free cloth. Detergent residue and cardboard smells both ruin a pour."),

    # ------------------------------------------------- opening and pouring (7)
    Q("Opening and pouring",
      "Where should the foil capsule be cut on a still wine bottle?",
      ["Below the lip of the bottle", "Above the lip", "It should be left in place",
       "At the base of the neck"], 0,
      "Cutting below the lip stops the wine touching foil on its way out. It is also tidier when the bottle is presented."),
    Q("Opening and pouring",
      "A sparkling wine bottle is opened by doing what?",
      ["Holding the cork still and turning the bottle", "Turning the cork briskly",
       "Levering the cork with a corkscrew", "Shaking then releasing quickly"], 0,
      "Turning the bottle gives control, and a thumb stays over the cork from the moment the cage is loosened. A sigh rather than a bang."),
    Q("Opening and pouring",
      "Why should a sparkling wine bottle never be pointed toward guests?",
      ["A cork can leave under considerable pressure and cause injury",
       "It is merely traditional", "It disturbs the sediment",
       "It warms the bottle"], 0,
      "The bottle holds around six atmospheres. Serious eye injuries happen every year."),
    Q("Opening and pouring",
      "A standard pour of still wine in a restaurant is roughly what?",
      ["About 150 ml, five ounces", "About 350 ml", "About 50 ml", "A full glass"], 0,
      "Five pours to a bottle at that size, which is how by-the-glass pricing is built."),
    Q("Opening and pouring",
      "Twisting the bottle slightly as the pour finishes achieves what?",
      ["It stops the last drop running down the bottle", "It aerates the wine",
       "It settles sediment", "It is required by law"], 0,
      "A small turn with a lifted neck. A serviette in the other hand covers what the turn misses."),
    Q("Opening and pouring",
      "If a cork breaks during extraction, what is the sound approach?",
      ["Reinsert the worm at an angle and extract the remainder carefully",
       "Push the cork into the bottle immediately", "Discard the bottle",
       "Shake the bottle to dislodge it"], 0,
      "Pushing it in risks fragments and a wine that cannot be presented. Failing that, decant through a fine strainer."),
    Q("Opening and pouring",
      "Why is the cork traditionally placed before the host?",
      ["So the host may inspect it if they wish", "It is used to reseal the bottle",
       "It proves the vintage", "It absorbs spills"], 0,
      "Largely ceremonial now, and smelling it tells you little a glass will not. A soaked or crumbling cork can hint at storage problems."),

    # ---------------------------------------- order of service and list (7)
    Q("Order of service and the list",
      "The bottle is presented to whom before opening?",
      ["The person who ordered it", "The eldest guest", "Whoever is nearest",
       "Nobody, it is opened at the sideboard"], 0,
      "The host confirms producer, wine and vintage before the foil is cut, which is the last moment an error can be caught cheaply."),
    Q("Order of service and the list",
      "After the host approves the wine, in what order are guests served?",
      ["The other guests first, the host last", "The host first, then the others",
       "Alphabetically", "Nearest to the door first"], 0,
      "The host tastes but is poured last. It is one of the clearest signals of trained service."),
    Q("Order of service and the list",
      "The host's initial taste is intended to establish what?",
      ["That the wine is sound, not that they like it", "That it suits their palate",
       "That the price is acceptable", "That it is the correct temperature"], 0,
      "Soundness is the question. A wine disliked but not faulty is a conversation rather than an automatic replacement."),
    Q("Order of service and the list",
      "A guest declares a wine faulty and you disagree. What is the correct response?",
      ["Replace it graciously and check the bottle away from the table",
       "Argue the point at the table", "Refuse and charge for it",
       "Insist the guest tastes it again"], 0,
      "Never litigate at the table. Tasting it afterwards tells you whether the case is worth raising with the supplier."),
    Q("Order of service and the list",
      "A guest brings their own bottle and the restaurant adds a fee. What is that fee called?",
      ["A fee for serving wine a guest has brought", "A charge for opening any bottle",
       "The cost of replacing corks", "A tax on imported wine"], 0,
      "It covers glassware, service and the lost sale. Policies vary widely and are worth stating plainly on the list."),
    Q("Order of service and the list",
      "Within a meal, wines are conventionally sequenced how?",
      ["Lighter before heavier, dry before sweet, young before old",
       "Heavier before lighter", "Sweet before dry", "In no fixed order"], 0,
      "Each wine should not be diminished by the one before it. The rule bends for a deliberate contrast, knowingly."),
    Q("Order of service and the list",
      "Recommending a wine well within a guest's stated budget achieves what?",
      ["It builds trust and usually returns more over time", "It reduces the bill unnecessarily",
       "It signals a poor list", "It is considered an insult"], 0,
      "Selling to the budget rather than above it is the durable strategy. A guest who feels handled does not come back."),
]
