"""Rank I rewrite — Tasting & Service (66 questions).

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py, to verify independence.

Openers varied from the start, and the constructions in lib.BANNED_TEMPLATES
avoided by construction rather than by later reframing.
"""

from lib import Q

CAT = "Tasting & Service"
SLUG = "r1-tasting-service"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("The deductive grid", 7),
    ("Sight", 6),
    ("Nose", 7),
    ("Palate", 8),
    ("Assessing structure", 6),
    ("Faults", 6),
    ("Service temperature", 6),
    ("Glassware and decanting", 6),
    ("Opening and pouring", 7),
    ("Order of service and the list", 7),
]

BANK = [
    # ------------------------------------------------- the deductive grid (7)
    Q("The deductive grid",
      "A systematic tasting method proceeds in which order?",
      ["Sight, nose, palate, conclusion", "Nose, sight, conclusion, palate",
       "Palate, sight, nose, conclusion", "Conclusion, sight, nose, palate"], 0,
      "The order matters because each stage constrains the next. Reaching a conclusion first and then hunting for evidence is the commonest way to taste badly."),
    Q("The deductive grid",
      "What is the purpose of tasting to a fixed grid rather than freely?",
      ["It forces every component to be assessed",
       "It shortens the tasting by letting you skip components you have already placed",
       "It guarantees the correct grape and origin once every box is filled in",
       "It removes the need for experience"], 0,
      "A grid stops you skipping the inconvenient components that do not fit the theory you have already formed. It is a discipline against your own guessing, and it settles nothing by itself."),
    Q("The deductive grid",
      "In a blind tasting conclusion, which elements are typically called?",
      ["Grape, origin and vintage range",
       "The producer and the single vineyard the wine came from",
       "The retail price and the importer on the back label",
       "The name of the winemaker and their training"], 0,
      "Grape, place and approximate age, argued from the evidence gathered. Naming the producer is a party trick rather than the exercise."),
    Q("The deductive grid",
      "Why should a taster describe rather than judge in the early stages?",
      ["Description gathers evidence; judgement ends the enquiry",
       "Judgement is forbidden by law", "Description is faster",
       "Only a certified palate is qualified to judge a wine's quality"], 0,
      "Saying good or bad closes the question prematurely. Saying pale ruby with a garnet rim leaves you somewhere to go, and no certificate is required to do it."),
    Q("The deductive grid",
      "Palate fatigue during a long tasting is best managed how?",
      ["Spitting, water and breaks between flights",
       "Swallowing more slowly so less alcohol reaches the palate",
       "Eating strongly flavoured food to reset the palate between flights",
       "Tasting only reds"], 0,
      "Alcohol accumulates and the palate dulls, so swallowing slowly changes nothing. Spitting is professional practice rather than modesty, and plain water between flights resets more than bread does."),
    Q("The deductive grid",
      "Ambient conditions can distort a tasting. Which is most disruptive?",
      ["Strong ambient smells", "A quiet room",
       "Natural daylight", "A white tablecloth"], 0,
      "The nose does most of the work, so competing aromas from perfume or cooking ruin an assessment. Daylight and a white surface are aids rather than distractions."),
    Q("The deductive grid",
      "Why is a white background used when assessing a wine's appearance?",
      ["It shows the wine's true colour and clarity",
       "A pale surface keeps the glass from warming under the lights",
       "It is required by the wine laws of most producing countries",
       "It reduces glare on the glass"], 0,
      "Colour read against a patterned or coloured surface is unreliable and comes back distorted. A tilted glass over white paper is the standard arrangement, adopted because it works rather than because anything obliges it."),

    # -------------------------------------------------------------- sight (6)
    Q("Sight",
      "The edge of a red has paled and browned while the core stays deep. What does that suggest?",
      ["Advancing age", "High alcohol", "Residual sugar", "The use of oak"], 0,
      "A young red runs to the edge with its core colour; an older one pales and browns at the rim. It is one of the more reliable visual clues."),
    Q("Sight",
      "As a red wine ages, its colour generally moves in which direction?",
      ["From purple through ruby and garnet toward tawny",
       "From tawny toward purple as pigment leaves the skins",
       "It stays where it started once the wine is in bottle",
       "From garnet toward green"], 0,
      "Anthocyanins polymerise and drop out over time, and nothing in a sealed bottle adds pigment back. Whites move the opposite way, deepening from pale straw toward gold and amber."),
    Q("Sight",
      "The tears or legs running down a glass indicate what?",
      ["Alcohol and glycerol content",
       "The overall quality of the wine",
       "Age", "Sweetness alone"], 0,
      "They are a surface-tension effect, useful as a rough alcohol signal and worthless as a quality one, despite the folklore that better wines run more slowly."),
    Q("Sight",
      "You pour a wine that is visibly cloudy in the glass. What should that prompt?",
      ["An unfiltered wine, or microbial spoilage",
       "High tannin",
       "A wine fined and filtered bright before it was bottled",
       "Extended oak ageing, which leaves fine lees suspended in the wine"], 0,
      "Deliberately unfiltered wines can be cloudy by intent, so haze prompts a question rather than a verdict. Confirm on the nose and palate. A wine polished bright on the bottling line is the case a hazy glass argues against, and a wine is racked clear off its barrel lees before bottling, so time in barrel is not the source of the haze."),
    Q("Sight",
      "Small crystals in the bottom of a bottle or on the cork are usually what?",
      ["Harmless tartrate crystals", "Fragments of glass from the bottling line",
       "Mould growing under the capsule", "Undissolved sugar left from sweetening"], 0,
      "Tartrates precipitate when a wine is chilled and are tasteless. They alarm guests, so a quiet explanation is part of the job."),
    Q("Sight",
      "A deep, opaque colour in a young red most reliably suggests what?",
      ["Thick-skinned grapes, a warm climate or a long maceration",
       "Great age, since red wine darkens steadily in bottle",
       "High acidity",
       "Low alcohol, since a lighter wine cannot carry a deep colour"], 0,
      "Colour reflects extraction, grape variety and a warm climate more than it reflects quality, and reds lose depth with age rather than gaining it. A pale wine may be a great Pinot Noir and a black one an ordinary Syrah."),

    # --------------------------------------------------------------- nose (7)
    Q("Nose",
      "A young unoaked white smells of lemon, green apple and elderflower. Those aromas are classed as what?",
      ["Primary, from the grape", "Secondary, from fermentation",
       "Tertiary, from bottle age", "Quaternary, from bottling"], 0,
      "Primary from the fruit, secondary from winemaking including fermentation and oak, tertiary from age. Sorting them is most of the deductive work."),
    Q("Nose",
      "Which aromas are classed as tertiary?",
      ["Those developed by bottle age and oxidative maturation",
       "Fresh citrus and green apple from a cool-climate vineyard",
       "Vanilla picked up from a new oak barrel",
       "Banana from carbonic maceration during fermentation"], 0,
      "Leather, mushroom and dried fruit are the usual markers, built by bottle age and by slow oxidation in barrel rather than by the barrel's own aroma, which is secondary. Their presence is the strongest evidence for calling an older vintage range."),
    Q("Nose",
      "Vanilla, coconut and sweet spice on the nose most often point to what?",
      ["New oak", "Botrytis", "Malolactic conversion", "High acidity"], 0,
      "Oak lactones and vanillin come from the barrel, while malolactic conversion runs to butter rather than vanilla. American oak tends to the coconut and dill end, French toward finer spice."),
    Q("Nose",
      "A buttery aroma in a white wine is most commonly attributed to what?",
      ["Malolactic conversion producing diacetyl",
       "New oak alone, since barrels give butter too",
       "Residual sugar", "Cold fermentation"], 0,
      "Diacetyl is the by-product, and a barrel contributes vanilla and spice rather than butter. Whether it is welcome is a style question, and many producers block malolactic to preserve tautness."),
    Q("Nose",
      "Why should a taster smell the wine before swirling as well as after?",
      ["The most volatile compounds show before agitation",
       "Swirling oxidises the wine past the point of useful assessment",
       "The ritual is traditional and tells the taster nothing",
       "It warms the wine"], 0,
      "The still nose catches the lightest, most fleeting compounds, and some faults announce themselves there first. Swirling then releases the heavier ones by increasing the surface area."),
    Q("Nose",
      "Aroma intensity is assessed independently of quality because what?",
      ["A restrained wine may be fine and a loud one ordinary",
       "Intensity cannot be measured",
       "Quality is decided on the palate alone, not on the nose",
       "Intensity always indicates age"], 0,
      "Keeping the two apart is the discipline. Many great wines are quiet, particularly when young or served too cold, and the nose contributes to a quality judgement without intensity settling it."),
    Q("Nose",
      "Fruit described as fresh rather than cooked or dried suggests what about origin?",
      ["A cooler climate or a younger wine",
       "A warmer climate, where longer hang time keeps the fruit crisp",
       "Extended barrel ageing, which preserves the fruit as it was picked",
       "High residual sugar holding the fruit fresh"], 0,
      "Fruit condition is one of the better climate clues: crisp and tart at the cool end, baked and jammy at the warm end. Time in barrel dries the fruit character rather than preserving it."),

    # ------------------------------------------------------------ palate (8)
    Q("Palate",
      "Which structural components are assessed on the palate?",
      ["Sweetness, acidity, tannin, alcohol and body", "Colour and clarity",
       "Aroma intensity alone",
       "Tannin and colour, with the other components left aside"], 0,
      "Each is judged separately before any conclusion about balance. Colour and clarity belong to the sight stage and cannot be tasted. Running the components together is how a high-alcohol wine gets called sweet."),
    Q("Palate",
      "Length, in tasting terms, refers to what?",
      ["How long the flavour persists",
       "How long the wine spent in barrel before bottling",
       "How long the bottle has aged before opening",
       "The length of time the bottle stays open"], 0,
      "Persistence is one of the more dependable quality markers, and it is measured in seconds after the wine has been swallowed or spat."),
    Q("Palate",
      "A wine described as balanced means what?",
      ["No single component dominates the others", "It has no tannin",
       "It is exactly half sweet and half dry", "It is inexpensive"], 0,
      "Balance is a relationship rather than a level: high acid can be balanced by high sugar, and high tannin by fruit and body."),
    Q("Palate",
      "Body, in tasting terms, describes what?",
      ["The wine's weight and texture in the mouth",
       "The depth of colour, which tracks how heavy a wine feels",
       "The alcohol reading on the label and nothing else",
       "The tannin level alone"], 0,
      "Alcohol, glycerol, sugar and extract all contribute, so no single figure captures it. Whole-mouth impression rather than a single measurable component, and a pale wine can be as weighty as a black one."),
    Q("Palate",
      "Perceived sweetness in a dry wine can be created by which component?",
      ["High alcohol or ripe fruit character", "High acidity", "Firm tannin",
       "Low temperature"], 0,
      "Alcohol reads faintly sweet and very ripe fruit reads sweeter still. A technically dry wine is regularly described as sweet for this reason."),
    Q("Palate",
      "Retronasal perception refers to what?",
      ["Aroma arriving from the back of the mouth",
       "Smelling the empty glass after the wine has been poured away",
       "Smelling the wine in the glass before it is swirled",
       "The sensation of tannin"], 0,
      "Much of what is called flavour is smell reaching the olfactory receptors from behind. It is why a blocked nose flattens food and wine alike."),
    Q("Palate",
      "Why do tasters draw air across the wine in the mouth?",
      ["It volatilises aromatics",
       "It cools the wine", "It removes tannin", "It reduces alcohol"], 0,
      "Air lifts the aromatic compounds off the liquid and up behind the palate, which is retronasal perception. Unattractive to watch and genuinely informative."),
    Q("Palate",
      "A wine that seems hollow in the middle is usually said to lack what?",
      ["Mid-palate fruit or concentration", "Acidity", "Alcohol", "Colour"], 0,
      "Attack and finish present, nothing between. It is a common shape in over-cropped or heavily manipulated wine."),

    # ------------------------------------------------ assessing structure (6)
    Q("Assessing structure",
      "Acidity is judged physically by which sensation?",
      ["Salivation at the sides of the tongue", "A drying grip on the gums",
       "Warmth at the back of the throat", "Weight on the tongue"], 0,
      "The mouth waters in response to acid, while warmth is the alcohol talking. Counting how long salivation continues is a practical way to rank two wines."),
    Q("Assessing structure",
      "Which wine component registers as touch rather than as a taste?",
      ["Tannin", "Acidity", "Sweetness", "Bitterness"], 0,
      "Astringency is touch rather than taste: tannin binding the lubricating proteins in saliva. It is why it builds across several sips."),
    Q("Assessing structure",
      "Alcohol is assessed by which sensation?",
      ["Warmth at the back of the mouth and throat", "Salivation",
       "A drying grip", "A metallic tang"], 0,
      "The burn is the clue, and it is easily confused with body. Very high alcohol also reads slightly sweet."),
    Q("Assessing structure",
      "Why is tannin best assessed after several sips rather than one?",
      ["It accumulates across sips",
       "It fades with repetition, so the first sip overstates it",
       "The first sip is always inaccurate whatever is being judged",
       "It changes the wine's temperature"], 0,
      "Astringency builds as saliva proteins are stripped, so a single sip understates it. A wine that seemed supple can turn firm by the third mouthful."),
    Q("Assessing structure",
      "Confusing tannin with acidity is a common error. What distinguishes them?",
      ["Tannin dries the mouth; acid makes it water",
       "Tannin is sweet; acid is bitter",
       "Tannin is felt only in white wine, where acid is absent",
       "There is no reliable difference"], 0,
      "Opposite physical responses, and while tannin is chiefly a red-wine component, acid is in every wine. Both can make a wine seem firm, which is where the confusion comes from."),
    Q("Assessing structure",
      "Serving temperature affects perceived structure in which way?",
      ["Cold accentuates acid and tannin",
       "Temperature changes aroma but leaves structure untouched",
       "Cold accentuates alcohol and warmth accentuates acid",
       "Warmth accentuates acidity"], 0,
      "Warmth does the reverse, pushing alcohol and body forward. Much of what is blamed on a wine is really a service fault, and the useful range is narrower than most people assume."),

    # ------------------------------------------------------------ faults (6)
    Q("Faults",
      "A wine smelling of wet cardboard, damp cellar and muted fruit is showing what?",
      ["Cork taint from TCA", "Volatile acidity", "Reduction", "Heat damage"], 0,
      "TCA strips fruit before it announces itself, so a merely dull wine may be lightly corked. It can come from cellar materials as well as cork."),
    Q("Faults",
      "Nail varnish and vinegar on the nose indicate which fault?",
      ["Volatile acidity", "Cork taint", "Reduction", "Tartrate instability"], 0,
      "Acetic acid with ethyl acetate. Trace levels add lift and are sometimes deliberate; past a threshold the wine is spoiled."),
    Q("Faults",
      "Struck match, rubber or drains on opening, often blowing off with air, suggests what?",
      ["Reduction", "Oxidation", "Cork taint", "Brettanomyces"], 0,
      "Sulphur compounds from a low-oxygen environment. Decanting or swirling frequently clears it, which distinguishes it from a permanent fault."),
    Q("Faults",
      "A white wine that is deep gold, flat and smelling of bruised apple is likely what?",
      ["Oxidised", "Reduced", "Corked", "Too cold"], 0,
      "Acetaldehyde and colour deepening. Deliberate in Sherry and Vin Jaune, a fault in an unfortified table wine."),
    Q("Faults",
      "Barnyard, sticking plaster and leather notes are usually attributed to what?",
      ["Brettanomyces", "Malolactic conversion", "New oak", "Botrytis"], 0,
      "A spoilage yeast. Opinion divides on trace levels, and at higher levels it flattens fruit and homogenises a range."),
    Q("Faults",
      "A pushed-up cork and a maderised, stewed character point to what?",
      ["Heat damage in storage or transit", "Cork taint, which lifts the cork as it develops",
       "Reduction from a ferment starved of oxygen",
       "Excessive filtration stripping the wine"], 0,
      "Wine expands when it gets hot and forces the cork. It is a shipping and storage failure rather than a winemaking one."),

    # ----------------------------------------------- service temperature (6)
    Q("Service temperature",
      "Sparkling wine is generally served within which range?",
      ["6 to 10 C", "12 to 14 C", "16 to 18 C", "2 to 4 C"], 0,
      "Cold holds the mousse and keeps the pressure manageable on opening. Fine vintage Champagne benefits from the warmer end."),
    Q("Service temperature",
      "Full-bodied red wine is best served around which temperature?",
      ["15 to 18 C", "20 to 22 C", "8 to 10 C", "4 to 6 C"], 0,
      "Room temperature is a phrase from unheated houses. Above about 18 C alcohol dominates and the wine loses definition."),
    Q("Service temperature",
      "Beaujolais and other light reds are often served how?",
      ["Lightly chilled, around 12 to 14 C", "At 20 C", "As cold as sparkling wine",
       "Warmed slightly above room temperature"], 0,
      "Low tannin and bright fruit take a chill well. Over-warm Gamay turns flabby."),
    Q("Service temperature",
      "Serving a white wine too cold has which effect?",
      ["It mutes aroma and flavour", "It increases perceived sweetness",
       "It softens acidity", "It has no effect"], 0,
      "Aromatics need warmth to volatilise. An expensive white poured from an ice bucket is often tasted at its worst."),
    Q("Service temperature",
      "Which fortified wine is conventionally served chilled?",
      ["Fino Sherry", "Vintage Port", "Tawny Port at cellar temperature",
       "Bual Madeira"], 0,
      "Fino and Manzanilla are served cold and drunk fresh, closer to a white wine than to the other fortifieds."),
    Q("Service temperature",
      "Why is an ice bucket filled with both ice and water rather than ice alone?",
      ["Water conducts heat away far faster than air",
       "It looks more attractive",
       "Water in the bucket stops the label soaking off the bottle",
       "Without water the wine would freeze against the ice"], 0,
      "Ice alone touches only part of the bottle and leaves air in the gaps. Half water and half ice chills in a fraction of the time, at the cost of a soaked label rather than a saved one."),

    # ------------------------------------------- glassware and decanting (6)
    Q("Glassware and decanting",
      "Why is a wine glass tapered inward at the rim?",
      ["It concentrates aromas toward the nose", "It prevents spills",
       "The narrower rim strengthens the glass against knocks",
       "It makes the pour look larger"], 0,
      "A bowl that narrows gathers the volatiles. It is also why a glass is filled to its widest point and no higher. A fine rim is the most fragile part of the glass, not the strongest."),
    Q("Glassware and decanting",
      "A wine glass should be filled to roughly what level?",
      ["The bowl's widest part", "The brim", "Three-quarters full",
       "One-tenth full"], 0,
      "Leaving air above the wine is what makes swirling possible, so the widest part of the bowl is a ceiling rather than a target. A full glass cannot be assessed."),
    Q("Glassware and decanting",
      "A forty-year-old red has thrown a heavy deposit. What is the decant chiefly achieving?",
      ["To separate the wine from its sediment",
       "To bring a cold cellar bottle up to serving temperature",
       "To drive oxygen through it and open it up quickly",
       "To remove tannin"], 0,
      "Old wine throws a deposit and is often fragile, so the decant is careful and served promptly. Hard aeration is the last thing it wants, and temperature is a side effect rather than the point."),
    Q("Glassware and decanting",
      "A young Barolo is closed and grippy on opening. Why might you decant it?",
      ["To aerate it and soften the tannin",
       "To remove the heavy deposit a young Barolo throws",
       "To chill it", "To reduce its alcohol"], 0,
      "The opposite purpose from an old wine, and it may be poured vigorously and left to open for an hour or more. A wine this young has thrown little worth separating."),
    Q("Glassware and decanting",
      "Why is a candle or light used beneath the neck when decanting?",
      ["To watch the sediment approach the shoulder",
       "To warm the wine gently as it passes the flame",
       "Purely for the ceremony of the occasion",
       "To inspect the cork for staining before pouring"], 0,
      "Any steady light works, and the flame is nowhere near the wine long enough to warm it. The point is the moment the deposit reaches the shoulder, when pouring stops."),
    Q("Glassware and decanting",
      "Washing glassware with strongly scented detergent risks what?",
      ["Residue that taints the aroma", "Cracking the glass",
       "Dulling the colour", "Raising the serving temperature"], 0,
      "Glasses are best rinsed in very hot water and polished with a lint-free cloth. Detergent residue and cardboard smells both ruin a pour."),

    # ------------------------------------------------- opening and pouring (7)
    Q("Opening and pouring",
      "Where should the foil capsule be cut on a still wine bottle?",
      ["Below the lip of the bottle", "Above the lip, so the foil stays neat",
       "It is left in place and the cork drawn through",
       "At the base of the neck"], 0,
      "Cutting below the lip stops the wine touching foil on its way out. It is also tidier when the bottle is presented."),
    Q("Opening and pouring",
      "A sparkling wine bottle is opened by doing what?",
      ["Holding the cork still and turning the bottle",
       "Turning the cork briskly while the bottle is held still",
       "Levering the cork with a corkscrew", "Shaking then releasing quickly"], 0,
      "Turning the bottle gives control, and a thumb stays over the cork from the moment the cage is loosened. A sigh rather than a bang."),
    Q("Opening and pouring",
      "Why should a sparkling wine bottle never be pointed toward guests?",
      ["A cork can leave under pressure and injure",
       "It is a point of table etiquette rather than of safety",
       "Pointing the bottle at the table disturbs its sediment",
       "It warms the bottle"], 0,
      "The bottle holds around six atmospheres. Serious eye injuries happen every year, which makes this a safety rule rather than a nicety."),
    Q("Opening and pouring",
      "A standard pour of still wine in a restaurant is roughly what?",
      ["About 150 ml", "About 350 ml", "About 50 ml", "A full glass"], 0,
      "Five pours to a bottle at that size, about five ounces each, which is how by-the-glass pricing is built."),
    Q("Opening and pouring",
      "Twisting the bottle slightly as the pour finishes achieves what?",
      ["It stops drips down the bottle", "It aerates the wine",
       "It settles sediment", "It is required by law"], 0,
      "A small turn with a lifted neck stops the last drop running down the label. A serviette in the other hand covers what the turn misses."),
    Q("Opening and pouring",
      "If a cork breaks during extraction, what is the sound approach?",
      ["Reinsert the worm at an angle",
       "Push the cork into the bottle immediately",
       "Discard the bottle and open another at once",
       "Shake the bottle until the fragment works loose"], 0,
      "Come in shallow and draw out the remainder carefully. Pushing it in risks fragments and a wine that cannot be presented; failing that, decant through a fine strainer."),
    Q("Opening and pouring",
      "Why is the cork traditionally placed before the host?",
      ["So the host may inspect it if they wish", "It is used to reseal the bottle",
       "It proves the vintage", "It absorbs spills"], 0,
      "Largely ceremonial now, and smelling it tells you little a glass will not. A soaked or crumbling cork can hint at storage problems."),

    # ---------------------------------------- order of service and list (7)
    Q("Order of service and the list",
      "The bottle is presented to whom before opening?",
      ["The person who ordered it", "The eldest guest", "Whoever is nearest",
       "Nobody, it is opened at the sideboard"], 0,
      "The host confirms producer, wine and vintage before the foil is cut, which is the last moment an error can be caught cheaply."),
    Q("Order of service and the list",
      "After the host approves the wine, in what order are guests served?",
      ["The other guests first, the host last",
       "The host first, since they ordered and approved the wine",
       "Alphabetically", "Nearest to the door first"], 0,
      "The host tastes but is poured last. It is one of the clearest signals of trained service."),
    Q("Order of service and the list",
      "The host's initial taste is intended to establish what?",
      ["That the wine is sound", "That the wine suits the host's own taste",
       "That the price is acceptable", "That it is the correct temperature"], 0,
      "Soundness is the question, not preference. A wine disliked but not faulty is a conversation rather than an automatic replacement."),
    Q("Order of service and the list",
      "A guest declares a wine faulty and you disagree. What is the correct response?",
      ["Replace it graciously", "Argue the point at the table",
       "Refuse the complaint and charge for the bottle",
       "Insist the guest tastes it again"], 0,
      "Never litigate at the table. Check the bottle away from it afterwards; that tells you whether the case is worth raising with the supplier."),
    Q("Order of service and the list",
      "A guest brings their own bottle and the restaurant adds a fee. What is that fee called?",
      ["A fee for serving wine a guest has brought",
       "A charge for opening any bottle on the list",
       "The cost of replacing corks", "A tax on imported wine"], 0,
      "It covers glassware, service and the lost sale, and it applies only to the bottle the guest carried in. Policies vary widely and are worth stating plainly on the list."),
    Q("Order of service and the list",
      "Within a meal, wines are conventionally sequenced how?",
      ["Light before heavy, dry before sweet",
       "Heavier before lighter, so the palate is opened early",
       "Sweet before dry, to clear the palate first",
       "In no fixed order"], 0,
      "Young before old as well. Each wine should not be diminished by the one before it, and the rule bends for a deliberate contrast, knowingly."),
    Q("Order of service and the list",
      "Recommending a wine well within a guest's stated budget achieves what?",
      ["It builds trust and usually returns more over time",
       "It reduces the bill and costs the room a returning guest",
       "It signals a poor list", "It is considered an insult"], 0,
      "Selling to the budget rather than above it is the durable strategy. A guest who feels handled does not come back."),
]
