"""Rank I rewrite - United States (61 questions).

Written from the syllabus below. The imported bank was not read while writing.

Openers are varied from the start and the constructions in lib.BANNED_TEMPLATES
are avoided by construction. Where a fact is a bare number, name or date, the
stem approaches it from a scenario rather than from the subject noun.
"""

from lib import Q

CAT = "United States"
SLUG = "r1-united-states"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Wine law and labels", 7),
    ("Napa Valley", 7),
    ("Sonoma and the North Coast", 6),
    ("Central Coast and inland California", 6),
    ("California grapes and history", 6),
    ("Oregon", 6),
    ("Washington", 6),
    ("New York and the Northeast", 5),
    ("Other states", 4),
    ("Climate and geography", 4),
    ("History and the trade", 4),
]

BANK = [
    # ------------------------------------------------ wine law and labels (7) -
    Q("Wine law and labels",
      "A bottle says Cabernet Sauvignon on the front label. Under federal rules, how much of that grape must be in the wine?",
      ["At least 75 percent", "At least 51 percent", "At least 85 percent", "All of it"], 0,
      "Federal law sets the varietal floor at 75 percent, so a quarter of the blend can be something else entirely. Several states, Oregon among them, hold their producers to a stricter figure."),
    Q("Wine law and labels",
      "A petition to draw the boundaries of a new American wine region is filed with which body?",
      ["The Alcohol and Tobacco Tax and Trade Bureau", "The Department of Agriculture",
       "The Food and Drug Administration", "The Environmental Protection Agency"], 0,
      "The TTB, part of the Treasury, evaluates the evidence for a distinctive growing area and grants the AVA. Petitions are usually brought by the growers themselves rather than by any government body."),
    Q("Wine law and labels",
      "A grower inside an AVA plants whatever variety he likes at whatever yield he likes and still puts the AVA name on the label. Why is that permitted?",
      ["An AVA fixes boundaries and sets no rule on grape or yield",
       "AVA rules bind only wineries that own more than fifty acres",
       "AVA rules govern yield but leave grape choice open",
       "He holds a federal exemption from the AVA rules"], 0,
      "This is the central difference from a European appellation, which typically dictates permitted varieties, maximum yields and often winemaking. An AVA sets no rule at all on which grape is planted or how heavily it is cropped; it is a statement about place and nothing else."),
    Q("Wine law and labels",
      "For a wine carrying an AVA on its label, a stated vintage must account for at least how much of the fruit?",
      ["95 percent", "85 percent", "75 percent", "All of it"], 0,
      "The figure is 95 percent for an AVA, but only 85 percent when the appellation given is a state or a county. The tighter the place claim, the tighter the vintage rule."),
    Q("Wine law and labels",
      "The words Estate Bottled appear across the bottom of a label. What does that guarantee?",
      ["The winery sits inside the named AVA and grew, made and bottled the wine there",
       "The wine came from one single vineyard, wherever the winery happens to sit",
       "The estate has been in the same family for at least fifty years",
       "The wine was bottled by hand rather than on a line"], 0,
      "Estate Bottled is one of the few American label terms with real legal weight: the fruit has to come off land the winery owns or controls inside that same AVA, and the wine must be crushed, aged and bottled on the premises. Reserve, by contrast, means whatever the producer wants it to mean."),
    Q("Wine law and labels",
      "Which state can claim the very first AVA ever approved, granted in 1980?",
      ["Missouri", "California", "New York", "Oregon"], 0,
      "Augusta, on the Missouri River, was approved months ahead of Napa Valley. Missouri had a large and serious wine industry in the nineteenth century, which is easy to forget now."),
    Q("Wine law and labels",
      "A label reads Russian River Valley. At minimum, how much of the fruit came from inside those boundaries?",
      ["85 percent", "75 percent", "95 percent", "All of it"], 0,
      "An AVA name requires 85 percent, while federal law asks only 75 percent for a county or state name. California is stricter than that federal floor, so a Sonoma County wine needs 75 percent Sonoma fruit but must be 100 percent California grown."),

    # -------------------------------------------------------- napa valley (7) -
    Q("Napa Valley",
      "At a 1976 tasting in Paris a California red finished ahead of the Bordeaux field. Which producer made it?",
      ["Stag's Leap Wine Cellars", "Chateau Montelena", "Robert Mondavi Winery",
       "Beaulieu Vineyard"], 0,
      "Stag's Leap Wine Cellars took the red flight and Chateau Montelena the white, both with 1973s. The result did more for California's international standing than any amount of marketing could have."),
    Q("Napa Valley",
      "More Napa acreage goes to one variety than to any other. Which is it?",
      ["Cabernet Sauvignon", "Chardonnay", "Merlot", "Zinfandel"], 0,
      "Cabernet Sauvignon takes roughly half of Napa's planted area and drives its reputation and its prices. Chardonnay is a distant second."),
    Q("Napa Valley",
      "Cool air off San Pablo Bay reaches the southern end of the valley. Which pair of grapes does that suit?",
      ["Pinot Noir and Chardonnay", "Cabernet Sauvignon and Petit Verdot",
       "Zinfandel and Petite Sirah", "Riesling and Gewurztraminer"], 0,
      "Los Carneros straddles the Napa and Sonoma county line at the water's edge and is cold by Napa standards. Much of California's better sparkling base wine comes from there."),
    Q("Napa Valley",
      "A Napa vineyard planted high enough to sit clear of the fog that fills the valley below is most likely in which AVA?",
      ["Howell Mountain", "Oakville", "Yountville", "Oak Knoll District"], 0,
      "Howell Mountain vineyards must lie above 1,400 feet, which puts them above the fog line. Mountain fruit tends to be smaller berried and more tannic than fruit from the valley floor."),
    Q("Napa Valley",
      "Which pair of appellations sit side by side on the valley floor immediately north of Yountville?",
      ["Oakville and Rutherford", "Howell Mountain and Mount Veeder",
       "Carneros and Coombsville", "Calistoga and Chiles Valley"], 0,
      "The Oakville and Rutherford benches are gravelly, well drained alluvial fans and form the historic heartland of Napa Cabernet. Rutherford dust is the old shorthand for the dusty tannin found there."),
    Q("Napa Valley",
      "In 1968 Napa County passed a measure that has shaped the valley ever since. What did it do?",
      ["It zoned the valley floor for agriculture",
       "It banned irrigation on the valley floor",
       "It capped yields for every vineyard in the county",
       "It required all Napa wine to be estate bottled"], 0,
      "The Agricultural Preserve was the first of its kind in the country and set a large minimum parcel size, which blocked subdivision of the valley floor. Without it the valley floor would very likely be housing today."),
    Q("Napa Valley",
      "A grower standing on Atlas Peak looks west across the valley floor to Mount Veeder on the opposite skyline. Napa is walled in by which two ranges?",
      ["The Mayacamas and the Vaca", "The Sierra Nevada and the Mayacamas",
       "The Santa Lucia and the Gabilan", "The Cascades and the Coast Range"], 0,
      "The Mayacamas divide Napa from Sonoma on the west and carry Mount Veeder and Spring Mountain, while the Vaca range on the east carries Atlas Peak and Howell Mountain. The valley narrows steadily as it runs north toward Calistoga."),

    # ------------------------------------------ sonoma and the north coast (6) -
    Q("Sonoma and the North Coast",
      "Fog funnels in off the Pacific each night and burns off late the following morning, which has made one Sonoma appellation a byword for Pinot Noir. Which?",
      ["Russian River Valley", "Alexander Valley", "Knights Valley", "Dry Creek Valley"], 0,
      "The fog buys several extra hours of cool each day, stretching the ripening period. That long, slow hang is what growers there are really farming for."),
    Q("Sonoma and the North Coast",
      "Old head-trained bush vines of Zinfandel are the signature of which Sonoma appellation?",
      ["Dry Creek Valley", "Green Valley of Russian River Valley", "Carneros",
       "Sonoma Coast"], 0,
      "Dry Creek's warm days and gravelly benchland suit Zinfandel, and some plantings there date back over a century. Old vines yield little but concentrate flavour."),
    Q("Sonoma and the North Coast",
      "Which Sonoma appellation, warmer and further from the ocean, has built its name on rounded Cabernet Sauvignon?",
      ["Alexander Valley", "Russian River Valley", "Green Valley of Russian River Valley",
       "Petaluma Gap"], 0,
      "Alexander Valley runs north from Healdsburg and sits beyond the reach of most of the fog. Its Cabernet tends to be softer and earlier drinking than Napa's."),
    Q("Sonoma and the North Coast",
      "A cool valley in Mendocino County, open to the Pacific at its western end, has become a source of traditional method sparkling wine. Name it.",
      ["Anderson Valley", "Alexander Valley", "Redwood Valley", "Potter Valley"], 0,
      "Anderson Valley is cold enough to ripen base wine at low sugar and high acid, which is exactly what sparkling production wants. It is also strong territory for Pinot Noir and aromatic whites."),
    Q("Sonoma and the North Coast",
      "Which North Coast county lies inland and north of Napa, high around a large lake, and contains the Red Hills AVA?",
      ["Lake County", "Mendocino County", "Solano County", "Yolo County"], 0,
      "Lake County sits at elevation around Clear Lake, with volcanic soils and very clear air. Its Cabernet Sauvignon and Sauvignon Blanc are increasingly bottled under their own labels rather than sold off."),
    Q("Sonoma and the North Coast",
      "Sonoma, Napa, Mendocino and Lake counties all sit inside which umbrella appellation?",
      ["North Coast", "Central Coast", "Northern California", "Sierra Foothills"], 0,
      "North Coast is a large multi-county AVA that also takes in Marin and Solano. Producers reach for it when a blend crosses county lines."),

    # ----------------------------- central coast and inland california (6) -----
    Q("Central Coast and inland California",
      "In one California county the coastal mountains run east to west rather than north to south, opening the valleys straight at the ocean. What does that do?",
      ["Cold marine air pours far inland, so the coastal end is the cold end",
       "It blocks ocean influence and leaves the valleys uniformly hot",
       "It doubles the annual rainfall", "It shelters the vineyards from wind entirely"], 0,
      "The transverse ranges of Santa Barbara County create a sharp temperature gradient over a short distance. Pinot Noir grows at the western end while Bordeaux varieties ripen at the eastern end."),
    Q("Central Coast and inland California",
      "Which Santa Barbara appellation occupies the cold western end of the Santa Ynez Valley and is planted overwhelmingly to Pinot Noir and Chardonnay?",
      ["Sta. Rita Hills", "Happy Canyon of Santa Barbara", "Ballard Canyon",
       "Alisos Canyon"], 0,
      "Sta. Rita Hills takes the full force of the marine air coming through the gap. Happy Canyon, further east and much warmer, grows Cabernet Sauvignon and Sauvignon Blanc instead."),
    Q("Central Coast and inland California",
      "A warm inland appellation in San Luis Obispo County, known for a very wide swing between day and night temperatures, has made its name with Zinfandel and Rhone varieties. Which?",
      ["Paso Robles", "Edna Valley", "Arroyo Seco", "Chalone"], 0,
      "Paso Robles is hot by day and cools sharply after dark, which keeps acidity in place while sugars build. It is large and varied enough to have been divided into a set of sub-appellations."),
    Q("Central Coast and inland California",
      "Which county's Salinas Valley draws such a reliable afternoon wind off the bay that growers plan the vineyard around it?",
      ["Monterey", "Napa", "Amador", "Lake"], 0,
      "The valley opens directly onto Monterey Bay, and the wind can shut the vines down in the afternoon. The Santa Lucia Highlands sit on terraces above the valley floor and are a leading source of Pinot Noir."),
    Q("Central Coast and inland California",
      "Warm, flat and dependent on irrigation, the Central Valley supplies most of the country's everyday wine. Which of these appellations lies within it?",
      ["Lodi", "Sta. Rita Hills", "Anderson Valley", "Howell Mountain"], 0,
      "Lodi sits at the northern end, cooled a little by air off the Sacramento Delta. Alongside its volume production it holds a remarkable stock of old Zinfandel vines."),
    Q("Central Coast and inland California",
      "Gold Rush miners planted vines in the hills east of Sacramento, and some of those old Zinfandel plantings still stand. Which region is this?",
      ["The Sierra Foothills", "The Santa Cruz Mountains", "Livermore Valley",
       "The Napa Valley"], 0,
      "Amador County and El Dorado are the best known parts, farming at elevation on granitic soils. The vineyards survived largely because the area was too remote to be worth redeveloping."),

    # -------------------------------------- california grapes and history (6) -
    Q("California grapes and history",
      "DNA analysis matched California's Zinfandel to an old Croatian variety and to which Italian grape?",
      ["Primitivo", "Sangiovese", "Aglianico", "Barbera"], 0,
      "Zinfandel, Primitivo and the Croatian Tribidrag are one variety under three names. The Croatian population is the original, and the vine reached America by way of a nineteenth-century nursery."),
    Q("California grapes and history",
      "A pale, off-dry pink wine made from a black grape became a runaway commercial success in the 1980s. What was it called?",
      ["White Zinfandel", "Blush Merlot", "Vin Gris de Cabernet", "Rose of Mission"], 0,
      "Sutter Home's version began with a fermentation that stopped early and left sugar behind. Its enormous sales are the reason a great many old Zinfandel vineyards were never pulled out."),
    Q("California grapes and history",
      "Spanish missionaries brought north the first wine grape to be planted widely in California. What is it known as?",
      ["The Mission grape", "Zinfandel", "Palomino", "Concord"], 0,
      "The Mission grape is the Spanish Listan Prieto, carried up from Mexico with the mission chain. It makes rather thin wine and survives now mostly as a curiosity and in some old field blends."),
    Q("California grapes and history",
      "A dark, tannic California red sold for generations as Petite Sirah turns out to be which variety?",
      ["Durif", "Syrah", "Mourvedre", "Carignan"], 0,
      "Durif was bred in France in the nineteenth century from Syrah and Peloursin. It gives inky colour and heavy tannin, and old field blends often carry it interplanted with Zinfandel."),
    Q("California grapes and history",
      "A California producer blends Cabernet Sauvignon, Merlot and Cabernet Franc, with no one grape reaching 75 percent. Which trademarked term may go on the label?",
      ["Meritage", "Claret", "Cuvee", "Reserve"], 0,
      "The term was coined so that Bordeaux-style blends had a name when no single variety could legally be printed. Reserve, by contrast, is unregulated in the United States and means nothing in law."),
    Q("California grapes and history",
      "Thousands of acres of Napa and Sonoma vineyard had to be torn out and replanted through the late 1980s and 1990s. What forced it?",
      ["Phylloxera overcame the usual rootstock",
       "A statewide ban on vineyard irrigation", "An outbreak of Pierce's disease",
       "A single catastrophic frost"], 0,
      "AXR-1, the rootstock planted almost everywhere through the 1970s, proved not to resist the louse it was supposed to withstand. The replanting was ruinously expensive but did let growers rethink spacing, clones and varieties from scratch."),

    # ------------------------------------------------------------- oregon (6) -
    Q("Oregon",
      "More than half of Oregon's vineyard acreage is given to a single red grape. Which one?",
      ["Pinot Noir", "Cabernet Sauvignon", "Syrah", "Zinfandel"], 0,
      "Pinot Noir dominates the state, and the Willamette Valley in particular. Pinot Gris is the leading white by some distance."),
    Q("Oregon",
      "In 1965 a grower planted Pinot Noir in the Willamette Valley against the advice of nearly everyone. Which winery did he go on to found?",
      ["The Eyrie Vineyards", "Domaine Drouhin Oregon", "Ponzi Vineyards",
       "Adelsheim Vineyard"], 0,
      "David Lett judged the valley's latitude and cool, damp climate closer to Burgundy than California was. Within twenty years Burgundian houses were buying land nearby."),
    Q("Oregon",
      "Oregon holds its producers to a varietal minimum stricter than federal law demands. What is the figure?",
      ["90 percent", "75 percent", "85 percent", "100 percent"], 0,
      "The federal floor is 75 percent, but Oregon requires 90 for most varieties. A listed group, largely Bordeaux and Rhone grapes that are traditionally blended, is exempted at 75."),
    Q("Oregon",
      "Red volcanic soil known as Jory is the calling card of which Willamette Valley sub-appellation?",
      ["Dundee Hills", "Yamhill-Carlton", "Ribbon Ridge", "McMinnville"], 0,
      "Jory is weathered basalt, iron rich and free draining. Yamhill-Carlton by contrast sits on ancient marine sedimentary soils, and growers argue endlessly about what each does to the wine."),
    Q("Oregon",
      "What shelters the Willamette Valley from the full weight of Pacific storms?",
      ["The Coast Range", "The Cascade Range on its eastern side",
       "The Columbia River", "The Siskiyou Mountains"], 0,
      "The Coast Range stands between the valley and the Pacific and takes the brunt of the weather, while the Cascades on the eastern side hold back continental extremes. Gaps such as the Van Duzer Corridor let cool ocean air slip through."),
    Q("Oregon",
      "Rogue and Umpqua Valleys lie in the south of the state. How do they differ from the Willamette?",
      ["They are warmer and drier, and suit Syrah",
       "They are colder and plant almost nothing but Riesling",
       "They sit at sea level directly on the coast",
       "They lie east of the Cascades in true desert"], 0,
      "Southern Oregon sits in a warmer, more sheltered pocket of country, where Syrah, Tempranillo and the Bordeaux varieties all ripen. The wines look nothing like the Pinot Noir the state is known for."),

    # --------------------------------------------------------- washington (6) -
    Q("Washington",
      "Almost all of Washington's vineyards sit east of a range that wrings the rain out of Pacific storms. Which range?",
      ["The Cascades", "The Coast Range", "The Blue Mountains", "The Olympics"], 0,
      "Seattle's reputation for rain belongs to the western side. Cross the Cascades and the same latitude becomes near desert, which is where the vines are."),
    Q("Washington",
      "Parts of eastern Washington see under ten inches of rain in a year. What does that oblige growers to do?",
      ["Irrigate what they plant there",
       "Harvest in the spring", "Plant hybrids rather than vinifera",
       "Give up trellising altogether"], 0,
      "Water is delivered by canal and drip line, so the grower decides how much the vine gets and when. That hands them precise control over vine vigour, and being able to withhold water is a tool rather than merely a chore."),
    Q("Washington",
      "Yakima Valley, Walla Walla Valley and Red Mountain all sit inside which larger appellation?",
      ["Columbia Valley", "Puget Sound", "Willamette Valley", "Snake River Valley"], 0,
      "Columbia Valley is the vast umbrella covering most of the state's plantings, and Walla Walla Valley is one of the nested AVAs inside it, reaching across the state line into Oregon. Puget Sound, Columbia Gorge and Lewis-Clark Valley lie outside Columbia Valley altogether."),
    Q("Washington",
      "One Washington appellation lies west of the Cascades, cool and damp enough that only early-ripening varieties succeed. Which?",
      ["Puget Sound", "Horse Heaven Hills", "Wahluke Slope", "Rattlesnake Hills"], 0,
      "Puget Sound is the state's wet-side exception, tiny by comparison with the east. Madeleine Angevine and Siegerrebe are the sorts of grapes that will ripen there."),
    Q("Washington",
      "Which small, warm Washington appellation has built its name on dense and firmly tannic Cabernet Sauvignon?",
      ["Red Mountain", "Lake Chelan", "Ancient Lakes of Columbia Valley",
       "Naches Heights"], 0,
      "Red Mountain is a modest south-facing slope with high heat and poor soils, and its fruit is in demand across the state. Cabernet Sauvignon and Merlot lead Washington's red plantings overall."),
    Q("Washington",
      "Ice-age floods repeatedly tore down the Columbia basin, stripping soil away and dumping gravel and silt. Whose vineyard soils were formed this way?",
      ["Eastern Washington's", "The Finger Lakes'", "Napa Valley's",
       "The Santa Ynez Valley's"], 0,
      "The Missoula Floods left the sandy, gravelly ground the region farms today. Those free-draining sands are hostile to phylloxera, which is why a great many Washington vines are still own-rooted."),

    # -------------------------------------- new york and the northeast (5) ----
    Q("New York and the Northeast",
      "Deep glacial lakes keep vines alive through winters that would otherwise kill them, and one white grape has become the region's calling card. Which grape?",
      ["Riesling", "Chardonnay", "Viognier", "Albarino"], 0,
      "The Finger Lakes are deep enough to hold heat well into winter and to slow the worst of the cold on the slopes above them. Riesling handles the cold and shows the site clearly."),
    Q("New York and the Northeast",
      "Which New York growing region is thoroughly maritime, sits east of the city, and favours Merlot and Cabernet Franc?",
      ["Long Island", "The Finger Lakes", "The Hudson River Region",
       "The Niagara Escarpment"], 0,
      "Water on three sides gives the North Fork a long, mild autumn, and Merlot in particular struggles to ripen in the colder inland regions. Cabernet Franc is hardier and is in fact the leading red vinifera of the Finger Lakes."),
    Q("New York and the Northeast",
      "Concord, Catawba and Niagara descend from which grape species?",
      ["Vitis labrusca", "Vitis vinifera", "Vitis rotundifolia", "Vitis berlandieri"], 0,
      "Labrusca is native to North America and gives the pungent aroma usually called foxy. Most of the crop goes to juice, jelly and sweet wine rather than to dry table wine."),
    Q("New York and the Northeast",
      "Vidal Blanc and Seyval Blanc turn up wherever winters are brutal. What are they?",
      ["French-American hybrid grapes",
       "Clones of Chardonnay", "Native American species", "Phylloxera-resistant rootstocks"], 0,
      "Hybrids cross vinifera with American species to buy the cold hardiness and disease resistance that vinifera lacks. Vidal Blanc's thick skin and high acidity also make it the workhorse grape of North American icewine."),
    Q("New York and the Northeast",
      "Vinifera was thought unplantable in the Finger Lakes until a researcher proved otherwise in the middle of the twentieth century. What was his insight?",
      ["Grafting vinifera onto a cold-hardy rootstock",
       "Planting only on flat ground below the lakes",
       "Picking everything before the end of August",
       "Abandoning vinifera in favour of hybrids"], 0,
      "Konstantin Frank had worked with vines in a far colder climate and knew the rootstock was the limiting factor: the right one let vinifera come through the winter alive. New York's vinifera industry descends directly from that argument."),

    # -------------------------------------------------------- other states (4) -
    Q("Other states",
      "Humid summers and Viognier make an unlikely pair, yet one East Coast state has built its modern reputation on that grape and on Cabernet Franc. Which state?",
      ["Virginia", "Texas", "Michigan", "Idaho"], 0,
      "Virginia's problem is humidity and its consequent disease pressure rather than cold. Thomas Jefferson tried and failed to grow vinifera at Monticello two centuries before it worked."),
    Q("Other states",
      "Norton, a red variety descended from a native American species, is the signature grape of which state?",
      ["Missouri", "Oregon", "Arizona", "Vermont"], 0,
      "Norton shrugs off humidity and cold that would destroy vinifera. German settlers built a substantial Missouri wine industry on it long before Prohibition closed it down."),
    Q("Other states",
      "Most of the Texas grape crop is grown on a high, flat plateau up near Lubbock. Which appellation is that?",
      ["Texas High Plains", "Texas Hill Country", "Escondido Valley", "Bell Mountain"], 0,
      "Elevation of around three thousand feet buys the cold nights the rest of the state lacks. Hill Country has more wineries and more visitors, but the High Plains grows the fruit."),
    Q("Other states",
      "Two narrow peninsulas reaching out into a Great Lake are the heart of one state's fine-wine production. Which state?",
      ["Michigan", "Wisconsin", "Minnesota", "Ohio"], 0,
      "Old Mission and Leelanau are almost surrounded by water, which delays budbreak in spring and holds off frost in autumn, and Riesling and other cool-climate whites do best there. Most of Michigan's acreage is actually Concord and Niagara juice grapes away to the south-west."),

    # ------------------------------------------------- climate and geography (4)
    Q("Climate and geography",
      "Hot interior air rises and pulls cold marine air in over a chilly ocean current. Which everyday feature of California vineyards does that produce?",
      ["Summer fog that cools the coastal valleys", "Hail through August",
       "Monsoon rain at harvest", "Deep frost on the valley floor in July"], 0,
      "The California Current chills the air sitting above it, and wherever the coastal hills have a gap that air runs inland. It is the reason cool-climate grapes succeed at so warm a latitude."),
    Q("Climate and geography",
      "Nights in many western American vineyards fall away sharply after very hot days. Why does that matter in the glass?",
      ["Cool nights hold the acidity in place",
       "Cool nights stop the vine from budding", "Cool nights ferment the fruit on the vine",
       "Cool nights raise tannin in white grapes only"], 0,
      "The hot days build sugar and colour while the cool nights keep the acidity, so a wide diurnal swing lets a grower reach full ripeness without the wine going flat and flabby. Elevation and marine air are the two usual sources of it."),
    Q("Climate and geography",
      "Eastern Washington lies a little further north than Bordeaux does. What does that latitude give the vineyards?",
      ["Longer daylight through midsummer", "Cooler daytime temperatures in July",
       "Considerably higher rainfall", "A longer growing season than Bordeaux enjoys"], 0,
      "The extra daylight helps drive ripeness through a short, intense season. The cold desert nights that follow those long days are what keep the acidity."),
    Q("Climate and geography",
      "Why is drip irrigation routine across the American West but tightly restricted in many European appellations?",
      ["Much of the West cannot grow vines without water, and no appellation rule bars it",
       "American vine varieties need more water than European ones",
       "European growers dry-farm purely by preference",
       "Federal law in the United States requires vineyards to be irrigated"], 0,
      "Rainfall in eastern Washington or the Central Valley simply will not carry a crop. European appellation law has traditionally treated irrigation as a way of inflating yields."),

    # -------------------------------------------------- history and the trade (4)
    Q("History and the trade",
      "National Prohibition ran from 1920 to 1933. Which allowance kept a good many vineyards in the ground?",
      ["Sacramental wine and limited home winemaking",
       "Licences to export wine to Canada", "Medicinal alcohol sold through pharmacies alone",
       "Nothing; every commercial vineyard was uprooted"], 0,
      "Churches could still buy sacramental wine and households could make a set quantity at home, so shipping grapes east became the business. Thick-skinned varieties survived the rail journey best, which is why finer grapes were often pulled out for them."),
    Q("History and the trade",
      "After Repeal, the sale of alcohol in the United States was reorganised into what structure?",
      ["A three-tier system of producer, wholesaler and retailer",
       "A state monopoly in every state", "Direct producer-to-consumer sales only",
       "A two-tier system of producer and retailer"], 0,
      "Producers generally must sell to wholesalers, who sell on to retailers and restaurants. The rules vary state by state, which is why a wine easy to buy in one state can be unobtainable in the next."),
    Q("History and the trade",
      "Robert Mondavi coined a name for barrel-aged Sauvignon Blanc in the 1960s, and other wineries then borrowed it. What is the term?",
      ["Fume Blanc", "Blanc de Noirs", "Sauvignon Reserve", "Chenin Fume"], 0,
      "Fume Blanc is a federally approved synonym for Sauvignon Blanc, so the 75 percent varietal minimum applies to it, but no law requires the oak the name implies. The renaming rescued a grape that was then selling poorly in California."),
    Q("History and the trade",
      "European vineyards were rescued from phylloxera in the nineteenth century by what American contribution?",
      ["Native American vines as rootstock",
       "American pesticides applied to the soil", "American hybrid wine grapes",
       "American irrigation techniques"], 0,
      "Vitis riparia, rupestris and berlandieri tolerate the root louse where vinifera cannot, so vinifera is grafted onto them. The louse had reached Europe on American vines in the first place, which is the irony of the fix."),
]
