"""Rank I rewrite - Winemaking Techniques (50 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing.

This category is the vocabulary of the cellar, not the process. Rank I's
Viticulture & Winemaking already owns how a white is made, how a red is made and
how a sparkling wine is made, and it defines carbonic maceration, saignee,
batonnage and extended maceration in those terms. What is left, and what is
written here, is the NAMED INTERVENTION and what it does to the wine a guest will
taste: what delestage achieves that a pump-over cannot, why a cold soak is held
cold, what a cellar gains by keeping twenty lots apart. A student who works
through it should be able to hear an operation named on a tech sheet or by a
grower and say what changed in the glass because of it.

The running order follows the wine: the fruit before it ferments, the cap, the
extraction decisions, the corrections to must and wine, the yeast, the bacteria
and the lees, then the vessel, the oxygen, the clarification and finally the
press and the blend.

Where a term already belongs to another category as an answer - soutirage and
ouillage and egg white to Rank II Bordeaux, sur lie to the Loire, foudre to the
Rhone, talha to Portugal, mutage to Dessert & Sweet Wines - it appears here only
as a distractor or not at all. Every stem opener is distinct, no stem leads with
the subject noun where the subject is the answer, and the constructions in
lib.BANNED_TEMPLATES are avoided by design.
"""

from lib import Q

CAT = "Winemaking Techniques"
SLUG = "r1-winemaking-techniques"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Before the ferment begins", 5),
    ("Working the cap", 5),
    ("Extraction, colour and maceration", 5),
    ("Adjusting the must and the wine", 5),
    ("Yeast and the ferment", 5),
    ("Malolactic and the lees", 5),
    ("Vessels and what they give", 5),
    ("Oxygen, given and withheld", 5),
    ("Clarifying and stabilising", 5),
    ("Pressing, blending and the finished wine", 5),
]

BANK = [
    # ------------------------------------------ before the ferment begins (5) --
    Q("Before the ferment begins",
      "A rotating perforated drum with paddles inside throws bunches against its wall, the berries drop through the holes and the woody frames travel out of the far end. Which cellar operation is that machine performing?",
      ["Destemming", "Pressing", "Fining", "Racking"], 0,
      "Taking the stalks off removes a green, bitter element and hands the winemaker the decision of how much stem character the wine gets, rather than accepting whatever the bunch happened to bring. Crushing is a separate action entirely, and a good machine can strip every stem without breaking a single berry."),
    Q("Before the ferment begins",
      "Crushed black grapes are held at eight degrees for four days and the yeast are kept from starting. What is chiefly being drawn out of the skins in that window?",
      ["Colour and aroma, with little tannin",
       "Tannin and structure, with little colour",
       "Sugar out of the pulp inside the berry",
       "Sharp acidity out of the seeds"], 0,
      "Grape pigment dissolves readily in water while tannin needs alcohol to come out in quantity, so a cold soak loads colour and fruit aroma without hardening the wine. There is no alcohol in the vat yet to defend it, which is why the step is run cold and under a protective gas."),
    Q("Before the ferment begins",
      "Freshly pressed white juice is left overnight in a chilled tank and the bright fraction is drawn off a sludge of pulp and skin fragments in the morning. What is that step called?",
      ["Debourbage", "Delestage", "Remontage", "Remuage"], 0,
      "Fermenting very dirty juice gives a coarse wine that can turn bitter and sulphurous, so the heavy solids are dropped out first. A little cloudiness is left on purpose, because juice cleaned absolutely spotless lacks the nutrients the yeast need and can struggle to finish."),
    Q("Before the ferment begins",
      "Bunches travel along a vibrating belt where hands pull out shrivelled berries, leaves and anything mouldy before the crusher. Which flaw is that work preventing, given that nothing later in the cellar removes it cleanly?",
      ["Green and mouldy flavours carried in on the fruit",
       "Cloudiness in the young wine, which no filter fully clears",
       "Tartrate crystals dropping out in the bottle later",
       "A protein haze appearing in warm weather"], 0,
      "A sorting table is the cheapest quality tool in the building because taint travels forward: a single handful of mouldy fruit marks a whole vat, and the treatments that chase the flavour back out strip the wine's own fruit along with it. Optical sorters do the same job by camera and air jet, fast enough to keep up with a machine harvest."),
    Q("Before the ferment begins",
      "A white must sits stubbornly cloudy for two days, so the winemaker doses it with a preparation that breaks down the gum holding the fine particles in suspension. What has been added?",
      ["A pectolytic enzyme", "Extra sulphur dioxide", "Tartaric acid", "A cultured yeast"], 0,
      "Pectin is a natural gum in the grape that keeps solids afloat, and the enzyme cuts it so they fall within hours instead of days. The same preparations are used to raise the yield at the press and to help colour come out of red skins."),

    # ------------------------------------------------------ working the cap (5) --
    Q("Working the cap",
      "A cellar hand stands on a plank above an open wooden vat and pushes the floating raft of skins under with a wooden plunger. Which French term names that?",
      ["Pigeage", "Remontage", "Foulage", "Remuage"], 0,
      "Working by hand or by foot gives a soft, unhurried extraction, and the operator can feel how much the cap will give up, which is why it survives in cellars making delicate reds. The drawbacks are heat, the carbon dioxide sitting over the vat and the labour of repeating it three times a day."),
    Q("Working the cap",
      "Wine is drawn from a valve at the base of a red fermenter and sprayed back over the skins through a hose. Beyond wetting the cap, what does that circulation supply?",
      ["A measured dose of oxygen for the yeast",
       "Sugar to restart a ferment that has slowed",
       "A steady fall in the wine's alcohol",
       "The carbon dioxide that protects the vat"], 0,
      "Yeast need a little oxygen early on to build healthy cell membranes and carry the sugar all the way down, and splashing wine through air is how a red ferment gets it. The operation is remontage, and how hard and how often it is run is one of the main levers on how much a red extracts."),
    Q("Working the cap",
      "The entire contents of a fermenting red tank are run into an empty vessel, the cap left to drain onto the screen, and the wine then returned over the top of it. What does that achieve which a straightforward pump-over does not?",
      ["The seeds settle out and can be left behind, taking their tannin with them",
       "It halts the ferment for a day, since the wine stands in an empty tank",
       "It flushes the tank with carbon dioxide, so the cap is shielded from air",
       "It raises the alcohol, since part of the wine evaporates in the transfer"], 0,
      "Delestage, or rack and return, also breaks the cap apart completely and aerates hard, so it is an aggressive tool rather than a gentle one. Leaving the seeds on the floor of the vessel is the point of it, since far less of their hard tannin then reaches the wine. Cellars reach for it early, when they want extraction and a clean tannin profile, and stop before the wine is stripped."),
    Q("Working the cap",
      "Three warm days pass with nobody touching a red fermenter, and the top of the cap dries out in the air. What is the specific danger sitting in that crust?",
      ["Acetic bacteria colonise the exposed skins and raise volatile acidity",
       "Film yeast spread across the dry crust and leave the wine a shade paler",
       "Brettanomyces breeds in the crust and drains back as a sweeter second wine",
       "The dried skins take up the wine's alcohol, so the red falls short of its strength"], 0,
      "Skins above the liquid are warm, wet with sugar and open to the air, which is precisely the habitat acetic bacteria want. Keeping the cap submerged or at least wet is therefore a preservation job as much as an extraction one, and the volatile acidity a neglected crust throws cannot be taken back out of the wine afterwards."),
    Q("Working the cap",
      "Slatted boards hold the skins permanently below the surface of a fermenting red, so no crust ever forms at all. How does extraction under that arrangement compare?",
      ["Slow and steady, with no aeration and no daily cap work",
       "Fast and hard, because the skins are held under pressure",
       "Almost nothing is extracted, since the skins are never agitated",
       "Colour is extracted but tannin is not"], 0,
      "A submerged cap keeps every skin in contact with wine at all times and needs no plunging, which suits a cellar without the hands for three punch-downs a day. It also shuts out air, so wines raised this way often want aeration later on."),

    # ------------------------------------- extraction, colour and maceration (5) --
    Q("Extraction, colour and maceration",
      "Juice is bled off a red fermenter after a few hours on the skins and finished separately as a pink wine. Beside a rose pressed straight from red grapes, how does that wine usually show?",
      ["Deeper in colour and fuller in body",
       "Paler and lighter, with lower alcohol",
       "Sweeter, because the juice never ferments out",
       "Indistinguishable, since both come from the same fruit"], 0,
      "The bled juice comes off a vat set up to make red wine, from riper fruit and with more skin contact than fruit picked and pressed for pink in the first place. Saignee is the word for the bleeding, and a dark example is easily mistaken for a light red on the table."),
    Q("Extraction, colour and maceration",
      "Colour climbs steeply in a red fermenter for the first several days and then starts to fall back, although the skins are still sitting in the wine. What accounts for the decline?",
      ["Pigment binds to skins, seeds and yeast and drops out of solution",
       "The pigment ferments away into alcohol along with the sugar",
       "The rising temperature of the vat bleaches the pigment out",
       "Escaping carbon dioxide carries the pigment up and out of the tank"], 0,
      "Anthocyanins are adsorbed by the solids in the vat and by the yeast themselves, so a longer maceration does not automatically mean a darker wine. It is one of the reasons a cellar tastes a fermenter daily rather than working to a fixed number of days."),
    Q("Extraction, colour and maceration",
      "Inside an unbroken berry sealed under carbon dioxide, the fruit's own enzymes go to work before any yeast can reach the pulp. Which acid is largely consumed in that process?",
      ["Malic acid", "Tartaric acid", "Lactic acid", "Acetic acid"], 0,
      "Intracellular fermentation burns off much of the berry's malic acid and makes a small amount of alcohol along with the perfumed aromatics the method is prized for. Losing that acid is why such wines taste soft and round while still very young, even off fruit picked at modest ripeness."),
    Q("Extraction, colour and maceration",
      "Red must is run through a heat exchanger at seventy degrees, held there for two hours and then pressed before any yeast is pitched. What is the cellar buying with that heat?",
      ["Colour out of the skins in hours, with the wine then fermented off them like a white",
       "A firmer tannin structure than a long maceration on the skins could build",
       "A higher final alcohol, since the heat drives water off and concentrates the sugar in the must",
       "A wine that will age longer in bottle than one fermented on its skins in the usual way"], 0,
      "Heat pulls pigment out of the skins in a couple of hours, so the juice can be pressed off and fermented clear like a white, and the press house is free again the same day. What comes back is colour and soft fruit with very little tannin, which is why thermovinification belongs to volume reds meant to be drunk young. It is also reached for when rot has left an enzyme in the fruit that would otherwise brown the wine, since the heat destroys it."),
    Q("Extraction, colour and maceration",
      "A vat is filled with destemmed but deliberately uncrushed berries and left to break down gradually under their own weight. What is the winemaker expecting to gain?",
      ["A gentler start, brighter fruit and softer tannin",
       "A ferment that runs right through to dryness in three days",
       "A deeper colour than crushing the fruit would have given",
       "A higher final alcohol than the same fruit crushed would reach"], 0,
      "Whole berries ferment partly from the inside as their skins give way, which is slower and less extractive than working a fully crushed must. It is a common choice with thin-skinned varieties where the aim is perfume and lift rather than density."),

    # --------------------------------------- adjusting the must and the wine (5) --
    Q("Adjusting the must and the wine",
      "A cool-vintage must reads ten and a half degrees of potential alcohol, and a measured weight of beet sugar is stirred in before fermentation. What does the finished wine gain, and what does it not?",
      ["Alcohol and body, but no sweetness, since the yeast ferment it away",
       "Sweetness and body, but no extra alcohol, since none of it ferments",
       "Alcohol and sweetness both, since some of the sugar survives",
       "Colour and tannin, but no gain in alcohol at all"], 0,
      "Chaptalisation gives the yeast more sugar to work with, so the wine finishes stronger and drier rather than sweeter. It cannot make unripe fruit taste ripe, which is why it is treated as a correction to a hard year and not as a recipe."),
    Q("Adjusting the must and the wine",
      "Fruit picked in a hot year comes in at pH 3.9 and the juice tastes soft and flat. Which addition is the standard remedy in cellars permitted to make it?",
      ["Tartaric acid", "Calcium carbonate", "Beet sugar", "Potassium sorbate"], 0,
      "Tartaric is chosen because the grape already contains it and, unlike malic, bacteria will not consume it later, so the correction holds. Dropping the pH also sharpens the finish and makes whatever sulphur dioxide is in the wine far more effective as a preservative."),
    Q("Adjusting the must and the wine",
      "A cool northern white finishes with acidity so sharp it is painful to taste, and the cellar wants to blunt it before bottling. Which treatment does that job?",
      ["Stirring in a chalk-based salt that drops part of the acid out",
       "Adding tartaric acid, which binds the sharp acid and drops it out",
       "Warming the wine gently in tank until part of the acid is driven off",
       "Sweetening the wine with a measure of grape spirit before bottling"], 0,
      "Calcium carbonate reacts with the acid and drops out as an insoluble salt that is filtered away, so total acidity falls and the wine reads rounder. Deacidification is much rarer worldwide than acidification, since only cool regions in poor years ever need it."),
    Q("Adjusting the must and the wine",
      "A finished red reads sixteen and a half per cent and burns on the finish, and the producer wants it nearer fourteen without cooking the wine. Which treatment answers that?",
      ["Reverse osmosis, taking the alcohol out of what crosses the membrane",
       "Adding water to the tank until the reading falls, without thinning it",
       "Chilling the wine until the alcohol freezes out and is skimmed off",
       "Filtering the wine through a pad fine enough to hold the alcohol back"], 0,
      "The membrane separates a thin watery fraction from the wine, the alcohol is taken out of that fraction alone, and what is left goes back, which is why the flavour survives the operation. A spinning cone reaches the same end by vacuum distillation at a temperature low enough not to cook anything. Simply watering a wine back from sixteen and a half to fourteen would take something like a seventh of its volume in water, which hollows the wine out even where the law allows it."),
    Q("Adjusting the must and the wine",
      "A thin, hollow red is dosed before ageing with a powder extracted from grape skins, seeds and oak. What is that addition there to do?",
      ["Add structure and help hold the colour in place",
       "Raise the alcohol, since the powder carries sugar too",
       "Lower the pH, so the wine finishes fresher",
       "Strip bitterness out of a coarse young red"], 0,
      "Oenological tannin binds with pigment and helps fix colour as well as building grip on the palate. It cannot invent concentration, so it works at the margin of a weak wine rather than transforming one."),

    # ------------------------------------------------- yeast and the ferment (5) --
    Q("Yeast and the ferment",
      "Nothing is pitched into the tank and the cellar waits for the population already on the fruit and in the building to start work. What is the trade being accepted?",
      ["More aromatic complexity, against a slower and less predictable ferment",
       "A faster and steadier ferment, with less aromatic character to show",
       "Higher alcohol, since the wild population tolerates more of it",
       "Lower alcohol and deeper colour than a pitched culture gives"], 0,
      "An ambient ferment is a succession of species rather than one strain, and the wine picks up more variety from that sequence. The risk is real: the ferment can crawl, stop short of dryness or throw volatile acidity, so the cellar has to be ready to step in."),
    Q("Yeast and the ferment",
      "Fermentation halts at four grams of sugar per litre in a vat that ran too hot, and the yeast are dead. Why is that dangerous rather than merely inconvenient?",
      ["Sugar with no yeast working on it invites spoilage",
       "The four grams unbalance the red, since any sugar reads as sweetness",
       "The wine will refuse to fall bright while any sugar remains in it",
       "The colour will drop out of solution within a matter of days"], 0,
      "A stuck ferment has to be protected with sulphur and restarted with a culture acclimatised to the alcohol already present, and the odds worsen the longer it sits. Heat, very high sugar and a shortage of nutrient in the juice are the usual causes."),
    Q("Yeast and the ferment",
      "Instead of a packet of dried yeast, a cellar picks a small quantity of grapes a week early, ferments them and tips the result into the main vat. What is that starter called?",
      ["A pied de cuve", "A solera", "A liqueur de tirage", "A dosage"], 0,
      "It gives the vineyard's own population a running start, so the main ferment begins promptly without a commercial strain ever entering the building. It sits between pitching a culture and waiting on the ambient flora entirely, and it carries some of the risk of both."),
    Q("Yeast and the ferment",
      "One Chardonnay ferments in barrel from the start; another ferments in steel and is racked into the same barrels afterwards. Which difference should show in the glass?",
      ["The barrel-fermented wine carries its oak more seamlessly",
       "The barrel-fermented wine tastes markedly more oaky and obvious",
       "The steel-fermented wine finishes higher in alcohol",
       "The steel-fermented wine ends up deeper in colour"], 0,
      "Fermenting in wood binds the oak compounds into the wine while the yeast are still active, and the sediment left behind keeps working on the texture afterwards, so the wine feels broader as well as less overtly oaky. Moving a finished wine into oak lays the flavour on top of it instead, which reads as a seasoning rather than as part of the wine."),
    Q("Yeast and the ferment",
      "Two tanks of identical juice are pitched with different commercial strains and smell nothing alike a fortnight later. What is the strain actually doing to produce that?",
      ["Freeing odourless precursors, and adding by-products of its own",
       "Contributing varietal aromas bred in, which the juice lacked",
       "Turning the aroma of one variety into that of another grape",
       "Drawing aroma compounds out of the walls of the steel tank"], 0,
      "A great deal of a wine's aroma arrives bound to sugars or amino acids and has no smell at all until a yeast enzyme cuts it loose, and strains differ sharply in how much they release. On top of that the yeast make esters and higher alcohols of their own, which is why strain choice is a genuine stylistic decision."),

    # ---------------------------------------------- malolactic and the lees (5) --
    Q("Malolactic and the lees",
      "Bottled in a hurry, a red that had not finished its bacterial conversion reaches the shelf faintly hazy and prickling on the tongue. What has gone on inside the bottle?",
      ["The conversion carried on there, throwing carbon dioxide and a bacterial haze",
       "The yeast found sugar they had missed and ran a second alcoholic ferment in the bottle",
       "Air drawn in past the cork oxidised the wine and dropped a brown deposit with it",
       "Tartrates came out of solution in a cold warehouse and clouded the wine"], 0,
      "Bacteria left alive in a wine that still holds malic acid will finish the job wherever they happen to be, and in a sealed bottle the carbon dioxide they throw off has nowhere to go. A cellar therefore either sees the conversion right through in tank, confirming it by chromatography or an enzymatic test rather than by taste, or filters the bacteria out before the wine goes anywhere near the filler."),
    Q("Malolactic and the lees",
      "A cellar wants the bacterial conversion finished before winter cold shuts it down. Which pair of conditions encourages it?",
      ["A warm cellar and a low level of sulphur dioxide",
       "A cold cellar and a high level of sulphur dioxide",
       "A warm cellar and a high level of sulphur dioxide",
       "A cold cellar and no sulphur dioxide at all"], 0,
      "The bacteria work best at around eighteen to twenty-two degrees, slow almost to a stop below fifteen and are held back by free sulphur dioxide, so a cellar creates or removes those two conditions depending on what it wants. Preventing the conversion in a wine meant to stay sharp is exactly the same knowledge applied in reverse."),
    Q("Malolactic and the lees",
      "Immediately after fermentation a vessel holds a coarse sediment of skin fragments, pulp and dead yeast, and a much finer one settles later. Why is the coarse fraction usually taken away early?",
      ["It can strip oxygen from the wine and throw sulphurous smells",
       "It holds the wine's colour, which returns during ageing",
       "It would restart the fermentation once the wine is moved",
       "It makes the finished wine taste sweet and flat"], 0,
      "Gross lees are dense and biologically active, and a wine left sitting on them can develop off-smells within weeks. The first racking is therefore timed in days rather than months, and a cellar judges the moment by smelling the tank rather than by the calendar, since a warm vessel turns faster than a cold one."),
    Q("Malolactic and the lees",
      "Two identical barrels are filled from one tank; one is left sitting on its fine sediment and the other is drawn off clean. Which stays fresher for longer with no extra sulphur, and why?",
      ["The one on its sediment, because the yeast cells take up oxygen",
       "The clean one, because the sediment draws oxygen into the barrel",
       "The clean one, because the sediment raises the wine's pH over time",
       "Neither, because the sediment has no bearing on how the wine oxidises"], 0,
      "Lees act as a natural antioxidant, which is part of why wines raised on them can be handled with a lighter hand on added sulphur. That protection vanishes the moment the wine is moved away from them, so the racking date is also a sulphur decision."),
    Q("Malolactic and the lees",
      "Every fortnight through the winter one barrel of white has its sediment roused back into suspension with a rod while its neighbour is left undisturbed. What should separate them at the table?",
      ["The roused barrel tastes rounder and creamier in texture",
       "The roused barrel tastes distinctly sweeter than its neighbour",
       "The undisturbed barrel finishes higher in alcohol",
       "The roused barrel ends up deeper in colour"], 0,
      "Putting the sediment back into suspension multiplies the wine's contact with it, and the compounds released build weight across the middle of the palate. It is a lever with a price, since a heavily worked barrel trades some of its aromatic lift for that texture, and fashion has swung back towards restraint."),

    # ---------------------------------------------- vessels and what they give (5) --
    Q("Vessels and what they give",
      "Unlined concrete tanks shaped like eggs have replaced steel in some cellars for whites raised without oak. Beyond the thermal steadiness of a thick wall, what is the shape meant to do?",
      ["Set up a slow convection current that keeps the fine sediment moving",
       "Compress the wine at the base so that it falls bright faster",
       "Increase the surface of wine in contact with the air",
       "Allow the grapes to be pressed inside the vessel itself"], 0,
      "With no corners to trap anything, the tank is said to circulate gently on its own and give something of the effect of stirring with nobody touching it. Concrete's uncontested virtue is mass, since a heavy wall holds temperature steady through a warm cellar and contributes no flavour whatever."),
    Q("Vessels and what they give",
      "Wine raised in unglazed earthenware behaves unlike the same wine in a steel tank of equal size. What is the clay contributing?",
      ["A slow exchange of oxygen through the porous wall",
       "Vanilla and toast, drawn out of the fired clay itself",
       "A measurable rise in the wine's acidity over the months",
       "A faster and warmer fermentation than steel"], 0,
      "Porosity puts a clay vessel between a barrel and a tank: the wine breathes, but nothing is seasoned into it. Producers who want the neutrality without the air line or wax the interior precisely to shut that exchange down."),
    Q("Vessels and what they give",
      "An inexpensive red shows clear vanilla and toast, yet the producer owns no barrels at all. How was that done?",
      ["Oak chips or staves left in the tank",
       "A longer fermentation on the skins",
       "A dose of oenological tannin",
       "Ageing in unlined concrete tanks"], 0,
      "Chips, staves and inserts deliver oak flavour cheaply and quickly, and at the bottom of the market they are the rule rather than the exception. What they cannot give is the slow maturation a barrel provides alongside its flavour, so the oak arrives on a wine that has not been changed in any other way. Toast level and oak origin are specified much as they would be for a barrel, and the dose is set in grams per litre."),
    Q("Vessels and what they give",
      "Cooling jackets wrap the outside of a stainless tank and chilled glycol runs through them. Which ability does steel hand the winemaker that a wooden vat cannot?",
      ["Fast, precise control of fermentation temperature",
       "A slow trickle of oxygen through the vessel wall",
       "Flavour compounds drawn from the vessel itself",
       "A lower final acidity in the finished wine"], 0,
      "Steel conducts heat quickly, so a ferment can be held within a degree of a target and a tank can be chilled hard whenever the cellar chooses. Wood insulates instead, which is why coolers have to be dropped inside a wooden vat rather than strapped around it."),
    Q("Vessels and what they give",
      "Open wooden vats still stand in cellars that could afford any equipment they liked. What do they offer that a closed steel tank does not for a red ferment?",
      ["They hold their warmth and let the cap be worked by hand",
       "They keep the wine entirely free of oxygen during the ferment",
       "They let fermentation begin without any yeast at all",
       "They make chilling the ferment easier than steel"], 0,
      "An open top is what makes plunging possible at all, and thick staves keep a ferment warm overnight without any heating. The cost is that everything above the wine line is exposed to the air, so the cap can never be left to itself."),

    # ---------------------------------------------- oxygen, given and withheld (5) --
    Q("Oxygen, given and withheld",
      "A ceramic diffuser feeds a fine, metered stream of oxygen into a tank of young red over several months. What is that treatment set up to achieve?",
      ["Tannin softened and colour fixed in months, not years",
       "A second fermentation, since the oxygen wakes the sleeping yeast",
       "The removal of the wine's carbon dioxide, left over from the ferment",
       "An increase in the wine's alcohol, since oxygen feeds the yeast"], 0,
      "Micro-oxygenation imitates the trickle of air a barrel supplies, at a rate the cellar sets in milligrams per litre per month. Overdone it dries the wine out and ages it before its time, so the dose is tiny and the tank is tasted constantly."),
    Q("Oxygen, given and withheld",
      "Pressed white juice is deliberately splashed and aerated until it browns in the tank, before any yeast goes anywhere near it. Why is that not the disaster it looks?",
      ["The compounds that brown drop out before fermentation, so the finished wine holds its colour better",
       "The yeast consume the oxygen later in the ferment, and the brown colour is reversed as the wine falls bright",
       "Browning raises the acidity of the juice",
       "The brown pigment settles into the sediment and is stirred back in"], 0,
      "Hyperoxidation sacrifices the phenolics that would otherwise have oxidised in bottle: they polymerise and settle out with the juice solids, and whatever brown survives is taken down onto the yeast and lees during fermentation rather than being reversed, so the wine ships more stable than juice protected all the way through. It costs some aromatic detail, which is why it suits neutral varieties and not perfumed ones."),
    Q("Oxygen, given and withheld",
      "Before wine is moved into an empty vessel, the tank is flushed with an unreactive gas and the headspace kept full of it afterwards. What is being protected?",
      ["The wine's fruit aroma and colour, by keeping oxygen off it",
       "The wine's temperature, by insulating it from the cellar",
       "The wine's sparkle, by holding it under gas pressure",
       "The wine's clarity, by settling the particles faster"], 0,
      "Carbon dioxide, nitrogen and argon are all used for this, and a cellar working reductively will flush hoses, presses and bottling lines as well as tanks. Whites and roses gain the most from it, since they have no tannin to spend defending themselves."),
    Q("Oxygen, given and withheld",
      "An actively fermenting vat is remarkably safe from oxidation even with the lid off and nothing added to it. What is defending the wine?",
      ["The blanket of carbon dioxide the yeast throw off",
       "The alcohol, which is too stable a molecule to oxidise",
       "The sugar still in solution, which soaks up air",
       "The heat of the ferment, which drives the oxygen out"], 0,
      "Fermentation throws off a heavy blanket of gas that sits on the wine and pushes air out of the vessel, which is also why an enclosed fermentation cellar is genuinely dangerous to walk into. The protection ends the moment fermentation does, and that is when a winemaker's attention to oxygen properly begins."),
    Q("Oxygen, given and withheld",
      "A tank is pumped deliberately through the air into another vessel, splashing as it falls, rather than being moved gently across. What is the cellar after?",
      ["A dose of oxygen, to drive off sulphur compounds and open the wine up",
       "A faster transfer, since wine falling through air moves quicker",
       "A rise in the wine's temperature as it falls through the air",
       "A finer sediment in the receiving tank, since the wine falls hard"], 0,
      "Splash racking treats oxygen as a tool rather than a threat, and a wine closed up from too little air will often clean up within hours of it. The same handling given to a delicate white with nothing to hide simply tires it out."),

    # ----------------------------------------------- clarifying and stabilising (5) --
    Q("Clarifying and stabilising",
      "A white wine bright at bottling turns cloudy after an afternoon in a hot car, although nothing has spoiled. Which treatment before bottling prevents that?",
      ["A bentonite clay fining, which takes the proteins out",
       "A heavier dose of sulphur dioxide just before bottling",
       "A longer spell on the sediment, which settles the proteins out",
       "A warmer bottling temperature, which keeps the proteins dissolved"], 0,
      "Grape proteins stay dissolved while a wine is cool and come out of solution when it is warmed, which is why the haze appears in transit or on a shelf and never in the cellar. Bentonite is a swelling clay that binds those proteins and is filtered away with them, and it is standard insurance on nearly every commercial white."),
    Q("Clarifying and stabilising",
      "Held at minus four degrees for a week before bottling, a white throws a crust on the tank wall which is then filtered away. What has been prevented?",
      ["Crystals appearing in the bottle later on",
       "A refermentation in the bottle later on",
       "The wine browning on the shop shelf",
       "A protein haze in warm weather"], 0,
      "Potassium bitartrate is far less soluble in cold wine, so chilling forces it out where it can be removed rather than leaving it to appear on a cold shelf months later. More producers skip the step each year, on the grounds that the deposit is a cosmetic matter and the chilling costs the wine some aroma."),
    Q("Clarifying and stabilising",
      "Two filters stand in the bottling room: one traps particles inside a thick pad of medium, the other has a rated pore size that nothing larger can pass. Which one alone can be relied on to hold a sweet wine stable in bottle, and why?",
      ["The rated membrane, because it removes every live yeast cell",
       "The pad, because it takes far more solids out in a single pass",
       "The rated membrane, because it lowers the wine's alcohol",
       "The pad, because it feeds the wine a little oxygen too"], 0,
      "A sweet wine is a bottle of food for any yeast that survives bottling, and a membrane rated below a micron is the usual guarantee against that. The pad is cheaper and gentler and takes the bulk of the solids out first, so the two are run in sequence rather than as rivals."),
    Q("Clarifying and stabilising",
      "A guest asks whether a wine is suitable for a vegan diet. Which stage of production is the reason the answer is sometimes no?",
      ["Fining, because several fining agents are animal-derived",
       "Fermentation, because yeast is counted as an animal product",
       "Filtration, because the pads themselves are made from gelatin",
       "Bottling, because the capsules are sealed with wax from animals"], 0,
      "Gelatin, isinglass from fish swim bladders, casein from milk and beaten egg white have all been used for centuries, and little or none of them normally survives into the bottle, though milk and egg agents must still be declared on an EU label unless the residue is shown to fall below the legal limit. The vegan question turns on whether an animal product was used at all rather than on what is left behind, so producers making the claim switch to mineral or plant-based agents, or bottle without fining."),
    Q("Clarifying and stabilising",
      "Nothing is fined out of a wine and nothing is filtered before it is bottled. What is being traded, and for what?",
      ["Some clarity and stability, in return for texture and aroma",
       "Some alcohol, in return for a longer finish and a fuller body",
       "Some acidity, in return for a softer palate at the table",
       "Some colour, in return for a longer life in bottle"], 0,
      "Every fining and every filtration removes something besides its target, and the argument for leaving a wine alone is that the collateral loss outweighs the gain. The price is a wine that may throw a deposit and is less predictable in transit, which is a real consideration on a long shipping route."),

    # -------------------------------- pressing, blending and the finished wine (5) --
    Q("Pressing, blending and the finished wine",
      "The last and hardest fraction to come out of a red press is run into its own tank, apart from the wine that drained off under gravity. Why keep them separate?",
      ["It is darker, more tannic and coarser, so how much goes back is a choice",
       "It is sweeter than the free-run wine, since the skins give up sugar",
       "It is paler and softer than the free-run, so it is sold off in bulk",
       "It is cloudier than free-run wine, so it is always discarded"], 0,
      "Free-run wine is the elegant part, while press wine carries structure and colour that a blend may badly need in a light year. The fractions are tasted separately and a proportion is folded back in, or none at all."),
    Q("Pressing, blending and the finished wine",
      "Grapes are squeezed slowly through a deep cake of skins in a vertical basket rather than driven along by a continuous screw. What does the slower press give?",
      ["Cleaner juice with less bitterness, since the cake filters it",
       "A far higher yield per tonne, since the cake gives the plate more to press",
       "Juice carrying more colour and tannin than a continuous press gives",
       "A faster turnaround at harvest, since the basket empties itself"], 0,
      "Hard, fast pressing tears skins and cracks pips and drives phenolics and solids into the juice, and no later treatment fully undoes it. The basket press is slow and labour-hungry, which is why it survives at the quality end and almost nowhere else."),
    Q("Pressing, blending and the finished wine",
      "Twenty small lots ferment separately in one cellar when a single large tank would have been far cheaper to fill and to clean. What does that buy?",
      ["Each parcel can be judged and treated on its own",
       "The wine ferments faster in small volumes than in large ones",
       "Small lots need no filtration before bottling",
       "The wine reaches a higher alcohol in a small vessel"], 0,
      "Blending is a subtractive art as much as an additive one, and keeping lots apart is what makes leaving something out possible at all. Once a spoiled barrel has gone into the tank there is no way back, which is the whole argument for the extra work."),
    Q("Pressing, blending and the finished wine",
      "A tech sheet records a cuvaison of twenty-one days. Which part of the process does that figure describe?",
      ["The time the wine spent in contact with the skins",
       "The time the wine spent in barrel afterwards",
       "The time the wine spent on its own sediment",
       "The time between bottling and release to the trade"], 0,
      "The figure covers the whole span in the fermenting vessel with the solids, taking in any cold soak beforehand and any maceration after the sugar has gone. A number well beyond the length of the ferment itself is therefore a signal that the cellar macerated afterwards."),
    Q("Pressing, blending and the finished wine",
      "A grower says the wine will not be bottled for eighteen months, during which it will be racked, topped up, blended and fined. Which single French word covers that whole span?",
      ["Elevage", "Soutirage", "Assemblage", "Mutage"], 0,
      "The word means raising or bringing up, and it takes in maturation, movement, blending and clarification alike. It says nothing on its own about the vessel, so eighteen months of it may mean steel, concrete, clay or oak in any combination."),
]
