"""Rank I rewrite - Wine Law (55 questions, all multiple choice).

Written from the syllabus below. The imported bank was not read while writing.

One idea holds the category together: a wine law is a promise about ORIGIN
first and quality second, and every country has chosen for itself how tightly
to bind the two. The running order follows that thought outward. What a
protected name actually promises, then how it differs from a brand, then the
European framework every member state now shares, then the French system that
the rest of Europe copied, then what a rulebook reaches into, then the numbers
it prints, then the ladders each country built, then the systems that grew up
outside Europe, and last the inspection that makes any of it mean anything.

The national ladders themselves belong to the country categories and are only
named here as examples of a framework, never taken apart. Decoding the wording
on a particular bottle belongs to Label Reading, grape synonyms to Grapes &
Labels, and the mechanics of revising a classification to Rank II.

Every stem opener is distinct, the constructions in lib.BANNED_TEMPLATES are
avoided by design, and where the answer is an institution, a country or a term
the stem opens with a scene, a document or a problem so the subject arrives as
the answer rather than as the first clause.
"""

from lib import Q

CAT = "Wine Law"
SLUG = "r1-wine-law"
PREFIX = "i"
RANK = "Rank I"
SOURCE = "data-intro.js"

SYLLABUS = [
    ("Origin as the promise", 6),
    ("Indication, brand and the right to a name", 5),
    ("The European framework", 7),
    ("France and the appellation model", 6),
    ("What a rulebook controls", 6),
    ("Percentages, volumes and tolerances", 5),
    ("Ladders, rungs and national variations", 8),
    ("Frameworks beyond Europe", 6),
    ("Inspection, enforcement and the limits of the law", 6),
]

BANK = [
    # ------------------------------------------- origin as the promise (6) ---
    Q("Origin as the promise",
      "Two bottles carry the identical protected regional name, one thrilling and one thoroughly dull, and neither producer has broken any rule. What does that name actually guarantee?",
      ["That the fruit grew inside the named boundary and the stated rules were followed",
       "That the wine reached a minimum standard of flavour, a score having been awarded to it before release",
       "That the producer owns vineyards rather than buying fruit in from other growers",
       "That the wine will reward several years of cellaring"], 0,
      "A protected name is a claim about a place and about compliance, and compliance is auditable in a way deliciousness is not. Within those limits the range from grower to grower stays enormous, which is why a buyer who knows only the appellation still knows very little."),
    Q("Origin as the promise",
      "Early wine laws did nothing but draw a boundary on a map, and thin, poorly made wine went on carrying celebrated names quite lawfully. What did the next generation of laws add?",
      ["Rules on how the wine inside the boundary had to be grown and made",
       "A minimum selling price for each named region, fixed annually by the state",
       "A ban on exporting wine outside the country of origin",
       "A requirement that every bottle state its alcoholic strength"], 0,
      "A boundary answers where and says nothing about how, so a grower could crop enormously, pick unripe and still use the name. Binding production rules to the map is the single step that turned a delimitation into an appellation, and every modern European system rests on it."),
    Q("Origin as the promise",
      "Frost cuts a village crop to a third, and the grower blends what survives with fruit from parcels entitled only to the wider regional name. Which way may a wine move between two appellations nested inside one another?",
      ["Downward into the broader name, but never upward into the tighter one",
       "Upward into the tighter name, but never downward",
       "Either way, provided the fruit is genuinely from the region",
       "Neither way, since a parcel is fixed to one name for good"], 0,
      "Declassification is always available because the broader rulebook is the easier one to satisfy, and every hectare inside a village sits inside the region as well. The reverse is impossible by construction, which is the practical test of which of two overlapping names sits above the other."),
    Q("Origin as the promise",
      "One appellation covers an entire region and a second covers a single village lying inside it. Which of the two rulebooks will be the stricter?",
      ["The village one, since the requirements tighten as the named area narrows",
       "The regional one, since a rulebook covering many more growers has to be written more strictly",
       "Neither, since both rulebooks are approved by the same authority",
       "Whichever of the two was written more recently"], 0,
      "Yields fall, minimum ripeness rises and the list of permitted grapes usually shortens with every step inward. That is what makes a narrow name worth having: it costs the grower something to use it, and the cost is the information the buyer is paying for."),
    Q("Origin as the promise",
      "Before a new wine name may be protected, its supporters have to establish something more than that the wine is well made. What must they show?",
      ["A demonstrable link between the place and the character or reputation of its wine",
       "That the region already exports a substantial quantity, and has done so for many years",
       "That every grower in the zone has signed the application",
       "That the wine has won awards over three consecutive vintages"], 0,
      "The whole legal theory of a geographical indication is that the ground, the climate and the local way of working leave a mark a buyer can rely on. No link means no case, however good the wine, which is why applications rest on soil surveys, climate records and documented history rather than on tasting notes."),
    Q("Origin as the promise",
      "A grower crops at half the permitted maximum, picks far riper than the minimum and holds the wine twice as long as required. How does the law treat that?",
      ["It is permitted, since the rules fix outer limits rather than targets",
       "It voids the appellation, because the wine no longer matches the rulebook",
       "It requires prior written permission from the appellation body",
       "It is permitted only for producers above a certain size"], 0,
      "A rulebook fixes the widest yield and the lowest ripeness a name will tolerate, so a producer may be as strict with himself as he likes. A few rulebooks do cap alcohol or fix a window for bottling, but the general asymmetry is why the best estates in a region are usually far inside the limits and why the limits themselves tell you about the floor far more often than the ceiling."),

    # ------------------------- indication, brand and the right to a name (5) --
    Q("Indication, brand and the right to a name",
      "Brands are bought, sold, licensed and carried across borders every day, and a protected wine name can do none of those things. Which difference accounts for that?",
      ["A trademark belongs to one owner, while a protected name belongs collectively to whoever farms inside the delimited place",
       "A trademark is registered nationally and a protected name internationally",
       "A trademark protects a logo and a protected name protects a word",
       "A trademark lasts ten years and a protected name lasts fifty"], 0,
      "Nobody owns an appellation, so it cannot be assigned, and it cannot travel because its entire content is where the fruit grew. Any grower inside the boundary who meets the rules may use it, and no grower outside may, however much they pay."),
    Q("Indication, brand and the right to a name",
      "A sparkling wine made in England is labelled with a protected French wine name followed by the words style, produced in Sussex, so no buyer could be deceived about where it came from. Why is that still unlawful in the European Union?",
      ["Protection extends to evocation, so a qualifier that discloses the true origin does not rescue the use",
       "It would be lawful if the French name were printed smaller than the English one",
       "It is unlawful only for sparkling wine and permitted for still wine",
       "It becomes lawful as soon as the wine is exported outside the Union"], 0,
      "The regulation closes off translation, transliteration and the words style, type, method and imitation alongside outright misuse. The test is whether the protected name is being called to mind at all, not whether any particular buyer was actually deceived, so an honest statement of the true origin makes no difference to the outcome."),
    Q("Indication, brand and the right to a name",
      "Wine names won formal recognition as a species of intellectual property, sitting alongside patents and trademarks, in a world trade agreement concluded in 1994. Which agreement?",
      ["The TRIPS agreement, administered by the World Trade Organization",
       "The Treaty of Rome, which founded the European Economic Community in 1957",
       "The Madrid Protocol, which handles trademark registrations",
       "The Bretton Woods agreement"], 0,
      "Trade-Related Aspects of Intellectual Property Rights obliges member states to give geographical indications legal means of protection, and it singles out wine and spirits for a stricter standard than other goods. It is the reason a producer in a country with no appellation tradition of its own can still be stopped from using a European wine name."),
    Q("Indication, brand and the right to a name",
      "Somebody applies to register the name of a famous wine village as a trademark for wine made a thousand miles from it. What is the usual outcome?",
      ["Refusal, because a mark that misleads the public about geographical origin cannot be registered",
       "Registration, since trademark law and origin law are separate systems that take no account of one another",
       "Registration, provided the applicant adds a disclaimer to the label",
       "Refusal, but only if a producer from that village formally objects"], 0,
      "Deceptiveness as to origin is a standing ground of refusal in most trademark systems, quite apart from any protected indication. Where a mark was registered long before the indication existed, the two are usually allowed to coexist, which is how a handful of odd historical pairings survive."),
    Q("Indication, brand and the right to a name",
      "One kind of protection lapses if its holder stops using it and neglects to renew, while the other runs on for as long as the place and its rules exist. Which is the one that lapses?",
      ["The trademark", "The geographical indication",
       "Both lapse on the same cycle", "Neither lapses once granted"], 0,
      "A registered mark has to be renewed periodically and can be revoked for non-use, because it is private property that its owner is expected to work. A registered indication has no expiry date and no owner to abandon it, so it survives changes of hand and generations of growers, though the Union may still cancel a name whose specification stops being met or under which nothing at all has been sold for seven consecutive years."),

    # ------------------------------------------ the european framework (7) ---
    Q("The European framework",
      "Until the reform that took effect in 2009, European labels divided into quality wine produced in a specified region and table wine. What replaced that split?",
      ["A single origin framework of protected designations and protected geographical indications, shared with cheese, ham and other foods",
       "A four-tier system written specifically for wine and used nowhere else",
       "Purely national classifications, with the European layer abolished",
       "A points system in which panels scored each wine before release"], 0,
      "Wine was given the same pair of categories the food scheme already used for Parmigiano Reggiano and Prosciutto di Parma, and the two strands have since been drawn into one European register and, since 2024, one regulation. Nothing on the ground moved when it happened: the zones and rulebooks already in force were carried straight across into the new categories, so the reform was a change of framework rather than of boundary."),
    Q("The European framework",
      "A protected designation of origin requires its grapes to come from inside the named zone. What proportion?",
      ["All of them", "At least eighty-five percent", "At least seventy-five percent",
       "At least half"], 0,
      "Origin is absolute at this level, and it is the sharpest line between the two protected categories: the broader indication tolerates a fifteen percent margin from outside its boundary while the designation tolerates none. The rules on production and processing tighten in step."),
    Q("The European framework",
      "A producer wants a longer list of permitted varieties and a wider boundary than his designation of origin allows, and still wants to name a real region on the label. Which European category takes that wine?",
      ["A protected geographical indication",
       "A registered collective trademark",
       "A national quality tier standing outside the European system",
       "A protected designation of origin with a derogation"], 0,
      "The broader category exists precisely to house good wine that does not fit the local rulebook, and it is where varietal labelling and experimental plantings live across most of Europe. Its zones are typically far larger, sometimes covering a whole river basin or province."),
    Q("The European framework",
      "A cheap European bottle names no region whatever, yet prints the grape variety and the year on its front label. What is that bottle's standing in European wine law?",
      ["Wine with no geographical indication, a category permitted to state variety and vintage",
       "An unlawful label, since variety and year may be printed only under a name protected in law",
       "A protected geographical indication whose region was omitted by choice",
       "Wine sold under a trademark, which exempts it from origin rules"], 0,
      "Before the reform this tier could name neither, which left cheap wine with nothing to say but a brand name. Opening variety and vintage to it created an enormous market in wine sold by grape rather than by place, and the claims are certified even though no region is named."),
    Q("The European framework",
      "Italy prints DOCG, Spain prints DO and France prints appellation controlee, though all three wines sit in the same European category. What is the standing of those national words?",
      ["They are protected traditional terms a member state may keep using for wines in the European category",
       "They are marketing phrases that carried legal weight once and lost it when the European categories arrived",
       "They are transitional wording due to be withdrawn from all labels",
       "They are trademarks owned by each country's producers' association"], 0,
      "The reform harmonised the categories without erasing a century of national vocabulary, so both layers are lawful and either may appear. It is the reason a sommelier still has to know four or five sets of initials that all denote the same European object."),
    Q("The European framework",
      "A name protected in one member state is enforceable in every other without any further application anywhere. What makes that so?",
      ["Registration is made once at European level and protects the name across the whole union",
       "Each member state automatically copies the others' registers into its own",
       "The producer must lodge a separate filing in each state, but the fee is waived",
       "Protection follows the wine, so it applies only where the wine is actually sold"], 0,
      "A single European register holds every protected wine, food and spirit name, and an entry on it binds every member state at once. Protection is territorial, though, so the same name has to be defended by separate agreement or registration outside the union."),
    Q("The European framework",
      "Planting a new commercial vineyard in the European Union needs something no Australian or Californian grower has to obtain. What?",
      ["An authorisation from the member state, granted within a capped national total each year",
       "Membership of the local co-operative, which holds the planting rights for its whole district",
       "A minimum holding of five hectares of vineyard",
       "The written consent of neighbouring growers"], 0,
      "Total planted area may grow only by a small percentage annually, a survival of the older planting-rights regime brought in to stop the wine lakes of the last century. It is the clearest case of wine law regulating the industry itself rather than anything printed on a label."),

    # ------------------------------------ france and the appellation model (6) --
    Q("France and the appellation model",
      "Growers in a southern Rhone village drew up a charter of their own in 1923, fixing boundaries, permitted varieties and a minimum ripeness, and a decree of 1935 built a national system on that template. Which institution was created to run it?",
      ["The Institut National des Appellations d'Origine",
       "The Comite Interprofessionnel du Vin de Champagne",
       "The Direction Generale des Douanes",
       "The Institut Pasteur"], 0,
      "The 1935 decree set up a national committee for appellations of origin which took the institute's name a dozen years later and is today the Institut National de l'Origine et de la Qualite. Its founding lesson came from the growers themselves: a boundary is worth nothing unless the rules for farming inside it travel with it."),
    Q("France and the appellation model",
      "Rank the three tiers of French origin law from the freest rules to the tightest.",
      ["Vin de France, IGP, AOC", "IGP, Vin de France, AOC",
       "AOC, IGP, Vin de France", "Vin de France, AOC, IGP"], 0,
      "The bottom rung makes no geographical claim beyond the country and leaves grape and method entirely open. Each step up narrows the boundary and lengthens the rulebook, so the freedom a producer gives away is exactly what the name he gains is made of."),
    Q("France and the appellation model",
      "Who drafts the production rules for a French appellation in the first instance?",
      ["The growers' body for that appellation, which submits them to the national institute for approval",
       "The agriculture ministry alone, which drafts each rulebook and sends it out to the growers to apply",
       "The European Commission, which then notifies the member state",
       "The regional chamber of commerce for the department"], 0,
      "Appellations are largely self-governing, with the state acting as approver and referee rather than as author. That is why rulebooks differ so much in ambition from one appellation to the next, and why tightening one is a political argument among neighbours long before it is a legal act."),
    Q("France and the appellation model",
      "Roquefort, Comte and the poultry of Bresse all carry appellations administered by the very institute that runs the wine appellations. What does that reveal about the French model?",
      ["Appellation of origin is a general agricultural idea rather than a wine idea",
       "Those foods were added to the wine register as an exception in the 1990s",
       "Those foods sit on a separate register that merely shares the institute's name",
       "Only products fermented or matured over time may hold an appellation"], 0,
      "The same reasoning applies wherever a place, a breed or a practice leaves a mark a buyer can rely on, so butter, lentils and olive oil sit on the register beside the wines. Wine supplied the earliest delimitations and by far the most elaborate rulebooks, but the first French appellation of origin of all was granted to a cheese in 1925, a decade before the wine decrees."),
    Q("France and the appellation model",
      "Vin de pays was the French name for an entire tier until European harmonisation renamed it. What is that tier called now?",
      ["Indication Geographique Protegee", "Appellation d'Origine Protegee",
       "Vin de Qualite Superieure", "Vin de Table Regional"], 0,
      "The change was terminological rather than substantive: the same zones, broadly the same rules, a European name in place of a French one. Many producers still print the older wording alongside the new, so a single label can carry both at once and a buyer meets two names for one tier."),
    Q("France and the appellation model",
      "France once operated a fourth tier for regions working their way toward full appellation status, and abolished it with the 2011 vintage. What was it called?",
      ["Vin Delimite de Qualite Superieure", "Vin de Pays", "Vin de Table",
       "Cru Bourgeois"], 0,
      "It sat between the regional tier and full appellation status, and a candidate region had to prove itself there for years before applying to move up. Almost all its members were eventually promoted or absorbed into a regional indication, which left France with the three tiers it has today."),

    # ---------------------------------------- what a rulebook controls (6) ---
    Q("What a rulebook controls",
      "A rulebook states its production ceiling in hectolitres per hectare. What is being capped?",
      ["The volume of wine that may be made from a given area of vineyard",
       "The alcoholic strength the finished wine is allowed to reach before bottling",
       "The total area an estate is allowed to own",
       "The number of bottles a producer may sell in a year"], 0,
      "The reasoning is that a heavily cropped vine spreads what the site can give across too much fruit, so a ceiling is the bluntest and most universal quality lever in European law. It is set variety by variety and appellation by appellation, and it tightens as the named area narrows."),
    Q("What a rulebook controls",
      "Appellation rules routinely set a floor on the potential alcohol of the juice before any cellar work has begun. What is that floor really measuring?",
      ["How ripe the fruit was when it was picked",
       "How strong the wine will be after fortification",
       "How much sugar the cellar is allowed to add",
       "How much acidity the juice is carrying"], 0,
      "Sugar in the juice becomes alcohol, so a minimum potential alcohol is a ripeness test written in a unit a laboratory can verify in minutes. In a cold wet season it is the requirement that quietly puts fruit out of reach of the name its vineyard normally carries."),
    Q("What a rulebook controls",
      "Beyond boundary, grape and yield, European rulebooks commonly dictate two further things about the vineyard itself. Which pair?",
      ["Planting density and the pruning methods permitted",
       "The rootstock chosen and the orientation of the rows",
       "The size of the picking crew and the wage paid",
       "The make of tractor and the spraying schedule"], 0,
      "Both are proxies for how hard the vine is made to work: close spacing forces roots down and holds each plant to a modest crop, while a pruning rule caps the number of buds and therefore of bunches. It is how a rulebook reaches into the vineyard without ever tasting anything."),
    Q("What a rulebook controls",
      "Watering the vines is ordinary practice in Australia and California and restricted or forbidden across much of appellation Europe. What is the reasoning behind the restriction?",
      ["Irrigation loosens the tie between the season and the crop and lets a grower push past the yield the rules assume",
       "Irrigation water is thought to carry disease into the vineyard",
       "European aquifers are legally reserved for household use",
       "Wet soil prevents the roots from taking up minerals"], 0,
      "The objection is philosophical as much as agronomic: an appellation claims that the wine reflects its year and its ground, and a tap undermines both. Derogations in drought years have become steadily more common, which makes this one of the places European wine law is visibly moving."),
    Q("What a rulebook controls",
      "Officials sample the vineyards through the late summer and then fix the earliest date on which picking may begin. What does that rule exist to prevent?",
      ["Fruit being harvested before it reaches the ripeness the name requires",
       "Growers competing with one another to put the first wine of the vintage on sale",
       "Pickers being employed outside the declared season",
       "Machine harvesters being used in the cooler part of the day"], 0,
      "Sampling gives the decision an evidential basis rather than a calendar one, so the date moves with the season. The rule matters most in cool regions and in years when a grower is tempted to pick early and clear the crop before rain arrives."),
    Q("What a rulebook controls",
      "Origin law in Europe reaches from the line on the map through the vineyard and into the cellar. Which of these does it leave entirely to the producer?",
      ["The price at which the wine is sold",
       "The maximum yield per hectare",
       "The grape varieties that may be planted",
       "The minimum alcoholic strength at picking"], 0,
      "A denomination governs how wine is grown and made, not what it costs or who may buy it, so bottles from one village can sit ten times apart on the same list. Price control has been tried historically and is now vanishingly rare, since it turns a quality rulebook into a cartel."),

    # ------------------------------ percentages, volumes and tolerances (5) --
    Q("Percentages, volumes and tolerances",
      "European law will not let a bottle print a single grape name unless eighty-five percent of the wine is that grape, and American federal law asks for less than that. What does it ask for?",
      ["Seventy-five percent of the wine", "Ninety percent of the wine",
       "Fifty-one percent of the wine", "The same eighty-five percent that Europe asks"], 0,
      "A quarter of an American varietal wine may be something else entirely, and none of it need be declared anywhere, so a varietal label is a majority claim rather than a purity claim on either side of the Atlantic. The federal figure is a floor rather than a settlement: individual states may hold their own growers above it and several do, while no European appellation may go below the European figure."),
    Q("Percentages, volumes and tolerances",
      "A cask in a European cellar is topped up each year from the harvest that follows, and the producer still means to print one year on the label. How much of the wine may come from other years?",
      ["Fifteen percent of the volume", "Five percent of the volume",
       "Twenty-five percent of the volume", "None of it whatever"], 0,
      "European rules ask that eighty-five percent of a bottle carrying a year come from that harvest, and the margin exists so that a small topping-up from an adjacent year does not cost a wine its vintage. Other countries set their own figures, so a producer selling into several markets has to work to the strictest of them rather than to the rule at home. It matters most for wines held in cask and drawn on gradually, and a wine that cannot meet the figure simply goes out without a year on it."),
    Q("Percentages, volumes and tolerances",
      "A laboratory in Bordeaux finds 13.9 percent alcohol in a bottle whose label states 13.5 percent, and no offence has been committed. Why not?",
      ["Labelled strength carries a tolerance of half a percentage point either side of the true figure",
       "Alcohol statements are advisory and carry no legal force",
       "Any figure is lawful provided it has been rounded downward",
       "Tolerance applies only to wines sold outside the country of production"], 0,
      "Alcohol varies from vat to vat and analysis carries its own error, so labels are printed to a permitted margin rather than to a measurement. A wider tolerance is allowed for certain categories, including some wines matured for years before release, which is why two identically labelled bottles can genuinely differ. The half point is the European figure, and American rules allow a wider margin again."),
    Q("Percentages, volumes and tolerances",
      "Wine bottles arrive in a fixed set of sizes and never in, say, 600 millilitres. What accounts for that?",
      ["Law prescribes the nominal volumes in which wine may be sold",
       "Glassmakers settled on a voluntary industry standard",
       "Duty is chargeable only on those particular volumes, so no other size is worth filling",
       "Cork diameters limit the range of usable bottle necks"], 0,
      "The permitted list runs from small aircraft measures through the half and the standard bottle up to the magnum, above which European law simply stops prescribing, and it is consumer-protection law of the same family as net-quantity marking on any packaged good. A producer cannot invent a size to frustrate a price comparison on the shelf."),
    Q("Percentages, volumes and tolerances",
      "A grower brings in more fruit than his appellation's permitted yield allows. What becomes of the surplus?",
      ["It cannot carry the appellation name and goes out under a lower designation or to the still",
       "It may be sold under the appellation name at a reduced price once the surplus has been declared",
       "It must be left unharvested on the vine and written off",
       "The grower forfeits the appellation for his next three vintages"], 0,
      "The sanction attaches to the name rather than to the wine, so nothing is wasted and nothing is smuggled through. Push past the absolute ceiling that many rulebooks set above the permitted yield and the penalty is heavier still, since the whole of that year's crop loses the name rather than the excess alone. Rules of this kind are why a wet, generous year shows up in a region's paperwork as much as in its cellars."),

    # ------------------------ ladders, rungs and national variations (8) -----
    Q("Ladders, rungs and national variations",
      "Denominazione, Denominacion, Denominacao and Appellation all appear on European labels in four different languages. What single idea do all four express?",
      ["That the name on the bottle is a designation of origin fixed by law",
       "That the wine was matured in oak before release",
       "That the estate grew the fruit and bottled the wine on its own premises",
       "That the wine passed a government tasting panel"], 0,
      "All four are the local word for naming, three of them built on Latin nomen and the French on appellare, and all four wines sit in the same European category whatever the spelling. What follows the word is what tells you which national rung is meant."),
    Q("Ladders, rungs and national variations",
      "Set the French, Italian, Spanish and Portuguese systems side by side and the vocabulary differs completely while the structure matches almost step for step. What accounts for that?",
      ["The other three built on the French model, and all four now sit inside the same European framework",
       "All four were drafted together by a single commission in Brussels",
       "All four were modelled on a ripeness ladder",
       "The resemblance is coincidental, since each was built in isolation"], 0,
      "France wrote the modern pattern first, a delimited place bound to a production rulebook, and its neighbours adopted it over the following decades, long before any European harmonisation existed. The later European layer then tidied the categories without disturbing the shape underneath, which is why a student who learns one of the four can read the others quickly."),
    Q("Ladders, rungs and national variations",
      "An estate makes one of its country's most admired and expensive reds and sells it under the humblest geographical tier available. What does that reveal about the tiers?",
      ["A tier records compliance with a rulebook and not the standing of the wine",
       "The estate has been demoted for a breach of the rules",
       "The wine must in fact be of modest quality",
       "The tiers rank producers by reputation, so a famous estate sits at the top of them"], 0,
      "A producer who wants a grape or a technique the local rulebook forbids has to accept the lower name, and buyers who follow producers rather than appellations do not care. Several of the most sought-after wines in Europe are sold exactly this way, which is the strongest practical argument against reading a tier as a quality score."),
    Q("Ladders, rungs and national variations",
      "A celebrated property asks to have its own wines raised to the national top tier while its neighbours stay where they are. Why does that request normally fail?",
      ["The tier is granted to a delimited area and to everyone inside it, not to a company",
       "Only the state may initiate a promotion, never a producer",
       "The applicant must first be ranked by an independent tasting panel drawn from outside the region",
       "Top tiers are closed to privately owned estates"], 0,
      "Promotion is a decision about ground, so one estate's excellence argues for its whole appellation and never for itself alone. A few countries have created a category for a single property, and it is a deliberate exception written precisely because the general rule works the other way."),
    Q("Ladders, rungs and national variations",
      "Greece, Bulgaria and Romania all print the same pair of European origin categories on their labels as France and Italy do. What made that so?",
      ["All are European Union member states, so the same origin framework applies to them",
       "All three signed a bilateral treaty with France",
       "The World Trade Organization allocated the categories to them",
       "All three adopted the categories voluntarily, judging that European wording would help their exports"], 0,
      "The framework comes with membership rather than being an option a country weighs up. It means a Greek designation and a French one are the same legal object in different languages, which is why a sommelier can read the standing of a label from a country whose alphabet they cannot."),
    Q("Ladders, rungs and national variations",
      "One European country built its quality ladder on how much sugar the fruit carried at picking rather than on how tightly the boundary was drawn. Which country?",
      ["Germany", "France", "Italy", "Spain"], 0,
      "It is the deepest structural difference in European wine law: a ripeness ladder can be climbed anywhere in the country, while an origin ladder cannot be climbed at all, only inhabited. It also means the most prominent quality word on such a label says nothing whatever about which vineyard the wine came from."),
    Q("Ladders, rungs and national variations",
      "Wine rules in one Alpine country are written canton by canton, so the yield ceiling for the same grape changes as you cross a lake. Which country?",
      ["Switzerland", "Austria", "Slovenia", "France"], 0,
      "A federal layer sets the outline and each canton fills in appellations, ceilings and ripeness minimums for itself. The fragmentation is one reason so little of the wine is seen abroad, since no single national name ever gathered enough recognition to sell on."),
    Q("Ladders, rungs and national variations",
      "A ladder built on sugar at harvest is steadily losing its power to separate one wine from another as the growing season warms. Why?",
      ["Ripeness that was once exceptional is now reached routinely, so the upper rungs stop carrying information",
       "Must weight can no longer be measured accurately in warm conditions",
       "European law now forbids ladders based on must weight",
       "Growers deliberately pick unripe to avoid the higher rungs"], 0,
      "A rung means something only while it is hard to reach, and warming has made the middle of such a ladder attainable in most sites in most years. That pressure is why growers' associations built vineyard hierarchies of their own from the 1990s, and why a ripeness ladder is now typically set alongside an origin pyramid that narrows from a region through a sub-region and a village down to a single vineyard, rather than being replaced by one."),

    # -------------------------------------- frameworks beyond europe (6) -----
    Q("Frameworks beyond Europe",
      "Letters on a Canadian label stand for an alliance whose rules reach past simply tracing where the fruit grew. What else does it require?",
      ["That the wine pass a laboratory analysis and an expert tasting panel before release",
       "That the wine be aged in Canadian oak",
       "That the producer own every vineyard the fruit came from rather than buying any of it in",
       "That the wine be held a minimum of two years before release"], 0,
      "The Vintners Quality Alliance also fixes minimum ripeness and a list of permitted varieties, which puts it much closer to a European appellation than to most schemes in the New World. It is a useful corrective to the idea that the two hemispheres regulate wine in fundamentally different ways."),
    Q("Frameworks beyond Europe",
      "Before rules settled in 2015, a bottle sold as Japanese wine could be made from imported bulk juice and never see a Japanese grape. What did those rules require?",
      ["That only wine from grapes grown in Japan may be called Japan Wine",
       "That every bottle carry a tasting panel number",
       "That imported juice be capped at fifteen percent of any blend sold at home",
       "That the grape variety always be stated on the front label"], 0,
      "Wine bottled domestically from foreign juice now has to say so, which separated a small quality sector from a large blending trade at a stroke. The standard was set in 2015 and came into force three years later, after a transition that let the old labels run out. It is a recent instance of the oldest idea in wine law: make the label say where the fruit actually grew."),
    Q("Frameworks beyond Europe",
      "Several countries outside Europe agreed by treaty to stop using European place names as style words for their own fortified and sparkling wines. What did that oblige them to do?",
      ["Invent or adopt replacement names for those styles",
       "Pay a licence fee to the European producers concerned",
       "Restrict those wines to their own domestic markets",
       "Stop making those styles altogether"], 0,
      "It is geographical-indication protection in its most practical form: a word treated as a style description for a century turned out to belong to somebody else. Some of the replacement terms have since become respected names in their own right, which was not obvious at the time."),
    Q("Frameworks beyond Europe",
      "American labels once carried the words Chablis, Burgundy and Champagne on wine grown nowhere near any of those places. What closed the practice to new brands?",
      ["A 2006 trade agreement with the European Union that shut the names to any brand not already using them",
       "A Supreme Court ruling on consumer deception",
       "The registration of those names as American trademarks",
       "A federal statute banning all foreign place names on domestic wine"], 0,
      "Brands already using the terms were allowed to continue, which is why a small number of such labels survive on shelves. Grandfather the old and close the door on the new is the standard settlement when a long-established brand collides with a protected indication."),
    Q("Frameworks beyond Europe",
      "A European appellation wants its name defended in a country that keeps no register of geographical indications at all. What is the usual route?",
      ["A bilateral agreement, or registering the name there as a collective or certification mark",
       "Nothing can be done until that country builds a register",
       "The World Trade Organization enforces the name directly on request",
       "The name is automatically protected everywhere once registered at home"], 0,
      "Protection is territorial, so a name vigorously defended at home may be free for anyone to use a border away until something is signed or filed. It is why certain famous European names exist as appellations in one country and as trademarks in another, doing the same job through different machinery."),
    Q("Frameworks beyond Europe",
      "Appellations outside Europe were mostly drawn as boundaries first, with production rules arriving late or never at all. Which explanation is usually given?",
      ["Those regions were planted by growers free to choose their own varieties and methods, so there was no settled practice for a law to write down",
       "Their governments lacked the constitutional power to regulate farming",
       "European law forbade them from adopting production rules of their own",
       "Their climates are so reliable that production rules would serve no purpose"], 0,
      "A European appellation codifies what growers were already doing; a newer one records where growers turned out to be doing well. That difference in order, rather than any difference in seriousness, is the honest account of why one kind of system dictates the grape and the other does not."),

    # ------------- inspection, enforcement and the limits of the law (6) -----
    Q("Inspection, enforcement and the limits of the law",
      "Nothing in the glass or in the laboratory proves with certainty which vineyard a wine came from. What does that force every origin scheme in the world to rest on?",
      ["Audited records following the fruit from the vineyard through the cellar to the bottle",
       "Chemical fingerprinting of the finished wine, which can place any bottle in its own vineyard",
       "The word of the producer, backed by nothing",
       "A panel of tasters familiar with the region"], 0,
      "Isotope and trace-element work can corroborate a claim, but it cannot originate one, so paperwork carries the whole weight of origin law. That is also why wine fraud is overwhelmingly a documents crime rather than a cellar one, and why inspectors spend their days in offices."),
    Q("Inspection, enforcement and the limits of the law",
      "A dismal vintage in a famous appellation still produces bottles carrying the full appellation name. Why does the law allow that?",
      ["Compliance is tested wine by wine each year, and the standing of the year itself is not a legal question",
       "The appellation is suspended automatically in years officially rated poor",
       "Members vote each year on whether the name may be used",
       "The name may be used only once a vintage rating has been published"], 0,
      "A rulebook can ask whether this wine met the requirements and cannot ask whether the season was any good. Producers answer the gap themselves by declassifying weak lots, and the buyer answers it by knowing the year, which is why vintage knowledge survives in an age of technical competence."),
    Q("Inspection, enforcement and the limits of the law",
      "Alongside origin law, a second and entirely separate body of law governs wine almost everywhere and has nothing to do with where it grew. Which?",
      ["Excise duty and the licensing of its sale",
       "The authorisations that cap new vineyard planting",
       "The ranking of a region's vineyards into crus",
       "The safety rules covering machinery in the cellar"], 0,
      "Duty is charged by volume and often by strength, which is why bottle sizes, strength statements and cellar registers interest revenue authorities as much as wine bodies. A sommelier meets this body of law every working night, in service hours, in age checks and in the terms of the premises licence."),
    Q("Inspection, enforcement and the limits of the law",
      "Until 2012 a European bottle could claim only to be made from organically grown grapes, never to be organic wine. What did the regulation of that year add?",
      ["Rules governing the cellar as well as the vineyard, including a lower ceiling on sulphur dioxide",
       "A prohibition on all added sulphur dioxide",
       "A requirement that the wine be sold unfiltered, so that nothing is stripped out after fermentation",
       "A ban on exporting organic wine outside the union"], 0,
      "Certification had stopped at the winery door, so nothing in law said what could be done to the fruit once it arrived. Fixing permitted cellar practices completed the claim and turned a farming certificate into a description of the wine itself."),
    Q("Inspection, enforcement and the limits of the law",
      "A merchant leaves a case of classified wine beside a radiator for a summer and pours it, cooked, to a guest. What does the appellation's rulebook say about that?",
      ["Nothing at all, since its requirements are spent once the wine leaves the producer",
       "The name is forfeited automatically as soon as a bottle is found in poor condition",
       "The producer must replace any bottle spoiled in storage",
       "Storage temperature is fixed by the rulebook all the way down to the glass"], 0,
      "A wine that satisfied every requirement in the vineyard and the cellar can still be destroyed in a hot warehouse or a sunlit window, and no origin law reaches that far. Everything after the sale is left to trade practice and to ordinary consumer law, which is why a merchant's and a sommelier's own handling matters more to what the guest tastes than any letters on the label do."),
    Q("Inspection, enforcement and the limits of the law",
      "Inspections, laboratory work and the administration behind a European denomination all cost money. Who pays for them?",
      ["The producers who use the name, through levies on their own production",
       "General taxation in the member state, since the controls serve the public",
       "The European Commission, from a central fund",
       "The buyer, through a surcharge collected at retail"], 0,
      "A denomination is largely self-financing, which gives its members a direct interest in how thoroughly it is policed and in who else is admitted to use the name. It also explains why a small appellation with few producers struggles to fund the controls a large one takes for granted."),
]
