"""Rank II rewrite - Bordeaux (54 questions: 20 MC, 34 short answer).

Certified level, pitched deliberately above the Rank I "Bordeaux" category.
Where Rank I names the First Growths, this asks what the brokers of 1855 were
actually ranking and what has moved since; where Rank I says Sauternes owes its
sweetness to noble rot, this asks what botrytis does that raisining does not and
why cryoextraction is argued about. Nothing here repeats a Rank I task.

The running order is built around one idea: a Bordeaux label is a claim about
three separate things - a place, a rank and a trading arrangement - and a
Certified candidate has to be able to take the three apart. So the classifications
come first and are treated as documents with authors, revisions and lawsuits;
then the appellations; then the ground underneath them; then the rules and the
trade that move the wine.

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py.

Accept lists are built against lib.match_sa, a port of core.js matchSA, and were
tested rather than eyeballed. No '~' entries appear anywhere: the tilde is
exact-OR-containment, so a one-word tilde grades any wrong answer holding that
word. Where a real and different wine or rank extends or truncates the right
answer - Bordeaux against Cotes de Bordeaux, Fronsac against Canon-Fronsac,
Pomerol against Lalande-de-Pomerol, Cru Bourgeois against the full three-tier
answer, Bouchet against Petit Bouchet, sweet white against plain white - the
wrong form was run through match_sa to confirm it does NOT grade, and ex=True
with listed phrasings was applied to the nine questions where it did. Each of
those lists was then widened until every natural phrasing of its own answer
still grades, because exact matching rejects anything not written down.

Facts are restricted to ones that do not drift. Ownership, production volumes,
price standings and the newest classification memberships are deliberately
absent; ageing minima, permitted varieties, geology, geography, classification
structure and technique carry the weight instead.
"""

from lib import Q, SA

CAT = "Bordeaux"
SLUG = "r2-bordeaux"
PREFIX = "c"
RANK = "Rank II"
SOURCE = "data-questions.js"

SYLLABUS = [
    ("The 1855 list as a document", 6),
    ("Graves, Saint-Emilion and Cru Bourgeois", 6),
    ("Communal appellations of the Left Bank", 6),
    ("The appellations sommeliers forget", 6),
    ("Soil, gravel and drainage", 6),
    ("Varieties and the permitted list", 6),
    ("Ageing minima and elevage", 5),
    ("Sauternes, Barsac and botrytis", 6),
    ("Dry whites and Pessac-Leognan", 4),
    ("The trade, en primeur and second wines", 3),
]

BANK = [
    # -------------------------------------- The 1855 list as a document (6) --
    Q("The 1855 list as a document",
      "Brokers working for the 1855 exposition wrote down estate names, not plots of ground. What follows for a classified growth that later buys a neighbouring parcel?",
      ["The rank travels with the name, so approved fruit from the added land may go into the classified wine",
       "The added land is barred from the classified wine for fifty years",
       "The estate drops a tier until the list is next reviewed",
       "The parcel keeps the rank of whoever farmed it in 1855"], 0,
      "This is the standing complaint against 1855: it ranked commercial names rather than delimited vineyard, so holdings could grow, shrink and swap without the rank moving. A Burgundian classification does the opposite, fixing the boundary and letting the owner change."),
    Q("The 1855 list as a document",
      "A guest insists the red side of the 1855 ranking has never been altered. Which correction is accurate?",
      ["It has been altered twice: an estate added within a year of publication, and one promotion in 1973",
       "It has been altered once, when Haut-Brion was written in during 1953",
       "It is rebuilt every decade in the same way Saint-Emilion's is",
       "It has been altered three times, the last of them in the 1990s"], 0,
      "Cantemerle was omitted and inserted almost immediately, and Mouton Rothschild rose from Second to First in 1973. Haut-Brion was in the original list from the start, which is what makes that distractor tempting to anyone who half-remembers the Graves connection."),
    SA("The 1855 list as a document",
       "Left off the exposition list and restored as a Fifth Growth within the year after its owner objected, which Medoc estate was the first correction ever made?",
       "Cantemerle",
       ["cantemerle", "cantemerle in macau",
        "chateau cantemerle in the haut medoc"],
       "The wine had been sold direct to the Dutch trade rather than through the Bordeaux market, so the brokers had no local price record for it. That is a neat illustration of what the list was really measuring: presence on one city's exchange."),
    SA("The 1855 list as a document",
       "Below Chateau d'Yquem, the Sauternes side of 1855 holds two ranks of classified growth. Name them.",
       "Premier Cru and Deuxieme Cru",
       ["premier cru and deuxieme cru", "premier cru deuxieme cru",
        "deuxieme cru and premier cru", "premiers crus and deuxiemes crus",
        "first growth and second growth", "first growths and second growths",
        "premier crus and deuxieme crus",
        "premier cru classe and deuxieme cru classe",
        "deuxieme cru classe and premier cru classe",
        "premier cru classe deuxieme cru classe",
        "premiers crus classes and deuxiemes crus classes"],
       "Yquem sits alone above them as Premier Cru Superieur, a tier invented for it. The reds got five tiers and the sweet wines two, which tells you how much finer the price gradations were thought to be on the Left Bank.",
       ex=True),
    SA("The 1855 list as a document",
       "Suppose a classified chateau buys vineyard from an unclassified neighbour. Which national body decides whether that ground is entitled to the appellation the classified wine carries?",
       "The INAO",
       ["inao", "institut national de l'origine et de la qualite",
        "the national appellation body", "institut national des appellations d'origine"],
       "The rank is a private nineteenth-century verdict, but the appellation on the same label is a state matter, and parcel eligibility is settled by the INAO against the delimited zone. So the classification cannot be enlarged by purchase alone: the land has to already be inside the right appellation."),
    SA("The 1855 list as a document",
       "Moving an estate between tiers of the 1855 reds needed something the trade could not grant on its own. What instrument finally did it in 1973?",
       "A ministerial decree",
       ["ministerial decree", "a decree from the agriculture minister",
        "government decree", "ministerial order", "a decree of the minister of agriculture"],
       "Baron Philippe pressed for fifty years and the change came by decree of the agriculture ministry, not by any vote of brokers. That is precisely why nobody expects a second one: there is no standing mechanism, only a political act."),

    # ------------------------------ Graves, Saint-Emilion and Cru Bourgeois (6)
    Q("Graves, Saint-Emilion and Cru Bourgeois",
      "Graves drew up its own classification for reds in 1953 and finished the job with whites in 1959. How is the resulting list arranged?",
      ["One tier only, with estates classified for red, for white, or for both",
       "Five tiers, deliberately mirroring the 1855 reds",
       "Two lettered categories, A and B", "Three tiers reviewed every ten years"], 0,
      "There is no hierarchy inside it: an estate is a Cru Classe de Graves or it is not, and the entry records which colour it was classified for. Haut-Brion is classified for its red alone, so its white, one of the most expensive dry whites in France, carries no rank at all."),
    Q("Graves, Saint-Emilion and Cru Bourgeois",
      "Two bottles from the same Right Bank village read Saint-Emilion Grand Cru and Saint-Emilion Grand Cru Classe. What separates them?",
      ["The first is an appellation with stricter rules, the second is a rank held by a named estate",
       "The first is a rank, the second is a wine from purchased fruit",
       "The first is declassified wine from a classified estate, the second is the grand vin",
       "They are two spellings of one thing and mean the same"], 0,
      "Saint-Emilion Grand Cru is open to anyone in the zone who meets lower yields, higher minimum alcohol and a longer elevage with an approval tasting. Grand Cru Classe is a place on the classification, held by a specific chateau, and the word Classe is the entire difference on the shelf."),
    SA("Graves, Saint-Emilion and Cru Bourgeois",
       "Every estate on the Graves classified list now sits inside a single appellation carved out in 1987. Which appellation contains them all?",
       "Pessac-Leognan",
       ["pessac leognan", "pessac leognan aoc", "the pessac leognan appellation"],
       "The classified estates all lie in the northern communes nearest the city, which is exactly the ground the 1987 appellation was drawn around. Nothing in the southern half of Graves was ever classified, so the two lists coincide entirely."),
    SA("Graves, Saint-Emilion and Cru Bourgeois",
       "Rebuilt after its own annulment, the Medoc ranking outside 1855 now runs to three ascending levels. Name them in order.",
       "Cru Bourgeois, Cru Bourgeois Superieur and Cru Bourgeois Exceptionnel",
       ["cru bourgeois cru bourgeois superieur and cru bourgeois exceptionnel",
        "cru bourgeois cru bourgeois superieur cru bourgeois exceptionnel",
        "cru bourgeois cru bourgeois superieur and exceptionnel",
        "cru bourgeois superieur and exceptionnel",
        "cru bourgeois superieur exceptionnel",
        "cru bourgeois then superieur then exceptionnel",
        "bourgeois superieur and exceptionnel"],
       "The tiers were abolished in the 2000s after litigation, leaving a flat annual selection of individual wines, and were restored when the system was rebuilt around estate-level assessment. Exceptionnel is the smallest group and carries requirements on vineyard management and cellar practice, not only on the tasting.",
       ex=True),
    SA("Graves, Saint-Emilion and Cru Bourgeois",
       "Unlike an 1855 growth, a Cru Bourgeois estate holds its standing only for a fixed run of harvests before it must reapply. How long does the award now run?",
       "Five vintages",
       ["five vintages", "5 vintages", "five years", "5 years", "five consecutive vintages",
        "five", "5", "five harvests", "5 harvests", "five vintages at a time"],
       "Reapplication is the whole point of the exercise: the rank is meant to describe present performance rather than a nineteenth-century price list. It also means the label statement is tied to the vintage in the bottle, not to the chateau in perpetuity.",
       ex=True),
    SA("Graves, Saint-Emilion and Cru Bourgeois",
       "Ausone and Cheval Blanc held the top rank of the Saint-Emilion classification alone for decades. In the 2012 revision, which two estates were raised to join them?",
       "Angelus and Pavie",
       ["angelus and pavie", "pavie and angelus", "angelus pavie", "pavie angelus"],
       "Both promotions were contested in court, which is the recurring feature of this classification rather than an accident: because rank is revisable it is worth suing over, and because it is written into the appellation rules the state ends up in the argument. The 1855 list attracts no litigation for the opposite reason.",
       ex=True),

    # --------------------------- Communal appellations of the Left Bank (6) --
    Q("Communal appellations of the Left Bank",
      "Only one of the Medoc's great communal appellations extends well beyond the village that names it. Which group of communes does Margaux also cover?",
      ["Cantenac, Soussans, Arsac and Labarde", "Listrac, Moulis and Avensan",
       "Cussac, Lamarque and Arcins", "Macau, Ludon and Saint-Laurent"], 0,
      "Five communes in all share the name, which is much of why Margaux is the least uniform of the four in soil and in style. An address in Cantenac or Labarde is labelled Margaux with nothing on the bottle to say so."),
    Q("Communal appellations of the Left Bank",
      "One of the four famous Medoc communes holds no First Growth at all, yet nearly all of its vineyard is classified. Which commune is that?",
      ["Saint-Julien", "Saint-Estephe", "Margaux", "Pauillac"], 0,
      "Saint-Julien is small, tightly drawn and dominated by classified estates, so the average bottle carrying the name is a serious wine. Saint-Estephe is larger and has proportionally far more unclassified land, which is why its name alone tells you less."),
    SA("Communal appellations of the Left Bank",
       "Wines from the northernmost of the four great communes are firmer and slower than their neighbours because a water-retaining layer sits under the gravel. Name that layer.",
       "Clay",
       ["clay", "clay subsoil", "dense clay", "clay beneath the gravel", "cold clay"],
       "Saint-Estephe's gravel is shallower and the clay under it holds water, so the vine suffers less drought stress and the wines carry more flesh and more grip. Latour's Enclos in Pauillac shows the same effect in miniature, which is one reason it performs in dry years."),
    SA("Communal appellations of the Left Bank",
       "Great Medoc sites are almost all built on a low mound of gravel standing a few metres proud of the surrounding land. What is the local term for such a mound?",
       "Croupe",
       ["croupe", "croupes", "gravel croupe"],
       "The height is trivial in absolute terms and decisive in practice: it puts the water table further below the roots and lets cold air drain away downslope. The old Medoc saying that the best vines see the river is really a statement about being on a croupe."),
    SA("Communal appellations of the Left Bank",
       "Running north from the city, the Haut-Medoc appellation stops where the plain Medoc appellation begins. Which commune marks that northern boundary?",
       "Saint-Seurin-de-Cadourne",
       ["saint seurin de cadourne", "st seurin de cadourne",
        "the commune of saint seurin de cadourne"],
       "North of it the peninsula flattens, the gravel thins and clay takes over, which is the physical reason the line falls where it does. Everything beyond is entitled only to Medoc, whatever the quality in the glass."),
    SA("Communal appellations of the Left Bank",
       "A Pauillac estate bottles a white wine from Sauvignon Blanc grown among its Cabernet. Which appellation must that bottle carry?",
       "Bordeaux Blanc",
       ["bordeaux blanc", "bordeaux", "bordeaux aoc", "bordeaux blanc aoc",
        "aoc bordeaux blanc", "aoc bordeaux", "regional bordeaux blanc",
        "regional bordeaux", "the bordeaux appellation",
        "the regional white appellation", "plain bordeaux blanc"],
       "Every communal appellation in the Medoc is for red wine only, so a white from Pauillac drops straight to the regional level however grand the address. Mouton's Aile d'Argent and the white of Margaux are sold exactly this way.",
       ex=True),

    # ------------------------------- The appellations sommeliers forget (6) --
    Q("The appellations sommeliers forget",
      "Four existing cotes appellations were folded into a single umbrella denomination in 2009, each keeping its own name as a prefix. Which four?",
      ["Blaye, Cadillac, Castillon and Francs", "Bourg, Blaye, Fronsac and Castillon",
       "Cadillac, Loupiac, Sainte-Croix-du-Mont and Blaye",
       "Castillon, Francs, Bourg and Graves de Vayres"], 0,
      "Sainte-Foy joined the union later and Cotes de Bourg stayed out of it altogether, which is the detail that catches people. A wine may also be sold as plain Cotes de Bordeaux without any prefix if the fruit is blended across the zones."),
    Q("The appellations sommeliers forget",
      "Two communal appellations of the Medoc sit inland behind the main gravel ridge and hold no classified growth between them. Which pair?",
      ["Moulis and Listrac", "Macau and Arcins", "Cussac and Lamarque",
       "Avensan and Soussans"], 0,
      "Both are entitled to their own communal names, so they outrank the surrounding Haut-Medoc while sitting outside the 1855 story entirely. Their clay and limestone gives sterner, less immediately charming wine, which is much of why the brokers of 1855 priced them below the riverside communes."),
    SA("The appellations sommeliers forget",
       "A modest stream runs east to west across the Right Bank, marking the northern limit of Pomerol and of Saint-Emilion, with the satellite appellations lying beyond it. Name that stream.",
       "The Barbanne",
       ["barbanne", "barbanne stream", "riviere barbanne", "the barbanne river"],
       "It is small enough to step across and it is nonetheless one of the most consequential lines in Bordeaux, because Lalande-de-Pomerol and the four Saint-Emilion satellites all begin on the far side of it. Old local lore held that the good wine was on the southern bank and the witches on the northern one."),
    SA("The appellations sommeliers forget",
       "Inside Fronsac sits a smaller appellation drawn around two limestone hills above the Dordogne. Name that inner appellation.",
       "Canon-Fronsac",
       ["canon fronsac", "canon fronsac aoc", "the canon fronsac appellation"],
       "It covers the slopes of the Canon and Saint-Michel hills, where molasse and limestone replace the sandier ground of Fronsac proper. Any grower in Canon-Fronsac may declassify to Fronsac; the reverse is not possible, which is the practical test of which sits above the other."),
    SA("The appellations sommeliers forget",
       "Looking across the estuary at the Medoc, one Right Bank cotes appellation has kept a real planting of a red variety now scarce elsewhere in Bordeaux. Which variety?",
       "Malbec",
       ["malbec", "cot", "malbec cot", "malbec or cot", "malbec grape"],
       "Cotes de Bourg is the one place in the region where the grape is still treated as a serious blending component rather than a relic. Its early budding and poor fruit set are why the rest of Bordeaux replanted to Merlot after the 1956 frost."),
    SA("The appellations sommeliers forget",
       "North of the Barbanne lies an appellation of its own that absorbed the neighbouring commune of Neac and is often sold as a cheaper route to Merlot on clay. Name it.",
       "Lalande-de-Pomerol",
       ["lalande de pomerol", "lalande de pomerol aoc",
        "the lalande de pomerol appellation", "lalande"],
       "Neac had its own appellation until it was merged in, and the eastern part of the zone on gravel over clay is the part that most resembles Pomerol itself. The western half is sandier and gives the lighter wines that set the price expectation for the whole name."),

    # ------------------------------------------- Soil, gravel and drainage (6)
    Q("Soil, gravel and drainage",
      "Rounded stones the size of a fist lie metres deep across the best Medoc vineyards. How did they get there?",
      ["Rivers carried them down from the Pyrenees and the Massif Central during the Ice Ages",
       "They weathered in place out of the limestone bedrock",
       "They were dredged from the estuary and spread by growers",
       "They blew inland as gravel from the Atlantic dunes"], 0,
      "Glacial meltwater moved enormous volumes of stone north along the Garonne and dumped it in terraces as the flow slackened. The stones are therefore foreign to the Medoc, which is why the ground changes character the moment you step off a terrace."),
    Q("Soil, gravel and drainage",
      "Two Saint-Emilion estates lie a kilometre apart, one at the edge of the limestone plateau and one on sand at the foot of the slope. What difference in the wines should you predict?",
      ["The plateau gives firmer, slower, longer-lived wine; the sand gives lighter, earlier-drinking wine",
       "The sand gives the more tannic and longer-lived wine of the two",
       "The plateau gives sweeter wine because limestone raises sugar",
       "There is no reliable difference, since both are planted to Merlot"], 0,
      "Limestone holds a water reserve and keeps acidity, so the plateau wines have structure and a long life. The sandy foot of the cotes warms fast and drains hard, giving perfumed, supple wine that is ready early and does not repay cellaring."),
    SA("Soil, gravel and drainage",
       "Under the Pomerol plateau runs a pan of iron-cemented sand, usually called crasse de fer. Growers also give it a blacksmith's name. What is that second term?",
       "Machefer",
       ["machefer", "machefer clinker", "machefer or clinker"],
       "Machefer is the word for forge clinker, which is what the stuff looks like when a trench cuts through it. The pan slows drainage, so the vine still has water in a dry August, and growers have long credited it with the iron, truffled note of the best of the plateau."),
    SA("Soil, gravel and drainage",
       "Saint-Emilion's plateau is quarried for building stone as well as planted with vines, and its limestone carries a name taken from the fossils in it. Name that limestone.",
       "Calcaire a asteries",
       ["calcaire a asteries", "asteries limestone", "starfish limestone",
        "calcaire a asteries limestone"],
       "The asteries are fragments of fossil starfish left in an Oligocene marine deposit. The same rock was cut out from beneath the town for the buildings above it, which is why the plateau is riddled with cellars at a constant temperature."),
    SA("Soil, gravel and drainage",
       "Before the seventeenth century the Medoc was largely marsh, and foreign engineers were brought in to drain it and expose the gravel. Which country did they come from?",
       "The Netherlands",
       ["netherlands", "holland", "dutch", "dutch engineers", "the low countries"],
       "Dutch drainage work is the reason the Medoc has a wine industry at all, and their trade is also why so much early Medoc wine went north rather than to Paris. The drainage channels they cut are still called jalles and still do the job."),
    SA("Soil, gravel and drainage",
       "Deep gravel gives a vine no water reserve to speak of, and in a fine year that shortage is a virtue rather than a problem. What is the term for the mild, controlled version of it?",
       "Water stress",
       ["water stress", "mild water stress", "moderate water stress",
        "hydric stress", "controlled water deficit", "water deficit"],
       "A vine denied water at veraison stops making leaves and puts its effort into ripening the fruit, which concentrates the berry and thickens the skin. Push it further and the vine shuts down altogether, which is why the same gravel that makes a great dry vintage makes a hard one in drought."),

    # --------------------------------------- Varieties and the permitted list (6)
    Q("Varieties and the permitted list",
      "Six new varieties were admitted to the Bordeaux and Bordeaux Superieur appellations in 2021 as an adaptation to a warming climate. What limits came with them?",
      ["No more than five percent of the planted area and ten percent of the blend",
       "No limit on planting, but no more than twenty percent of the blend",
       "They may be used in second wines only",
       "They may be used for rose and clairet only"], 0,
      "The caps are what make the change conservative: the varieties are there to be trialled, not to remake the blend. They are also confined to the two regional appellations, so a communal wine such as Pauillac or Margaux may not use them at all."),
    Q("Varieties and the permitted list",
      "Beyond Sauvignon Blanc, Semillon and Muscadelle, a white Bordeaux may carry a minority of three older accessory varieties. Which trio?",
      ["Colombard, Ugni Blanc and Merlot Blanc", "Chardonnay, Chenin Blanc and Viognier",
       "Riesling, Aligote and Melon de Bourgogne",
       "Petit Manseng, Gros Manseng and Courbu"], 0,
      "They are capped at a minority share and are mostly a legacy of the distilling and bulk trade, since Colombard and Ugni Blanc are the Cognac grapes. Merlot Blanc really is a child of Merlot, a natural crossing with Folle Blanche found in the Gironde in 1891, and it is now nearly gone."),
    Q("Varieties and the permitted list",
      "Carmenere remains a permitted Bordeaux red and is almost never seen there. What drove it out?",
      ["It ripens very late, sets its crop badly and grafted poorly when the region replanted",
       "The 1855 brokers struck it from the classified estates",
       "DNA work showed it to be Merlot under another name",
       "Its wines were barred from export by the negociants"], 0,
      "Coulure and late ripening made it unreliable in a maritime climate, and replanting after phylloxera was the moment growers dropped it. It went to Chile before all this, where it was long mistaken for Merlot, and it ripens there in a way it rarely did at home."),
    SA("Varieties and the permitted list",
       "A pink-skinned mutation of Sauvignon Blanc is permitted for white Bordeaux and valued for the weight and stone-fruit character it adds. Name it.",
       "Sauvignon Gris",
       ["sauvignon gris", "sauvignon gris grape", "gris de sauvignon"],
       "It gives lower acidity and a broader palate than Sauvignon Blanc, so it is used the way Semillon is, to fill out the middle. Several Pessac-Leognan whites carry a few percent of it and never mention it on the label."),
    SA("Varieties and the permitted list",
       "Bordeaux growers have an old local name for Malbec, still used in the Medoc and quite different from the one used on the Right Bank. What is the Medoc name?",
       "Cot",
       ["cot", "cot in the medoc", "cot or pressac", "pressac or cot",
        "cot also called pressac", "cot malbec", "cot the medoc name for malbec"],
       "Pressac is the Right Bank name, said to come from the family that spread the vine around Saint-Emilion, and Auxerrois is what the same grape is called in Cahors. One variety with four names is a standard trap on a blind tasting sheet.",
       ex=True),
    SA("Varieties and the permitted list",
       "Around Saint-Emilion, Cabernet Franc goes by a local name that older growers still use in conversation. What is that name?",
       "Bouchet",
       ["bouchet", "gros bouchet", "bouchet or gros bouchet", "gros bouchet or bouchet",
        "bouchet in saint emilion", "bouchet on the right bank"],
       "Cheval Blanc's plantings were traditionally described in those terms, and the same grape is Breton in the Loire. Petit Bouchet is the local name for Cabernet Sauvignon, so the qualifier carries the whole of the difference, and knowing it is what separates following a Right Bank grower's description of a blend from guessing at it.",
       ex=True),

    # ------------------------------------------ Ageing minima and elevage (5)
    Q("Ageing minima and elevage",
      "Cellar hands walk the rows of barriques every week or two with a jug, filling each one back up to the bung. Which operation is this?",
      ["Ouillage", "Soutirage", "Collage", "Assemblage"], 0,
      "Wine evaporates through the staves, and the space left behind would let the wine oxidise and acetify. Topping up keeps the barrel brim full, which is why a traditional cellar is measured in labour as much as in oak."),
    Q("Ageing minima and elevage",
      "At what point in the cycle does a classified chateau normally settle the proportions of its grand vin?",
      ["In the winter or spring after the harvest, before the wine is shown en primeur",
       "At the press, so the varieties ferment together",
       "Immediately before bottling, about two years after the harvest",
       "Only after the first year's sales figures are known"], 0,
      "Lots are fermented and kept separate by variety and by parcel, then tasted and assembled early, so what the trade tastes in the spring is already the blend. The lots left out go to the second wine or are sold off in bulk."),
    SA("Ageing minima and elevage",
       "Drawing clear wine off its sediment from one barrel to another, a cellarman sets a lit candle behind the glass to watch for the first cloud. Name the operation.",
       "Soutirage",
       ["soutirage", "soutirage a la bougie", "racking", "racking by candle",
        "candle racking"],
       "Racking every three months or so in the first year both clarifies the wine and gives it a measured dose of air, which softens tannin. The candle is the oldest gauge there is: the moment the stream turns hazy, the cellarman stops."),
    SA("Ageing minima and elevage",
       "Classified-growth reds are still clarified before bottling with a traditional agent whipped up at five or six per barrique. What is that agent?",
       "Egg white",
       ["egg white", "egg whites", "fresh egg white", "fresh egg whites",
        "beaten egg white", "beaten egg whites", "whipped egg white",
        "whipped egg whites", "albumen", "egg albumen", "white of egg",
        "whites of egg", "blanc d'oeuf", "blancs d'oeufs"],
       "The albumen binds the harshest tannins and carries them to the bottom, softening the wine without stripping it the way a heavy filtration would. It is one reason a classified Bordeaux is not usually vegan, and estates that skip it now often bottle unfined instead.",
       ex=True),
    SA("Ageing minima and elevage",
       "Bordeaux has a traditional-method sparkling appellation of its own, and the rules set a floor for time on the lees. How long?",
       "Nine months",
       ["nine months", "9 months", "nine months on the lees", "9 months on the lees",
        "nine months ageing on lees", "nine", "9",
        "nine months minimum", "at least nine months"],
       "Cremant de Bordeaux is made from the region's own varieties, whites and reds alike, and the nine-month floor is the standard Cremant requirement across France. Non-vintage Champagne must spend twelve months on its lees inside a fifteen-month minimum before release, which is a fair measure of how much of that category's character is bought with time.",
       ex=True),

    # -------------------------------------- Sauternes, Barsac and botrytis (6)
    Q("Sauternes, Barsac and botrytis",
      "Some estates chill picked bunches until part of the load freezes, then press. What does the technique achieve, and why is it argued over?",
      ["Water in the least concentrated berries freezes first, so only the richest juice runs, which critics call a cellar substitute for selecting in the vineyard",
       "It kills the botrytis before fermentation, which critics say removes the wine's aroma",
       "It extracts colour from the skins, which critics say makes the wine too dark",
       "It precipitates tartrates and raises acidity, which critics say unbalances the wine"], 0,
      "Cryoextraction works on the difference in freezing point between dilute and concentrated juice, so it removes the water a rainy harvest put back into the berries. It is legal, and the objection is that it rescues fruit that selective picking would have left behind."),
    Q("Sauternes, Barsac and botrytis",
      "Grapes left to raisin on the vine also concentrate their sugar. What does noble rot do beyond that?",
      ["It consumes some acid and sugar and leaves glycerol and its own aroma compounds behind",
       "It adds tannin drawn out of the skins",
       "It raises the total acidity of the juice",
       "It removes the need for a selective harvest"], 0,
      "Passerillage is pure dehydration, so the juice is simply a more concentrated version of what was there. Botrytis is an organism living in the berry: it metabolises part of the crop and leaves glycerol, gluconic acid and the honeyed, saffron notes that raisined fruit never shows."),
    SA("Sauternes, Barsac and botrytis",
       "Sauternes and Barsac name two of the five communes entitled to the appellation. Name the three others.",
       "Bommes, Fargues and Preignac",
       ["bommes fargues and preignac", "bommes fargues preignac",
        "bommes preignac and fargues", "bommes preignac fargues",
        "fargues bommes and preignac", "fargues bommes preignac",
        "fargues preignac and bommes", "fargues preignac bommes",
        "preignac bommes and fargues", "preignac bommes fargues",
        "preignac fargues and bommes", "preignac fargues bommes"],
       "Yquem is in Sauternes, Rieussec and de Fargues in Fargues, and La Tour Blanche and Lafaurie-Peyraguey in Bommes. Only Barsac holds the right to a name of its own, and the other four have to use the collective one.",
       ex=True),
    SA("Sauternes, Barsac and botrytis",
       "Let the autumn stay wet and the same fungus becomes a disaster instead of an asset. What is the destructive form called?",
       "Grey rot",
       ["grey rot", "gray rot", "pourriture grise", "botrytis as grey rot"],
       "Without dry afternoons the berry never dehydrates, so the fungus keeps spreading, splits the skins and lets acetic bacteria and fruit flies in. The finished wine tastes mouldy and oxidised, which is why a single week of the wrong weather can cost a Sauternes estate its whole crop."),
    SA("Sauternes, Barsac and botrytis",
       "Between Barsac and the city of Bordeaux, enclaved inside Graves on the same side of the river, lies a third sweet-wine appellation whose growers may also sell dry wine as Graves. Name it.",
       "Cerons",
       ["cerons", "cerons aoc", "the cerons appellation", "cerons in graves"],
       "It sits within the Graves boundary rather than beside it, so a grower there has two appellations available depending on how the wine finishes. The style is lighter and less sweet than Sauternes, which makes it a useful half-step between a dry Graves and a full Sauternes on a list."),
    SA("Sauternes, Barsac and botrytis",
       "Botrytised must settles poorly and blocks a filter almost at once, because the fungus leaves a sticky polysaccharide behind in the juice. Name that compound.",
       "Beta-glucan",
       ["beta glucan", "beta glucans", "glucan", "glucans", "b glucan",
        "beta 1 3 glucan", "beta 1 3 glucans"],
       "The molecule is long and gelatinous, so it bridges the pores of a pad or membrane the moment pressure is applied. Cellars deal with it by settling the must cold and long, or with a glucanase enzyme, rather than by pushing harder.",
       ex=True),

    # ----------------------------------------- Dry whites and Pessac-Leognan (4)
    Q("Dry whites and Pessac-Leognan",
      "Serious dry white Bordeaux is usually denied one conversion that every red in the region undergoes. Which, and for what reason?",
      ["Malolactic conversion, blocked to preserve the wine's acidity",
       "Alcoholic fermentation, stopped early to leave a little sugar",
       "Cold stabilisation, skipped so tartrates remain",
       "Oxidative racking, avoided so no air reaches the wine"], 0,
      "Malic acid is the sharper of the two, and in a maritime climate where whites are picked for freshness it is worth keeping. Chilling the barrel and a dose of sulphur are the usual means, and where the wine is left to go through it, richness is being chosen over tension."),
    SA("Dry whites and Pessac-Leognan",
       "Through the first winter a white barrel is opened and its sediment stirred back up into the wine. What is that operation called?",
       "Batonnage",
       ["batonnage", "lees stirring", "stirring the lees", "batonnage or lees stirring"],
       "Suspended lees give body and a creamy texture and also consume oxygen, so a stirred barrel is better protected than a still one. Overdone it flattens the aromatics, which is why estates chasing precision now stir far less than they did a generation ago."),
    SA("Dry whites and Pessac-Leognan",
       "Graves Superieures on a label promises something other than a better dry white. What is actually in the bottle?",
       "Sweet white wine",
       ["sweet white wine", "sweet white", "sweet white bordeaux", "sweet white graves",
        "moelleux", "sweet wine", "semi sweet white wine", "semi sweet wine",
        "semi sweet white", "sweet white wine from graves", "sweet graves",
        "white wine with residual sugar", "sweet white wine moelleux"],
       "The word Superieures marks style, not rank: the appellation is reserved for white with residual sugar from the Graves zone. A guest who orders it expecting a grander version of dry Graves gets a semi-sweet wine, which is a good reason to read the word out loud when the bottle is presented.",
       ex=True),
    SA("Dry whites and Pessac-Leognan",
       "Grapefruit and boxwood in a young Sauvignon Blanc come from sulphur-bearing compounds that are locked in the grape and released by the yeast. Name that family of compounds.",
       "Thiols",
       ["thiols", "thiol", "volatile thiols", "varietal thiols"],
       "They exist in the fruit bound to other molecules and have no smell until fermentation cuts them loose, which is why the choice of yeast changes the aroma so much. They also oxidise readily, and their loss is much of what makes an old bottle of cheap Sauvignon taste of nothing in particular."),

    # ----------------------------- The trade, en primeur and second wines (3)
    Q("The trade, en primeur and second wines",
      "A customer buys a case as futures in the spring after the harvest. What has he paid for, and when does it arrive?",
      ["Wine still in barrel, paid for now and delivered in bottle roughly two years later",
       "Bottled wine already in the chateau's cellar, held until he calls for it",
       "An option to buy later at whatever the market price turns out to be",
       "A share of the vintage settled in cash rather than in wine"], 0,
      "The money reaches the chateau long before the wine is bottled, which is the whole commercial point of the system. The buyer takes the risk that the wine will be cheaper on release, and the price is normally quoted in bond, so duty and VAT still fall due when the wine is taken out of the warehouse."),
    Q("The trade, en primeur and second wines",
      "Standing between a chateau and the merchant who buys from it is a second intermediary who never takes ownership of the wine. What does that party do?",
      ["Brokers the sale and samples the wine, for a commission of about two percent",
       "Buys the wine outright and resells it at a margin",
       "Bottles and labels the wine on the chateau's behalf",
       "Sets the release price and announces it to the market"], 0,
      "The courtier knows both cellars and books, matches wine to merchant and guarantees the sample matches the lot. The negociant is the one taking title and risk, and the chateau alone sets the price."),
    SA("The trade, en primeur and second wines",
       "Merchants on the Place cannot simply order what they want from a sought-after chateau; a house holds a fixed share of the crop, year in and year out. What is that entitlement called?",
       "An allocation",
       ["allocation", "allocations", "annual allocation"],
       "The share is historic and jealously guarded, and a merchant who declines a poor vintage risks losing it in a good one. That is why weak years still sell: the entitlement, not the wine, is what the buyer is protecting."),
]
