"""Rank II rewrite - Food & Pairing (65 questions: 13 MC, 52 short answer).

First Rank II category, run early to find the short-answer shape's problems
before 30 more Rank I categories are written against untested tooling.

Accept lists are calibrated against the ORIGINAL Advanced bank, never the
imported Rank II one, and validated by lib.accept_problems against a port of
core.js norm(): lowercase, accents stripped, punctuation to space, and the
engine's stopword list (the, a, an, chateau, domaine, de, du, des, la, le)
removed. A '~' prefix is NOT a strict match: core.js also accepts it when the
input merely contains it as a whole word, so a one-word tilde grades any wrong
answer holding that word. Strictness comes from ex=True, which makes every
plain entry exact-match only, so the lists below spell out the phrasings taken.

Written from the syllabus below. The imported bank was not read while writing.
"""

from lib import Q, SA

CAT = "Food & Pairing"
SLUG = "r2-food-pairing"
PREFIX = "c"
RANK = "Rank II"
SOURCE = "data-questions.js"

SYLLABUS = [
    ("Core pairing principles", 8),
    ("Tastes and their effect on wine", 8),
    ("Difficult foods", 7),
    ("Classic regional pairings", 9),
    ("Cheese", 7),
    ("Protein, method and sauce", 6),
    ("Wine-flattering and wine-killing elements", 5),
    ("Service judgement at the table", 7),
    ("Sweet, fortified and aperitif", 5),
    ("Structure and technique", 3),
]

BANK = [
    # ------------------------------------------ core pairing principles (8) -
    SA("Core pairing principles",
       "Name the two broad strategies for pairing, one matching like with like and the other setting them against each other.",
       "Complement and contrast",
       ["complement and contrast", "contrast and complement", "complementary and contrasting",
        "matching and contrasting"],
       "Complement echoes a quality the dish already has; contrast supplies what it lacks. Most classic pairings are one or the other stated plainly."),
    SA("Core pairing principles",
       "Before any question of flavour, which single structural quality should be matched between dish and wine?",
       "Weight, or body",
       ["weight or body", "body or weight", "weight and body", "weight body", "body weight",
        "weighty", "body"],
       "A delicate wine disappears under a heavy dish and a heavy wine flattens a delicate one. Weight is the first filter and it settles most bad pairings before flavour is considered."),
    Q("Core pairing principles",
      "A dish's sweetness sets a floor for the wine. What follows from that?",
      ["The wine must be at least as sweet as the dish", "The wine should be drier than the dish",
       "Sweetness in food has no bearing on wine", "The wine should be higher in alcohol"], 0,
      "Sweeter food strips a wine of fruit and leaves acid and alcohol exposed. Matching or exceeding the dish's sweetness is the one near-inviolable rule of dessert pairing."),
    SA("Core pairing principles",
       "A dish high in acidity demands what of the wine, if the wine is not to taste flat?",
       "At least as much acidity",
       ["matching acidity", "equal or higher acidity", "more acid than the dish",
        "at least as much acidity"],
       "Acid in the dish resets the palate and makes a lower-acid wine taste dull and flabby. Meeting it keeps the wine tasting fresh."),
    SA("Core pairing principles",
       "Which food element most reliably softens the perception of tannin?",
       "Protein and fat",
       ["protein and fat", "fat and protein", "protein or fat", "fat or protein",
        "protein fat", "fat protein"],
       "Tannin binds with protein, which is why a rare steak makes a young tannic red seem rounder. Fat coats the palate and blunts the same astringency.",
       ex=True),
    SA("Core pairing principles",
       "Salt in a dish does what to a wine's perceived tannin and fruit?",
       "Softens tannin and lifts fruit",
       ["softens tannin and lifts fruit", "reduces tannin", "makes it seem fruitier",
        "tames tannin and brings out fruit"],
       "Salt is the most reliably wine-friendly thing on a plate: it suppresses bitterness and astringency and makes fruit read more clearly."),
    Q("Core pairing principles",
      "Why is a high-alcohol wine a poor partner for a very spicy dish?",
      ["Alcohol amplifies the burn of capsaicin", "Alcohol neutralises capsaicin",
       "Alcohol removes the dish's sweetness", "Alcohol raises perceived acidity"], 0,
      "Ethanol and capsaicin both stimulate the same heat receptors, so each intensifies the other. Lower alcohol and a little sugar are the way out."),
    SA("Core pairing principles",
       "Bitterness in the food and bitterness in the wine combine in what way?",
       "Additively, amplifying each other",
       ["they amplify each other", "additive", "they add up", "increases bitterness"],
       "Unlike salt or acid, bitterness does not cancel. Two bitter elements compound, which is why radicchio or charred greens punish a tannic red."),

    # --------------------------------- tastes and their effect on wine (8) --
    SA("Tastes and their effect on wine",
       "Umami in a dish, with no salt to balance it, tends to do what to a red wine's tannin?",
       "Makes it seem harder and more bitter",
       ["makes tannin harsher", "harsher", "more bitter and drying", "accentuates tannin"],
       "Glutamates push tannin toward bitterness and metal. Adding salt to the dish is often the quickest repair to a pairing failing this way."),
    SA("Tastes and their effect on wine",
       "Identified in Japan and associated with glutamates, which taste makes wine pairing hardest?",
       "Umami",
       ["umami taste", "umaminess"],
       "Umami is the savoury depth in mushroom, aged cheese, cured fish, tomato and stock. It is the least wine-friendly of the basic tastes."),
    Q("Tastes and their effect on wine",
      "A dessert sweeter than the wine served with it produces which effect?",
      ["The wine tastes thin, sour and stripped of fruit", "The wine tastes noticeably sweeter",
       "The wine tastes more alcoholic but otherwise unchanged", "No perceptible change"], 0,
      "Relative sweetness governs the perception. Out-sweetened, a wine loses its fruit and shows only acid and alcohol."),
    SA("Tastes and their effect on wine",
       "Which two food tastes are broadly wine-friendly, tending to make most wines taste better?",
       "Salt and acid",
       ["salt and acid", "acid and salt", "salt and acidity", "saltiness and acidity"],
       "Both suppress bitterness and lift fruit. It is why a squeeze of lemon or a pinch of salt can rescue a pairing that seemed wrong."),
    SA("Tastes and their effect on wine",
       "Which two food tastes are broadly wine-hostile?",
       "Sweetness and umami",
       ["sweetness and umami", "umami and sweetness", "sweet and umami", "sugar and umami"],
       "Each strips fruit and exposes structure. Both can be managed, sweetness by matching it and umami usually by adding salt."),
    SA("Tastes and their effect on wine",
       "Fat in a dish invites which two possible responses in the wine?",
       "Acidity to cut it, or tannin to scour it",
       ["acidity or tannin", "tannin or acidity", "acid or tannin", "high acid or firm tannin"],
       "Two routes to the same end. Acidity refreshes the palate between bites; tannin binds the fat and clears it."),
    Q("Tastes and their effect on wine",
      "How does residual sugar in a wine interact with chilli heat?",
      ["Sugar tempers the burn", "Sugar intensifies the burn",
       "Sugar has no effect on perceived heat", "Sugar makes the dish taste saltier"], 0,
      "A little sweetness is the standard counter to capsaicin, which is why off-dry aromatic whites are the reflex recommendation for spicy food."),
    SA("Tastes and their effect on wine",
       "Serving a red too cold does what to its tannin and bitterness?",
       "Increases both",
       ["increases both", "increases tannin and bitterness", "makes them more prominent",
        "accentuates them"],
       "Cold hardens tannin and sharpens bitterness while muting aroma. An over-chilled red often reads as a bad pairing when it is only a service fault."),

    # ------------------------------------------------- difficult foods (7) --
    SA("Difficult foods",
       "Name the compound in artichoke that makes a wine tasted after it seem distortedly sweet.",
       "Cynarin",
       ["cynarin", "cynarine"],
       "Cynarin interferes with the sweet receptors, so the next sip reads sweeter than it is. It is the reason artichoke has a reputation as unpairable.",
       ex=True),
    SA("Difficult foods",
       "Asparagus is difficult with wine because of which family of compounds, also prominent in Sauvignon Blanc?",
       "Methoxypyrazines",
       ["methoxypyrazines", "pyrazines", "methoxypyrazine"],
       "The green, vegetal pyrazines in the vegetable meet the same compounds in the wine and compound each other. A herbaceous Sauvignon is the usual escape rather than the problem."),
    Q("Difficult foods",
      "Why is a sharply vinegar-dressed salad hard to pair?",
      ["Acetic acid clashes with wine acidity and leaves the wine tasting dull",
       "It is far too salty for any wine", "It carries more tannin than most reds",
       "It coats the palate in fat"], 0,
      "Vinegar's acid is a different, harsher character than wine acid, and it flattens what follows. Softening the dressing is a better fix than changing the wine."),
    SA("Difficult foods",
       "Faced with a fiercely hot curry, which style of wine would you pour?",
       "Off-dry, low-alcohol aromatic white",
       ["off dry white", "low alcohol off dry white", "off dry aromatic white",
        "slightly sweet aromatic white"],
       "Sugar tempers capsaicin and low alcohol avoids feeding it. Tannin and high alcohol are the two things to avoid outright."),
    SA("Difficult foods",
       "Oily fish such as mackerel with a heavily tannic red produces which specific fault?",
       "A metallic, fishy taste",
       ["metallic taste", "metallic", "fishy metallic taste", "tinny"],
       "Iron in the wine reacting with the fish oils is the usual explanation. The effect is unmistakable and it is why the old white-with-fish rule persists."),
    SA("Difficult foods",
       "Egg yolk is awkward with wine chiefly because of which property?",
       "It coats the palate",
       ["coats the palate", "palate coating", "it coats the mouth", "coating texture"],
       "A coated palate blunts everything after it. Acidity and bubbles are the usual counter, which is much of why Champagne suits egg dishes."),
    SA("Difficult foods",
       "Which fortified wine is the traditional partner for dark chocolate?",
       "Ruby or LBV Port",
       ["ruby or lbv port", "ruby port", "lbv port", "late bottled vintage port",
        "ruby or late bottled vintage port", "port"],
       "Chocolate's bitterness and fat need sweetness and body to stand against them. A young, fruit-forward Port has both.",
       ex=True),

    # ---------------------------------------- classic regional pairings (9) -
    SA("Classic regional pairings",
       "Sancerre is the classic partner for which goat cheese from the same stretch of the Loire?",
       "Crottin de Chavignol",
       ["crottin de chavignol", "crottin", "chavignol"],
       "Grown and made within sight of each other, and the textbook illustration of what grows together goes together."),
    SA("Classic regional pairings",
       "Which Loire white, especially when bottled sur lie, is the traditional match for oysters?",
       "Muscadet",
       ["muscadet", "muscadet sevre et maine", "muscadet sur lie"],
       "High acid, low alcohol, no oak and a faint saline lees character. It is close to a neutral frame around the oyster.",
       ex=True),
    Q("Classic regional pairings",
      "Sauternes with foie gras is chiefly an example of which strategy?",
      ["Complement, richness and sweetness meeting richness", "Contrast, acid cutting through fat",
       "A deliberate weight mismatch", "Tannin binding protein"], 0,
      "The pairing works by matching opulence with opulence, though the wine's acidity is what stops the combination cloying."),
    SA("Classic regional pairings",
       "Port and which English blue cheese make one of the classic sweet-and-salty pairings?",
       "Stilton",
       ["stilton", "blue stilton", "stilton cheese"],
       "Sweetness against salt and pungency, with enough body on both sides that neither is overwhelmed.",
       ex=True),
    SA("Classic regional pairings",
       "White truffle shaved over pasta in Piedmont is classically served with which local red?",
       "Barolo or Barbaresco",
       ["barolo or barbaresco", "barolo", "barbaresco", "nebbiolo"],
       "Nebbiolo's perfume and savoury edge meet the truffle rather than competing with it, and the pairing is regional to the point of being local."),
    SA("Classic regional pairings",
       "A tomato-based sauce demands high acidity. Which Tuscan red is the standard answer?",
       "Chianti",
       ["chianti", "chianti classico", "chianti classico riserva", "sangiovese"],
       "Tomato is acidic enough to flatten a soft red. Sangiovese meets it, which is why the pairing is a regional reflex.",
       ex=True),
    Q("Classic regional pairings",
      "What makes Champagne so effective with fried food?",
      ["Acidity and bubbles scour fat from the palate", "Its sweetness balances the salt",
       "Its tannin binds the frying oil", "Its low alcohol cools the palate"], 0,
      "Carbonation and acid together clear fat between mouthfuls, which resets the palate for the next bite."),
    SA("Classic regional pairings",
       "Aromatic Southeast Asian dishes are usually matched with which Alsace or German style?",
       "Off-dry Riesling or Gewurztraminer",
       ["off dry riesling", "gewurztraminer", "riesling", "off dry gewurztraminer"],
       "Aromatic intensity to meet the dish, sweetness to handle chilli, and low alcohol so the heat is not amplified."),
    SA("Classic regional pairings",
       "Muscadet, Chablis and Champagne share which structural feature that suits raw shellfish?",
       "High acidity with no oak",
       ["high acidity with no oak", "high acidity and no oak", "high acidity no oak",
        "high acidity", "crisp unoaked acidity", "acid and no oak", "high acid and no oak"],
       "Oak and shellfish rarely agree, and acidity does the work a squeeze of lemon would. The three wines differ in everything else.",
       ex=True),

    # ------------------------------------------------------------ cheese (7)
    Q("Cheese",
      "Why is white wine often a better partner for cheese than red?",
      ["Acidity cuts fat where tannin tends to clash with it", "White wine is generally sweeter",
       "Red wine is served too cold for cheese", "Cheese contains no fat to speak of"], 0,
      "The red-wine-with-cheese habit is largely convention. Tannin and cheese fat frequently fight, while acidity does the job cleanly."),
    SA("Cheese",
       "Blue cheese is classically paired with which category of wine?",
       "Sweet wine",
       ["sweet wine", "sweet wines", "dessert wine", "sweet fortified wine"],
       "Sweetness balances the salt and the pungency. Sauternes with Roquefort and Port with Stilton are the same idea in two regions."),
    SA("Cheese",
       "Which Burgundian washed-rind cheese is traditionally served with Marc de Bourgogne, the same spirit used to wash it?",
       "Epoisses",
       ["epoisses", "epoisses de bourgogne"],
       "Washed-rind cheeses are pungent enough to defeat most wine. Matching the cheese to the spirit it was washed in sidesteps the problem.",
       ex=True),
    SA("Cheese",
       "Hard aged cheeses such as Comte suit which character in a wine particularly well?",
       "Nutty, oxidative character",
       ["oxidative", "nutty oxidative wine", "oloroso", "vin jaune"],
       "The nuttiness of a long-aged cheese meets the nuttiness of an oxidatively aged wine. Vin Jaune with Comte is the regional case."),
    SA("Cheese",
       "Goat cheese and Sauvignon Blanc succeed because both carry which pair of qualities?",
       "Tanginess and a herbaceous, grassy note",
       ["tanginess and grassiness", "acidity and herbaceousness", "tangy and grassy",
        "sharpness and green notes"],
       "The pairing is complementary on both counts, which is why it survives outside its home region as well as within it."),
    SA("Cheese",
       "Manchego alongside which fortified wine is a fixture of the tapas table?",
       "Sherry",
       ["sherry", "manchego and sherry", "jerez", "dry sherry"],
       "Fino for the younger cheese and Amontillado as it ages. Salt and nuttiness sit on both sides, and the wine's bite keeps the sheep's-milk richness from settling.",
       ex=True),
    SA("Cheese",
       "Serving a very salty cheese with a sweet wine is which strategy?",
       "Contrast",
       ["contrasting", "by contrast", "opposition", "opposing"],
       "Neither element is echoed; each supplies what the other lacks. It is the most reliable route with strong cheeses."),

    # ------------------------------------------ protein, method and sauce (6)
    Q("Protein, method and sauce",
      "When a dish carries a dominant sauce, what should the wine be matched to?",
      ["The sauce", "The protein", "The garnish", "The starch"], 0,
      "The sauce usually carries more flavour intensity than the protein under it. Match the loudest element on the plate."),
    SA("Protein, method and sauce",
       "The same chicken poached and then grilled calls for different wines. Which variable changed?",
       "The cooking method, and with it weight and flavour intensity",
       ["cooking method", "preparation", "the method of cooking", "how it was cooked"],
       "Protein alone is a poor guide. Method decides whether the dish is delicate or browned and assertive."),
    SA("Protein, method and sauce",
       "Grilling and searing add which flavour dimension that suits oak-aged reds?",
       "Char and browned, Maillard flavours",
       ["char and browned maillard flavours", "char", "maillard", "maillard flavours",
        "char and maillard", "seared crust", "grill char", "char and browning"],
       "Browning creates the roasted, savoury compounds that echo barrel toast. It is why the same cut suits a different wine off the grill.",
       ex=True),
    SA("Protein, method and sauce",
       "A young tannic red with rare beef works partly through which chemical interaction?",
       "Tannin binding with protein",
       ["tannin binds protein", "tannin and protein bind", "tannin protein binding",
        "protein binds tannin"],
       "The bound tannin is no longer available to grip the palate, so the wine reads softer and rounder than it would alone."),
    SA("Protein, method and sauce",
       "Smoked foods sit badly with heavily oaked wine for what reason?",
       "The smoke and the oak compound each other",
       ["smoke and oak clash", "they compound", "oak amplifies the smoke",
        "too much smoke together"],
       "Two smoky elements do not balance, they accumulate. An unoaked or lightly oaked wine leaves room for the food's own smoke."),
    SA("Protein, method and sauce",
       "Poaching, steaming and raw preparations call for wines of what character?",
       "Light-bodied, delicate and unoaked",
       ["light and delicate", "light bodied and unoaked", "delicate unoaked wines",
        "lighter wines"],
       "Nothing has been added by browning, so the dish stays quiet and the wine must too or it will bury it."),

    # ---------------------- wine-flattering and wine-killing elements (5) ---
    Q("Wine-flattering and wine-killing elements",
      "Which is most likely to leave a fine old red tasting stripped and hollow?",
      ["A sweet chutney served alongside", "A plain roast joint", "A hard aged cheese",
       "Lightly salted bread"], 0,
      "Sweetness on the plate out-sweetens a dry mature wine and takes its fruit with it. The other three are neutral or helpful."),
    SA("Wine-flattering and wine-killing elements",
       "Beyond vinegar, which common raw salad ingredient is a frequent wine-killer?",
       "Raw onion, or strong raw garlic",
       ["raw onion", "onion", "raw garlic", "garlic"],
       "Both are pungent and sulphurous raw, and both flatten a wine. Cooking either one largely removes the problem."),
    SA("Wine-flattering and wine-killing elements",
       "Mint sauce with lamb is difficult for which reason?",
       "Its sharp acidity and cooling menthol cut across the wine",
       ["menthol", "sharp acidity and mint", "vinegar and mint", "the mint and vinegar"],
       "It is really a vinegar problem with a cooling aromatic on top. Redcurrant or a simple jus leaves the wine far more room."),
    SA("Wine-flattering and wine-killing elements",
       "Which treatment can turn a wine-hostile vegetable into a wine-friendly one?",
       "Roasting, which adds sweetness and browning",
       ["roasting", "roasting them", "charring", "browning them"],
       "Roasting drives off water, concentrates sugar and browns the surface, moving the vegetable toward the wine rather than against it."),
    SA("Wine-flattering and wine-killing elements",
       "A fiercely hot dish with a tannic, high-alcohol red fails because which two elements amplify each other?",
       "Capsaicin heat and alcohol",
       ["heat and alcohol", "capsaicin and alcohol", "chilli and alcohol", "heat and tannin"],
       "Alcohol intensifies the burn and the burn sharpens the tannin. Every element is pulling the same wrong direction."),

    # ------------------------------------- service judgement at the table (7)
    Q("Service judgement at the table",
      "A table of six has ordered six different dishes and wants one bottle. What is the soundest recommendation?",
      ["A versatile, high-acid, low-tannin wine", "The most powerful red on the list",
       "A sweet wine to cover everything", "A heavily oaked white"], 0,
      "With no single dish to match, the goal shifts from best pairing to fewest collisions. Acid is friendly and tannin is not."),
    SA("Service judgement at the table",
       "When a guest's stated preference conflicts with the textbook pairing, which should prevail?",
       "The guest's preference",
       ["the guest", "guest preference", "what the guest wants", "the guests wishes"],
       "Hospitality outranks theory. Offer the pairing once if invited, then pour what was asked for without further comment."),
    Q("Service judgement at the table",
      "Across a tasting menu, how should the wines generally progress?",
      ["Lighter to heavier, drier to sweeter", "Heavier to lighter throughout",
       "Sweeter to drier throughout", "In no particular order"], 0,
      "Each pour should not be diminished by the one before it. The same logic governs flights and comparative tastings."),
    SA("Service judgement at the table",
       "Why is a by-the-glass programme built around food-friendly wines rather than distinctive ones?",
       "Each glass has to work with many different dishes",
       ["they must suit many dishes", "one wine many dishes", "it has to match anything",
        "each glass meets every dish"],
       "A by-the-glass pour is ordered without knowing what it will meet. Breadth beats brilliance in that slot."),
    SA("Service judgement at the table",
       "A guest orders a big Cabernet with sole. What is the correct response?",
       "Serve it graciously, offering an alternative only if invited",
       ["serve what they ordered", "give them what they asked for",
        "serve it graciously", "pour it and say nothing"],
       "Correcting a guest costs more than the pairing is worth. The exception is a fault in the bottle, which is a different conversation."),
    SA("Service judgement at the table",
       "When one wine must serve a table sharing many dishes, which attribute matters most?",
       "Versatility",
       ["versatility", "versatile", "flexibility", "being versatile", "adaptability"],
       "High acidity, moderate alcohol and restrained tannin or oak. The wine's job is to be unobjectionable everywhere rather than perfect once.",
       ex=True),
    SA("Service judgement at the table",
       "Which service adjustment can rescue a red that is showing too tannic against the food?",
       "Serve it slightly cooler, or decant it",
       ["serve it cooler", "chill it slightly", "decant it", "lower the temperature"],
       "Warmth exaggerates alcohol and cold hardens tannin, so the useful range is narrow. Air softens young tannin as well."),

    # -------------------------------------- sweet, fortified and aperitif (5)
    Q("Sweet, fortified and aperitif",
      "Pedro Ximenez Sherry is near-black, viscous and intensely sweet. What is it classically poured over?",
      ["Vanilla ice cream", "A citrus sorbet", "Raw oysters", "A dry water biscuit"], 0,
      "At that concentration it behaves more like a sauce than a drink, and the cold cream keeps its raisined sweetness from becoming overwhelming."),
    SA("Sweet, fortified and aperitif",
       "Which Sherry styles are the classic aperitif with olives, almonds and salted fish?",
       "Fino or Manzanilla",
       ["fino or manzanilla", "fino", "manzanilla"],
       "Bone dry, saline and low in alcohol for a fortified wine. Salt on the plate and salt in the glass reinforce each other."),
    SA("Sweet, fortified and aperitif",
       "Melon with which style of sweet French fortified wine is a traditional first course?",
       "Vin doux naturel, such as Muscat de Beaumes-de-Venise",
       ["vin doux naturel", "muscat de beaumes de venise", "muscat"],
       "Grapey sweetness against the melon's own perfume, at a weight that does not overwhelm a first course."),
    SA("Sweet, fortified and aperitif",
       "Why does a dry sparkling wine struggle against a sweet dessert?",
       "The dessert leaves it tasting sour and thin",
       ["it tastes sour", "tastes thin and acidic", "the wine seems sour", "it turns austere"],
       "Brut Champagne with wedding cake is the standard illustration of the rule being broken by convention."),
    SA("Sweet, fortified and aperitif",
       "A fruit tart, as opposed to a chocolate one, is the standard match for which category?",
       "A late-harvest or botrytised sweet white",
       ["botrytised sweet white", "late harvest white", "sauternes", "noble rot wine"],
       "Fruit and acid on the plate meet fruit and acid in the glass. Chocolate's bitterness and fat instead call for something fortified."),

    # ------------------------------------------- structure and technique (3)
    SA("Structure and technique",
       "Which wine component binds with salivary proteins to produce the drying grip that food fat relieves?",
       "Tannin",
       ["tannins", "condensed tannin", "condensed tannins"],
       "Astringency is a tactile sensation rather than a taste: tannin stripping the lubricating proteins from saliva."),
    SA("Structure and technique",
       "Which structural element in white wine performs the palate-cleansing role that tannin plays in red?",
       "Acidity",
       ["acidity", "acid", "high acidity", "high acid", "crisp acidity",
        "fresh acidity"],
       "Both cut richness, by different mechanisms. It is why an unoaked high-acid white can handle food a soft red cannot.",
       ex=True),
    SA("Structure and technique",
       "What is the term for flavours combining to an effect greater than either alone, for better or worse?",
       "Synergy",
       ["synergy", "synergism", "synergistic effect", "synergistic"],
       "Worth naming because it runs both ways: the best pairings and the worst are both synergies rather than simple sums.",
       ex=True),
]
