"""Rank II rewrite - Italy North (62 questions: 27 MC, 35 short answer).

Certified level, pitched deliberately above the Rank I "Italy" category. Where
Rank I names the grape behind Barolo, this asks which soil formation softens the
western communes; where Rank I says Prosecco ferments in tank, this asks what a
Rive means on the label. Nothing here repeats a Rank I task.

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py.

Accept lists are built against lib.match_sa, a port of core.js matchSA. No '~'
entries appear anywhere: the tilde is exact-OR-containment, so a one-word tilde
grades any wrong answer that happens to hold that word. Where a shorter form of
an answer is itself a different and wrong thing (Recioto, Moscato, Trebbiano,
Valtellina), the accept lists were tested to confirm the short form does NOT
grade, rather than assumed.

Facts are restricted to ones that do not drift. Ownership, production volumes
and the newest denomination promotions are deliberately absent; ageing minima,
grape identity, geology and geography carry the weight instead.
"""

from lib import Q, SA

CAT = "Italy North"
SLUG = "r2-italy-north"
PREFIX = "c"
RANK = "Rank II"
SOURCE = "data-questions.js"

SYLLABUS = [
    ("Barolo and Barbaresco", 9),
    ("Piedmont beyond Nebbiolo", 8),
    ("Alto Piemonte and Valle d'Aosta", 6),
    ("Lombardy", 8),
    ("Valpolicella and Soave", 8),
    ("Prosecco and the rest of the Veneto", 7),
    ("Friuli-Venezia Giulia", 6),
    ("Trentino-Alto Adige", 6),
    ("Liguria and Emilia-Romagna", 4),
]

BANK = [
    # ---------------------------------------------- Barolo and Barbaresco (9) -
    Q("Barolo and Barbaresco",
      "Blue-grey compact marl in the western communes gives a Barolo that perfumes and softens earlier than one off the eastern ridge. Which soil formation supplies it?",
      ["Tortonian", "Serravallian", "Messinian", "Langhian"], 0,
      "The Tortonian Sant'Agata Fossili marls under La Morra and Barolo hold water and give a rounder, more scented wine. The older Serravallian soils of Serralunga and Monforte carry more sand and sandstone and build a firmer, slower one."),
    Q("Barolo and Barbaresco",
      "Since 2010 a Barolo label may carry the name of a delimited vineyard site alongside the denomination. What is the official term for such a site?",
      ["Menzione Geografica Aggiuntiva", "Contrada", "Climat", "Sori"], 0,
      "The MGA map put roughly 170 named sites on a legal footing, ending a century of informal cru names invented by producers. It records boundaries only and makes no claim about quality, unlike Burgundy's hierarchy."),
    Q("Barolo and Barbaresco",
      "Iron-firm tannin and glacially slow evolution mark the wines of one narrow eastern ridge in the Barolo zone. Which commune sits along it?",
      ["Serralunga d'Alba", "La Morra", "Verduno", "Novello"], 0,
      "The Serralunga ridge runs north to south on thin, pale, sandy limestone soils that keep vigour low. La Morra at the opposite edge of the zone gives the most fragrant and earliest-drinking style."),
    Q("Barolo and Barbaresco",
      "Counting from the first of November after harvest, a Barbaresco may not be sold until how much time has passed?",
      ["Twenty-six months", "Thirty-eight months", "Eighteen months", "Fifty months"], 0,
      "Twenty-six months in total, of which nine must be in wood; the Riserva runs to fifty. Barolo's clock is longer at both tiers, which is the practical difference a guest is most likely to taste."),
    SA("Barolo and Barbaresco",
       "Of the thirty-eight months a Barolo must age before release, a fixed part has to pass in wood. How long in cask?",
       "Eighteen months",
       ["eighteen months", "18 months", "eighteen months in cask", "eighteen months in wood",
        "18 months in cask", "18 months in wood"],
       "The remaining time may be spent in bottle or in stainless steel, which is how an estate chasing a fresher style keeps oak influence down. Riserva raises the total to sixty-two months without raising the wood minimum.",
       ex=True),
    SA("Barolo and Barbaresco",
       "Fruit from a young plot, or a cru declassified in a difficult year, is usually bottled under a broader Nebbiolo denomination created in 1994. Name it.",
       "Langhe Nebbiolo",
       ["langhe nebbiolo", "langhe nebbiolo doc", "nebbiolo langhe doc"],
       "Langhe is the catch-all denomination for the hills either side of the Tanaro and takes wines that fall outside the cru rules. Nebbiolo d'Alba is a separate and more tightly drawn DOC, and it excludes the Barolo and Barbaresco vineyards entirely."),
    SA("Barolo and Barbaresco",
       "Nearly all of the Barbaresco zone lies in three villages, with a fragment of Alba making up the rest. Name the three villages.",
       "Barbaresco, Neive and Treiso",
       ["barbaresco neive and treiso", "barbaresco neive treiso", "barbaresco treiso and neive",
        "barbaresco treiso neive", "neive barbaresco and treiso", "neive barbaresco treiso",
        "neive treiso and barbaresco", "neive treiso barbaresco", "treiso barbaresco and neive",
        "treiso barbaresco neive", "treiso neive and barbaresco", "treiso neive barbaresco"],
       "Barbaresco itself sits lowest and warmest by the river, Neive to the east, Treiso highest and coolest to the south. The remainder is the San Rocco Seno d'Elvio quarter of Alba.",
       ex=True),
    SA("Barolo and Barbaresco",
       "One Langhe vineyard was already being named on bottles in 1752, well over a century before anyone drew a cru map. Name that site.",
       "Cannubi",
       ["cannubi", "cannubi vineyard", "the cannubi site", "cannubi in barolo"],
       "The hill sits in the middle of the Barolo commune where the Tortonian and Serravallian soils meet, which is the usual explanation for its balance of scent and structure. That 1752 bottle predates Barolo as a dry wine altogether."),
    SA("Barolo and Barbaresco",
       "Cinchona bark, rhubarb root and spices steeped in a Langhe red produce a digestivo often poured at the end of service. Name that drink.",
       "Barolo Chinato",
       ["barolo chinato", "chinato", "barolo chinato digestivo"],
       "China is the Italian for cinchona, the quinine bark, which is where the bitterness and the name come from. It began as a nineteenth-century pharmacy tonic and is now the classic partner for dark chocolate."),

    # ------------------------------------------ Piedmont beyond Nebbiolo (8) --
    Q("Piedmont beyond Nebbiolo",
      "Rose petal and a faintly bitter finish mark a red DOCG grown in a handful of communes around Castagnole Monferrato. Which grape gives it?",
      ["Ruche", "Freisa", "Malvasia di Casorzo", "Pelaverga"], 0,
      "Ruche is aromatic in a way almost no other Italian red is, closer to a Moscato lift than to Nebbiolo tar. It is grown nowhere else of consequence, so the wine and the place are effectively the same thing."),
    Q("Piedmont beyond Nebbiolo",
      "A pale Piedmontese red carries far more tannin than its colour suggests, because its berries hold an unusual number of pips. Which grape is it?",
      ["Grignolino", "Freisa", "Vespolina", "Uva Rara"], 0,
      "The name traces to grignole, dialect for pips, and the berries can hold four or five where most grapes hold two. Skin contact therefore has to be brief, which is why the wine stays so light in colour while finishing firm."),
    Q("Piedmont beyond Nebbiolo",
      "North of Turin one white grape serves for a dry wine, for a metodo classico and for a passito, all under a single denomination. Which grape?",
      ["Erbaluce", "Arneis", "Favorita", "Nascetta"], 0,
      "Erbaluce di Caluso covers all three styles, which is unusual for one DOCG. High acidity is what makes the grape work in every register, including a passito dried for years."),
    Q("Piedmont beyond Nebbiolo",
      "Raspberry and rose scent a sweet, lightly sparkling red made around Acqui Terme. Which grape is pressed for it?",
      ["Brachetto", "Freisa", "Bonarda Piemontese", "Croatina"], 0,
      "Brachetto is an aromatic red in the Muscat mould and is fermented only partway, so alcohol stays low and grape perfume survives. It is the red counterpart to Moscato d'Asti in both style and purpose."),
    SA("Piedmont beyond Nebbiolo",
       "One grower in the Colli Tortonesi revived a nearly extinct white from the 1980s, and it now makes Piedmont's longest-lived dry white. Name the grape.",
       "Timorasso",
       ["timorasso", "timorasso grape", "timorasso variety"],
       "It had been pulled out in favour of easier, higher-cropping varieties and survived in scraps of old vineyard. The wines start closed and waxy and take on a kerosene and honey character over five to ten years, which is why they are so often compared to Riesling."),
    SA("Piedmont beyond Nebbiolo",
       "Asti's bubbles come from a single fermentation of must in a sealed tank, halted while sugar still remains. What is that tank process called in Italy?",
       "Metodo Martinotti",
       ["metodo martinotti", "martinotti", "martinotti method", "charmat", "metodo charmat",
        "charmat method"],
       "Federico Martinotti patented the sealed-tank idea in Asti before Eugene Charmat built the machinery in France, which is why Italy uses the Italian name. Crucially there is no second fermentation here at all: the wine never finishes the first one."),
    SA("Piedmont beyond Nebbiolo",
       "Piedmont's traditional-method sparkling DOCG must be vintage-dated and rest at least thirty months on its lees. Name it.",
       "Alta Langa",
       ["alta langa", "alta langa docg", "alta langa metodo classico"],
       "Pinot Nero and Chardonnay, alone or together, must supply at least ninety percent, with up to a tenth from other non-aromatic Piedmontese varieties. The vines sit high in the hills south of the Langhe where Nebbiolo would never ripen. The compulsory vintage date is the detail that separates it from most Italian metodo classico."),
    SA("Piedmont beyond Nebbiolo",
       "Dolcetto's most structured expression carries a DOCG named for a town in the southern Langhe. Name that town.",
       "Dogliani",
       ["dogliani", "dogliani docg", "dolcetto di dogliani", "dogliani in the langhe"],
       "Older vines on steeper, poorer slopes give a Dolcetto with real grip and a bitter-almond finish that repays a few years. Diano d'Alba and Ovada are the other zones where the grape is taken seriously rather than treated as an everyday red."),

    # ------------------------------------ Alto Piemonte and Valle d'Aosta (6) -
    Q("Alto Piemonte and Valle d'Aosta",
      "The Sesia river divides Alto Piemonte's two DOCGs between separate provinces. Which of them lies on the western bank?",
      ["Gattinara", "Ghemme", "Boca", "Lessona"], 0,
      "Gattinara sits west of the Sesia in the province of Vercelli, Ghemme east of it in Novara. Both are Nebbiolo, called Spanna here, and both may be softened with a little Vespolina or Uva Rara."),
    Q("Alto Piemonte and Valle d'Aosta",
      "Pink acidic volcanic rock left by a collapsed supervolcano underlies the vineyards at Boca. What is that rock called?",
      ["Porphyry", "Gneiss", "Schist", "Limestone"], 0,
      "The Valsesia caldera collapsed and tipped on its side, which exposed the whole plumbing of a volcano at the surface. Porphyry soils are acidic and iron-rich, and the Nebbiolo grown on them comes out paler and more savoury than in the Langhe."),
    Q("Alto Piemonte and Valle d'Aosta",
      "Ungrafted vines on low pergolas above a thousand metres beneath Mont Blanc are planted to which white grape?",
      ["Prie Blanc", "Erbaluce", "Nascetta", "Moscato Bianco"], 0,
      "Blanc de Morgex et de La Salle is among the highest vineyard land in Europe, and the altitude is what has kept phylloxera out. The pergolas are kept knee-high so the stone underneath radiates warmth back at the fruit."),
    SA("Alto Piemonte and Valle d'Aosta",
       "Stone-pillared pergolas terrace a steep Nebbiolo vineyard at Piedmont's northern boundary with Valle d'Aosta. Which denomination is made there?",
       "Carema",
       ["carema", "carema doc", "carema in piedmont", "the carema denomination"],
       "The masonry pillars, called pilun, store the day's heat and give it back at night in a place that is marginal for the grape. Everything is worked by hand on terraces too narrow for a machine."),
    SA("Alto Piemonte and Valle d'Aosta",
       "Crossing out of Piedmont into Valle d'Aosta, Nebbiolo changes name once again. What is it called there?",
       "Picotendro",
       ["picotendro", "picotener", "picoutener", "picotendro or picotener"],
       "Donnas is the valley's Nebbiolo denomination, sitting just upstream of Carema on the same stretch of the Dora Baltea. Chiavennasca in Valtellina and Spanna in Alto Piemonte are the other regional names for the identical grape."),
    SA("Alto Piemonte and Valle d'Aosta",
       "A white variety shared with the Swiss Valais gives Valle d'Aosta a saline, high-acid wine of real concentration. Name that grape.",
       "Petite Arvine",
       ["petite arvine", "arvine", "petite arvine grape", "arvine grape"],
       "The upper Rhone and the upper Dora Baltea sit either side of the same Alpine watershed, and varieties crossed the passes long before borders mattered. Cornalin made the same journey and is the Valais's Humagne Rouge, while Fumin and Petit Rouge are Aosta natives."),

    # ------------------------------------------------------------ Lombardy (8)
    Q("Lombardy",
      "One Franciacorta style is bottled at lower pressure and may use no black grapes at all. What is it called?",
      ["Saten", "Rose", "Riserva", "Dosaggio Zero"], 0,
      "Saten is made only from Chardonnay and Pinot Bianco and finished under about five atmospheres rather than six, which softens the mousse. It is always Brut, so the silkiness comes from pressure and blend rather than from sugar."),
    Q("Lombardy",
      "Sassella, Grumello, Inferno and Valgella are named subzones of one Lombard denomination. Which one?",
      ["Valtellina Superiore", "Franciacorta", "Oltrepo Pavese", "Lugana"], 0,
      "Maroggia is the fifth. All five sit on the south-facing terraces of the Adda valley, where Nebbiolo is called Chiavennasca and every operation is done by hand."),
    Q("Lombardy",
      "In the Oltrepo Pavese a red sold as Bonarda is pressed from a differently named variety. Which grape is actually in the bottle?",
      ["Croatina", "Uva Rara", "Vespolina", "Barbera"], 0,
      "The true Bonarda Piemontese is a separate grape grown further west, and the two are regularly confused on a list. Oltrepo Bonarda is Croatina, usually frizzante, soft and faintly bitter."),
    SA("Lombardy",
       "Franciacorta's Riserva tier demands a very long stay on the lees before disgorgement. How long?",
       "Sixty months",
       ["sixty months", "60 months", "five years", "5 years", "sixty months on the lees",
        "60 months on the lees", "five years on the lees", "sixty", "60"],
       "Riserva must also be vintage-dated, so the ageing and the harvest statement travel together. A non-vintage Franciacorta needs eighteen months on lees and a Millesimato thirty.",
       ex=True),
    SA("Lombardy",
       "The white grown on clay flats at the southern end of Lake Garda goes under a local name, though DNA work has tied it to Verdicchio. Name it.",
       "Turbiana",
       ["turbiana", "trebbiano di lugana", "turbiana or trebbiano di lugana",
        "trebbiano di lugana or turbiana"],
       "Lugana was long labelled Trebbiano di Lugana, which invited the assumption that it belonged with the undistinguished Trebbiano Toscano. It does not: the grape is Verdicchio, and the heavy clay is what gives the wine its weight and its capacity to age."),
    SA("Lombardy",
       "Dried Moscato grapes make a sweet red with a DOCG of its own in a single commune near Bergamo. Name the wine.",
       "Moscato di Scanzo",
       ["moscato di scanzo", "moscato di scanzo docg", "scanzo", "moscato scanzo"],
       "The variety is a dark-berried Moscato found essentially nowhere else, dried on racks and then aged for two years. The zone is measured in tens of hectares, so bottles rarely leave the province."),
    SA("Lombardy",
       "Nebbiolo dried in ventilated lofts through the autumn gives Valtellina a red of at least fourteen percent alcohol. Name that wine.",
       "Sforzato di Valtellina",
       ["sforzato di valtellina", "sforzato", "sfursat", "sfursat di valtellina",
        "sforzato valtellina"],
       "Sfursat is the dialect form and appears on plenty of labels. Both it and Amarone are legally dry, each disciplinare capping residual sugar, and the fourteen percent floor here is written into the rules."),
    SA("Lombardy",
       "Franciacorta sits on stony debris pushed into low hills by a glacier retreating from Lake Iseo. What is that landform called?",
       "Moraine",
       ["moraine", "glacial moraine", "morainic hills", "moraine amphitheatre"],
       "The amphitheatre of moraine drains hard and warms early, which suits early-picked base wine for sparkling. Lugana on the other side of the lake district sits on the heavy clay the same glaciers left behind instead."),

    # ---------------------------------------------- Valpolicella and Soave (8)
    Q("Valpolicella and Soave",
      "A large-berried Valpolicella grape was long taken for a clone of Corvina and proved to be a variety in its own right. Which is it?",
      ["Corvinone", "Rondinella", "Oseleta", "Dindarella"], 0,
      "Corvinone ripens later and holds thicker skins, which is why growers value it for drying. The rules now let it stand in for a share of the Corvina in the blend."),
    Q("Valpolicella and Soave",
      "Besides Classico, only one valley name may be added to a Valpolicella label. Which name?",
      ["Valpantena", "Illasi", "Negrar", "Marano"], 0,
      "Valpantena runs north from Verona just east of the Classico hills and has its own long-standing reputation. Negrar and Marano are Classico communes and Illasi lies in the eastern valleys, but none of them may appear as a denomination on its own."),
    Q("Valpolicella and Soave",
      "Of the three grapes traditionally written into the Valpolicella blend, one is no longer compulsory. Which one?",
      ["Molinara", "Corvina", "Rondinella", "Corvinone"], 0,
      "Molinara is pale and low in tannin, and many growers felt it thinned the wine, so it became optional. Corvina still has to lead, with Rondinella filling a defined minority share."),
    Q("Valpolicella and Soave",
      "Reckoned from the first of January after the harvest, how long must an Amarone rest before it may be released?",
      ["Two years", "Six months", "Four years", "Seven years"], 0,
      "Two years for the standard wine on that January clock, while the Riserva runs four years from the first of November of the harvest year. Most estates hold it far longer than the rule asks, because the tannin drawn out of shrivelled fruit takes time to settle."),
    SA("Valpolicella and Soave",
       "Soave Classico covers the hills of the walled town itself and those of one neighbouring commune. Name that commune.",
       "Monteforte d'Alpone",
       ["monteforte d'alpone", "monteforte", "monteforte dalpone",
        "commune of monteforte d'alpone"],
       "The Classico zone straddles a boundary between two geologies, calcareous ground on the Soave side and volcanic on the Monteforte side. Everything beyond those hills is plain Soave, much of it grown on the flat."),
    SA("Valpolicella and Soave",
       "Dark rock laid down by undersea eruptions underlies Soave's finest hills and is credited for the wine's saline tension. Name that rock.",
       "Basalt",
       ["basalt", "basaltic rock", "volcanic basalt", "basalt lava"],
       "The eruptions happened underwater in the Eocene, which is why the basalt sits interleaved with marine limestone. Growers separate the two: basalt sites give a tighter, smokier Garganega, limestone a softer and more floral one."),
    SA("Valpolicella and Soave",
       "Veneto's first DOCG, granted in 1998, was not a dry wine at all but a sweet one from dried grapes. Name it.",
       "Recioto di Soave",
       ["recioto di soave", "recioto di soave docg", "recioto soave", "soave recioto"],
       "Garganega dries well because its skins are thick and its bunches loose, so air moves through them. Recioto della Valpolicella is the red equivalent and a different wine entirely, which is why the second half of the name is the part that matters."),
    SA("Valpolicella and Soave",
       "Bunches for Amarone spend the winter in a purpose-built loft with through-draughts on every side. What is that room called in Italian?",
       "Fruttaio",
       ["fruttaio", "il fruttaio", "fruttai", "the fruttaio loft"],
       "Airflow, not warmth, is what keeps rot off the fruit, so the lofts are built high and open with fans now doing what the wind used to. Bunches are laid in single layers on racks or in shallow crates so nothing touches."),

    # ----------------------------------- Prosecco and the rest of the Veneto (7)
    Q("Prosecco and the rest of the Veneto",
      "On a Conegliano Valdobbiadene label one word introduces a single steep hillside belonging to a named village. Which word?",
      ["Rive", "Contrada", "Sori", "Bricco"], 0,
      "There are forty-three of them, and a Rive wine must be hand-harvested and carry a vintage. The word is the local dialect for a steep slope rather than a legal quality tier."),
    Q("Prosecco and the rest of the Veneto",
      "A cloudy Prosecco refermented in bottle and left undisgorged on its lees carries which traditional name?",
      ["Col Fondo", "Chiaretto", "Ripasso", "Passito"], 0,
      "Col fondo means with the bottom, and the sediment is meant to be there. It was the farmhouse style before tanks arrived, and it comes out drier, savoury and gently hazy."),
    Q("Prosecco and the rest of the Veneto",
      "Volcanic hills between Soave and Vicenza grow a white grape so high in acid that it is used almost only for sparkling wine. Which grape?",
      ["Durella", "Vespaiola", "Garganega", "Tai"], 0,
      "Durella takes its name from the hardness of its skin and keeps searing acidity even when fully ripe. Long lees ageing is what makes the traditional-method wines approachable, though tank method still accounts for the larger share of production."),
    SA("Prosecco and the rest of the Veneto",
       "Within Valdobbiadene a single steep hill of about a hundred hectares is the most prized site of the whole denomination. Name it.",
       "Cartizze",
       ["cartizze", "superiore di cartizze", "cartizze hill",
        "valdobbiadene superiore di cartizze"],
       "The slope is so steep that everything is carried by hand, and it is traditionally finished slightly sweeter than the rest of the zone. Land there is among the most expensive vineyard in Italy."),
    SA("Prosecco and the rest of the Veneto",
       "At Breganze, bunches of Vespaiola are twisted onto wires and hung to shrivel for a sweet wine. Name that wine.",
       "Torcolato",
       ["torcolato", "breganze torcolato", "torcolato di breganze"],
       "Torcolato comes from torcere, to twist, which is exactly what is done to the bunches before they are hung. The grape keeps ferocious acidity, so the finished wine is sweet without being cloying."),
    SA("Prosecco and the rest of the Veneto",
       "South of Lake Garda a white blend shares its stretch of morainic hills with Bardolino. Name that denomination.",
       "Bianco di Custoza",
       ["bianco di custoza", "custoza", "custoza doc", "bianco di custoza doc"],
       "The blend leans on Garganega with Trebbiano Toscano, Friulano and Cortese filling it out, so it drinks rounder than Soave from the same lead grape. The zone sits almost wholly inside the southern half of Bardolino, which runs a good deal further north up the lake, and many estates make both."),
    SA("Prosecco and the rest of the Veneto",
       "Volcanic cones rise straight out of the plain southwest of Padua and carry a DOCG for sweet Moscato Giallo. Name those hills.",
       "Colli Euganei",
       ["colli euganei", "euganei", "euganean hills", "colli euganei docg"],
       "The wine is Fior d'Arancio, orange blossom, which is exactly what Moscato Giallo smells of. The hills are old volcanic intrusions that never erupted through the surface, so they stand isolated above flat farmland."),

    # ------------------------------------------------- Friuli-Venezia Giulia (6)
    Q("Friuli-Venezia Giulia",
      "Layered marl and sandstone flysch underlies the Collio, and growers there have their own word for it. What is that word?",
      ["Ponca", "Galestro", "Alberese", "Tufo"], 0,
      "Ponca weathers quickly into a shallow, poor, free-draining soil that vines root into readily. It is the same Eocene flysch that continues over the border into Slovenian Brda under the name opoka."),
    Q("Friuli-Venezia Giulia",
      "A Friulian sweet-wine grape sets only a fraction of the flowers it opens, so its yields are minute. Which grape?",
      ["Picolit", "Verduzzo", "Ribolla Gialla", "Refosco"], 0,
      "The condition is called floral abortion, and it leaves bunches with a scatter of berries and plenty of air between them. Those loose bunches dry beautifully, which is the one advantage of an otherwise ruinous defect."),
    SA("Friuli-Venezia Giulia",
       "Verduzzo Friulano dried for a golden sweet wine holds DOCG rank in the hills above Nimis. Name that wine.",
       "Ramandolo",
       ["ramandolo", "ramandolo docg", "verduzzo di ramandolo"],
       "Verduzzo is unusual among sweet-wine grapes for its tannin, which comes off the skins and gives the wine grip against the sugar. The zone is tiny, steep and among the coldest vineyard land in the region."),
    SA("Friuli-Venezia Giulia",
       "A peppery Friulian red also known as Ribolla Nera was rescued from near extinction in the 1970s. Name the grape.",
       "Schioppettino",
       ["schioppettino", "schioppettino grape", "the schioppettino variety"],
       "It was left off the permitted list after the war and survived in a few old plots around Prepotto until growers pushed to have it reinstated. The black pepper note comes from rotundone, the same compound that marks cool-climate Syrah."),
    SA("Friuli-Venezia Giulia",
       "Iron-red soil over fissured limestone on the Slovenian border grows Vitovska and Terrano. Name that plateau.",
       "Carso",
       ["carso", "carso doc", "kras", "carso plateau"],
       "The karst is riddled with sinkholes and caves, and the little soil there is collects in pockets between bare rock. The bora wind off the northeast is fierce enough to shape how vines are trained."),
    SA("Friuli-Venezia Giulia",
       "Skin-fermented Ribolla Gialla made one border village the address most associated with Friulian orange wine. Name the village.",
       "Oslavia",
       ["oslavia", "oslavia in collio", "village of oslavia"],
       "Long skin macerations were revived there in the mid-1990s, in wood, and buried Georgian qvevri followed with Gravner's 2001 vintage. Ribolla Gialla suits the treatment because its skins are thick and its acidity high."),

    # ----------------------------------------------------- Trentino-Alto Adige (6)
    Q("Trentino-Alto Adige",
      "Deep-coloured Lagrein has its historic home in one quarter on the edge of Bolzano. Which one?",
      ["Gries", "Termeno", "Cortaccia", "Appiano"], 0,
      "The alluvial gravel at Gries is warm and free-draining, which suits a late-ripening variety on a valley floor. Lagrein is a descendant of Teroldego and shows the same dark colour and bitter-cherry edge."),
    Q("Trentino-Alto Adige",
      "Italy's first denomination created specifically for traditional-method sparkling wine sits in the mountains along the upper Adige. Which denomination?",
      ["Trento DOC", "Franciacorta", "Conegliano Valdobbiadene", "Asti"], 0,
      "Trento was recognised in 1993 for metodo classico alone, drawing on vineyards planted high on both valley walls. Altitude supplies the acidity that a base wine for sparkling needs."),
    SA("Trentino-Alto Adige",
       "Pinot Bianco that stays fresh for decades comes from a village on porphyry sand west of Bolzano. Name that village.",
       "Terlano",
       ["terlano", "terlan", "terlano doc", "terlaner"],
       "The sandy quartz porphyry soils are unusually rich in potassium, which growers there credit for the wine's structure and longevity. Old bottles are released from the cellar as Rarita after at least ten years on the lees."),
    SA("Trentino-Alto Adige",
       "Sylvaner, Kerner and Gruner Veltliner grow up a narrow valley running from Bolzano toward the Brenner pass. Name that valley.",
       "Valle Isarco",
       ["valle isarco", "eisacktal", "eisacktaler", "isarco valley", "valle isarco eisacktal"],
       "It is the coldest and highest of Alto Adige's zones, which is why the grape list reads more Austrian than Italian. The wines are lean, high-acid and aromatic rather than broad."),
    SA("Trentino-Alto Adige",
       "Trentino's one notable native white is dried on racks until Holy Week to make the region's Vino Santo. Name the grape.",
       "Nosiola",
       ["nosiola", "nosiola grape", "nosiola variety"],
       "The drying runs about six months, far longer than most passito, and botrytis is welcomed on the way. The name comes from nocciola, hazelnut, which is what the dry version tastes of."),
    SA("Trentino-Alto Adige",
       "Mozart's Don Giovanni calls for a dark, soft red from Trentino by name in its final act. Name the grape.",
       "Marzemino",
       ["marzemino", "marzemino grape", "marzemino d'isera"],
       "Isera in the Vallagarina is its stronghold, on basalt soils south of Rovereto. The wine is fragrant and low in tannin, meant to be drunk within a few years rather than kept."),

    # ---------------------------------------------- Liguria and Emilia-Romagna (4)
    Q("Liguria and Emilia-Romagna",
      "Pigato turned out under DNA analysis to be the same variety as a white already planted the length of the northwest coast. Which one?",
      ["Vermentino", "Albarola", "Bosco", "Cortese"], 0,
      "Pigato is a mutation of Vermentino with freckled skins, which is what the name records. Growers still bottle the two separately because the clones behave differently in the vineyard and in the glass."),
    Q("Liguria and Emilia-Romagna",
      "One Lambrusco sets fruit so poorly that its wine comes out pale pink and unusually sharp. Which one?",
      ["Lambrusco di Sorbara", "Lambrusco Grasparossa di Castelvetro",
       "Lambrusco Salamino di Santa Croce", "Lambrusco Maestri"], 0,
      "Sorbara flowers badly and drops much of its crop, leaving thin bunches with little colour to give. Grasparossa at the other end of the scale is dark, tannic and much fuller bodied."),
    SA("Liguria and Emilia-Romagna",
       "The first Italian white ever raised to DOCG, back in 1987, grows in the hills of Romagna. Name the grape.",
       "Albana",
       ["albana", "albana di romagna", "romagna albana", "albana grape"],
       "The promotion was controversial at the time because the wine was thought not to merit it, and it pushed the authorities to be stricter afterwards. Albana has thick skins, so it takes to both skin contact and drying for passito."),
    SA("Liguria and Emilia-Romagna",
       "Grapes dried in lofts above the terraced cliffs of the Cinque Terre make a rare sweet wine sold in small bottles. Name it.",
       "Sciacchetra",
       ["sciacchetra", "sciacchetra passito", "sciacchetra di cinque terre"],
       "Bosco leads the blend with Albarola and Vermentino alongside, all of it carried off terraces reachable only on foot or by rack railway. Yields after drying are so small that a few bottles come from a whole day's picking."),
]
