"""Rank II rewrite - Italy Central & South (61 questions: 25 MC, 36 short answer).

Certified level, pitched deliberately above the Rank I "Italy" category. Where
Rank I asks which grape makes Taurasi, this asks when Aglianico is picked in
Irpinia; where Rank I names the black rooster, this asks what the top Classico
tier demands. Nothing here repeats a Rank I task.

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py.

Accept lists are built against lib.match_sa, a port of core.js matchSA. No '~'
entries are used anywhere: the tilde is exact-OR-containment, so a one-word
tilde grades any wrong answer holding that word. Where a wrong answer could
contain the right one as a qualified phrase, ex=True makes every entry
exact-only and the plausible phrasings are spelled out instead.

Figures are restricted to ones that do not drift. Ownership, production volumes
and the newest denomination promotions are deliberately absent.
"""

from lib import Q, SA

CAT = "Italy Central & South"
SLUG = "r2-italy-central-south"
PREFIX = "c"
RANK = "Rank II"
SOURCE = "data-questions.js"

SYLLABUS = [
    ("Chianti and its subzones", 8),
    ("Montalcino and Montepulciano", 7),
    ("Coastal Tuscany and the Super Tuscans", 6),
    ("Umbria and Marche", 7),
    ("Lazio, Abruzzo and Molise", 6),
    ("Campania", 7),
    ("Puglia, Basilicata and Calabria", 7),
    ("Sicily", 7),
    ("Sardinia", 6),
]

BANK = [
    # ------------------------------------------ Chianti and its subzones (8) -
    Q("Chianti and its subzones",
      "A nineteenth-century formula for Chianti allowed a white grape so the wine would drink well young. Which white was named?",
      ["Malvasia", "Vernaccia", "Grechetto", "Vermentino"], 0,
      "Bettino Ricasoli set out Sangiovese with Canaiolo for structure and a little Malvasia for early appeal in 1872. He treated the white share as optional, but the 1967 DOC made it compulsory at ten to thirty percent, 1996 made it optional again, and from the 2006 vintage white grapes were banned from Chianti Classico outright."),
    Q("Chianti and its subzones",
      "Flaky, friable marl that splits into plates underlies many of the best sites between Florence and Siena. What is that soil called locally?",
      ["Galestro", "Terra rossa", "Ponca", "Albariza"], 0,
      "Galestro breaks up easily and drains hard, which suits Sangiovese on a slope. Alberese, a hard compact limestone, is the other rock name worth knowing in the same hills."),
    Q("Chianti and its subzones",
      "Cooler, higher ground in the Sieve valley northeast of Florence gives the Chianti subzone most often singled out for longevity. Which subzone is it?",
      ["Rufina", "Colli Senesi", "Colline Pisane", "Montalbano"], 0,
      "Altitude and a cool draught out of the Apennines slow ripening and hold acidity. The wines start tighter and reward cellaring more than most Chianti does."),
    SA("Chianti and its subzones",
       "Since the 2006 vintage a whole category of grape has been shut out of the Classico blend. Which category?",
       "White grapes",
       ["white grapes", "white varieties", "white grape varieties", "white wine grapes"],
       "Trebbiano and Malvasia had been permitted for over a century and were often used to stretch volume. Removing them was the single clearest step in Classico's move upmarket."),
    SA("Chianti and its subzones",
       "A Classico producer wants the denomination's top tier, which demands estate-grown fruit and thirty months of ageing. Which designation is that?",
       "Gran Selezione",
       ["gran selezione", "chianti classico gran selezione", "classico gran selezione",
        "gran selezione tier", "gran selezione level", "gran selezione designation"],
       "Introduced in 2013 above Riserva, and unusual in tying the tier to fruit the estate farmed itself. Riserva by contrast can be built from bought grapes.",
       ex=True),
    SA("Chianti and its subzones",
       "Outside the Classico zone the Sangiovese minimum sits at seventy percent. Inside it, what does the rulebook demand?",
       "Eighty percent Sangiovese",
       ["eighty percent", "80 percent", "80%", "eighty percent sangiovese",
        "at least 80 percent", "at least eighty percent", "80 percent sangiovese",
        "eighty per cent", "80 per cent", "eighty", "80"],
       "The remaining fifth may be Canaiolo, Colorino or an international variety, and many estates now bottle the wine as pure Sangiovese anyway. The wider Chianti DOCG stays at seventy.",
       ex=True),
    SA("Chianti and its subzones",
       "Some producers restart a finished wine with dried, part-raisined grapes to build body and softness. What is that Tuscan practice called?",
       "Governo all'uso toscano",
       ["governo all'uso toscano", "governo", "governo toscano", "governo method",
        "governo alluso toscano"],
       "The renewed fermentation adds a little alcohol and glycerol and rounds off hard young tannin. It fell out of favour with the drive for concentration and has been revived by growers chasing drinkability."),
    SA("Chianti and its subzones",
       "West of Florence a small DOCG has required Cabernet in its blend since long before anyone spoke of Super Tuscans. Name it.",
       "Carmignano",
       ["carmignano", "carmignano docg", "carmignano in tuscany"],
       "The rules oblige at least a tenth Cabernet Franc or Sauvignon alongside Sangiovese. Cabernet was growing there under the name uva francesca in Medici times, which makes the zone the oldest precedent for what Bolgheri later made famous."),

    # -------------------------------------- Montalcino and Montepulciano (7) -
    Q("Montalcino and Montepulciano",
      "Ferruccio Biondi-Santi propagated a particular Sangiovese selection in the nineteenth century. What is that selection called locally?",
      ["Brunello", "Prugnolo Gentile", "Morellino", "Nielluccio"], 0,
      "Brunello means little dark one and refers to the fruit rather than the wine. Prugnolo Gentile, Morellino and Nielluccio are the same grape's names in Montepulciano, the Maremma and Corsica."),
    Q("Montalcino and Montepulciano",
      "A Montalcino estate declassifies younger fruit into a wine it can sell a year after harvest. Which denomination takes it?",
      ["Rosso di Montalcino", "Sant'Antimo", "Moscadello di Montalcino", "Val d'Orcia"], 0,
      "Rosso is the same grape from the same hill under a much shorter ageing requirement, which lets an estate protect the Brunello in a difficult year. It is often the better value and always the earlier drink."),
    Q("Montalcino and Montepulciano",
      "Shelter from an extinct volcanic cone keeps this zone drier and warmer than the Chianti hills to its north. Which peak gives that shelter?",
      ["Monte Amiata", "Monte Conero", "Monte Vulture", "The Apuan Alps"], 0,
      "Amiata breaks up storms coming off the Tyrrhenian, so Montalcino sees markedly less rain than Chianti Classico. Growers there worry about drought where growers further north worry about rot."),
    SA("Montalcino and Montepulciano",
       "An estate in Montalcino plants Cabernet and Chardonnay alongside its Sangiovese. Under which local DOC may it bottle them?",
       "Sant'Antimo",
       ["sant'antimo", "santantimo", "sant'antimo doc", "santantimo doc"],
       "Sant'Antimo is the catch-all denomination covering everything on the hill that is not Brunello, Rosso or Moscadello. It is named for the Romanesque abbey below the town."),
    SA("Montalcino and Montepulciano",
       "Before Brunello made the town famous, Montalcino was known for a sweet white pressed from Moscato. What is that wine called?",
       "Moscadello di Montalcino",
       ["moscadello di montalcino", "moscadello", "moscadello montalcino", "moscadello wine"],
       "Moscadello was the commercial wine of the zone for centuries and was traded well beyond Tuscany. It survives as a curiosity in still, frizzante and late-harvest forms."),
    SA("Montalcino and Montepulciano",
       "In Montepulciano the local Sangiovese clone must supply at least what proportion of a Vino Nobile?",
       "Seventy percent",
       ["seventy percent", "70 percent", "70%", "at least seventy percent",
        "70 percent sangiovese", "seventy percent sangiovese", "at least 70 percent",
        "seventy per cent", "70 per cent", "seventy", "70"],
       "The balance may include Canaiolo, Mammolo and other permitted varieties, so a Nobile is more often a blend than a Brunello is. The clone is called Prugnolo Gentile here.",
       ex=True),
    SA("Montalcino and Montepulciano",
       "A Nobile Riserva is held longer than the standard bottling before release. How long in total?",
       "Three years",
       ["three years", "3 years", "three years of ageing", "36 months", "thirty six months",
        "three", "3", "three years in total", "three years total"],
       "The standard wine needs two years and the Riserva a third, part of which must be spent in bottle. Both are shorter requirements than Brunello carries.",
       ex=True),

    # ------------------------------- coastal Tuscany and the Super Tuscans (6)
    Q("Coastal Tuscany and the Super Tuscans",
      "Antinori first sold a barrique-aged Sangiovese as a table wine rather than a Chianti from the 1971 vintage. Which wine was that?",
      ["Tignanello", "Sassicaia", "Ornellaia", "Solaia"], 0,
      "Small French oak and a blend outside the rulebook meant it could not be labelled Chianti Classico, so it went out as a vino da tavola. The white grapes left the blend with the 1975 vintage, which is also when Cabernet was written in."),
    Q("Coastal Tuscany and the Super Tuscans",
      "Merlot on a vein of blue clay in Bolgheri, in a vineyard first planted by Tenuta dell'Ornellaia, produces which single-variety bottling?",
      ["Masseto", "Guado al Tasso", "Le Serre Nuove", "Paleo Rosso"], 0,
      "The clay holds water through a hot coastal summer, which is why Merlot behaves there as it does nowhere else in Tuscany. The vineyard is a matter of a few hectares."),
    Q("Coastal Tuscany and the Super Tuscans",
      "A sweet red passito from the island of Elba holds DOCG rank. Which grape is dried for it?",
      ["Aleatico", "Ciliegiolo", "Colorino", "Mammolo"], 0,
      "Aleatico is a red-berried relation of Muscat and keeps that grapey perfume through drying. The wine is sweet, scented and only lightly tannic."),
    SA("Coastal Tuscany and the Super Tuscans",
       "Guado al Tasso and Ornellaia share a denomination built on Bordeaux varieties. Which two lead it in practice?",
       "Cabernet Sauvignon and Merlot",
       ["cabernet sauvignon and merlot", "merlot and cabernet sauvignon",
        "cabernet sauvignon merlot", "merlot cabernet sauvignon"],
       "The rulebook allows Cabernet Sauvignon, Merlot and Cabernet Franc each from nothing up to the whole blend, and caps Syrah and Sangiovese at half, so the first two lead by practice rather than by rule. Bolgheri Sassicaia was carved out as its own DOC in 2013 and sits outside this denomination."),
    SA("Coastal Tuscany and the Super Tuscans",
       "Which denomination covers Sangiovese grown broadly across the Maremma, sitting below Morellino di Scansano in the hierarchy?",
       "Maremma Toscana",
       ["maremma toscana", "maremma toscana doc"],
       "It gathers up the wide coastal plain and its hinterland under one name, in reds, whites and roses. Morellino remains the tighter, hillier zone within that country."),
    SA("Coastal Tuscany and the Super Tuscans",
       "Tignanello's sister wine from the same hillside leans on Cabernet Sauvignon rather than Sangiovese. Name it.",
       "Solaia",
       ["solaia", "solaia antinori", "antinori solaia"],
       "The plot faces south and takes its name from the sun, and the wine inverts its neighbour's proportions. A small share of Sangiovese still keeps it recognisably Tuscan."),

    # ------------------------------------------------- Umbria and Marche (7) -
    Q("Umbria and Marche",
      "Before the dry version was ever bottled commercially, Montefalco's Sagrantino was made in which style?",
      ["A sweet passito from dried grapes", "A pale dry rosato", "A fortified wine",
       "A lightly sparkling red"], 0,
      "The sweet passito was the traditional Easter wine of the district and the dry bottling only appeared in the 1970s. Drying suits a grape whose tannin is otherwise ferocious."),
    Q("Umbria and Marche",
      "Which Umbrian DOCG south of Perugia is a Sangiovese-led red released only as a Riserva?",
      ["Torgiano Rosso Riserva", "Montefalco Rosso", "Colli Martani", "Lago di Corbara"], 0,
      "The plain Torgiano red stays at DOC; only the longer-aged wine was promoted. It is one of the few Italian DOCGs that exists at Riserva level alone."),
    Q("Umbria and Marche",
      "DNA profiling matched Verdicchio to a variety long grown in the Veneto under another name. Which?",
      ["Trebbiano di Soave", "Garganega", "Trebbiano Toscano", "Cortese"], 0,
      "Verdicchio, Trebbiano di Soave and Trebbiano di Lugana proved to be one variety under three regional names. It is unrelated to the far more widely planted Trebbiano Toscano."),
    SA("Umbria and Marche",
       "Umbria's best-known white grows on tufa beneath a cathedral town and was historically made off-dry. Name the wine.",
       "Orvieto",
       ["orvieto", "orvieto classico", "orvieto doc", "orvieto abboccato"],
       "The soft volcanic rock under the town was hollowed into cellars that held a steady cool temperature, which favoured wines with sugar left in them. Most Orvieto today is finished dry."),
    SA("Umbria and Marche",
       "Which native white grape gives Umbrian blends more body and grip than Trebbiano manages?",
       "Grechetto",
       ["grechetto", "grechetto grape", "grechetto di orvieto"],
       "Grechetto has thicker skins and holds acidity better, so it stands up to lees work and even to oak. It is increasingly bottled on its own rather than used to prop up a blend."),
    SA("Umbria and Marche",
       "Marche grows Verdicchio in a smaller inland valley that never opens to the sea. Name that zone.",
       "Matelica",
       ["matelica", "verdicchio di matelica", "matelica doc", "matelica in the marche"],
       "The valley runs north to south rather than out to the Adriatic, so it gets a continental swing of temperature the coastal Castelli di Jesi never sees. The wines are leaner and slower to open."),
    SA("Umbria and Marche",
       "A Montepulciano-based red comes off a limestone headland rising straight out of the Adriatic near Ancona. Name the wine.",
       "Rosso Conero",
       ["rosso conero", "conero", "rosso conero doc", "conero riserva"],
       "Monte Conero is the only real promontory on that long flat coast, and its limestone gives a firmer wine than Montepulciano usually makes. Rosso Piceno, further south, blends the grape with Sangiovese instead."),

    # ---------------------------------------- Lazio, Abruzzo and Molise (6) --
    Q("Lazio, Abruzzo and Molise",
      "A bishop's servant is said to have chalked his verdict on inn doors along the road to Rome near Lake Bolsena. Which wine took its name from that tale?",
      ["Est! Est!! Est!!! di Montefiascone", "Cesanese del Piglio", "Frascati Superiore",
       "Aleatico di Gradoli"], 0,
      "The scout was sent ahead to mark where the wine was good, and doubled the word twice at Montefiascone. The story has outlived any reputation the wine itself holds."),
    Q("Lazio, Abruzzo and Molise",
      "Which grape is grown for Lazio's red DOCG, in the hills southeast of Rome toward Frosinone?",
      ["Cesanese", "Nero Buono", "Aleatico", "Ciliegiolo"], 0,
      "Cesanese gives a perfumed, medium-bodied red with a faintly bitter finish, and the Piglio zone is its stronghold. Lazio's other DOCGs are both white and both at Frascati."),
    SA("Lazio, Abruzzo and Molise",
       "Much of what reaches the bottle as Trebbiano d'Abruzzo is not Trebbiano Toscano. Which variety is often there instead?",
       "Bombino Bianco",
       ["bombino bianco", "bombino", "bombino bianco grape", "trebbiano abruzzese",
        "bombino bianco or trebbiano abruzzese", "trebbiano abruzzese or bombino bianco"],
       "The denomination permits Bombino Bianco as well as the distinct local Trebbiano Abruzzese, and the two have been confused in the vineyard for generations. The rare wines with real depth come from the local variety, not from Trebbiano Toscano.",
       ex=True),
    SA("Lazio, Abruzzo and Molise",
       "Teramo's hills in the north of Abruzzo carry the region's own DOCG for Montepulciano. What is it called?",
       "Montepulciano d'Abruzzo Colline Teramane",
       ["montepulciano d'abruzzo colline teramane", "colline teramane", "colline teramane docg",
        "montepulciano colline teramane", "montepulciano d'abruzzo colline teramane docg",
        "colline teramane montepulciano"],
       "Higher, cooler sites under the Gran Sasso give a firmer wine than the coastal plain does, and the ageing requirement is longer. The bulk of the region's Montepulciano is bottled at DOC level below it.", ex=True),
    SA("Lazio, Abruzzo and Molise",
       "A once nearly extinct Abruzzo white, now widely planted, shares its name with a sheep's cheese. Name the grape.",
       "Pecorino",
       ["pecorino", "pecorino grape", "pecorino bianco", "pecorino variety"],
       "It was down to a handful of vines by the 1980s and is now the region's most fashionable white. Small berries and thick skins give it more weight and alcohol than Trebbiano."),
    SA("Lazio, Abruzzo and Molise",
       "Molise's native red variety was nearly lost and now carries a DOC of its own. Name it.",
       "Tintilia",
       ["tintilia", "tintilia del molise", "tintilia grape"],
       "The name comes from a dialect word for dye, which describes the colour it gives. It grows best high inland, where Molise's hills climb toward the Apennine spine."),

    # ------------------------------------------------------------ Campania (7)
    Q("Campania",
      "Aglianico ripens so late in Irpinia that picking often runs into which month?",
      ["November", "July", "August", "September"], 0,
      "It is among the last varieties harvested anywhere in Italy, and the long hang keeps acidity high while tannin slowly resolves. That combination is why Taurasi is built to age."),
    Q("Campania",
      "Vines at Campi Flegrei grow in deep volcanic sand and many still stand on their own roots. What does that sand keep out?",
      ["Phylloxera, which cannot move through it", "Downy mildew, which cannot spread in it",
       "Spring frost, which cannot settle on it", "Botrytis, which cannot take hold in it"], 0,
      "The louse cannot travel through loose siliceous sand to reach a root, so ungrafted vines survive there. Sardinia's Sulcis and Colares in Portugal depend on the same accident of soil."),
    Q("Campania",
      "Which pair of grapes makes the white and the red of Lacryma Christi del Vesuvio?",
      ["Coda di Volpe and Piedirosso", "Falanghina and Aglianico", "Fiano and Sciascinoso",
       "Greco and Casavecchia"], 0,
      "Coda di Volpe means fox's tail and describes the shape of the bunch. Both grapes are grown on the volcano's ash and lava soils inside the national park."),
    SA("Campania",
       "The village that gives Greco di Tufo its name was long mined for a mineral used in the cellar. Which mineral?",
       "Sulphur",
       ["sulphur", "sulfur", "sulphur mines", "sulfur mines", "sulphur mining"],
       "The mines closed decades ago but the smoky, struck-match note in the wine is still routinely traced to them. Sulphur remains the winemaker's principal antioxidant and antiseptic."),
    SA("Campania",
       "Which Campanian white takes on hazelnut and honey with age and is grown in the hills east of Naples?",
       "Fiano di Avellino",
       ["fiano di avellino", "fiano avellino", "fiano di avellino docg", "avellino fiano",
        "fiano", "fiano d'avellino"],
       "Fiano is low-yielding and thick-skinned, and unusually for a southern white it improves for years in bottle. Altitude around Avellino supplies the acidity that makes the ageing possible."),
    SA("Campania",
       "Campania's second red is nicknamed dove's foot for the colour of its stalks at harvest. Name the grape.",
       "Piedirosso",
       ["piedirosso", "piedirosso grape", "per' e palummo", "pere e palummo"],
       "The stems turn red as the fruit ripens, which is what the dialect name records. It gives a softer, earlier-drinking wine than Aglianico and is often blended in to lighten it."),
    SA("Campania",
       "Vines on the Amalfi coast are worked on narrow terraces held by dry stone walls. Which DOC covers them?",
       "Costa d'Amalfi",
       ["costa d'amalfi", "costa damalfi", "costa amalfi", "costa d'amalfi doc"],
       "Furore, Ravello and Tramonti are its named subzones, all of them tended by hand because no machine can reach the terraces. Some Tramonti vines are ungrafted and well over a century old."),

    # ----------------------------------- Puglia, Basilicata and Calabria (7) --
    Q("Puglia, Basilicata and Calabria",
      "Head-trained bush vines stand free of wires across much of the Salento. What is that training system called in Italian?",
      ["Alberello", "Pergola", "Tendone", "Guyot"], 0,
      "The vine forms its own low goblet, shading the fruit and needing no trellis in a dry, windy place. Yields are small and every operation has to be done by hand."),
    Q("Puglia, Basilicata and Calabria",
      "Castel del Monte takes its name from a thirteenth-century castle in Puglia. Which native red is bottled there at DOCG level as a Riserva?",
      ["Nero di Troia", "Negroamaro", "Primitivo", "Susumaniello"], 0,
      "Nero di Troia, also called Uva di Troia, ripens late and carries firm tannin, so it needs the extra ageing a Riserva demands. It is the third of Puglia's major reds after Primitivo and Negroamaro."),
    Q("Puglia, Basilicata and Calabria",
      "On the Ionian coast of Calabria, the Ciro zone builds its red on which grape?",
      ["Gaglioppo", "Magliocco", "Nerello Mascalese", "Nero d'Avola"], 0,
      "Gaglioppo gives a pale, savoury, high-alcohol red with more tannin than its colour suggests. Magliocco is the region's other serious native red, grown further west and south."),
    SA("Puglia, Basilicata and Calabria",
       "Puglia gained a DOCG for a naturally sweet style of Primitivo. Which town names it?",
       "Manduria",
       ["manduria", "primitivo di manduria", "primitivo di manduria dolce naturale",
        "manduria in puglia"],
       "The sweet version stops fermentation while sugar remains rather than adding spirit, which is what naturale records. The dry Primitivo di Manduria from the same town stays at DOC."),
    SA("Puglia, Basilicata and Calabria",
       "Salento's leading red carries a name usually read as black and bitter. Name the grape.",
       "Negroamaro",
       ["negroamaro", "negro amaro", "negroamaro grape"],
       "The everyday reading is black and bitter, though philologists more often trace it to the Latin niger and the Greek mavros, both simply meaning black. It makes deep reds and some of Italy's best-regarded roses."),
    SA("Puglia, Basilicata and Calabria",
       "Basilicata's DOCG rank applies only to a longer-aged version of its one famous red. Which word marks that on the label?",
       "Superiore",
       ["superiore", "aglianico del vulture superiore", "vulture superiore", "the word superiore"],
       "The standard bottling remains a DOC and only the extended-ageing wine was promoted. Volcanic soils and altitude on the Vulture give the acidity that carries the wine through those years.", ex=True),
    SA("Puglia, Basilicata and Calabria",
       "A sweet passito made in a town at the southern tip of Calabria carries the town's name. Name the wine.",
       "Greco di Bianco",
       ["greco di bianco", "greco bianco", "greco di bianco doc", "greco di bianco passito"],
       "The grapes are dried on mats in the sun on a stretch of coast facing Sicily. The wine is amber, orange-scented and made in tiny quantity, and the town really is called Bianco."),

    # -------------------------------------------------------------- Sicily (7)
    Q("Sicily",
      "Etna's vineyards are mapped by contrada. What does that term denote?",
      ["A named vineyard district on the mountain's flank", "A style of low bush training",
       "A cooperative cellar shared by growers", "A grade of minimum ageing"], 0,
      "The contrade are administrative parcels that growers now use much as Burgundy uses climats, and many appear on labels. Soil, altitude and lava flow age change sharply between neighbouring ones."),
    Q("Sicily",
      "One Marsala grade forbids the sweetening additions the others permit. Which grade is it?",
      ["Vergine", "Fine", "Superiore", "Superiore Riserva"], 0,
      "Vergine takes no cooked must and no mistella, so it is dry and shaped entirely by long oxidative ageing. The other grades may be adjusted for colour and sweetness."),
    Q("Sicily",
      "Grillo arose as a crossing of which two Sicilian grapes?",
      ["Catarratto and Zibibbo", "Inzolia and Carricante", "Grecanico and Nero d'Avola",
       "Catarratto and Inzolia"], 0,
      "The Muscat parent explains the faint grapey lift in a grape otherwise known for body and resistance to oxidation. Those qualities are why it became the backbone of good Marsala."),
    SA("Sicily",
       "Etna Bianco Superiore may be grown in one commune only, on the eastern flank. Name it.",
       "Milo",
       ["milo", "milo commune", "commune of milo", "milo on etna"],
       "Milo faces the Ionian sea and catches most of the rain that reaches the mountain, which suits Carricante's late ripening. The Superiore rules also demand a higher share of that grape."),
    SA("Sicily",
       "Nerello Mascalese must lead an Etna Rosso, with a softer partner permitted alongside. Name that partner.",
       "Nerello Cappuccio",
       ["nerello cappuccio", "cappuccio", "nerello mantellato", "nerello cappuccio grape"],
       "Cappuccio brings colour and flesh where Mascalese brings perfume, tannin and acidity. Its name describes the cloak of leaves the vine throws over itself."),
    SA("Sicily",
       "Sweet passito from the Aeolian islands north of Sicily is named for the largest island of the group. Name the wine.",
       "Malvasia delle Lipari",
       ["malvasia delle lipari", "malvasia di lipari", "malvasia lipari",
        "malvasia delle lipari doc"],
       "Salina rather than Lipari itself grows most of it, on volcanic terraces above the sea. The grapes are dried on racks and the wine comes out amber, apricot-scented and lightly herbal."),
    SA("Sicily",
       "Which Sicilian white is the island's most planted variety, long used as base wine for Marsala?",
       "Catarratto",
       ["catarratto", "catarratto bianco", "catarratto grape"],
       "It crops generously and was for decades sent north or distilled rather than bottled with any ambition. Lower yields and earlier picking have shown it can make a serious dry white."),

    # ------------------------------------------------------------ Sardinia (6)
    Q("Sardinia",
      "Ungrafted bush vines more than a century old grow in deep sand in Sardinia's southwest. Which denomination covers them?",
      ["Carignano del Sulcis", "Cannonau di Sardegna", "Mandrolisai", "Nuragus di Cagliari"], 0,
      "The sand of Sant'Antioco and the Sulcis coast defeated phylloxera, so old own-rooted alberello vines survive. The wine is fuller and riper than Carignan usually manages in France."),
    Q("Sardinia",
      "A Sardinian white ages under a film of yeast in part-filled casks in the Tirso valley. Which wine is it?",
      ["Vernaccia di Oristano", "Malvasia di Bosa", "Nasco di Cagliari",
       "Vermentino di Sardegna"], 0,
      "The flor works as it does in Jerez, and the wine emerges dry, nutty and high in alcohol without being fortified. It has nothing to do with Vernaccia di San Gimignano in Tuscany."),
    SA("Sardinia",
       "Vermentino reaches its most concentrated form on the island in a northeastern zone of decomposed granite. Name that zone.",
       "Gallura",
       ["gallura", "vermentino di gallura", "gallura zone", "gallura in the northeast"],
       "Granite sand drains fiercely and holds the vines short of water, which concentrates the fruit. The rest of the island bottles the grape under a broader denomination covering all of Sardinia."),
    SA("Sardinia",
       "Sardinia's Spanish centuries left a Catalan-speaking town in the northwest whose name marks a DOC. Name the town.",
       "Alghero",
       ["alghero", "alghero doc", "alghero in sardinia", "town of alghero"],
       "Aragon repopulated the town from Catalonia in the fourteenth century and the language held. The DOC is unusually permissive, covering a long list of varieties in every colour."),
    SA("Sardinia",
       "A white variety brought over from Spain survives almost nowhere but around Alghero. Name it.",
       "Torbato",
       ["torbato", "torbato grape", "torbato di alghero"],
       "It nearly disappeared and was kept going by a single large producer in the town. The wine is dry, saline and firmer than most Mediterranean whites of its weight."),
    SA("Sardinia",
       "Which red grape gives Sardinia a light everyday DOC bottled under its own varietal name across much of the island?",
       "Monica",
       ["monica", "monica di sardegna", "monica grape"],
       "Monica makes a soft, low-tannin red for drinking young, quite unlike Cannonau in weight. It is planted widely enough to carry an island-wide denomination of its own."),
]
