"""Rank II rewrite - Producers & Icons (41 questions: 8 MC, 33 short answer).

Certified level, pitched deliberately above the Rank I "Producers & Icons"
category, which was written first and read end to end before a word of this one.
Rank I owns "which house makes which famous wine" completely - the yellow label,
the artist labels, the pagodas, the braille, Monfortino, Nacional, Grange - and
nothing here sets that task. What is asked instead is what a professional knows
about a house once the name is already on the table: which grand cru it holds
outright, what is actually in the cuvee and whether the cuvee is declared at all,
what governs the second label, which vessel the cellar counts in, and which of
its bottlings answers to a rule rather than to a recipe.

The running order is built around one idea: an icon is a decision made twice
over, once in the vineyard and once in the office. So the blocks run from the
ground the house holds, through what goes into the bottle and what is left out of
it, to the second labels, the trading arrangement, the plots and vessels the
cellar is known by, the words printed on the back, and last the rules a handful
of houses have imposed on themselves and never relaxed.

Written from the syllabus below. The imported bank was not read while writing; it
is read only afterwards, by check-similarity.py. The committed Rank II regional
categories were read first as well, and their estates were deliberately left
alone: Latour's Enclos, Cheval Blanc's Bouchet, Tignanello, Solaia, Masseto,
Cannubi, Opus One, To Kalon, Bien Nacido, Scharzhofberg, Erdener Pralat and the
Cote Blonde all belong to questions that already exist somewhere in this corpus.

Accept lists are built against lib.match_sa, a port of core.js matchSA, and were
verified by executing a probe script rather than by eye: for every short answer
the displayed answer, two natural rephrasings and every wrong answer that could
be named were graded, and the wrong answers had to come back False. No '~'
entries appear anywhere, since the tilde is exact-OR-containment and a one-word
tilde grades any wrong answer holding that word.

Two hazards drove the ex=True decisions. The first is that a real and different
name so often contains the right one: Salon sits whole inside Menetou-Salon,
Grenache inside Grenache Blanc, Chalon inside Chalon-sur-Saone, Clarence inside
nothing but its own longer form, and Rosacker beside the Geisberg and Osterberg
that another question in this file asks for. The second is core.js norm(), which
strips 'the', 'a', 'an', 'chateau', 'domaine', 'de', 'du', 'des', 'la' and 'le',
so 'la grande rue' and 'grande rue' collapse into one string, 'chateau chalon'
normalises to 'chalon', and half the obvious accept entries here turned out to be
duplicates of each other once normalised. Every list was checked for that.
Each ex=True list was then widened until article, hyphen, spelling, abbreviation
and word-order variants of its own answer all still grade, because exact matching
rejects anything not written down.

Facts are restricted to ones that do not drift. No ownership changes, no volumes,
no price standings, no promotions from the last few years. Vineyard boundaries,
label law, cellar practice, cask sizes, the composition of a cuvee and the
self-imposed rules a house has kept for generations carry the weight instead.
"""

from lib import Q, SA

CAT = "Producers & Icons"
SLUG = "r2-producers-icons"
PREFIX = "c"
RANK = "Rank II"
SOURCE = "data-questions.js"

SYLLABUS = [
    ("Monopoles and vineyards held outright", 5),
    ("What is actually in the icon bottle", 5),
    ("Declared, skipped and held back", 4),
    ("Second and third labels", 5),
    ("Grower, negociant and merchant", 5),
    ("Single plots and single wines", 5),
    ("Vessels a house is known by", 4),
    ("The words on the back label", 4),
    ("Houses that set their own rule", 4),
]

BANK = [
    # ------------------------ Monopoles and vineyards held outright (5) ------
    Q("Monopoles and vineyards held outright",
      "One French grand cru appellation covers exactly the ground of a single property, so the appellation boundary and the estate map are the same line. Which appellation?",
      ["Romanee-Conti", "Echezeaux", "Musigny", "Corton"], 0,
      "The appellation runs to a shade under two hectares in Vosne-Romanee and has not been divided in living memory, so a vintage yields one wine and one only. Echezeaux and Corton sit at the other extreme, each of them split among dozens of separate owners, and even Musigny, small as it is, is shared among a handful."),
    SA("Monopoles and vineyards held outright",
       "A narrow strip of vineyard runs straight up the slope between Romanee-Conti and La Tache, and every row of it has long been farmed by one family. Name that climat.",
       "La Grande Rue",
       ["la grande rue", "la grande rue grand cru", "la grande rue monopole",
        "the la grande rue climat", "grande rue in vosne romanee",
        "la grande rue vineyard"],
       "It was left a premier cru when the grand crus of Vosne-Romanee were drawn up in the 1930s and was promoted only in 1992, late enough that older books still print it a rank below its neighbours. The name records an old road running up the hill rather than any claim about the wine, and the strip is narrow because it follows that route.",
       ex=True),
    SA("Monopoles and vineyards held outright",
       "Clos Sainte Hune, a walled plot of a little over a hectare and a half at Hunawihr, lies inside one of Alsace's grand crus, though the label has traditionally said nothing about it. Name the grand cru.",
       "Rosacker",
       ["rosacker", "rosacker grand cru", "grand cru rosacker",
        "the rosacker vineyard", "rosacker at hunawihr", "rosacker in alsace",
        "rosacker grand cru at hunawihr"],
       "Rosacker is limestone and dolomite on the slope above Hunawihr, and the clos sits in the heart of it. The house behind the wine built its reputation long before the grand cru system was delimited at all, which is why the plot name has always carried more weight on that label than the site name would.",
       ex=True),
    SA("Monopoles and vineyards held outright",
       "A wall dated 1698 encloses just under two hectares of Chardonnay in the middle of the village of Le Mesnil-sur-Oger, and the house that bought it in 1971 bottles the plot on its own in declared years. Name the clos.",
       "Clos du Mesnil",
       ["clos du mesnil", "clos du mesnil blanc de blancs", "krug clos du mesnil",
        "clos du mesnil in le mesnil sur oger", "the clos du mesnil vineyard"],
       "Being walled inside a village rather than open on the slope, it ripens a little differently from the vineyard around it, which is the whole argument for keeping it apart. A single-vineyard Champagne of this kind gives up the blender's usual insurance, so it appears only in years the plot can carry a wine by itself.",
       ex=True),
    SA("Monopoles and vineyards held outright",
       "Above the Marne at Mareuil-sur-Ay a walled slope pitches at something close to forty-five degrees, the steepest planted ground in Champagne, and it has been bottled as a vintage wine in nearly every harvest since 1935. Name that clos.",
       "Clos des Goisses",
       ["clos des goisses", "goisses", "philipponnat clos des goisses",
        "clos des goisses at mareuil sur ay", "clos des goisses monopole"],
       "The pitch and the due-south exposure ripen fruit well ahead of the villages around it, which is why the wine can be declared in years its neighbours would not. Goisses comes from a local word for a very steep slope, so the name describes the ground rather than the wine, and the wall marks a holding that has never been broken up.",
       ex=True),

    # -------------------------- What is actually in the icon bottle (5) ------
    Q("What is actually in the icon bottle",
      "A guest compares two vintages of one classified Medoc estate and finds the first blend led by Merlot and the second by Cabernet Sauvignon, although no vines were pulled up between them. What accounts for the swing?",
      ["Lots that fell short of the grand vin were left out of it, and which variety fell short differs from one year to the next",
       "The estate replanted a large parcel and did not announce it",
       "Appellation rules fix a different blend for each vintage according to the season",
       "The second wine takes a fixed share of every variety, so what remains sets the proportions"], 0,
      "Planting is a decision of decades and blending a decision of one winter, so the two never match. A wet September that spoils the Merlot and a cool one that leaves the Cabernet green both show up in the assemblage rather than in the vineyard, and an estate that kept its proportions fixed in spite of the season would be bottling its weather, not correcting for it."),
    SA("What is actually in the icon bottle",
       "Alsace's grand cru rules admit only one named site to a label, so a house whose long-lived Riesling cuvee is drawn from parcels in a pair of them prints no grand cru name at all. Which grand crus are blended in that cuvee?",
       "Geisberg and Osterberg",
       ["geisberg and osterberg", "osterberg and geisberg", "geisberg osterberg",
        "osterberg geisberg",
        "grand cru geisberg and grand cru osterberg",
        "geisberg and osterberg above ribeauville",
        "the geisberg and osterberg grand crus"],
       "The pair sit side by side on the slope above Ribeauville, Geisberg the steeper and more terraced of them, and a blend across the two forfeits a mention that either could have carried alone. The house treats its own cuvee name as the stronger claim, which is a fair reading of how Alsace was actually sold before the grand crus were delimited.",
       ex=True),
    SA("What is actually in the icon bottle",
       "One Champagne prestige cuvee is assembled from several declared vintages rather than from a single one, on the argument that a blend of good years beats the best of them alone, and it therefore carries no date. Name that cuvee.",
       "Grand Siecle",
       ["grand siecle", "laurent perrier grand siecle", "grand siecle laurent perrier",
        "the grand siecle cuvee"],
       "Each release blends years the house had declared as vintages in their own right, which reverses the usual assumption that a vintage wine outranks a blended one. The house now numbers each release as an iteration in its own sequence, and each is built from a different trio of those years rather than to a fixed recipe."),
    SA("What is actually in the icon bottle",
       "A dry white is pressed at the sole Premier Cru Superieur of Sauternes, from the same rows as its sweet wine, and it goes to market under a single letter of the alphabet. Name that wine.",
       "Ygrec",
       ["ygrec", "y", "y ygrec", "the letter y", "ygrec dry white",
        "y dry white of yquem", "ygrec the dry white of yquem",
        "the dry white called y", "y d'yquem", "ygrec d'yquem",
        "y yquem", "ygrec yquem", "y of yquem", "ygrec of yquem"],
       "Ygrec is the French name of the letter Y, and the wine is a Sauvignon and Semillon blend from fruit picked before botrytis takes hold, or from a year in which it never does. It is not declassified sweet wine: the decision is taken at the start of the harvest rather than at the end of it, and the wine is fermented dry on purpose. Yquem stands alone as Premier Cru Superieur above the eleven first growths of 1855, several of which now press a dry white of their own under a single initial, R at Rieussec, S at Suduiraut and G at Guiraud.",
       ex=True),
    SA("What is actually in the icon bottle",
       "Two adjoining Stags Leap District vineyards, S.L.V. and Fay, are normally bottled apart; in years when a barrel selection drawn from both is judged to beat either, one Napa winery releases a third wine instead. Name it.",
       "Cask 23",
       ["cask 23", "cask twenty three", "cask 23 cabernet sauvignon",
        "the cask 23 bottling", "stag s leap wine cellars cask 23",
        "cask 23 from stag s leap"],
       "The wine began as a single cask set aside in 1974 and has been made only in vintages the cellar thinks justify it. Naming the source vineyards on their own labels and blending them for the flagship is the reverse of the Bordeaux habit, where the blend is the flagship and the parcels are never seen at all.",
       ex=True),

    # ------------------------------ Declared, skipped and held back (4) ------
    Q("Declared, skipped and held back",
      "From the 2012 vintage one Pauillac first growth stopped offering its wine as futures and now releases each vintage when it judges the wine ready to drink. What changed for the buyer?",
      ["It arrives years later, at a price set against the market of the day",
       "It arrives a year earlier, before the final blend has been settled",
       "The estate's 1855 rank lapses on any vintage sold outside a futures campaign",
       "Only the estate may sell it, the negociants of the Place having been cut out of the trade altogether"], 0,
      "Selling futures moves the cash risk from the chateau to the buyer and the storage risk with it, and withdrawing reverses both. The estate holds the stock in its own cellars for a decade and releases in tranches, and the trade still handles the wine, so what disappeared is the barrel sale rather than the merchant."),
    SA("Declared, skipped and held back",
       "A Cote des Blancs house has never made a non-vintage wine, a rose or a blend of villages, and in a year it does not care for it releases nothing at all under its name. Name that house.",
       "Salon",
       ["salon", "champagne salon", "maison salon", "salon le mesnil",
        "salon blanc de blancs", "salon cuvee s", "cuvee s salon",
        "salon of le mesnil sur oger"],
       "Fewer than fifty vintages have been released since the first in 1905, so in most years the fruit it has contracted goes elsewhere and no bottle appears. The wine is a blanc de blancs from one grand cru village, held far beyond the legal minimum before disgorgement, and the refusal to make anything else is the whole of the house's proposition.",
       ex=True),
    SA("Declared, skipped and held back",
       "One Champagne house releases the same vintage more than once: at around eight years, and then again after far longer on the lees, with every release presented as a further stage in that wine's life. What does the house call those stages?",
       "Plenitude",
       ["plenitude", "plenitudes", "p2", "p3", "p 2", "p 3", "plenitude p2",
        "second plenitude", "deuxieme plenitude", "plenitude releases",
        "plenitude p3", "the plenitude stages"],
       "The argument is that a wine on its lees does not develop steadily but arrives at a series of windows, and the cellar disgorges at each of them rather than once. The later releases were sold for years under a different name borrowed from the house's own library before the current one was adopted, so old bottles and new ones carry both.",
       ex=True),
    SA("Declared, skipped and held back",
       "Growers in one Jura appellation submit their wine to a committee that may refuse the whole vintage, and when it does, not a bottle is sold under the name. Name that appellation.",
       "Chateau-Chalon",
       ["chateau chalon", "chateau chalon aoc", "aoc chateau chalon",
        "the chateau chalon appellation", "chateau chalon vin jaune",
        "chateau chalon in the jura"],
       "The appellation makes vin jaune and nothing else, and the wine spends more than six years in cask under a veil of yeast before it may be bottled, so a refusal falls on work long since done. Whole vintages were declassified outright in the 1970s and 1980s, and the rejected wine goes to market as plain Cotes du Jura instead.",
       ex=True),

    # -------------------------------------- Second and third labels (5) ------
    Q("Second and third labels",
      "Asked at the table what a Bordeaux second wine actually contains, a sommelier should be able to answer without guessing. What governs it?",
      ["Whatever the estate left out of its grand vin, most often young vines and parcels that underperformed",
       "Fruit from a separate vineyard the estate keeps for the purpose, outside its classified holding",
       "The press wine, the free-run juice all going into the grand vin",
       "A share of the crop fixed by the appellation, which is why the proportion barely moves from one vintage to the next"], 0,
      "Nothing in law fixes the category, so a second wine carries the same appellation as the grand vin and differs from it only by selection. Estates that once sold their surplus lots in bulk now bottle them, and several have added a third wine underneath, which is a commercial judgement about how far the selection can be pushed."),
    SA("Second and third labels",
       "A Margaux third growth presents its junior label not as a strainer for lots that missed the grand vin but as a different reading of the same vineyard, picked and raised its own way. Name that wine.",
       "Alter Ego",
       ["alter ego", "alter ego de palmer", "the alter ego of palmer",
        "alter ego the second label"],
       "Palmer makes the point that the wine is not lesser but different: more Merlot, earlier picking, a shorter elevage and a style meant to be drunk sooner. Whether a buyer accepts that or reads it as a second wine with better marketing is exactly the argument the label was built to start."),
    SA("Second and third labels",
       "Bahans Haut-Brion disappeared from wine lists after the 2006 vintage, although the wine behind the name did not. What is that second wine called now?",
       "Le Clarence de Haut-Brion",
       ["le clarence de haut brion", "clarence", "clarence of haut brion",
        "le clarence de haut brion the second wine"],
       "The name honours Clarence Dillon, the American financier who bought the property in 1935, and the change lined the second wine up with the family name used across the group. Second labels are renamed often enough that a wine list can be years out of date without anyone noticing, which is reason enough to check the vintage against the name.",
       ex=True),
    SA("Second and third labels",
       "One Ribera del Duero bodega sells a red in its fifth year, drawn from the same vineyards as a flagship it holds back roughly twice as long. Name the wine released early.",
       "Valbuena",
       ["valbuena", "valbuena 5", "valbuena 5o", "valbuena cinco",
        "vega sicilia valbuena", "valbuena quinto ano", "valbuena 5 ano",
        "the valbuena bottling"],
       "The number in its name counts the years from harvest to release rather than anything about the blend, and the fruit comes off the same estate rather than off lesser ground. Selling a serious wine early is a cash decision as much as a stylistic one, since a cellar holding stock for a decade has to be paid for somehow.",
       ex=True),
    SA("Second and third labels",
       "A Napa estate founded as a Franco-American partnership sells a second wine blended across several harvests, so it carries no vintage at all. Name it.",
       "Overture",
       ["overture", "overture from opus one", "opus one overture",
        "the overture bottling", "overture napa valley", "overture by opus one"],
       "Blending several years into one red is ordinary in Champagne and rare in Napa, where the vintage date is treated as part of the claim. It is sold largely at the winery rather than through the trade, which is why it turns up on wine lists far less often than the estate's flagship does.",
       ex=True),

    # -------------------------------- Grower, negociant and merchant (5) -----
    Q("Grower, negociant and merchant",
      "Printed on a French label the word Chateau is not decoration, and it may be used only where a pair of conditions are met. Which pair?",
      ["The grapes all come off the estate's own vines, and the wine is vinified there",
       "The estate holds a rank in a recognised classification, and a building stands on the land",
       "The property sits inside a communal appellation, and its owner farms at least ten hectares",
       "The fruit is grown and bottled in the same commune, and the label states the year the estate was founded"], 0,
      "The rule is about the fruit and the winemaking rather than about architecture: every grape must be grown on the named holding and the wine made there, so plenty of chateaux are sheds and plenty of grand houses have no vines at all. It comes from the same body of French law that governs Domaine, Clos, Cru and Abbaye, all of them traditional terms with conditions attached rather than free adjectives."),
    SA("Grower, negociant and merchant",
       "In Jerez a private stockholder buys young wine, ages a few butts of it in a warehouse of his own and sells the result on to the shippers rather than bottling under his own name. What is he called?",
       "Almacenista",
       ["almacenista", "almacenistas", "almacenista stockholder",
        "a jerez almacenista"],
       "The word means warehouseman, and the trade grew up because ageing stock is slow money that a small holder can afford to tie up and a shipper would rather buy than carry. Some of those soleras are now bottled under the almacenista's name alongside the shipper's, which is how a category that existed to be invisible became collectable."),
    SA("Grower, negociant and merchant",
       "Until 1986 no Port could be exported unless it had first been aged in one town across the river from Oporto, which is why the quintas up the valley shipped nothing under their own names. Name that town.",
       "Vila Nova de Gaia",
       ["vila nova de gaia", "gaia", "villa nova de gaia",
        "vila nova de gaia across the douro"],
       "The rule bound the trade to the shippers' lodges and to their entrepot, so a grower who wanted to sell abroad had to sell to a shipper first. Its repeal is why estates up the valley began bottling and exporting under their own names from the late 1980s, and the modern shape of the Douro trade follows from it."),
    SA("Grower, negociant and merchant",
       "A Burgundian grower who buys grapes as well as farming his own registers a second business for the bought fruit, and by long convention its bottles open with a different word from the estate's. Which word?",
       "Maison",
       ["maison", "maison rather than domaine", "the word maison",
        "maison instead of domaine", "maison followed by the name",
        "maison on the label", "the maison prefix", "maison not domaine"],
       "Domaine is reserved by law for wine off the grower's own vines and Maison signals a merchant business, even where one family runs both from one cellar. Maison is defined nowhere at all, which is why a house that farms not a single row may call itself one with nobody's permission; what the law polices is the word Domaine, and the merchant word is left to the trade's own convention.",
       ex=True),
    SA("Grower, negociant and merchant",
       "Barrels sold at the Hospices de Beaune auction are catalogued under cuvee names that appear on no map of the slope, and the buyer's own cellar raises and bottles the wine afterwards. What do those cuvee names record?",
       "The benefactors who gave the vineyards",
       ["the benefactors who gave the vineyards", "benefactors", "donors",
        "the people who donated the vines", "the donors of the vineyards",
        "benefactors who donated the vines", "the names of the donors",
        "past donors", "the people who gave the vineyards to the hospices",
        "the donors who left vines to the hospital"],
       "The hospital has been left vines since the fifteenth century, and each bequest is kept as a named cuvee rather than folded into the rest, so the catalogue reads as a list of benefactors. A cuvee may draw on parcels in more than one climat, which is exactly why those names cannot be found on any vineyard map."),

    # --------------------------------- Single plots and single wines (5) -----
    Q("Single plots and single wines",
      "Long before grafting, a grower who lost a vine bent a cane down from the plant beside it, buried the middle of that cane until it took root and then cut it free. Which operation is this?",
      ["Provignage", "Ebourgeonnage", "Palissage", "Greffage"], 0,
      "The new plant grows on its own roots and carries the parent's material exactly, so a plot renewed this way keeps whatever selection was originally in it. It also explains why old ungrafted parcels are irregularly spaced: a vine put there by layering stands where its parent could reach, not where a surveyor wanted it."),
    SA("Single plots and single wines",
       "Small walled parcels at Ay carry Pinot Noir that was never grafted onto American rootstock, and the blanc de noirs made from them runs to a few thousand bottles in the years it appears. Name that cuvee.",
       "Vieilles Vignes Francaises",
       ["vieilles vignes francaises", "vvf", "bollinger vieilles vignes francaises",
        "vieilles vignes francaises bollinger", "the vieilles vignes francaises cuvee",
        "bollinger vvf", "vieilles vignes francaises champagne"],
       "French old vines is all the name claims, and the point of it is the ungrafted stock rather than the age of any particular plant. A third parcel at Bouzy was lost to phylloxera and grubbed up in the 2000s, which is a reminder that such plots survive by constant work rather than by luck.",
       ex=True),
    SA("Single plots and single wines",
       "A single Yountville vineyard planted in the nineteenth century supplies the whole of a Napa red whose name is the Latin for lord and master of the house. Name the vineyard.",
       "Napanook",
       ["napanook", "napanook vineyard", "napanook in yountville",
        "the napanook site"],
       "Napanook was among the first vineyards planted in that part of the valley and its fruit was sold to other wineries for most of a century before it was bottled on its own. Yountville sits between the cool of Oak Knoll and the warmth of Oakville, which is much of why the wine is built on structure rather than on ripeness."),
    SA("Single plots and single wines",
       "A Bordeaux family that had already founded a Napa joint venture set up a second one in the 1990s on Andean gravels in the upper Maipo, and the wine took its name from a character in Beaumarchais. Name it.",
       "Almaviva",
       ["almaviva", "vina almaviva", "almaviva in maipo", "almaviva chile",
        "the almaviva red"],
       "Count Almaviva belongs to The Marriage of Figaro, and the label carries a design borrowed from Mapuche art, so the bottle advertises both partners at once. The Chilean partner was already growing Cabernet of the first rank on that stretch of gravel, which is why the ground was settled before the deal was."),
    SA("Single plots and single wines",
       "A Saint-Emilion first growth and a Mendoza estate share a Malbec-led red grown on stony Andean ground at around a thousand metres. Name that wine.",
       "Cheval des Andes",
       ["cheval des andes", "cheval des andes mendoza",
        "terrazas cheval des andes", "the cheval des andes joint venture"],
       "Malbec leads it and Cabernet Sauvignon fills it out, which is the Bordeaux partner's contribution to a grape Argentina had long bottled on its own. Mendoza's old ungrafted Malbec is the material such ventures are really after, since cuttings of that quality no longer exist in the variety's homeland."),

    # ---------------------------------- Vessels a house is known by (4) ------
    SA("Vessels a house is known by",
       "Mosel estates have always aged in a large oval cask of about a thousand litres, and older price lists quote a crop by the number of them filled. Name that cask.",
       "Fuder",
       ["fuder", "fuders", "fuder cask", "mosel fuder", "german fuder",
        "a thousand litre fuder", "1000 litre fuder"],
       "A thousand litres of wine touching that much oak takes almost nothing from the wood, which is exactly the point on a Riesling meant to taste of slate and fruit. The half-size cask is a Halbfuder and the Rhine's equivalent is larger again, and all of them are giving way in many cellars to steel, which does the same job of adding nothing at all.",
       ex=True),
    SA("Vessels a house is known by",
       "Bordeaux quotes a crop and a price in a unit that no cellar actually contains: nine hundred litres, or four barriques. Name that unit.",
       "Tonneau",
       ["tonneau", "tonneaux", "one tonneau", "the bordeaux tonneau"],
       "Nine hundred litres is twelve hundred bottles, or a hundred cases of twelve, so a chateau's crop and an opening price are both still discussed in tonneaux although the wine never sits in one. It is a unit of account inherited from the days when claret travelled in cask, and it survives because everyone in the trade can convert it in their head."),
    SA("Vessels a house is known by",
       "Northern Rhone cellars often raise Syrah in a cask of about six hundred litres, larger than a barrique and smaller than a foudre, chosen so that the oak marks the wine less. Name it.",
       "Demi-muid",
       ["demi muid", "demi muids", "demimuid", "demi muid cask"],
       "Half a muid, the muid being an old measure that varied from town to town, so the name is a fossil of a unit nobody uses any more. The wider stave and the lower ratio of wood to wine give slower oxygen and much less vanilla than a barrique, which is why estates trying to lighten their oak move to this size rather than merely to older barrels."),
    SA("Vessels a house is known by",
       "Douro contracts and lodge records still count in a cask of roughly five hundred and fifty litres, and a shipper's stock is described in them rather than in litres. Name that cask.",
       "Pipe",
       ["pipe", "pipes", "port pipe", "the douro pipe", "pipa", "a pipe of port",
        "port pipes", "pipe cask", "port pipe cask"],
       "The word covers a family of sizes rather than one exact volume, since the shipping pipe of about 534 litres, the valley pipe of 550 and the larger lodge pipe used for ageing all differ. Production of a declared vintage is still quoted in pipes, which is why the figures in a trade report never look like litres.",
       ex=True),

    # ------------------------------------ The words on the back label (4) ----
    Q("The words on the back label",
      "Two bottles of one house's multi-vintage cuvee carry different edition numbers on the label, and no vintage appears anywhere on either. What does that number identify?",
      ["The particular blend, so one release can be told from the next",
       "How long the wine spent on its lees before it was disgorged",
       "The dosage in grams per litre, printed as a code rather than a figure",
       "The cellar in which that lot was aged, which the house treats as part of the wine's identity"], 0,
      "A multi-vintage blend is remade every year and is never quite the same wine twice, which the old convention of calling it simply non-vintage concealed. Numbering the releases lets a buyer, a sommelier and a critic all refer to one specific assembly, and some houses print a further code that resolves to the disgorgement date."),
    SA("The words on the back label",
       "One Reims house prints on every non-vintage bottle the year in which the blend went down into its cellar, so a buyer can work out how long it lay there before release. Give the French phrase used for that statement.",
       "Mis en cave",
       ["mis en cave", "mise en cave", "the mis en cave date", "mis en cave year",
        "date de mise en cave"],
       "The blend is assembled from one harvest and its reserves and then bottled for its second fermentation, and the year printed is the year that happened. A bottle laid down in one year and released six later has therefore spent that whole span on its lees, which the label of an ordinary non-vintage leaves a buyer to guess at."),
    SA("The words on the back label",
       "Tiny quantities of intensely extracted Right Bank red, made in the 1990s in cellars barely larger than the buildings they were nicknamed after, earned their makers a label they never chose. What were they called?",
       "Garagistes",
       ["garagistes", "garagiste", "garage winemakers", "the garage movement"],
       "The name began as a jibe about scale and the wines turned it into a marketing category, with prices following critical scores rather than any classification. The style went out of fashion as taste moved back towards freshness, but the argument it started, about whether a small parcel farmed obsessively can outrank a classified estate, has not gone away."),
    SA("The words on the back label",
       "Across the top of a bottle of everyday claret run the words Grand Vin de Bordeaux, printed larger than anything else on the label. What does that phrase promise about the wine?",
       "Nothing at all",
       ["nothing at all", "nothing", "nothing whatever", "it promises nothing",
        "no guarantee", "it guarantees nothing", "absolutely nothing",
        "no promise at all", "nothing it has no legal meaning",
        "nothing the phrase has no legal force", "nothing whatsoever",
        "no promise", "it means nothing", "it has no legal meaning",
        "no legal meaning", "it carries no legal meaning",
        "it has no legal force", "no legal force", "nothing legally",
        "it is not defined in law", "no legal definition",
        "it has no legal definition"],
       "Grand vin has a real use inside a chateau, where it names the estate's first selection as against its second wine, but printed as a slogan on a regional bottling it carries no requirement of any kind. The statements that do bind on that label are the appellation, the vintage and the bottling line, and none of them is usually the largest thing on it.",
       ex=True),

    # ------------------------------- Houses that set their own rule (4) ------
    Q("Houses that set their own rule",
      "Merchants who want a case of one Vosne-Romanee domaine's grand crus are obliged to take a spread of its lesser wines in the same shipment. What does that practice achieve for the domaine?",
      ["The whole range moves, the famous bottles carrying the rest with them",
       "It keeps the grand crus out of the auction rooms, where resale is forbidden by the appellation",
       "It satisfies a Burgundian rule obliging a producer to offer its whole range to any buyer",
       "It lowers the duty due on the shipment, which is levied on the case rather than on the bottle"], 0,
      "A village Vosne-Romanee is a harder sell than a grand cru, and tying the two together means the cellar never has to discount either of them. The buyer's compensation is that the door stays open for the next vintage, which is worth more than the margin lost on the wines they did not especially want."),
    SA("Houses that set their own rule",
       "One Barossa house has kept a workshop inside its winery since the 1940s, turning out something almost every other winery in the world buys in. What does it make there?",
       "Oak barrels",
       ["oak barrels", "barrels", "casks", "oak casks", "wooden barrels",
        "wooden casks", "barriques", "wine barrels", "its own barrels",
        "its own oak barrels", "its own casks", "its own oak casks",
        "its own wooden barrels", "its own wooden casks", "its own barriques",
        "its own wine barrels", "it makes barrels", "it makes oak barrels",
        "it makes casks", "it makes oak casks", "it makes wooden barrels",
        "it makes wooden casks", "it makes barriques", "it makes wine barrels",
        "it makes its own barrels", "it makes its own oak barrels",
        "it makes its own casks", "it makes its own oak casks",
        "it makes its own wooden barrels", "it makes its own wooden casks",
        "it makes its own barriques", "it makes its own wine barrels",
        "cooperage", "its own cooperage", "barrels in its own cooperage",
        "barrel", "oak barrel", "makes barrels", "makes oak barrels",
        "makes casks", "makes its own barrels", "makes its own oak barrels",
        "makes its own casks", "it makes its barrels",
        "it makes all its own barrels", "they make their own barrels",
        "make their own barrels", "it builds its own barrels",
        "builds its own barrels", "it makes and repairs barrels",
        "it still makes its own barrels", "it still makes its own oak barrels",
        "oak barrels in its own cooperage", "oak casks and barrels",
        "barrels and casks", "it has its own cooperage", "has its own cooperage",
        "its cooperage", "a working cooperage", "in house cooperage"],
       "Yalumba is the house, and a working cooperage lets it buy standing timber, season the staves for as long as it likes and build to its own specification rather than take what a supplier offers. Almost nobody else bothers, because the craft takes a cooper's whole working life to learn and one winery needs only a few hundred barrels a year.",
       ex=True),
    SA("Houses that set their own rule",
       "In a vintage judged not strong enough, a Barbaresco cooperative declines to bottle any of the nine single-vineyard Riservas it is known for. What becomes of that fruit?",
       "It all goes into the cooperative's straight Barbaresco",
       ["the cooperative's straight barbaresco", "the straight barbaresco",
        "the normale barbaresco", "the normale", "the normal barbaresco",
        "the regular barbaresco", "the basic barbaresco",
        "the entry level barbaresco", "the ordinary barbaresco",
        "the classic barbaresco", "the standard barbaresco",
        "the plain barbaresco", "one barbaresco",
        "it goes into the cooperative's straight barbaresco",
        "it goes into the straight barbaresco",
        "it goes into the normale barbaresco", "it goes into the normale",
        "it goes into the normal barbaresco",
        "it goes into the regular barbaresco",
        "it goes into the basic barbaresco",
        "it goes into the entry level barbaresco",
        "it goes into the ordinary barbaresco",
        "it goes into the classic barbaresco",
        "it goes into the standard barbaresco",
        "it goes into the plain barbaresco", "it goes into one barbaresco",
        "it all goes into the cooperative's straight barbaresco",
        "it all goes into the straight barbaresco",
        "it all goes into the normale barbaresco",
        "it all goes into the normale",
        "it all goes into the normal barbaresco",
        "it all goes into the regular barbaresco",
        "it all goes into the basic barbaresco",
        "it all goes into the entry level barbaresco",
        "it all goes into the ordinary barbaresco",
        "it all goes into the classic barbaresco",
        "it all goes into the standard barbaresco",
        "it all goes into the plain barbaresco",
        "it all goes into one barbaresco",
        "all of it goes into the cooperative's straight barbaresco",
        "all of it goes into the straight barbaresco",
        "all of it goes into the normale barbaresco",
        "all of it goes into the normale",
        "all of it goes into the normal barbaresco",
        "all of it goes into the regular barbaresco",
        "all of it goes into the basic barbaresco",
        "all of it goes into the entry level barbaresco",
        "all of it goes into the ordinary barbaresco",
        "all of it goes into the classic barbaresco",
        "all of it goes into the standard barbaresco",
        "all of it goes into the plain barbaresco",
        "all of it goes into one barbaresco",
        "it is blended into the cooperative's straight barbaresco",
        "it is blended into the straight barbaresco",
        "it is blended into the normale barbaresco",
        "it is blended into the normale",
        "it is blended into the normal barbaresco",
        "it is blended into the regular barbaresco",
        "it is blended into the basic barbaresco",
        "it is blended into the entry level barbaresco",
        "it is blended into the ordinary barbaresco",
        "it is blended into the classic barbaresco",
        "it is blended into the standard barbaresco",
        "it is blended into the plain barbaresco",
        "it is blended into one barbaresco",
        "it is all blended into the cooperative's straight barbaresco",
        "it is all blended into the straight barbaresco",
        "it is all blended into the normale barbaresco",
        "it is all blended into the normale",
        "it is all blended into the normal barbaresco",
        "it is all blended into the regular barbaresco",
        "it is all blended into the basic barbaresco",
        "it is all blended into the entry level barbaresco",
        "it is all blended into the ordinary barbaresco",
        "it is all blended into the classic barbaresco",
        "it is all blended into the standard barbaresco",
        "it is all blended into the plain barbaresco",
        "it is all blended into one barbaresco",
        "blended into the cooperative's straight barbaresco",
        "blended into the straight barbaresco",
        "blended into the normale barbaresco", "blended into the normale",
        "blended into the normal barbaresco",
        "blended into the regular barbaresco",
        "blended into the basic barbaresco",
        "blended into the entry level barbaresco",
        "blended into the ordinary barbaresco",
        "blended into the classic barbaresco",
        "blended into the standard barbaresco",
        "blended into the plain barbaresco", "blended into one barbaresco",
        "it is declassified into the cooperative's straight barbaresco",
        "it is declassified into the straight barbaresco",
        "it is declassified into the normale barbaresco",
        "it is declassified into the normale",
        "it is declassified into the normal barbaresco",
        "it is declassified into the regular barbaresco",
        "it is declassified into the basic barbaresco",
        "it is declassified into the entry level barbaresco",
        "it is declassified into the ordinary barbaresco",
        "it is declassified into the classic barbaresco",
        "it is declassified into the standard barbaresco",
        "it is declassified into the plain barbaresco",
        "it is declassified into one barbaresco",
        "it all ends up in the cooperative's straight barbaresco",
        "it all ends up in the straight barbaresco",
        "it all ends up in the normale barbaresco",
        "it all ends up in the normale",
        "it all ends up in the normal barbaresco",
        "it all ends up in the regular barbaresco",
        "it all ends up in the basic barbaresco",
        "it all ends up in the entry level barbaresco",
        "it all ends up in the ordinary barbaresco",
        "it all ends up in the classic barbaresco",
        "it all ends up in the standard barbaresco",
        "it all ends up in the plain barbaresco",
        "it all ends up in one barbaresco"],
       "The crus are bottled only when the year justifies them, so a weak vintage yields one wine where a strong one yields ten. It runs against the usual incentive, since the cru bottlings are the profitable ones, and it is why the cooperative's ordinary Barbaresco in a lesser year is better than its price suggests.",
       ex=True),
    SA("Houses that set their own rule",
       "Chateauneuf-du-Pape permits a long list of varieties, and one celebrated estate there ignores all but a single grape, growing it on sand well back from the stony plateau. Which variety fills that red?",
       "Grenache",
       ["grenache", "grenache noir", "black grenache", "garnacha",
        "grenache alone", "one hundred percent grenache", "100% grenache",
        "pure grenache", "only grenache", "nothing but grenache",
        "grenache noir alone", "all grenache", "100 percent grenache",
        "100 % grenache", "grenache 100%", "grenache 100 percent",
        "100% grenache noir"],
       "Chateau Rayas is the estate, and its red carries no Syrah, no Mourvedre and nothing else the decree allows. Sand, the shade of surrounding pine woods and very low yields give a wine so pale and perfumed that it is regularly mistaken for red Burgundy blind, which is much of the reason it is argued about.",
       ex=True),
]
