"""Rank II rewrite - Spain (37 questions: 13 MC, 24 short answer).

Certified level, pitched deliberately above the Rank I "Spain" category. Where
Rank I names the three Rioja zones, this asks what a bodega must do inside one
before the label may print it; where Rank I asks how long a red Gran Reserva
ages, this asks what the same word demands of a white; where Rank I identifies
Palo Cortado from its symptoms, this asks what the capataz chalked on the butt
that sent the wine down the biological road in the first place. Nothing here
repeats a Rank I task.

The running order is built around one idea: in Spain the rulebook is the wine's
biography. So the file opens with the categories and what each of them costs a
producer, moves through Rioja's ground-based rungs and the national ageing
words, then walks the map - Duero, Catalunya, the northwest interior, Galicia -
asking in each place what the local rules demand rather than where the region
sits, and ends in Jerez and Sant Sadurni, where the vessel and the veil do the
work no rulebook can.

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py.

Accept lists are built against lib.match_sa, a port of core.js matchSA, and were
tested by execution rather than eyeballed. No '~' entries appear anywhere: the
tilde is exact-OR-containment, so a one-word tilde grades any wrong answer that
happens to hold that word. Spanish wine vocabulary is unusually full of names
that extend other names, and each was probed rather than assumed: Vino de Pago
against Vino de Pago Calificado, Cava de Guarda against Cava de Guarda Superior,
Albillo Mayor against the real and different Albillo Real, Hondarrabi Beltza
against Hondarrabi Zuri, Palma against the Dos and Tres Palmas age marks, and
Cream against Pale Cream. Where the wrong form graded, ex=True was applied and
the list then widened until every natural phrasing of the right answer still
graded, because exact matching rejects anything not written down. Every
threshold answer - a vine age, a bottle minimum, a varietal percentage - carries
ex=True for the reason build.py's comparative probe exists: read by containment
a threshold means the same thing in both directions.

Note that core.js norm() strips 'de', 'la' and 'des' as stopwords, which
collapses 'vino de pago calificado' and 'vino pago calificado' into one string,
so every list here was checked for entries that normalise to the same thing.

Facts are restricted to ones that do not drift. No ownership, no volumes, no
rankings by size; appellation rules, label mechanics, cellar practice, grape
identity and geography carry the weight instead.
"""

from lib import Q, SA

CAT = "Spain"
SLUG = "r2-spain"
PREFIX = "c"
RANK = "Rank II"
SOURCE = "data-questions.js"

SYLLABUS = [
    ("The categories and what they cost a producer", 3),
    ("Rioja: zones, villages and single vineyards", 5),
    ("The ageing words in cask and in bottle", 4),
    ("The Duero and its denominations", 5),
    ("Priorat and Catalunya", 3),
    ("Bierzo, Mencia and the Leon plateau", 2),
    ("Galicia's denominations and subzones", 4),
    ("Jerez: the solera and the flor", 4),
    ("Jerez: the marks, the age claims and en rama", 3),
    ("Cava: zones and ageing tiers", 2),
    ("Txakoli and the Basque coast", 2),
]

BANK = [
    # ------------------- The categories and what they cost a producer (3) -----
    Q("The categories and what they cost a producer",
      "Selling in bulk to a bottler outside the denomination keeps that wine out of Spain's highest tier for good. Which requirement shuts that door?",
      ["Wine at the qualified tier must be bottled inside the delimited zone",
       "Wine at the qualified tier may be sold only inside Spain",
       "Wine at the qualified tier must age two years before release",
       "Wine at the qualified tier must be pressed within a day of picking"], 0,
      "Bottling at origin is the point of the rung: once a tanker leaves the zone the regulating body has no way of knowing what reaches the glass, so the qualified tier simply refuses to let it go. Wine may still change hands in bulk between registered bodegas inside the boundary, which is how growers and cooperatives supply the ageing houses, but the last stop before the cork has to be a registered cellar in the zone. The condition falls hardest on houses whose business was built on selling wine by the litre to a bottler somewhere else, which is much of why so few denominations have ever applied."),
    Q("The categories and what they cost a producer",
      "A back label carries the mark of Grandes Pagos de Espana, and a guest reads it as a rank above DO. What is it really?",
      ["A private association of estates, admitted by its own members",
       "The top rung of the national quality ladder",
       "A denomination covering single estates in Castilla-La Mancha",
       "A seal issued by each denomination's regulating body after a compulsory tasting of every lot"], 0,
      "Nothing in Spanish wine law mentions it; the estates set their own standards and vote on who joins, which is a guild rather than a rank. It is worth knowing precisely because the wording sits so close to the legal single-estate category that a guest cannot be expected to tell them apart."),
    SA("The categories and what they cost a producer",
       "An estate already holding Spain's single-property denomination happens to lie inside the boundary of a qualified region, and its category picks up an extra word. Give the full name.",
       "Vino de Pago Calificado",
       ["vino de pago calificado", "pago calificado", "vinos de pago calificado",
        "denominacion de pago calificado", "vino de pago calificado dop",
        "denominacion de origen de pago calificado"],
       "The law provides for it directly: a pago sitting within a qualified denomination, and meeting that denomination's requirements as well as its own, takes the longer name. It is the only place in the Spanish system where two categories are stacked on one bottle, and there are barely a handful of estates it can apply to at all.",
       ex=True),

    # ------------------- Rioja: zones, villages and single vineyards (5) ------
    Q("Rioja: zones, villages and single vineyards",
      "Three new rungs went into Rioja's rulebook in 2017, ranking ground instead of counting months in cask. Which set of names is right?",
      ["Vino de Zona, Vino de Municipio and Vinedo Singular",
       "Vino de Paraje, Vino de Pueblo and Gran Vinedo",
       "Vino de Pago, Vino de Villa and Vina Clasificada",
       "Crianza de Zona, Reserva de Municipio and Vinedo Historico"], 0,
      "The ladder narrows from one of the three zones, to a named town, to a single plot, and it runs alongside the ageing words rather than replacing them, so a bottle can carry a village name and Reserva at once. It was a deliberate answer to the charge that Rioja ranked cellars and not vineyards, and it borrows its shape openly from Burgundy."),
    Q("Rioja: zones, villages and single vineyards",
      "A white Rioja lists Tempranillo Blanco on its back label, and the guest assumes a research station bred it. Where did the variety actually come from?",
      ["A single mutated shoot found on a Tempranillo vine in a Rioja vineyard",
       "A crossing of Tempranillo and Viura made at a Logrono research station",
       "An old white recovered from abandoned plots and identified by DNA",
       "A Bordeaux white brought south during the phylloxera years"], 0,
      "A grower found one arm of an ordinary black Tempranillo bearing white berries, and the shoot was propagated, tested and eventually written into the rulebook. Rioja authorised it in 2007 in a batch of nine varieties that took in Maturana Blanca and Turruntes alongside Chardonnay, Sauvignon Blanc and Verdejo, so the same reform bought native identity and international insurance at one stroke."),
    SA("Rioja: zones, villages and single vineyards",
       "Fruit off a young plot cannot go into Rioja's single-vineyard bottling however good the wine turns out. How old must the vines be?",
       "Thirty-five years",
       ["thirty five years", "35 years", "35", "thirty five",
        "at least thirty five years", "at least 35 years",
        "minimum thirty five years", "minimum 35 years",
        "thirty five years old", "35 years old", "at least 35 years old",
        "thirty five years of age", "vines of thirty five years",
        "the vines must be thirty five years old",
        "a minimum of thirty five years", "a minimum of 35 years",
        "at least thirty five years old", "minimum thirty five years old",
        "minimum 35 years old", "vines at least 35 years old",
        "vines at least thirty five years old", "a minimum of 35 years old",
        "a minimum of thirty five years old", "35 years or more",
        "thirty five years or more"],
       "The tier also demands hand harvesting, a yield well below the general limit, and a pass in two separate tastings before the back label is released. Age alone was never going to be enough on its own, because a mediocre old plot is easy to find, but it is the condition that cannot be met by simply farming better next year.",
       ex=True),
    SA("Rioja: zones, villages and single vineyards",
       "Rioja lets a label name a zone only when the fruit comes wholly from it, and the cellar steps must happen inside that same zone as well. Name the one that comes first.",
       "Vinification",
       ["vinification", "vinified", "winemaking", "fermentation", "fermented",
        "vinifying", "fermenting", "making the wine", "wine making",
        "vinification in the zone", "fermentation in the zone",
        "winemaking in the zone", "vinified in the zone", "fermented in the zone",
        "made in the zone", "vinified there", "fermented there", "made there",
        "the wine must be vinified there",
        "the wine must be vinified in the zone",
        "it must be vinified in the zone",
        "the wine has to be made in the zone",
        "the wine must be made in the zone",
        "it must be made in the zone", "must be made in the zone"],
       "A winery outside the boundary cannot print the zone even if every grape came from inside it, which stops a name being attached to fruit trucked anywhere convenient. Vinification is only the first step the rule catches, since the ageing and the bottling have to happen inside the zone as well. That is why the zone names took so long to appear on labels at all, plenty of established bodegas drawing fruit from more than one of the three.",
       ex=True),
    SA("Rioja: zones, villages and single vineyards",
       "Whole bunches go uncrushed into an open stone lagar in an Alavesa village, and the wine is sold off before the next vintage comes in. What is a wine made that way called?",
       "Cosechero",
       ["cosechero", "vino de cosechero", "cosecheros", "cosechero wine",
        "a cosechero from rioja alavesa"],
       "The bunches ferment under their own weight, partly inside the intact berries, and the wine goes into bottle purple, low in tannin and meant for the winter. It is the oldest commercial style in Rioja and it survived the whole barrel-ageing era in the villages, which is why it turns up in Alavesa bars and almost nowhere on an export list."),

    # ---------------------- The ageing words in cask and in bottle (4) --------
    Q("The ageing words in cask and in bottle",
      "A Spanish white has spent four years ageing, six months of that in barrel. Which of the ladder's words may the bodega print?",
      ["Gran Reserva",
       "Reserva, that word being the highest a white may reach",
       "Crianza, because only six of the forty-eight months were spent in wood",
       "None of them, the ladder having been written for red wine alone"], 0,
      "The white and rosado timetable is shorter than the red one at every rung, and its wood requirement is much lighter: four years in all with six months in cask carries the top word. A red asking for the same word needs five years, and far more of them in oak, which is why a white Gran Reserva costs a fraction of what its name suggests."),
    SA("The ageing words in cask and in bottle",
       "Spain's national rulebook asks a red Gran Reserva for sixty months of ageing in all, and fixes a floor for the share of it that must pass in oak. Give that floor.",
       "Eighteen months",
       ["eighteen months", "18 months", "18", "eighteen",
        "at least eighteen months", "at least 18 months",
        "minimum eighteen months", "minimum 18 months",
        "a minimum of eighteen months", "a minimum of 18 months",
        "eighteen months in oak", "18 months in oak",
        "eighteen months in cask", "18 months in cask",
        "eighteen months in barrel", "18 months in barrel",
        "at least eighteen months in oak", "at least 18 months in oak",
        "at least eighteen months in cask", "at least 18 months in cask",
        "eighteen months of oak", "18 months of oak", "a year and a half",
        "eighteen months or more", "18 months or more"],
       "Sixty months in all, at least eighteen of them in an oak cask, is the whole of what the national text asks of a red at the top rung. A denomination may set a harder rule for its own producers and the serious ones have, so the word compares cleanly only inside a single rulebook: two bottles both reading Gran Reserva can differ by a year or more of wood. What is being measured either way is elapsed time and nothing else, which is why the rung says nothing at all about where the fruit grew.",
       ex=True),
    SA("The ageing words in cask and in bottle",
       "Spain's ageing words name two places and no third, so a bodega that leaves its Reserva a year in stainless steel gains nothing by it. Which two places?",
       "In cask and in bottle",
       ["in cask and in bottle", "in cask and bottle", "cask and bottle",
        "in cask and in glass", "in cask and glass", "cask and glass",
        "in barrel and in bottle", "in barrel and bottle", "barrel and bottle",
        "in barrel and in glass", "in barrel and glass", "barrel and glass",
        "in oak and in bottle", "in oak and bottle", "oak and bottle",
        "in oak and in glass", "in oak and glass", "oak and glass",
        "in wood and in bottle", "in wood and bottle", "wood and bottle",
        "in wood and in glass", "in wood and glass", "wood and glass",
        "in bottle and in cask", "in bottle and cask", "bottle and cask",
        "in bottle and in barrel", "in bottle and barrel", "bottle and barrel",
        "in bottle and in oak", "in bottle and oak", "bottle and oak",
        "in bottle and in wood", "in bottle and wood", "bottle and wood",
        "in glass and in cask", "in glass and cask", "glass and cask",
        "in glass and in barrel", "in glass and barrel", "glass and barrel",
        "in glass and in oak", "in glass and oak", "glass and oak",
        "in glass and in wood", "in glass and wood", "glass and wood",
        "casks and bottles", "in casks and in bottles",
        "barrels and bottles", "in barrels and in bottles",
        "bottles and casks", "bottles and barrels",
        "both cask and bottle", "both barrel and bottle", "both oak and bottle",
        "ageing in cask and in bottle", "aging in cask and in bottle",
        "ageing in cask and bottle", "aging in cask and bottle",
        "cask and bottle ageing", "cask and bottle aging",
        "barrel and bottle ageing", "barrel and bottle aging",
        "cask and bottle only", "in cask and in bottle only",
        "cask and bottle time", "time in cask and bottle",
        "cask ageing and bottle ageing", "cask aging and bottle aging"],
       "Both clocks run at once inside a single total, so a rule reading thirty-six months with twelve in cask leaves the remainder to be served in glass. Steel is named nowhere in the definitions, so a bodega holding stock in tank earns neither cask time nor bottle time towards Reserva or Gran Reserva. Crianza is the one loose thread, its definition fixing the total and the cask floor but never saying where the balance must sit, so at that rung alone the months out of the barrel may pass in tank.",
       ex=True),
    SA("The ageing words in cask and in bottle",
       "Reserva asks less of a white than of a red, a full year less in fact. Give the white's total under the national rule.",
       "Twenty-four months",
       ["twenty four months", "24 months", "24", "twenty four", "two years",
        "at least twenty four months", "at least 24 months", "at least two years",
        "minimum twenty four months", "minimum 24 months", "minimum two years",
        "twenty four months in total", "24 months in total", "two years in total",
        "twenty four months of ageing", "24 months of ageing",
        "a minimum of twenty four months", "a minimum of 24 months",
        "a minimum of two years", "twenty four months total",
        "24 months total", "two years total"],
       "Twenty-four months for a white or rosado against thirty-six for a red, and the white needs only six of them in cask. The gap runs the whole length of the ladder, so every one of the three words means something different depending on the colour of what is in the bottle.",
       ex=True),

    # ------------------------- The Duero and its denominations (5) ------------
    Q("The Duero and its denominations",
      "Old plots around Toro carry untrellised bush vines set very wide apart and never watered. Which constraint dictated that layout?",
      ["The low rainfall, which leaves each vine a wide patch to itself",
       "A denomination rule capping the vines that may be registered on a hectare",
       "The shallow water table, which every root reaches within a metre of the surface",
       "The risk of spring frost, which settles more heavily in a trellised canopy"], 0,
      "Toro takes little more than a third of a metre of rain in a year, so the vineyard is spaced to the water rather than to the tractor. The same arithmetic explains the goblet: a low free-standing head shades its own fruit and needs no wire, posts and wire being an expense that pays only where there is enough water to grow a canopy worth training."),
    Q("The Duero and its denominations",
      "Pale rosado drawn from black and white grapes picked and fermented together made one Castilian denomination's name long before its reds did. Which one?",
      ["Cigales", "Arlanza", "Tierra de Leon", "Ribera del Duero"], 0,
      "The old field blend was co-fermented rather than blended afterwards, which gives a paler and more savoury wine than a modern rosado bled off a red vat. Cigales sits between Ribera del Duero and Toro on the Pisuerga, and its reds have only lately caught up with the pink wine that carried the name for centuries."),
    SA("The Duero and its denominations",
       "Putting Verdejo on a Rueda label commits a bodega to more of the grape than the denomination name alone does. Give the minimum a varietal label demands.",
       "Eighty-five percent Verdejo",
       ["eighty five percent verdejo", "85% verdejo", "85 percent verdejo",
        "eighty five percent", "85%", "85 percent", "85", "eighty five",
        "eighty five per cent", "85 per cent", "eighty five per cent verdejo",
        "85 per cent verdejo", "at least eighty five percent",
        "at least 85 percent", "at least 85%", "minimum 85%",
        "minimum eighty five percent", "at least eighty five percent verdejo",
        "at least 85% verdejo", "a minimum of 85 percent verdejo",
        "a minimum of eighty five percent verdejo", "a minimum of 85%",
        "a minimum of eighty five percent", "minimum eighty five percent verdejo",
        "minimum 85 percent verdejo", "85 percent of the blend"],
       "Plain Rueda needs half the blend to be Verdejo and the rest may be Viura or another permitted white; naming the grape lifts the floor. The same figure governs a Rueda labelled Sauvignon, so the two claims on a shelf are stronger than they look and the unnamed bottle is the one to ask about.",
       ex=True),
    SA("The Duero and its denominations",
       "White vines are scattered through the oldest Ribera del Duero plantings, and the denomination now authorises a white wine from the local one. Name that variety.",
       "Albillo Mayor",
       ["albillo mayor", "albillo", "albillo mayor grape",
        "the albillo mayor variety", "blanco albillo mayor"],
       "It was interplanted among the black vines for centuries and a little of it still finds its way into the reds, softening them without lifting the colour. Albillo Real, grown around Madrid, is a different variety altogether despite the shared first name, and the confusion is exactly why the rulebook spells out which Albillo it means.",
       ex=True),
    SA("The Duero and its denominations",
       "Downstream of Toro the Duero cuts a granite gorge along the Portuguese border, and the denomination there is built on Juan Garcia. Name it.",
       "Arribes",
       ["arribes", "do arribes", "arribes del duero", "the arribes denomination"],
       "The gorge shelters terraces that would be unworkable anywhere colder, and Juan Garcia gives a pale, high-toned red closer to a Galician wine than to anything in Castile. Port country begins a short way downstream, where the same gorge carries on into Portugal, so the hard rock and the vertiginous terracing are of a piece with what follows."),

    # --------------------------------- Priorat and Catalunya (3) --------------
    Q("Priorat and Catalunya",
      "Priorat built a ladder of its own climbing from village wine through a named site to a classified vineyard. What stands at the very top of it?",
      ["Gran Vinya Classificada", "Vinya Historica", "Paratge Qualificat",
       "Cru Superior"], 0,
      "The scheme ranks ground rather than producers. It is the paratge rung that the rulebook itself names and maps, several hundred of them alongside the named villages, while the two classified rungs above are awarded plot by plot on application, against a long record of single-vineyard bottling and a lasting hold on the land, which is why so few of them exist. Village wine asks that the fruit come wholly from the village named but does not oblige the bottler to have farmed it, so the estate condition belongs to the classified rungs rather than to the whole ladder."),
    SA("Priorat and Catalunya",
       "A downy-leaved mutation of Garnacha holds its acidity better in heat, and the Catalan rulebooks list it separately from its parent. What is it called?",
       "Garnatxa Peluda",
       ["garnatxa peluda", "garnacha peluda", "lledoner pelut", "hairy grenache",
        "garnatxa peluda hairy grenache"],
       "The underside of the leaf is felted with fine hairs, which is where the name comes from, and growers keep it on the hottest and stoniest parcels because it ripens more slowly than ordinary Garnacha. It is permitted across the Catalan denominations and is a fair share of the old-vine plantings a buyer is actually paying for when a label says Garnacha."),
    SA("Priorat and Catalunya",
       "In Alella, north of Barcelona, the local white goes by Pansa Blanca. Which widely planted Catalan variety is that?",
       "Xarel-lo",
       ["xarel lo", "xarello", "xarel lo pansa blanca", "pansa blanca xarel lo",
        "xarel lo grape", "the xarel lo variety", "xarel lo blanc",
        "xarel lo blanca", "xarel lo also called pansa blanca"],
       "One vine, two names, and the Alella version is the older of them. Xarel-lo is the most oxidation-resistant of the traditional Catalan whites, which is why it carries the body in a sparkling blend and why it is the one of them most often bottled on its own as a still wine. Watch the pink-skinned Xarel-lo Vermell, a separate variety that Alella calls Pansa Rosada, because the two Pansas are as easy to confuse as the two names of this one.",
       ex=True),

    # -------------------------- Bierzo, Mencia and the Leon plateau (2) -------
    Q("Bierzo, Mencia and the Leon plateau",
      "Growers took Bierzo's red for a relative of Cabernet Franc until DNA profiling settled the question. What did the profiling show?",
      ["It is the same variety as Portugal's Jaen",
       "It is a natural crossing of Tempranillo and Garnacha from the Middle Ages",
       "It is a colour mutation of Godello, the white grown on the same slopes",
       "It is identical to Galicia's Brancellao under a Leonese name"], 0,
      "The Cabernet Franc idea came from the perfume, all violet and graphite, rather than from anything in the vine, and it was repeated in print for decades. Jaen is grown in the Dao, across the mountains from Bierzo, and the match tells you the variety crossed the border long before anyone was recording what they planted."),
    SA("Bierzo, Mencia and the Leon plateau",
       "East on the Leon plateau a thick-skinned black grape gives deeply coloured rosados, made by dropping whole bunches into the fermenting must. Name the variety.",
       "Prieto Picudo",
       ["prieto picudo", "prieto picudo grape", "the prieto picudo variety",
        "prieto picudo tinto", "the black prieto picudo"],
       "The technique is called madreo, and the added bunches restart the ferment and raise a light prickle that the wine keeps into the bottle. The variety takes its name from its dark, pointed berries, its bunches are unusually compact, and it is grown seriously almost nowhere outside the province. A white mutation of it exists and is a different grape, so the rulebooks name the black one in full.",
       ex=True),

    # ------------------------ Galicia's denominations and subzones (4) --------
    Q("Galicia's denominations and subzones",
      "One Galician denomination lies inland against the Portuguese border in a sheltered valley, and it is the warmest and driest of the five. Which?",
      ["Monterrei", "Ribeiro", "Ribeira Sacra", "Rias Baixas"], 0,
      "The valley of the Tamega sits in a rain shadow, so Monterrei ripens Godello and Treixadura with far less anxiety about rot than the coast has. It is the least exported of the five and the one a Galician list is least likely to carry, which is exactly why it is worth asking about."),
    SA("Galicia's denominations and subzones",
       "Facing Portugal across the mouth of the Mino, one Rias Baixas subzone traditionally blends Loureira into its Albarino. Name the subzone.",
       "O Rosal",
       ["o rosal", "rosal", "the o rosal subzone", "el rosal"],
       "The blend gives a more floral and slightly softer wine than the pure Albarino of the northern subzones, and the terraces there run down to the river rather than to the open Atlantic. Condado do Tea, further upstream, is the warmest of the subzones and Val do Salnes on the coast is the coolest, so the appellation spans a real climatic range for so small a place."),
    SA("Galicia's denominations and subzones",
       "Inland along the Avia and the Mino, the Ribeiro leans on a later-ripening native that gives more flesh and less bite than Albarino. Name it.",
       "Treixadura",
       ["treixadura", "trajadura", "treixadura grape", "the treixadura variety"],
       "It buds and ripens late, needs a warmer inland site than the coast can offer, and gives a broader wine usually blended with Godello, Loureira or Torrontes. In northern Portugal the same vine is Trajadura and goes into Vinho Verde for exactly the same reason: weight."),
    SA("Galicia's denominations and subzones",
       "Printing Albarino on the front of a Rias Baixas bottle triggers a stricter rule than leaving it off. How much of the grape must the wine then hold?",
       "One hundred percent Albarino",
       ["one hundred percent albarino", "100% albarino", "100 percent albarino",
        "one hundred percent", "100%", "100 percent", "100", "all of it",
        "one hundred per cent", "100 per cent", "one hundred per cent albarino",
        "100 per cent albarino", "entirely albarino", "wholly albarino",
        "all albarino", "it must be entirely albarino",
        "it must be 100% albarino", "it must be 100 percent albarino",
        "it must be one hundred percent albarino", "it has to be 100% albarino",
        "a minimum of 100 percent albarino"],
       "Nothing else may be in the blend, which is a stricter varietal rule than most of Europe uses and is why the name on the front is worth reading. A Rias Baixas without the grape name may perfectly well be a blend with Loureira, Caino Blanco or Treixadura, and in the southern subzones it usually is.",
       ex=True),

    # ------------------------------ Jerez: the solera and the flor (4) --------
    Q("Jerez: the solera and the flor",
      "A butt fortified past a certain strength loses its veil of flor for good and turns oxidative. Roughly where does that line fall?",
      ["Around 15.5 percent",
       "Around 12 percent, which is the strength of the unfortified base wine",
       "Around 18 percent",
       "Around 22 percent"], 0,
      "The yeast that forms the veil stops working somewhere close to fifteen and a half, so a cellar master fortifies to just under that line to keep a wine biological and to just over it to kill the flor deliberately. That single decision, taken on a young wine, is what separates the whole Fino family from the whole Oloroso family."),
    SA("Jerez: the solera and the flor",
       "Wine drawn off the solera row is topped back up from the criadera above it, in an operation the bodegas name after dew. Give that term.",
       "Rocio",
       ["rocio", "el rocio", "rocio refill", "rociar"],
       "The word is literal: the younger wine is introduced gently, down the wall of the butt or through a tube, so the veil floating on the surface is not torn. Tearing it would let oxygen at the wine underneath, which is the one thing a biological cellar exists to prevent, and it is why the refill is a slow job rather than a pour."),
    SA("Jerez: the solera and the flor",
       "A cellar hand lifts a sample from beneath the veil without tearing it, using a narrow cup on a long whippy handle. Name the tool.",
       "Venencia",
       ["venencia", "venencia cup", "silver venencia", "sherry venencia",
        "jerez venencia"],
       "The Jerez form is a silver cup on a whalebone or cane rod, long enough to reach the bottom of a butt through the bunghole; Sanlucar uses a lighter one cut from a single piece of cane. The person wielding it is the venenciador, and pours from arm's height into a glass held at the waist, which aerates the wine and is a good deal harder than it looks.",
       ex=True),
    SA("Jerez: the solera and the flor",
       "One outstanding harvest is set aside and aged in its own casks, never refreshed from a younger scale. What is a Sherry made that way called?",
       "Anada",
       ["anada", "vino de anada", "anada sherry", "an anada wine",
        "vintage sherry", "anada wines", "anadas"],
       "It carries a year on the label, which almost nothing else in Jerez does, because a solera has no vintage to declare. The wines were traditionally kept in the coolest corner of the bodega and drawn on to correct a solera in a difficult year, so bottling one at all is a modern decision rather than an old tradition.",
       ex=True),

    # ----------------- Jerez: the marks, the age claims and en rama (3) -------
    Q("Jerez: the marks, the age claims and en rama",
      "A Fino goes into bottle with little more than a coarse filter, released in small lots in spring and again in autumn. What has the guest gained, and lost?",
      ["More of the veil's yeasty, saline intensity, and much less time before the bottle tires",
       "A higher strength, the wine having been fortified a second time on its way into the bottle",
       "Residual sweetness, some of the sugar having been left unfermented",
       "A deeper colour and walnut character, the wine having oxidised for years after its flor died"], 0,
      "Cold stabilisation and tight filtration strip fine solids that carry aroma, so leaving them in gives a fuller and more savoury wine that is also markedly less stable. The release dates are not marketing: the veil is thickest in spring and autumn and thinnest in the heat of August, so the wine underneath is genuinely different at different times of year."),
    SA("Jerez: the marks, the age claims and en rama",
       "At the first classification the capataz chalks a mark on the butt, and one mark sends the young wine down the biological road. Name that mark.",
       "Palma",
       ["palma", "una palma", "the palma mark"],
       "A stroke like a palm frond says the wine is delicate and clean and will be lightly fortified to keep its veil alive. A raya, a plain horizontal bar, sends a fuller wine the oxidative way, and the crossed mark that gives Palo Cortado its name is a palma struck through, meaning the cellar master changed his mind about it.",
       ex=True),
    SA("Jerez: the marks, the age claims and en rama",
       "Before the letters VORS may go on a label the regulating body verifies the claimed average age in a laboratory rather than from the cellar book. Which test does it use?",
       "Carbon dating",
       ["carbon dating", "carbon 14 dating", "radiocarbon dating", "carbon 14",
        "c14 dating", "radiocarbon analysis", "carbon dating of the wine"],
       "Atmospheric nuclear testing left a spike of radiocarbon in everything grown since the 1950s, and the amount left in a wine gives its age directly, which no ledger could prove for a blend that has never been a single vintage. VOS claims an average of twenty years and VORS thirty, and both are checked this way before the seal is granted."),

    # ------------------------------ Cava: zones and ageing tiers (2) ----------
    Q("Cava: zones and ageing tiers",
      "Zoning came to Cava so that a label could finally say where the fruit grew rather than only how the wine was made. Which is a genuine Cava zone?",
      ["Comtats de Barcelona", "Camp de Tarragona", "Ribera del Cava",
       "Alt Penedes"], 0,
      "The denomination was drawn around a production method and a register of approved plots rather than around a boundary, which is how it came to stretch across half the country, and the zones answer the old complaint that followed from it. A buyer can now tell an Ebro valley bottle from a Catalan one, and a zone may be subdivided further so a district can be named as well."),
    SA("Cava: zones and ageing tiers",
       "Cava's ageing tiers were sorted into two families, the upper one vintage-dated and starting at eighteen months on the lees. Name that upper family.",
       "Cava de Guarda Superior",
       ["cava de guarda superior", "guarda superior",
        "the guarda superior tier", "guarda superior cava"],
       "Reserva, Gran Reserva and the single-plot tier all sit inside it, and every wine in the family must declare its harvest year, which the entry tier below need not. Because the family carries the vintage, a bottle without one is telling a buyer where it sits without ever printing the word.",
       ex=True),

    # ------------------------------ Txakoli and the Basque coast (2) ----------
    SA("Txakoli and the Basque coast",
       "The oldest Basque txakoli denomination is named for a fishing town on the Gipuzkoa coast. Name that denomination.",
       "Getariako Txakolina",
       ["getariako txakolina", "getaria", "txakoli de getaria",
        "chacoli de getaria", "getariako txakolina do",
        "do getariako txakolina", "getaria txakolina",
        "txakolina de getaria", "getariako"],
       "Recognised at the end of the 1980s, it covers the steep coastal slopes either side of the town and is the most maritime of the three Basque denominations. The others cover Bizkaia around Bilbao and Araba inland in the Ayala valley, sheltered behind the Sierra Salvada but still on the Atlantic side of the watershed, where the wines are riper and a good deal less salty.",
       ex=True),
    SA("Txakoli and the Basque coast",
       "Txakoli is nearly all white, yet the Basque rulebooks also list a black-berried variety for the rare reds and rosados. Name it.",
       "Hondarrabi Beltza",
       ["hondarrabi beltza", "hondarribi beltza", "ondarrabi beltza",
        "hondarrabi beltza grape", "hondarrabi beltz"],
       "Beltza is Basque for black, and the grape is a small share of the plantings; a little is co-fermented with the white in some villages to give the pink wine its colour. Both varieties trail their canopies on high pergolas above the damp ground, which is the same answer to the same problem the Galicians reached on the other end of the same coast.",
       ex=True),
]
