"""Rank II rewrite - Spirits & Cocktails (54 questions: 15 MC, 39 short answer).

Certified level, pitched deliberately above the Rank I "Sake & Spirits" category
and written so that nothing repeats a Rank I task. Where Rank I asks which agave
species tequila may use, this asks what the NOM number on the bottle identifies;
where Rank I asks what the discarded fractions of a still run are called, this
asks what happens to them afterwards. The reader is running a whole beverage
programme, so the weight sits on legal definitions, ageing minima and the builds
a bar actually works to.

Written from the syllabus below. The imported bank was not read while writing;
it is read only afterwards by check-similarity.py.

Accept lists are built against lib.match_sa, a port of core.js matchSA, and every
one was executed against adversarial input rather than eyeballed. No '~' entries
appear anywhere: the tilde is exact-OR-containment, so a one-word tilde grades
any wrong answer that happens to carry that word.

Eleven answers carry ex=True, every one of them because a REAL and DIFFERENT
thing extends or contains the right answer, which no mechanical check catches:
"non chill filtered" is the opposite of chill filtration; "straight corn whiskey"
is a separate legal category from corn whiskey; "less than twenty percent",
"less than 96 percent", "less than two years" and "below 14.5 percent" all
invert their own answers; "57 proof" is a wholly different strength from 57
percent, and it is the confusion that question exists to expose; a "bonded
warehouse" is the building rather than the label that names it; "chlorophenols"
and "polyphenols" are different compound families from phenols; "Campbell" is
not Campbeltown; and demerara sugar is not the Demerara river. Each of the
eleven was then widened until the natural phrasings of its own answer grade
again, because ex=True on its own turns a grading contract into a spelling test.

Facts are restricted to ones that do not drift. No ownership, no production
volumes, no "currently the largest": legal minima, geography, chemistry and the
dates written into regulation carry the weight instead.
"""

from lib import Q, SA

CAT = "Spirits & Cocktails"
SLUG = "r2-spirits-cocktails"
PREFIX = "c"
RANK = "Rank II"
SOURCE = "data-questions.js"

SYLLABUS = [
    ("Distillation and proof", 6),
    ("Scotch whisky", 7),
    ("Irish and American whiskey", 6),
    ("Cognac, Armagnac and other brandies", 6),
    ("Rum and cane spirits", 5),
    ("Agave spirits", 6),
    ("Gin, vodka and aniseed spirits", 6),
    ("Vermouth, amari and aperitifs", 6),
    ("Classic cocktail families", 6),
]

BANK = [
    # -------------------------------------------- Distillation and proof (6) --
    Q("Distillation and proof",
      "A tall swan neck with a bulge at its base sends much of the rising vapour back down into the pot before it ever reaches the condenser. What does that do to the spirit?",
      ["Lightens it, because the heavier compounds fall back and are redistilled",
       "Darkens it, because copper is stripped from the neck into the vapour",
       "Raises its congener load, because the vapour condenses twice over",
       "Lowers its strength, because alcohol condenses before water does"], 0,
      "The effect is called reflux, and it is why a tall narrow still gives a more delicate spirit than a short fat one of the same capacity. Contact with copper rises along with it, which strips sulphur compounds out of the vapour as a bonus."),
    Q("Distillation and proof",
      "Two linked columns, an analyser fed with wash and a rectifier that returns its condensate to be stripped again, let one apparatus run without ever being emptied. Whose patent of 1830 was that?",
      ["Aeneas Coffey", "Robert Stein", "Edouard Adam", "Eugene Charmat"], 0,
      "Coffey's design is the ancestor of every continuous still working today, and grain whisky, most vodka and most rum all pass through one. Stein's earlier continuous still was superseded within a couple of years, Adam is remembered for condensing apparatus, and Charmat's name belongs to sparkling wine rather than to spirits."),
    SA("Distillation and proof",
       "Neither the first nor the last part of a pot still run is thrown away; what is held back goes into the charge for the following run. What is that returned material called?",
       "Feints",
       ["feints", "feints and foreshots", "foreshots and feints",
        "feints returned to the still", "heads and tails", "foreshots and tails"],
       "They are rich in the heavy oily compounds the stillman rejected, and redistilling them recovers the alcohol without letting those compounds into the hearts. A still house wastes very little: even the spent wash goes to cattle feed."),
    SA("Distillation and proof",
       "European law stops calling a distillate a spirit drink of its raw material, and calls it ethyl alcohol of agricultural origin instead, once it passes a fixed strength. What strength is that?",
       "96 percent",
       ["96 percent", "96%", "96 per cent", "ninety six percent", "96 percent abv",
        "96 abv", "96 percent alcohol", "96 percent alcohol by volume",
        "at least 96 percent", "96 percent or above", "96", "96% abv", "96% vol",
        "96 percent vol", "96 percent or more", "above 96 percent", "over 96 percent"],
       "Above that point the distillate has lost the fingerprint of whatever it was made from, which is why vodka can come from grain, potato or grape and taste of none of them. Whisky rules run the other way and cap distillation below 94.8 percent so the cereal survives into the glass.",
       ex=True),
    SA("Distillation and proof",
       "A malt bottled at 43 percent turns cloudy the moment a guest adds a splash of water. Which treatment would have prevented that haze, and is often left out on purpose?",
       "Chill filtration",
       ["chill filtration", "chill filtering", "chill filtered", "chillfiltering",
        "chillfiltration", "chillfiltered", "chill filter", "cold filtration",
        "cold filtering", "cold filtered", "chill filtration before bottling",
        "chill filtration at bottling", "chill filtering before bottling"],
       "Long-chain fatty esters drop out of solution when a spirit is chilled or watered below about 46 percent, which is a cosmetic problem and nothing more. Filtering them out at low temperature removes the haze and, many argue, some texture with it, so bottlings at 46 percent and above frequently skip it.",
       ex=True),
    SA("Distillation and proof",
       "Wash at around eight percent alcohol goes into the wash still and comes off cloudy at roughly twenty-one percent, ready for a further pass. What is that first distillate called?",
       "Low wines",
       ["low wines", "low wine", "low wines from the wash still"],
       "Only the second run is cut into heads, hearts and tails; the first is collected whole because there is nothing yet worth separating. Irish pot still whiskey adds a third pass, which is where much of its lighter texture comes from."),

    # --------------------------------------------------------- Scotch whisky (7)
    Q("Scotch whisky",
      "A label reads blended malt Scotch whisky and names no distillery anywhere on it. What is in the bottle?",
      ["Malt whiskies from more than one distillery, with no grain whisky at all",
       "Malt and grain whisky drawn from one distillery",
       "Malt whisky from one distillery, married from several casks",
       "Grain whiskies from several distilleries with a little malt added"], 0,
      "The category was called vatted malt until the Scotch Whisky Regulations settled the naming in 2009. Blended Scotch is the different animal: malt whisky married with grain whisky from a column still, which is what the great majority of Scotch sold in the world is."),
    Q("Scotch whisky",
      "Five whisky localities and regions are protected under the Scotch Whisky Regulations, and one of them is a single island rather than a stretch of the mainland. Which?",
      ["Islay", "Orkney", "Skye", "Jura"], 0,
      "The regulations protect five: Highland, Lowland, Speyside, Campbeltown and Islay. Orkney, Skye, Jura, Mull and Arran all distil, but they sit inside the Highland region rather than standing on their own."),
    SA("Scotch whisky",
       "Thirty distilleries once crowded a single harbour town on the Kintyre peninsula, and its name survives as one of Scotland's protected whisky regions. Name the town.",
       "Campbeltown",
       ["campbeltown", "campbelltown", "campbeltown on kintyre", "campbeltown kintyre",
        "campbeltown scotland", "the town of campbeltown"],
       "The town collapsed as a whisky centre in the 1920s and ran for decades on a couple of working distilleries, but the region was never struck off. What survived there also kept practices that vanished elsewhere, floor malting among them.",
       ex=True),
    SA("Scotch whisky",
       "Dufftown, Rothes and Craigellachie all sit inside the same protected Scotch whisky region, clustered around one river valley. Name the region.",
       "Speyside",
       ["speyside", "speyside region", "spey valley"],
       "The Spey and its tributaries drain the whole zone, and those towns are its distilling centres. A Speyside whisky may also be labelled Highland, since the zone sits geographically inside the Highland region, but the reverse is not permitted."),
    SA("Scotch whisky",
       "Peating is quoted in parts per million measured on the malt, and the figure counts one family of compounds picked up from the kiln smoke. Name that family.",
       "Phenols",
       ["phenols", "phenol", "phenolic compounds", "phenolics", "total phenols",
        "phenol compounds"],
       "A good deal of the phenol is lost through fermentation and distillation, so the number on a bag of malt overstates what reaches the glass by a wide margin. Guaiacol and the cresols sit within that family and carry the tar, smoke and iodine notes.",
       ex=True),
    SA("Scotch whisky",
       "Oak is not the only cask requirement in the Scotch rules, which also set a limit on the size of the vessel. What is that maximum?",
       "700 litres",
       ["700 litres", "700 liters", "seven hundred litres", "700 litre", "700 litre casks",
        "a maximum of 700 litres", "700 litre maximum", "not exceeding 700 litres",
        "no more than 700 litres", "up to 700 litres", "maximum 700 litres",
        "700", "seven hundred", "700 l"],
       "Anything larger falls outside the definition, which rules out the great vats used elsewhere for solera-style ageing. Inside the limit the range is wide, from the 200 litre ex-bourbon barrel through the 250 litre hogshead to the 500 litre sherry butt.",
       ex=True),
    SA("Scotch whisky",
       "Colour is the one adjustment a Scotch producer may still make in the vat, and a single additive is permitted for it. Name that additive.",
       "Spirit caramel",
       ["spirit caramel", "caramel", "plain caramel", "e150a", "caramel colouring"],
       "Water and spirit caramel are the only permitted additions after maturation, so a Scotch cannot be sweetened or flavoured the way some other categories legally can. The caramel exists to make batches look alike rather than to add taste, though whether it is genuinely tasteless is argued about at length."),

    # -------------------------------------------- Irish and American whiskey (6)
    Q("Irish and American whiskey",
      "Unmalted barley entered the Irish mash bill in the eighteenth century for a reason that had nothing to do with flavour. What drove it?",
      ["A duty levied on malted grain", "A shortage of peat for kilning",
       "An excise ban on triple distillation", "A rule requiring imported corn"], 0,
      "The tax was charged on malt, so distillers cut the mash with raw barley and lowered the bill. What began as tax avoidance became the defining texture of Irish single pot still whiskey, which is creamy and spiced in a way an all-malt mash is not."),
    Q("Irish and American whiskey",
      "American regulations cap the strength at which bourbon may come off the still, and again the strength at which it may go into the barrel. Which pair of figures is correct?",
      ["160 proof off the still and 125 proof into the barrel",
       "190 proof off the still and 160 proof into the barrel",
       "140 proof off the still and 110 proof into the barrel",
       "125 proof off the still and 160 proof into the barrel"], 0,
      "That is 80 percent alcohol off the still and 62.5 percent into the wood, with a bottling floor of 80 proof. Entry strength matters because a lower one pulls different compounds out of the oak, which is why some distillers barrel well under the ceiling."),
    SA("Irish and American whiskey",
       "The word straight on an American whiskey label carries an ageing requirement that plain bourbon does not have to meet. How long?",
       "Two years",
       ["two years", "2 years", "two years in oak", "at least two years",
        "two years minimum", "minimum two years", "24 months", "two years old",
        "two years in wood", "two years in barrel", "two years in new charred oak"],
       "Two years in new charred oak, with corn whiskey the single exception, and if a straight whiskey is younger than four years the label has to state its age. Bourbon itself has no ageing minimum at all, so a spirit is legally bourbon the moment it goes into the barrel.",
       ex=True),
    SA("Irish and American whiskey",
       "One American designation demands a single distilling season at one distillery, four years in a federally supervised warehouse, and bottling at exactly 100 proof. Name it.",
       "Bottled in Bond",
       ["bottled in bond", "bonded", "bond", "bottled in bond whiskey",
        "bonded whiskey", "bottled in bond bourbon", "bonded bourbon",
        "bottled in bond act"],
       "The Bottled-in-Bond Act of 1897 was a consumer protection measure at a time when whiskey was routinely adulterated, and the government put its own supervision behind the label. It is why so many bonded bottlings sit at exactly fifty percent alcohol.",
       ex=True),
    SA("Irish and American whiskey",
       "A bottle sold as American blended whiskey may be mostly neutral spirit, but a floor is set for the real whiskey in it. What is that floor?",
       "Twenty percent",
       ["twenty percent", "20 percent", "20%", "twenty per cent", "20 per cent",
        "at least twenty percent", "at least 20 percent", "a fifth", "one fifth",
        "twenty percent straight whiskey", "20 percent straight whiskey", "20",
        "twenty", "20% straight whiskey", "20 per cent straight whiskey",
        "20 percent whiskey", "at least a fifth", "one fifth straight whiskey"],
       "The remaining four fifths may be grain neutral spirit, which is why the category sits well below straight whiskey in both price and character. Canadian blends answer to a different rule and Scotch blends to another again, so the word blended means something different in each country.",
       ex=True),
    SA("Irish and American whiskey",
       "An American spirit built on a mash of at least eighty percent corn may be sold with no wood ageing at all, and if it is aged the barrel must be used or uncharred. Name that category.",
       "Corn whiskey",
       ["corn whiskey", "corn whisky", "american corn whiskey", "corn whiskey category"],
       "The uncharred or used barrel is the whole point: new charred oak is what makes bourbon, so this category is deliberately kept away from it and stays close to its raw distillate. Most of it is sold white, and it is the legal descendant of American moonshine.",
       ex=True),

    # ----------------------------------- Cognac, Armagnac and other brandies (6)
    Q("Cognac, Armagnac and other brandies",
      "A tier was added to the Cognac ladder in 2018, sitting above XO and carrying a fourteen-year floor. What is it called?",
      ["XXO", "Napoleon", "Hors d'Age", "Fine Champagne"], 0,
      "The same reform lifted XO itself from six years to ten, which left Napoleon standing on the six-year step XO had vacated. Hors d'Age is treated as equal to XO rather than as a step of its own, so it takes the same ten-year floor, and Fine Champagne describes the crus blended rather than any age at all."),
    Q("Cognac, Armagnac and other brandies",
      "Four grapes carry the Armagnac plantings, and one of them is a hybrid, the only such vine allowed in a French appellation spirit. Which?",
      ["Baco Blanc", "Folle Blanche", "Colombard", "Ugni Blanc"], 0,
      "Baco Blanc, also called Baco 22A, crosses Folle Blanche with an American vine and was bred after phylloxera to work the sandy soils of Bas-Armagnac. It was due to be swept away by the EU ban on hybrid vines and was kept for Armagnac alone."),
    SA("Cognac, Armagnac and other brandies",
       "Gascony gained an appellation in 2005 for a spirit that reaches the bottle clear, having never touched wood. Name it.",
       "Blanche Armagnac",
       ["blanche armagnac", "armagnac blanche", "blanche d'armagnac", "white armagnac"],
       "It rests in glass or stainless steel for at least three months and is bottled at forty percent or more, which puts a purely aromatic distillate on the table. Served very cold it does the work of a good eau-de-vie or a white rum, and it turns up in cocktails for the same reason."),
    SA("Cognac, Armagnac and other brandies",
       "Cognac's official ageing count begins not on the day the spirit leaves the still but on a fixed date afterwards. Which date?",
       "The first of April",
       ["1 april", "april 1", "first of april", "april first", "1st april",
        "april 1st", "1st of april"],
       "The compte runs from the first of April following the harvest, so an eau-de-vie distilled in February sits at compte 00 until then, becomes compte 0 on that date and reaches compte 1 a year later. Distillation itself has to be finished by the thirty-first of March, which is what fixes the date."),
    SA("Cognac, Armagnac and other brandies",
       "Pears are not a rounding-off in one Calvados appellation but a legal requirement, at a minimum of thirty percent. Name that appellation.",
       "Domfrontais",
       ["domfrontais", "calvados domfrontais", "domfrontais calvados", "pays de domfront"],
       "The bocage around Domfront is pear country, and perry pear trees take far longer to come into bearing than apples do. The appellation also insists on a single distillation in a column still, the opposite of the double pot distillation required in the Pays d'Auge."),
    SA("Cognac, Armagnac and other brandies",
       "Clay and flint left by decomposed limestone give one compact Cognac cru a violet-scented spirit that comes round faster than the chalk crus do. Name that cru.",
       "Borderies",
       ["borderies", "les borderies", "borderies cru"],
       "It is the smallest of the six crus and sits just north of the town of Cognac itself. Grande and Petite Champagne are chalkier and much slower, while Fins Bois, Bons Bois and Bois Ordinaires ring the region and give quicker-maturing spirit still."),

    # ------------------------------------------------- Rum and cane spirits (5)
    Q("Rum and cane spirits",
      "Jamaican pot still rum is bought and sold on a figure given in grams per hectolitre of pure alcohol, and the heaviest marks smell of overripe banana and glue. What is being counted?",
      ["Esters", "Phenols", "Aldehydes", "Fusel oils"], 0,
      "Counts run from around 100 up to a legal ceiling of 1600 grams per hectolitre in the heaviest continental flavoured marks, which are blended in tiny proportions rather than drunk neat. Long, deliberately wild fermentations are what build them."),
    SA("Rum and cane spirits",
       "The acidic liquid left in the still after a Jamaican distillation is not discarded but returned to the next fermentation to build pungency. What is that liquid called?",
       "Dunder",
       ["dunder", "dunder pit", "dunder from the still"],
       "It works like a sourdough starter, held in pits and topped up rather than made fresh each time. Together with muck, a rotting mass of cane trash and acid, it drives the ester counts that define the heavy Jamaican marks."),
    SA("Rum and cane spirits",
       "Wooden pot and Coffey stills, some of them well over a century old, still work on one river in Guyana, and the rums made on them carry that river's name. Name it.",
       "Demerara",
       ["demerara", "demerara river", "river demerara", "demerara rum",
        "demerara in guyana", "demerara guyana"],
       "The wooden stills survived because their staves are credited with a character no metal still reproduces, so they were moved rather than scrapped as distilleries closed. The rums are dark, heavy and smoky, and were the backbone of the Royal Navy blend.",
       ex=True),
    SA("Rum and cane spirits",
       "Brazilian law sets a minimum bottling strength for cachaca lower than the forty percent the United States demands of rum. What is it?",
       "Thirty-eight percent",
       ["38 percent", "thirty eight percent", "38%", "38 per cent",
        "thirty eight per cent", "38 percent abv", "38 abv", "thirty eight", "38",
        "38 percent alcohol"],
       "Cachaca runs from thirty-eight to forty-eight percent and may not be distilled above fifty-four, while rum has to reach forty percent in the United States and 37.5 in the European Union. Up to six grams of sugar per litre is permitted before the drink has to be relabelled as adocada, sweetened.",
       ex=True),
    SA("Rum and cane spirits",
       "Ships' pursers proved the strength of the rum ration by wetting gunpowder with it and setting light to the result. Which alcoholic strength does that test correspond to?",
       "Fifty-seven percent",
       ["57 percent", "fifty seven percent", "57%", "57 per cent", "about 57 percent",
        "57", "57 abv", "57 percent abv", "fifty seven per cent",
        "57 percent alcohol", "57.15 percent", "57 percent alcohol by volume"],
       "Gunpowder will still flash when wetted with spirit at about fifty-seven percent and will not below it, which is where navy strength and the old 100 degrees British proof both come from. It is why a navy strength gin is bottled at 57 rather than at a round number.",
       ex=True),

    # ---------------------------------------------------------- Agave spirits (6)
    Q("Agave spirits",
      "Every bottle of Tequila carries the letters NOM followed by a four-figure number. What does that number identify?",
      ["The distillery that made it, as registered with the regulator",
       "The field the agave was cut from",
       "The year the agave was harvested",
       "The number of times the spirit was distilled"], 0,
      "One NOM can cover many brands, since a single distillery may produce for dozens of labels, so two bottles with different names and the same NOM came off the same equipment. It is the quickest way for a buyer to see who actually made a spirit."),
    Q("Agave spirits",
      "A Tequila label says nothing about being one hundred percent agave. Where may the rest of its fermentable sugar come from?",
      ["Up to forty-nine percent from other sugars, usually cane",
       "Up to twenty-five percent from other sugars, usually cane",
       "Up to forty-nine percent from other agave species",
       "Up to fifteen percent from grape must"], 0,
      "That style is known as mixto, though the word never appears on a label and the absence of the hundred percent claim is the only signal. The other sugar is fermented alongside the agave rather than blended in afterwards."),
    SA("Agave spirits",
       "A great wheel of volcanic stone is dragged around a circular pit to crush cooked agave in the traditional way. What is that wheel called?",
       "Tahona",
       ["tahona", "tahona wheel", "tahona stone"],
       "The stone crushes rather than shreds, so fibre and juice ferment together and the spirit comes out rounder and more vegetal. A roller mill does the same job in an hour instead of a day, which is why the old method survives only where a producer chooses to pay for it."),
    SA("Agave spirits",
       "A small wild agave that grows in shade beneath oaks, yields very little sugar and cannot be farmed in rows makes some of the most expensive mezcal. Name it.",
       "Tobala",
       ["tobala", "agave tobala", "tobala agave"],
       "It grows from seed rather than from the pups that propagate espadin, so every plant harvested is one fewer in the wild. A dozen years or more in the ground yields a fraction of the sugar of a cultivated agave, and the price follows."),
    SA("Agave spirits",
       "Mezcal's rules recognise a ladder of production classes, and the strictest bars mechanical shredding altogether and demands a clay pot still. Name that class.",
       "Ancestral",
       ["ancestral", "mezcal ancestral", "ancestral mezcal", "ancestral category"],
       "Mezcal artesanal sits a step below and allows a copper pot still and mechanical shredding, while plain Mezcal permits column stills, autoclaves and diffusers. The word describes method rather than quality, though in practice the two tend to travel together."),
    SA("Agave spirits",
       "Sonora makes an agave spirit with a Mexican denomination of its own, so it may not be sold as mezcal however it is made. Name it.",
       "Bacanora",
       ["bacanora", "bacanora from sonora", "sonoran bacanora"],
       "It is distilled from Agave angustifolia, the same species as espadin, and was outlawed in Mexico for most of the twentieth century. Raicilla in Jalisco and sotol in Chihuahua sit outside the mezcal denomination too, and sotol is not made from agave at all."),

    # ------------------------------------------ Gin, vodka and aniseed spirits (6)
    Q("Gin, vodka and aniseed spirits",
      "Botanicals are steeped in neutral spirit and the result is bottled without going near a still again. Which category does that gin fall into?",
      ["Compound gin", "Distilled gin", "London Dry gin", "Genever"], 0,
      "Compound gin is perfectly legal and is what bathtub gin always was, but it may not call itself distilled gin. Distilled gin has to be redistilled in the presence of its botanicals, and London Dry adds that nothing beyond water and a trace of sugar may go in afterwards."),
    Q("Gin, vodka and aniseed spirits",
      "European rules put a floor under the bottling strength of vodka. Where does it sit?",
      ["37.5 percent", "40 percent", "32 percent", "43 percent"], 0,
      "The United States sets its floor at forty percent, which is why some vodkas are bottled differently for each market. European rules also make a vodka distilled from anything other than cereals or potatoes name its raw material on the label."),
    SA("Gin, vodka and aniseed spirits",
       "A juniper-flavoured spirit from the Low Countries is built on a distillate of malted grain, and is sold as jonge or oude according to how much of that distillate it carries. Name it.",
       "Genever",
       ["genever", "jenever", "dutch genever", "genever gin"],
       "Oude and jonge describe style rather than age, and the malt wine base is what makes the spirit read closer to a light whisky than to a London Dry. Its protected geographical indication covers the Netherlands, Belgium and small parts of France and Germany."),
    SA("Gin, vodka and aniseed spirits",
       "After juniper, one seed appears in more gin recipes than any other, bringing lemon peel and a sage-like warmth with it. Name it.",
       "Coriander",
       ["coriander", "coriander seed", "coriander seeds", "coriandrum sativum"],
       "The seed is rich in linalool, which reads as citrus and lavender and dovetails with the pine and pepper of juniper rather than sitting beside it. Angelica root is the third of the standard trio and works as a fixative, binding the lighter aromatics together."),
    SA("Gin, vodka and aniseed spirits",
       "Absinthe's early twentieth-century ban was blamed on a compound in wormwood that was later shown to be present in only tiny amounts. Name that compound.",
       "Thujone",
       ["thujone", "alpha thujone", "thujone from wormwood"],
       "Analysis of surviving pre-ban bottles found it at levels far too low to cause the effects laid at its door; strength, cheap adulteration and simple volume explain the rest. European law now caps it in bitter spirits at thirty-five milligrams per litre, which most absinthe never approached anyway."),
    SA("Gin, vodka and aniseed spirits",
       "A French aperitif takes its anise character mainly from star anise and liquorice rather than from wormwood, and is poured one part to five of water. Name it.",
       "Pastis",
       ["pastis", "pastis de marseille", "french pastis"],
       "It appeared after absinthe was banned and stayed on after absinthe returned, because it is a different drink rather than a substitute. Liquorice supplies most of the sweetness, and at forty percent and above it is the water that turns it into a long aperitif rather than a shot."),

    # --------------------------------------------- Vermouth, amari and aperitifs (6)
    Q("Vermouth, amari and aperitifs",
      "A bottle of sweet vermouth has stood open on the back bar since the spring. What has happened to it, and what should have been done?",
      ["It has oxidised, and an open bottle belongs in the refrigerator for a few weeks at most",
       "Nothing at all, since fortification keeps an open bottle stable for a year on the bar",
       "It has refermented, and an open bottle should be kept sealed and warm to prevent that",
       "It has thrown a deposit, and an open bottle should be decanted before it goes cloudy"], 0,
      "Vermouth is wine at around sixteen percent, well short of a Port's nineteen to twenty-two, and no amount of sugar keeps air out of an opened bottle, so it browns and flattens like any other wine. A Martini built on tired vermouth is among the commonest faults on a bar and the cheapest of all to fix."),
    SA("Vermouth, amari and aperitifs",
       "No aromatised wine may be sold as vermouth unless one particular botanical is present, and the German name for that plant is where the word vermouth came from. Name the plant.",
       "Wormwood",
       ["wormwood", "artemisia", "artemisia absinthium", "wormwood artemisia"],
       "Wermut is the German, and Artemisia species remain the signature bitter of the category. The rest of the recipe is wide open: a vermouth may carry anything from citrus peel and cinchona to vanilla and rhubarb, but without the Artemisia it is merely an aromatised wine."),
    SA("Vermouth, amari and aperitifs",
       "Vermouth is a wine before it is anything else, and European law fixes the band of alcoholic strength it must sit inside. What is the lower limit of that band?",
       "Fourteen and a half percent",
       ["fourteen and a half percent", "14.5 percent", "14.5%", "14.5 per cent",
        "fourteen point five percent", "fourteen and a half", "14.5", "14.5 abv",
        "14.5 percent abv", "14.5 percent alcohol", "fourteen and a half per cent",
        "at least 14.5 percent", "14.5 percent minimum"],
       "The band runs from there to twenty-two percent, and at least three quarters of the finished drink has to be wine. Below the floor it is not an aromatised wine at all, and above the ceiling it has become a bitter liqueur.",
       ex=True),
    SA("Vermouth, amari and aperitifs",
       "One style of vermouth carries a geographical indication tying it to a northern Italian city and the region around it. Name that indication.",
       "Vermouth di Torino",
       ["vermouth di torino", "vermouth of turin", "torino", "turin",
        "vermouth di torino ig"],
       "The wine must be Italian and the production must happen in Piedmont, with the Superiore tier adding that the Artemisia itself be grown there. Turin is where the commercial category began in the eighteenth century, which is why the aromatised wine trade and the Italian bitters trade grew up in the same city."),
    SA("Vermouth, amari and aperitifs",
       "A family of French aperitif wines takes its name from the bark that bitters it. Name the family.",
       "Quinquina",
       ["quinquina", "quinquinas", "quinquina aperitif"],
       "Cinchona bark supplies quinine, and these drinks were sold as a tonic against malaria long before anyone thought of them as an aperitif. Lillet, Dubonnet and Byrrh are the surviving names, and all of them are built on wine rather than on spirit."),
    SA("Vermouth, amari and aperitifs",
       "Suze and Salers draw their bitterness from the root of a yellow alpine flower rather than from cinchona or wormwood. Name that plant.",
       "Gentian",
       ["gentian", "yellow gentian", "gentian root", "gentiana lutea"],
       "The roots are dug from mountain pasture, take decades to reach a useful size and are protected in some areas as a result. The same root bitters much of the Italian aperitivo family alongside citrus peel, and it is why those drinks taste earthy rather than merely sweet."),

    # ------------------------------------------------ Classic cocktail families (6)
    Q("Classic cocktail families",
      "An order comes in for a drink of spirit, vermouth and bitters and nothing else, and the bartender reaches for a mixing glass rather than a shaker. What is that choice protecting?",
      ["Clarity and a heavier texture, since there is nothing in the glass to emulsify",
       "The strength, since shaking drives off alcohol as the drink warms",
       "The bitters, whose aromatics break apart under agitation",
       "The temperature, since a shaker cannot chill a drink as far as stirring can"], 0,
      "Shaking aerates and clouds, which suits a drink carrying citrus, egg or dairy and ruins one made only of spirits. Both methods chill and dilute; stirring simply does it more slowly and leaves the texture heavier."),
    SA("Classic cocktail families",
       "The earliest printed definition of a cocktail, from 1806, names a spirit, sugar, water and one thing more. What is that fourth element?",
       "Bitters",
       ["bitters", "aromatic bitters", "a dash of bitters", "cocktail bitters"],
       "That definition, printed in a New York newspaper, is why the Old Fashioned is described as the original cocktail: it is exactly those four elements and nothing else. Everything with a name of its own came later, as ingredients were added to that frame."),
    SA("Classic cocktail families",
       "Roughly a quarter of the liquid in a properly made stirred drink was never poured out of a bottle. Where did it come from?",
       "Dilution from the melting ice",
       ["dilution", "melting ice", "melted ice", "water from the ice",
        "water from melting ice", "dilution from the ice", "ice", "ice melting",
        "melting of the ice", "ice melt"],
       "Water is an ingredient in every cocktail whether the recipe lists it or not, which is why the same ratios taste different stirred for ten seconds and stirred for thirty. Serving a stirred drink short of dilution leaves it hot, closed and unbalanced."),
    SA("Classic cocktail families",
       "Rye, sugar, Peychaud's bitters and a rinse of an anise spirit make a New Orleans drink served with no ice in the glass. Name it.",
       "Sazerac",
       ["sazerac", "sazerac cocktail", "new orleans sazerac"],
       "The glass is chilled and rinsed with absinthe or a pastis, and the drink itself is built separately and strained in. It began on Cognac and moved to rye once phylloxera cut the brandy supply, which is why recipes for both survive."),
    SA("Classic cocktail families",
       "A spirit and a carbonated mixer over ice in a tall glass, with no citrus and no sugar added, belong to which family?",
       "The highball",
       ["highball", "highballs", "highball family"],
       "Length is the point: the mixer supplies most of the volume, so the drink is judged on how much soda and how much ice rather than on ounces of spirit. Add citrus and sugar and it becomes a Collins, and shake that same mixture before the soda goes in and it becomes a fizz."),
    SA("Classic cocktail families",
       "Gin, green Chartreuse, maraschino and lime in equal measures make a Prohibition-era drink revived out of a Detroit club's list. Name it.",
       "The Last Word",
       ["last word", "last word cocktail"],
       "Equal-parts building is the whole trick: a pair of assertive liqueurs balanced against gin and lime, with nothing able to dominate. The drink disappeared for decades and returned in the 2000s when a bartender found it in a recipe book from 1951."),
]
