"""Rank II rewrite - Service & Hospitality (64 questions: 23 MC, 41 short answer).

Written from the syllabus below. The imported bank was not read while writing.

Certified level, so the weight sits on judgement rather than recall: what to do
with a bottle that has been sent back twice, when a decant helps and when it
costs, what a stock count is actually feeding. Openers are varied from the start
and the subject noun is kept out of the opening clause wherever the answer is the
subject itself.
"""

from lib import Q, SA

CAT = "Service & Hospitality"
SLUG = "r2-service-hospitality"
PREFIX = "c"
RANK = "Rank II"
SOURCE = "data-questions.js"

SYLLABUS = [
    ("Glassware and stemware", 6),
    ("Sequence of service and etiquette", 7),
    ("Opening and pouring still wine", 5),
    ("Sparkling wine service", 6),
    ("Decanting judgement", 6),
    ("Service temperature", 6),
    ("Faults and guest recourse", 6),
    ("Other beverages at table", 6),
    ("Cellar and inventory management", 6),
    ("The wine list and selling", 5),
    ("Hospitality and difficult situations", 5),
]

BANK = [
    # ------------------------------------------- glassware and stemware (6) --
    SA("Glassware and stemware",
       "Filled to 50 ml for assessment and holding 215 ml to the brim, which standardised glass does competition tasting specify?",
       "The ISO tasting glass",
       ["iso tasting glass", "~iso", "iso glass", "inao glass", "iso standard glass"],
       "The ISO glass is a controlled variable rather than a fine drinking vessel. Everyone at the bench is then smelling the same volume under the same headspace."),
    Q("Glassware and stemware",
      "A wide, deeply bowled glass is reached for when Pinot Noir is poured. What is that shape doing?",
      ["Presenting a large surface of wine so delicate aromatics gather in the bowl",
       "Holding the wine several degrees cooler for longer",
       "Slowing oxidation once the wine has been poured",
       "Allowing a larger measure without appearing generous"], 0,
      "Aromatically subtle, high-acid reds gain from surface area and headspace. The narrower Bordeaux shape suits wines whose aromas need no help arriving."),
    Q("Glassware and stemware",
      "Handling a poured glass by the bowl rather than the stem creates which pair of problems?",
      ["Hand warmth raises the temperature and fingermarks obscure the appearance",
       "The glass is weakened at its thinnest point and likelier to break",
       "The wine reads as more tannic and less sweet",
       "Dissolved gas escapes faster from the surface"], 0,
      "Both matter at a tasting bench: a white climbs several degrees in a warm hand, and a smeared bowl makes clarity impossible to judge honestly."),
    SA("Glassware and stemware",
       "A glass leaves the machine carrying a faint chalky bloom. Which two-step remedy is standard before it goes to a table?",
       "Steam and polish with a lint-free cloth",
       ["steam and polish", "steam it and polish", "steaming and polishing",
        "hold it over steam then polish", "steam then polish with a cloth"],
       "Detergent bloom and water spots survive a machine cycle. Steam softens the film so linen lifts it away instead of smearing it around the bowl."),
    SA("Glassware and stemware",
       "Serious sparkling lists now pour into a tulip or a white wine glass rather than a narrow flute, chasing which quality the flute suppresses?",
       "Aroma",
       ["aroma", "aromas", "bouquet", "aromatics", "nose", "smell", "aroma and bouquet",
        "the smell of the wine"],
       "A flute shows the bead and hides everything else. Vintage Champagne is a wine before it is a spectacle, and it needs room to be smelled."),
    SA("Glassware and stemware",
       "Which residue, invisible to a guest, will flatten the mousse of a sparkling wine within seconds of the pour?",
       "Detergent left in the glass",
       ["detergent left in the glass", "detergent", "detergent residue", "soap",
        "soap residue", "soap film", "washing up liquid", "traces of detergent"],
       "Surfactants break bubble walls as they form, so a technically clean glass can kill a Champagne. It is the commonest reason a good sparkling wine looks lifeless."),

    # -------------------------------- sequence of service and etiquette (7) --
    Q("Sequence of service and etiquette",
      "The label is turned toward one person at the table before the foil is cut. Why that person?",
      ["They ordered the wine and are the only one who can confirm it is what they chose",
       "They are the eldest person seated",
       "They are seated closest to the sommelier station",
       "They are expected to settle the bill"], 0,
      "Presentation is the last cheap moment to catch a wrong vintage or a wrong producer. Once the capsule is cut the bottle belongs to the restaurant."),
    SA("Sequence of service and etiquette",
       "After the host has approved a bottle, in what order do the remaining glasses get filled?",
       "Guests first and the host last",
       ["guests first host last", "host last", "guests before the host",
        "the host is poured last"],
       "The host tastes first and drinks last. Guests are poured in turn around the table, which is one of the clearest tells of trained service."),
    SA("Sequence of service and etiquette",
       "From which side of a seated guest is a glass filled in classical restaurant service?",
       "The right",
       ["right", "right side", "right hand side", "from the right", "on the right",
        "to the right", "right of the guest", "the guests right", "right hand"],
       "Beverages go to the right, where the glassware sits, and food to the left. Working the wrong side puts an arm across the guest."),
    Q("Sequence of service and etiquette",
      "A guest tastes and says the wine is not to their liking, though nothing is wrong with it. What is the correct handling?",
      ["Take it away without argument, offer an alternative, and treat the cost as a business decision",
       "Explain that the wine is sound and ask them to persevere with it",
       "Replace it and put both bottles on the bill",
       "Ask the rest of the table to decide whether it stays"], 0,
      "Soundness is the test for a fault, but a disliked bottle is a commercial question rather than a technical one. Most of it can be recovered by the glass."),
    SA("Sequence of service and etiquette",
       "A firm young red and a fragile old one are poured across a single meal. Which goes into the glass first?",
       "The young wine",
       ["young wine", "young", "young one", "young red", "younger wine", "younger one",
        "younger red", "young wine first", "young red first", "young before old",
        "pour the young wine first", "the young wine goes first"],
       "Order protects the more delicate bottle. A firm young red after an old one flattens it, while the reverse merely flatters the young wine.", ex=True),
    Q("Sequence of service and etiquette",
      "Glasses are exchanged rather than reused when a table moves from a white to a red. What is that avoiding?",
      ["Residue of the first wine altering the second",
       "A licensing requirement covering glassware",
       "The second wine arriving at the wrong temperature",
       "A glass too small to hold a full measure"], 0,
      "Even a teaspoon of an aromatic white shows in a Pinot Noir. Where a fresh glass is impossible, a splash of the new wine is used to rinse the old one out."),
    SA("Sequence of service and etiquette",
       "Stations, tools and glassware are set in place before the first guest arrives. Which French term covers that preparation?",
       "Mise en place",
       ["mise en place", "~mise", "mis en place", "miseenplace"],
       "The phrase travels from the kitchen to the floor unchanged. A sommelier hunting for a decanter mid-service failed an hour before the doors opened."),

    # ----------------------------------- opening and pouring still wine (5) --
    SA("Opening and pouring still wine",
       "Which corkscrew, carrying a foil blade and a two-step lever, is the tool actually carried in the pocket?",
       "Sommelier knife",
       ["sommelier knife", "sommeliers knife", "waiters friend", "waiter s friend",
        "wine key"],
       "The second notch on the lever is what makes it work, letting a long cork come out in two controlled stages rather than one wrenching pull."),
    Q("Opening and pouring still wine",
      "Cutting the capsule below the lower lip rather than above it prevents what?",
      ["Wine touching foil on its way into the glass",
       "The cork breaking apart inside the neck",
       "The label tearing when the bottle is presented",
       "Sediment being stirred back into suspension"], 0,
      "Old lead capsules made this a health point and modern ones make it a question of taste and tidiness. The cut also looks deliberate rather than hacked."),
    Q("Opening and pouring still wine",
      "The worm has entered off-centre and the cork is beginning to tear. What is the least damaging recovery?",
      ["Ease off, re-angle the worm down the same channel, and lift slowly and straight",
       "Push the cork into the bottle and pour at once",
       "Drive the worm all the way through and pull hard",
       "Warm the neck of the bottle to loosen the cork"], 0,
      "Speed is what destroys a cork. Re-angling within the existing hole keeps the remaining cork whole instead of drilling a second channel through it."),
    SA("Opening and pouring still wine",
       "A fifty-year-old cork crumbles at the first turn of the worm. Which two-pronged extractor exists for exactly this?",
       "The Ah-So, or butlers friend",
       ["ah so", "butlers friend", "butler s friend", "two pronged puller",
        "twin prong extractor"],
       "The blades slide down either side of the cork and grip it whole, which is the only chance with a cork a worm would simply pulverise."),
    SA("Opening and pouring still wine",
       "The pour is finishing and a drop is about to run down the shoulder. Which movement of the bottle prevents it?",
       "A twist of the bottle as it is lifted",
       ["a twist of the bottle as it is lifted", "twist of the bottle", "twist the bottle",
        "twisting the bottle", "rotate the bottle", "rotating the bottle",
        "turn the bottle", "twist", "twist of the wrist", "turn of the wrist",
        "twist and lift"],
       "A small turn as the neck comes up carries the last drop back over the lip. A serviette in the other hand covers whatever the turn misses."),

    # ------------------------------------------- sparkling wine service (6) --
    SA("Sparkling wine service",
       "With a thumb held over the cork, the wire cage is loosened. How many half-turns does the loop conventionally take?",
       "Six half-turns",
       ["six", "6", "six half turns", "6 half turns", "half a dozen",
        "half a dozen turns", "six turns"],
       "Six is close to universal across producers, which is why a trained hand can loosen a cage without looking at it. The thumb never leaves the cork while the wire is worked."),
    Q("Sparkling wine service",
      "A thumb stays over the cork from the instant the cage is loosened. What is that guarding against?",
      ["A cork leaving under roughly six atmospheres of pressure",
       "The wire scratching the label",
       "Wine foaming over the lip of the bottle",
       "The bottle warming in the hand"], 0,
      "The pressure is comparable to a heavy vehicle tyre and the cork gives no warning. Eye injuries from sparkling corks are reported every year."),
    SA("Sparkling wine service",
       "A loud report and a plume of foam mark a badly opened sparkling bottle. Which sound should the opening aim for?",
       "A soft sigh",
       ["~sigh", "soft sigh", "quiet sigh", "~whisper", "gentle sigh"],
       "The bang is escaping gas that ought to have stayed dissolved in the wine. A controlled release leaves the mousse where the guest can drink it."),
    Q("Sparkling wine service",
      "Filling a flute in two stages rather than one achieves what?",
      ["The first foam subsides so a full measure fits without overflowing",
       "The wine picks up useful oxygen between the two pours",
       "The wine is held closer to its serving temperature",
       "Pressure in the bottle is reduced for the next pour"], 0,
      "A single pour into a cold, narrow glass is almost all head. A small pour, a pause, then the rest, and the glass ends correctly filled to about two thirds."),
    SA("Sparkling wine service",
       "Tilting the glass and pouring down its inner wall does what for a sparkling wine?",
       "Preserves the mousse",
       ["preserves the mousse", "preserve the mousse", "mousse", "keeps the mousse",
        "preserves the bubbles", "keeps the bubbles", "keep the bubbles",
        "reduces foaming", "less foam"],
       "Bubbles break where wine strikes a flat surface hard. Down the side, more gas stays in solution and the wine keeps its texture as well as its look."),
    SA("Sparkling wine service",
       "An unfinished bottle of Champagne has to hold its pressure overnight. Which closure does that job?",
       "A clamping sparkling wine stopper",
       ["champagne stopper", "sparkling wine stopper", "clamping stopper",
        "pressure stopper", "champagne sealer"],
       "A sprung clamp grips the lip of the bottle and holds several atmospheres. The teaspoon in the neck is folklore and does nothing whatever."),

    # ---------------------------------------------- decanting judgement (6) --
    SA("Decanting judgement",
       "A bottle has lain on its side for thirty years and is on tonight's order. What should have been done to it yesterday?",
       "Stood upright a day before service",
       ["stood upright a day before service", "stood upright", "stand upright",
        "stand it upright", "stood it upright", "store it upright", "stored upright",
        "upright", "standing upright", "left standing upright", "upright for a day",
        "stand it up", "stood it up", "stand the bottle upright"],
       "Sediment lying along the flank of a bottle cannot be decanted cleanly. A day standing pulls it into the punt, where a careful pour can leave it behind."),
    Q("Decanting judgement",
      "Two decants, a young Barolo and a 1971 Burgundy, differ in handling how?",
      ["The young wine is poured hard and left to open; the old one is poured gently and served straight away",
       "Both are poured hard and rested for an hour before service",
       "The old wine is poured hard and the young one gently",
       "Neither is poured until the wine has reached room temperature"], 0,
      "One decant is for air and the other is for sediment, and they call for opposite handling. A fragile old wine can fall apart in the decanter within twenty minutes."),
    SA("Decanting judgement",
       "A light is set under the neck of the bottle during a decant. What is the server watching for?",
       "Sediment reaching the neck",
       ["sediment reaching the neck", "sediment", "deposit", "sediment in the neck",
        "sediment reaching the shoulder", "deposit approaching the shoulder",
        "the sediment moving up", "sediment coming up the neck",
        "the deposit reaching the neck"],
       "A candle is traditional and a phone torch does the same work. The pour stops the moment the cloud arrives at the shoulder, and the last inch stays behind."),
    Q("Decanting judgement",
      "A fifteen-year-old Rioja Gran Reserva is ordered and the table asks whether it wants a decanter. Which reply is soundest?",
      ["Taste it first: decant if it is closed, pour from the bottle if it seems fragile",
       "Decant anything older than ten years as a matter of policy",
       "Never decant Spanish wine, since it has already had long cask ageing",
       "Decant only when a guest specifically asks for it"], 0,
      "Age alone settles nothing. Gran Reserva has usually spent years in cask and may be perfectly open already, in which case air costs it more than it gives."),
    SA("Decanting judgement",
       "Bottled unfiltered and throwing a heavy crust, which fortified wine is decanted as a matter of routine?",
       "Vintage Port",
       ["vintage port", "vintage ports", "vintage porto", "unfiltered vintage port",
        "crusted port", "vintage port and crusted port"],
       "The crust forms because the wine goes into bottle young and unfiltered. Tawny, aged in cask and filtered before bottling, needs nothing of the kind.", ex=True),
    SA("Decanting judgement",
       "Which piece of equipment sits in the neck of the decanter to catch cork fragments and coarse deposit?",
       "A decanting funnel",
       ["decanting funnel", "~funnel", "wine funnel", "decanter funnel",
        "funnel with a screen"],
       "The better ones carry an angled spout that runs wine down the wall of the decanter rather than dropping it into the middle, which suits a fragile old red."),

    # ---------------------------------------------- service temperature (6) --
    SA("Service temperature",
       "Ice alone chills a bottle slowly and unevenly. What else goes into the bucket?",
       "Water",
       ["water", "cold water", "ice and water", "water and ice", "ice water",
        "water in the bucket", "half water"],
       "Air between cubes insulates, so dry ice cubes touch only a fraction of the glass. Half ice and half water chills several times faster."),
    Q("Service temperature",
      "The red has stood by the pass all evening and now tastes hot and blurred. What is the remedy?",
      ["A few minutes in ice to bring it back toward sixteen degrees",
       "A hard decant to drive off some of the alcohol",
       "An ice cube dropped into each glass",
       "A second bottle opened and blended with the first"], 0,
      "Above about eighteen degrees alcohol dominates and definition disappears. Five minutes in a bucket rescues a wine that had seemed faulty."),
    Q("Service temperature",
      "Serving a fine white straight out of a full ice bucket costs the guest what?",
      ["Most of its aroma and much of its texture",
       "Its acidity, which cold strips away",
       "Its colour, which fades at low temperature",
       "Its alcohol, which evaporates in the bucket"], 0,
      "Aromatic compounds need warmth to volatilise, so a serious white shows least at four degrees. A bucket is for holding a temperature, not for reaching one."),
    SA("Service temperature",
       "Cold hardens one structural component of a red and mutes the aromatics. Which component turns harsher?",
       "Tannin",
       ["~tannin", "~tannins", "~astringency", "~tannic grip"],
       "The same bottle at ten degrees and at sixteen can seem to be two wines. An over-chilled red reads as tough and bitter when nothing at all is wrong with it."),
    SA("Service temperature",
       "Which two Sherry styles are served as cold as a white wine and treated as perishable once opened?",
       "Fino and Manzanilla",
       ["fino and manzanilla", "manzanilla and fino", "fino manzanilla",
        "manzanilla fino", "fino and manzanilla sherry"],
       "Both age under flor and are bottled at modest strength, so they oxidise much as a table wine does. A bottle open for a week has nothing left worth selling.", ex=True),
    SA("Service temperature",
       "A restaurant with no cellar keeps its reds in a kitchen at twenty-two degrees. Which single purchase most improves service?",
       "A temperature-controlled wine cabinet",
       ["wine cabinet", "wine fridge", "temperature controlled cabinet",
        "wine refrigerator", "climate controlled cabinet"],
       "Wine stored warm is tired before it is opened, and no amount of ice at the table undoes that. Storage decides more about a bottle than service ever can."),

    # --------------------------------------- faults and guest recourse (6) --
    SA("Faults and guest recourse",
       "Damp cardboard on the nose and fruit that has gone quiet point to a taint. Name the compound usually responsible.",
       "TCA, or 2,4,6-trichloroanisole",
       ["~tca", "trichloroanisole", "2 4 6 trichloroanisole", "trichloranisole"],
       "TCA suppresses fruit long before it smells of anything itself, so a merely dull bottle may be lightly tainted. Cellar timber can carry it as readily as a cork."),
    SA("Faults and guest recourse",
       "A wine smelling of struck match and drains cleans up after ten minutes in the glass. Which condition explains it?",
       "Reduction",
       ["~reduction", "~reductive", "~reduced", "sulphur compounds"],
       "Volatile sulphur compounds form where a wine has seen too little oxygen. Because air disperses them, a decant is a diagnosis as much as a treatment."),
    Q("Faults and guest recourse",
      "The same wine has been returned twice as corked and both bottles taste sound to you. What is the professional response?",
      ["Replace it again without argument and raise the pattern with management afterwards",
       "Explain in detail why the guest is mistaken",
       "Charge for both bottles and say nothing further",
       "Decline to open a third bottle of anything"], 0,
      "Nothing is won by litigating at the table. Two sound bottles rejected is a commercial matter for later, and often a guest who dislikes the style rather than the bottle."),
    SA("Faults and guest recourse",
       "Sticking plaster, barnyard and a flattening of fruit across a producer's whole range point to which spoilage organism?",
       "Brettanomyces",
       ["brettanomyces", "brett", "dekkera", "brettanomyces bruxellensis"],
       "The yeast produces 4-ethylphenol and 4-ethylguaiacol. Small amounts divide opinion, and at higher levels every wine in a range starts to smell the same."),
    Q("Faults and guest recourse",
      "A bottle arrives with wine seeping past the capsule and a fill level well down the shoulder. What does that suggest?",
      ["Heat damage or a failed seal at some point in storage or transit",
       "A wine deliberately aged under a veil of flor",
       "Ordinary evaporation in any bottle over five years old",
       "A mark of quality in mature Bordeaux"], 0,
      "Wine expands when it gets hot and forces its way past the cork. Some ullage is normal in a very old bottle, but a sticky capsule and fresh seepage are not."),
    SA("Faults and guest recourse",
       "Open since Monday, a by-the-glass red now tastes flat and bruised. Which process is at work?",
       "Oxidation",
       ["~oxidation", "~oxidised", "~oxidized", "oxygen exposure"],
       "Acetaldehyde builds while fruit falls away. A by-the-glass programme without gas or vacuum is selling a different wine on Thursday from the one it opened on Monday."),

    # ---------------------------------------- other beverages at table (6) --
    SA("Other beverages at table",
       "Which single property of a beer glass, ruined by grease or detergent film, decides whether the head survives the pour?",
       "Cleanliness, a beer-clean glass",
       ["beer clean glass", "cleanliness", "clean glass", "grease free glass"],
       "Any residue collapses foam as it forms, exactly as it does with sparkling wine. A glass that leaves bubbles clinging to its sides is not clean."),
    SA("Other beverages at table",
       "Ginjo and daiginjo are separated from ordinary sake by one number on the label. Which measurement is it?",
       "The rice polishing ratio, or seimaibuai",
       ["polishing ratio", "rice polishing ratio", "seimaibuai", "milling rate",
        "degree of polishing"],
       "Ginjo requires the grain milled to sixty per cent or less and daiginjo to fifty, stripping the outer layers that carry coarser flavours."),
    Q("Other beverages at table",
      "A table orders sake alongside a delicate raw fish course. Which service suits a daiginjo?",
      ["Chilled, in a small wine glass or an ochoko",
       "Heated to about fifty degrees in a tokkuri",
       "Over ice with a twist of citrus",
       "At room temperature in a large balloon"], 0,
      "Warming suits robust junmai styles and blunts a fragile one. The highly milled grades are served cold and increasingly from a stemmed glass."),
    Q("Other beverages at table",
      "Warming a brandy balloon over a flame at the table is now regarded as what?",
      ["Poor practice, since heat drives off alcohol and coarsens the aroma",
       "Essential preparation for any long-aged spirit",
       "A legal requirement for Cognac service in France",
       "The only correct treatment for an XO"], 0,
      "The hand is warmth enough, and most houses now prefer a tulip that concentrates aroma without cooking it. The flame is theatre from another era."),
    SA("Other beverages at table",
       "Served before a meal to sharpen the appetite rather than satisfy it, a drink of that kind is called what?",
       "An aperitif",
       ["~aperitif", "~apertif", "~aperitivo", "~aperatif"],
       "Dry, moderate in alcohol, often saline or bitter. Fino, dry sparkling and vermouth all work because they leave the palate hungry rather than full."),
    SA("Other beverages at table",
       "Taken after the meal and often a brandy or a fortified wine, which term applies to that drink?",
       "A digestif",
       ["~digestif", "~digestive", "~digestivo", "~after dinner drink"],
       "The category is set by its moment rather than its contents. Sweetness and strength both suit a palate that has finished eating."),

    # --------------------------------- cellar and inventory management (6) --
    SA("Cellar and inventory management",
       "Bottles are laid on their sides for a reason that applies to one type of closure only. Which closure?",
       "Natural cork",
       ["natural cork", "cork", "corks", "natural corks", "cork stopper",
        "natural cork stopper", "one piece natural cork"],
       "A cork dries and shrinks in an upright bottle and eventually lets air past. Synthetic and screwcap closures cannot dry out, so the practice does nothing for them.", ex=True),
    SA("Cellar and inventory management",
       "A cellar holds steady temperature and humidity, yet bottles stored beside the loading bay age badly. Which overlooked factor is likely?",
       "Vibration",
       ["~vibration", "~vibrations", "~movement", "~shaking"],
       "Constant low-level movement keeps sediment in suspension and is widely held to disturb a wine's development. Compressors, lifts and loading doors are the usual sources."),
    Q("Cellar and inventory management",
      "Stock is counted and valued at the close of each period. Which figure does that count feed directly?",
      ["Cost of goods sold, and from it the beverage cost percentage",
       "The service charge distributed to staff",
       "The corkage rate charged to guests",
       "The number of covers served"], 0,
      "Opening stock plus purchases minus closing stock gives what was actually consumed. Without a count, cost of sales is a guess and so is every margin built on it."),
    SA("Cellar and inventory management",
       "Every listed wine has a minimum quantity below which it must be reordered. What is that quantity called?",
       "The par level",
       ["par level", "~par", "par stock", "minimum par"],
       "Par is set from how fast a wine sells and how long the supplier takes to deliver. Set high it ties up cash, set low it puts the wine off the list."),
    SA("Cellar and inventory management",
       "The oldest stock of a wine leaves before the newest delivery does. Which four-letter principle is that?",
       "FIFO, first in first out",
       ["fifo", "first in first out", "stock rotation", "oldest sold first"],
       "It matters most for beer, an open by-the-glass range and anything with a drink-by window. In a cellar of ageworthy reds the reverse is often deliberate."),
    Q("Cellar and inventory management",
      "A case of a listed wine has not moved in eighteen months. What is the standard remedy before it becomes dead stock?",
      ["Show it by the glass or in a flight, and get the floor staff tasting and selling it",
       "Write the whole case off at once",
       "Raise its price so it reads as a serious bottle",
       "Return it to the supplier for a credit"], 0,
      "Dead stock is cash sitting on a shelf. Most slow wines are slow because nobody on the floor has tasted them and can say anything true about them."),

    # --------------------------------------- the wine list and selling (5) --
    Q("The wine list and selling",
      "Pricing every bottle at the same multiple of its cost produces which distortion?",
      ["The expensive end becomes unsellable while the cheap end earns too little cash",
       "The cheap end becomes unprofitable and the expensive end subsidises it",
       "Regional balance across the list collapses",
       "Margins by the glass fall below margins by the bottle"], 0,
      "Most lists slide the multiple downward as cost rises, so a fine bottle carries a larger cash margin at a smaller percentage. A flat multiple prices the best wines off the list."),
    SA("The wine list and selling",
       "Bringing their own bottle, a guest is charged for the glassware, the service and the lost sale. Name that charge.",
       "Corkage",
       ["~corkage", "corkage fee", "~corkage charge", "byo fee"],
       "It is a policy rather than a rule, and it works best stated plainly on the list. Waiving it for a bottle the restaurant does not stock buys a great deal of goodwill."),
    SA("The wine list and selling",
       "Which single ratio, cost divided by selling price, does management watch to judge a beverage programme?",
       "Beverage cost percentage",
       ["beverage cost percentage", "pour cost", "cost percentage", "beverage cost"],
       "It is read as a trend rather than as a target. A programme selling more fine wine at a lower percentage can be more profitable in cash than one hitting its number."),
    Q("The wine list and selling",
      "Recommending a bottle well below the price a table has named tends to produce what over a season?",
      ["Trust, return visits and a larger total spend",
       "A reputation for a weak and cautious list",
       "An immediate loss the restaurant cannot recover",
       "Guests who order nothing else for the rest of the meal"], 0,
      "Selling to a budget rather than above it is the durable strategy. A guest who feels worked over remembers that longer than they remember the wine."),
    SA("The wine list and selling",
       "Wines poured by the glass sit half-empty for days. Which gases are used to hold them?",
       "Argon and nitrogen",
       ["argon and nitrogen", "argon", "nitrogen", "inert gas", "argon or nitrogen"],
       "Argon is denser than air and blankets the surface, while nitrogen displaces the oxygen above the wine. Vacuum systems attack the same problem by removing the headspace."),

    # ---------------------------- hospitality and difficult situations (5) --
    Q("Hospitality and difficult situations",
      "A regular guest is visibly intoxicated and orders another bottle. What does the sommelier do?",
      ["Decline the sale courteously, offer food and water, and help arrange transport",
       "Serve it, since the guest is well known to the house",
       "Serve a cheaper wine at the same price",
       "Take the order and let the kitchen delay it"], 0,
      "Refusing service is a legal duty in most jurisdictions and a duty of care everywhere. Done quietly and without an audience, it rarely costs the relationship."),
    Q("Hospitality and difficult situations",
      "Asked about a wine they genuinely do not know, which response serves the guest best?",
      ["Say so, then find out and come back with a real answer",
       "Improvise a plausible description from the region and grape",
       "Steer the conversation toward a wine they do know",
       "Hand over the list and let the guest decide alone"], 0,
      "Guests forgive not knowing and remember being misled. The recovery, made quickly, usually reads as more expert than a smooth invention would."),
    SA("Hospitality and difficult situations",
       "Which French term names the trolley or side table used for finishing and serving beside the guest?",
       "The gueridon",
       ["gueridon", "gueridon trolley", "gueridon table", "service trolley"],
       "Decanting, carving and flaming all happen there rather than on the guest's own table. It keeps the work visible without putting equipment among the plates."),
    SA("Hospitality and difficult situations",
       "One glass of a 1990 first growth is wanted with the rest of the bottle left intact. Which device makes that possible?",
       "A Coravin",
       ["~coravin", "coravin system", "argon needle device", "needle and argon system"],
       "A fine needle passes through the cork, argon replaces what is drawn out, and the cork reseals behind it. It changed which bottles a list can sensibly open."),
    SA("Hospitality and difficult situations",
       "Which phrase describes service that meets a need before the guest has voiced it?",
       "Anticipatory service",
       ["anticipatory service", "anticipation", "anticipatory", "reading the table"],
       "Water refilled unasked, a glass changed before the next wine arrives, a chair steadied. It is the difference between a table being served and a table being looked after."),
]
